### ISSUE TITLE
Beautified Table - by 10am MT May 22nd

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#1000]
Table providing info on three different tech learning tools - needs to show a screenshot of each tool, some info/refs on each, and the accessibility features of each in an aesthetically pleasing way. 

Content not yet complete, draft here: [TableFig.pptx](https://github.com/phetsims/tasks/files/3197726/TableFig.pptx)

**Comment by DianaTavares** [comment]
Hi Emily! i am going to work in this artwork!
What size do you want the table? Do you want that I use the pictures in the file?

**Comment by emily-phet** [comment]
@DianaTavares Thanks for taking this on!

I poked around for an example that might serve as inspiration. This is a nice example of something that doesn't "feel" like a table...which is what i'm hoping for.
<img width="256" alt="Screen Shot 2019-05-20 at 12 15 28 PM" src="https://user-images.githubusercontent.com/5109055/58039755-4c79b200-7af9-11e9-82a8-8b820049e687.png">

This will be put into a pdf document with no page limit, so it can be as large as ~1/3 of a standard page.

**Comment by DianaTavares** [comment]
this are the first drafts (I use the same text about PhET in the three columns only to see how it looks with more text). I think that helps when the pictures are the same size.

![Screen Shot 2019-05-20 at 1 59 17 PM](https://user-images.githubusercontent.com/26031501/58048258-8fdb1d00-7b07-11e9-9f63-d0d8a5d63139.png)

I am not very sure it the table need extra lines to differentiate the columns:

![Screen Shot 2019-05-20 at 1 59 08 PM](https://user-images.githubusercontent.com/26031501/58048240-85b91e80-7b07-11e9-96a8-a5f1068861d0.png)

Do you also want that I play with colors and font size? 
![Screen Shot 2019-05-20 at 2 01 54 PM](https://user-images.githubusercontent.com/26031501/58048394-eb0d0f80-7b07-11e9-8598-7a15a21e563a.png)

**Comment by emily-phet** [comment]
@DianaTavares Thanks! These look great...I think all black text, with the vertical lines separating each one, and (additionally) a very thin, short horizontal line separating the text details from the display features checklist would be nice.

Which software did you used to make this? Now that you have it all laid out nicely, I could probably adapt the file directly as the final content gets added, or just make a variation in Powerpoint.

**Comment by DianaTavares** [comment]
It is PowePoint 
here is the file: 
[EmilyTable.pptx](https://github.com/phetsims/tasks/files/3199693/EmilyTable.pptx)

Here is the picture withe horizontal lines: 
![Screen Shot 2019-05-20 at 2 20 06 PM](https://user-images.githubusercontent.com/26031501/58049611-7e474480-7b0a-11e9-823e-4fd14b597b85.png)

**Comment by emily-phet** [comment]
Perfect! Thanks. I can take it from here.

**Comment by DianaTavares** [comment]
Good! then I am going to close the issue. You can open it again if you need that I help more!
