### ISSUE TITLE
Download and re-upload .gdoc files in phet-storage

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1003]
KP noticed that some files seem to be tricky to access and they are files that have the .gdoc file extension in phet-storage google drive.

To clean up, the files need to be downloaded and re-uploaded to phet-storage.
To find files, search "*.gdoc" in phet-storage google drive.
(You may need to clear your browser cache to download the files)

**Comment by arouinfar** [comment]
@oliver-phet much of phet-storage is being migrated to phet-research. IRB-protected research data should not be downloaded and re-uploaded as it will seriously set back the migration progress.

**Comment by oliver-phet** [comment]
@arouinfar Are the files you are migrating being deleted from phet-storage after migration? We can defer on this issue until that is done.

**Comment by arouinfar** [comment]
Ownership is being transferred to phet-research, files are then reorganized within the phet-research Drive structure, and then will be eventually unshared with phet-storage.

**Comment by oliver-phet** [comment]
Assigning to you, @arouinfar - update the issue when that phet-research migration is done and I'll get going on this.

**Comment by arouinfar** [comment]
@oliver-phet, searching phet-storage for *.gdoc files results in only 69 files. None of these files are research-related, and only 4 of these files are owned by phet-storage. The rest are owned by the deprecated phetstorage account.

Most of these files appear to be related to Teacher Primers. Not sure why these files are even on phet-storage, as Teacher Primer files are all stored in phet-docs under PhET Files > PhET Teaching Resources > [Teacher Primers](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYRFZZYTdmVWY5Z28).

**Comment by oliver-phet** [comment]
I verified that these files are all on phet-docs. Closing.
