### ISSUE TITLE
ISTE 2019 video

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tasks#1004]
This includes the previous year's video.  Please look and request and changes.
https://drive.google.com/drive/folders/1JulUuWxjCKvx3WsRfw8jbjAofXf6vlrZ

**Comment by arouinfar** [comment]
@KatieWoe I'm only seeing an a11y-specific video in that folder. Is there a more general video too?

**Comment by KatieWoe** [comment]
Right, sorry.  That was the latest ISTE video I found.  I'll dig deeper.

**Comment by amanda-phet** [comment]
I see conference videos here: https://github.com/phetsims/phet-info/tree/master/conferences 

The ISTE_2017 video looks fine to me.

**Comment by oliver-phet** [comment]
@KatieWoe can you add CCK and EFaC to the ISTE 2019 rotator video and re-upload to phet-info?

**Comment by KatieWoe** [comment]
New 2019 ISTE video: https://github.com/phetsims/phet-info/blob/master/conferences/ISTE_2019.mp4
