### ISSUE TITLE
Conference Email collection form

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1005]
@chrisklus is making a simple webpage that can be loaded on any computer for users at conferences to type in their email. We can then email these users after the conference to remind them of PhET, encourage them to sign up for a website account, etc.

**Comment by chrisklus** [comment]
I've finished and committed the utility. It lives here: https://github.com/phetsims/phet-info/blob/master/conferences/collect-emails.html. Navigate to it in your file system, then simply double click to open in your browser.

Description and instructions, copied directly from the file header:

```
This is an email gathering utility intended for offline usage at PhET conferences. Because offline support is a
requirement, acquired emails are saved to localStorage instead of a remote database.

The email list is stored via a key in localStorage, see PHET_MORE_INFO_EMAILS_STRING below. To view emails saved
on the current device, add the query parameter flag `showEmails` to the URL of this file. I recommend copying them to
another destination at the end of each conference booth session.

To delete the saved email list from the current device, click the 'delete emails' button while viewing the list of
emails. If the email list is deleted by mistake, it is available for recovery via a backup key in localStorage, see
PHET_MORE_INFO_EMAILS_BACKUP_STRING below. The backup list includes all emails that have ever been saved to the current
device (since the cache was last cleared), not just the emails saved since the most recent deletion within this app. To
view the backup list, open a console in your browser and enter
`JSON.parse( localStorage.getItem( {{PHET_MORE_INFO_EMAILS_BACKUP_STRING}} ) );`. The double braces indicate that you
need to fill in the value from below, e.g. `JSON.parse( localStorage.getItem( 'phet-more-info-emails-backup' ) );`.

NOTE/TODO: For some reason, when opening a new tab, localStorage in the console doesn't contain any saved data
(including the backup) until this utility is run in the tab. Then, the backup and any saved emails become available.

Developed and tested on Mac OS + Google Chrome.
```

@oliver-phet can you review and test?

**Comment by oliver-phet** [comment]
This is working great, thanks @chrisklus !

**Comment by oliver-phet** [comment]
A few enhancements we'd like:

- Pressing [Enter] submits the form
- The email text box always has "focus" so that users don't need to click inside of it to start typing

**Comment by chrisklus** [comment]
I've added a few enhancements. Changes include:

* submit the form via [enter] or button press
* text input receives focus on page load and after successful form submission
* text input resizes responsively and has x-padding for smaller devices
* style improvements
* "Learn more about PhET!" added as the tab title so people viewing sims in the same browser know what the page is for

I looked these over with @oliver-phet, so I think we can close here. Anyone feel free to reopen if more work is needed.
