### ISSUE TITLE
Get @brandonLi8 access to bayes

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tasks#1006]
@brandonLi8 and I have been trying to set up his RSA key on bayes so that he can publish a dev version for vector addition. When he tries to login, the server responds with "Connection closed", so I'm assuming his identikey needs to be added for him to have access.

![image](https://user-images.githubusercontent.com/5618316/60616799-8d6b1480-9d8f-11e9-9edb-66cef302833e.png)

@mattpen could you check this out?

**Comment by mattpen** [comment]
I've added Brandon to the appropriate admin group, he should be able to logon now.  Let me know if he has trouble running sudo or needs to be added to the `phet` group.

**Comment by chrisklus** [comment]
@brandonLi8 able to publish dev versions, thanks @mattpen!
