### ISSUE TITLE
Certificate for Lairane to visit PhET

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1007]
> Thanks again for your positive response. I’m really excited to start volunteering with you guys.
> 
> I will need an official confirmation from you in advance. This is required for my temporary work leave in Brazil. A letter confirming your acceptance with the volunteering location, start and end dates would be sufficient. The period is from October 1  to December 30, 2019.
> 
> By completing the volunteering, I will also need a simple certificate from you to confirm my program abroad.

**Comment by ariel-phet** [comment]
Letter sent to Oliver, it sounds like Lairane might need something else to bring back, but we can discuss after she gets here. Closing.
