### ISSUE TITLE
Graphic for Description Framework

### ISSUE THREAD

**Issue by terracoda** [phetsims/tasks#1008]
I need a high resolution graphic for a manuscript submission. 
The manuscript is due in mid September, so no immediate rush.

I have made a sketch of the graphic. 
![Sketch7-Framework_web](https://user-images.githubusercontent.com/1902116/61944546-33c8c500-af9e-11e9-8312-63bf1be0d625.jpg)

The colors are important as they need to kind of match the colors we use in a second figure:
![fig02-pdom-4col-riaw-no-HH](https://user-images.githubusercontent.com/1902116/61944662-8a360380-af9e-11e9-87d3-63dfdb8d56ee.png)

It would be great if the graphic is made in Illustrator (SVG), so I have access to adjust the labels and colors of needed.

The intended width of the graphic will be to fit in a single column of text, no more than 3.5 inches wide and I will need to export it to a printing resolution of 300 dpi.

**Comment by terracoda** [comment]
I would add that the circles could be filled in with color with some kind of accentuation of the over-lapping areas.

@emily-phet, do you have anything (any details) to add?

**Comment by emily-phet** [comment]
@terracoda I agree the color coding is important, to help people see the relationship between these two figures. I'm not sure filled circles will work, since they overlap (and what color would it be at the overlap?) so let's definitely have a version where the circle stroke has a color. Not opposed to trying out filled circles as a second option, though. 

I don't have any other suggestions at the moment.

@ariel-phet please assign to an artist/designer.

**Comment by DianaTavares** [comment]
I am going to work on the design starting next week. Thanks for the sketch and yes, I am going to consider the color-coding!

**Comment by DianaTavares** [comment]
Here is the first draft. The size is 3.5 X 2.6 inches. Let me know what do you think! 

![Graph-Description-Framework-02](https://user-images.githubusercontent.com/26031501/62495615-aa7e7300-b793-11e9-9508-f235ed5d960f.png)

**Comment by terracoda** [comment]
@DianaTavares, thanks, apologies for the delay. This looking really good. I have to think about the colours and the fonts.

I want the 4 colours to be clearly different, and I want the areas "Current State" and "Relevant Changes" to kind of be different some how.

**Comment by DianaTavares** [comment]
@terracoda I am going to be on vacation until the 26. I am going to send you the .ia file by email if you want to play with the fonts and colors. After 26 I can help you again with the design as needed.

**Comment by terracoda** [comment]
@DianaTavares, thanks for sending me the .ai file. I adjusted the type styles a little and added filled circles. I am not yet happy with the colors (need to check for accessibility still).

I have a question. You have more than one artboard in the file. How do I export into a hi-res png just a single art board. I have the column diagram in another .ai file and I do not need it in this file.

**Comment by terracoda** [comment]
Here's my updated figure:
![framework-figure-filled-colors](https://user-images.githubusercontent.com/1902116/64377997-4820c880-d006-11e9-90ec-255a1e9385fb.png)

What do you think of the type?

I am trying to communicate 2 main categories that are accessed in different ways
- State Descriptions (reading - skimming and scanning)
- Responsive Descriptions (interacting with actual objects and making changes)

And then, each main category has 2 types of descriptions that are represented by 2 pairs of circles.

The pairs of circles overlap to provide:
- the current state
- the relevant changes

The user goes back and fourth between accessing the current state and hearing relevant changes to receive the full STORY.

In your opinion does the type communicate these things (big main headings, non-italicized labels, and italicized labels)?

**Comment by terracoda** [comment]
I will email the file back to you, so you have the updated one.

**Comment by emily-phet** [comment]
@terracoda Regarding draft in https://github.com/phetsims/tasks/issues/1008#issuecomment-528569905, I really like the updated typology. One small suggestion regarding font would be to try tweaking so that "Current State" and "Relevant Changes" are highlighted a little bit more. Maybe slightly larger font, or slightly thicker stroke. I didn't realize for a moment that they were bolded (which is odd in hindsight, since they're clearly bolded...but you know how it is with perception!). 

Regarding color, I love what's happening on the responsive descriptions side, with the yellow/red/orange. The "Relevant Changes" union section really pops! If there were a way to get that same effect for the state descriptions side, that would be ideal. The blue/green combo may be hard...but perhaps one thing to try would be making the "Current State" section a little bluer (or little greener?) - just playing around with that to see if something "pops" a bit more. 

Overall, it's a really beautiful graphic!

**Comment by DianaTavares** [comment]
> I have a question. You have more than one artboard in the file. How do I export into a hi-res png just a single art board. I have the column diagram in another .ai file and I do not need it in this file.

Hi @terracoda,
At the top of Illustrator, click on "File" and then select "export". In the window that appears:
1. Select in what format you want to save the picture
2. Select "Use Artboards"
3. Select "Range" and write the number of the artboard that you want to import (in case that is only one or a couple of artboards but not all of them).

![Screen Shot 2019-09-05 at 5 37 44 PM](https://user-images.githubusercontent.com/26031501/64388403-97fe9000-d004-11e9-93d1-25123265cc14.png)

After you click "export" in that window, another window is going to show up. There is where you select the resolution (a) and if you want the background white or transparent (b):

![Screen Shot 2019-09-05 at 5 43 32 PM](https://user-images.githubusercontent.com/26031501/64388550-0a6f7000-d005-11e9-9ae1-c613cd05a37d.png)

Nice improvements in the design! I will think about ideas for the colors. I will let you know when I have a suggestion

**Comment by terracoda** [comment]
One last go before I sleep ;-)
I used the following colors in this version.
- Blue `#5BB8E8` - 100% and 30% opacity
- Light Green `#33B44E` at 30% opacity for filled circle
- Darker Green stroked circle `#2C993E` 100% opacity
- orange and yellow are the sam as in your file

![Screen Shot 2019-09-05 at 8 35 08 PM](https://user-images.githubusercontent.com/1902116/64389407-1bc47680-d01d-11e9-869d-12cf045c07a1.png)

**Comment by terracoda** [comment]
Here's a handy color tool in case you need  it.
[http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3](http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3)

**Comment by DianaTavares** [comment]
Thanks @terracoda. I am finishing today too, I will play with it tomorrow!

**Comment by terracoda** [comment]
Ok, sounds good @DianaTavares, I will work on the writing of the paper tomorrow :-) and leave the color iterations to you :-)

**Comment by DianaTavares** [comment]
One first idea was to take out the circles' strokes.  I feel that they take a lot of attention because they are bigger than the text. Also, with the strokes, the color combination of the green and blue doesn't make a contrast, but without the strokes, it looks better. 

![image](https://user-images.githubusercontent.com/26031501/64467776-af5f7b00-d0e1-11e9-89d5-d6981bd117a7.png)

I am going to continue playing with the colors to have more contrast

**Comment by terracoda** [comment]
@DianaTavares, I really like the graphic without the strokes. It is a great idea to remove those.

Do you have any experience with testing the contrast of colors for people with colorblindness? There are free tools available. 

Most of my experience is in choosing background colors that provide a high enough contrast with any over-layed text. I have less experience with actually ensuring each color is distinguishable.

**Comment by DianaTavares** [comment]
Hi @terracoda, I tried the two options that Illustrator includes for colorblindness: protanopia (blindness to red picture 1) and deuteranopia(blindness to green picture 2). This are the results: 
![Screen Shot 2019-09-09 at 10 52 13 PM](https://user-images.githubusercontent.com/26031501/64582932-cf4aa500-d354-11e9-86f7-7bfbb73e168e.png)

![Screen Shot 2019-09-09 at 10 52 25 PM](https://user-images.githubusercontent.com/26031501/64582935-d1146880-d354-11e9-8369-3e0c2c2152d9.png)

with grayscale looks like this:
![Screen Shot 2019-09-09 at 10 52 59 PM](https://user-images.githubusercontent.com/26031501/64582954-de315780-d354-11e9-8669-6df0f776bf09.png)

I think that the colors provide enough contrast. What do you think?

**Comment by terracoda** [comment]
Not bad, but could you try tweaking the blue and green, if possible making
- the green more different from the red in the protanopia (blindness to red) (picture 1)
- the blue and green more different in the greyscale

I do not know anything about colors to make this happen.
Can you ask @amanda-phet to see what she thinks?

**Comment by emily-phet** [comment]
Hey folks - I think we're getting a little off track here. I think if we add the lines back in, people will get that there is a relevant union happening, regardless of color. For this figure, and others throughout the paper, the different colored regions will be labeled. 

I think we want to maximize the color cueing (that the different description types blend to make something new) for those that can distinguish color reasonably well. For those that cannot distinguish colors well, that cueing is unlikely to come through anyway. Does that make sense? i.e., In my opinion, we're not going to be able to find colors that cue this idea for everyone, but the text will be able to do some of that work.

**Comment by terracoda** [comment]
@emily-phet, I can see how the lines help will help with defining the overlaps, maybe thinner ones would be bit more subtle, but still define the overlaps.

**Comment by DianaTavares** [comment]
Ok! Then this is the comparison of the pictures with a stroke of 1pt and the original that was 2 pt (using the original colors):

>I used the following colors in this version.

>Blue #5BB8E8 - 100% and 30% opacity
Light Green #33B44E at 30% opacity for filled circle
Darker Green stroked circle #2C993E 100% opacity
orange and yellow are the same as in your file

![image](https://user-images.githubusercontent.com/26031501/64634651-546ca300-d3c3-11e9-9a33-9820076ba0d7.png)

I realize that I have been using a darker blue color with more opacity ( `00B3BE` at 50%) This is the version using that blue with 1pt stroke:

![image](https://user-images.githubusercontent.com/26031501/64634870-da88e980-d3c3-11e9-94d9-ae900f660046.png)

With that opacity is hard to see the strokes. I made this version with 30%
![image](https://user-images.githubusercontent.com/26031501/64634977-29368380-d3c4-11e9-9791-463c9e0dcddb.png)

In my opinion, my favorite one is the original colors with a stroke of 1pt (the first picture). this is the contrast with the colorblindness filters for that picture:

![image](https://user-images.githubusercontent.com/26031501/64635047-5daa3f80-d3c4-11e9-9b01-64e46f9e2340.png)

![image](https://user-images.githubusercontent.com/26031501/64635087-76b2f080-d3c4-11e9-8391-e08200081ac6.png)

![image](https://user-images.githubusercontent.com/26031501/64635107-87636680-d3c4-11e9-833a-05b9a6255a63.png)

what do you think?

**Comment by terracoda** [comment]
The thinner strokes look way better. Thanks @DianaTavares!

I agree with @DianaTavares. I like the first color version in comment https://github.com/phetsims/tasks/issues/1008#issuecomment-530035370

Any preferences @emily-phet?
Or is this a wrap?

**Comment by terracoda** [comment]
I got feedback from Clayton, @DianaTavares and @emily-phet, I'll sketch a tweak to the labeling in the morning - colours are fine, I think. Top priority is making sure I get the abstract submitted and paper finished.

**Comment by terracoda** [comment]
@DianaTavares, I am going to close this issue for now. I'll open a new one when/if we need to iterate.

Thanks for your help on this figure.
