### ISSUE TITLE
Do some simple batch find/replace es6 conversions?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1010]
I have spend a noticeable amount of time converting files to es6. In general this is about 5 steps. Some of these could be done across the project in a batch find replace, here are the ones I've thought of. Does this seem like something worth doing on the whole? Marking for a last minute dev meeting.

```
define( function( require ) {
-> define( require => {

var (\w+) = require
-> const $1 = require
```

**Comment by pixelzoom** [comment]
Sure, but... why?

**Comment by jonathanolson** [comment]
Sounds like it would save time to do it in one batch?

**Comment by zepumph** [comment]
If all require statements were `consts`, it would improve the auto-import grunt task. 

It also seems like energy that is never worth thinking about/spending, ever again. doing it on a file by file basis is likely X times less efficient, where X is the number of files, as it will take 30 seconds to change all usages. 

30 seconds X 2744 (number of usages of `@constructor`) = too much time!

**Comment by Denz1994** [comment]
Discussed at dev meeting: 09/19/19

This is a time saver. @zepumph  go ahead with this addition.

Taking this a bit further means enabling the no-var lint rule and auto fix the failed cases. We suspect auto-fix will change var to const/let and if it can’t fix it will leave var. @zepumph will take a go at this.

**Comment by zepumph** [comment]
I committed the top two above. I will attempt to use the `no-var` to autofix over in https://github.com/phetsims/tasks/issues/1012. Closing
