### ISSUE TITLE
replace spot links with phet-dev

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1011]
I am still seeing a few places that are linking to `www.colorad.edu/physics/. . .` instead of phet-dev.

**Comment by zepumph** [comment]
```
_.sample( [ 'SR', 'MK', 'DB', 'AP', 'CM', 'JG', 'MP', 'JB', 'JO', 'CK' ,'ST'] )
->"JG"
```

@jessegreenberg will you please review. I kept the links in chipper 1.0 deploy docs, though I'm not sure if that is worth it. What do you think?

**Comment by jessegreenberg** [comment]
Hitting this as part of the ready-for-review task this iteration. Changes look good and I did a search for any remaining references to spot. I found one more in phet-io-wrappers and @samreid confirmed that it is correct. See https://github.com/phetsims/phet-io-wrappers/commit/8eb004b1c478f59619ca84d8a334446df468645d.

Closing.
