### ISSUE TITLE
using delete increases memory

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tasks#1013]
@samreid, @zepumph, and I were trying to improve cleanup by removing the no-longer-needed phetioBaselineMetadata from all phetioObjects after the sim's construction has finished with `delete this.phetioBaselineMetadata` in PhetioObject.

We then ran some tests to see if this saved us any memory, too, but found that this deletion actually consistently *increased* Graphing Quadratic's memory by 1MB. Changing the `delete` to a `null` assignment didn't cost extra megabytes, but didn't seem to save any either.

@samreid: perhaps the V8 engine having to create a different type because the schema changed is a possible explanation... maybe related to hidden classes? Further investigation is needed for a definite explanation. @jonathanolson does any of this ring a bell?

**Comment by jonathanolson** [comment]
> perhaps the V8 engine having to create a different type because the schema changed is a possible explanation... maybe related to hidden classes? Further investigation is needed for a definite explanation. @jonathanolson does any of this ring a bell?

It definitely would change the hidden class, however there's a chance that it's not changing the hidden class and is instead rolling it back to a slower larger key-value store type? That would explain the memory increase. nulling things out would probably be preferred.

**Comment by samreid** [comment]
I ran the following tests to see the impact on memory:

```js
// 20MB
  class Person {
    constructor( index ) {
      this.name = 'myname' + index;
      this[ 'property0' ] = index;
    }
  }

  window.hello = [];
  for ( let i = 0; i < 100000; i++ ) {
    window.hello.push( new Person( i ) );
  }
```

```js
// 40MB
  class Person {
    constructor( index ) {
      this.name = 'myname' + index;
      this[ 'property' + Math.random() ] = index;
    }
  }

  window.hello = [];
  for ( let i = 0; i < 100000; i++ ) {
    window.hello.push( new Person( i ) );
  }
```

**Comment by jonathanolson** [comment]
> I ran the following tests to see the impact on memory

Are we using random (or different) property names in common phet-io things?

**Comment by zepumph** [comment]
>Are we using random (or different) property names in common phet-io things?

Not that I know of.

How would we do a delete case that demonstrated this problem? I couldn't get it to work with this.

```js

  // 12MB
  class Person {
    constructor( index ) {
      this.name = 'myname' + index;
      this[ 'property0' ] = index;
    }
  }

  window.hello = [];
  for ( let i = 0; i < 100000; i++ ) {
    const person = new Person( i );
    window.hello.push( person );
  }
```

```js

  // 12MB
  class Person {
    constructor( index ) {
      this.name = 'myname' + index;
      this[ 'property0' ] = index;
    }
  }

  window.hello = [];
  for ( let i = 0; i < 100000; i++ ) {
    const person = new Person( i );
    delete person[ 'property0' ];
    window.hello.push( person );
  }
```

**Comment by samreid** [comment]
> Are we using random (or different) property names in common phet-io things?

No, but I've sometime seen code like this:

```js
  class Person {
    constructor( index ) {
      this.name = 'myname' + index;
      
      if (age>20){
        this.occupation = randomOccupation();
      }
    }
  }
```

**Comment by zepumph** [comment]
I think it is good to note that using `delete` can mess with shadow classes and performance. I haven't used it in a performance-required fashion since this issue. I'm going to close this issue and proceed with recognizing that life is better if classes' schema aren't mutated.
