### ISSUE TITLE
Investigate MS Teams

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#1014]
Things to investigate: 
- Web, desktop, and mobile clients
- Messaging
- Emoji reactions
- Code snippets 
- Channels
- Threads
- Message searching
- Guest access
- Status options 
- Integrations with google drive, google calendar, github
- Polling option (also, Forms) 
- Video calling features 
- Teams (directory, how conversations are organized, quick access to people, tabs)

**Comment by ariel-phet** [comment]
For the moment, we feel like slack is meeting our needs. 

One of the big missing features of Teams currently appears to be the ability to set a current status, which although a small feature, is fairly integrated into our current workflow/habits.

I am going to mark as deferred and set a calendar reminder for us to revisit this question in 6 months.

**Comment by ariel-phet** [comment]
I think this issue can be closed. The free version of slack has been working fine, and it seems that there is actually some advantage to NOT having an infinite history of messages as it forces the team to properly document decisions/critical discussions in github issues/design documents/ etc.
