### ISSUE TITLE
Create gifs for email campaign

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1016]
Can you please create a ~600px wide (at our standard aspect ratio) GIF of quick interactions (~5 seconds) with the following unreleased sims:

- [ ] Energy Skate Park - measure screen, using the measure tool on dots
- [ ] Circuit Construction Kit:AC - 
- [ ] Density - 

@kathy-phet please fill in details for what you would like. QA can take the recordings and I can get them into our holiday emails.

**Comment by oliver-phet** [comment]
Also - if it seems like the details are too small to capture at our normal aspect ratio, you could take a smaller screen recording of the relevant feature.

**Comment by KatieWoe** [comment]
Not final, just suggestions for what the gifs might look like.  Let me know if you approve and I'll make good quality versions in the right aspect ratio:
![suggestionforgif](https://user-images.githubusercontent.com/41024075/70162044-48b71280-167a-11ea-92e1-e8f0ad7e75a4.gif)

**Comment by oliver-phet** [comment]
@KatieWoe I think these are looking good - @kathy-phet any comments or requests?

**Comment by oliver-phet** [comment]
@KatieWoe Can you try making a new separate gif on ESP - basically what you already had above (but at the proper aspect ratio)?
Might try to "zoom in" to the energy panel/dots within the gif.

**Comment by KatieWoe** [comment]
@kathy-phet here are my proposals:
![espzoomin](https://user-images.githubusercontent.com/41024075/70349805-b8680180-1822-11ea-8907-b01bcdc4ffa1.gif)

**Comment by KatieWoe** [comment]
![cckac](https://user-images.githubusercontent.com/41024075/70349825-c1f16980-1822-11ea-8732-51ef057f49c3.gif)

**Comment by KatieWoe** [comment]
![density](https://user-images.githubusercontent.com/41024075/70349839-c9187780-1822-11ea-8688-3aaa39ae4bdd.gif)

**Comment by oliver-phet** [comment]
@KatieWoe I don't know what caused this but the CCK image seems to have a black border on the top and right sides. Any way to get rid of that?

**Comment by KatieWoe** [comment]
I probably didn't have the screen aligned well when I recorded it. I'll try to crop it out.

**Comment by KatieWoe** [comment]
Here you go:
![ezgif com-resize](https://user-images.githubusercontent.com/41024075/70654072-dbbff180-1c12-11ea-95b6-d1c8dd7ab68d.gif)
