### ISSUE TITLE
Ensuring associated github issue for TODOS in common code

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#1017]
As discussed in https://github.com/phetsims/chipper/issues/815, we will go through our common code repos (excluding scenery, dot, kite for now) and see what TODOs need an associated github issue, once complete, we will enforce the suggested lint rule in these common repos. We will have devs sign up for various repos at dev meeting, and do a weekly check in until this work is complete.

- [x] aqua (@jonathanolson)
- [x] assert (@samreid) - no TODOs
- [x] axon (@samreid) - all TODOs already have reference issues
- [x] binder (@chrisklus)
- [x] blast (@samreid) - no TODOs
- [x] brand (@samreid) - no TODOs
- [x] bumper @pixelzoom
- [x] chipper (@jonathanolson, @zepumph)
- [x] griddle (@Denz1994) - 3 TODOs addressed, 1 issue created
- [x] joist (@samreid) - all TODOs already reference issues
- [x] mobius (@jonathanolson)
- [x] perennial (@jonathanolson/@mattpen) - done by @pixelzoom 
- [x] phet-core @pixelzoom
- [x] phetcommon (@samreid) - 1 issue created
- [x] phet-io (@zepumph & @chrisklus)
- [x] query-string-machine (@samreid) - 1 TODO addressed, 1 issue created
- [x] scenery-phet (@jessegreenberg) - done by @pixelzoom 
- [x] shred (@jbphet)
- [x] smithers @mattpen - 4 TODOs addressed, 0 remaining
- [x] sun @pixelzoom
- [x] tambo (@jbphet)
- [x] tandem (@zepumph & @chrisklus)
- [x] tappi (@jessegreenberg) - completed by @pixelzoom 
- [x] twixt (@jonathanolson)
- [x] utterance-queue (@zepumph)
- [x] vegas (@jbphet)
- [x] vibe (@jbphet)
- [x] wilder (@zepumph)

**Comment by pixelzoom** [comment]
All of the "chipping" that I volunteered for is done.  I created 7 issues, and addressed 2 or 3.

**Comment by samreid** [comment]
@ariel-phet would like to see another one checked off for next week.

**Comment by zepumph** [comment]
Chipper is done

**Comment by Denz1994** [comment]
As discussed in dev-meeting on 02/20/20:
PSA @jbphet will take a swing at one of his assigned repo within the next 1-2 weeks.

**Comment by jbphet** [comment]
Mine are done, unassigning.

**Comment by pixelzoom** [comment]
I did the perennial and tappi repos.

**Comment by pixelzoom** [comment]
I also took care of scenery-phet.  

All repos are done. Closing.
