### ISSUE TITLE
Eliminate all debugger usages from the project

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1020]
I often get bit by trying to search for where I have added debuggers for local debugging and finding that the project has 12 usages of `debugger;` checked in. Can we get rid of them? I'm going to try to do that and mark for dev meeting to see if anyone disagrees with me.

**Comment by zepumph** [comment]
Done in the above commit. In all cases it seems like I was just cleaning up, and most of it looked mistakenly checked in. Does anyone dislike the idea of adding `debugger;` to bad-text?

**Comment by pixelzoom** [comment]
I don't see any reason why code with `debugger;` should be checked in.  OK with me to add to bad-text.js.

**Comment by samreid** [comment]
It would be better to use this built-in lint rule: https://eslint.org/docs/rules/no-debugger

**Comment by zepumph** [comment]
That's a great idea! Thanks @samreid.

**Comment by jessegreenberg** [comment]
We are already using no-debugger
![image](https://user-images.githubusercontent.com/6396244/73477989-3c41f400-4363-11ea-885d-93bc71613db5.png)

**Comment by pixelzoom** [comment]
@zepumph Since we already have a lint rule for this, can this issue be closed?

**Comment by zepumph** [comment]
What I was finding was code that wasn't linted, and multiple places where there was checked in `// debugger;`. I think that it was enough to just delete those few usages. Ready to close, thanks.
