### ISSUE TITLE
Artwork for CCK - updated dog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#1021]
In https://github.com/phetsims/circuit-construction-kit-common/issues/512 we modified the behavior of the dog so that it has a fuse-like behavior. It will disconnect from the circuit and bark when the current is too high. 

We would like to update the dog's artwork so to that it looks at the screen when when it "barks". @megan-phet mentioned that it might be more time consuming to modify the original artwork to turn the dog's head, and suggested redrawing the dog. I think this is a reasonable idea, but we should keep the following in mind:

* Two images are needed. One where the dog is facing forward (like the one currently in the sim) and one where the dog is looking over its shoulder at the sim user.
* Keep the artboard dimensions the same as the one used in [grab-bag.ai](https://github.com/phetsims/circuit-construction-kit-common/blob/master/assets/grab-bag.ai)
* Match the original pose, so that the paw & tail positioning stays the same. (Both the face-forward and over-shoulder poses should have the same paw & tail positions.)
* The general coloring/breed of the dog should still be Emmy-like, but look like the one drawn for ESP in #962.

This is lower priority than #1019.

**Comment by megan-phet** [comment]
![IMG_08E0FB1EF6A9-1](https://user-images.githubusercontent.com/40698031/78061708-d9f97580-734a-11ea-885c-d9e2b00b2419.jpeg)

**Comment by megan-phet** [comment]
<img width="426" alt="Screen Shot 2020-04-12 at 4 12 33 PM" src="https://user-images.githubusercontent.com/40698031/79081204-825af280-7cd8-11ea-8b43-e8615cf66881.png">
