### ISSUE TITLE
fill in gaps in public-facing developer documentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#1022]
Over in https://github.com/phetsims/normal-modes/issues/2, I did a code review of Normal Modes, contributed by a 3rd party.   The review took longer than expected because the 3rd party was not aware of some of the essential tools and documentation that PhET relies on.

@ariel-phet asked me to create this issue based on my comment in https://github.com/phetsims/normal-modes/issues/2#issuecomment-584411970:
> Most of the deficiencies (e.g. lint, assertions) can be traced to deficiencies in PHET's documentation for 3rd-party developers. @ariel-phet we might consider triaging these GitHub issues to pull out the things that need to be improved in PhET doc.

In the case of Normal Modes, the 3rd party was not aware of:
* assertions
* lint
* PhET Software Design Patterns doc (especially options pattern)

Looking through the GitHub issues related to the code review may identify some others, but those are the "big 3".

**Comment by samreid** [comment]
If `assert` was an `import` instead of a global, then users could have a clear path to navigating to it, then we can document it there?

**Comment by zepumph** [comment]
From developer meeting today:

* Not a super high priority
* There are more developers out there using our code
* Updating documentation is important
  * Running lint
  * enabled assertions (maybe we enabled by default)
  * Using es6 modules
* Add assertions to example-sim/simula rasa as examples (there are none currently)

@pixelzoom volunteered to implement the last two bullets. Thank you @pixelzoom!!

**Comment by pixelzoom** [comment]
- [x] Running lint

I added this to the "Utilities and Instrumentation for Development and Testing" section of the PhET Development Overview:

> Run `grunt lint` on the command line to check for lint errors. All code should be free of lint errors. (lint is a tool that analyzes source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. PhET uses the eslint variant of lint.)

- [x] enabled assertions (maybe we enabled by default)

This was already present in the "Utilities and Instrumentation for Development and Testing" section of the PhET Development Overview:

> Query parameter: `?ea`. This parameter is used to “enable assertions”. The sim should run without triggering any assertion errors in ?ea mode.

- [x] Using es6 modules

This will presumably be addressed by https://github.com/phetsims/chipper/issues/854.

- [x] Add assertions to example-sim/simula rasa as examples (there are none currently)

I added assertions that type-check arguments to example-sim and simula-rasa.  The example in example-sim explains what they are, and how to enable them:

```js
    // This is an example of using assertions to check for potential programming errors. In this case, we are verifying
    // that the arguments have the expected type.  Run the simulation with query parameter ?ea to enable assertions.
    assert && assert( barMagnet instanceof BarMagnet, 'invalid barMagnet' );
    assert && assert( modelViewTransform instanceof ModelViewTransform2, 'invalid modelViewTransform' );
```

@ariel-phet please assigning someone to review.

**Comment by ariel-phet** [comment]
@chrisklus please feel free to close once review (and any changes or back and forth that should take place) are complete.

**Comment by chrisklus** [comment]
Code and documentation changes look good. I tested the type checks added to `simula-rasa` with `grunt create-sim` and they're working as expected. Thanks @pixelzoom, back to you to close if all set.

**Comment by pixelzoom** [comment]
👍 Closing.
