### ISSUE TITLE
Modify banner artwork

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#1023]
Currently all banners are 1024x170. We would like the artwork modified so that 
1. The banners are 1300x170 (with artwork contained in 1260x170) 
2. All titles are vertically centered in the banners

There can be artwork above and below the title bounding boxes, just not inside. In some cases the artwork can be make larger or smaller, but in most cases you'll probably need to _add_ artwork to fill the extra space. 

In order of priority: 
- [x] Underwater
- [x] Classroom 
- [x] Skatepark
- [x] Jungle
- [x] Lab
- [ ] Flatiron
- [ ] Flatiron Sunset
- [ ] Flatiron Snow
- [x] Space
- [ ] Flying PhET Girl

**Comment by clmccutchan** [comment]
@amanda-phet Here's a first attempt at the underwater banner.

![banner_underwater_021220-01](https://user-images.githubusercontent.com/25354670/74387904-1bdc5580-4db7-11ea-866d-33b37ed1098b.jpg)

**Comment by clmccutchan** [comment]
@amanda-phet To make the colors on the banners less vibrant, I've added a white rectangle above the image and decreased it's opacity. You can set the opacity at the percent that works best for the website. 
![banner_underwater_OpaqueLayer-01](https://user-images.githubusercontent.com/25354670/74485379-d7fd5500-4e77-11ea-8456-d21f53efc809.png)

**Comment by clmccutchan** [comment]
@amanda-phet Here's a draft of the classroom banner.
![banner_classroom_Border_021320](https://user-images.githubusercontent.com/25354670/74487265-417f6280-4e7c-11ea-85b2-89eeefa36747.png)
![banner_classroom_Opaque_021320](https://user-images.githubusercontent.com/25354670/74487269-42b08f80-4e7c-11ea-98c9-742e1ee47cd8.png)

**Comment by amanda-phet** [comment]
I think it would be helpful to see the classroom banner with a title. I suspect that it will look strange with a title centered in that red rectangle and not centered within the white board. A few ideas... 
1. Make the whiteboard the fill height of the banner (or maybe with a thin border) and put the student in the center over to the side. 
2. Make the whiteboard shorter so the title looks centered in it. 
3. I'm also wondering if we need additional students to fill the space, or perhaps some students could look like they are in a discussion about a sim? I am conflicted about this particular banner because I love the people, the mountains, the teacher, but we also don't usually want to encourage a "teacher in front of the room" style of classroom. Happy to discuss this over zoom too, if you'd like.

**Comment by clmccutchan** [comment]
Totally agree on the classroom, @amanda-phet. 

1 and 2. I had the same thought about the whiteboard and started altering it. I'll place sample text that is two lines long in each of the banners so we can really get a feel for the text placement. I think that it could be centered vertically and the student moved. 

3. We may need to discuss this so I can come up with a solution that makes sense with PhET's style.

For the underwater banner, I moved the background fish out of the center text area. If you decide against them, you can just hide the layer.

The Flatirons banners will need the most work. The mountains are currently centered and take up most of the vertical space. I'll need to move them to the left and then fill the right with other mountains.

**Comment by clmccutchan** [comment]
@amanda-phet I've updated the classroom, skatepark, and jungle banners.
![banner_classroom_021420](https://user-images.githubusercontent.com/25354670/74615972-50674e80-50e2-11ea-80ea-a2496a3f6b2b.png)
![banner_skatepark_021420](https://user-images.githubusercontent.com/25354670/74615974-53623f00-50e2-11ea-9e53-94e80460c3a4.png)
![banner_jungle_CM_021620](https://user-images.githubusercontent.com/25354670/74615983-6412b500-50e2-11ea-9943-b868f824c512.png)

**Comment by amanda-phet** [comment]
These are looking really great! Let me try them in context for these pages and run them by the team at tomorrow's meeting.

**Comment by clmccutchan** [comment]
@amanda-phet Here are two more. I've left the more difficult lab scene and three flatiron banners for last. Let me know what edits need to be made to the other banners!

![banner_flyingphetgirl_021720-01](https://user-images.githubusercontent.com/25354670/74696835-34cd7800-51b6-11ea-8489-9b1bf4cbad48.png)
![banner_space_021720-01](https://user-images.githubusercontent.com/25354670/74696841-35fea500-51b6-11ea-9383-f5c9331a8dff.png)

**Comment by clmccutchan** [comment]
@amanda-phet Here are two ideas for the laboratory banner. The text in example B is centered in the vertical space but looks too low because there are no graphic elements at the top of the banner to balance the lab bench at the bottom. Example A attempts to create a more balanced space. There might be another graphic that would work better than the curly tubing. 

![banner_lab_021820A](https://user-images.githubusercontent.com/25354670/74781476-c85a8380-525e-11ea-816a-8cbf29a94d31.png)
![banner_lab_021820B](https://user-images.githubusercontent.com/25354670/74781483-ca244700-525e-11ea-83e9-692255934bd9.png)

**Comment by amanda-phet** [comment]
These are all looking great! One thing I think I'd like, now that we're making these a lot more useful... is actually a wider box for titles. I think the bounds right now for that inner rectangle are 300x105. If you can squeeze that out to 400x105 I think that might make the area a little more useful. The outer rectangle (170x420) should still include some visual elements so that on a mobile device the user can see some of the theme still. Titles are Roboto, bold, size 35.2px. 

For Chemistry I think I prefer without the tubing above the title, but we can keep both and when we get to that page consider both.

**Comment by clmccutchan** [comment]
@amanda-phet Here are 5 of the banners with the new boundaries and the correct font.

![banner_jungle_021920](https://user-images.githubusercontent.com/25354670/74893309-5317ad00-5349-11ea-924d-a2b719425ece.png)
![banner_lab_021920](https://user-images.githubusercontent.com/25354670/74893312-54e17080-5349-11ea-98e1-426f490a0af4.png)
![banner_skatepark_021920](https://user-images.githubusercontent.com/25354670/74893315-56129d80-5349-11ea-9fe1-71d09c514cfa.png)
![banner_space_021920](https://user-images.githubusercontent.com/25354670/74893316-56ab3400-5349-11ea-855e-548772e576d1.png)
![banner_underwater_021920](https://user-images.githubusercontent.com/25354670/74893317-5743ca80-5349-11ea-8edb-899200cc097c.png)

**Comment by clmccutchan** [comment]
@amanda-phet Here are two more with the updated text boundary. I'll work on the three flatirons scenes now.

![banner_classroom_021920](https://user-images.githubusercontent.com/25354670/74978307-8c9ff500-53e9-11ea-9acd-c1584ce6d8e4.png)
![banner_flyingphetgirl_021920](https://user-images.githubusercontent.com/25354670/74978310-8dd12200-53e9-11ea-82a0-fe06792de2ec.png)

**Comment by amanda-phet** [comment]
Awesome. These look great!

**Comment by clmccutchan** [comment]
@amanda-phet I'm going to need to rework the Flatirons scene(s). The current layout just doesn't work with the text box layout. I'll try to get a new draft of one of the Flatirons banners by Monday.

**Comment by amanda-phet** [comment]
@clmccutchan can you email or upload the ai files for these final banners? We are ready to do some exporting and get the website updated!

**Comment by clmccutchan** [comment]
@amanda-phet I'm having trouble finding the Google drive I need to put the .ai files in. Could you send a link? Thanks!

Also, I should have a draft of the Flatirons tomorrow!

**Comment by amanda-phet** [comment]
This folder should work: https://drive.google.com/drive/folders/11Pjhsui7cGYKEIFuNeC_IjjqPuB-TBWV 

Thanks!

**Comment by clmccutchan** [comment]
@amanda-phet I've placed 7 Illustrator files in the folder. All of the files are saved as CS6. The 3 remaining banners all of the Flatirons.

**Comment by clmccutchan** [comment]
@amanda-phet Here's a first draft of a reworked Flatirons banner. 

![banner_flatirons_022620](https://user-images.githubusercontent.com/25354670/75389917-a2f3f800-58a4-11ea-8605-a010cfa7299b.png)

**Comment by amanda-phet** [comment]
Thanks @clmccutchan ! I went to the folder and had no problem opening the underwater banner, exported it, and hopefully soon it will be on the website. If any issues arise I'll let you know, but I don't anticipate anything. 

I'll run this flatirons banner by the team tomorrow. I think it looks pretty!

**Comment by clmccutchan** [comment]
@amanda-phet Here's another draft of the Flatirons banner. The right side of the mountains needs some work and the plants aren't completely filled in. I think the thing that is odd about the Flatirons banners is that they don't have any people in them. All of the other banners have kids doing things, but the three Flatirons banners don't match this style. I think I'm trying to create a hybrid style but am not sure it's working.

 
![banner_flatirons_031120](https://user-images.githubusercontent.com/25354670/76446885-553fbb00-638d-11ea-8276-5cc84a974b84.png)

**Comment by amanda-phet** [comment]
I agree the mountains need a little bit of work (a little pointer? flatter sides?), but I love the buffalo and plants! This is awesome! Don't worry about the lack of people in this banner. It looks great as it is. Thanks for the update, and I'd say let's continue in this direction.

**Comment by clmccutchan** [comment]
@amanda-phet I've filled in the plants and fixed the right side of the mountains for the Flatirons banner. I'm working on the snow scene now.

![banner_flatirons_031720](https://user-images.githubusercontent.com/25354670/76985832-70b74280-6906-11ea-82df-8ba22ba6b1bc.png)

**Comment by amanda-phet** [comment]
Looks awesome!

**Comment by clmccutchan** [comment]
@amanda-phet Here are the last two Flatirons banners. Let me know what you'd like me to edit.

![banner_flatironsnow_032120](https://user-images.githubusercontent.com/25354670/77372765-10703880-6d2c-11ea-9c84-3bf639e5595e.png)
![banner_flatironsunset_032320](https://user-images.githubusercontent.com/25354670/77372769-1239fc00-6d2c-11ea-9bb8-3c6c61d638db.png)

**Comment by amanda-phet** [comment]
These look great! I'm a little concerned about the sunset one because it's also night time, and I'm not sure there is enough contrast between the white text and the background for some of those light colors. So I think we either need to make it earlier in the evening (so the rest of the sky can be blue/purple, but light enough for black text), or later at night (and just a very faint glow where the sun is setting). I lean more toward the sunset because I just think the colors are pretty, but the moon would probably need to be more subtle. What do you think?

**Comment by clmccutchan** [comment]
@amanda-phet Let me mess around with this. I'll lighten the sky and try removing the moon. I may need to add bats or some other creature that likes being out at dusk.

**Comment by amanda-phet** [comment]
Hey @clmccutchan do you have an update on the flatirons banners? I think the sunset one was the only one that still needed tweaking. How is that going now? I think the spring and winter ones were all done- can you put those in the google drive for us to start using?

**Comment by clmccutchan** [comment]
Hi @amanda-phet, I'm working on that banner today and tomorrow and hopefully, will have a new draft by the afternoon. Sorry I stalled out on that!

**Comment by amanda-phet** [comment]
Thanks for the update! Just wanted to wrap this up because I might have another task for you to start :)

**Comment by clmccutchan** [comment]
@amanda-phet Here's a light option and a dark option for the sunset banner. What do you think?

![banner_flatironsunset_DARK_042120](https://user-images.githubusercontent.com/25354670/80045995-733d2700-84c6-11ea-88e9-73e8b358ec08.png)
![Uploading banner_flatironsunset_LIGHT-042220.png…]()

**Comment by clmccutchan** [comment]
@amanda-phet  Here's a light option and a dark option for the sunset banner. What do you think?

![banner_flatironsunset_DARK_042120](https://user-images.githubusercontent.com/25354670/80046093-cc0cbf80-84c6-11ea-8d76-96e5c1e5f576.png)
![banner_flatironsunset_LIGHT-042220](https://user-images.githubusercontent.com/25354670/80046118-daf37200-84c6-11ea-9f35-e137dc96fc3a.png)

**Comment by amanda-phet** [comment]
Now we have another banner, yay! They both look great to me. The light sunset has something funny on the pink circle, but I can't quite tell what it is, but the top looks like the blue is squishing it or something. The shape just doesn't quite look as "radiant" as the one in https://github.com/phetsims/tasks/issues/1023#issuecomment-602914587. But this is minor. I think if you find anything there worth tweaking go for it, but if it's an illusion then leave it as it is and plop them all in the drive folder!

**Comment by clmccutchan** [comment]
@amanda-phet The light blue banner has to abrupt a transition between the pink and blue. I'll tweak that.

**Comment by clmccutchan** [comment]
@amanda-phet I've changed the type of blur used in the sunset to that it transitions better from one color to the next.

![banner_flatironsunset_CM_LIGHT-01](https://user-images.githubusercontent.com/25354670/80150978-86a7cb00-8576-11ea-8270-06e6970baca5.png)

**Comment by clmccutchan** [comment]
@amanda-phet All the Illustrator files have been uploaded. Let me know if there's anything else you want me to tweak.

**Comment by amanda-phet** [comment]
Thanks so much @clmccutchan . These are all so beautiful. I can't wait until we can get them all up on the website!
