### ISSUE TITLE
Greenhouse waves prototype

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1024]
@arouinfar requested a Greenhouse waves prototype, here are my notes on how it should work:

Waves emanating down from the top of the screen.  Not damped.  Black lines on white page, controls for frequency and amplitude. Control for number of waves.  They are all in phase.  3-10 waves.  Reset button that starts them at the top again.

Next greenhouse meeting is Tuesday 1pm.  But Amy is out on Feb 18th, but that or next one would be OK.

Maybe in scenery phet demo or something.

Get fancy?  Make a fake sky and grass.  Rectangles.  Waves hit the ground in the grass.

I said it could take up to 4 hours including all the controls and everything.  See how far I get in an hour.

**Comment by samreid** [comment]
Here's an initial prototype, you need to make sure the window is short and wide instead of tall and thin so you don't see the tops of the sine waves:

https://phet-dev.colorado.edu/html/scenery-phet/1.0.0-dev.17/phet/scenery-phet_en_phet.html?greenhouseWaves

@arouinfar can you please take a look and let me know if you'd like any other changes for this draft?

**Comment by samreid** [comment]
@kathy-phet here is a version with yellow waves and a higher max number of waves:

https://phet-dev.colorado.edu/html/scenery-phet/1.0.0-dev.18/phet/scenery-phet_en_phet.html?greenhouseWaves

**Comment by arouinfar** [comment]
@samreid this is looking great, thanks! 

I think this demo takes care of our needs @kathy-phet. Can we close the issue?

**Comment by samreid** [comment]
I moved the prototype over to the greenhouse-effect repo, closing.
