### ISSUE TITLE
Background artwork for the Greenhouse Effect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#1033]
This is a higher priority than #1032.

We are currently redesigning the [Greenhouse Effect](https://phet.colorado.edu/en/simulation/legacy/greenhouse) simulation, which has three distinct scenes: modern, pre-industrial, and ice age. 

Java artwork:
<img width="790" alt="Screen Shot 2020-04-01 at 2 16 30 PM" src="https://user-images.githubusercontent.com/8419308/78182488-827b0880-7423-11ea-85e3-81f259703085.png">
<img width="787" alt="Screen Shot 2020-04-01 at 2 16 46 PM" src="https://user-images.githubusercontent.com/8419308/78182492-8444cc00-7423-11ea-911b-b53c21a81d54.png">
![image](https://user-images.githubusercontent.com/8419308/78183503-3cbf3f80-7425-11ea-9618-e25edf04acd3.png)

@clmccutchan some things to keep in mind 
* The HTML5 sim background has dimensions of 1024x617, but there will be controls taking up ~1/4 of the right side of the screen, so if possible avoid placing any buildings/items there.
* The thermometer is not part of the background, so you don't need to include that.
* All three scenes should have a common surface profile, but the ice age scene adds glaciers on top of that. Let's try two glaciers for that scene, and avoid the screen edges if possible.
* The modern scene should have a mix of residential/commercial buildings, but the general number of buildings should be similar to Java.
* The pre-industrial scene should look agrarian, but we don't want to show any livestock.
* Each scene can also have up to three clouds. The clouds should be roughly the same size and should have a very flattened look.

Please let me know if you have any questions!

**Comment by clmccutchan** [comment]
Hey @arouinfar, I just wanted to give you a heads up that I'm getting back into these backgrounds. Has anything changed about the specifications before I start? Thanks!

**Comment by arouinfar** [comment]
Artwork was tracked in https://github.com/phetsims/greenhouse-effect/issues/49 and the sim has been published, closing.
