### ISSUE TITLE
"Grid" Graphics for RaP radio buttons

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#1036]
For the sim Ratio and Proportion, I would like to replace the currently labeled "Grid" and "Numbered Grid" with icons of a grid and numbered grid.

The "grid" display in the sim will ultimately have only horizontal lines, no vertical lines (think notebook paper you used in school with wide ruled horizontal lines). So for the icon, perhaps three horizontal lines, and for the numbered grid perhaps three horizontal lines numbered "1, 2, 3"? 

We're going to be space constrained, so if we can get two horizontal lines to work, that would be ideal...but I'm guessing three horizontal lines for each icon will be needed to convey the idea well. Here's the latest [sim link](https://bayes.colorado.edu/dev/html/ratio-and-proportion/1.0.0-dev.19/phet/ratio-and-proportion_en_phet.html) - but note the vertical lines will be removed soon when "grid" and "numbered grid" is displayed.

As an example of other sims with grid icons, see the Area Model: Decimals sim (just right of the large grid play area are checkboxes with grid lines).

@clmccutchan Is this something you could create?

**Comment by clmccutchan** [comment]
@emily-phet These icons should be pretty simple to create. I'll use a size of 100x100 pixels for the assets. We may need to tweak the size of the numbers once you place the draft .pngs in the sim.

**Comment by emily-phet** [comment]
@clmccutchan Here's updated info on the look and feel needed for this artwork. We'd like something that will be implemented as buttons, similar to these:
<img width="293" alt="Screen Shot 2020-05-22 at 7 08 42 AM" src="https://user-images.githubusercontent.com/5109055/82676648-965d1280-9bfb-11ea-92bd-0aaf2227d2dc.png">
(in mockup above, the lines in the button artwork indicate text, not gridlines, so the new ones created will need to look more like gridlines).

- There will be the "hide" button (with the eye image, we'll just reuse existing artwork from other sims).
-  There will be the "gridline" button as described originally... two or three horizontal lines, whichever is the minimum to clearly convey "gridlines". 
- The third button will have the "numbered gridlines" option, two or three horizontal lines with the numbers in the *center* - see mockup below of what numbered gridlines will look like. Note, gridlines and numbered grid (numbers and lines) will all be dark grey, not black.

<img width="402" alt="Screen Shot 2020-05-22 at 6 52 59 AM" src="https://user-images.githubusercontent.com/5109055/82676827-dae8ae00-9bfb-11ea-9ddb-6882c78b86d6.png">

Can you comment when you might have these ready (or if you have any questions, of course!).

**Comment by clmccutchan** [comment]
@emily-phet I'm so sorry I stalled out on this! I should have a draft by the end of the day; Monday at the latest.

**Comment by clmccutchan** [comment]
@emily-phet How about something like this? 

![Gridlines_Grid_052520](https://user-images.githubusercontent.com/25354670/82841022-e0f7bc80-9e91-11ea-8664-504c2446fe8c.png)
![Gridlines_NumberedGrid_052520](https://user-images.githubusercontent.com/25354670/82841024-e1905300-9e91-11ea-94e9-424c953a0dc1.png)

**Comment by emily-phet** [comment]
Thanks @clmccutchan! I think these are on the right track. Can you make the grey lines thinner, and bring them closer together within each image. Also, square off the edges for the numbered grid. 
The latest sim now has the numbered grid in it, so here's what it looks like (note: I think they'll be some tweaks to the numbers - maybe making them bold, or changing the font).

<img width="949" alt="Screen Shot 2020-05-28 at 7 05 14 AM" src="https://user-images.githubusercontent.com/5109055/83151658-b4ba8680-a0b1-11ea-8a1e-571e8e2f2c5f.png">

**Comment by clmccutchan** [comment]
@emily-phet Would you like me to add an additional gridline so that there are 4 per icon?

**Comment by emily-phet** [comment]
@clmccutchan I think the three lines per image looks pretty good. Can you move the lines within each one a little closer together? Maybe 40% closer?

**Comment by clmccutchan** [comment]
@emily-phet Here are two options for line spacing for each icon. What do you think?

![Gridlines_060220_Grid](https://user-images.githubusercontent.com/25354670/83549488-a1992380-a4c2-11ea-8f6f-ef84123008c0.png)
![Gridlines_060220_Grid2](https://user-images.githubusercontent.com/25354670/83549491-a2ca5080-a4c2-11ea-9472-bf15b80b3d28.png)
![Gridlines_060220_NumberedGrid](https://user-images.githubusercontent.com/25354670/83549492-a2ca5080-a4c2-11ea-9fb6-0b6022156a01.png)
![Gridlines_060220_NumberedGrid2](https://user-images.githubusercontent.com/25354670/83549493-a2ca5080-a4c2-11ea-91c1-3af3110df63c.png)

**Comment by emily-phet** [comment]
Thanks @clmccutchan - the second of each (closest distance) looks great to me. 

@zepumph Let's try these, along with the eye image that's in Area Model Multiplication.

**Comment by zepumph** [comment]
Catch you over in https://github.com/phetsims/ratio-and-proportion/issues/55 for implementation.

**Comment by zepumph** [comment]
Sorry I forgot, we need to store the original asset in github as well, so @clmccutchan  can you please provide the `ai` file or whatever underlying resource provided the png files above. Thanks!

**Comment by clmccutchan** [comment]
Sorry about the delay, @zepumph. I've placed the file in my folder on Google drive since github doesn't accept .ai files. Here's the link to my folder: https://drive.google.com/open?id=0B6CMwxdP0NGYbDZ4Qmt2UDZlOEU

The file is called Gridlines.ai.

**Comment by zepumph** [comment]
Thanks! Added to github.
