### ISSUE TITLE
Mockup for new Waves sim idea for upcoming grant proposal

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/tasks#1041]
@amanda-phet @arouinfar 

@emily-phet is working on a grant proposal and we were hoping for a quick turnaround for a basic, sketchy mockup for a sim idea we have with all of the usual PhET elements. This will be used as a figure in the proposal with some explanation text about the premise. Ideally, we could have the mockup made by early-middle next week!

I've included a SUPER basic graphical idea below, but the idea here is that there are two controls that can be moved side by side using left and right hand to generate "waves", which when done correctly will generate (visual) feedback in the center of the screen based on the phase of the generated waves.

Feel free to unassign/reassign as needed, ask me any questions, and thank you! 

scenario 1
![image](https://user-images.githubusercontent.com/47331395/86961274-2e687a00-c11e-11ea-87cf-d3d4331d053d.png)
scenario 2
![image](https://user-images.githubusercontent.com/47331395/86961931-47bdf600-c11f-11ea-9b99-91ca335defd0.png)
scenario 3
![image](https://user-images.githubusercontent.com/47331395/86961960-53112180-c11f-11ea-94c6-67c3bba98954.png)

**Comment by emily-phet** [comment]
@amanda-phet @ariel-phet @arouinfar We're hoping someone could a little bit of time to throw this together, doesn't have to be polished, just something to get the idea across while having a typical PhET feel to it (rather than the sketch above). Please let me know if the timeline is too tight and it's not possible, or if another artist on the team may have the time.

**Comment by amanda-phet** [comment]
I can work on this tomorrow (Friday 7/10/20) if @BLFiedler or @emily-phet is available for a zoom call about it.

**Comment by BLFiedler** [comment]
Reaching out via slack

**Comment by amanda-phet** [comment]
Met with @BLFiedler and came up with these three screenshots. If you have a room, I think a starting state is really helpful :) 

Please discuss and let me know what tweaks you want. 

![image](https://user-images.githubusercontent.com/7852916/87172615-be7b0080-c291-11ea-9f67-098dec546a9c.png)

![image](https://user-images.githubusercontent.com/7852916/87172709-e1a5b000-c291-11ea-8954-fc4fa34d88ea.png)

![image](https://user-images.githubusercontent.com/7852916/87172723-ea968180-c291-11ea-9197-0b598940f128.png)

**Comment by emily-phet** [comment]
These look great! 

Can we add the following? - so it seems a bit more PhET-like...
- Shift the whole "Play area" over the left slightly (or squish down a bit) to make room for some controls on the right side.
- Add some radio buttons (scene selection style) with a few different wave patterns (complete constructive, destructive, and something else @BLFiedler?)
- Just above the center wave, put a black bar (kind of like RaP) - my idea is that selecting a different wave button would put a kind of target at the top of the screen. This black bar would represent whatever that target looks like, black bar for now would be fine...maybe the width of the constructed wave (wide for constructive, narrow for destructive).

**Comment by BLFiedler** [comment]
I think that makes sense. I think the 3rd choice would be 90o out of phase (pi/2), which is slightly higher in amplitude but shifted relative to the drawn sinusoid: 
![image](https://user-images.githubusercontent.com/47331395/87185319-cbeeb580-c2a6-11ea-958f-f8194883b6f1.png)

@amanda-phet Let me know if you'd like to hop in another quick call for me to try to clarify if you're not quite sure what @emily-phet is saying.

We could maybe consider some checkbox controls for reference lines? e.g. center lines and horizontal grid lines?

**Comment by amanda-phet** [comment]
![image](https://user-images.githubusercontent.com/7852916/87187431-656b9680-c2aa-11ea-9d7d-0de6c7c74d40.png)

![image](https://user-images.githubusercontent.com/7852916/87187456-6d2b3b00-c2aa-11ea-84c5-ec71d02a67ed.png)

![image](https://user-images.githubusercontent.com/7852916/87187486-76b4a300-c2aa-11ea-8c28-6dde871a6f81.png)

**Comment by BLFiedler** [comment]
Ah sorry, I totally spaced during our discussion. The center line checkbox should put the line on both sides, not just the right.

**Comment by amanda-phet** [comment]
Here you go. Also updated the checkbox, which is a little strange. You may want a phrase there instead. 

![image](https://user-images.githubusercontent.com/7852916/87203877-c900be80-c2c0-11ea-9423-3291d9e4c73c.png)
![image](https://user-images.githubusercontent.com/7852916/87203888-d322bd00-c2c0-11ea-83ee-a78c6e8e0d77.png)
![image](https://user-images.githubusercontent.com/7852916/87203903-dd44bb80-c2c0-11ea-8164-c9010ba4dde8.png)

**Comment by BLFiedler** [comment]
Hey @amanda-phet 

Could we modify the icon for the center line to have 3 dashes and center it with the above grid icon?

After that, that should do it for this mockup!

**Comment by amanda-phet** [comment]
![1D-wave-01](https://user-images.githubusercontent.com/7852916/87596506-7e5eb800-c6ad-11ea-9158-61e1913ba3de.png)
![1D-wave-02](https://user-images.githubusercontent.com/7852916/87596509-7ef74e80-c6ad-11ea-9683-d54d9455b8ba.png)
![1D-wave-03](https://user-images.githubusercontent.com/7852916/87596511-7f8fe500-c6ad-11ea-8707-30f605315f4b.png)

[1D-wave.ai.zip](https://github.com/phetsims/tasks/files/4927993/1D-wave.ai.zip)

**Comment by BLFiedler** [comment]
Looks great! Over to you @emily-phet to close.

**Comment by emily-phet** [comment]
@BLFiedler can you take the zip file and put it in the proposal folder? Once that's done, go ahead and close.

This looks great - thanks @BLFiedler and @amanda-phet for putting this together!
