### ISSUE TITLE
Document supported browsers in an open source manner

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1042]
Related to https://github.com/phetsims/tasks/issues/1037 and https://github.com/phetsims/query-string-machine/issues/39#issuecomment-659488375 and https://github.com/phetsims/tasks/issues/1018. It feels like we should have a place where devs can see what browsers we support. 

Over in https://github.com/phetsims/query-string-machine/issues/39#issuecomment-659488375, @samreid mentioned that likely https://phet.colorado.edu/en/help-center/running-sims is the best place for end-users, but there isn't a central location where we let it be known to devs that the phet code base (including underlying and potentially independent libraries like QSM and scenery) doesn't support certain browsers. I am running into this quite a bit as we drop support for IE, and it think it would be a good step for the project to take in terms of transparency and open-source philosophy.

My recommendation (expanding on @samreid's in that link) is to put this somewhere in top level documentation, and link to that where ever needed. 

Some proposals:
* Create `supported-browsers.md`, link to it in `phet-development-overview.md`, and in any library README file needed. This modular doc could be easily updated by QA et. all as we rotate out what is tested, and could be a clear ground truth.
* We could also put this directly into the `phet-development-overview.md`.

What do people think? Marking for dev meeting

**Comment by mattpen** [comment]
@ariel-phet will create a document that lists the browsers we support in phet-info.

**Comment by ariel-phet** [comment]
@zepumph the more I think about this, why don't we link to the example testing matrix? I believe I brought that up, but for some reason people maybe didn't think it was a good idea

https://docs.google.com/spreadsheets/d/1jl8z3MjmGBeU_Z5voMIN-rBF9al6LNyey9ZIuOpoUzA/edit#gid=26937364

That is really the ground truth document. Whenever we add or remove a platform, that is where we do it. Having a separate document just seems like a maintenance burden where things are likely to get out of sync. if you can convince me there is value in a second document we can revisit, but if not, lets just link that example test matrix in the necessary places.

**Comment by zepumph** [comment]
I think that the important piece is to make sure that the whole world has read access to it. I'm not sure that is set up at this time.

**Comment by ariel-phet** [comment]
Document here: https://github.com/phetsims/phet-info/blob/master/doc/supported-browsers.md

Closing
