### ISSUE TITLE
Mockup for new geometry sim for upcoming grant proposal

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/tasks#1045]
Tagging @amanda-phet and @arouinfar for this first. This will be similar in nature to what @amanda-phet created for the last proposal.

@emily-phet is working on a new grant proposal and we were hoping for a quick-ish turnaround for another basic, sketchy mockup for a sim idea we have with all of the usual PhET elements. This will be used as a figure in the proposal with some explanatory text about the premise. Ideally, we could have the mockup made by early-middle next week!

The premise here is on the manipulation of quadrilateral shapes (between rectangles, parallelogram, etc) through change side lengths and angles (through corner/side dragging, stretching, pinching, etc)  while comparing against known shapes (e.g. from a toolbox of previously created shapes). Possible readouts include, but are not limited to, toggling on angles or side lengths. 

I don't have a very good mockup for this one this time, so this will require a meeting to chat and try to generate the first mockup. I can be available any time the remainder of this week and Monday next week.

Feel free to assign/unassign/reassign as needed, ask me any questions, and thank you!

I'm copying in some text that Emily had previously written to help ideate the sim, but I will stress that this is more theoretical, less concrete with respect to how the sim mockup will end up and we should use discussion time to anchor the design:

> 6.3 Learning Tools In interviews, participants will use one or more of the following three learning tools, introduced previously in Section 2, described here detailing the design rationale, learner task structure, and multimodal affordances provided. Each of the following new geometry learning tools will present learners with an interactive four-sides shape (quadrilateral). When dragging any of the shapes’ vertices or edges, it remains quadrilateral. Each embody a distinct scaffolding design rationale. We anticipate these design rationale differ in terms of their consequences for the user’s agency, movement, reasoning, and, potentially, learning through manipulating the mathematical structures displayed. The rationale of the proposal to compare between “hard” and “soft” constraints as these contribute to the emergence of mathematical ontologies. 
>  
> Quadrilateral 1 will present learners with a quadrilateral that is initially a parallelogram (i.e., with opposite sides parallel). No matter how one reconfigures it, the shape responds such that it always remains a parallelogram. The learner’s task is to describe the object’s invariant properties, that is, to characterize what it is about this object that remains constant (consistent, conserved, “the same”) across all its states one generates. In a sense, the learner is asked to compose a declarative idea of what this object “is”.  This design utilizes what we might call hard constraints: a priori environmental constraints on movement that the designer encodes and the user is to discern. The user need not exercise agency in keeping the mathematical ontology intact: No matter how the user moves (drags) elements in the structure, the conceptual organization of the structure remains intact. In this design rational, the designer constructs constraints on possible movement. This design approach harkens back to early reform-oriented pedagogical regimens of offering children prefabricated concrete materials. The child is to develop new concepts through inquiry-oriented manipulation, where the focal phenomenon is the object (Froebel, 1885/2005; Montessori, 1949/1967).  
>  
> Quadrilateral 2 will present learners with a quadrilateral that is initially not a parallelogram. As the learner reconfigures it, feedback is provided (e.g., color change, sound, and/or vibration) whenever the shape happens to be a parallelogram. The learner is tasked initially to find the ‘positive’ feedback and then to maintain the ‘positive’ feedback. This design bears what we might call, by way of contrast, soft constraints: ad hoc task constraints on movement that the user discovers and self imposes. Moving under these self-imposed constraints, the user self-organizes to receive continuous positive feedback in performing the assigned motor-control task of transitioning between permissible configurations of the display. The students are tasked to manipulate the shape such that a particular goal state (feedback) be achieved and maintained. In the course of this work, an imaginary perceptual structure, the attentional anchor (Abrahamson, Shayan, Bakker, Van der Schaaf, 2016), may emerge on the students’ sensorimotor interface with the environment. The students, who are further invited to describe their strategy, may refer directly to this new object they are perceiving and explain how they are handling it. Here, the process of articulating the strategy unfolds through specifying what one is keeping constant to operate the apparatus. That is, the stable mathematical attributes of the system come forth as ontologies (what is) through the enacting, attending to, and/or describing sensorimotor actions (what I am doing). There is no a priori object beyond the flexible figural form. Rather, the object takes shape as an entity that materializes from discovered patterns in enactment of an assigned task, as the student works through the enactment of a new movement form (Varela, Thompson, & Rosch, 1991).

**Comment by arouinfar** [comment]
This may be more up @amanda-phet's alley, but if she's unavailable, I can meet with @BLFiedler on Friday to discuss.

**Comment by BLFiedler** [comment]
Amanda has agreed to take it up! Meeting tomorrow to discuss.

**Comment by amanda-phet** [comment]
Feedback from @emily-phet on 9/10/20: 

* Remove sim name from the lower left corner of both
* In the yellow-background example, let's have the right-side panel be taller and wider, as if the person dragged the upper right vertex up and to the right. That makes it clear that horizontal and vertical shifts result in accommodating changes to result in a parallelogram.
* For the blue background example, we need the left side screen background to be green (use the RaP green), and the right side background to be...something else. Can be anything, probably when we make it we will start by trying the same paradigm we have for RaP, where in proximity you get shades of green, but far away you get white. Who knows if it will work, or if we'll need to try a different approach (only green exactly at parallelogram, red elsewhere...?) but just some thoughts.
* If the nav bar + PhET icon could be larger, that would be ideal. Imagine we're making an icon of the mockup, rather than a typical mockup, since the size of each final mockup will need to be small on the page.
* Removed the option to have two shapes from the mockup used in the proposal. I think that makes it more clear the basic idea, and not something hard to see at small sizes  (though I think we'll still need those when we make the real ones).
* The text/icons on the upper right need to be much larger. Right now they're imperceptible at small image sizes. Maybe go to just checkbox + icon, and we'll add a sentence indicating what they are in the text.

**Comment by amanda-phet** [comment]
![parallelogram-sim_1](https://user-images.githubusercontent.com/7852916/93104817-9205ab00-f66b-11ea-8501-288c6bc7721e.png)
![parallelogram-sim_2](https://user-images.githubusercontent.com/7852916/93104819-929e4180-f66b-11ea-95d3-39cde2eb3567.png)
![parallelogram-sim_3](https://user-images.githubusercontent.com/7852916/93104820-929e4180-f66b-11ea-9c9c-6f202d0ddbab.png)
![parallelogram-sim_4](https://user-images.githubusercontent.com/7852916/93104822-929e4180-f66b-11ea-9dd5-2f523b9b9cd9.png)

I've made a version with hands to show the interaction.. I think it can be helpful, but it's just an alternative if you want to use it. 

![parallelogram-sim-alt_2](https://user-images.githubusercontent.com/7852916/93105045-d5601980-f66b-11ea-9636-c486f6a10cac.png)
![parallelogram-sim-alt_4](https://user-images.githubusercontent.com/7852916/93105047-d5f8b000-f66b-11ea-993d-4319569c7006.png)

**Comment by BLFiedler** [comment]
I believe this is complete for now with some additional work coming from an external designer.

**Comment by BLFiedler** [comment]
Reopening this rather than creating a new issue - we have a few modifications we'd like to make to this "quadrilaterals" sim to expand it to a "Shapes" sim for (yet) another grant we are submitting soon!

Without getting too fancy (will be a rather small image), the plan will be to change to another shape, possibly one more control added, and to make some minor color changes.

@amanda-phet Let me know if you'd like to take this on again and have a quick chat about it! Otherwise, we can open it up.

**Comment by amanda-phet** [comment]
Three options: radio buttons, "scene selection" radio buttons, and three screens. 

Please let us know what else you'd like here.. different color, checkbox options, etc. 
![image](https://user-images.githubusercontent.com/7852916/94844139-04e88300-03db-11eb-9e02-1e4f32158dea.png)

**Comment by amanda-phet** [comment]
@emily-phet this is for your review!

**Comment by BLFiedler** [comment]
@amanda-phet  Thanks again! Can we take the first image and just make the numbers a bit bigger (just for show) as the image will be about this small: 
![image](https://user-images.githubusercontent.com/47331395/95111215-6cb10d80-06fc-11eb-823c-380407580d70.png)

Perhaps two font sizes up? (or whatever looks good without looking comical or obtrusive) and any necessary adjustments to the radio button size/spacing that makes sense to fit in the text size change. And then I just need the high quality (slash large) source image and we're good! 

Thank you!

**Comment by amanda-phet** [comment]
![shapes-triangle-05](https://user-images.githubusercontent.com/7852916/95114886-dc75c700-0701-11eb-991b-2374f451fd2d.png)
