### ISSUE TITLE
Convert simulations to ES6/class

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1050]
Similarly to #1044, we would now like to investigate converting simulation repos to use ES6/class/arrow functions/`this` instead of `self`/const, etc.  @jonathanolson demonstrated a utility he developed to assist in this task.  @ariel-phet asked me to create a checklist issue in the tasks repo to track each developer porting one simulation forward by Thursday Oct 22.

- [x] @pixelzoom (all sims have been converted to ES6)
- [x] @samreid (Fraction Comparison)
- [x] @Denz1994 
- [x] @zepumph 
- [x] @jonathanolson 
- [x] @jessegreenberg 
- [x] @jbphet (Faraday's Law)
- [x] @chrisklus 
- [x] @phetsims/research-partners 

@ariel-phet can you please review the developer list?  I'm not sure if everyone should be on there, or if I've missed someone.  Also, I discovered GitHub issues have a max of 10 assignees, so I was unable to assign @shreyas-g-ucb.

UPDATE: I finished a sim, so I unassigned myself, and that made room for @shreyas-g-ucb.

UPDATE: For the record, at the time of this issue creation, we had 3119 occurrences of `class ... extends` and 887 occurrences of `inherit( `

EDIT: Saurabh and Brandon removed

**Comment by samreid** [comment]
I used the Sublime script to convert fraction-comparison, and it went very smoothly.  There was one occurrence of `this` before `super`, and I manually fixed some whitespace near the constructor jsdoc (added a blank line before it).  I manually converted a few `var` to `const`, and everything else looked great, nice work @jonathanolson.

**Comment by samreid** [comment]
I finished my remaining sim.  We are down to 868 occurrences of `inherit( `.

**Comment by zepumph** [comment]
>each developer porting one simulation forward by Thursday Oct 22.

With this timeline, I would like to promote priority.

**Comment by mattpen** [comment]
I removed Shreyas because he is not currently working for us.  

I haven't worked on the sim development since mid-2016.  Is there a quick guide to what needs to be done for me to complete work on a sim?  If not, it may be more efficient to remove me from this list.

**Comment by samreid** [comment]
I noted that @mattpen wasn't listed in https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md, so I'm going to check him off and unassign.  Sorry for the confusion!

**Comment by ariel-phet** [comment]
Marking to check in for dev meeting

**Comment by jbphet** [comment]
I've ported Faraday's Law using the script.  The script is awesome, and I think I may use it to port a sim or two a week until mine are all done. Thanks @jonathanolson.  Unassigning myself.

**Comment by zepumph** [comment]
The plugin can be found at https://github.com/phetsims/phet-sublime-plugin

**Comment by zepumph** [comment]
That was tremendously pleasant. My experience in Friction, and involved going to each file in the `js/` directory that wasn't already a class, and running the "Phet: Classify" command from the sublime command palette. I found that no extra steps had be done after that for the sim to successfully run. I think my preferred mode of using this would be to apply this to a whole directory, instead of just file by file. Especially as a webstorm user, I would prefer to run it on everything, and then go back to webstorm and review the changes. 

Good work @jonathanolson, thanks for implementing this.

**Comment by Denz1994** [comment]
Similar story to @zepumph's comment above. 

I ended up using Sublime to avoid any potential Intellij compatibility issues. Masses and Springs converted nicely. Capacitor-Lab-Basics still required additional workarounds due to using `this` before the `super` call but that is a sim specific implementation detail and not related to @jonathanolson's tool. Great tool overall.

**Comment by jessegreenberg** [comment]
I used the plugin on trig-tour using Sublime Text 3, it was great and saved a ton of time. I had to do very few things manually, they were
- Required visibility annotations that became eslint errors after the switch, there is no way to automate that.
- It didn't add a space between the class declaration and constructor documentation.
- Occasionally it didn't change `SuperType.call` -> `super`. I am pretty sure it missed the places where there was a comment above the `SuperType.call`.

**Comment by mattpen** [comment]
@ariel-phet will create a chip-away issue to apply the change to all sims.

@jonathanolson will try to address some of the above comments.

**Comment by zepumph** [comment]
I was able to have success converting all js files recursively in a directory using this script after you cd to that dir (like `js/` in a sim repo). Running on git bash on windows. You can just change the path to the classify script as needed.

`find ./ -maxdepth 100 -iname '*.js'  -type f -exec python /c/Users/MyUser/AppData/Roaming/Sublime\ Text\ 3/Packages/phet-sublime-plugin/classify.py {} \;`

**Comment by chrisklus** [comment]
I converted Plinko Probability and Color Vision above. Thanks @jonathanolson! And thanks @zepumph for the recursive suggestion in https://github.com/phetsims/tasks/issues/1050#issuecomment-714743901 - that worked very well for me.

**Comment by zepumph** [comment]
I think all that is left in this issue are the improvements to classify.py, like https://github.com/phetsims/tasks/issues/1050#issuecomment-714583971

**Comment by jonathanolson** [comment]
No need to handle the python bits, I'm not using them in Sublime anymore. Closing.
