### ISSUE TITLE
Converting all sims to ES6

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#1051]
The dev team agreed it would be good for the (code) health of the project to convert all simulations to ES6

## HTML5 Sims Conversion Party List

- [x]  Acid-Base Solutions | @pixelzoom 
- [x]  Area Builder | @jbphet 
- [x]  Area Model Algebra | @jonathanolson 
- [x]  Area Model Decimals | @jonathanolson 
- [x]  Area Model Introduction | @jonathanolson 
- [x]  Area Model Multiplication | @jonathanolson 
- [x]  Arithmetic  | @jbphet  
- [x]  Atomic Interactions  | @jbphet  
- [x]  Balancing Act  | @jbphet 
- [x]  Balancing Chemical Equations  | @pixelzoom 
- [x]  Balloons and Static Electricity  | @jessegreenberg  
- [x]  Beer's Law Lab  | @pixelzoom  
- [x]  Bending Light  | @samreid 
- [x]  Blackbody Spectrum  | @jbphet  
- [x]  Blast | @samreid 
- [x]  Build a Fraction | @jonathanolson 
- [x]  Build a Molecule | @denz1994
- [x]  Build an Atom  | @jbphet
- [x]  Buoyancy | @jonathanolson
- [x]  Calculus Grapher | @jonathanolson
- [x]  Capacitor Lab: Basics | @denz1994
- [x]  Chains | @pixelzoom 
- [x]  Charges And Fields | @jonathanolson 
- [x]  Circuit Construction Kit: AC | @samreid
- [x]  Circuit Construction Kit: Black Box Study | @samreid 
- [x]  Circuit Constructor Kit: DC | @samreid
- [x]  Circuit Constructor Kit: DC - Virtual Lab| @samreid 
- [x]  Collision Lab | @jonathanolson 
- [x]  Color Vision | @chrisklus
- [x]  Concentration |  @pixelzoom 
- [x]  Coulomb's Law | @zepumph 
- [x]  Curve Fitting | @jonathanolson 
- [x]  Density | @jonathanolson
- [x]  Diffusion | @pixelzoom 
- [x]  Eating, Exercise, and Energy | @samreid 
- [x]  Energy Forms and Changes | @chrisklus
- [x]  Energy Skate Park |  @jessegreenberg 
- [x]  Energy Skate Park: Basics |  @samreid 
- [x]  Equality Explorer | @pixelzoom
- [x]  Equality Explorer: Basics | @pixelzoom
- [x]  Equality Explorer: Two Variables | @pixelzoom 
- [x]  Estimation | @jbphet
- [x]  Example Sim | @pixelzoom 
- [x]  Expression Exchange |  @jbphet  
- [x]  Faraday's Law |  @jbphet 
- [x]  Fluid Pressure and Flow | @zepumph 
- [x]  Forces and Motion: Basics |  @samreid 
- [x]  Fourier: Making Waves |  @pixelzoom
- [x]  Fraction Comparison | @samreid
- [x]  Fraction Matcher | @jonathanolson
- [x]  Fractions: Equality | @jonathanolson 
- [x]  Fractions: Intro | @jonathanolson
- [x]  Fractions: Mixed Numbers | @jonathanolson 
- [x]  Friction | @zepumph
- [x]  Function Builder | @pixelzoom 
- [x]  Function Builder: Basics | @pixelzoom 
- [x]  Gas Properties | @pixelzoom
- [x]  Gases Intro | @pixelzoom
- [x]  Gene Expression Essentials | @jbphet
- [x]  Greenhouse Effect | @samreid
- [x]  Graphing Lines | @pixelzoom  
- [x]  Graphing Quadratics | @pixelzoom 
- [x]  Graphing Slope-Intercept | @pixelzoom
- [x]  Gravity And Orbits | @jessegreenberg 
- [x]  Gravity Force Lab |  @zepumph  
- [x]  Gravity Force Lab: Basics | @zepumph
- [x]  Hooke's Law | @pixelzoom
- [x]  Inverse Square Law Common | ???
- [x]  Isotopes and Atomic Mass | @jbphet
- [x]  John Travoltage |  @samreid
- [x]  Least-Squares Regression |  @jonathanolson 
- [x]  Make a Ten |  @jonathanolson  
- [x]  Masses and Springs | @Denz1994 
- [x]  Masses and Springs: Basics | @Denz1994 
- [x]  Models of the Hydrogen Atom | @pixelzoom
- [x]  Molarity | @zepumph
- [x]  Molecules and Light | @jessegreenberg 
- [x]  Molecule Polarity | @pixelzoom 
- [x]  Molecule Shapes |  @jonathanolson 
- [x]  Molecule Shapes: Basics |  @jonathanolson 
- [x]  My Solar System |  @jonathanolson 
- [x]  Natural Selection | @pixelzoom
- [x]  Neuron |  @zepumph 
- [x]  Normal Modes | @jonathanolson
- [x]  Number Line: Distance |  @jbphet 
- [x]  Number Line: Integers |  @jbphet  
- [x]  Number Line: Operations |  @jbphet
- [x]  Number Play | @Denz1994 
- [x]  Ohm's Law|  @zepumph 
- [x]  Optics Lab | @veillette
- [x]  Pendulum Lab | @jonathanolson 
- [x]  pH Scale |  @pixelzoom 
- [x]  pH Scale: Basics |  @pixelzoom  
- [x]  PhET-iO Test Sim |  @chrisklus 
- [x]  Plinko Probability | @chrisklus  
- [x]  Projectile Motion | @jbphet 
- [x]  Proportion Playground |  @jonathanolson  
- [x]  Ratio and Proportion | @zepumph
- [x]  Reactants, Products and Leftovers |  @pixelzoom  
- [x]  Resistance in a Wire |  @zepumph 
- [x]  Rutherford Scattering |  @jessegreenberg 
- [x]  Simula Rasa | @pixelzoom 
- [x]  States of Matter |  @jbphet  
- [x]  States of Matter: Basics |  @jbphet  
- [x]  Trig Tour |  @jessegreenberg 
- [x]  Under Pressure |  @samreid 
- [x]  Unit Rates |  @pixelzoom  
- [x]  Vector Addition | @pixelzoom 
- [x]  Vector Addition: Equations | @pixelzoom 
- [x]  Wave Interference | @samreid 
- [x]  Wave on a String |  @jonathanolson  
- [x]  Waves Intro | @samreid 
- [x]  Wilder | @jonathanolson
- [x]  X-ray Diffraction | @heldentodd 

NOTE
- [x] https://github.com/phetsims/tasks/issues/1051 should be taken off hold when this issue is complete and assigned

**Comment by chrisklus** [comment]
Assuming this is a continuation of https://github.com/phetsims/tasks/issues/1050, I checked off what I converted over there.

**Comment by zepumph** [comment]
All of my sims have been done. I also checked off optics-lab, which seemed to already be done (classify.py didn't change anything). I also converted Projectile Motion because I was in that sim last.

**Comment by samreid** [comment]
@jbphet will review the unchecked sims to see if they need to be updated.  He will also look at doing more than one a week, so we can finish sooner rather than later.

@ariel-phet: I'd like to have this polished off early in January.

**Comment by zepumph** [comment]
We reallocated some assignments to try to get this done by next week. Good luck us!

**Comment by samreid** [comment]
I finished greenhouse and forces-and-motion basics.

**Comment by zepumph** [comment]
neuron complete, see https://github.com/phetsims/neuron/issues/146.

**Comment by Denz1994** [comment]
Number-Play complete.

**Comment by jessegreenberg** [comment]
I just finished rutherford-scattering and inverse-square-law-common, removing my assignment.

**Comment by pixelzoom** [comment]
12/10/2020 dev meeeting

* @jbphet will be done by the end of the week
* @jonathanolson is checking my-solar-system now

When this issue is done, @jbphet will label open associated issues (e.g. phetsims/phet-info#143) for dev meeting.

**Comment by jbphet** [comment]
I think I've finished off the last ones.  We should take one more look at this in developer meeting to make sure we haven't missed anything, and then close this pup.
