### ISSUE TITLE
Artwork for proposal

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#1073]
Looking for an artist to do some last-minute artwork. Involves drawing hands.

@clmccutchan - would you be available. Would need the artwork done as soon as possible - proposal is due Monday.

**Comment by clmccutchan** [comment]
@emily-phet I've got two other projects due Monday and can't take on anything else. I can reach out to the illustrator I use as a subcontractor.

**Comment by emily-phet** [comment]
@clmccutchan - thanks for the quick response, and suggestion. The artist I usually work with was able to come through at the last minute, and we were able to get it done in time. :) 

Closing issue now.
