### ISSUE TITLE
Verify public query parameters 

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tasks#1076]
From https://github.com/phetsims/chipper/issues/1002.

Please go through and verify any public query parameters for your sims by marking them as `public: true`.
Then, please update your sims in this spreadsheet: https://docs.google.com/spreadsheets/d/1TddeTtD8zAayJzs02g0fL7dR1iWYczs1CMFdYd3SBNc/edit#gid=0

- [x] Acid-Base Solutions | @pixelzoom
- [x] Area Builder | @jbphet
- [x] Area Model Algebra | @jonathanolson 
- [x] Area Model Decimals | @jonathanolson 
- [x] Area Model Introduction | @jonathanolson 
- [x] Area Model Multiplication | @jonathanolson 
- [x] Arithmetic  | @jbphet
- [x] Atomic Interactions  | @jbphet 
- [x] Balancing Act  | @jbphet
- [x] Balancing Chemical Equations  | @pixelzoom 
- [x] Balloons and Static Electricity  | @jessegreenberg 
- [x] Beer's Law Lab  | @pixelzoom
- [x] Bending Light  | @samreid 
- [x] Blackbody Spectrum  | @jbphet 
- [x] Blast | @samreid
- [x] Build a Fraction | @jonathanolson 
- [x] Build a Molecule | @jonathanolson 
- [x] Build an Atom  | @jbphet
- [x] Buoyancy | @jonathanolson 
- [x] Calculus Grapher | @jonathanolson 
- [x] Capacitor Lab: Basics | @jonathanolson 
- [x] Chains |
- [x] Charges And Fields | @jonathanolson 
- [x] Circuit Construction Kit: AC | @samreid 
- [x] Circuit Construction Kit: AC - Virtual Lab | @samreid 
- [x] Circuit Construction Kit: Black Box Study | @samreid
- [x] Circuit Constructor Kit: DC | @samreid
- [x] Circuit Constructor Kit: DC - Virtual Lab| @samreid 
- [x] Collision Lab | @jonathanolson
- [x] Color Vision | @chrisklus
- [x] Concentration |  @pixelzoom 
- [x] Coulomb's Law | @zepumph
- [x] Curve Fitting | @jonathanolson 
- [x] Density | @jonathanolson
- [x] Diffusion | @pixelzoom 
- [x] Eating, Exercise, and Energy | @samreid 
- [x] Energy Forms and Changes | @chrisklus 
- [x] Energy Skate Park |  @jessegreenberg 
- [x] Energy Skate Park: Basics |  @samreid 
- [x] Equality Explorer | @pixelzoom
- [x] Equality Explorer: Basics | @pixelzoom 
- [x] Equality Explorer: Two Variables | @pixelzoom 
- [x] Estimation | @jbphet
- [x] Example Sim | @pixelzoom
- [x] Expression Exchange |  @jbphet 
- [x] Faraday's Law |  @jbphet
- [x] Fluid Pressure and Flow | @zepumph 
- [x] Forces and Motion: Basics |  @jessegreenberg 
- [x] Fourier: Making Waves |  @pixelzoom
- [x] Fraction Comparison | @samreid
- [x] Fraction Matcher | @jonathanolson 
- [x] Fractions: Equality | @jonathanolson 
- [x] Fractions: Intro | @jonathanolson
- [x] Fractions: Mixed Numbers | @jonathanolson 
- [x] Friction | @zepumph
- [x] Function Builder | @pixelzoom 
- [x] Function Builder: Basics | @pixelzoom 
- [x] Gas Properties | @pixelzoom
- [x] Gases Intro | @pixelzoom
- [x] Gene Expression Essentials | @jbphet 
- [x] Greenhouse Effect | @jbphet
- [x] Graphing Lines | @pixelzoom 
- [x] Graphing Quadratics | @pixelzoom 
- [x] Graphing Slope-Intercept | @pixelzoom 
- [x] Gravity And Orbits | @jessegreenberg 
- [x] Gravity Force Lab |  @zepumph
- [x] Gravity Force Lab: Basics | @zepumph 
- [x] Hooke's Law | @pixelzoom
- [x] Isotopes and Atomic Mass | @jbphet 
- [x] John Travoltage |  @samreid
- [x] Least-Squares Regression |  @jonathanolson 
- [x] Make a Ten |  @jonathanolson
- [x] Masses and Springs | @chrisklus 
- [x] Masses and Springs: Basics | @chrisklus 
- [x] Models of the Hydrogen Atom | @pixelzoom 
- [x] Molarity | @zepumph
- [x] Molecules and Light | @jessegreenberg 
- [x] Molecule Polarity | @pixelzoom
- [x] Molecule Shapes |  @jonathanolson 
- [x] Molecule Shapes: Basics |  @jonathanolson 
- [x] My Solar System |  @jonathanolson
- [x] Natural Selection | @pixelzoom
- [x] Neuron |  @jbphet
- [x] Normal Modes | @jonathanolson
- [x] Number Line: Distance |  @jbphet
- [x] Number Line: Integers |  @jbphet 
- [x] Number Line: Operations |  @jbphet
- [x] Number Play | @chrisklus
- [x] Ohm's Law|  @zepumph
- [x] Optics Lab | @veillette
- [x] Pendulum Lab | @jonathanolson 
- [x] pH Scale |  @pixelzoom
- [x] pH Scale: Basics |  @pixelzoom 
- [x] PhET-iO Test Sim |  @chrisklus
- [x] Plinko Probability | @chrisklus 
- [x] Projectile Motion | @jbphet
- [x] Proportion Playground |  @jonathanolson 
- [x] Ratio and Proportion | @zepumph
- [x] Reactants, Products and Leftovers |  @pixelzoom 
- [x] Resistance in a Wire |  @zepumph
- [x] Rutherford Scattering |  @jessegreenberg 
- [x] Simula Rasa | @pixelzoom
- [x] States of Matter |  @jbphet 
- [x] States of Matter: Basics |  @jbphet 
- [x] Trig Tour |  @jessegreenberg
- [x] Under Pressure |  @samreid 
- [x] Unit Rates |  @pixelzoom 
- [x] Vector Addition | @pixelzoom 
- [x] Vector Addition: Equations | @pixelzoom 
- [x] Wave Interference | @samreid
- [x] Wave on a String |  @jonathanolson 
- [x] Waves Intro | @samreid
- [x] Wilder | @jonathanolson
- [x] X-ray Diffraction | @heldentodd

**Comment by pixelzoom** [comment]
Changes that I made to the spreadsheet:

(1) I added "JavaScript file" column, where you should indicate the name of the .js file containing the sim-specific query parameters.

(2) I deleted the "Private Query Parameters" column.  Some of my sims have dozens of private query parameters, and I don't think it's necessary or desirable to reproduce them here.  If anyone is interested in the private query parameters, see the JavaSript file -- any query parameters not marked `public: true` are private.

**Comment by pixelzoom** [comment]
I've completed my sims. I'm responsible for 28 sims, and there are only 12 unique sim-specific query parameters.  All public common-code query parameters are applicable to all of my sims, with the exception of single-screen sims where `homeScreen` is irrelevant.

**Comment by pixelzoom** [comment]
In the spreadsheet "Javascript file" column, I linked the filenames to the source files in GitHub, so you can quickly navigate to see the complete set of query parameters in a file.   And that are not marked `public: true` are private by default.

**Comment by jbphet** [comment]
I followed the precedents established by @pixelzoom, and have entered the sims for which I'm the responsible developer into the spreadsheet.

**Comment by jonathanolson** [comment]
Are all phet-io customization query parameters public? Not sure how to handle the `?switch` query parameter in https://github.com/phetsims/capacitor-lab-basics/blob/master/js/common/CLBQueryParameters.js.

**Comment by zepumph** [comment]
I'm not sure if this is correct, but I thought that `public` query parameters were those which we would feel comfortable releasing for general consumption, and not just for a single client's request for customizations. For example `?standford` for Balancing Act isn't marked as public. 

As for `switch` in particular, I'd ask a designer. My guess is that it is general, and not just for a single customization, but I'm not sure.

**Comment by jonathanolson** [comment]
Sounds good! I'm mainly running into query parameters where I don't know if they should be public or not. My remaining items are:

- `switch` in capacitor-lab-basics
- `exploreNumbers` in make-a-ten
- `scene` in proportion-playground
- `showOuterLonePairs` in molecule-shapes (+basics)

I've asked designers for input.

**Comment by samreid** [comment]
I'm not familiar with the make-a-ten query parameter.  

For Capacitor Lab: Basics, it may be generally useful as public, but I would recommend to be conservative--leave it marked as private until we know more or have a specific client request or design discussion.

For Proportion Playground, I think that was designed for debugging.

I'm not sure about molecule shapes.

**Comment by jessegreenberg** [comment]
@samreid I wasn't sure about `?showItemToolboxes` in FAMB, should that be public? https://github.com/phetsims/forces-and-motion-basics/issues/215

**Comment by jessegreenberg** [comment]
Reviewed my sims and updated spreadsheet. Only public param was in energy-skate-park which @samreid marked in https://github.com/phetsims/energy-skate-park/commit/e4fb9273b8162a21e27ba59549493f7963457c7e, thanks!

**Comment by pixelzoom** [comment]
@jessegreenberg There are no entries in the spreadsheet for FAMB and MAL.

**Comment by pixelzoom** [comment]
@jessegreenberg There are no entries in the spreadsheet for FAMB, GAO, and MAL.

**Comment by jessegreenberg** [comment]
Thanks! For FAMB I wasn't sure, see https://github.com/phetsims/tasks/issues/1076#issuecomment-769280157.

**Comment by pixelzoom** [comment]
@jessegreenberg OK.  But ForcesAndMotionBasicsQueryParameters.js exists and should be in the spreadsheet, so I've added it.

**Comment by chrisklus** [comment]
I didn't see anything for `chains` and Optics Lab so I crossed those off

**Comment by samreid** [comment]
> @samreid I wasn't sure about ?showItemToolboxes in FAMB, should that be public? phetsims/forces-and-motion-basics#215

That seems like it should remain private.  It has a very specific use when combined with other PhET-iO customizations.

**Comment by samreid** [comment]
The fractions suite is checked off above but empty in the spreadsheet.  I didn't see any files matching "fmquer" so perhaps it doesn't have query parameters, and I didn't see anything in the fractions-common repo.   So I'll mark "none" for those on the spreadsheet.

Therefore it seems like this issue can be closed, and we will continue in https://github.com/phetsims/chipper/issues/1002
