### ISSUE TITLE
Circuit Construction Kit: DC & DC "Virtual Lab" 1.2.0

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1078]
https://github.com/phetsims/QA/issues/610

> I published the 1.2 versions of the sims. @arouinfar do we need to update metadata on the website?
> 
> @oliver-phet and @arouinfar discussed that we may need to reach out to clients or people that have written in to phethelp. Please feel free to open a separate issue as appropriate.

**Comment by arouinfar** [comment]
@oliver-phet new features include:

* Non-ohmic, "real" bulb accessible in the Advanced options on the Lab screen. To include by default, use the `addRealBulbs`  query parameter.
* Support for displaying IEC schematic circuit components, accessible in PhET Menu > Options, or by using `schematicStandard=iec` query parameter.
* Support for Zoom and Magnfication, which will ease access on smaller touch screens.

**Comment by oliver-phet** [comment]
English email sent 2/26/2021.
