### ISSUE TITLE
Should we prefer absolute issue URLs to shorthand issue references in commit messages?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1081]
From https://github.com/phetsims/phet-io-wrappers/issues/402#issuecomment-805990700, @jessegreenberg and I identified that not all associated commits were showing up in the issue history, because some were listed as:

phetsims/repo/issues#NNN

and some were listed as 

phetsims/repo#NNN

![image](https://user-images.githubusercontent.com/679486/112355083-f052bc80-8c92-11eb-9ac2-dc225a2253a1.png)

This the commit references in the issue cannot be used to list which commits need to be cherry-picked, since they do not all appear.

We also noticed that WebStorm history view has good support for hyperlinks in commit messages, making it easy to navigate to an issue from a commit.  I use this feature frequently.  @jessegreenberg and I checked in other repos and found that most developers usually use the issue URL, here is an example of @pixelzoom @zepumph and @samreid commits from natural selection:

![image](https://user-images.githubusercontent.com/679486/112353851-c5b43400-8c91-11eb-8033-06a62aa0b51c.png)

It looks like @jonathanolson typically uses the full URL (when referring to a scenery issue from a scenery commit). @jbphet tambo commits typically use the full tambo issue URL.  @pixelzoom commits in fourier are a mix:

![image](https://user-images.githubusercontent.com/679486/112355608-71aa4f00-8c93-11eb-8edb-a64084d5375c.png)

So it appears that most of the team often uses the full issue URL, should we reaffirm the value of this and encourage all team members to use this pattern?  Should we allow exceptions, for instance, if some developers recommend `#NNN` syntax for commits that are in the same repo as the issue (as long as we are careful that they don't creep into multi-repo commits)?

**Comment by pixelzoom** [comment]
I typically use the short form (just the issue number) if the commit involves 1 repo, the associated GitHub issue is in the same repo as the commit, and I don't have the full URL handy.   I'm not excited about having to go find the full URL every time I commit.  It will be a tiny bit of additional time (and cost to PhET) on every commit.  But if that's what PhET wants, that's what I'll do.

**Comment by zepumph** [comment]
In general my first impression here is that it should be up to developer discretion.

>I identified that not all associated commits were showing up in the issue history, because some were listed as:

This is just because the syntax is incorrect. Instead of phetsims/phet-io-wrappers/issues#402, github expects phetsims/phet-io-wrappers#402 (note how github shows the hyperlink on the second). Looks like it is correct for https://github.com/phetsims/phet-io-wrappers/commit/35a6233a2297c67bbaac42d2a193a22f02d8c8e2, and a mistake was made in some like https://github.com/phetsims/phet-io-wrappers/commit/e03a62beec7312f01de96fb89a8541c28021d743.


>We also noticed that WebStorm history view has good support for hyperlinks in commit messages, making it easy to navigate to an issue from a commit.

In my Webstorm, I can easily press a keybinding I made for the "Open on Github" command which takes me to the commit on github. From here it is easy to click on the now hyperlinked.

To me, this whole thing is a non issue. Devs should feel free to link issues however they see best. If this issue is to double down on making a more rigid process because of the fact that @jessegreenberg messed up a commit message issue link, then I don't agree with it.

**Comment by samreid** [comment]
> In my Webstorm, I can easily press a keybinding I made for the "Open on Github" command which takes me to the commit on github. From here it is easy to click on the now hyperlinked.

Thanks, I tried out a keystroke for that and it seems nice!  UPDATE: it worked on some commits but not others, and I cannot see why.

> I typically use the short form (#NNN) if the commit involves 1 repo, the associated GitHub issue is in the same repo as the commit, and I don't have the full URL handy.

I do not want to encourage a rigid process that will slow down or inconvenience any developer.  Personally, I have settled into a pattern that feels like negligible overhead, and it is nice to be able to have the hyperlink from the history view directly--I don't see a use case for wanting to navigate to the commit page, unless as a stepping stone.

Using the issue number shorthand seems liable to error--I have seen numerous commits that refer to the wrong issue because they use the `#NNN` shorthand and were committed in the wrong repo.  For instance, the commit in this issue is incorrect: https://github.com/phetsims/joist/issues/72.  Is this error rate already below a tolerable threshold? It's hard to say because we don't know how often this is happening.

**Comment by zepumph** [comment]
What's the difference between saying, as a dev team, "stop messing up issue links" as opposed to, as a team, saying, "you must use a github URL always"? I feel like one leaves devs available to do what they feel works best for them. 

BTW, for my personal workflow, I have no strong preference here, I use URLs about 95% of the time.

**Comment by samreid** [comment]
> UPDATE: it worked on some commits but not others, and I cannot see why.

To elaborate, some commits have the "Open on GitHub"

![image](https://user-images.githubusercontent.com/679486/112365741-999eb000-8c9d-11eb-97b6-c7de4466caee.png)

but some did not.  I checked through a number of commits and they all had it--not sure what happened before, but more things were grayed out and the "Open on GitHub" wasn't even appearing.

> What's the difference between saying, as a dev team, "stop messing up issue links" as opposed to, as a team, saying, "you must use a github URL always"?

Having correct issue links seems important, and maybe URLs is one way (not necessarily the best or only way) to reduce that error rate.  And clicking on a URL in the history view is ever so slightly easier than "CTRL+OPT+CMD+G then click on the issue URL".  But I'm happy to live with that if it's our consensus.

**Comment by pixelzoom** [comment]
@samreid said:
> ... Having correct issue links seems important, ...

How do you propose to verify that links are "full" and "correct"?

**Comment by samreid** [comment]
I do not recommend verifying that links are full and correct, the questions are mainly:

* Is our current error rate at an acceptable level?
* If not, is there something easy we can to to increase accuracy without hampering developer's workflow?

**Comment by pixelzoom** [comment]
During sim development, I make hundreds of commits that are unrelated to a GitHub issue. So I'm also wondering how you're going to determine when a commit message needs to mention a GitHub issue.  Or are you going to make the (possibly incorrect) assumption that if there's nothing that looks like an issue mention, then none is required?

**Comment by jonathanolson** [comment]
I don't have strong preferences, but if we move commits to a new repo, the shorthand breaks (referencing issues in the wrong repo). So slight preference for full URLs or something involving the repo name, but this hasn't been a problem for me.

**Comment by pixelzoom** [comment]
>  if we move commits to a new repo, the shorthand breaks (referencing issues in the wrong repo)

Are you sure about that? I've transferred a number of issues, and I recall being impressed that GitHub fixed links.  Maybe I wasn't looking at shorthand links.

**Comment by samreid** [comment]
For clarification: @jonathanolson described moving commits whereas @pixelzoom described moving issues.

**Comment by jonathanolson** [comment]
> Are you sure about that? I've transferred a number of issues, and I recall being impressed that GitHub adjusted issue links. Maybe I wasn't looking at shorthand links.

So if you have a repo A commit referencing `#105`, the GitHub website would expand that to `phetsims/A/issues/105` presumably. However if you move that commit to repo B, its commit message would still presumably just be `#105`, and so GitHub tools would expand that to `phetsims/B/issues/105`, which presumably will NOT be the correct issue. Am I wrong?

For when issues are moved, I love the forwarding to the correct issues.

**Comment by pixelzoom** [comment]
I don't know if you're wrong. I'm just not sure which forms of "GitHub issue mentions" the GitHub "transfer issue" feature deals with correctly.

**Comment by samreid** [comment]
To clarify the miscommunication.  There is a difference between transferring an **issue** using the "transfer issue" feature, and moving **commits** from one repo to another, like one would do with this script: perennial/bin/copy-history-to-different-repo.sh.

**Comment by jessegreenberg** [comment]
I have lately been pasting full URLs into commit messages for ease and so I don't have to worry about messing up the syntax in the commit message. But I don't feel like this is something we need to enforce as a project.

**Comment by samreid** [comment]
From today's meeting:

@jonathanolson mentioned that he prefers the full URL
@jessegreenberg mentioned that he has been using the full URL recently
@pixelzoom sometimes likes to use the shorthand.  But if not everyone will do it and nobody will enforce using the full URL.  I use the full URL most of the time, but just a sim repo sometimes I will use `#NNN`.
@jbphet That's exactly what I do.  But I have messed up a couple where I thought I was only committing to one repo, but it committed 2 repos.
@chrisklus uses the full URL, but no strong feelings about making everyone use it

Our consensus is that:
* we would like to use URLs for the benefit of the project
* we will not enforce it, don't worry if you use shorthand sometimes

**Comment by jbphet** [comment]
Another reason to favor full URLs: If the code is ever moved from one repo to another, the full URL will reference the correct issue while an issue number by itself will not, and will likely reference an _incorrect_ issue.  This come up for @jessegreenberg this week as he moved the molecules-and-light code into the greenhouse-effect issue.
