### ISSUE TITLE
Update link to more activities in teacher tips

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#1093]
When the new sim pages were published, we realized we needed to update the links at the end of every teacher tips document. (https://github.com/phetsims/website-meteor/issues/305). Here is a list of every sim that we can use to keep track of which teacher tips need updating. 

@arouinfar and @BLFiedler feel free to assign sims to yourself, and check off as you complete this task. 

- [x] Acid-Base Solutions (@amanda-phet )
- [x] Area Builder (@amanda-phet )
- [x] Area Model Algebra (@amanda-phet )
- [x] Area Model Decimals (@amanda-phet )
- [x] Area Model Introduction (@amanda-phet )
- [x] Area Model Multiplication (@amanda-phet )
- [x] Arithmetic (@Nancy-Salpepi)
- [x] Atomic Interactions (@arouinfar)
- [x] Balancing Act (@Nancy-Salpepi)
- [x] Balancing Chemical Equations (@Nancy-Salpepi )
- [x] Balloons and Static Electricity (@BLFiedler )
- [x] Beer's Law Lab (@Nancy-Salpepi )
- [x] Bending Light (@Nancy-Salpepi )
- [x] Blackbody Spectrum (@arouinfar)
- [x] Build a Fraction (@Nancy-Salpepi)
- [x] Build a Molecule (@arouinfar)
- [x] Build an Atom (@Nancy-Salpepi )
- [x] Capacitor Lab: Basics (@Nancy-Salpepi)
- [x] Charges and Fields (@Nancy-Salpepi )
- [x] Circuit Construction Kit: DC (@arouinfar)
- [x] Circuit Construction Kit: DC - Virtual Lab (@arouinfar)
- [x] Collision Lab (@arouinfar)
- [x] Color Vision (@Nancy-Salpepi )
- [x] Concentration (@Nancy-Salpepi )
- [x] Coulomb's Law (@arouinfar)
- [x] Curve Fitting (@Nancy-Salpepi )
- [x] Diffusion (@arouinfar)
- [x] Energy Forms and Changes (@arouinfar)
- [x] Energy Skate Park (@arouinfar)
- [x] Energy Skate Park: Basics (@Nancy-Salpepi )
- [x] Equality Explorer (@amanda-phet )
- [x] Equality Explorer: Basics (@amanda-phet )
- [x] Equality Explorer: Two Variables (@amanda-phet )
- [x] Expression Exchange (@amanda-phet )
- [x] Faraday's Law (@BLFiedler )
- [x] Forces and Motion: Basics (@Nancy-Salpepi )
- [x] Fourier: Making Waves (@arouinfar)
- [x] Fraction Matcher (@Nancy-Salpepi )
- [x] Fractions: Equality (@Nancy-Salpepi)
- [x] Fractions: Intro (@Nancy-Salpepi)
- [x] Fractions: Mixed Numbers (@Nancy-Salpepi)
- [x] Friction (@BLFiedler )
- [x] Function Builder (@Nancy-Salpepi )
- [x] Function Builder: Basics (@Nancy-Salpepi )
- [x] Gas Properties (@arouinfar)
- [x] Gases Intro (@arouinfar)
- [x] Gene Expression Essentials (@Nancy-Salpepi )
- [x] Graphing Lines (@Nancy-Salpepi )
- [x] Graphing Quadratics (@Nancy-Salpepi )
- [x] Graphing Slope-Intercept (@Nancy-Salpepi )
- [x] Gravity and Orbits (@arouinfar)
- [x] Gravity Force Lab (@BLFiedler )
- [x] Gravity Force Lab: Basics (@BLFiedler )
- [x] Hooke's Law (@Nancy-Salpepi )
- [x] Isotopes and Atomic Mass (@arouinfar)
- [x] John Travoltage (@BLFiedler )
- [x] Least-Squares Regression (@Nancy-Salpepi )
- [x] Make a Ten (@Nancy-Salpepi )
- [x] Masses and Springs (@arouinfar)
- [x] Masses and Springs: Basics (@arouinfar)
- [x] Molarity (@BLFiedler )
- [x] Molecule Polarity (@Nancy-Salpepi )
- [x] Molecule Shapes (@Nancy-Salpepi )
- [x] Molecule Shapes: Basics (@Nancy-Salpepi )
- [x] Molecules and Light (@BLFiedler )
- [x] Natural Selection (@Nancy-Salpepi )
- [x] Neuron (@Nancy-Salpepi )
- [x] Number Line: Distance (@Nancy-Salpepi )
- [x] Number Line: Integers (@Nancy-Salpepi )
- [x] Number Line: Operations (@Nancy-Salpepi )
- [x] Ohm's Law (@BLFiedler )
- [x] Pendulum Lab (@Nancy-Salpepi)
- [x] pH Scale (@arouinfar)
- [x] pH Scale: Basics (@arouinfar)
- [x] Plinko Probability (@Nancy-Salpepi )
- [x] Projectile Motion (@Nancy-Salpepi )
- [x] Proportion Playground
- [x] Ratio and Proportion (@BLFiedler )
- [x] Reactants, Products and Leftovers (@Nancy-Salpepi )
- [x] Resistance in a Wire (@BLFiedler )
- [x] Rutherford Scattering (@Nancy-Salpepi )
- [x] States of Matter (@arouinfar)
- [x] States of Matter: Basics (@arouinfar)
- [x] Trig Tour (@Nancy-Salpepi )
- [x] Under Pressure (@Nancy-Salpepi )
- [x] Unit Rates (@Nancy-Salpepi )
- [x] Vector Addition (@arouinfar)
- [x] Vector Addition: Equations (@arouinfar)
- [x] Wave Interference (@arouinfar)
- [x] Wave on a String (@Nancy-Salpepi )
- [x] Waves Intro (@BLFiedler )

**Comment by BLFiedler** [comment]
Change required:

Statement at the bottom of the page: "See all published activities for SIM-NAME here." should be edited so that the "here" is hyperlinked to `https://phet.colorado.edu/en/simulations/SIM-NAME/activities`

**Comment by amanda-phet** [comment]
I noticed that the URL doesn't currently have `https://` so I'm adding that in as well as changing the end of the URL.

**Comment by arouinfar** [comment]
I've tried twice now to edit the list above only to get this warning:
> The content you are editing has changed. Please copy your edits and refresh the page.

I will update the tips that I have on my computer that use the latest template. Roughly, that translates to any sim from 2019 onwards, but includes sims that have recently been republished (like pH Scale).

@Nancy-Salpepi please start with older sims, working backwards from this list:
https://phet.colorado.edu/en/simulations/filter?type=html&sort=newest&view=grid

**Comment by Nancy-Salpepi** [comment]
OK will do @arouinfar

**Comment by BLFiedler** [comment]
This is now done for the simulations I indicated I'd update along with the other inclusive feature updates. Took a bit to get some inclusive feature support materials ready. Unassigning!
