### ISSUE TITLE
My commits are showing up double. 

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1094]
My commits are showing up double.  What is causing this, will it cause problems, can it be prevented?  For instance, in https://github.com/phetsims/chipper/issues/1156

![image](https://user-images.githubusercontent.com/679486/144310121-f444065f-4ec2-418c-b8ac-b541055355d9.png)

**Comment by jessegreenberg** [comment]
Hey @samreid I was just reading through https://github.com/phetsims/chipper/issues/1156 and noticed that your commits no longer have two profile icons. So maybe this was a temporary github bug.
![image](https://user-images.githubusercontent.com/6396244/144445940-c1fe0dd8-92a0-41b6-a3a7-5808b7e80fd6.png)

**Comment by samreid** [comment]
It seems fixed now, thanks!  Closing.
