### ISSUE TITLE
Develop design patterns for Typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1097]
### Priority:
1. Options
 - SR(20), MK(30), JO(15)
https://github.com/phetsims/chipper/issues/1128
2. Enumerations
 - SR(10), MK(15), CM(3)
https://github.com/phetsims/chipper/issues/1106
3. Mixins
 - JO(3), MK(20), JG(5) 
https://github.com/phetsims/chipper/issues/1127

Including documentation work
- Keep JS documentation

**Comment by zepumph** [comment]
For the last ~3 weeks or so, these three issues have been adapted enough to unblock converting common code to typescript over in https://github.com/phetsims/tasks/issues/1096. This issue as a Q1 2022 goal is complete, but https://github.com/phetsims/chipper/issues/1128 will still need more work. @samreid would you like to close this issue?

**Comment by samreid** [comment]
Yes, everything else is tracked in side issues, closing.
