### ISSUE TITLE
Unfuddle guest account is missing

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1098]
On 1/9/22 8:15 PM, Chris Malley wrote:

> I’m forwarding this to everyone who is an Unfuddle administrator.  A Google Group member is having difficulty following the instructions for accessing legacy code. Contrary to the instructions, there appears to be no “guest” user associated with the PhET Unfuddle project. Could someone please volunteer to figure this out, then reply in the Google Group?

**Comment by oliver-phet** [comment]
I'm guessing this user changed the user name and password of the guest account? (Last signed in Nov 1, 2021)
![image](https://user-images.githubusercontent.com/5090275/148821875-8ee7ece1-9566-4887-a0fb-95962000b2ed.png)

**Comment by oliver-phet** [comment]
That account has been changed back to guest/guest!

**Comment by oliver-phet** [comment]
Replied to the user in the google group, closing.
