### ISSUE TITLE
PhET Global Logo Creation

### ISSUE THREAD

**Issue by RVieyra** [phetsims/tasks#1101]
By February 15 (if possible -- not incredibly urgent):

Produce the following PhET Global logos --> all must have TM to the right of "PhET"

(1) Social Media icon
(2) Logo on clear background for placing on black/dark background, with and without Interactive Simulations text
(3) Logo on clear background for placing on white background, with and without Interactive Simulations text

<img width="236" alt="Screen Shot 2022-02-01 at 4 12 44 PM" src="https://user-images.githubusercontent.com/89751562/152052289-78f7cbc8-43cf-4644-8e44-708d31e277c4.png">

**Comment by amanda-phet** [comment]
I couldn't remember if we needed the TM on the small social media logo, but it's there anyway. If you find that it looks like a strange speck, I think it can be removed. 
![phet-global](https://user-images.githubusercontent.com/7852916/152087056-bcfb33b4-d304-4563-a117-28cd6d78b538.png)
![phet-global-on-white](https://user-images.githubusercontent.com/7852916/152087062-b4b451d4-dfec-4098-9b15-2d256c46f730.png)
![phet-global-on-black](https://user-images.githubusercontent.com/7852916/152087065-de4f813e-f2d2-4701-8e7a-d846b4e00456.png)
![phet-globe-on-black](https://user-images.githubusercontent.com/7852916/152087072-89ce1fb1-83bc-440f-85e1-c154e561148e.png)
![phet-globe](https://user-images.githubusercontent.com/7852916/152087079-6e47a5c7-6d53-4672-b322-c83ade39be00.png)

Here are the exported logos, but they will also live in this google drive folder: https://drive.google.com/drive/u/0/folders/1sRi3NR43zObdj397LkrF_vXSqMFOYhiR

**Comment by amanda-phet** [comment]
@RVieyra you can drag the images here onto your desktop, or get them from google drive. Please close if all looks good!

**Comment by RVieyra** [comment]
These look perfect. Thank you!

I will also edit the document you shared with me. For now, I'll just be using these logos on Medium.com (if that's what we use for the blog), as well as PhET Global **programming**. For everything else, we'll continue to use the regular logo.
