### ISSUE TITLE
PhET Visual Identity

### ISSUE THREAD

**Issue by RVieyra** [phetsims/tasks#1102]
In order to bring a sense of cohesion to PhET resources, we will expand on the PhET Visual Identity document: https://docs.google.com/document/d/1K7SLrK2_rAugnC1IdRbeLwcUShP0rVdARNZdk-OkY50/edit?usp=sharing

I will begin to populate the document with some new things we have been developing.

@ariel-phet , thank you for your willingness to try to develop a new, sleeker style for PhET presentations. Here are three presentations you might look at as you consider a new template--these give a lot of examples of the variety of slides we use. (If we do decide on a final style, we'd love to have it by April, so we can build the Fellowship and Virtual Workshop-related materials into the new style).

- PhET Translator Network Informational Session: https://docs.google.com/presentation/d/1DGEx80gcL-wolkrLRF8J8Z_TG-8tgDQCFpavxmI2Pn0/edit?usp=sharing

- Introduction to PhET: https://docs.google.com/presentation/d/1IrtgG9LnIf_TuY2MY8FEKoBLS8xgkjUpeXVX77IaiK0/edit?usp=sharing

- PhET Fellowship Session #1: https://docs.google.com/presentation/d/1tDRTiYhI8l-xfX6jyt1OtBEooOjaz_gSKR66RZdT2RQ/edit?usp=sharing (You will note, this presentation includes some purple/turquoise imagery that we pulled from Diana's WISE Foundation Fellowship -- we have been given permission to use these, and I imagine they will stay as-is because of their complexity. Please don't worry about "fitting" them into any style.

**Comment by RVieyra** [comment]
@ariel-phet Hi! I'm just checking in. Have you given any thought to a new, sleeker PPT designs for PhET presentations? No particular deadline, but we'll use what you produce if you have anything.

**Comment by ariel-phet** [comment]
@RVieyra -- not yet, I hope to give this some thought next week.

**Comment by ariel-phet** [comment]
Unlikely this will happen for me. Closing
