### ISSUE TITLE
Social Media Postings

### ISSUE THREAD

**Issue by RVieyra** [phetsims/tasks#1108]
Ariel,

Would you kindly post the following (or some version of it!) to social media (Twitter, Facebook, LinkedIn) in the next day or two?

Curious about effective #STEM education practices with PhET simulations? Join our new Africa Share and Discuss webinar series to learn about the work of researchers and educators across Africa, starting with Dr. Umesh Ramnarain of the University of Johannesburg. Register: https://cuboulder.zoom.us/meeting/register/tJYrcOGtqTsqHtY6RzohzlFYQYtbHYLNM-W7

![Ramnarain 20 April 2022](https://user-images.githubusercontent.com/89751562/162033047-679d3017-7cc4-471a-abf4-33454a10238c.png)

**Comment by RVieyra** [comment]
FYI, Dr. Umesh does not seem to have a Twitter account (his name is all over, but he doesn't have a profile to link to).

**Comment by ariel-phet** [comment]
Will do. I think tomorrow would be best.

**Comment by ariel-phet** [comment]
Posted!
