### ISSUE TITLE
Artwork for MSaB

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#1113]
1. A simple brown table for the water glasses to sit on
2. Notebook paper for the background of the 2D cups

Something like this: 
![image](https://user-images.githubusercontent.com/7852916/185213201-8cbe1a57-2223-4bc9-aa9d-9ef485075c07.png)

Latest version of the sim to play with and see the true context: 
https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.7/phet/mean-share-and-balance_en_phet.html

**Comment by amanda-phet** [comment]
@mariahmaephet shared this in slack: 

<img width="1060" alt="Screen Shot 2022-09-06 at 12 17 16 PM" src="https://user-images.githubusercontent.com/7852916/188732576-bc64ea05-9925-4c03-896f-4003abbdd2a5.png">

I shared it with the team and overall we are excited about the direction, but have a few tweaks in mind
* Make the tear more "even" across, so it's not dramatically longer on one side than the other
* Remove the holes
* Tone down the drop shadow- it is almost distracting- maybe lighter gray? 
* Make the paper lines )the blue and red) a bit more faint 
* Consider removing the red lines and the holes altogether, since this will span most of the width of this paper

The desk looks good, but we're not sure we need the drawers at all. It might help to see it cropped, so I can send you an ai file so you can get the layering. We are also wondering if the perspective on the desk matches the cups, but let's see when we get it together in one ai file. 

Thanks Mariah!

**Comment by amanda-phet** [comment]
Here is an ai file that might be helpful so you can see the new artwork in context:  
[msab-mockup.ai.zip](https://github.com/phetsims/tasks/files/9500573/msab-mockup.ai.zip)

**Comment by mariahmaephet** [comment]
<img width="643" alt="Screen Shot 2022-09-07 at 12 07 43 PM" src="https://user-images.githubusercontent.com/11527557/188949631-9cc26917-0d77-40dc-942f-436faefb873c.png">
<img width="1248" alt="Screen Shot 2022-09-07 at 12 13 35 PM" src="https://user-images.githubusercontent.com/11527557/188949635-caa729cb-e3f4-4803-a551-c77ec078e9f7.png">

How's this? I like a little bit of the desk peaking out below just to give more context and relate it to the science classroom a bit more.

**Comment by amanda-phet** [comment]
I like it!! If you could export the pngs (or share the ai file) I can ask @marlitas to put the artwork in the live sim and see if it needs any tweaks.

**Comment by mariahmaephet** [comment]
[msab-mockupMHedit.ai.zip](https://github.com/phetsims/tasks/files/9559006/msab-mockupMHedit.ai.zip)

Let me know if that works

**Comment by amanda-phet** [comment]
@mariahmaephet and I met today and decided she would also work on creating something more table-like for the Leveling Out and Fair Share screens, as well as a wrapped chocolate/candy bar for the Leveling Out screen.

**Comment by mariahmaephet** [comment]
So played around a little and the classroom table is definitely too bulky. If you wanted to keep it simple with the plates, it could be something closer to the second option, or even have it tie into the other candy themed things we've done and have it be a candy counter (this was just a random mock up example). Makes the plate thing weird, but it could be replaced with a box or something
<img width="866" alt="Screen Shot 2022-09-13 at 2 37 42 PM" src="https://user-images.githubusercontent.com/11527557/190004658-9964a36e-58fd-4eb0-abdd-d0c588d702f8.png">
<img width="864" alt="Screen Shot 2022-09-13 at 2 40 39 PM" src="https://user-images.githubusercontent.com/11527557/190005020-89760596-ef66-4377-b596-d3d4bc720efb.png">
<img width="865" alt="Screen Shot 2022-09-13 at 2 35 18 PM" src="https://user-images.githubusercontent.com/11527557/190005049-c30f8578-1c51-4244-9d59-ba62289d8dc6.png">

**Comment by mariahmaephet** [comment]
I put some alternates for the paper in this file. Let me know if there's other versions you want--I think it was just relaxing the tear and having variations in the lines and paper size, right?
<img width="936" alt="Screen Shot 2022-09-21 at 2 24 10 PM" src="https://user-images.githubusercontent.com/11527557/191603838-3f4f9d4f-8707-4508-af1b-53df13d6dcca.png">



[msab-mockupMHedit copy.ai.zip](https://github.com/phetsims/tasks/files/9620140/msab-mockupMHedit.copy.ai.zip)

**Comment by amanda-phet** [comment]
@mariahmaephet we are back to trying something new for the paper background. The lines created too much interference, so we're wondering if we could try a spiral notebook instead with no lines. 

Maybe something simple, like this: 
![image](https://user-images.githubusercontent.com/7852916/196746836-b52ac195-b46c-4d51-80c7-f72cd45c7375.png)

But with the appearance of a stack of pages (on the bottom and right edges, I presume). This one is a bit too much, but I think it shows the stack of pages clearly. 
![image](https://user-images.githubusercontent.com/7852916/196747457-64a04854-4fe3-48a6-888c-72ac10032873.png)

**Comment by catherinecarter** [comment]
I wonder if the spirals end up being too much, even after making them a little smaller, if a side spiral would be less distracting? 
![image](https://user-images.githubusercontent.com/109630002/196751192-95d889ad-d8fa-4829-a064-1b9cd4839067.png)

**Comment by amanda-phet** [comment]
>I wonder if the spirals end up being too much, even after making them a little smaller, if a side spiral would be less distracting? 

I think there is currently a lot more vertical space than horizontal space available for spirals.

**Comment by mariahmaephet** [comment]
Ignore the wonky rings, but how does this look @amanda-phet 

<img width="625" alt="Screen Shot 2022-10-19 at 2 19 26 PM" src="https://user-images.githubusercontent.com/11527557/196795573-644c3ba3-4128-44b6-a2cf-d062ebeb4b8a.png">

**Comment by amanda-phet** [comment]
I like the direction! We'd definitely like the spirals to be as minimalist as possible. Maybe even just one per hole instead of two? And as small as seems reasonable for the paper pad. 

I'll probably adjust the height of the pad, but that is easy for me to fine-tune myself.

**Comment by marlitas** [comment]
@amanda-phet and @mariahmaephet I just wanted to check in on where things are at with this asset so I can get a better idea on when the Intro Screen will be ready for an RC test.

**Comment by samreid** [comment]
@marlitas and I reached out to @mariahmaephet on slack:

> Hi Mariah!  Marla and I are talking about https://github.com/phetsims/tasks/issues/1113 and wondering about when there might be a draft we can use in the sim.  Also, what do you think about rendering some or all of that in the code?  Maybe the paper nodes, and add artwork for the rings?  Anyways, we are on a zoom call until 11am if you want to chat.  Have a nice day!

**Comment by amanda-phet** [comment]
@mariahmaephet do you have an update on the timeline for these updates?

**Comment by mariahmaephet** [comment]
@amanda-phet Oh! It wasn't posted here--I was messaging with Sam and Marla on Slack last week. I made a version with the paper and ring/hole separated so they could piece it together themselves. That seemed to work for them--or I haven't heard anything else about it. 
<img width="1292" alt="Screen Shot 2022-10-31 at 10 39 00 AM" src="https://user-images.githubusercontent.com/11527557/200682728-a7e1f9e4-b4de-4394-8158-6e0de9fea335.png">

**Comment by marlitas** [comment]
Yes! Worked great. I posted and update in https://github.com/phetsims/mean-share-and-balance/issues/102 about the implemented artwork. I think that issue is just waiting for your review/feedback @amanda-phet

**Comment by amanda-phet** [comment]
Thanks for the update @mariahmaephet . 

In the future, @samreid and @marlitas , please include me in slack discussions so I am in the loop!
