### ISSUE TITLE
Yidan Prize Foundation Social Media

### ISSUE THREAD

**Issue by RVieyra** [phetsims/tasks#1116]
@ariel-phet ,

Could you plan a social media release announcing our participation at the Yidan Prize summit? They include some suggested language. @kathy-phet @zamb6873 

**DEADLINE**: Because this will link to livestream, this will need to go out probably this afternoon or Saturday. (The event starts at 7 PM Sunday HK time, which is early Sunday morning for you!)

*******

Dear all,

 
Thank you for speaking at our 2022 Yidan Prize Summit. We’re pleased to share the following with you ahead of our event on 6 December (9am-4pm HKT).
 
·         Communications playbook
o   We’d be grateful if you could invite your colleagues and friends to join our discussion online. We’ve prepared [some sample wording and visual assets](https://www.dropbox.com/s/30fi2sxppv62od4/2022%20Yidan%20Prize%20Summit%20playbook%20for%20speakers.docx?dl=0) for sharing on social media and newsletters.
o   To tune into the live stream, you may register here: https://share.hsforms.com/1nGtL4MsESdKSd_VMuIbHgQc2ow8
 
·         Panel recording
o   Thank you for the rich discussion earlier in October. We’ve edited the recording into a [30-minute panel discussion](https://www.dropbox.com/s/qh1yvmbon2axehj/Panel%202_V1124.mp4?dl=0) to be screened at the Summit. We look forward to the 30-minute live Q&A after each session—Chris, Zach, and Kathy will be joining the Q&A in person.
 
·         Teacher case studies
o   We’ve compiled a booklet of case studies showcasing the impactful work of educators globally, including two case studies from PhET. While the print copies will be distributed at the Summit, please feel free to share this [booklet in pdf](https://yidanprize.org/files/2022-teacher-case-studies.pdf) with your wider network as well.
 
It has been a great pleasure working with everyone on this panel. Thank you so much for your time and commitment. We look forward to hearing more insights at the Summit Q&A next week!
 
Thank you for your support!
 
Best regards,
Yu-Ting

**Comment by ariel-phet** [comment]
Posted on Friday
