### ISSUE TITLE
Need Icons for New Inclusive Features

### ISSUE THREAD

**Issue by terracoda** [phetsims/tasks#1117]
We have a couple new features that we would like icons for:
- Interactive Highlights
- Camera Input
- Custom Gesture (added further down)

We will also need a web filter for these features, but I think I will need to make an issue in a different repo for that.

Tagging @amanda-phet to help me, or to help me find someone who can help me.

- For Interactive Highlights, I was thinking a thick rectangle, or square with a pointer on it, maybe even a mouse on it?
- For Camera Input, I was thinking a straight on camera with a human or hand in front. This one is tricky of course.

**Comment by terracoda** [comment]
This is really bad, and I know it can't be colored, but this is what I can copy and paste together using Preview:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/1902116/217620837-bea5dd34-985b-43a7-ad37-e7a50c6d4392.png">

**Comment by terracoda** [comment]
And here is a fun-silly camera input idea:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1902116/217633830-998d11e5-db19-445a-acdf-ca0364d1657a.png">

**Comment by terracoda** [comment]
I searched font-awesome for the icons.
- arrow-pointer
- face-smiling-hands
- camera-web

**Comment by terracoda** [comment]
@amanda-phet, timeline for this would be with the website. When you are ready to layout the new content for the Inclusive Design section.

**Comment by BLFiedler** [comment]
Updating to indicate we'll need the icons sooner for our videos which will be created before the website is updated.

Also, there is the potential for the Camera Input feature to have a "non-hands" variant. We should consider just a Camera Input icon that will be used for all sub-features.

**Comment by terracoda** [comment]
I realized yesterday that we also already have another inclusive feature:
- Custom Gesture

This feature is meant for touch devices. The feature changes the focus-based navigation of the sim to use custom swipes and taps (very similar to iOS VoiceOver gestures) on touch devices.

We designed this feature so Jen Tennison (SLU Chrome Lab) could use teh Voicing feature and do studies with blind people using her haptic designs for JT and GFLB.

**Comment by terracoda** [comment]
Super rough concept draft, and we do NOT need this one right-away. 
<img width="161" alt="custom-gesture-draft" src="https://user-images.githubusercontent.com/1902116/221259116-12f517f2-972e-4df0-a25e-f3d9cae22bc4.png">

**Comment by BLFiedler** [comment]
> Should we move ahead with just adding icons to the set, and figure out the website later?

Yes, please. The icons are going into videos in the next week or so. We can figure out how they fit into the website after that.

**Comment by mariahmaephet** [comment]
@amanda-phet Like this? I'll round them out a bit to match the style
<img width="679" alt="Screen Shot 2023-03-17 at 12 23 57 PM" src="https://user-images.githubusercontent.com/11527557/226000512-d64b31be-31b6-48a6-a868-0ae79aa6a347.png">

**Comment by terracoda** [comment]
Wow. That was quick.

I am wondering what these icons mean to people?

**Comment by amanda-phet** [comment]
[a11y-icons.ai.zip](https://github.com/phetsims/tasks/files/11005371/a11y-icons.ai.zip)

@mariahmaephet here is the ai file with the other assets. Can you add these three to the file, match the weight/stroke of the white parts to match as best as you can, pick 3 new colors, and then share a screenshot of the entire collection? 

It's possible we'll need to think about using similar colors for similar features because we will run out of different colors to use! Especially since these all need to be pretty saturated and dark. We're getting to the point where we might want one color for visual display, one for auditory display, and one for input. Thoughts @terracoda @emily-phet @BLFiedler ?

**Comment by terracoda** [comment]
I agree we are going to run out of colors - likely already have run out.

I started on a feature-relationship hierarchy somewhere? Looking for issue.

**Comment by mariahmaephet** [comment]
How do these look? It's easy to change the background color, and I have a general swatch that I try to work off of if that gives you more ideas of colors.
<img width="1227" alt="Screen Shot 2023-03-17 at 1 38 16 PM" src="https://user-images.githubusercontent.com/11527557/226036359-fc3fd003-0837-4b6a-939f-3fcd52831829.png">
<img width="297" alt="Screen Shot 2023-03-17 at 1 38 20 PM" src="https://user-images.githubusercontent.com/11527557/226036384-b1e4f8b9-3d37-44f2-94bd-963ce2a254a3.png">

**Comment by emily-phet** [comment]
Commenting on @terracoda's previous comment:
I had previously suggested color coding based on modality: like one color for all input options and different colors for Auditory and Visual features. 
There are lots of ways to slice this cake, and none will be perfect (there are times where features can/may overlap modalities). But maybe something like one color for each of these categories of features, and all features within that category have the same color:
- Input Options
- Auditory (interactive description, Voicing, sound & sonification)
- Visual (interactive highlights, and perhaps in the future, color contrast etc. - note, if the printer option currently in some sims is already this, maybe pan-and-zoom)
- Linguistic/localisation features 

I may be missing a feature, but I think you get the idea.

**Comment by terracoda** [comment]
@mariahmaephet thanks for turning my ideas into sharp-looking icons. The icons look really nice.

I have 2 questions for @emily-phet and @BLFiedler: 
- Do you think the icons represent the features nicely as is? 
- Are you both comfortable moving forward with this imagery?

The next issue is color...as suggested by @emily-phet, I think it makes sense to reduce the number of colors by grouping the icons by modality or related features. How does this grouping feel?
- Input Features (Magenta)
    - Alternative Input
    - Gesture Input
    - Camera Input
- Auditory Display Features 
   - Sound Display (Blue)
       - Sound & Sonification
   - Description Display (Orange or Green?)
       - Interactive Description
       - Interactive Description on Mobile
       - Voicing
 - Visual Display (Purple)
      - Pan & Zoom
      - Interactive Highlights

**Comment by terracoda** [comment]
Regarding color and groups, I was thinking, we could use different "shades/ranges" of the main color for the items in the group, if people like that idea.

**Comment by BLFiedler** [comment]
### **Color:** 

re: Talisien's idea in the past two posts: Let's give it a try! I think that could work. Frees us up to make more features in the future and not keep running into this issue too...

### **Imagery:** 

The Camera Input: Hands icon is a bit busy to me. Also, I wouldn't want folks to think we're tracking their face at all. I'd recommend removing the face and trying just the two hands or even just one hand (similar to our Ratio and Proportion hands?). 

The Gesture Input icon has some pretty small components. Might want to see if we can make the swipe arrow larger or consider a different configuration. I have no real suggestions, but here are some images I found that may inspire others?

![image](https://user-images.githubusercontent.com/47331395/227542357-002500c8-b090-423a-9226-e79e53d4a4dc.png)

![image](https://user-images.githubusercontent.com/47331395/227542394-d07f84ab-e911-4a19-b545-1c07e148a669.png)

**Comment by terracoda** [comment]
Great feedback Brett. Sorry, just seeing this now. I'll reach out on slack to see when @mariahmaephet is available.

**Comment by mariahmaephet** [comment]
So here's some edits from our conversation this morning--
<img width="764" alt="Screen Shot 2023-03-27 at 11 46 37 AM" src="https://user-images.githubusercontent.com/11527557/228037425-2b0f0edb-5122-44cd-a965-c8e0b0b092a4.png">

**Comment by terracoda** [comment]
The look great @mariahmaephet
- I like the square corners on the interactive highlights.
- A 4-way drag is definitely something custom, so if @BLFiedler  agreed, we can keep that one, too. I like the hand much better.
- I think the camera & the hand work well for Camera Input: Hands.

Regarding color, I do like the 3 shades. That's a nice effect, but I fear it this might complicate things. Let's do a single color for each group and see how that works:

Here's the groups again:
INPUT - Magenta:
- Alternative Input (i.e. keyboard)
- Custom Gesture
- Camera Input: Hands

AUDIO - 2 different colors
Sound & Sonification - Blue

Description Display - Orange
- Interactive Description
- Interactive Description on Mobile
- Voicing

VISUAL - Purple
- Pan & Zoom
- Interactive Highlights

Let's see how these 4 colors (Magenta, Orange, Blue, Purple) look together.

**Comment by terracoda** [comment]
Assigning back to you @mariahmaephet to do the single color groupings.

**Comment by mariahmaephet** [comment]
Let me know if I got that right
<img width="1209" alt="Screen Shot 2023-03-29 at 12 32 37 PM" src="https://user-images.githubusercontent.com/11527557/228648107-391a142a-398d-4037-b1fa-eb6044b45bd9.png">

**Comment by terracoda** [comment]
The color groupings are correct. Thank you Mariah!

Now, for the big questions @BLFiedler and @emily-phet, any thoughts on the color groupings? It was predictable...we have lost our rainbow effect.

Here's what I am wondering about: 
- Do we need to change the color for the Input grouping?
- Do we want to use shades within a grouping?
- Do we want to distinguish Voicing from Screen Reader access with color? It would be good to know how you both feel about.

**Comment by amanda-phet** [comment]
I just want to say I love the color groupings! All of the orange ones have speech bubbles, and that just makes a ton of sense. 

Is there a chance we'll add another color to the set? If not... I wonder if we should pick 4 colors that look nice together and cover more of the rainbow spectrum than these four (basically, this set doesn't have any green, and that might balance it all out).

**Comment by BLFiedler** [comment]
The shading might be nice so long as it stays above 3:1, but we might be okay. I'm not sure that Voicing needs its own color. That might cause the groupings to lose meaning.

I'm trying to imagine how this will worked with RaP as an example:
![image](https://user-images.githubusercontent.com/47331395/228653148-6a157e4e-daaf-4206-a1fb-668896c96f7a.png)

I agree with Amanda that maybe there is a shift in color set overall that would make this more appealing.

Also, here's some views of the icons in colorblind configs:
Blue blind: 
![image](https://user-images.githubusercontent.com/47331395/228653715-8e586490-0218-4873-bbdb-b435655e4470.png)

Red blind:
![image](https://user-images.githubusercontent.com/47331395/228653799-8d4497b9-8134-46ce-94a8-e13864ec8420.png)

Green-blind:
![image](https://user-images.githubusercontent.com/47331395/228653878-14255b4b-760c-4280-b7d3-09aedf827005.png)

**Comment by terracoda** [comment]
I am good with keeping all description as one color! I agree the connection between the speech bubbles and the color is a very nice one.

**Comment by emily-phet** [comment]
I like Amanda's comment above re adding in something in the green to one of the groupings. Regarding how many colors total might, I can imagine the following total:
Auditory
Visual
Haptic
Linguistic(?)/localization - indicating that there's some way to change the language/localization in the sim...maybe all forms of this lumped together (e.g., language and visual displays related to localization)
Input (all input methods lumped together for the foreseeable future)

So that would be five colors total if auditory were together. 

@terracoda I think it will be hard to do shades of color within a grouping if each sub-feature gets its own color. Perhaps a different approach would be to have shades of color where it matters a lot to distinguish sub-features. For example, having one shade of orange for the text-centric auditory display and another shade of orange for sound and sonification, rather than having it be its own color. Right now, I would vote against having sound and sonification be its own color because the color mapping loses the connection to the modality if two auditory outputs are colored differently. 

We could also use shades of color either now or in the future to distinguish between different types of input methods, if input methods grow larger in fully published sims. Right now the list is larger (Bluetooth, object tracking with OpenCV, and straight up plugin connection to bespoke custom device - the Smart Quad) are all options, but not yet in sims published to the main list. 

I would suggest not distinguishing Voicing from Interactive Description with color. They are related in so many ways, and I like having one color for each modality emphasized in a feature, which is auditory for both.

**Comment by terracoda** [comment]
The only feature I can think of at the moment that is not yet represented is the Haptic feature. We have worked on this feature, but it is not published in any sims.

"Haptics" seems like another output display mode, that could potentially have its own color.

But I like the idea of pick the nicest 4 right now.

**Comment by terracoda** [comment]
I am good with using one color for Auditory.

**Comment by terracoda** [comment]
I am not the best person to choose colors. Based on @emily-phet's suggestion, the current colors would be reduce to 3, since we have no examples of Haptics yet. 

Would this work?

AUDITORY - ORANGE
- Sound & Sonification  
- Interactive Description
- Interactive Description on Mobile
- Voicing

INPUT - GREEN
- Alternative Input (i.e. keyboard)
- Custom Gesture
- Camera Input: Hands

VISUAL - PURPLE
- Pan & Zoom
- Interactive Highlights
- Localization (Language and Character sets)

HAPTIC - BLUE
- no published sims yet

**Comment by terracoda** [comment]
I need someone else to choose the 3-4 starting colors.

**Comment by terracoda** [comment]
And just adding that we could flip colours for Input and Auditory features.

**Comment by amanda-phet** [comment]
Orange, green, and purple sound like a nice set of 3 to me. That leaves room to add blue and magenta down the road.

**Comment by terracoda** [comment]
**Option 2:**
AUDITORY - Green
- Sound & Sonification
- Interactive Description
- Interactive Description on Mobile
- Voicing

INPUT - Orange
- Alternative Input (i.e. keyboard)
- Custom Gesture
- Camera Input: Hands

VISUAL - PURPLE
 - Pan & Zoom
 - Interactive Highlights
 - Localization (Language and Character sets)

HAPTIC - BLUE
- no published sims yet, no icon yet

**Comment by mariahmaephet** [comment]
Alrighty, is this correct?
<img width="1214" alt="Screen Shot 2023-04-04 at 11 53 55 AM" src="https://user-images.githubusercontent.com/11527557/229892037-2eac91ac-1857-4516-b62b-c35258abe9c8.png">

**Comment by mariahmaephet** [comment]
Oh, yep, here ya go
<img width="1221" alt="Screen Shot 2023-04-04 at 12 00 56 PM" src="https://user-images.githubusercontent.com/11527557/229893913-088ab990-2e13-43c0-8551-262a315d2913.png">

**Comment by terracoda** [comment]
The little green one with the mobile phone.

**Comment by mariahmaephet** [comment]
How's that
<img width="1202" alt="Screen Shot 2023-04-04 at 12 43 46 PM" src="https://user-images.githubusercontent.com/11527557/229902671-4fbc2df1-09d4-4860-b362-d3682d9a5d88.png">

**Comment by BLFiedler** [comment]
![image](https://user-images.githubusercontent.com/47331395/229903092-2b1309b2-2b86-4af1-96d5-68b76d3e1de8.png)

![image](https://user-images.githubusercontent.com/47331395/229903157-a579dd5f-6b6c-4218-a3cc-ae9cfc574244.png)

Contrast is fine with either green, in case that matters to anyone!

**Comment by terracoda** [comment]
I like the darker one.

**Comment by BLFiedler** [comment]
I don't know why, but I think I prefer the auditory icons as green and input as orange. No reasoning other than gut.

**Comment by terracoda** [comment]
Well, there is also this icon...that Amanda made for me for the description course. I was hoping not to change the color of the Interactive Description icon.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/1902116/229905560-4c3c3f98-cfbb-4c82-894f-b1574890089b.png">

Seeing the grouped colors, I am still wondering if Sound & Sonification should be a unique color?

**Comment by terracoda** [comment]
@BLFiedler, it's probably the order of the rainbow that you are leaning towards. Orange goes before green. We could always list Auditory features first if need be.

**Comment by BLFiedler** [comment]
I am mostly just not a fan of orange (cautionary color) and there are more oranges than green ones in the latest mockups. I defer though, my taste here is irrelevant.

**Comment by terracoda** [comment]
OK, thanks. Orange is not cautionary for me - fun, creative, exciting.

Let's keep Auditory Orange.

**Comment by mariahmaephet** [comment]
Great! Here's the file
[a11y-iconsedit.ai.zip](https://github.com/phetsims/tasks/files/11152802/a11y-iconsedit.ai.zip)

**Comment by terracoda** [comment]
I think we need a png for each icon as well. I'll message you on slack.

**Comment by terracoda** [comment]
Thanks @mariahmaephet . Closing issue.

**Comment by mariahmaephet** [comment]
[icons svg.zip](https://github.com/phetsims/tasks/files/11737727/icons.svg.zip)
