### ISSUE TITLE
Update/Change Inclusive Design Research flow diagram

### ISSUE THREAD

**Issue by terracoda** [phetsims/tasks#1118]
In addition to #1117 , we will need an updated research and design flow diagram.

The current one looks like this:
![image](https://user-images.githubusercontent.com/1902116/219413028-2ce29525-0436-44b2-aa84-07adea61a9e1.png)

And our flow is evolving to be more about co-design. We need to capture these 4 steps in the diagram:
1. IDEAS & COLLABORATION
2. PROTOYPING
3. COLLABORATIVE INVESTIGATION
4. REFINING

**We are wondering if 2 and 3 could be represented a figure-8 in some way?**

**If not,** we could potentially update the current graphic like this:

- Ideate & Collaborate
- Prototype
- Collaboratively Investigate (replaces Research)
    - Around the circle:
        - Inclusive Investigation
        - Observe, Share, Discuss with diverse learners
        - Co-create with diverse learners
        - Redesign
- Refine (replaces Final Design)
- Cross modal Quality Assurance
- PhET website

**Comment by terracoda** [comment]
Assigning to you @amanda-phet for help.
Tagging @BLFiedler and @emily-phet for any additional comments

**Comment by terracoda** [comment]
Timeline would coincide with the the layout of the new content for the Inclusive Design pages.
We have content ready for 4 pages:
- About/Overview page - This is the landing page describing Inclusive Design at PhET
- Inclusive Features page - Describes each inclusive feature in briefly and in more detail. Combines and re-structures the brief descriptions and "more about" sections from the current "prototypes" page.
- Prototypes page - completely restructured. Provides links to sims we are working on or have worked on and have unfinished or unpublished features. Visualizes the state of each feature, and may provide a box that briefly describes "Known Issues" that effect multiple sims.
- Knowledge page - lists our research papers, presentations, and other artifacts we would like to share with the research community.

**Comment by amanda-phet** [comment]
@mariahmaephet do you have ideas for how to make a clear and modern-looking diagram to reflect Taliesin's description? Maybe we could meet the week of February 27th to discuss some ideas.

**Comment by amanda-phet** [comment]
We finished this and published the page, so closing this issue.
