### ISSUE TITLE
Update Inclusive Design section on website

### ISSUE THREAD

**Issue by terracoda** [phetsims/tasks#1119]
Related to #1117 and #1118 We have content ready to update, restructure, and layout the Inclusive Design pages on the website. We discussed making them more like the PhET Global pages. Tracking progress in phetsims/a11y-research/issues/181. 

The google docs are in the website projects folder, "Inclusive Design Section".

We have content ready for the 4 pages:
- **About/Overview** page - This is the landing page describing Inclusive Design at PhET
- **Inclusive Features/ Features** page - Describes each inclusive feature in briefly and in more detail. Combines and re-structures the brief descriptions and "more about" sections from the current "prototypes" page.
- **Inclusive Prototypes/ Prototypes** page - completely restructured. Provides links to sims we are working on or have worked on and have unfinished or unpublished features. Visualizes the state of each feature, and may provide a box that briefly describes "Known Issues" that effect multiple sims.
- **Knowledge** page - lists our research papers, presentations, and other artifacts we would like to share with the research community.

For the actual tabs, I think one-word will work, and then in the H1 we can add "Inclusive".
- About or Overview
- Features
- Prototypes
- Knowledge

@amanda-phet assigining to you for help. Note that I am not sure what labels to use.
Tagging @emily-phet and @BLFiedler for comment.

**Comment by amanda-phet** [comment]
The inclusive design page was published, so this issue is stale. Closing.
