### ISSUE TITLE
Figure out how to enable WebGL in browser configurations

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#112]
We need to figure out the steps involved in enabling WebGL in various browsers. (It can be disabled/enabled in some browsers)

@arnabp Can you create a google doc with instructions for enabling webgl on the browsers:

Safari 6, 7, 8 (if possible)
Firefox (latest)
Chrome (latest)

**Comment by ariel-phet** [comment]
Looks like this is all done, since and is now being made into a webpage. Thanks!
