### ISSUE TITLE
Use KeyboardListener instead of globalKeyStateTracker and custom listeners

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#1126]
Searching for `globalKeyStateTracker`. `keydown:`, and `keyup:` I found this list of files that might be improved by using KeyboardListener:

 - [x] EFACIntroScreenView.js (`keydown`, `keyup`) @jbphet
 - [x] MagnetAutoSlideKeyboardListener.js (`keydown`, `keyup`) @jbphet
 - [x] FaradaysLawKeyboardDragListener.js (`keyup`) @jbphet - (didn't update this one, [here's why not](https://github.com/phetsims/tasks/issues/1126#issuecomment-1666065050)).
 - [x] PhetMenu.ts @jessegreenberg
 - [x] PreferencesDialog.ts @jessegreenberg
 - [x] PreferencesTabs.ts @jessegreenberg
 - [x] GrabDragInteraction.js @jessegreenberg
 - [x] AquaRadioButtonGroup.ts @jessegreenberg
 - [x] ComboBoxListBox.ts @jessegreenberg
 - [x] Dialog.ts @jessegreenberg
 - [x] BothHandsInteractionListener.ts  @zepumph
 - [x] ~AccessibleNumberSpinner.ts~ @jessegreenberg - Not a good candidate for KeyboardListener. Adds other alt input listeners and replacing is more effort than it is worth. People will not go here to look for an example, this is an internal implementation.
 - [x] ~AccessibleValueHandler.ts~ @jessegreenberg - Same as AccessibleNumberSpinner.
 - [x] WaveGameLevelNode.ts @pixelzoom - moved to https://github.com/phetsims/fourier-making-waves/issues/237
 - [x] ~localeProperty.ts @samreid @zepumph~ necessary usage of globalKeyStateTracker (no Node close by)
 - [x] ~phetioDevSaveLoad.ts @samreid @zepumph~ - necessary usage of globalKeyStateTracker (no Node close by)
 - [x] ~Display.ts @jessegreenberg~ - necessary usage of globalKeyStateTracker
 - [x] ~AnimatedPanZoomListener.js @jessegreenberg~ - necessary usage of globalKeyStateTracker
 - [x] PlayControlButton.ts @jessegreenberg 

### Important notes:
- Remember to dispose the listener, if you need to.

### Examples:

`globalKeyStateTracker` was often used to add support for global hotkeys. It is better to use KeyboardListener now for this case. Here is an example of the old style an an example switching to KeyboardListener.

<details><summary>Old style</summary>

```js
globalKeyStateTracker.keydownEmitter.addListener( event => {

  // Make sure this Node is visible, pdomVisible, and enabled for input.
  if ( this.pdomDisplayed && this.enabledProperty.value ) {
    if ( KeyboardUtils.isKeyEvent( event, KeyboardUtils.KEY_ESCAPE ) ) {
      // Escape
      ...
    }
    else if ( globalKeyStateTracker.altKeyDown && KeyboardUtils.isKeyEvent( event, KeyboardUtils.KEY_C ) ){
      // Alt+C
      ...
    }
  }
} );
```
</details>

<details><summary>Using KeyboardListener</summary>

```js

const keyboardListener = new KeyboardListener( {
  keys: [ 'escape', 'alt+c' ],
  callback: ( event, listener ) => {
    if ( listener.keysPressed === 'escape' ) {
      // escape key was pressed
    }
    else if ( listener.keysPressed === 'alt+c' ) {
      // alt+c were pressed
    }
  },
  
  // By making this listener "global" it will fire no matter where focus is in the document as long as
  // myNode is visible and has input enabled. If this is false, callback will only fire when myNode has keyboard focus.
  global: true
} );

myNode.addInputListener( keyboardListener );
```
</details>

Often, a custom input listener was used for `keydown` and `keyup` events added to a particular Node. It might be better to use KeyboardListener for these for now. 

<details><summary>Old style</summary>

```js
    preferencesTabs.addInputListener( {
      keydown: event => {
        if ( KeyboardUtils.isKeyEvent( event.domEvent, KeyboardUtils.KEY_DOWN_ARROW ) ) {
          this.focusSelectedPanel();
        }
      }
    } );
```
</details>

<details><summary>Using KeyboardListener</summary>

```js
    preferencesTabs.addInputListener( new KeyboardListener( {
      keys: [ 'arrowDown' ],
      callback: () => {
        this.focusSelectedPanel();
      }
    } ) );
```
</details>

**Comment by jessegreenberg** [comment]
> - [ ] localeProperty.ts

This one is for ?keyboardLocaleSwitcher. Since there is no view component to add a listener to, using the global `globalKeyStateTracker` is probably best but curious if @samreid has an opinion so Ill put his name next to that one.

**Comment by pixelzoom** [comment]
I've attempted to follow the example provided, and it's not working in fourier-making-waves `WaveGameLevelNode`.  So I'm moving that conversion to https://github.com/phetsims/fourier-making-waves/issues/237.

**Comment by jbphet** [comment]
Can we a static list of range keys that would parallel the previous `KeyboardUtils.isRangeKey()`?

**Comment by jessegreenberg** [comment]
> Can a static list of range keys be added that would parallel the functionality we previously got from KeyboardUtils.isRangeKey()?

Thanks @jbphet, I added functions for this in the above commit. They are exported from EnglishStringToCodeMap.

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/tasks/issues/1126#issuecomment-1664582407, after seeing the usage in https://github.com/phetsims/energy-forms-and-changes/commit/3a708eb1d5fbf20fabf1550c808cb0fdc4fea951, I changed it a little. Functions and constants were moved to EnglishStringKeyUtils.

**Comment by jbphet** [comment]
I changed the ones assigned to me with the exception of `FaradaysLawKeyboardDragListener`.  This one is a drag listener rather than a general keyboard listener, and it extends `KeyboardDragListener`, which doesn't appear to be deprecated or anything.  In other words, it doesn't seem like an improvement to migrate this one, so I'm not going to.
