### ISSUE TITLE
Document query parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#1127]
This issue was motivated by a tour of new "aqua" query parameters that @zepumph gave at today's dev meeting.

Query parameters are only useful if we can find them, and they are documented. @jessegreenberg noted thast we can find query parameters by searching for "QueryStringMachine.getAll".

A search for "QueryStringMachine.getAll" shows a surprising number of query parameters that are undocumented.  Assigning to the responsibile developers, and to @kathy-phet to prioritize.

## aqua
- [x] aqua/js/continuous-loop.js @jonathanolson 
- [x] aqua/js/patient-snapshotter.js @jonathanolson 
- [x] aqua/js/snapshot-comparison.js @jonathanolson 
- [x] aqua/js/take-snapshot.js @jonathanolson
- [x] aqua/js/client/client.js @jonathanolson 
- [x] aqua/js/client/no-test.js @jonathanolson 
- [x] aqua/js/client/pageload-test.js @jonathanolson 
- [x] aqua/js/client/qunit-test.js @jonathanolson 
- [x] aqua/js/client/sim-test.js @jonathanolson 
- [x] aqua/js/client/wrapper-test.js @jonathanolson 
- [x] aqua/js/report/report.js @jonathanolson 
- [x] aqua/js/report/request.js @jonathanolson 
- [x] aqua/test-server/test-sims.js (`randomize`) @zepumph 

# phet-io-wrappers
- [x] phet-io-wrappers/common/js/Recorder.js @zepumph 
- [x] phet-io-wrappers/common/js/migration/MigrationEngine.js @zepumph 
- [x] phet-io-wrappers/js/tests/SimTests.js @zepumph 
- [x] phet-io-wrappers/login/crossCheckID.js @zepumph 
- [x] phet-io-wrappers/login/login.js @zepumph 
- [x] phet-io-wrappers/migration/index.html @zepumph 
- [x] phet-io-wrappers/record/index.html @zepumph 
- [x] phet-io-wrappers/state/index.html @zepumph 

## other 

- [x] joist/common/js/selectScreensTest.js (apparently duplicated from initalize-globals.js) @chrisklus 
- [ ] scenery/tests/sandbox.html @jonathanolson 
- [x] utterance-queue/js/UtteranceQueueTest.ts @jessegreenberg

**Comment by zepumph** [comment]
See https://github.com/phetsims/scenery/issues/1586. Closing
