### ISSUE TITLE
Investigate external server providers (e.g. Amazon, Rackspace) for use as data collection hosts

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#121]
We have been using phet-server for data collection, but it shut itself down in the midst of a study last week, and is old, and can no longer be relied upon for this purpose.  Simian is a possibility, but is currently being set up as a failover for the main PhET web server machine, so it would probably be best to minimize impact on this machine.  Given these constraints, and the fact that we probably don't want to buy more hardware ourselves, we should investigate leasing a virtual server from someone.  Amazon does this, I think Rackspace is another company, and CU OIT has a service too.  We should find out costs, setup time, and how it would all work.

**Comment by ariel-phet** [comment]
Current plan is fit this test in after Neuron and Arithmetic are published

**Comment by ariel-phet** [comment]
I think we can close this issue - it seems we have been able to accomplish this need via metacog, and ideally we would like to keep our hands completely off being responsible for data from any 3rd party studies.
