### ISSUE TITLE
Create new sim screenshots to match HTML5 aspect ratio

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#132]
We need to generate new screenshots for all of our "legacy" Java and Flash sims (that do NOT have an HTML5 version). The aspect ratio of the new screenshots will need to be the same as the existing HTML5 screenshots (2048x1342 with navbar) - which means a new screenshot resolution of 1024 x 672.

The screenshots should not include the File menu, only the tabs. 

There is a utility called 'Sizer' for Windows: http://www.brianapps.net/sizer/
May be an option for Mac here:
http://www.labnol.org/software/resize-mac-windows-to-specific-size/28345/
https://agilewarrior.wordpress.com/2012/09/07/how-to-resize-a-mac-window-to-exact-dimensions/

File naming should be "[sim name]-screenshot.png" without [] and ""

For example: energy-forms-and-changes-screenshot.png (sized at 1024x672)
![energy forms and changes 1 00 _2014-12-11_14-31-04](https://cloud.githubusercontent.com/assets/5090275/5402554/a3911462-8142-11e4-9c58-72c090be7475.png)

**Comment by ariel-phet** [comment]
@bryo5363 and @orejolaphet - this task is becoming a higher priority since we are making nice progress on changes to our sim pages. 

I think it would be good to go through all the sims that can be easily resized to the correct aspect ratio first, and we will then figure out how to deal with the outliers. 

@bryo5363 - how many of the sims have you done so far?

**Comment by orejolaphet** [comment]
@bryo5363 which java sims have you taken screen shots of?

**Comment by bryo5363** [comment]
I did all of them except for the ones w/o adjustable aspect ratio. I
believe those are lasers and one of the quantum sims. I have a dropbox full
of the screenshots

**Comment by ariel-phet** [comment]
@bryo5363 can you put a link to the dropbox in this issue?

**Comment by bryo5363** [comment]
https://drive.google.com/folderview?id=0B7WUaZM7uvVKbXhjMEs4Rm1OVU0&usp=sharing

**Comment by amanda-phet** [comment]
I found 11 missing screenshots. I also noticed that the HTML5 sims with a legacy version are not on the list- shouldn't we also have resized screenshots of those sims? They will definitely show up in the list of sims when viewing the site in a different locale. 

@ariel-phet please comment. I think with so many sims to look through, a table would be helpful to check off as we go so I'm going to make that and share it on google drive.

**Comment by ariel-phet** [comment]
Yes, we will probably need those as well.

**Comment by amanda-phet** [comment]
@bryo5363 Can you look at this spreadsheet and add notes in the next column about the issue with the screenshot? If the window can't be resized, for example. That way I know which sims to look at more closely. 

@ariel-phet Until I have more information I won't make any new screenshots.

**Comment by aaronsamuel137** [comment]
It looks like there are still some missing screenshots - I haven't looked to closely but it seems like all of the sims the have HTML versions need legacy screen shots as well as some other random ones like circuit-construction-kit-dc.

**Comment by amanda-phet** [comment]
@aaronsamuel137 Based on the spreadsheet being filled in it looks like @bryo5363 is still wrapping up this project and is checking them off as he goes. I don't think they are all in the drive folder that is linked above.

**Comment by aaronsamuel137** [comment]
OK great! All of the screenshots I have are on phet-dev now. Any ones that look like they are the wrong size are one's I haven't received yet.

**Comment by aaronsamuel137** [comment]
@bryo5363, please take a look at my comments in #203 to see the correct naming convention.

**Comment by amanda-phet** [comment]
We have determined that this is in a "good enough" state. Closing.

**Comment by amanda-phet** [comment]
This project needs to be completed. It is good enough for the current state of the website, but all of our sims need to have a high-res screenshot that lives in this folder: https://drive.google.com/folderview?id=0B7WUaZM7uvVKbXhjMEs4Rm1OVU0&usp=sharing. Please add any here that were done but are missing. 

Please complete this spreadsheet as the screenshots get done: https://docs.google.com/spreadsheets/d/1mBiWoz1ff0yMqyCkwXzDVfKI5x8KXa7MKYInMuqh5PQ/edit#gid=0 

The folder lists 96 files but the spreadsheet says 130 are done, so definitely make sure these two items accurately reflect each other.

**Comment by bryo5363** [comment]
@amanda-phet I have compiled most of the screenshots that needed to be taken into a new file. I was not able to capture 8 screenshots; the information is available on the spreadsheet you created. 

There is no Java version of ph scale basics so I was not able to produce a screenshot for this sim. Everything else either has Mac compatibility issues or will not let the user adjust aspect ratio.

**Comment by amanda-phet** [comment]
Can you point me to the place where all of the screenshots are located? Even better, can you put them in the linked google drive folder so they are all in the same place?

**Comment by amanda-phet** [comment]
Thanks @bryo5363 All of the screenshots are now in one folder, shared with the team. Closing.
