### ISSUE TITLE
Test Java version of Bending Light

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#133]
@bryo5363 can you test the Java version of Bending Light?

Original sim found here:

http://phet.colorado.edu/en/simulation/bending-light

We want to test the java version thoroughly to identify any bugs that are currently present since we are planning to port this sim to HTML5. It would be good to have this testing complete by mid-January.

Please report any issues in the Energy Forms and Changes github repo.

****Please mark any of the issues discovered with the label  "Java bug: TB fixed in HTML"***

Please also mark in this ticket when you have checked the sim on the two main operating systems.

- [x] Mac
- [x] Windows

**Comment by bryo5363** [comment]
Where should I report issues? It says above in the Energy Forms and Changes repo but I just want to make sure @ariel-phet

**Comment by samreid** [comment]
Yes, I think "Energy Forms and Changes repo" is a typo.  I'll create a bending-light repo now for these issues.

**Comment by samreid** [comment]
I created a bending-light repo and added it to the QA team's repos.  Please test it out and let me know if there is more for me to do:
https://github.com/phetsims/bending-light

**Comment by bryo5363** [comment]
It seems to be working. Thanks @samreid

**Comment by ariel-phet** [comment]
Definitely a typo...sorry about that!

**Comment by orejolaphet** [comment]
Believe testing has been completed.
