### ISSUE TITLE
Dev Testing for Pendulum Lab 1.0.0-dev.1

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#134]
@bryo5363...

Pendulum Lab 1.0.0-dev.1 is ready for dev testing:
http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.1/pendulum-lab_en.html

Please test it on the following platforms:
- [x] Windows + Chrome
- [x] OS X + Safari
- [x] iPad iOS + Safari

There are some layout issues, but @arouinfar will address those, please focus testing on functionality and performance on various platforms

**Comment by bryo5363** [comment]
The iPad performance is quite sluggish. Everything runs pretty slow but it is still functioning well.

**Comment by bryo5363** [comment]
The functionality on all three platforms is acceptable. I have only noticed one bug with the period timer, which has been identified in the issues. There are performance issues on all three platforms however. Both OSX and Windows run fairly well but there is a noticeable stutter upon opening the simulation. The iPad runs slower than both OSX and Windows and also contains the same stutter as the other two. Besides the performance issue I would say this sim is looking great.

**Comment by ariel-phet** [comment]
@bryo5363 thanks for finishing up testing!
