### ISSUE TITLE
dev testing: Reactants, Products and Leftovers 1.0.0-dev.23

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#135]
Reactants, Products and Leftovers (aka RPAL) is ready for 'dev' testing.  Here's the dev version:

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.23/reactants-products-and-leftovers_en.html

There are no known issues for this sim. If you find a problem or have a question, please create an issue at https://github.com/phetsims/reactants-products-and-leftovers/issues

Please test on the following platforms:
- [x] Mac OS X + Safari
- [x] Mac OS X + Firefox
- [x] iPad iOS + Safari
- [x] Windows + Chrome
- [x] Windows + IE11

You may find the following query parameters useful when testing:

**dev**
- Displays a red rectangle around the "safe" bounds of the screen. Verify that everything is drawn within these bounds.
- Shows the answer to each Game challenge at bottom-center of the screen.
- Adds a 'Test' button to the Game's level-selection screen. (Ignore this, it's for me. And its omitted if you use the playAll query parameter.)
- Adds replay [<] and skip [>] buttons to the Game, in the upper-right corner. They look like this:
![screenshot_179](https://cloud.githubusercontent.com/assets/3046552/5640666/cc501652-95e5-11e4-9d8d-6e4ef1d9c078.png)

**playAll**
-  Plays all possible reactions for each level of the game. Use this to examine all possible reactions and molecules. (When this query parameter is not specified, 5 reactions are chosen at random for each game.)

**guessCorrect**
- Initializes spinners to the correct answer in the Game. They are usually initialized to zero.

**showReward**
- Shows the reward at the end of a game, regardless of your score. Use this to check the reward for each game level.  The rewards for each level are: 1 =  molecules, 2 = smiley faces, 3 = sandwiches.

To use query parameters, append a '?' to the URL, then separate query parameters with '&'. For example:

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.23/reactants-products-and-leftovers_en.html?dev&playAll&guessCorrect

**Comment by pixelzoom** [comment]
@ariel-phet please feel free to modify (or be more specific about) the platforms that I've enumerated above.

**Comment by ariel-phet** [comment]
@bryo5363 and @orejolaphet please make this your current top testing priority.

**Comment by orejolaphet** [comment]
No issues found for Mac OS X + Safari

**Comment by bryo5363** [comment]
No issues were found for Max OSX and Firefox 35.0

**Comment by phet-steele** [comment]
No issues seen on Windows 8.1 Chrome + IE11

**Comment by pixelzoom** [comment]
Looks like dev testing is completed, with no bugs identified. One performance issue was reported (https://github.com/phetsims/reactants-products-and-leftovers/issues/27), but I suspect that it's specific to iOS7 and is still acceptable.

**Comment by ariel-phet** [comment]
Sounds good, closing.
