### ISSUE TITLE
Research monitors

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#137]
We need to research and pick out a monitor for sim @amanda-phet and @arouinfar to use. This will be for graphic design, so requirements are: 

- 24" - 27" 
- high resolution (at least 1920x1200 for 24" monitor, and even higher if 27")
- high number of colors 
- excellent color accuracy (something like IPS?) 
- less than $1000 
- available to purchase on amazon.com

Good to have:
- high ratings
- multiple inputs
- adjustable

When you have selected a monitor that you think is best please let us know and we will have @oliver-phet order it.

**Comment by amanda-phet** [comment]
@arouinfar can you please edit this if you feel there are more requirements?

**Comment by arouinfar** [comment]
Having a HDMI connection is preferred, though not strictly necessary.

**Comment by arnabp** [comment]
This seems to be the best option: http://amzn.to/17wurVB

The Asus PA279Q is a 27" 1440p IPS display with 99% Adobe RGB, HDMI and MiniDisplay inputs, and full tilt, swivel, pivot, and height adjustments at ~$800.

**Comment by ariel-phet** [comment]
@oliver-phet - let's go ahead and order this monitor, so @amanda-phet and @arouinfar can test one out

**Comment by oliver-phet** [comment]
Monitor should arrive Monday for testing.

**Comment by amanda-phet** [comment]
Thanks for your research @arnabp !

**Comment by oliver-phet** [comment]
This monitor worked great. And I ordered a second. Closing.
