### ISSUE TITLE
artwork for bunnies in Natural Selection

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#138]
@alexklinger I need a bunny drawn for the HTML5 version of Natural Selection. The original bunnies looked like this: 
White
![screen shot 2015-01-08 at 5 03 07 pm](https://cloud.githubusercontent.com/assets/7852916/5673392/6722efb0-9758-11e4-8205-8532157c4474.png)
With long teeth
![screen shot 2015-01-08 at 5 04 17 pm](https://cloud.githubusercontent.com/assets/7852916/5673393/7088abc6-9758-11e4-9d59-ff5501a950e4.png)
With long tail
![screen shot 2015-01-08 at 5 04 03 pm](https://cloud.githubusercontent.com/assets/7852916/5673394/7336243e-9758-11e4-8d15-c0a5a5414c1d.png)

Please draw a basic (but cute) white bunny that has the look and feel of our HTML5 sims (it can look similar to the original, but the gray stroke could have less detail and the style could be different), whose fur color can easily be changed in illustrator, and that can have a visible tail and set of long teeth. Once we have decided on the look of the bunny we can add in the mutations (long teeth and long tail).

**Comment by alexklinger** [comment]
@amanda-phet 
This is the basic look I have so far.
![bunny-phet](https://cloud.githubusercontent.com/assets/8651105/5743845/2281880a-9bd9-11e4-892d-67a584ac1a73.jpg)

**Comment by amanda-phet** [comment]
@alexklinger that's a great start. Let's discuss it Thursday when we meet. (regarding Thursday, my office is F-1019, and I am available earlier if you want to stop by any time after 3:30pm).

**Comment by alexklinger** [comment]
Here is the white bunny with shadow:
![bunny-phet-drop](https://cloud.githubusercontent.com/assets/8651105/5771383/f47cf216-9cf8-11e4-91d4-68d74fc3f959.jpg)
vs with stroke:
![bunny-phet-stroke](https://cloud.githubusercontent.com/assets/8651105/5771389/05e75618-9cf9-11e4-9907-11a73bb72bf5.jpg)
many with shadow:
![many-bunnies-drop-shadow](https://cloud.githubusercontent.com/assets/8651105/5771397/2f5d2248-9cf9-11e4-8955-db26b847c0b0.jpg)
many with stroke:
![many-bunnies-phet](https://cloud.githubusercontent.com/assets/8651105/5771398/38949986-9cf9-11e4-90fc-e45a3f7003e4.jpg)

**Comment by amanda-phet** [comment]
The style and posture look great to me. Let's keep this bunny and work on how we'll define the edge of each one. 

When there are multiple, the drop shadow makes the ones in the background so gray that I'm leaning toward the "stroke". Can we try a lighter (maybe gray) and thinner stroke? Also, it would be nice if it was less of an overall outline and more part of the drawing of the bunny- let's see how a gray stroke looks and maybe we'll add a little of it between the front legs or around part of the head where it meets the body.

**Comment by alexklinger** [comment]
I added some subtle leg stroke, and reduced it around the entire body.
![bunny-with-leg-stroke](https://cloud.githubusercontent.com/assets/8651105/5888550/a17a73e4-a3c0-11e4-9a01-c9dcf0a1f1b2.jpg)

**Comment by amanda-phet** [comment]
Looks good. Can you drop that illustrator file in the drive folder?

**Comment by amanda-phet** [comment]
@alexklinger go ahead and drop the .ai file for the bunny in the drive folder. Thanks!

**Comment by samreid** [comment]
Nice work @alexklinger, thanks!

**Comment by alexklinger** [comment]
No problem! Here's a look at the brown bunny.
![bunny-brown](https://cloud.githubusercontent.com/assets/8651105/5986887/5713fe22-a8cc-11e4-83ad-f84fb89a3dbf.jpg)

**Comment by alexklinger** [comment]
Here is the brown bunny
![brownbunny](https://cloud.githubusercontent.com/assets/8651105/6012792/aab1705c-ab09-11e4-9706-06f6eae145ba.jpg)

**Comment by alexklinger** [comment]
with long tail

![whitebunnylongtail](https://cloud.githubusercontent.com/assets/8651105/6013933/bed58a6e-ab18-11e4-927e-d2ac73fe5579.jpg)

**Comment by alexklinger** [comment]
with long teeth
![bunny-long-teeth](https://cloud.githubusercontent.com/assets/8651105/6013946/fc1bd964-ab18-11e4-8c48-940167053af8.jpg)

**Comment by alexklinger** [comment]
Updated Bunny with long tail.
![whitebunnylongtail](https://cloud.githubusercontent.com/assets/8651105/7267961/83c8380e-e880-11e4-9559-95198135a2bc.jpg)

**Comment by ariel-phet** [comment]
Hey @alexklinger - this looks good for the moment. I would say let's focus on the Cafe press project for the moment, as that is likely to be a fair bit of work.

**Comment by ariel-phet** [comment]
unassigning and labeling deferred until we work on this sim

**Comment by ariel-phet** [comment]
Long way off from working on this sim. Closing.
