### ISSUE TITLE
artwork for wolf in Natural Selection

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#139]
I need a wolf drawn in illustrator. The original looked like this:
![screen shot 2015-01-09 at 2 09 00 pm](https://cloud.githubusercontent.com/assets/7852916/5687366/191c8572-9809-11e4-8cc8-9779ee70f057.png)

When the wolves get small on the screen the black stroke around them doesn't look great, so less detail there would be nice. It doesn't need to look exactly like the original.

**Comment by ariel-phet** [comment]
Closing this task. We are unlikely to work on Natural selection anytime soon
