### ISSUE TITLE
Redesign social media links on website

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#140]
The text and links on our social media page (http://phet.colorado.edu/en/stay-connected) need a new design: 
![screen shot 2015-01-09 at 2 14 16 pm](https://cloud.githubusercontent.com/assets/7852916/5687430/db482804-9809-11e4-9c55-9babdf7f248b.png)

We would still like the same information to be there, but there are more visually appealing ways we can direct people to our facebook and twitter pages, and encourage people to read the blog or subscribe to the newsletter.

**Comment by alexklinger** [comment]
I would recommend using font awesome social icons in the footer of the entire site, rather than having a stay connected page. http://fontawesome.io/icons/

**Comment by amanda-phet** [comment]
Thanks for your input Alex. We agree and will continue working on the redesign of the footer in our weekly meetings.

**Comment by ariel-phet** [comment]
Yes, a duplicate, copying some comments into the other issue and closing.
