### ISSUE TITLE
artwork for cannon in Projectile Motion

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#141]
I need a cannon drawn in illustrator that looks more iconic than the current civil-war era cannon (https://phet.colorado.edu/sims/projectile-motion/projectile-motion_en.html). It should have a clearly grippable area in the center to drag the cannon on the screen and a clear area on the muzzle to pivot the barrel.

**Comment by ariel-phet** [comment]
@alexklinger - this particular project would be good to meet with @amanda-phet in person and brainstorm some ideas.

**Comment by alexklinger** [comment]
I'm available to meet between from 1-5pm tomorrow, weds. (1/14), and friday (1/16). On thursday I can meet from 3-5.

**Comment by alexklinger** [comment]
@amanda-phet ^

**Comment by amanda-phet** [comment]
@alexklinger How about Friday at 1pm?

**Comment by alexklinger** [comment]
@amanda-phet I'll be in on Thursday at 4.

**Comment by alexklinger** [comment]
@amanda-phet 
![cannonwip](https://cloud.githubusercontent.com/assets/8651105/6034009/a2dea3b4-abda-11e4-90fc-56d07c915f6d.jpg)

**Comment by amanda-phet** [comment]
I think it looks great. I will bring it to the sim team to see what they think.

**Comment by ariel-phet** [comment]
@amanda-phet, how about you and I discuss this artwork before bringing to the larger team.

**Comment by amanda-phet** [comment]
@ariel-phet and I discussed this and we have some changes we'd like to see. I like the wooden base, and the very clear pivot point. This cannon here has a triangular base, which would allow for more of the cannon to be visible when it is rotated- let's try something like this, and continue the wooden planks under it as you did above (but perhaps not as wide). 

![1077884-clipart-pirate-cannon-royalty-free-vector-illustration](https://cloud.githubusercontent.com/assets/7852916/6151817/979343b0-b1d5-11e4-812e-2ff7c4466129.jpg)

In terms of the look of the cannon, let's move more away from the civil-war look and toward something that looks a little more harmless. I like the clipart above because it has less detail and a playful shape. 

I like that the cannon below has some color and a band of stars, giving it some whimsey.
![stunt-clipart-human-cannonball_gg64282065](https://cloud.githubusercontent.com/assets/7852916/6151842/c635d28c-b1d5-11e4-8ab9-3d3fa8cbaff4.jpg)

The explosion you drew is perfect, don't change it at all. In fact, try to make the cannon match the playful feel of the explosion. 

@alexklinger let me know if you have questions and want to meet. Otherwise, give us an update when you think you are getting toward this vision.

**Comment by alexklinger** [comment]
![cannon](https://cloud.githubusercontent.com/assets/8651105/6362049/02b8d7de-bc46-11e4-9fbf-97395c09afaf.jpg)

**Comment by alexklinger** [comment]
I decided to shy away from the star idea because it signifies the U.S.A to me and I don't know if that's appropriate for your international audience.

**Comment by amanda-phet** [comment]
@alexklinger Can you upload the illustrator file for this cannon to the Drive folder?

**Comment by alexklinger** [comment]
Uploaded

**Comment by amanda-phet** [comment]
Thanks, this looks great.
