### ISSUE TITLE
Infrared Source for Molecules & Light

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#142]
The infrared source for Molecules & Light is drawn using 3D effects. To avoid rendering issues, it would be best if it can be redrawn in 2D by @alexklinger.

The original .ai file can found here:
https://drive.google.com/file/d/0B-YvjkIIcS_aLWZUTlk5QjlucFk/view?usp=sharing

Assigning to @amanda-phet for prioritization.

**Comment by alexklinger** [comment]
![infrared-source-no3d](https://cloud.githubusercontent.com/assets/8651105/5748369/9e03801e-9bfc-11e4-9b2e-8991b5283329.jpg) @amanda-phet How does this look?

**Comment by arouinfar** [comment]
@alexklinger -- I think the body looks great! The bulb color looks a bit too dark to me. Can you make it a brighter red? Before applying 3D effects, it was e12e00.

**Comment by alexklinger** [comment]
@arouinfar How's this? 
![infrared-source-no3d](https://cloud.githubusercontent.com/assets/8651105/5751447/f9d253c4-9c20-11e4-8b16-4b54a5098350.jpg)

**Comment by alexklinger** [comment]
@arouinfar How's this? 
![infrared-source-no3d](https://cloud.githubusercontent.com/assets/8651105/5751538/84183322-9c22-11e4-887c-6fe47a109ab3.jpg)

**Comment by arouinfar** [comment]
Looks great! Closing.
