### ISSUE TITLE
Print new PhET stickers and flyers

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#143]
I ordered a new box of 600 circle stickers. Can you print on them using the image with the logo AND the website URL.

Also, we need 1000 flyers printed of this flyer: https://drive.google.com/file/d/0Bz7jTh2s-5L5dUZkWHM2UDlIQzg/view?usp=sharing

**Comment by ariel-phet** [comment]
Thanks for this work, all looked great!
