### ISSUE TITLE
Add info to repository description and README re: publication status/obtaining stable version

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#144]
@pixelzoom said he would come up with some verbiage appropriate for the readme and description that suggest our process and why it is necessary to contact PhET to fork a stable version of the code.

**Comment by pixelzoom** [comment]
Here's what I came up with. I would discuss with all stakeholders before putting in the time to update repositories.

Repositories for published sims:

> This simulation has been published at <URL>.
> 
> The master branch of this repository is not guaranteed to be in a stable state. If you need a stable version of this repository and its dependencies, please contact PhET for more information.

Repositories for unpublished sims:

> This simulation is under development and has not yet been published.
> 
> The master branch of this repository is not guaranteed to be in a stable state. If you need a stable version this repository and its dependencies, please contact PhET for more information.


Common-code repositories:

> The master branch of this repository is not guaranteed to be in a stable state. If you need a stable version of this repository and its dependencies, please contact PhET for more information.

**Comment by samreid** [comment]
In my opinion, the boilerplate descriptive text that we apply to every PhET project should also contain a pointer to http://bit.ly/phet-development-overview

**Comment by ariel-phet** [comment]
Thanks for the first stab at the wording @pixelzoom - I also like your suggestion @samreid 

@oliver-phet - please discuss this question at developer meeting on January 22nd

We can then run it by @kathy-phet when she and I return from London

**Comment by samreid** [comment]
I have added documentation + instructions in the PhET Development Overview about how to check out specific SHAs for a simulation.  This text should be reviewed by another PhET developer, and I recommend to include a link to this section instead of saying:

> If you need a stable version of this repository and its dependencies, please contact PhET for more information.

Please see [PhET Development Overview: Master is Unstable: Accessing Rigorously Tested Code](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#bookmark=id.4fiykhwy31vk)

**Comment by pixelzoom** [comment]
I reviewed the section titled "Master is Unstable: Accessing Rigorously Tested Code". Fixed a couple of typos. This step confuses me:

> 6. To checkout the SHA for the simulation itself, additionally look up the SHA in the file and use `git checkout` to check it out.  (Note future version of `grunt checkout-shas` may handle this last step.

When did `grunt checkout-shas` start skipping the simulation itself? https://github.com/phetsims/chipper/issues/48 indicates that it doesn't ignore the simulation, and that this is a problem.

**Comment by samreid** [comment]
At today's meeting, we decided that checkout-shas and checkout-master would apply to the dependencies, but not the simulation itself.  I'll check the implementation to make sure this is the case.

**Comment by samreid** [comment]
I verified in the implementation and by testing with energy-skate-park-basics that the simulation is being skipped for SHA checkouts.

**Comment by pixelzoom** [comment]
@samreid wrote:
> I verified in the implementation and by testing with energy-skate-park-basics that the simulation is being skipped for SHA checkouts.

Great, thanks for confirming. So step (6) in the "PhET Development Overview" is valid.

Back to @ariel-phet for a decision on what exactly should be added to the README and description for repositories.

**Comment by samreid** [comment]
How about text like:

> To obtain code corresponding to a fully tested, published version of a simulation, please see [PhET Development Overview: Master is Unstable: Accessing Rigorously Tested Code](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#bookmark=id.4fiykhwy31vk)

**Comment by samreid** [comment]
But it sounds like @ariel-phet and/or @kathy-phet need to weigh in on this before we can move forward.

**Comment by samreid** [comment]
One point that came up in our discussion is that normally we want developers to use the master branch for development, testing, reporting issues, etc. and that it may be more of a special case where developers want to get the tested SHAs.

**Comment by samreid** [comment]
This simulation has been published at http://blah/blah/blah
OR
This simulation is under development and has not yet been published.

Development is done in the master branch, so the master branch is not a stable release.  To obtain code corresponding to a fully tested, published version of a simulation, please see [PhET Development Overview: Master is Unstable: Accessing Rigorously Tested Code](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#bookmark=id.4fiykhwy31vk)

If you need further assistance, please contact us at https://groups.google.com/forum/#!forum/developing-interactive-simulations-in-html5

**Comment by pixelzoom** [comment]
Not sure why, but this issues was moved over to #159. Closing.
