### ISSUE TITLE
Test Neuron 1.0.0-dev.7

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#145]
This version could use some pre-release testing.  Please test primarily for behavior, and please emphasize the pause and stepping back/forward behavior, as well as controlling time through the chart.  Please do *not* test performance on iPad at this point.

**Comment by orejolaphet** [comment]
Testing http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.7/neuron_en.html ?

**Comment by orejolaphet** [comment]
Tested on OSX 10.9.4 w/ Chrome 39. I notice no issues with the pause and stepping back/forward functions, that is no real issues in general.

**Comment by jbphet** [comment]
Please try it on a few more platforms, such as Safari and Firefox.

**Comment by orejolaphet** [comment]
Tested on Win 8 w/ FF 35.0 & IE 11 no issues with the pause and stepping back/forward function.
