### ISSUE TITLE
rc testing: RPAL 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#146]
Reactants, Products and Leftovers (aka RPAL) is ready for rc testing.

Release candidate:
http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-rc.1/reactants-products-and-leftovers_en.html

Test matrix:
https://docs.google.com/spreadsheet/ccc?key=0AkTcamSqEJ6EdDNIWm5OTEpoemxVUFo1ZmQtd2t5Q2c&usp=drive_web#gid=2

Note that the code base for this version is identical to 1.0.0-dev.23, which passed dev testing with no issues in https://github.com/phetsims/tasks/issues/135.  So it would be safe to skip (or mark as "tested") the platforms that were tested for 1.0.0-dev.23.

**Comment by ariel-phet** [comment]
@bryo5363, @orejolaphet, @phet-steele, @arnabp please make this your top testing priorities. As noted above you can make the dev tested platforms marked "tested"

**Comment by orejolaphet** [comment]
@ariel-phet can do

**Comment by ariel-phet** [comment]
Also don't forget to spot test the iframe link on 1 or two platforms and check that the downloaded HTML file works on one platform.

**Comment by pixelzoom** [comment]
Looking at the test matrix, we have no coverage on Win7.

Per @ariel-phet's request above:
Please spot test iFrame on FF, IE and mobile Safari.
Please spot test HTML download on 2 platforms of your choice. 
(Future test matrices will include these tests; for now, note the results in this issue.)

ETA for when this work can be completed?

**Comment by pixelzoom** [comment]
We're also missing coverage on: 
• iPad2 + iOS8 + Safari (@bryo5363 is signed up)
• Mac 9/10 + Chrome (@bryo5363 is signed up)
• Win8 + IE10.

**Comment by phet-steele** [comment]
iFrames on Windows 8.1 browsers were good.

**Comment by bryo5363** [comment]
Testing is completed on all devices except IE 10 on Windows 8; the only device that had this browser was the MacBook Air that has been deemed lost. Everything looks fine, the iFrame is working on all of the OSX browsers.

**Comment by pixelzoom** [comment]
@bryo5363  Thanks for the update. What is the status of the HTML download test?

**Comment by pixelzoom** [comment]
@ariel-phet The Win8+IE10 test platform is missing. Do you want to wait until https://github.com/phetsims/tasks/issues/153 is addressed, or do you want to forgo testing of this platform?

**Comment by bryo5363** [comment]
HTML downloads work well on all OSX (10.10.1, 10.9.5, 10.8.5, 10.7.5)

**Comment by pixelzoom** [comment]
I can't find a Win8+IE10 test machine. And I'm guessing that it's unlikely that one will materialize in the next day or two.  Since RPAL passed IE10 testing on Win7 with no problems, I don't expect Win8 to be any different. 

That completes RC testing for RPAL, this sim is ready to publish. Thanks testers! Closing.
