### ISSUE TITLE
Postmortem Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#147]
Work on postmortem checklist and adapt as needed from process used in Java sims

**Comment by ariel-phet** [comment]
Java postmortem listed below for convenience:

Version 8 Created by Chris M. on 21 Apr 2011. Previous Version
PhET postmortem process

1. Schedule a postmortem review meeting. Require the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind.  Allow sufficient time for the meeting, 1.5-2 hours.

2. Enlist a meeting moderator.  This should be someone who was not on the team and has no vested interest in the sim. The moderator's job is to make sure the meeting runs efficiently, stays on point, and doesn't become overly negative.  The moderator also documents the meeting, or you can enlist an additional person (not one of the participants) to be the secretary.  Do not record the meeting.

3. Require participants to bring a list of no more than 2 items that were done well during the project and no more than 2 items that could be improved upon.  Limiting to 2 requires people to think critically about their experience.

4. At the meeting, start by going around the room and having each person present their items (successes, then improvements).  Make a list of these items, and note duplicates.  Based on popularity, identify the top 5 success items and the top 5 items that need improvement.

5. Discuss the 5 success items first. Identify specific things that can be applied to future sims.  Celebrate, pat each other on the back. Then move on to the harder part.

6. Discuss the 5 improvement items.  Try to avoid getting personal. Discuss what was learned, and identify specific things that can be done to prevent these problems in the future.  If anything needs more investigation, assign to specific individuals.

7. Identify modifications to the PhET Look-&-Feel Guidelines. Based on what we learned during development of this sim, how should the guidelines be revised?

8. Review the "Sim completing checklist" here: https://phet.unfuddle.com/a#/projects/9404/notebooks/17977/pages/105244/latest

9. Create a postmortem report, capturing all of the above.  Modify any other documents (design, implementation, etc.) to reflect decisions made.

10. From the top 5 successes/improvements, decide what are the "take home messages" that would be useful to note in the future, and add these to the "Postmortem Take Home Messages" notebook: https://phet.unfuddle.com/a#/projects/9404/notebooks/17977/pages/105330/latest

11. Create Unfuddle tickets for action items.

**Comment by pixelzoom** [comment]
Does PhET have a "sim completion checklist" for HTML5 sims?

**Comment by ariel-phet** [comment]
Not yet -- I had started one, but it needs to be refined. I figured doing a postmortem would make it a higher priority for me to finish and get feedback.

**Comment by samreid** [comment]
Not sure if this is our only checklist, but we have some notes about sim development checklist here in the PhET Development Overview:
https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.tslwrzmorfdr

**Comment by ariel-phet** [comment]
We will plan to discuss at developer meeting when I return from london...my ideal is to create a "master checklist" for each sim that involves important milestones related to design, development, and testing. I will definitely take a look at the development overview checklist.

**Comment by ariel-phet** [comment]
@samreid said:

Not sure which members of the design team should attend (though I agree generally anyone with a significant involvement in the sim should attend the postmortem), but I think it is important to have at least one QA team member as part of the postmortem.

@ariel-phet replied:

@samreid -- we can see about that. Although I think that would be handy, I don't think we want to keep them at such a meeting for the full time (postmortems can be long and get into some details not relevant to the QA team). Perhaps we can arrange the process so that QA feedback is given early in the postmortem.

**Comment by ariel-phet** [comment]
First pass as postmortem process template viewable here:

https://github.com/phetsims/phet-info/blob/master/postmortem_process.md

**Comment by pixelzoom** [comment]
First pass looks good to me.

**Comment by ariel-phet** [comment]
Checklist created, closing
