### ISSUE TITLE
add additional RC-test tasks to the RC-test matrix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#148]
In 1/20/15 developer meeting notes, @ariel-phet requested:

> for release candidates lets put a couple of checkbox items in the task checkbox for testing iframe link on a couple of platforms (2 perhaps) checkbox for testing that downloaded html file works 

@samreid also has his own RC-testing issue template, which some developers weren't aware of. It lives here: https://github.com/phetsims/tasks/blob/master/doc/issue-template-release-candidate-testing.md

After much discussion, the consensus was that the test matrix is the defacto "check list" for RC testing, and it's not desirable to spread the check list across the matrix and tasks issue. (Note that it *is* desirable to have a check list in the tasks issue for dev testing, because there is no matrix.)  So we would like to merge @ariel-phet's request and @samreid's template into the test-matrix template.

**Comment by pixelzoom** [comment]
Another argument for keeping the entire check list in the RC-test matrix is that PhET has provided funders (e.g. RSC) with a link to the matrix, to demonstrate our QA process.

**Comment by ariel-phet** [comment]
Seems like a good suggestion.

**Comment by ariel-phet** [comment]
I started updating the example testing matrix a bit...took away the "categories" section since we really only put "must test" devices on here and we don't really test the surface or the nexus these days.

@oliver-phet - I put in a place holder for a checkbox item about iframe and downloaded file working. It seems good to put this at top. Can you pretty it up and make it more functional?
@pixelzoom can you make any suggestions if other tweaks need to be made?

https://docs.google.com/spreadsheets/d/1vk0QUOOOj_Jr4ePVgwiQ5L7HOsvgor7jkbNYqmCVWnQ/edit#gid=2

**Comment by oliver-phet** [comment]
I added a simple Yes/No to the top of the sheet for checking if the single file download and iframe work. Let me know if this is OK or if we want something else.

**Comment by samreid** [comment]
At the developer meeting, we discussed the desire to test iframe compatibility on a few specific platforms, such as Mobile Safari, IE and Firefox.  We also would like the QA tester to note which platform they *did* do their testing on (say if we leave the "run offline" testing up to the QA tester to decide).

**Comment by samreid** [comment]
We should also discuss whether QA testers should run the simulation with ?showPointerAreas or ?ea (probably just on one platform for those).

**Comment by pixelzoom** [comment]
?showPointerAreas (examining pointer areas) is something that should be evaluated by the developer and designer, and should be handled before a sim gets to testers.

?ea (checking for assertion failures) is something that developers should be doing diligently, arguably before on a daily basis, and certainly before publishing a version that other people are going to test.

If these things aren't happening, then I don't think the solution is to add more things for the testers to do. Perhaps there needs to be a "pre test" check list of things that must pass before testing begins?

**Comment by samreid** [comment]
> Perhaps there needs to be a "pre test" check list of things that must pass before testing begins?

To me, that sounds like it would be very helpful.

**Comment by samreid** [comment]
By the way, for the spreadsheet I think it would make more sense if the new tasks were put at the bottom (perhaps we can somehow direct Chrome to have new column headers starting at a certain row).  Then it becomes simple: one task per row.  And easy to add more tasks as necessary.

**Comment by oliver-phet** [comment]
We decided at developer meeting on Feb 5 that we will have iFrame and Download as 'optional tests' at the bottom of the testing matrix. The developer can decide which platforms/tests need done when creating the testing task.
