### ISSUE TITLE
Redesign of recruting flyer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#149]
This flyer, meant to attract computer science undergrads to apply for an internship at PhET, needs work. Right now there just isn't sufficient information on the flyer to convey what PhET is, what we are soliciting, and how to apply, unless you have a QR scanner. 

Take a stab at redesigning this flyer. We would like to *briefly* explain what PhET is and that we are offering an internship in sim development. It should have a similar "non-profit" feel to attract people who are interested in working in that environment. 

![sc-recruitment poster-2](https://cloud.githubusercontent.com/assets/7852916/5863013/b8558f1a-a233-11e4-9539-f518a1b3e78c.png)

**Comment by alexklinger** [comment]
I know this was lower priority but inspiration struck.

![phetposter](https://cloud.githubusercontent.com/assets/8651105/5982548/4f1a3cc2-a881-11e4-9e07-abcded1eddee.jpg)

**Comment by pixelzoom** [comment]
Code for Change is a partnership led by NYU Wagner's School of Public Service, One Economy, Code for America and NPower, and Hacker League, in association with the Blue Ridge Foundation.
https://www.hackerleague.org/hackathons/code-for-change

It looks like other organizations are using the same catch-phrase for similar programs. But I wanted you to be aware that it's not something that will be uniquely PhET.

**Comment by amanda-phet** [comment]
@alexklinger I think the new poster looks really nice. I would like to meet at some point to discuss another flyer of ours. 
@pixelzoom do we need to include any of that information on this flyer? It might be included in the original QR code, but I'm pretty sure that just directed you to the job posting.

**Comment by pixelzoom** [comment]
I don't know. Is PhET's "Code for Change" in any way related to the Hacker League program? I wasn't saying that it was.  What I was saying is that it's a common catch phrase that is used by the programs of other organizations.

**Comment by alexklinger** [comment]
@amanda-phet I'd be happy to come in early for the design meeting on wed, or monday 11am-5pm.

**Comment by alexklinger** [comment]
@pixelzoom and @amanda-phet I like the Code for Change copy, as long as it is not trademarked, I don't see a problem seeing as that was a one time event in 2012.

**Comment by amanda-phet** [comment]
@ariel-phet can you please comment? You seemed to say that since we've been using it without issue we should continue using it.

**Comment by amanda-phet** [comment]
@alexklinger What is the aspect ratio for this flyer? It looks slightly taller than 8.5x11, which is what we usually print our flyers on. Can you adjust the design to fit on a standard 8.5x11 sheet of paper? 

Also, the text on the bottom might be easier to read if the background color was slightly darker. 

If you can make these changes, go ahead and put the .ai file in our drive folder.

**Comment by ariel-phet** [comment]
Fine to use it for our purposes since it is just a recruitment flyer for campus and not something we are sending out in a mass email or advertising on our website. Seems to be a good catchphrase.

**Comment by alexklinger** [comment]
@amanda-phet This was designed for 14'' X 17'' which is standard poster size for most of the stuff you see on campus. I'll design one in 8.5'' x 11'' so that you have the option.

**Comment by amanda-phet** [comment]
Looks good. Closing.
