### ISSUE TITLE
Win8 + IE10 test machine is missing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#153]
In https://github.com/phetsims/tasks/issues/146#issuecomment-71262968, @bryo5363 wrote:

> Testing is completed on all devices except IE 10 on Windows 8; the only device that had this browser was the MacBook Air that has been deemed lost. 

Assigning to @ariel-phet to determine how to replace this missing test platform.

**Comment by ariel-phet** [comment]
After doing a bit of research it appears the IE10 does not run directly on Win8 (there is a mode to run IE11 in IE10 mode but this is meant for web developers). 

http://windowsitpro.com/windows-client/internet-explorer-10-windows-81

I will remove IE10 Win8 from the example test matrix.
