### ISSUE TITLE
procure a current iPad for testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#154]
The most current iPad in the test matrix is iPad3 (released March 2012). Shouldn’t we also be testing on something more current?

**Comment by ariel-phet** [comment]
@pixelzoom - what would you suggest? You tend to be "in the know" when it comes to apple products, do they have some planned release? It seems anecdotally things run fine on the iPad4 (I believe @kathy-phet has one). We have also received no issues to my knowledge regarding HTML5 sims and any iPad. I think the philosophy with the iPad3 has been that it is a good indicator, since it has the retina display but a weak processor.

**Comment by ariel-phet** [comment]
Just to add a bit more detail - do we anticipate one of the new platforms causing performance issues? For instance, the retina display was a big change and not surprising that is causes some issues. Obviously we can not know for sure, but it seems like certain changes (new OS, new display) are more worrisome than something like just a faster processor.

**Comment by pixelzoom** [comment]
Let's discuss whether there's a need at developer meeting, see what others think. I just thought it odd that PhET's most current iOS test device is almost 3 years old, which is ancient in the mobile world.  And as we move more into WebGL, it will be important to benchmark on slowest and fastest devices.

The iPad Pro, on the other hand, will be a must-buy device. Rumors: Q2 release, 12.2", 4K display (double the resolution of the iPad retina).

**Comment by arouinfar** [comment]
Having a newer iPad would also benefit our interviews. Yosemite supports iPad screen sharing without the need for 3rd party software, but it only works on modern iPads with the Lightning connector.

Screen recording on an iPad is a bit of a cumbersome process. It requires 3rd party software (Reflector) to screen share to another Mac, which can then have its screen recorded. Reflector doesn't work properly on my or @amanda-phet's MacBook Pro, but it does work on PhET's MacBook Air.  However, the MacBook Air often travels to conferences and isn't always available for interviews.

**Comment by ariel-phet** [comment]
I believe @oliver-phet is going to order a newer iPad shortly

**Comment by pixelzoom** [comment]
@arouinfar thanks for chiming in. It sounds like a newer iPad will be ordered soon. And if access to a MacBook that supports Reflector is an issue, please discuss with @oliver-phet.

**Comment by ariel-phet** [comment]
A newer iPad and a Macbook air have been ordered, closing

**Comment by oliver-phet** [comment]
New iPad Air 2 is on the tester desk and will be added to the asset doc tomorrow.
