### ISSUE TITLE
Safari 8 desktop missing from test matrix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#155]
The test matrix currently has this test category:

> Device = Mac OS X 10.9.5 & 10.10.1, Browser = Safari 7

Mac OS X 10.10 has Safari 8, which appears nowhere in the matrix. So I recommend splitting 10.9.5 and 10.10 into separate "Device" types.

**Comment by bryo5363** [comment]
@pixelzoom when I tested on 10.10 I just entered the Safari version into the browser bar. To conserve space we can just add Safari 7/8. This way we don't have to allocate additional rows for 10.10.1, especially since there is no difference between chrome and Firefox versions.

**Comment by pixelzoom** [comment]
@bryo5363 That doesn't make it clear that Mac OS 10.10 + Safari 8 is a required test. I'd prefer to split it out, even if Mac OS 10.10 has only one required test (Safari 8).

**Comment by bryo5363** [comment]
Sounds goo . I can update the matrix for RPAL since I need to finish HTML downloads. I apologize for the lack of speed on this matrix, I have been quite busy with schoo . It will be complete by tomorrow.

**Comment by pixelzoom** [comment]
No need to update the RPAL matrix, this is something we'll address in the matrix template after developer meeting discussion. Thanks.

**Comment by pixelzoom** [comment]
I changed the Mac OS X sections of the example test matrix, see screenshot below.  The rationale is that the testing on older versions of Mac OS X only needs to be done on older versions of Safari, which Chrome and Firefox should be tested on the latest version of Mac OS X.

@samreid @jonathanolson @jbphet please chime in if you disagree.

@ariel-phet If this looks OK, please close. 

![Uploading screenshot_190.png . . .]()
