### ISSUE TITLE
Test Molecules and Light 1.0.0-dev.3

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#157]
Please test 1.0.0-dev.3 http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.3/molecules-and-light_en.html 

@arouinfar Has the sim been interviewed on? If not, use this dev version.

**Comment by arouinfar** [comment]
@oliver-phet, I've already finished my scheduled interviews.  I ended up using dev.1 because dev.2 had serious issues preventing it from being usable in an interview (e.g. browser crashing, photon sources and molecules disappearing from the menus).

**Comment by ariel-phet** [comment]
Closing since we are going to make a few tweaks to the sim and reinterview
