### ISSUE TITLE
Create PhET "Bookmark" for Future Conference Booths

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#158]
We should consider making a informational bookmark similar to the one from RSC. A nice in between solution to a full flyer and minimal detail of a business card.

**Comment by amanda-phet** [comment]
Once we figure out #163 we will talk to @alexklinger about designing a bookmark to accompany the flyer.

**Comment by alexklinger** [comment]
Here is the first draft of the bookmark, I wasn't sure what information was important, so I kind of guessed. 

Side 1:
![phetbookmarkdraft-01](https://cloud.githubusercontent.com/assets/8651105/7106745/7e3cd292-e109-11e4-88bf-b9e3c7dccb1a.png)

Side 2:
![phetbookmarkdraft-02](https://cloud.githubusercontent.com/assets/8651105/7106747/b330371e-e109-11e4-9cbf-7ccc5b9d8a27.png)

**Comment by ariel-phet** [comment]
@daveunderwood - above you can see a rough draft that one of our students started in the past for a bookmark. No need to use any of the above, but you can see someone else's take on it.

**Comment by ariel-phet** [comment]
Our flyer and business cards seem to have been working well at the booth, closing
