### ISSUE TITLE
put all PhET-specific globals under window.phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#160]
Put all PhET-specific globals under window.phet, but refer to in code as phet.something.

**Comment by pixelzoom** [comment]
There are some PhET-specific globals in .html files (e.g. sim.html) so make sure those get changed too.

**Comment by pixelzoom** [comment]
Here are the PhET-specific globals that I was able to locate, by repository where they are defined. Scenery is not included here.

I was only able to indentify globals defined using `window.` prefix. If code is creating globals without `window.` prefix, I have no way to search for it. 

arch: phet.arch
assert: assertions, assert, assertSlow
axon: loadedAxon
build-a-molecule: loadedBuildAMoleculeConfig, namespace
dot: loadedDotConfig
energy-skate-park-basics: phetModel
joist: phet.*, phetJoistSimLauncher, TWEEN, simScene, simDisplay, simScreenshot, makeEverythingSlow, makeRandomSlowness, phetImages, performance
kite: loadedKiteConfig
mobius: loadedMobiusConfig, 
molecule-shapes: loadedMoleculeShapesConfig
phetcommon: phetcommon
phetcore: loadedPhetCoreConfig, phetAllocation, alloc, jshintOptions, jshintGlobals, module, phetVersion, phetLocale, hewlettOERTracker
sun: debugText
together: phet.*

**Comment by pixelzoom** [comment]
In addition to the `phet` qualifier, should we also indicate which repository the global is defined in? arch is currently doing this. Could be useful to prevent collisions, but could be verbose for long repo names.

For example:

phet.phetcommon.getQueryParameter
phet.energy-skate-park-basics.model
phet.joist.makeEverythingSlow
phet.kite.loadedConfig

I think I like having the repository name included. Opinion from @samreid @jonathanolson and @jbphet ?

**Comment by pixelzoom** [comment]
@jonathanolson how do you want to handle scenery? Will it attach all of its globals to window.phet.scenery? Are there globals that are not defined using `window.` prefix? Do you want to handle changes?

**Comment by jonathanolson** [comment]
Scenery standalone (via grunt build) defines window.scenery, but this isn't defined in sims (to keep our namespace clear). Similarly, Kite standalone uses window.kite.

For simulations, I'd be happy to attach the namespaces as follows (the conventions I have been using, but with the .phet prefix):
window.phet.core = <phet-core>
window.phet.axon = <axon>
window.phet.dot = <dot>
window.phet.kite = <kite>
window.phet.scenery = <scenery>

**Comment by jonathanolson** [comment]
Also, this is most helpful for debugging, as we use require.js for almost all loading purposes.

**Comment by jonathanolson** [comment]
Also dashes don't work in names, "phet.energy-skate-park-basics.something" is "phet.energy - skate - park - basics.something"

**Comment by pixelzoom** [comment]
@jonathanolson I see that the repos you've been involved with have a global that looks like this (for example):

> kite: loadedKiteConfig

What is this "load*Config" global used for?

**Comment by samreid** [comment]
> Looking at these examples, I think I like having the repository name included.

Yes, that seems like a good rule of thumb for now.

**Comment by jonathanolson** [comment]
loaded*Config is vestigial. It was used for HTML files that want to use require statements, and we needed to set a global and loop until it was loaded. Now we can use the nested require form (changed with https://github.com/phetsims/scenery/commit/813fbc98d5d8020043821bcb0ee2789438eb975f for Scenery).

I've been working my way through those, must have missed one.

**Comment by pixelzoom** [comment]
I said:
> Looking at these examples, I think I like having the repository name included.

@samreid said
> Yes, that seems like a good rule of thumb for now.

@jonathanolson pointed out:
> Also dashes don't work in names, "phet.energy-skate-park-basics.something" is "phet.energy - skate - park - basics.something"

How would you like to handle repo names that contain hyphens? energyskatepark-basics? energySkateParkBasics? other ideas?

**Comment by jonathanolson** [comment]
I believe I saw consensus in Skype chat for energySkateParkBasics

**Comment by pixelzoom** [comment]
We're not going to change the globals defined by assert.js.  If we did, we'd need to change all occurrences of:

> assert && assert( expression );

to:

> phet.assert.assert && phet.assert.assert( expression );

@jonathanolson said via Skype:
> [1/30/15, 2:48:13 PM] Jonathan Olson: I would like to leave it alone
[1/30/15, 2:48:42 PM] Jonathan Olson: since in general it's sims that rely on the phet.X namespace, not the more general libraries

**Comment by pixelzoom** [comment]
Completed dot: https://github.com/phetsims/dot/commit/c8a39d255f8d31727cf387fd07577db6d8c1168a

**Comment by pixelzoom** [comment]
@jonathanolson removed axon.loadedAxonConfig in https://github.com/phetsims/axon/commit/9db795a128d2e9339b5f7084f8e601fb2b6d5453.

**Comment by pixelzoom** [comment]
@jonathanolson removed BAM global in https://github.com/phetsims/build-a-molecule/commit/92491b52b46ba264192469e04de6f7d5165358d7

**Comment by pixelzoom** [comment]
@jonathanolson removed kit globals in https://github.com/phetsims/kite/commit/29e2af5a6cbcf47c8bf29ef1715c8ed48765fb8a.

**Comment by pixelzoom** [comment]
@jonathanolson removed window.loadedPhetCoreConfig in https://github.com/phetsims/phet-core/commit/d1121ec857d95c2b8fe345e1c6ec72609e4d9d0a.

**Comment by pixelzoom** [comment]
@jonathanolson removed loadedMobiusConfig in https://github.com/phetsims/mobius/commit/d896843c7491a1e2c6a8720eba1a93bf4b01eb9b.

**Comment by pixelzoom** [comment]
@samreid arch.js is creating a lot of globals: targets, websocketURL, websocketPath, webSocket, bufferedWebSocket, storedMessages, storeMessageListener.  Is this intentional/necessary? Or can we encapsulate these in an IIFE?

**Comment by pixelzoom** [comment]
These globals need some discussion:

window.alloc
window.phetAllocation
window.hewlettOERTracker

If I change them to conform to the naming convention for PhET globals, they would be:

window.phet.phetCore.alloc
window.phet.phetCore.phetAllocation
window.phet.phetCore.hewlettOERTracker

In the case of alloc and phetAllocation, I'm worried about the verbosity.  In the case of hewlettOERTracker, I don't know how this is being used, and whether the longer name presents any issues.

@jbphet @jonathanolson @samreid please chime in.

**Comment by samreid** [comment]
> @samreid arch.js is creating a lot of globals that don't appear to be used outside of arch.js: targets, websocketURL, websocketPath, webSocket, bufferedWebSocket, storedMessages, storeMessageListener. Is this intentional/necessary? Can we encapsulate these in an IIFE?

Yes, I think so.  Let's create an arch issue and investigate there.

**Comment by jonathanolson** [comment]
phetAllocation is used in things like Dot, where there is no creation of a global window.phet.

**Comment by samreid** [comment]
I haven't had to rely on window.alloc, window.phetAllocation and window.hewlettOERTracker lately so am not too concerned about their verbosity.  Typical use of phetAllocation is something like:

```js
phetAllocation && phetAllocation( 'Bounds3' );
``

In my opinion, it is fine if this is < 120 characters to keep it on one line.

window.alloc is exported by phetAllocation for inspection in the browser--not used in sim/library code, and I'm fine to rename it.

Not sure what the OERTracker is.

I also think it is odd for phetcommon and phetcore to contain the name "phet"--seems duplicated.  Perhaps rename them to 'common' and 'core', or something a bit more suitable & catchy?

**Comment by samreid** [comment]
I agree we should keep assert as a top level global.  (Hard to say whether we will want other exceptions).  But I could be persuaded otherwise if others feel strongly.

**Comment by samreid** [comment]
The "I made one" strategy here seems like a nice way to check for extra window leaks at runtime:
http://stackoverflow.com/questions/14063064/how-to-find-the-global-variables-used-in-my-javascript

**Comment by pixelzoom** [comment]
Yes, that could be a handy utility.

**Comment by samreid** [comment]
> Yes, that could be a handy utility.

We could bake it into our framework, and run it when ?ea is turned on.  That could help us crowdsource the testing of it.

**Comment by pixelzoom** [comment]
When ?ea is on, I want to see assertion failures. Printing legitimate globals might obscure that, so I'd prefer a separate query parameter, something like 'printPhetGlobals'.

**Comment by samreid** [comment]
Let me clarify: the assertion I was recommending would look something like this:

```js
assert && assert(illegalGlobals.length===0,'the simulation should not create any globals');
```

where `illegalGlobals` is computed using the logic above together with our heuristics for what is allowed (such as window.phet).

**Comment by pixelzoom** [comment]
Discussion about checking for illegal globals ("I made one" strategy) moved to https://github.com/phetsims/phet-core/issues/17.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> phetAllocation is used in things like Dot, where there is no creation of a global window.phet.

OK, I guess we'll leave phetAllocation (and alloc) attached directly to window.

**Comment by pixelzoom** [comment]
My work on this is done.

Cleanup of arch globals has been assigned to @samreid. See https://github.com/phetsims/arch/issues/22, https://github.com/phetsims/arch/issues/23

Globals that didn't move to window.phet and why:

• assert, assertSlow, assertions - Used everywhere, more convenient to write assert && assert
• phetAllocation, alloc - used in scenery
• hewlettOERTracker - liable to break Google analytics if not attached to window

Closing.
