### ISSUE TITLE
Test States of Matter v1.0.0-dev.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#161]
Our contractor has delivered an initial version of this simulation for testing.  It has had some cursory testing since delivery, but not much, so this is some of the first thorough internal PhET testing to occur on this sim.

There are known issues on iPad, so for now please restrict your testing to desktop for now.  It would be good to test multiple OSes and browsers, see the list below.  Please check them off below as you do.

- [x] Windows 7 or 8 + Chrome latest
- [x] Windows 7 or 8 + Firefox latest
- [ ] Windows 7 or 8 + Internet Explorer
- [ ] OSX 10.8 or higher + Safari
- [x] OSX 10.8 or higher + Chrome
- [x] OSX 10.8 or higher + Firefox

Link: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html.

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele @arnabp please make this your top testing priority

**Comment by ariel-phet** [comment]
Although not complete closing for now, so Actual Concepts can proceed with fixes instead of delaying until all platforms are tested.
