### ISSUE TITLE
Regression test Balancing Act v1.0.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#162]
An issue has been identified that warrants a maintenance release for the Balancing Act simulation, see https://github.com/phetsims/balancing-act/issues/40 and https://github.com/phetsims/balancing-act/issues/42.  The fixes that have been implemented for these issues should, in theory, produce no functional changes from v1.0.1, which is currently published on the web site.  The QA team should verify that v1.0.2 (link: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.0.2/balancing-act_en.html) doesn't introduce any new issues vs. the currently published version (link: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.0.1/balancing-act_en.html).

This is regression testing for a maintenance release, not a full release test, so no separate spreadsheet will be set up.  Still, the QA team should test on several different browser/OS combos and at least on iPad.

**Comment by jbphet** [comment]
This has been discussed with @ariel-phet and @phet-steele (both are in my office at the moment), and @phet-steele will be assigned.

**Comment by phet-steele** [comment]
Everything checks out on iPad, Win 8.1 and OSX 10.9.5. I logged a ticket that contains problems that hopefully don't prevent release.

**Comment by jbphet** [comment]
The issue to which @phet-steele is referring is https://github.com/phetsims/balancing-act/issues/43.  The issue is difficult to reproduce, and has likely always been there, so this should not block publication of the maintenance release.

**Comment by jbphet** [comment]
Testing seems adequate, thanks.  Closing.
