### ISSUE TITLE
Redesign of teacher/conference flyer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#163]
Redesign the flyer we distribute mainly to teachers at our booth at conferences. We want to advertise our free interactive simulations, give some context about the program and how sims can be flexibly used in classrooms, and especially emphasize the URL and the fact that they are free.

**Comment by alexklinger** [comment]
![flyerredesign-04](https://cloud.githubusercontent.com/assets/8651105/6338281/eea76a98-bb6a-11e4-8469-6a0d4e2ae372.png)

**Comment by pixelzoom** [comment]
Looks like there's a black rectangle across the top of the "Color Vision" screenshot. You can see it in the top "thought bubble" and in the red slider.

**Comment by amanda-phet** [comment]
This is just to show the progress made so far- by no means a final draft!

**Comment by alexklinger** [comment]
![flyerredesignalexpg2](https://cloud.githubusercontent.com/assets/8651105/6432729/395fa3f4-c019-11e4-98c2-f4841b177064.jpg)
![flyerredesignalexpg1](https://cloud.githubusercontent.com/assets/8651105/6432730/396042fa-c019-11e4-8bdd-6418d97e7e90.jpg)

**Comment by amanda-phet** [comment]
Thanks @alexklinger. Can you please email me the ai file so that I can edit the prompts and copy?

**Comment by amanda-phet** [comment]
After review by Kathy and others, we have a new version of our teacher flyer. Thanks @alexklinger
