### ISSUE TITLE
Dev testing for Molecule Shapes 1.0.0-dev.14

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#164]
Please dev test the latest version of Molecule Shapes (http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.14/molecule-shapes_en.html)

It has two performance modes, WebGL (used if available) and Canvas. In bug reports, if possible note which modes a bug occurs in. The changes are quite apparent visually (and Canvas is much slower):

WebGL:
![molecule-shapes-webgl](https://cloud.githubusercontent.com/assets/480878/4804181/0f10445a-5e67-11e4-9441-974115ff4626.png)
Canvas:
![molecule-shapes-canvas](https://cloud.githubusercontent.com/assets/480878/4804184/14a9ded0-5e67-11e4-87db-65ddc691555b.png)

Testing should also include the (fairly hidden) global options. Go to the PhET Menu => "Options", and try things with settings on/off. The "lone pairs" global option only changes appearance in the 2nd screen.

Testing of multi-touch handling would be appreciated. On each screen, either multiple atoms/lone pairs can be dragged at the same time (with different fingers), OR the molecule can be rotated as a whole.

Additionally, I would appreciate testing of the screenshot mode (please test http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.14/molecule-shapes_en.html?screenshot). The screenshot (PhET Menu => Screenshot) should work on both screens, and the appearance/rotation of the molecule should look like it does in the sim. Some platforms may not have a Screenshot item in the menu (this is expected), no need to report that.

Testing on the following platforms would be appreciated (let me know if certain platforms can't be tested):

- [ ] Windows + Chrome (expect WebGL)
- [ ] Windows + Firefox (expect WebGL)
- [ ] Windows + IE9 (falls back to Canvas)
- [ ] Windows + IE11 (expect WebGL)
- [ ] OS X + Safari 7.0 or eariler (falls back to Canvas)
- [ ] OS X + Safari 7.1+ (WebGL manually enabled)
- [ ] OS X + Safari 8 (WebGL manually enabled)
- [ ] OS X + Chrome (expect WebGL)
- [ ] OS X + Firefox (expect WebGL)
- [ ] iPad iOS 7 + Safari (falls back to Canvas - interested if performance is at all usable)
- [ ] iPad iOS 8 + Safari (expect WebGL)

Known issues:

Original Java simulation: http://phet.colorado.edu/en/simulation/molecule-shapes

Please report any issues to https://github.com/phetsims/molecule-shapes/issues.

Thanks!

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele @arnabp this should be the next main priority once states of matter dev testing is complete.

**Comment by bryo5363** [comment]
@jonathanolson The sim does not open in Safari 8

**Comment by pixelzoom** [comment]
Opens for me on Mac OS 10.10.2 + Safari 8.0.2.  @bryo5363 what version of Mac OS 10? Or is this iOS?

**Comment by pixelzoom** [comment]
Perhaps @bryo5363 doesn't have WebGL enabled. If I turn off WebGL, the sim crashes on startup, console error below. (Isn't it supposed to fallback gracefully to canvas?)

![screenshot_446](https://cloud.githubusercontent.com/assets/3046552/6025486/159f9f8e-ab90-11e4-8c96-c2ffd81e96c3.png)

**Comment by bryo5363** [comment]
I was using OSX 10.10.1 with Safari 8.0. It was on the testing device labeled Dirac.

**Comment by jonathanolson** [comment]
https://github.com/phetsims/scenery/issues/374 is a bug that will cause failures for any browser that doesn't have WebGL enabled. Please only test this dev release for WebGL-supported browsers (I'll have another release to test non-WebGL browsers).

**Comment by ariel-phet** [comment]
Test moved to #168 closing
