### ISSUE TITLE
Inventory/Cataloging of PhET devices [THU FEB 5]

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/tasks#165]
We need to inventory all of the PhET communal devices and create an up-to-date digital record of these devices. We've asked folks who've borrowed communal tech to return it to F1011 on **Thursday Feb 5** for inventory day so that we can update our records and give devices more permanent homes.

On this day, these are the tasks that need to happen:

- [x] Ensure that every device has a unique name and is labelled
- [x] Label power adapters and cables with the name of the device
- [x] Where possible, update the device's name digitally to match the label (e.g. if possible, add the device name to the user id or device name in the OS/software)
- [x] Assign specific home locations for all devices (e.g. a specific drawer or shelf location) and label these locations with the device names. 
- [x] Update the <a href="https://docs.google.com/spreadsheets/d/1PzD7H2xGrkZewcuYXtAKtmwWe9I3syU6rtAZAaobA-Y/edit#gid=0">PhET asset tracking document</a> with...
    * Updated device names
    * Updated home location
    * All OS/browser combinations on that device, including virtual machines (label these as VM)
    * Login/password information (if applicable)
    * Any specialized/purchased software licenses installed (e.g. Camtasia, Reflector, Atlas.ti, Illustrator, etc.)
    * Other important technical info (*e.g. 'Must be plugged in at all times' or 'Runs the phettest server' or 'Has a blank partition available'*)

For the devices home locations, it is preferable if *most* of them can be located in the same room (F1011), so that they can be signed out more easily when borrowed in future [once the digital inventory is completed, we'll be creating a whiteboard that folks will sign when borrowing devices].

@bryo5363, @orejolaphet, and @arnabp, please coordinate between the three of you to get everything catalogued and updated. If there are devices in the spreadsheet that you can't locate, or questions about any of the device specs, check with @oliver-phet.

**Comment by ycarpenterphet** [comment]
Colored labels arrived today for labelling the power cables associated with various devices. I've placed these on the desk, so could @orejolaphet wrap up this task by adding the color-coded labels to the charging cables as discussed last week?

Once that's done, feel free to close this task.

**Comment by orejolaphet** [comment]
All of the apple chargers have now been color labeled. Scheme is as follows 
Yellow- Macbook Air
Red- iPad
Blue- iPad Mini & iPad air
Green- Mac Book Pro
Closing.
