### ISSUE TITLE
Change the wording for the Forces and Motion: Basics blurb

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#166]
While I was working on https://github.com/phetsims/tasks/issues/159 to design the sim README.md pages, I saw the text for Forces and Motion: Basics is still referring to "tug of war".  In https://github.com/phetsims/forces-and-motion-basics/issues/91 we renamed all of the "Tug of War" things to "Net Force" because using the term "Tug of War" could lead to misconceptions.  Hence, we should reword the blurb as well.  Assigned to @ariel-phet since he had thoughts about the renaming.

The current blurb reads:
> Explore the forces at work in a tug of war or pushing a refrigerator, crate, or person. Create an applied force and see how it makes objects move. Change friction and see how it affects the motion of objects.

**Comment by ariel-phet** [comment]
Simple wording change made

**Comment by samreid** [comment]
Thanks, looks good.
