### ISSUE TITLE
Camtasia front page video assets and gifs

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#167]
Hi @orejolaphet,

Could you email me the original camtasia files for the front pages videos? It would be good to have these backed up on a server somewhere.

Also, when you have a chance, can you look into exporting these videos as animated gifs with camtasia? I have been trying to convert the mp4s you sent to gifs, but I am getting lousy quality. If we can get the videos in gif format they will also play on iPhone and iPad.

Ideally, I would need gifs that are:

- 325px by 213px
- Don't have gradients that look separated into different bands
- As small a file size as you can get with decent quality

You can always open the gif files with a web browser to test what kind of quality you are getting. The main videos with issues are Energy Skate Park Basics and Balancing Act, since these have gradients in the sky.

Let me know if you have questions. Thanks!

**Comment by orejolaphet** [comment]
@aaronsamuel137 I just sent you the folder with all of the website videos. I looked into a converting one of the videos in to a gif format, and the quality was compromised. I'll try to find a way to do it with out losing quality.

**Comment by orejolaphet** [comment]
My attempts at converting to a gif format with Camtasia leave the gradients discrete, and text very blurry.

**Comment by aaronsamuel137** [comment]
I had the same problem. I think (though I'm not positive) it's because the mp4 files are already pretty compressed so the original videos are not high enough quality to yield a high quality gif.

Do you have higher quality originals, or are these mp4s the best we have?

**Comment by orejolaphet** [comment]
Videos I sent you were the highest quality I had left. I did noticed there were apps dedicated to gif conversion that seemed fairly good quality, although they cost money (2-5 dollars or something).

**Comment by ariel-phet** [comment]
Looks like @aaronsamuel137 now has the original files, and if direct conversion from camtasia does not produce good results, it is highly unlikely that an app will do better (camtasia is pretty elite software). Closing this issue.
