### ISSUE TITLE
Test Molecule Shapes 1.0.0-dev.15 and Molecule Shapes: Basics 1.0.0-dev.8

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#168]
Please dev test the latest version of Molecule Shapes (http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html) and Molecule Shapes: Basics (http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.0.0-dev.8/molecule-shapes-basics_en.html)

Presumably don't repeat testing done in https://github.com/phetsims/tasks/issues/164.

They has two performance modes, WebGL (used if available) and Canvas. In bug reports, if possible note which modes a bug occurs in. The changes are quite apparent visually (and Canvas is much slower):

WebGL:
![molecule-shapes-webgl](https://cloud.githubusercontent.com/assets/480878/4804181/0f10445a-5e67-11e4-9441-974115ff4626.png)
Canvas:
![molecule-shapes-canvas](https://cloud.githubusercontent.com/assets/480878/4804184/14a9ded0-5e67-11e4-87db-65ddc691555b.png)

Testing should also include the (fairly hidden) global options. Go to the PhET Menu => "Options", and try things with settings on/off. The "lone pairs" global option only changes appearance in the 2nd screen.

Testing of multi-touch handling would be appreciated. On each screen, either multiple atoms/lone pairs can be dragged at the same time (with different fingers), OR the molecule can be rotated as a whole.

Additionally, I would appreciate testing of the screenshot mode (please test http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html?screenshot). The screenshot (PhET Menu => Screenshot) should work on both screens, and the appearance/rotation of the molecule should look like it does in the sim. Some platforms may not have a Screenshot item in the menu (this is expected), no need to report that.

Testing on the following platforms would be appreciated (let me know if certain platforms can't be tested):

- [x] Windows + Chrome (expect WebGL)
- [x] Windows + Firefox (expect WebGL)
- [ ] Windows + IE9 (falls back to Canvas)
- [x] Windows + IE11 (expect WebGL)
- [x] OS X + Safari 7.0 or eariler (falls back to Canvas)
- [x] OS X + Safari 7.1+ (WebGL manually enabled)
- [x] OS X + Safari 8 (WebGL manually enabled)
- [x] OS X + Chrome (expect WebGL)
- [x] OS X + Firefox (expect WebGL)
- [x] iPad iOS 7 + Safari (falls back to Canvas - interested if performance is at all usable)
- [x] iPad iOS 8 + Safari (expect WebGL)

Known issues:

Original Java simulation: http://phet.colorado.edu/en/simulation/molecule-shapes

Please report any issues to https://github.com/phetsims/molecule-shapes/issues.

Thanks!

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele @arnabp this should be the next main priority once states of matter dev testing is complete.

**Comment by phet-steele** [comment]
Performance is slow with iOS 7 and Safari with most molecules that have octahedral molecular geometry. The performance is very dismal with the larger real molecules (XeF4, BrF5, PCl5, and SF6) coupled with outer lone pairs being shown. Dragging the molecule quickly results in lone pairs lagging behind and detaching from their molecule. An issue will be made at https://github.com/phetsims/molecule-shapes/issues
![photo](https://cloud.githubusercontent.com/assets/5863899/6085958/4349c6a4-adfb-11e4-8667-365810f9895d.PNG)

**Comment by bryo5363** [comment]
The sim looks great on OSX 10.9.5 Chrome 40.0.2214.111 (64-bit)

**Comment by ariel-phet** [comment]
This should currently be top priority to finish off

**Comment by bryo5363** [comment]
The simulation does not open on IE 9

**Comment by jonathanolson** [comment]
Closing for now, thanks! I have the IE9 issue fixed, and presumably we'll have an RC soon.
