### ISSUE TITLE
Update budgets through Jan 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#169]
@arnabp Please prioritize updating these budgets through Jan 2015:
Moore NSF DRK12 NSF DRK12 Matching NSF TUES CHEM

Also, your laptop is in F1011 - should hopefully get labeled today.

**Comment by arnabp** [comment]
I updated all of them except Moore, I can't seem to find the folder for that

**Comment by oliver-phet** [comment]
Sorry, number is: 13005113
