### ISSUE TITLE
Student Worker "Getting Started" Google Doc

### ISSUE THREAD

**Issue by phetsims** [phetsims/tasks#17]
Hey @orejolaphet can you start a "PhET Student Worker Intro" google doc? Maybe brainstorm with @bryo5363 the things you have to know...getting a gmail account, getting shared on google docs, getting a github account, maybe paste in some "how to make a good bug report" instructions. Basically a checklist of good things to know as a student worker. 

Not a super high priority, but would be nice to have an organized document by the end of the summer.

**Comment by ariel-phet** [comment]
@phet-steele this doc might be good to go through and see if it is up to date (guessing it is not) especially with phettest. Perhaps work with @brroberts1231 to update? and close this issue?

**Comment by phet-steele** [comment]
Moved to phetsims/QA/issues/110.
