### ISSUE TITLE
Consider publishing through the Apple AppStore

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#170]
It would be possible to publish individual simulations through the Apple AppStore.  This could make it easier for certain customers to access and use our simulations, and could improve our visibility.  It could be something like ~20 developer hours to investigate packaging our sims into an WebView (I forget the name of the new, faster iOS8 WebView), but that would be the right starting point.

The improved availability of our sims would be traded off against time to build/maintain/deploy sims to the AppStore, and the risk that they could get stale.

**Comment by ariel-phet** [comment]
I think we might consider this step after we have made our iOS App with the CS senior design project.

**Comment by ariel-phet** [comment]
@kathy-phet remarked awhile back that she wanted to hold off on this effort indefinitely until the PhET App has traction. Closing.
