### ISSUE TITLE
change ownership of Google Drive assets to phethelp

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#171]
@ariel-phet requested this at 2/5/15 developer meeting. phethelp's Gmail address is phethelp@gmail.com.

**Comment by pixelzoom** [comment]
I transferred ownership of all PhET documents that I've created to phethelp. 

Probably the easiest way to make sure this happens is to keep reassigning this issue until everyone has completed ownership transfer.  (Then figure out what to do with docs that are owned by people who are no longer with PhET.)  Assigning to @ariel-phet next, since he owns a fair number of the docs.

**Comment by pixelzoom** [comment]
Note that this applies to all types of Google Drive assets (documents, spreadsheets,...)

**Comment by ariel-phet** [comment]
All of my docs are done. @samreid you are up next!

**Comment by samreid** [comment]
is there a way to transfer google drive document ownership as a batch, or only one at a time?

**Comment by samreid** [comment]
Looks like CMD-A (ctrl-A) works, and sharing settings will apply to all selected.

**Comment by samreid** [comment]
Apparently I am unable to change the owner of these document to phethelp:

![image](https://cloud.githubusercontent.com/assets/679486/6136224/37d3ec80-b12c-11e4-8c6d-49cce239ac4e.png)

**Comment by pixelzoom** [comment]
@samreid wrote:
> Apparently I am unable to change the owner of these document to phethelp:

That's odd... Any idea why? Have you shared those docs to phethelp?

**Comment by samreid** [comment]
No idea.  After sharing to phethelp, the dropdown box reads like the image below.  Only appears to be a problem for video files and one PDF so far.

![image](https://cloud.githubusercontent.com/assets/679486/6136400/9bfdf7b8-b12d-11e4-9766-35fe521e650e.png)

**Comment by samreid** [comment]
According to this thread https://productforums.google.com/forum/#!msg/drive/-Wlq_u_1_24/iVrgEOHYOBQJ

> You cannot change ownership of synced or uploaded documents.

**Comment by samreid** [comment]
I have tried to work around this problem by creating a Google Drive Folder owned by phethelp, then transferring the files into that directory.

**Comment by samreid** [comment]
OK I finished transferring all of my created documents.  For synced documents I have moved them to a folder called "phet-synced-files" which phethelp owns.  Note to those that follow in my footsteps, I searched `owner: me` to find the documents I owned.  Looks like @jbphet is up next!

**Comment by samreid** [comment]
Another option for @ariel-phet to consider.  phethelp@gmail.com could download all of those synced files that I own, then reupload them, ensuring that phethelp owns (at least once copy of) them.  I'll leave it up to @ariel-phet to decide whether to go for it, or if it is good enough as it is.

**Comment by jonathanolson** [comment]
I've changed ownership on all of my shared files (all docs).
