### ISSUE TITLE
Urgent: Graphic Design Poster Work

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#172]
I would like to have PhET's new graphic designer do some polishing of a poster I 
have created. The deadline is soon, I need to submit by late afternoon Tuesday Feb.10.

The Powerpoint file is located at https://drive.google.com/file/d/0B44Uycdx6JGdMk9MWUlTQzI3SVU/view?usp=sharing . Again, I would just like a little polishing, if this is possible by mid-day Tuesday.

**Comment by alexklinger** [comment]
Yeah I can clean it up for you by tuesday. Looks like the spacing could just use some alignment.

**Comment by ariel-phet** [comment]
@alexklinger  The PhET logo is also incorrect (airplane is missing the tail, low res, incorrect font for Interactive Simulations, and that should be all caps). @amanda-phet can get you the proper logo, but you probably already have access to it on google drive.

**Comment by emily-phet** [comment]
@alexklinger: Thanks for looking into this. Depending on how much time you have, it could have more substantial changes - I can decrease some the text, and also have some background color.

Here are two examples from the conference where this poster will be shown:


1) ![chi14_wip_poster_mph_kamp_desmet-2](https://cloud.githubusercontent.com/assets/5109055/6101476/351e6b0a-afe2-11e4-9889-9779970dfabd.png)

2) https://drive.google.com/file/d/0B44Uycdx6JGdR0xTMHZJWVh1OWc/view?usp=sharing

**Comment by alexklinger** [comment]
@emily-phet Are there specific physical dimensions this will be printed on?

**Comment by emily-phet** [comment]
@alexklinger: The maximum size would be 4 feet wide x 3 feet high. The final version will need to be printed for the poster session (at whatever it's final full size is) and also made into an A4 or letter sized pdf file for publication.

**Comment by alexklinger** [comment]
@emily-phet Okay well I just worked in the powerpoint document you gave me and those dimensions for now. I really like the second example you showed and I'd be happy to do a more thought out concept like that with more time. For now, I've cleaned up a lot of alignment issues, and moved a few things. 
![2015-sigchi_handocclusionposter 001](https://cloud.githubusercontent.com/assets/8651105/6121919/f1072c3c-b0a8-11e4-99e4-ca4d5c719b7e.jpg)

**Comment by emily-phet** [comment]
@alexklinger: Looks great! If you're all done, just email me the powerpoint file.

**Comment by alexklinger** [comment]
@emily-phet Alternatively 

![2015-sigchi_handocclusionposter2 001](https://cloud.githubusercontent.com/assets/8651105/6122027/c914ee92-b0aa-11e4-8254-4e942a26a724.jpg)

**Comment by emily-phet** [comment]
Thanks @alexklinger. Posters were received and submitted (yay!). I went with the one where my name is centered. The final poster doesn't need to be printed until early April. If you have time for a more invasive re-design, that would be wonderful. The conference I'll be presenting at is a tech conference in Korea, where folks have very polished looking presentations. 
As an aside, I will also need some poster work done for a different conference in March. I'll open a separate issue for that one.
