### ISSUE TITLE
ACS Poster Design & Polishing

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#173]
I will be presenting a poster on accessible PhET simulations at the American Chemical Society Conference in March. The poster was invited as part of the Sci-Mix event, a general audience mixer - so it will get more exposure than a typical poster session. I would like help designing this poster, and also polishing up the final product.

**Comment by amanda-phet** [comment]
@alexklinger does that timeline work for you? Will you be available early-mid March to work on this?

**Comment by alexklinger** [comment]
@emily-phet Yeah, this works.

**Comment by arouinfar** [comment]
Closing since the poster has been completed.
