### ISSUE TITLE
test out iPad Air mirroring with Yosemite

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#174]
We should be able to screen record an iPad (running iOS 8) using the lightening USB cable (so only the iPad Air is applicable) and a mac running Yosemite (one of the macbook airs, please). See this post: http://www.tekrevue.com/tip/record-iphone-screen-quicktime/

Can you please try this out and let us know how easily it works? If it is smooth, document how to do this (perhaps the same document as the one you already started that uses Reflector). 

Then, investigate if we can do this wirelessly but without 3rd party software (like Reflector) so that we have that as an option.

**Comment by amanda-phet** [comment]
Investigate this, too, to compare: http://www.techsmith.com/tutorial-camtasia-mac-fuse-connect-mobile-device.html?utm_source=social&utm_medium=twitter&utm_content=notification&utm_campaign=cm

**Comment by ariel-phet** [comment]
@arnabp - since you are a pretty tech savy guy, please work on this task when you get a chance (after your high priority items for @oliver-phet are done)

**Comment by arnabp** [comment]
Setting up the quicktime recording on iPad is pretty straightforward, if you wanted to paste these instructions into the reflector document:
{
Plug in iPad to Macbook via Lightning USB cable
Open Quicktime (Image Capture will probably also open, ignore it)
Go to File>New Movie Recording
Click on dropdown arrow beside record button and select the iPad for both camera and microphone*
Click on the record button and your recording will begin.

*If the iPad does not appear as an option, you may need to log into the iPad and allow the iPad to "trust this computer." If this option is not available to you may also need to reboot the iPad.
}

I uploaded a video <a href="https://drive.google.com/file/d/0BxerAx_XXHB2MFE3RTk2WENkdnM/view?usp=sharing">here</a> of some of the sim testing, but it seems to run pretty smoothly. The only issue is that the screen resolution is capped at 1600x900.

As for camtasia, the link you posted is for putting up videos and pictures captured <i>by</i> the iPad as opposed to <i>of</i> the iPad, so it's not very useful for us.

**Comment by ariel-phet** [comment]
@amanda-phet can you put these descriptions/video in the appropriate place and then close the issue?

**Comment by amanda-phet** [comment]
I added it to the Interview Resources folder on Drive.
