### ISSUE TITLE
Accessibility (Draft) Icons

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#176]
I'd like Alex to draft up a consistent, and playful, set of accessibility icons. This would include icons for:
- keyboard navigation
- text to speech
- auditory descriptions
- sonification
- multiple languages

They don't need to be fancy, they just need a consistent aesthetic somewhat aligned with PhET's other icons, and a general playful look. Below are a few of the better ones that I found online, for inspiration.

Note: These are only drafts to be used in presentations/proposals, etc. No design committee needed. :)
Would be wonderful if I could have something to work with by Wednesday, Feb. 25th.

![screen shot 2015-02-16 at 7 54 30 am](https://cloud.githubusercontent.com/assets/5109055/6213851/3711b564-b5b1-11e4-8711-6b7bc1edba0d.png)

**Comment by samreid** [comment]
I think it would be helpful for you to describe the context where the icons will be used.

**Comment by emily-phet** [comment]
The icons will be used in grant proposals and presentations.

**Comment by amanda-phet** [comment]
@alexklinger we are thinking of using the fontawesome icon for translation on the website so maybe you can start there in terms of look and feel?

**Comment by amanda-phet** [comment]
@emily-phet Is it too late for these icons at this point? If not, we can have Alex prioritize this task. 

If it is too late, I would still like to keep this issue open because it will be extremely valuable down the road for indicating accessibility (eg., on sim pages).

**Comment by emily-phet** [comment]
It's never too late...for some things. :) Sure, keep 'em coming. There are always more grants, presentations, meetings, etc. The next upcoming deadline will probably be the ACS poster - timeline for that is in that github issue.

**Comment by alexklinger** [comment]
I think it would be more efficient to use http://thenounproject.com/ in this case. All of there icons can be used free with attribution to the designer. For $10 dollars per month, they can be used w/o attribution, and for about $2-3 dollars each you can purchase individual licenses for icons, which is probably cheaper than my hourly wage when you account for the time it would take for me to make these.

**Comment by amanda-phet** [comment]
@alexklinger Can you pick out some icons that you think would work?

**Comment by ariel-phet** [comment]
Just to chime in here...I do not really think cost is the issue. It is more important that they feel consistent with our look and feel and the PhET brand in general. It might be useful to find some icons that have the correct basic idea and work from there. Notice above that @emily-phet said:

a consistent aesthetic somewhat aligned with PhET's other icons, and a general playful look. 

I am thinking those are going to need to be custom in the long run. But again, finding some on the website you mention might be a good jumping off point.

**Comment by emily-phet** [comment]
My thoughts...I'd prefer to not have to worry about attribution (these will be used in a variety of materials, that will likely be reused in various ways for many months - or years - to come).

**Comment by alexklinger** [comment]
That whole point of buying a license is that you don't have to worry about attribution. Licenses vary from 2-4 dollars per icon on the noun project. These I made from scratch over about 3 hours. 
![accessibiltyiconsdraft](https://cloud.githubusercontent.com/assets/8651105/6676368/d73dfab0-cbec-11e4-8060-4b9500503b96.jpg)

**Comment by samreid** [comment]
> That whole point of buying a license is that you don't have to worry about attribution. Licenses vary from 2-4 dollars per icon on the noun project. 

Typically purchasing assets from a 3rd party still encumbers us with usage restrictions--for instance, one cannot typically relicense 3rd party assets, but we would be able to relicense artwork that we created ourselves.  In some cases we have used icons or artwork from 3rd parties that had a very open license such as MIT or SIL (fontawesome).  But I agree with @ariel-phet's point that it is also important that we can customize the artwork and tailor it to our needs.

**Comment by ariel-phet** [comment]
@alexklinger nice start. A couple of suggested tweaks:

1. On the speaker, round the cornders a bit (we tend to have a very soft look at PhET, not many sharp corners)

2. On both of the icons that have a human head, it looks quite male. Perhaps try to give it a more gender ambiguous look (see the html5 version of color vision for an example).

**Comment by ariel-phet** [comment]
I particularly like the text to speech one by the way!

**Comment by alexklinger** [comment]
https://thenounproject.zendesk.com/hc/en-us/articles/203639098-If-I-purchase-an-icon-do-I-own-it-forever- Since PhET does not sell anything the icons would be able to be used for an unlimited time frame and duplicated as much as needed. They come in SVG format and are easily manipulated in illustrator.

**Comment by ariel-phet** [comment]
@alexklinger we appreciate you showing us these other resources, but for this particular project we will stick with custom.

**Comment by alexklinger** [comment]
update wit rounded corners and more gender neutral look.
![accessibilty-icons](https://cloud.githubusercontent.com/assets/8651105/7015751/40eaf2ba-dc96-11e4-95d2-20632fb50ada.jpg)

**Comment by ariel-phet** [comment]
Hey @alexklinger - nice changes. Speaker looks good. I think I would suggest 1 main tweak to the "head" artwork.

Since these could appear fairly small, I think we need to reduce the detail slightly. I think you have captured a gender neutral look well, but we should look for places where detail can be reduced. For instance on the head with hair, I think we don't want that one separate bit of hair (since that detail will be lost at a smaller size). With the face, not sure if it can be changed, but you might see what they look at a small size and experiment a bit.

**Comment by mariahmaephet** [comment]
<img width="555" alt="screen shot 2015-09-29 at 2 38 38 pm" src="https://cloud.githubusercontent.com/assets/11527557/10177529/d45bf73c-66b7-11e5-96a8-2b6935a9614b.png">

**Comment by emily-phet** [comment]
I met with Dave Underwood to discuss these. He's planning to tweak some, and draft something new for others.

**Comment by emily-phet** [comment]
@ariel-phet - can we change the timeline on this? It would be great to have these ready to go in the next month or so. I'm going to start churning out new accessibility materials (e.g., more presentations, updating PhET's accessibility page, working with Jesse on developer material for general sharing) and it would be great to have these ready to add in to these materials.

**Comment by ariel-phet** [comment]
Sure, I imagine @daveunderwood will iterate quickly

**Comment by ariel-phet** [comment]
@emily-phet what is the status of this issue?

**Comment by emily-phet** [comment]
@ariel-phet - I don't think @daveunderwood finished iterating on these. I don't recall seeing any updated designs.

**Comment by ariel-phet** [comment]
@emily-phet here is the latest version, see what you think

![a11yicons](https://cloud.githubusercontent.com/assets/4051174/15786985/bdc8a758-297c-11e6-97cf-f17aeb8a9520.PNG)
[icons_june-2.pdf](https://github.com/phetsims/tasks/files/298076/icons_june-2.pdf)

**Comment by emily-phet** [comment]
I really like the auditory description, language, and text to speech icons. I think those are good to go. 

For the sound icon, I think we may need either two icons (one like what you have here, that indicates some sound component, and a second that indicates more sophisticated sounds), or a just a single sound icon that looks a little different from the typical, as it would be indicating that the only option is the more sophisticated sounds. I'm imagining something with wavy sound lines, to help get across there is dynamic sound, or sound mapped to sim parameters, rather than just bells or dings (which typically don't support accessibility).

For keyboard navigation, what about something more like this:
<img width="273" alt="screen shot 2016-06-07 at 11 23 27 am" src="https://cloud.githubusercontent.com/assets/5109055/15868028/1bf13eb6-2ca3-11e6-8837-131d8e1c646d.png">

**Comment by terracoda** [comment]
﻿﻿﻿Jon Hung shared this infusion icon during the design crit for keyboard dialog design. It could be worth considering as an alternative for the keyboard accessibility icon.

<img width="180" alt="kb-a11y-icon-infusion" src="https://user-images.githubusercontent.com/1902116/31900416-d531d5fc-b7f8-11e7-8d71-f4e22376a8b6.png">

**Comment by emily-phet** [comment]
Closing - @amanda-phet created some beautiful icons for a recent update to the a11y webpages.
