### ISSUE TITLE
Dev Testing for Molecules and Light 1.0.0-dev.5

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#177]
@orejolaphet, @phet-steele, @bryo5363 

Please dev test the latest version of Molecules and Light (http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.5/molecules-and-light_en.html) 

- [x] Windows + Chrome 
- [x] OS X + Safari 7.1+
- [x] iPad iOS 8 + Safari 

Please check than any previously reported issues have been addressed

**Comment by orejolaphet** [comment]
Testing on requested platforms have been completed. All previously reported bug related issues have been addressed. Closing.
