### ISSUE TITLE
coding guidelines don't mention 'Property' suffix convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#178]
The "PhET Development Overview" section of does not include the PhET convention of using 'Property' as the suffix of all names of type axon.Property. This should be explicitly specified in the coding guidelines, so that 3rd-party developers are aware of this. For example, see https://github.com/phetsims/sugar-and-salt-solutions/issues/8.

**Comment by ariel-phet** [comment]
@samreid can you add this info to the development overview?

**Comment by samreid** [comment]
I added this section to the style guidelines at https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w

> Naming for Property values:  All AXON/Property instances should be declared with the suffix `Property`.  For instance, if a visible property is added, it should have the name `visibleProperty` instead of simply `visible`.  This will guarantee consistency with Properties created by PropertySet, and help to avoid confusion with primitive (non-Property) values.

@pixelzoom want to take a look?

**Comment by pixelzoom** [comment]
Perfect, closing.
