### ISSUE TITLE
design README.md for common-code repos

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#180]
Related to https://github.com/phetsims/tasks/issues/159 (design README.md for sim repos).

For common-code repos:

1. What is the template for README.md?
2. When is the README.md generated?

**Comment by pixelzoom** [comment]
In #159...

@jonathanolson said:
> It probably depends a lot on the specific common-code repo.

So perhaps we don't have a template?...

@samreid said:
> Perhaps we should put together a working example for Joist (typical PhET repo) and for Scenery (custom PhET repo). Anyone feel free to start on this or let me know if I should do so.

**Comment by samreid** [comment]
> Anyone feel free to start on this or let me know if I should do so.

Amending my statement based on new information: I'm busy for the next week at least, so won't be able to start on this now.

**Comment by ariel-phet** [comment]
Seems like a good topic for dev meeting, I will put it on the agenda

**Comment by samreid** [comment]
We agreed Joist is already in pretty good shape:
https://github.com/phetsims/joist

Each other repo just needs its description.

**Comment by samreid** [comment]
@pixelzoom will start adding descriptions to some common repos.

**Comment by pixelzoom** [comment]
I updated the README.md for the common-code repos:

assert
axon
babel
chipper
dot
joist
kite
phet-core
phetcommon
scenery
scenery-phet
sherpa
sun

I did not do `arch` and `together` because they currently have lots of notes related to prototyping. 

I also did not do phetsims/brand and phetbrand/brand (private), because I'm not sure what we should say about these.

Other developers, feel free to revise descriptions. Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
I put this as an agenda item for Thursday March 12 developer meeting. Perhaps we can just fill out the descriptions at that time for the 4 remaining repos

**Comment by samreid** [comment]
I have updated the docs for arch + together.  Brand and its variants still need attention.

**Comment by ariel-phet** [comment]
Everything here now seems acceptable, closing
