### ISSUE TITLE
Test Least Squares Regression 1.0.0-rc.1

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#183]
Least Squares Regression 1.0.0-rc.1 is ready for release candidate testing:
http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-rc.1/

The test matrix: https://docs.google.com/spreadsheets/d/1fuKgDgWtNw0QjrkA08F4albsVDKlmdwjTjop5qszBi4/edit#gid=2

**Comment by bereaphysics** [comment]
Assigning to @ariel-phet

**Comment by ariel-phet** [comment]
@phet-steele @orejolaphet and @bryo5363 please make this sim your current top testing priority. Should be fairly straightforward testing. Thanks!

**Comment by phet-steele** [comment]
Testing matrix is completely filled out.

**Comment by ariel-phet** [comment]
Excellent, thanks!
