### ISSUE TITLE
Restore CafePress Pages with active merchandise

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#184]
Hey @oliver-phet - I believe awhile back you had @arnabp disable all of the active content from the cafepress store we had begun to set up.

Now that we have been given the go ahead to use CafePress by the university legal team it would be good to restore the ability to buy merchandise and see where we were at before advertising our storefront.

Feel free to reassign to @arnabp if he would be the best person.

**Comment by oliver-phet** [comment]
@arnabp Can you re-activate the PhET CafePress account?

**Comment by arnabp** [comment]
The website has been reactivated at http://www.cafepress.com/phetsims
I've also set it to private so you can only get to it with the link.

**Comment by ariel-phet** [comment]
Excellent, thanks!
