### ISSUE TITLE
design README.md for unpublished sim repos 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#185]
Splitting this issue out of #159.  What should the README.md look like for unpublished sim repos?

**Comment by pixelzoom** [comment]
My inclination is to keep the README for unpublished sims as simple as possible. Here's an example, with corresponding screenshot below: https://github.com/phetsims/function-builder.

@ariel-phet @samreid @jbphet please provide feedback. 

![screenshot_482](https://cloud.githubusercontent.com/assets/3046552/6566443/2e810574-c67f-11e4-9e08-32cdea51f9b5.png)

**Comment by pixelzoom** [comment]
README.md can be generated for an unpublished sim using `grunt generate-unpublished-README`. It currently uses a template that produces the format shown in the comment immediately above.

**Comment by ariel-phet** [comment]
That seems nice, simple, and to the point. I believe it also serves the purpose of making clear that this sim is not yet published. Feel free to just go with this solution.

**Comment by pixelzoom** [comment]
This solution is what is currently implemented for `grunt generate-unpublished-README`.
And all links now open in a separate tab/window.

**Comment by pixelzoom** [comment]
We reviewed this  3/10/15 developer meeting:

• Add “Documentation” section (same as published)

**Comment by pixelzoom** [comment]
All changes incorporated, see https://github.com/phetsims/function-builder for an example. Updating the README for all unpublished sims will be done in #187.

Closing.
