### ISSUE TITLE
Go in to PhET administration and delete all "Ratings"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#191]
There are a number of sims that have a "Rating" in the administrative side of the PhET website. These ratings produce a legend icon on the sim page (for example, http://phet.colorado.edu/en/simulation/beta-decay has an "under construction" logo in the top right corner of the sim page). 

We would like to delete all of these ratings from each sim that has one. If you log in to the PhET site as an administrator, click on simulations, then the sim, scroll down through all of the info until you get to the Ratings section
![screen shot 2015-03-13 at 9 55 08 am](https://cloud.githubusercontent.com/assets/7852916/6641990/0eb7105e-c967-11e4-85a9-85d0c9eeb3af.png)

uncheck the rating and save. 

The list of sims that have ratings are:

Under construction:

 molecule-shapes
 stern-gerlach
 rotation
 efield
 molecule-shapes-basics
 reversible-reactions
 calculus-grapher
 rutherford-scattering
 torque
 eating-and-exercise
 glaciers
 circuit-construction-kit-ac
 circuit-construction-kit-ac-virtual-lab
 capacitor-lab
 beta-decay
 atomic-interactions

Guidance recommended:

 stern-gerlach
 resonance
 reactions-and-rates
 reversible-reactions
 signal-circuit
 blackbody-spectrum
 conductivity
 motion-2d
 torque
 lunar-lander
 my-solar-system
 semiconductor
 normal-modes

Classroom tested:

 quantum-tunneling
 photoelectric
 radio-waves
 mass-spring-lab
 circuit-construction-kit-dc
 projectile-motion
 travoltage
 moving-man
 fourier
 sound
 circuit-construction-kit-dc-virtual-lab
 quantum-wave-interference

**Comment by ariel-phet** [comment]
Should be complete.
