### ISSUE TITLE
Collect performance data for Molecules and Light on iPad 3

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#192]
There is some work be done to improve the performance on the Molecules and Light simulation, and I could use some help collecting current performance data.  We need the average FPS rate on an iPad three for two different versions in four scenarios.  The two version are:
+ http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.8/molecules-and-light_en.html
+ an experimental version that removes the use of opacity in the sim specific code and in the radio buttons, link: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-exp-minimal-opacity/molecules-and-light_en.html

The four scenarios are:
+ Idle, just after being loaded
+ The initial startup configuration with the infrared emitter cranked all the way up (molecule is Carbon Monoxide).
+ Ultraviolet source turned all the way up with Nitrogen Dioxide as the target, pressing the "Return Molecule" button immediately after it appears.
+ Ultraviolet source with Nitrogen Dioxide as the target, molecule broken and off screen so that it is basically just a constant stream of photons being emitted with no interaction with any molecule.

In each case, please average the FPS value that is visible when the "?profiler" query parameter is used 
over the course of 1 minute.

For reference, this is in support of the following issues in the molecules-and-light repo:
https://github.com/phetsims/molecules-and-light/issues/91
https://github.com/phetsims/molecules-and-light/issues/93
https://github.com/phetsims/molecules-and-light/issues/98

I've discussed this with @phet-steele and he will start working on it, though I'll assign to @ariel-phet for now.

**Comment by ariel-phet** [comment]
@phet-steele - definitely make this your top priority for the moment

**Comment by phet-steele** [comment]
For model A1416 (iPad 3 Disessa) with iOS 8.1 and Safari 600.1.4, these are the numbers for 1.0.0-dev.8 taken over 60 seconds at 1 second intervals:

1. Idle: 59.933 fps
2. Infrared + CO: 29.517 fps
3. Pressing "Return Molecule": 24.333 fps
4. UV idle: 29.917 fps

**Comment by phet-steele** [comment]
For model A1416 (iPad 3 Disessa) with iOS 8.1 and Safari 600.1.4, these are the numbers for the experimental version taken over 60 seconds at 1 second intervals:

1. Idle: 59.95 fps
2. Infrared + CO:  30.883 fps
3. Pressing "Return Molecule": 25.267 fps
4. UV idle: 29.933 fps

**Comment by jbphet** [comment]
Thanks @phet-steele - this is all we need, at least for now.  Closing.
