### ISSUE TITLE
RC testing for Molecule Shapes 1.0.0-rc.2 & Molecule Shapes: Basics 1.0.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#193]
"Molecule Shapes" and "Molecule Shapes: Basics" are ready for their second release-candidate testing.

Release candidates:
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-rc.2/molecule-shapes_en.html (regular)
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.0.0-rc.2/molecule-shapes-basics_en.html ("Basics")

Test matrices:
https://docs.google.com/spreadsheets/d/1wfA1SVvOKK-d26ozNNeGDuuq5OtUpInGcEkfK_Eqvgg/edit (regular)
https://docs.google.com/spreadsheets/d/1pfJglrdMScIyruOXQilQiNse91tGhafQKLouOJISSMY/edit ("Basics")

If an issue is present in both simulations, please just make an issue for the main sim (https://github.com/phetsims/molecule-shapes/issues). Canvas performance (boxy appearance and warning displayed on sim launch) is likely to be less than ideal on tablets (see https://github.com/phetsims/molecule-shapes/issues/102).

**Comment by ariel-phet** [comment]
@oliver-phet @bryo5363 @phet-steele @arnabp please make this sim your top testing priority. I believe @jonathanolson has addressed all issues from RC1, so it should be pretty smooth sailing.

**Comment by arouinfar** [comment]
The testing matrix for Molecule Shapes: Basics is complete.

**Comment by ariel-phet** [comment]
All testing finished...closing this issue
