### ISSUE TITLE
Determine which activities apply to HTML5 sims

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#194]
Based on the concerns you brought up in our meeting this morning, I think you would be the perfect person to start the project of going through all of the activities. Do you have time/interest in this project? 

Perhaps just start with the gold-star activities, and for sims *that have an HTML5 version*, determine which activities 
* were written for the HTML5 version
* could work for the HTML5 version
* only apply to the legacy version

@ycarpenterphet started something like this for a single sim. Can you share your google spreadsheet with us and walk us through the process if necessary? I think it would be nice to follow the format you started. 

Eventually, we want to send a bulk email to the authors of activities that are not relevant to the HTML5 version and give them an opportunity to revise them.

**Comment by patricialoeblein** [comment]
I was going to attach  my spreadsheet of activity english language authors for viewing and discussion, but that doesn't appear to be a feature of GitHub, so I made a google spreadsheet. https://docs.google.com/spreadsheets/d/14HGPf2XI3VnlN4HyX38PAzSxykatSkp0y8p4YyGpa-k/edit#gid=312862783   The purpose of this spreadsheet has varied, so there are many blank spaces. I have made a few notes in the first row about why not all rows are filled. If we chose to use this spreadsheet,  I  feel like it would be helpful to make a row for each sim for which an activity was written and perhaps include the activity numbers if they are not going to change . I can work using this spreadsheet to identify activities that might fit the html5 sims. If this seems like a good enough starting place, I will continue to fill in this sheet offline and upload an updated one. I do not like to work on Google spreadsheets for many reasons.

**Comment by amanda-phet** [comment]
@patricialoeblein I shared a google doc with you (Alignment of activities w/ HTML5 sims) that will have a tab for each sim and within that tab will have each activity listed with notes. I think we'll need to look at each activity individually, not just each author, and it is probably best organized by sim. Take a look at it and let me know if it looks like something you can use.

**Comment by patricialoeblein** [comment]
I can see that the old spread sheet I have will not be useful for this project and I  deleted it, but I wonder if that deletes it for everyone.

However, I think the “Alignment of activities w Html5”  will be too difficult to use with the comments, ratings, and graphic evaluations. I had imagined that we would just quickly look at the activity and approve it for html5 or not. Then I thought we were going to email the authors of all activities for which an html5 sim has been published and ask them to verify or update their activity. I am not comfortable with making changes to an activity without the author’s approval, nor do I think we have time to re-write other peoples’ activities. I do like the idea of attending to the Gold star ones first. I would be ok with adding the html5 compatibility if the sim has had so few changes that the activity is applicable.  I think we need to discuss what to do if the author does not respond. We do have the problem that the authors did not agree to the Open Source licensing. Personally, I would not bother with the “not Gold stars”.

I do think it would be helpful  if an UG filled in the templates for the html5 sims with the Title Author level type last updated Gold Star PhET. I would add contact info for author and activity link. I also think a detailed description at the top of the sim sheet could have some information along the lines that you are hoping in terms of content and graphics. I would recommend that we have something about how well the scenes match the tabs, amount of changes in graphics with some details, comparison of content. Then anyone who is evaluating the activities would have a rubric.

After writing all this, I wonder if we could try to put up the new pages, use our social media to advertise that we have pages and ask for activity contributions. After a reasonable amount of time, we could look to see if each sim has a few Gold Stars and then attack the problem. I did this at one time by identifying sims that needed Gold stars, then I wrote some of my own and gave credit to the orginal authors if I needed. I do feel strongly that we have a great community and should ask for their help before we try to do their work for them.

Respectfully,

Trish

**Comment by amanda-phet** [comment]
I agree that we should not change anyone's activities. The legend in the document will help us with how to reach out to teachers- perhaps there are two different mass emails, one for activities that only require slight changes, and one for activities that need more revamping. I think that's a great idea to reach out via social media asking for people to upload their activities! 

I think this shared document *can* be used to quickly evaluate whether or not an activity is HTML5 compatible. The difficult thing is, when you start looking at activities, there is a lot of gray area on terms of compatibility, so the comments can be helpful for when that happens. I don't think you need to be as thorough as @ycarpenterphet was with RPAL. However any record we have of this information will be really useful.

**Comment by patricialoeblein** [comment]
I believe that engaging the authors and users of PhET will pay off in the long run because the ownership of the activities and gold stars is valued by many authors.

Here’s my vote:


1.       I think those of  PhET team members that have activities for sims that are now available in html5 could update ours.

2.       Ask for activities and see what happens before we spend evaluation energy.

3.       An UG could identify Gold star ones for which html5 sims have been published and send them a “personalized” letter that is developed from a template.  I would be happy to use my name in the signature since I wrote each gold star author when I gave them the star. We would want to keep track of the results as a metric.

In addition to these steps, we might want to consider if other PhET team members want to read the activities and give Gold stars or if I should continue the past process. I believe writing an evaluation rubric for Gold Stars might be more valuable than spending time evaluating the differences between sims and also identifying if old activities are applicable.


Trish

**Comment by amanda-phet** [comment]
@patricialoeblein, Just to clarify, We are all planning to participate in this process of looking at gold-star activities and determining if they can be included with the HTML5 sim, but it seemed like something you'd want to get started on. 

Any activities for which we could not make a determination will prompt an email asking the author(s) to update it if they wish for it to show up on the HTML5 sim page. 

Would you like to get started on this? If so, can I make the spreadsheet more accommodating? If not, our plan is to carve out some time in the next few weeks and just sit down and go through them.

**Comment by patricialoeblein** [comment]
Last time I responded, I said I would prefer to contact the authors of gold stars for the sims similar to the html5 ones. Also, send out a wide call for activities which we would review as they come in. Only after that do I think we should try to re-identify activities and only if there are not a gold one for a sim. Did I miss a discussion?

Trish

**Comment by patricialoeblein** [comment]
Amanda and I made a spreadsheet to keep track of progress. https://docs.google.com/spreadsheets/d/1ZYUl9GLmgc4KV0ioXT2FKaKkYLm33_C8VR4SorrXVbQ/edit#gid=0  . Steele will use the published date to help identify phet activities that could be updated with the contact information. I will email the person and ask if they can update the activity with the exception of me. I will put updating mine into my workflow. 

example email:
Yuen-ying, I am identifying gold star activities that are suitable for the html5 version. This activity, http://phet.colorado.edu/en/contributions/view/3966,  has a link to the old sim, so I am wondering if the activity would align with the html5 version. Please tell me if I can include it as a Concentration html5 resource. Thanks, Trish

**Comment by amanda-phet** [comment]
This is done! Closing.
