### ISSUE TITLE
Create a youtube video about how to run a sim on a mac 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#195]
https://phet-dev.colorado.edu/en/troubleshooting/mac#q5-header

Can you make a video with the steps above and some voice over with instructions. We heard at a recent conference that Mac users are running into trouble and think a video might be better.

**Comment by arnabp** [comment]
Here's a draft of the video: https://youtu.be/n1AKnZJBzdw
Assuming everything looks good, I just need the intro and outro we add to all of our videos

**Comment by oliver-phet** [comment]
@schasteen Can you send the intro/outro that we use in regular videos to me?

**Comment by arouinfar** [comment]
Nice work @arnabp. I like the script, but it seems like the narration and actions could be better synced.  For example, you open the file manually around 20s in, but around the 23s mark you talk about finding the Java file in finder and right clicking to open the file. This happens again around 40s when you talk about manually overriding the security settings, but then actually show how to do it around the 45s mark.

The volume could also be boosted a little bit. The audio seemed a bit quiet when listening to the video through earbuds, even with both YouTube's and my computer's volume maxed out.

**Comment by schasteen** [comment]
I assume you want just a .mov or .mp4 of the PhET "swoosh" and credits screens?  Not modifiable?  Or did you want our Premiere files in which the text, title, etc., is modifiable?

**Comment by schasteen** [comment]
Also, the ending screen will likely be changed soon, but I assume you want the current one; it will be perhaps a month before we finalize the new ending screen.

**Comment by oliver-phet** [comment]
I think just the video file is fine for now .mov might be easiest for us.

**Comment by oliver-phet** [comment]
@arnabp Can sync the video/speech as @arouinfar suggested? I have the intro clip and ending slides to add to the clip too.

**Comment by arnabp** [comment]
<a href="https://drive.google.com/file/d/0BxerAx_XXHB2cW9JZUtwVzBTSWc/view?usp=sharing">Here</a> is the finished video. Did you want me to upload it to one of the Youtube channels? Phet Sims or Phet Sims: Tech Info?

**Comment by arouinfar** [comment]
Great job with the syncing, @arnabp!

**Comment by oliver-phet** [comment]
@arnabp and I were discussing the length of the intro (I thought it seemed too long for this type of troubleshooting video). Thoughts from others?

**Comment by arouinfar** [comment]
@oliver-phet, are you talking about the stock PhET intro? I didn't find the intro to be unreasonably long when I first watched the video. It wasn't until after reading your comment that I noticed that it takes up a rather sizable percentage of the total running time.  For branding purposes I think we should keep our intros consistent. Though if we have plans to make several "quick tip" videos, it may be useful to have a shorter version of the intro.

**Comment by oliver-phet** [comment]
Yes, the stock intro. It is ~9 seconds and seems unnecessary for a troubleshooting video like this. I'm assuming the plan is to embed videos like this in the troubleshooting page, so imo they don't need to be branded like other videos and could either have a shorter intro or no intro.

**Comment by arouinfar** [comment]
If the only access point to the video will be through the troubleshooting page, then I agree that branding is not as important. If we plan on making more troubleshooting videos, then a short intro may be worth creating.  Otherwise, I'd be fine with removing the intro.

**Comment by schasteen** [comment]
I personally think the intro adds a nice polish and consistency to the video, and isn't too long.   But as Amy says, if this is part of a series, then the intro is more important.  I also think you can move off the intro screen more quickly.  It's pretty much done at 07:00 but we don't hear a narrator until 0:11.  I think that lag is the reason it feels slow.  You could start the narration slightly over the intro screen, then move into the screencast, but this could require a little more finessing.

For the ending screens, I should have specified; the social media links come first, and then the "donate" page, so that when the video stops playing, the viewer sees the "donate" screen.

Note too that we just got our high quality microphone set, which would be good to use for future screencast recordings.  Might eliminate some of that loud fan noise.

Stephanie

**Comment by arnabp** [comment]
The background noise was from the AC in Oliver's room, which is too loud and spreads through the room too much for the new mic not to pick up (which I used for this). 

Here's <a href="https://drive.google.com/file/d/0BxerAx_XXHB2T0JETmZHV216UEk/view?usp=sharing">a new version</a> where I reduced the length of the intro, used a simple background noise reducer, boosted the audio a bit, and switched the ending screens. How does it look now?

**Comment by arouinfar** [comment]
The audio quality has definitely improved. I don't hear the background noise unless I turn the volume up quite high. 

The "Mac Sim Troubleshooting" title and subtitle appear on screen for too little time to actually be read. Perhaps we should remove the "Bypassing Gatekeeper for Java Simulations" subtitle to facilitate quicker reading.

**Comment by schasteen** [comment]
I agree that the background noise is better.  If the title screen stays on there about another 1 second, and the title text doesn't fade out before the screen changes, that would probably help readability.

**Comment by arnabp** [comment]
Here's <a href="https://drive.google.com/file/d/0BxerAx_XXHB2M1ByQ2pVTXJNcnc/view?usp=sharing">another version</a> where I've boosted the slightly reduced the audio a bit, extended the intro a bit, and I had the test fade at the same time as the rest of the intro.

**Comment by arouinfar** [comment]
Looks good to me! Nice work, @arnabp.

**Comment by ariel-phet** [comment]
I think this video looks great, really clear narration as well!
