### ISSUE TITLE
Gas Pump for States of Matter

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#196]
We need a bike pump drawn in 2D for the HTML5 version of States of Matter. This pump will also be used in the upcoming redesign of Gas Properties.  

The current version looks like:
![image](https://cloud.githubusercontent.com/assets/8419308/6699483/1ef11924-ccc8-11e4-85dc-482a9c8a5c1e.png)

It's important to make sure the handle maintains its "grippy" look. The base will need some redesign. Can you paste in the pump you made for your design task, @alexklinger? We can start from there.

This would be good to start on once you've finished the ACS poster.

**Comment by alexklinger** [comment]
here is the one I made for the design task
![bikepumpphet](https://cloud.githubusercontent.com/assets/8651105/7015742/f36e4eb0-dc95-11e4-98d3-2ffaf316ebb4.jpg)

**Comment by arouinfar** [comment]
Hey @alexklinger, I'd let to set a time with you to discuss what needs to be done with the pump. I've sent you an email to schedule the meeting.

**Comment by arouinfar** [comment]
Just to summarize some of what @alexklinger and I discussed this morning -- 

Let's start with the making the handle more grabbable and interactive. One way to do this would be to create a "grippy" look similar to the current version of the pump. @alexklinger can also play with other ways of cueing interactivity. The perspective will also need to become flatter, but let's focus on the handle first.

**Comment by alexklinger** [comment]
@arouinfar 
![bikepumpphet2](https://cloud.githubusercontent.com/assets/8651105/7128242/a3bf4140-e20c-11e4-81f9-31a64ac1c149.jpg)

**Comment by arouinfar** [comment]
I really like the handle, @alexklinger! I'd like to see how it looks in the mockup. Can you put the .ai file in your Drive folder?

**Comment by alexklinger** [comment]
@arouinfar Just uploaded it.

**Comment by arouinfar** [comment]
Thanks, @alexklinger!

**Comment by arouinfar** [comment]
New pump has been implemented in States of Matter. Closing.
