### ISSUE TITLE
Solid, liquid, gas icons for States of Matter

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#197]
I need icons depicting a solid, liquid, and gas drawn for States of Matter. 

Currently the artwork looks like:
![image](https://cloud.githubusercontent.com/assets/8419308/6715891/484a5840-cd67-11e4-9f8e-6570120e8a51.png)

Ideally, these icons would look like a (non-cartoonish) ice block, water droplet, and gas cloud. These icons should also be drawn in 2D.

Once your PhET gmail account has been set up, I will share the original .ai files with you on Google Drive.

**Comment by mariahmaephet** [comment]
I'm not too crazy about the gas one still, but what do you think about the others?

![screen shot 2015-03-24 at 2 38 06 pm](https://cloud.githubusercontent.com/assets/11527557/6812289/8dced05a-d233-11e4-8e93-54e158b1ec01.png)
![screen shot 2015-03-24 at 2 38 29 pm](https://cloud.githubusercontent.com/assets/11527557/6812290/8dd11478-d233-11e4-9b24-bbce9768eed9.png)

**Comment by ariel-phet** [comment]
Hey @mariahmaephet, I will let @arouinfar comment, but a good workflow tip is to reassign the issue to the person you wish to have comment. (I have reassigned this issue to @arouinfar)

**Comment by arouinfar** [comment]
I really like the solid and liquid icons, @mariahmaephet! Since these will end up on a black background, the solid icon with the blue outline will probably work better. 

I agree that the gas could still use a little work. I think part of the problem is that the clouds look a bit too separated from one another, giving them a somewhat "solid" appearance. Let's instead try a single cloud.

I'm envisioning something like this cloud, which has a similar style to the icons you've drawn.
![image](https://cloud.githubusercontent.com/assets/8419308/6813900/35da20f0-d23f-11e4-9cc7-8d06f7064261.png)

Reassigning to @mariahmaephet.

**Comment by mariahmaephet** [comment]
![screen shot 2015-03-31 at 5 22 42 pm](https://cloud.githubusercontent.com/assets/11527557/6931456/a5ea9eca-d7ca-11e4-959e-a73f98436442.png)

@arouinfar

**Comment by arouinfar** [comment]
Great work, @mariahmaephet! Can you please put the .ai file(s) into your Google Drive folder? I would like to put them into the mockup to see how they look.

**Comment by arouinfar** [comment]
Self-assigning to implement new icons in the mockup.

**Comment by arouinfar** [comment]
Icons implemented, closing.
