### ISSUE TITLE
Robotic arm for Hooke's Law

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#198]
I will need a robotic arm drawn for Hooke's Law. @mariahmaephet, let's meet in person to discuss the task in more detail and brainstorm/sketch some ideas. When are you available to meet?

**Comment by mariahmaephet** [comment]
@arouinfar  I can meet tomorrow (Thursday) after 3 or any time on Friday. I'll be around for Spring Break if you're willing to meet then.

**Comment by ariel-phet** [comment]
@mariahmaephet and @arouinfar - actually a slightly higher priority has come up and it would be great if you could meet today at 3:00 pm to work on https://github.com/phetsims/tasks/issues/173

@amanda-phet will be emailing with details and to introduce you to @emily-phet

**Comment by mariahmaephet** [comment]
![screen shot 2015-03-31 at 5 54 36 pm](https://cloud.githubusercontent.com/assets/11527557/6931916/2ee2a10a-d7d0-11e4-8c49-f3b3c211b7cd.png)
![screen shot 2015-03-31 at 5 59 16 pm](https://cloud.githubusercontent.com/assets/11527557/6931917/2ee5e770-d7d0-11e4-8c94-3205c70bc309.png)

@arouinfar what do you think about these?

**Comment by arouinfar** [comment]
It's looking good, @mariahmaephet. I prefer the second design, but it will need a little adjusting. The hook looks a bit too sharp. Can you give it a more rounded/blunted end? This artwork isn't pressing, so please focus your attention on #206.

In the meantime, can you please send me the file for the 2nd arm? We will be discussing this sim during tomorrow's design meeting, and I'd like to insert the artwork as a placeholder.

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-03 at 10 49 10 am](https://cloud.githubusercontent.com/assets/11527557/6985292/13295280-d9ef-11e4-8e1c-3c91a00a4f17.png)
@arouinfar

**Comment by samreid** [comment]
The source of light within a sim is from the top-left.  For instance, if you run Concentration, you will see the highlighting on the top left of the reset all button (and Hooke's Law will also feature this reset all button):
https://phet.colorado.edu/sims/html/concentration/latest/concentration_en.html

Some of our sims are a bit of a "lighting direction" jumble at the moment, but it is one small touch that would be nice to keep consistent as we move forward, if it is not that much extra work while the artwork is being created.

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-03 at 11 18 22 am](https://cloud.githubusercontent.com/assets/11527557/6985684/40056c72-d9f3-11e4-9e3b-bd7b86bea4f9.png)
@samreid more like that?

**Comment by samreid** [comment]
Yes, thanks!  That will look more consistent with the reset all button (not sure what other graphics appear in Hooke's Law).

**Comment by arouinfar** [comment]
Thanks for your input @samreid. The arm looks great @mariahmaephet! Can you please update the .ai file in Drive?

**Comment by mariahmaephet** [comment]
@arouinfar just updated it

**Comment by arouinfar** [comment]
Hey @mariahmaephet, there are a few tweaks that we'd like to make to the hook, but it's probably easiest to discuss them in person. There's also another piece of artwork we'll need for Hooke's Law that we can discuss during our meeting. I'll send you an email to schedule a time.

**Comment by arouinfar** [comment]
@mariahmaephet will be working on the hinged look we discussed this afternoon. Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@mariahmaephet - this would be a good priority after the CHI poster since this sim is moving along quickly.

**Comment by mariahmaephet** [comment]
@arouinfar 

![screen shot 2015-04-24 at 10 56 22 am](https://cloud.githubusercontent.com/assets/11527557/7324147/e5fbd3a4-ea70-11e4-9e93-879ce1a72935.png)
![screen shot 2015-04-24 at 10 58 04 am](https://cloud.githubusercontent.com/assets/11527557/7324148/e5fe0700-ea70-11e4-84a1-32f8ef4a67f4.png)

**Comment by arouinfar** [comment]
Thanks, @mariahmaephet -- it looks great! Can you please put the .ai file into your Drive folder? Closing.

**Comment by pixelzoom** [comment]
@arouinfar Please send me the .ai, so I can check it into GitHub and integrate it into the sim.

**Comment by arouinfar** [comment]
The asset files have been sent to @pixelzoom.

**Comment by arouinfar** [comment]
I'm reopening this issue because there have been some concerns with the design of the hook (most notably that a hook is unlikely to be used to push). We would like to try a hooked pincer that could grab the end of the spring. The pincer could still have a similar artistic style to the hook that @mariahmaephet has already created. There should be two versions of the pincer, open and closed.

Here is an example of a pincher:
![image](https://cloud.githubusercontent.com/assets/8419308/7819349/5f352a18-039e-11e5-8d58-929ba3e85302.png)

Assigning to @amanda-phet for prioritization.

**Comment by pixelzoom** [comment]
There was some discussion about this at 5/28/15 design meeting that I don't see captured here. Was the consensus that the about pincer was a good direction? Or something else?

**Comment by ariel-phet** [comment]
@arouinfar - can you address @pixelzoom comment above and then reassign to @mariahmaephet

**Comment by arouinfar** [comment]
@pixelzoom, we decided to move forward with designing the pincer since it can be used to push and pull. The plan is to implement a wireframe pincer in the code (as shown below), but go through a few design iterations before implementing anything more complicated.
![image](https://cloud.githubusercontent.com/assets/8419308/7925639/abc93f78-0884-11e5-811c-d280e2cc1b3e.png)

@mariahmaephet, we would like to move forward with the pincer, somewhat similar to what is sketched above. I like the style of the original hook, but its visual weight could be reduced some when redesigning the hook as a pincer.

**Comment by mariahmaephet** [comment]
@arouinfar so something like this? Did you want the arm thinned out? 

![screen shot 2015-06-02 at 4 01 53 pm](https://cloud.githubusercontent.com/assets/11527557/7949228/bf6c7ca4-0940-11e5-9153-90a18ad1e205.png)
![screen shot 2015-06-02 at 4 02 01 pm](https://cloud.githubusercontent.com/assets/11527557/7949227/bf6c6070-0940-11e5-8fa2-4e1d9629e5aa.png)

**Comment by arouinfar** [comment]
That's a good start, @mariahmaephet. Let's pause on this issue for now, and wait to see how the team responds to the wireframe pincer implementation. We can discuss how to modify the pincer when the time comes. 

Self-assigning this issue for now.
