### ISSUE TITLE
Test Least Squares Regression 1.0.0-rc.2

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#199]
Least Squares Regression 1.0.0-rc.2 is ready for release candidate testing:
http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-rc.2/

The test matrix: https://docs.google.com/spreadsheets/d/1fuKgDgWtNw0QjrkA08F4albsVDKlmdwjTjop5qszBi4/edit#gid=2

For your information the changes from rc1 to rc2 were pretty invasive.

**Comment by ariel-phet** [comment]
@phet-steele @bryo5363 @orejolaphet @arnabp 

Please make this a high testing priority (can be done concurrently with with molecule shapes, although molecule shapes is a slightly higher priority)

**Comment by bereaphysics** [comment]
The issues raised on this RC were addressed and a new RC was released.
