### ISSUE TITLE
Chrome Beta sim testing for sims on our website

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#2]
We should test for bugs like https://github.com/phetsims/scenery/issues/224, which should immediately be apparent.

Can someone run through Beer's Law Lab and a few other sims to see if this occurs? Please first make sure the Beta is as up-to-date as possible.

It would also be nice to schedule this as a once-a-month quick test, so we don't get caught by breaking changes in the non-beta version.

**Comment by ariel-phet** [comment]
This issue seems stale and outdated, closing
