### ISSUE TITLE
Test Molecules and Light v1.0.0-dev.10

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#200]
We're getting very close to rolling a release candidate for this sim, but have decided to do one more round of dev testing since there have been a number of changes since the last round.  Be sure to not duplicate any of the currently existing tickets on this one.

Here's a link: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.0.0-dev.10/molecules-and-light_en.html.

**Comment by pixelzoom** [comment]
I did a quick test and found a couple of serious problems: 
https://github.com/phetsims/molecules-and-light/issues/107
https://github.com/phetsims/molecules-and-light/issues/106

**Comment by ariel-phet** [comment]
Issues addressed and bumped to RC
