### ISSUE TITLE
Investigate bad video playback on front page after open for a while

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#201]
@orejolaphet @bryo5363 @phet-steele Can you guys poke around a bit on the front page and see if you seen any sort of performance/choppy/frozen video? Kathy had the front page open for ~5 minutes and noticed that almost every other video would freeze or play choppy. She had her system monitor on and CPU usage was ~30%.
She was using Win 7 and Chrome.

**Comment by orejolaphet** [comment]
@oliver-phet I'll check around on Win 7 Chrome and OSX 10.9.4 Chrome.

**Comment by orejolaphet** [comment]
On Bates, the computer in Ariel's office Win 7 64-bit Chrome 41.0.2272.101 m, I left the home screen up for about 2 hours and noticed no issues. Likewise for my Mac OSX 10.9.4 Chrome 41.0.2272.76 (64-bit). I'll keep poking around, and check on other devices.

**Comment by ariel-phet** [comment]
Switching to low priority since it is looking like something quirky was going on with Kathy's computer, and not a general issue

**Comment by ariel-phet** [comment]
Nobody else seems to have reported this issue...I never saw anything while working at the recent conference. Closing
