### ISSUE TITLE
Facebook post about Martin

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#202]
Hey @arouinfar - you and I should develop a list of "interview" question for Martin

**Comment by ariel-phet** [comment]
This never really happened...but Martin will be back this summer (remotely). Maybe we can do it more properly then. Closing

**Comment by arouinfar** [comment]
@ariel-phet Sounds good. I have quite a few notes from my interview with Martin. I had left this issue open because I thought it might be nice to write something up to coincide with the release of Charges & Fields, but we can definitely revisit this issue this summer.

**Comment by ariel-phet** [comment]
Ah, the charges and fields release might work out well. Lets revisit when we get there (or summer!)
