### ISSUE TITLE
Rename screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#203]
The screenshots from #132 need to be slightly renamed to match the convention we've been using on GitHub. 

1. Rather than SimName-screenshot they should be sim-name-screenshot (eg., AlphaDecay-screenshot.png will be alpha-decay-screenshot.png) 
2. Any &s in sim names should be renamed as -and- (eg., Eating&Exercise-screenshot.png will be eating-and-exercise-screenshot.png) since &s are likely to be problematic. 

@orejolaphet will be working tomorrow (3/26) and Friday and said he could find time for it. Assigning to @ariel-phet for prioritization and clarification of task if needed.

**Comment by ariel-phet** [comment]
@amanda-phet - can you also take care of the couple of missing ones that will need to be "fudged" (like lasers)

Ideally all screenshots should be 2048x1344 (this was recently decided by the devs)

**Comment by orejolaphet** [comment]
The sims have been all renamed with the appropriate nomenclature,
https://drive.google.com/folderview?id=0B1dDzrtWHaLbfm1ZamxuRVB1bDhMWFRuZWF2ejlEMmh1WjhCcTFLOEVSVFRWVU1MN05FRzA&usp=sharing

**Comment by aaronsamuel137** [comment]
The names that should be used are the ones listed when you log in as an admin and click on the "Simulations" link. The legacy sims (unfortunately) do not follow the same conventions as the java sims. To find the right name, look in the "flavor" column of the simulation table.

I have already changed the names for the screenshots that have been uploaded already on my local machine - but this is good to keep in mind when uploading the missing screenshots.

Also, if it's not too hard we should probably change all wrong names in the drive too if this is where we plan on keeping a back up of all of these images.

**Comment by ariel-phet** [comment]
@elisemorgan this is an issue that has been lingering for quite some time, and I think you would be a good person to polish it off.

Please talk to @amanda-phet if you need details.

**Comment by ariel-phet** [comment]
@elisemorgan pinging on this issue

**Comment by elisemorgan** [comment]
Thanks for the ping @ariel-phet this task has been completed. https://drive.google.com/file/d/0B_TAL-jnJOoKVXlGRWxvOTZ2UUk/view?usp=sharing

**Comment by ariel-phet** [comment]
:smiley_cat: awesome!
