### ISSUE TITLE
Least Squares Regression 1.0.0-rc.3 is ready for release candidate testing:

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#204]
Least Squares Regression 1.0.0-rc.3 is ready for release candidate testing:
http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-rc.3

The test matrix: https://docs.google.com/spreadsheets/d/1fuKgDgWtNw0QjrkA08F4albsVDKlmdwjTjop5qszBi4/edit#gid=2

They were a few bug fixes for this release candidates. The most notable changes were done on the behavior of points in the bucket. They were no fix for any performance issues so it is not worth testing performance. If you could see that it behaves well on one platform  and that I didn't introduce any new bugs in my fixing process that would do it.

**Comment by ariel-phet** [comment]
Sim is published, closing
