### ISSUE TITLE
branch hygiene

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#205]
branches are getting a little out of hand.  We expect to have "master", release branches ("1.0"), and "gh-pages" (for github.io).  But there are many others, with no easy way to determine who created them, what they are used for, or when/whether they should be deleted.  For example...

Number of branches (including 'master') for common-code repos:

```
3 assert
5 axon
2 brand
9 chipper
9 dot
9 kite 
5 phet-core
4 phetcommon
2 nitroglycerin
10 scenery
7 scenery-phet
2 sherpa
3 together
2 vegas
1 vibe
```

A few sims:

```
5 build-an-atom
6 color-vision
10 forces-and-motion-basics
7 molecule-shapes
```

Recommended to clean this up.  And perhaps we should start logging an issue each time we create a (non release) branch, including the branch name, it's purpose, and when/whether it's intended to be deleted.  

I'll add this to the "dev meeting" agenda.

**Comment by pixelzoom** [comment]
We should also discuss which repos need a 'gh-pages' branch, and what the process is for maintaining that branch so that github.io is a useful resource.

**Comment by jonathanolson** [comment]
I've cleaned up the branches I've created (most notably the mutable-bits ones).

**Comment by pixelzoom** [comment]
At 3/31/15 dev meeting, we decided to create an issue each time we create a (non release) branch, including the branch name, it's purpose, and when/whether it's intended to be deleted. Issue title should be "branch: <name>".  No need to create such an issue for 'gh-pages' branches.

**Comment by pixelzoom** [comment]
@jonathanolson thanks for cleaning up.  I still see some branches in scenery/dot/kit that don't have a "branch" issue (see below).  Were these created by someone else?

scenery: ocad-day-1, ocad-day-2, pixi.js
dot: bounds2-vector-components
kite: pixi.js

**Comment by pixelzoom** [comment]
I've created issues for all branches that are unaccounted for, except those mentioned immediate above for scenery/dot/kite.  Feel free to describe or delete the branches at your leisure.

These common-code repos (see below) have branches with version numbers, which I think can be safely deleted. @jonathanolson @samreid @jbphet any objections? 

axon: 1.0, 1.1
chipper: 1.0, 1.1
phet-core: 1.0

**Comment by pixelzoom** [comment]
I created issues for the scenery/dot/kite branches, i.e.:

scenery: ocad-day-1, ocad-day-2, pixi.js
dot: bounds2-vector-components
kite: pixi.js

**Comment by pixelzoom** [comment]
Deleted these branches:

axon: 1.0, 1.1
chipper: 1.0, 1.1
phet-core: 1.0

**Comment by pixelzoom** [comment]
Done, closing.
