### ISSUE TITLE
Conference poster

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#206]
We'd like to make a new conference poster based on a design that's already been started. We have an image file (uploaded to your drive folder) that needs to be made into an illustrator file, with some changes. 
* make the logo bigger 
* change the slogan to "Shouldn't the best educational tools be FREE?" 

For now, just use some stock photos of students and eventually I'll give you some of our photos that we have permission to use. 

The size of the artboard should be 96"x36".

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-01 at 9 21 42 pm](https://cloud.githubusercontent.com/assets/11527557/6957125/2608cf24-d8b5-11e4-9eff-d5a0f1bdd2a8.png)

@amanda-phet Does this look good? What does the text on the bottom right say?

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-01 at 9 30 25 pm](https://cloud.githubusercontent.com/assets/11527557/6957194/5da235f0-d8b6-11e4-8ffc-286ce09d70ca.png)

**Comment by ariel-phet** [comment]
Hey, @mariahmaephet - nice start! It might be good to hash out the rest of the polishing in person. It looks like you might have some time on Friday...is there a good time for you to meet up?

A couple of requested tweaks:
1. I think it would be best if the "shouldn't the best..." question fit on two lines (it seems a bit odd to read on 3 lines) Feel free to choose a different font or play around to see what works. And perhaps we change the word "tools" to "resources" so perhaps "resources be FREE?" would be the second line.
2. We had talked about maybe putting the "FREE" in yellow, might be good to see how it looks
3. Ideally the yellow of the FREE, the underline, and the PhET "h" would all match
4. We should use the "full" PhET logo (with the Interactive Simulations line underneath) - I believe you have access to a copy.

**Comment by mariahmaephet** [comment]
@ariel-phet I apologize for not responding sooner--my computer charger is hiding from me. I'll try to borrow one tomorrow. I can meet any time, so let me know what works for you. If it's after 11am I should be able to get a charger and make those edits by then.

**Comment by ariel-phet** [comment]
Hey @mariahmaephet - how about we meet at 1 pm in @amanda-phet 's office

**Comment by mariahmaephet** [comment]
@ariel-phet 1pm works! See you then

**Comment by mariahmaephet** [comment]
@ariel-phet 
![screen shot 2015-04-03 at 10 45 36 am](https://cloud.githubusercontent.com/assets/11527557/6985274/dccfabda-d9ee-11e4-818c-9960807c8f9e.png)

**Comment by ariel-phet** [comment]
@mariahmaephet - can you put the finalized version in the phet .ai files google drive in the booth materials folder, and then reassign this issue to me to verify and close?

**Comment by ariel-phet** [comment]
Hey @mariahmaephet - I do not see the poster in the folder I mentioned above. It looks like you did not have edit permissions on that folder (which you now have).

**Comment by ariel-phet** [comment]
@mariahmaephet - also for clarity, when you upload the file please name it with the date (2015_04_04_phet-booth-banner)

**Comment by ariel-phet** [comment]
Looking great! Closing.
