### ISSUE TITLE
Test Molecules and Light Release Candidate 1.0.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#207]
Molecules and Light has a release candidate that is ready to be tested.  The test matrix can be found here: https://docs.google.com/spreadsheets/d/1SIuHF5V4TPR-H2FHugvL52cB6MvQ60gYgg-W-88A6mg/edit#gid=2

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele please make this your top testing priority

**Comment by oliver-phet** [comment]
Testing is now completed.

**Comment by ariel-phet** [comment]
Excellent...closing
