### ISSUE TITLE
Get activity licensing text

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#208]
@kathy-phet Do you have the licensing text for user-submitted activities? We would like to add this to the new 'Submit your activity' page and also have it available to answer user licensing questions about activities.

**Comment by oliver-phet** [comment]
We also need to know if the user has to check an "I agree" button, or if we can simply use text like "By submitting this activity, you are agreeing to the Licensing Agreement above."

**Comment by amanda-phet** [comment]
It is clearly a standard that other sites use when agreeing to licensing: 
![screen shot 2015-04-02 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/7852916/6974493/6fc8a38c-d950-11e4-94b9-2158c8113acf.png)

**Comment by ariel-phet** [comment]
Just as a side note, @oliver-phet  an issue such of this would be better to put in the website repo with the "requires Kathy" label

**Comment by ariel-phet** [comment]
We now have this text, closing
