### ISSUE TITLE
Artwork for Making Tens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#210]
This sim allows users to manipulate little torn pieces of paper. The best I could do with my skills currently looks like this: 
![screen shot 2015-04-03 at 12 29 42 pm](https://cloud.githubusercontent.com/assets/7852916/6986711/22e4f3ec-d9fd-11e4-8bd4-4efba55b456c.png)

The original app that the sim is based on has this look: 
![screen shot 2015-04-03 at 12 29 19 pm](https://cloud.githubusercontent.com/assets/7852916/6986709/16dfe318-d9fd-11e4-9743-b3df7bfdb54a.png)

can you please draw the small (one-digit) and large (two-digit) pieces of torn paper to match the original style better? Ignore the numbers- we have those. 

Thanks!

**Comment by amanda-phet** [comment]
Also, the three-digit paper looks like this:
![screen shot 2015-04-06 at 10 04 38 am](https://cloud.githubusercontent.com/assets/7852916/7007158/5a8c5044-dc44-11e4-97e2-ac90b840737a.png)

**Comment by ariel-phet** [comment]
@mariahmaephet - can you make this your top priority, and let me know when you thing you will be able to get to it?

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet 

How do these look? 
![screen shot 2015-06-01 at 2 32 08 pm](https://cloud.githubusercontent.com/assets/11527557/7923779/06bc23d8-086b-11e5-9697-3d40af30bd43.png)

**Comment by amanda-phet** [comment]
These look great! Will I be able to resize the pieces if you put the .ai file in drive? I'm concerned that the sizes aren't quite what we need, so I'm not sure if it's easier for you to make them the right size for for me to do it. 

Does this picture help you with the sizing? 
![screen shot 2015-06-02 at 10 12 43 am](https://cloud.githubusercontent.com/assets/7852916/7940734/f255cfe8-090f-11e5-9e41-bfdf798b77c8.png)

**Comment by mariahmaephet** [comment]
@amanda-phet  Yeah, you can definitely change the sizes in illustrator. I'll upload that now--let me know if it doesn't work

**Comment by amanda-phet** [comment]
It looks like it will work very well. I see now that they are rotated or flipped around to add variety, so I will do that! Thanks so much.

**Comment by amanda-phet** [comment]
When I resized the ripped paper to make the three necessary sizes, I noticed that the larger one now has a stretched appearance and a much thicker border. Would it be possible for you to make three different sizes so that the ripped edge doesn't scale so much when resized? They don't need to be exactly the proportion that I need, but I don't think stretching them is working. 

![screen shot 2015-06-03 at 12 37 27 pm](https://cloud.githubusercontent.com/assets/7852916/7968364/90c8c92c-09ed-11e5-998f-f99f310bf16b.png)


Unless there is a better way to resize them- I couldn't find a way to do it other than drag the corner. 

I will also check with the team and see what they think of the appearance, so perhaps wait until Thursday to revisit this (unless it is pretty quick).

**Comment by mariahmaephet** [comment]
@amanda-phet have you heard back from the team about what they'd like?

**Comment by amanda-phet** [comment]
Sorry, I didn't realize I wrote that last sentence! Yes, we like the appearance you came up with. 

I hope you can make these in 4 different sizes for me (we will also need a 1000 piece). The smallest two (1 and 10) look pretty good, but 100 and 1000 will need some work so that that gray border matches the thickness in the smallest two. When you look at them layered together, feel free to use your judgement to see how they look- the 10 may need an adjustment too.

**Comment by mariahmaephet** [comment]
@amanda-phet   I just readjusted some of them--I'll upload the .ai file to drive now so you can play around with them and let me know if they work.

**Comment by amanda-phet** [comment]
I will do that and get back to you. Thanks!

**Comment by amanda-phet** [comment]
I'll close this since these are all finished and were emailed to Ashraf.
