### ISSUE TITLE
Research a new quick-release plate for a Kalimar tripod

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#211]
We are missing a plate that goes with our Kalimar Pro-Tech V-40 tripod, and the ones we have don't fit quite right. I've been told we have bought one that didn't work. @schasteen can you let us know what you bought so we don't buy it again?

**Comment by oliver-phet** [comment]
@schasteen

**Comment by schasteen** [comment]
Here is the link to the product we bought before

<http://www.tripodquickrelease.com/Kalimar_Quick_Releases.htm>

Forum references:
<http://www.fixya.com/support/t5657474-kalimar_tripod>
<http://www.dpreview.com/forums/thread/1984617>

**Comment by phet-steele** [comment]
Do we still have this plate?

**Comment by schasteen** [comment]
No, it was returned.

**Comment by oliver-phet** [comment]
Closing this issue. If we need a new tripod, I will order another.
