### ISSUE TITLE
Translation utility UI mockups

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#212]
Hey @mariahmaephet, I need some help mocking up the user interface for our planned translation utility.

As a first step, please plan a meeting with @amanda-phet in the near future to get a quick overview of the "InVision" tool.

It would also be good for you and I to find a meeting time the week of April 6th to get started on this project (please just email me to set up a time).

**Comment by amanda-phet** [comment]
@mariahmaephet the site is http://www.invisionapp.com/. Sign up for a free account and you can look at the sample projects or tinker with making your own project. You basically just upload images, then within the site you can adding clickable areas that link to target images, comments, notes, etc.

---
Amanda McGarry
PhET Interactive Simulations
http://phet.colorado.edu

On Apr 4, 2015, at 12:02 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @mariahmaephet<https://github.com/mariahmaephet>, I need some help mocking up the user interface for our planned translation utility.

As a first step, please plan a meeting with @amanda-phet<https://github.com/amanda-phet> in the near future to get a quick overview of the "InVision" tool.

It would also be good for you and I to find a meeting time the week of April 6th to get started on this project (please just email me to set up a time).

**Comment by mariahmaephet** [comment]
@ariel-phet 

I think I've got InVision down, what would you like me to do?

**Comment by ariel-phet** [comment]
@mariahmaephet - lets discuss when we meet up

**Comment by ariel-phet** [comment]
This task has become a lower priority

**Comment by ariel-phet** [comment]
I think this issue can be closed since we have a reasonably working UI.
