### ISSUE TITLE
PhET girl poses for level selection buttons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#213]
We need 10 different level-selection icons for Making Tens. Ideally, they will communicate information about the level, but also be whimsical. 

An idea I had was to use PhET girl in different poses with numbers to communicate things like "under 10" and "between 10 and 99". 

The 10 levels are described below. As you can see, a button does not have a lot of real estate, so the images can not be too detailed. 
![screen shot 2015-04-06 at 10 46 49 am](https://cloud.githubusercontent.com/assets/7852916/7007854/87c46c44-dc4a-11e4-9678-8bd01529a2a8.png)

@mariahmaephet if you want to get started on manipulating PhET girl in to different poses, that would be a great start (and it would be very helpful for us to have these illustrator files). When you feel ready to tackle this specific task, let's talk about our ideas for the levels.

**Comment by ariel-phet** [comment]
@mariahmaephet - as an example I think for "over 100" we though we could have her peeking over the 100, or for one of the "under" examples perhaps peeking underneath the number (or bench pressing it or such). It can be pretty creative.I am sure you and @amanda-phet will discuss lots of ideas, but that is just to give a feel for the kind of thing we were thinking.

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet 

So I've been looking into character design and whatnot for PhET girl and figured out it's a lot easier and smarter to just work out her whole character in individual parts and then piece them together later for different poses and situations. I'm also not able to manipulate the versions of her you gave me previously so I'm having to redraw and figure out her whole look. This kind of thing is new for me but I'm super into it--it might just take a little longer to get you those specific poses. I've done her head and faces and am starting in on hands and legs. 
![screen shot 2015-05-29 at 10 45 19 am](https://cloud.githubusercontent.com/assets/11527557/7890864/9530c526-05fd-11e5-9354-ecabffcb2c31.png)

**Comment by mariahmaephet** [comment]
Here's a few I've been working on--does this look alright? I'll go through and add the logo to her shirt eventually
![screen shot 2015-06-01 at 3 53 21 pm](https://cloud.githubusercontent.com/assets/11527557/7925141/5e28dbe2-0876-11e5-940f-900d400073c5.png)

**Comment by amanda-phet** [comment]
These are looking great!

**Comment by amanda-phet** [comment]
For the purposes of Making Tens, can you come up with the poses for these specific levels? Again, the ideas we had were things like holding a 100 over her head (for under 100) or posing on top of a 10 (for over 10), or peeking over a 10.

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet Is this close to what you were thinking? And how is the page layout going to change? I wasn't sure what the numbers should look like or how big they or phet girl should be. 

<img width="1060" alt="screen shot 2015-07-13 at 3 45 13 pm" src="https://cloud.githubusercontent.com/assets/11527557/8661823/b7bbc828-2977-11e5-99b8-abc57aeb375f.png">

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet  

Since I didn't have wifi to do some things I spent a good amount of time just practicing and playing around with PhET girl and getting better and quicker at drawing her and learning how to do clothing and poses and such. I've done some objects and things but those probably aren't as relevant yet. 

<img width="1199" alt="screen shot 2015-07-13 at 4 01 12 pm" src="https://cloud.githubusercontent.com/assets/11527557/8661930/a11d050e-2978-11e5-8d11-8344278e108b.png">
<img width="1226" alt="screen shot 2015-07-13 at 4 01 22 pm" src="https://cloud.githubusercontent.com/assets/11527557/8661929/a1183312-2978-11e5-9325-4689d2506494.png">

**Comment by ariel-phet** [comment]
@mariahmaephet - love all these new poses/outfits! I think Safari PhET girl is one of my favorites

**Comment by ariel-phet** [comment]
@mariahmaephet  - 2 other interesting variations (if you feel inspired, but not high prioritiy at all)

1 -  a more "ethnically ambiguous" PhET girl...I think color vision has a good example of ethnically ambiguous (slightly darker skin, dark wavy/curly hair)

2. - PhET girl in a really "sporty" wheelchair. Looking like she is racing in it or such

**Comment by mariahmaephet** [comment]
@ariel-phet Like this kind?

![hannah-cockcroft](https://cloud.githubusercontent.com/assets/11527557/8702226/b94b701e-2ad3-11e5-8295-c2f49a13ec0d.jpg)

And did you want to try PhET girl out as more ambiguous in general or make it like different characters/outfits? 

<img width="494" alt="screen shot 2015-07-15 at 9 33 49 am" src="https://cloud.githubusercontent.com/assets/11527557/8702394/c1287d1c-2ad4-11e5-94c1-104b459f5fdd.png">


and probably not a priority, but were you wanting me to update other characters as well? I know in Balancing Act there's another boy, man, and woman.

**Comment by ariel-phet** [comment]
Just in general for the moment, so we have some thoughts/options.

Good question about Balancing Act, I will ask the original creator of the artwork, might be nice to have consistent artwork. (Similar question for Forces and Motion Basics).

Yes on the Wheel Chair...something like that and with a look of confidence on her face.

**Comment by emily-phet** [comment]
Just a thought - if PhET Girl has different colored skin, it might be more appropriate to change her hair and possibly other features correspondingly. I always find it a bit odd to see, for example, paintings of Native American women that look white women with darker skin. Regardless, we'll need to be careful here...not all dark skinned women have curly hair, etc. 
I wonder if there might be someone we could ask for advice, perhaps someone in marketing, so that we don't end up with an accidentally overly-stereotypic character.

**Comment by amanda-phet** [comment]
Thanks for chiming in @emily-phet . This was also making me think that rather than change the skin and hair of the current PhET girl, perhaps we should make a PhET boy instead? It might feel less contrived that way.

**Comment by ariel-phet** [comment]
@amanda-phet and @emily-phet - I also asked @mariahmaephet to try making a PhET girl that was just a separate character (not necessarily just trying to change hair/skin tone).

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet @emily-phet PhET girl has a whole gang now

I thought the boy on the bottom left could be good option for an 'ethnically ambiguous' PhET boy


<img width="985" alt="screen shot 2015-07-21 at 1 13 46 pm" src="https://cloud.githubusercontent.com/assets/11527557/8810169/5e85e3e0-2faa-11e5-9188-84277e8f91cb.png">

**Comment by emily-phet** [comment]
I like ariel as phet boy. Now we need an Emmy PhET dog. :)

**Comment by arouinfar** [comment]
@mariahmaephet these are all super awesome! Great work!!

**Comment by mariahmaephet** [comment]
@amanda-phet Are you available next week to go over the poses for the levels? I think I'll be meeting with Ariel on Wednesday but I could come in Monday as well.

**Comment by amanda-phet** [comment]
@mariahmaephet have you had a chance to make any of the level selection icons yet? If you have just one that would be great to look at as an update. Thanks!

**Comment by mariahmaephet** [comment]
@amanda-phet 
<img width="795" alt="screen shot 2015-09-11 at 2 51 15 pm" src="https://cloud.githubusercontent.com/assets/11527557/9826018/9c2d33de-5894-11e5-9e65-257db1884bff.png">

**Comment by mariahmaephet** [comment]
and i uploaded the .ai file to my drive (levelselection.ai)

**Comment by amanda-phet** [comment]
The team likes the artwork so I'll go ahead and close this. Thanks @mariahmaephet !
