### ISSUE TITLE
Test a few sims on the new "Datawind" 7" tablet

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#214]
@orejolaphet @bryo5363 @phet-steele Can you guys test a few HTML5 sims on this new "Datawind" 7" tablet? Maybe Molecule Shapes, ESPB, Balancing Act?

I put the tablet (still in box) on the device shelf.

Note issues you encounter on the tablet.

After testing sims, see if you can upgrade any of the software on the device (OS, browser), then retest some sims to see if there are any improvements.

**Comment by pixelzoom** [comment]
@oliver-phet Which model are you testing? Just curious.  Worth noting is that the resolution of all Datawind devices is only 800x480.

**Comment by phet-steele** [comment]
Using the "Browser" app, not the "Internet UbiSlate" app, these sims had very long load times:
Molecule Shapes (canvas) will run at 5-6 FPS, and selecting SF6 essentially freezes the app.
ESPB will run at 6-9 FPS on the first two screens, and drops to 4 FPS when multiple tracks are out on the playground screen.
Balancing Act, ?profiler wasn't working, but I'd put this sim in the ballpark of 6-10 FPS. It slows down with more things on screen.

@pixelzoom this is a UbiSlate 7C+ Smartphone

**Comment by phet-steele** [comment]
I cant get any of the three previously mentioned sims to open on the "Internet UbiSlate" app.

**Comment by phet-steele** [comment]
I've downloaded Chrome, and it does not perform any better or worse in my opinion.

**Comment by pixelzoom** [comment]
Curious about how it looks on this device, with the lower resolution.

**Comment by oliver-phet** [comment]
The sims I saw @phet-steele testing were all unusable using the default browser, Internet UbiSurfer, and the latest version of Chrome due to load time and lag. The resolution seemed "low", but adequate, to show a sim.

**Comment by ariel-phet** [comment]
Sounds like since sims are pretty much unusable we should close this investigation

**Comment by samreid** [comment]
@ariel-phet are you interested in testing the performance of webgl on this platform, to see what may (in principle) be possible for our sims with webgl support?  Here are some examples from a popular open source 2D WebGL project that may indicate "order of magnitude" of performance and tell us whether webgl will help anything on this platform:
http://www.pixijs.com/examples/

**Comment by ariel-phet** [comment]
@samreid - they were testing Chrome with ESPB...shouldn't that have already given a gauge of if Webgl is working?

**Comment by samreid** [comment]
The ESPB test gives us some information but it doesn't answer what would happen if more (or all) of the sim was rendered in WebGL--only about 5 moving objects were being rendered with WebGL in ESPB: the skater, the bar chart, the pie chart and the speedometer needle.  The rest (hundreds of other graphics) is a very heavyweight SVG tree, so we cannot be certain which was the expensive part to render or if things would speed up if more was rendered in WebGL.

On the other hand, using Pixi examples won't answer this question perfectly either since they are not the same complexity or rendering technique as we plan for a PhET WebGL Sim.

**Comment by ariel-phet** [comment]
@samreid - I am going to close this issue again. If at some point we have a sim rendered more fully in webgl, we can test, and at that time this tablet may also have an improved model.
