### ISSUE TITLE
Update iPads to iOS8.3

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#215]
Hey @orejolaphet, @bryo5363, @phet-steele, @arnabp whenever any of you gets the chance, can you update the iPads to iOS8.3 (which just came out)

Thanks!

**Comment by samreid** [comment]
@ariel-phet I'm seeing many reports that iOS 8.3 improves performance for iPad2 and iPad3, see http://www.reddit.com/r/apple/comments/31xh3l/ios_83_made_my_phone_feel_faster_than_ever_before/

I recommend to test performance on several sims on iOS8.2 using the ?profiler query parameter and record performance, *then* upgrade to iOS 8.3 and re-test performance on those same sims, so we can see if the performance updates apply to our simulations.

@ariel-phet does this sound OK to you?  If so, please make sure @orejolaphet @bryo5363 @phet-steele and @arnabp are aware of this plan before updating.

**Comment by ariel-phet** [comment]
Sounds good to me. @samreid do you mind putting a checklist of a few sims that are known to be borderline performance and might be good test cases?

**Comment by samreid** [comment]
Some tests for my iPad3, run with ?profiler so we can compare frame rates:

iOS 8.1.2
Energy Skate Park: Basics 1.0.0.  Intro Screen.  Pie Chart on, Bar Graph on, Grid on, Speedometer on.  Skater oscillating back and forth on the parabola track.
60fps

Energy Skate Park: Basics 1.0.0.  Playground Screen.  Dragging a single track in a circle many times
14fps

Faraday's Law 1.0.1.  Dragging bar magnet in a small circle in the top right of the screen many times.
17fps

Color Vision 1.0.0: Single bulb: Photon mode. Flashlight on
> http://www.colorado.edu/physics/phet/dev/html/color-vision/1.0.0-dev.14/color-vision_en.html
40 FPS (note different readout in this version, FPS and ms/frame switched places)

Build an Atom 1.2.0-dev.1 http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-dev.1/build-an-atom_en.html
Atom screen. Drag a single electron in a circle many times around the large dotted blue line
14fps

**Comment by samreid** [comment]
Would be great for others to replicate these tests on iPad3/iOS8.2, iPad3/iOS8.3, iPad2/iOS8.2, iPad2/iOS8.3.  Once my iPad3 is updated to iOS8.3 I'll run the tests again and report here.

**Comment by samreid** [comment]
I reported some numbers above.  SVG things seem about the same speed, but canvas seemed a bit faster, at least from the color-vision test.

**Comment by phet-steele** [comment]
The iPad2 in the office is running iOS 8.0, and her are the results from the same tests performed above:
ESPB Intro: 60fps
ESPB Playground: 17fps
Faraday's: 20fps
Color Vision: 60fps
Build an Atom: 12fps

I also performed tests on Molecule Shapes 1.0.0.
Model Screen, 4 lone pairs, 2 single bonds, rotating the molecule around while holding a bonded atom: 55fps
Real Molecules, SF6 with bond angles and outer lone pairs shown, then dragging a bonded atom around: 20fps

The iPad3 being used runs on iOS 8.1:
ESPB Intro: 60fps
ESPB Playground: 15fps
Faraday's: 15fps
Color Vision: 60fps
Build an Atom: 12fps
Molecule Shapes Model: 57fps
Molecule Shapes Real: 20fps

**Comment by phet-steele** [comment]
iPad2 now running on iOS 8.3, earlier performance is the first number reported, then the arrow points to the updated performance:
ESPB Intro: 60fps --> 60fps
ESPB Playground: 17fps --> 17fps
Faraday's: 20fps --> 20fps
Color Vision: 60fps --> 60fps
Build an Atom: 12fps --> 12fps
Molecule Shapes Model: 55fps --> 58fps
Molecule Shapes Real: 20fps --> 20fps

iPad3 now running on iOS 8.3:
ESPB Intro: 60fps --> 60fps
ESPB Playground: 15fps --> 16fps
Faraday's: 15fps --> 17fps
Color Vision: 60fps --> 60fps
Build an Atom: 12fps --> 12fps
Molecule Shapes Model: 57fps --> 57fps
Molecule Shapes Real: 20fps --> 21fps

**Comment by samreid** [comment]
Thanks @phet-steele, this is very valuable to help us understand what is happening in new iOS updates, and how it relates to performance improvements reported by others.  Nice work!

**Comment by ariel-phet** [comment]
Witten, Bjork, Leibniz still need updating

###Note
Please leave Lave as iOS 7.1 so we have an iOS 7 testing platform

**Comment by phet-steele** [comment]
Those three iPads are now updated! What's the deal with having two iPads named diSessa?

**Comment by phet-steele** [comment]
Never mind about the diSessa thing, figured it out.

**Comment by ariel-phet** [comment]
Excellent, thanks, and closing.
