### ISSUE TITLE
Polishing of CHI Poster

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#216]
If Mariah has some time to add a little polish to a poster by noon on Tuesday (this is the time I will head over to JILA to print it), that would be very helpful. 
- If only a little bit of time is possible, just going over it and aligning things would be great.
- If she has more time, I bet there's a way to structure this poster similar to the ACS poster she made a few weeks ago, e.g., with the "tablet tilting girl" image in a big circle in the middle, and the rest of the information in color blocks around the the center image.

I'll go ahead and email the powerpoint file of the draft poster to Mariah, since I can't attach it here.

**Comment by ariel-phet** [comment]
Hey @mariahmaephet - please make this your top priority now that the booth items are finished.

If possible, I think @emily-phet would like to meet with you on Monday (4/13) or Tuesday (4/14) - obviously I will let you two coordinate, I just wanted to put a "heads up" in this comment

**Comment by mariahmaephet** [comment]
@emily-phet @ariel-phet   I'm meeting Amy tomorrow at 3 if Emily is available at that time?

**Comment by emily-phet** [comment]
@mariahmaephet - I am available at 3pm today.

**Comment by mariahmaephet** [comment]
@emily-phet   Cool! Amy said she'll be running a little late so we can talk at 3 and probably be done by the time she gets there

**Comment by emily-phet** [comment]
@mariahmaephet - Amy and I may be coming from the same meeting, but I think our chat will be short so hopefully we can squeeze it in at 3pm.

**Comment by ariel-phet** [comment]
Since this poster has been printed, I am closing the issue
