### ISSUE TITLE
Creating PhET "Breaking Bad" T shirt

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#219]
I think it would be fun to have a PhET "Breaking Bad" style T-shirt. Something like:

![31mxzujkf4l _sx342_](https://cloud.githubusercontent.com/assets/4051174/7141074/79e2f74c-e28c-11e4-81ed-64fc98cd6e48.jpg)

But with "Interactive" (with the "In" for the element Indium) and "Simulations" (with the "Si" for the element Silicon).

**Comment by mariahmaephet** [comment]
@ariel-phet   were you thinking something like this? 

![screen shot 2015-04-24 at 11 53 22 am](https://cloud.githubusercontent.com/assets/11527557/7325015/8e8e80c8-ea78-11e4-8485-e7cd97095c70.png)
![screen shot 2015-04-24 at 11 51 24 am](https://cloud.githubusercontent.com/assets/11527557/7325017/8fdaa2a4-ea78-11e4-81ee-4b118c12480c.png)

I also thought it might be cute to have matching shirts with PhET girl
![screen shot 2015-04-24 at 11 44 10 am](https://cloud.githubusercontent.com/assets/11527557/7325027/ac5f7454-ea78-11e4-9510-332bae0d7ef9.png)
 
![screen shot 2015-04-24 at 11 56 38 am](https://cloud.githubusercontent.com/assets/11527557/7325076/fedeec14-ea78-11e4-9373-0e9508af5e5c.png)

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-24 at 12 08 50 pm](https://cloud.githubusercontent.com/assets/11527557/7325302/b7dcb86c-ea7a-11e4-84a3-af6aa4a95b37.png)

**Comment by mariahmaephet** [comment]
![screen shot 2015-04-24 at 12 17 58 pm](https://cloud.githubusercontent.com/assets/11527557/7325559/4c0b66b8-ea7c-11e4-8758-9da5a1f40d4b.png)
![screen shot 2015-04-24 at 12 20 11 pm](https://cloud.githubusercontent.com/assets/11527557/7325558/4c07cb98-ea7c-11e4-91ba-d1853f525d54.png)

**Comment by ariel-phet** [comment]
Hey @mariahmaephet - the first row is exactly what I was thinking in terms of the Interactive Simulations portion. It might be nice to have everything just on the front...so it says PhET with our logo small, and then Interactive Simulations in the breaking bad style (that was my vision anyhow).

Also remember, a good workflow is to reassign issues to someone if you want them to take a look. Mentioning with the "@" symbol is a good habit, but reassigning helps boost the attention.

**Comment by mariahmaephet** [comment]
@ariel-phet 

Just playing around with merchandise ideas--how do you like these stickers/designs? 

<img width="856" alt="screen shot 2015-07-13 at 4 18 07 pm" src="https://cloud.githubusercontent.com/assets/11527557/8662265/44ed3594-297b-11e5-8a1d-33a99ac2deb7.png">
<img width="465" alt="screen shot 2015-07-13 at 4 18 22 pm" src="https://cloud.githubusercontent.com/assets/11527557/8662267/44f63f86-297b-11e5-934d-3ec4bfeff3b8.png">
<img width="384" alt="screen shot 2015-07-13 at 4 18 37 pm" src="https://cloud.githubusercontent.com/assets/11527557/8662268/44f7d256-297b-11e5-9c56-dda731f9beec.png">
<img width="449" alt="screen shot 2015-07-13 at 4 18 44 pm" src="https://cloud.githubusercontent.com/assets/11527557/8662266/44f2fca4-297b-11e5-80b9-a4d322894751.png">

**Comment by ariel-phet** [comment]
Breaking bad shirt is up on cafepress, closing
