### ISSUE TITLE
Background Research on Potential Math Grant Partners

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/tasks#221]
We are applying for some funding for math grant, and need to understand who the other applicants are because we need to approach them to see if they would be open to working with PhET sims if we were funded. 

Do NOT email these contacts. 

Just create a google document, and do a bit of background research on the organization. Find the link to the organization/project website that the person works for. Find out (if you can do it through the website) 
- what sort of teacher PD services they offer, and 
- position the person in the list below holds. 

Thanks! 
Kathy 

Lori Shough - MCESAX <lori.shough@mcesa.maricopa.gov>, Christian Martinez <cmartinez@breakthroughcollaborative.org>, Cynthia Pulkowski <cpulkowski@assetinc.org>, Kimberly Mogavero <kmogavero@mindresearch.org>, Rosanna Satterfield <rosanna@njctl.org>, Lori Pidick <lpidick@pebc.org>, Kimberly Rimbey <krimbey@rodelfoundations.org>, Sarah Zaner <Sarah.Zaner@SRI.com>, Sarah Givens <sgivens@teachingchannel.org>, Beverly Simmons <bsimmons@ten80education.com>, Debbie A Leslie <daleslie@uchicago.edu>, Oliver Pascal Nix <Oliver.Nix@colorado.edu>, Katherine.Perkins@colorado.edu <Katherine.Perkins@colorado.edu>

**Comment by arnabp** [comment]
https://docs.google.com/spreadsheets/d/1U0_9H_xyTe34HPRS18JAZ0e4pAHZalhEwGETlgtFxOk/edit?usp=sharing

I've filled out most of the information. I'm not exactly sure what "teacher PD services" are. Does PD stand for professional development? And what exactly does that entail, ie, what am I looking for?

**Comment by ariel-phet** [comment]
@arnabp  - yes PD stands for professional development. @kathy-phet can comment more but usually PD involves short courses or such that teachers can take to learn more about content, a particular teaching method, effective use of a tool in the classroom etc.

For example, an interactive whiteboard company might have a webinar, or a short online course, or a short in person course (day long or such) that gives teachers effective ways over using their technology. Or a curriculum provider might provide a longer seminar that shows how to use their curriculum and assessments. If when you went to school your teachers had "inservice" days, they were often doing some sort of PD.

@patricialoeblein - do you think those are good examples of PD, or perhaps I am a little off base?

**Comment by patricialoeblein** [comment]
Good explanation. Teachers need to document their PD hours for things like license renewal or as part of their evaluations. Often self-identified independent learning is counted for PD. For example, if I wanted to learn more about how to use PhET effectively with clickers, I might watch videos, read articles, search for questions that are already written, etc. So, you may find that a district has a person who administrates a website of ideas and provides a way for teachers to document their PD. Those people might be good contacts.

**Comment by arnabp** [comment]
I've added information for the first two companies. Is this the sort of thing you're looking for? Should I be more (or less) specific?

https://docs.google.com/spreadsheets/d/1U0_9H_xyTe34HPRS18JAZ0e4pAHZalhEwGETlgtFxOk/edit?usp=sharing

**Comment by kathy-phet** [comment]
Hi Everyone, 

Thanks for the info on these groups. I did follow-up with many of these companies over the past month, and made some good contacts that will lead to PhET being used by them. Although the grant opportunity turned out not work well for our offerings, the connections were great. 

I'll close the ticket. 
K
