### ISSUE TITLE
Complete PhET Party Poll! 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/tasks#222]
Please go here and fill out the PhET Party Poll ... we are hoping to be able to coordinate a time when our undergraduate team is around! 

Reassign the issue to someone who hasn't checked off their name! 

Thanks, Kathy 

http://doodle.com/k56qvmr3b8vbz9ky

- [x] arnabp
- [x] BrianNewsome
- [x] bryo5363
- [x] EmilyRandall
- [x] jessegreenberg
- [ ] mariahmaephet
- [x] oreolaphet
- [x] phet-steele
- [x] alexklinger

**Comment by ariel-phet** [comment]
@arnabp @EmilyRandall @BrianNewsom @bryo5363 @jessegreenberg @mariahmaephet @orejolaphet @alexklinger please respond

**Comment by bryo5363** [comment]
@kathy-phet I believe everyone has completed the poll. I apologize for the delay; I filled the poll out on my phone but apparently it did not register with the site.

**Comment by ariel-phet** [comment]
Excellent, thanks!
