### ISSUE TITLE
Investigate adding a consistent label set to new repostiories

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#223]
From Developer meeting:

>AP: some consistent labels for GitHub issues?
I find labels super useful for organizing issues, maybe we should start to build a consistent set we tend to use for sim repos (and maybe when working with a 3rd party) 
Possible labels (such as priority, requires-kathy, performance, code review, scenery-related, ...)
Does this seem like a useful tool:
http://www.dorukdestan.com/github-label-manager
CM: I’ll have a look after my vacation, unless someone else wants to do it sooner.
SR: I’d recommend manually updating things first, after we decide on the labels (unless the github-label-manager can 100% guarantee it won’t break anything)
SR: To me, the most important label to keep consistent is “high-priority”.
AP: “requires-kathy” is important to me.

**Comment by pixelzoom** [comment]
github-label-manager does not support "batch" synchronization of labels across multiple repositories. It allows you to copy all (or some) labels from one repository to another.   As it's help says:

> Yes, not really much different from Github itself. But the thing is you can do those as bunches here. The main thing is that you can also copy another repos's labels into yours with or without some modifications.

We could have a "template" repository that has standard labels that we want, and add those to a repository when it's created. But when we modify the template in any way, github-label-manager doesn't provide any tools for updating the labels of all existing phetsims repositories.

So I don't see much value in this tool.

**Comment by pixelzoom** [comment]
Here's another possibility to investigate, but looks kind of scary: https://github.com/piwik/github-sync

**Comment by pixelzoom** [comment]
Punting on github-sync, see https://github.com/piwik/github-sync/issues/5.

**Comment by pixelzoom** [comment]
@ariel-phet is there anything else you want me to do regarding this issue?

**Comment by pixelzoom** [comment]
At 4/30/15, @ariel-phet asked @aaronsamuel137 to look at writing something custom to do this.

**Comment by samreid** [comment]
I wasn't at today's meeting, but how about doing @samreid's suggestion from the issue description:

> I’d recommend manually updating things first, after we decide on the labels

**Comment by pixelzoom** [comment]
I agree that we could manually update a couple of repos to agree on the set of labels, colors, etc. But we have 96 entries in active-repos. It would take hours (days?) for someone to manually update them.

**Comment by samreid** [comment]
Assuming it takes 2 minutes to do each repo, plus 10 minutes to create a list of repos and a place to check them off when done, this would be 10+2*96 minutes = 3.4 hours.  How long will it take to create + test an automated tool for this? How will it handle corner cases like "label already exists but is the wrong color" or "similar label exists and issues need to be associated with the new label"?  etc etc.

**Comment by pixelzoom** [comment]
I'm not advocating automation of this, and I think there will be some unexpected issues. (The case "label already exists but is the wrong color" is (supposedly) handled by github-sync, so I don't think that's a problem.  Replacing or deleting a label is indeed a problem.)

But I think your estimate of 2 minutes per repo is overly optimistic. I think it will be closer to 5 minutes per repo. Updating manually will be repetitive and therefore error prone.  And the set of labels will like evolve over time, so it's a task that will need to be done again, for an increasing number of repositories.

**Comment by ariel-phet** [comment]
Github gave some advice on this, moved to a chipper issue https://github.com/phetsims/chipper/issues/425 closing
