### ISSUE TITLE
Troubleshoot modmic for Mac

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/tasks#225]
We've run into an issue with the modmic that was recently purchased for recording sim primers.

On several Macbooks (e.g. mine [mid-2012 retina 15", OSX 10.9.5] and Dirac), the external mic is not recognized by the system when plugged in using the provided headset/mic splitter - only the internal microphone is displayed under System Preferences > Sound > Input, although the headphones are recognized as a connected output.

@arnabp Can you investigate and see if there is a common reason for the mic to not be recognized on some systems, and see if there are any suggested troubleshooting tips? @oliver-phet should have the mic currently.

**Comment by oliver-phet** [comment]
I just tested on my mac and the first time I plugged in, the mic wasn't recognized, I unplugged/replugged everything on my mac and mic and tried again and it recognized like normal.

**Comment by ycarpenterphet** [comment]
Looks like this can now be resolved by using the USB adapter instead of the splitter that plugs into the headphone jack.

I'll update the teacher primers technical documentation with information about both cases.

Closing.

**Comment by oliver-phet** [comment]
@ycarpenterphet Arnab and I were running into some weird clicking/beeping when using different mic setups. It might be good to double-check some the audio you've recorded to make sure it is acceptable quality.

**Comment by ycarpenterphet** [comment]
Interesting. I know that @arouinfar was encountering more static with the modmic (especially when using the USB adapter, although some with the headphone jack adapter as well) than with the internal mic on her laptop.

I will re-open this issue for now and report back after I try recording a new primer in a few days.

**Comment by ycarpenterphet** [comment]
Testing Results: 

<b>USB:</b> While the USB adapter offers higher compatibility (is recognized by more macs), there is, as reported, a continuous repeated beeping noise in the background as a result of how the USB port is powering the mic. This renders the audio unusable.

<b>Headphone jack splitter:</b> Offers great audio quality but is only recognized by a limited number of Macbook models. Of the currently available communal PhET devices, only the Macbook Airs (Jordan, Curie) recognize the input from this setup. Turing (same model as mine), Dirac, and Magnus do not. Erdos and Bose are the same model year as Dirac, and Copernicus is an older model year, so is unlikely to work. It's difficult to document a hardware model year after which the Macbooks will guaranteeably recognize this input (since the Airs seem to do so as early as 2010, while even a mid 2012 Macbook Pro 15" won't). OS version seems to have no impact.

Notably, recording on the Macbook Air results in lower resolution screen capture video (max 1024x670 in Chrome or FF since the address bar can't be hidden; max 1097x718 in Safari - and must hide the OSX Dock to save vertical space). The bumpers have a vertical dimension of 720px, so this seems to be an acceptable resolution, but it may require that we recommend to anyone needing to borrow a laptop to go with the modmic should use Safari only for recording.

**Comment by ycarpenterphet** [comment]
I'll update the documentation and primer team accordingly. If we decide we need any alternate solution, I'll open a new issue then.

Closing.

**Comment by ycarpenterphet** [comment]
Updates:

Tested modmic with alternate USB adapter (brand: Plantronics) with widely varying results. No beeping sounds in the background, but audio quality seemed to depend heavily on the laptop used. With my macbook pro (mid 2012 15" retina), there is audible continuous static in the background of the recording. With the Macbook Air (Jordan), the audio has a slightly different timbre (deeper?) using this USB adapter than using the headset jack adapter, but no issue with static.

So far, the best audio quality still seems to be with the headset jack adapter - will update with other devices over the next few days.

**Comment by ycarpenterphet** [comment]
Copernicus, Schrodinger and Erdos all correctly recognize the modmic with headset adapter. However, the sound quality with the headset adapter and Schrodinger is poor. The pickup of static is louder than the voice pickup, which is extremely quiet even after adjusting settings. It seems Mac's default ambient noise reduction is also very helpful.

Camtasia is not yet installed on Copernicus or Erdos.

**Comment by ycarpenterphet** [comment]
Screen resolution on Socrates is too low for recording (max 680 pixels vertically).

**Comment by schasteen** [comment]
Some additional documentation on this issue:
On some Macbooks, even though it pairs correctly, the ModMic has a buzzing in the background.  This is not the case with Copernicus.  So, if you can pair the ModMic on your computer, listen to make sure there is no background buzz.
When pairing on Copernicus, System Preferences refers to the ModMic as the External Microphone.  You can select "reduce background" for that device, and turn up the volume.  In Camtasia, however, the ModMic is referred to as the Built In Microphone (as opposed to Built in Input).  Make sure you have the correct devices selected.  On computers other than Copernicus, the microphone selections may be different (on my MacBook, System Preferences only listed External Microphone, and Camtasia only listed the Built-In Microphone).

Redux:
- If you hear background buzz in your recordings, use Copernicus
- Choose External Microphone (in System Prefs), turn up volume and use noise reduction.  
- Choose Built In Microphone in Camtasia
