### ISSUE TITLE
Reformatting AP's old computer

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#226]
@arouinfar I am going to eventually assign this issue to @arnabp for the actual work but it would be good to put the desire software requirements here.

I am assuming we want the following (and then please add or modify this list):
1. Windows 7
2. Microsoft Office
3. Camtasia
4. Java
5. IE, Firefox, Chrome (with up-to-date Flash)

The computer has many of these already, so we could either just wipe my files or do a fresh install

**Comment by arouinfar** [comment]
Looks great. @amanda-phet and I cannot think of any additional software that we would need on the laptop. Reassigning to @ariel-phet to prioritize this task for @arnabp.

**Comment by arnabp** [comment]
All listed applications have been installed on "Schrodinger" (It doesn't have a label yet). It's sitting on my desk in Oliver's office.

**Comment by ycarpenterphet** [comment]
the label-maker lives on the bottom shelf of AP's office (where most of the devices live), if it is needed.

**Comment by ariel-phet** [comment]
@arnabp - excellent...when it is labelled and added to the asset matrix can you drop it off with an appropriate charger in Amy and Amanda's office?

**Comment by arnabp** [comment]
Labeled and delivered!

**Comment by ycarpenterphet** [comment]
@arnabp Can you add this laptop as a new row in the Laptops section of the asset inventory spreadsheet, filling in the appropriate details on Home location, OS, model, any licensed software installed (like VMware or Camtasia)?

**Comment by arnabp** [comment]
Asset inventory has been updated
