### ISSUE TITLE
test cross-platform behavior of beaker version 1.0.0-together.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#228]
In the development of the data sharing capabilities, we have done very little cross platform testing.  It would be good to get some initial testing done to see if there are any major issues.

I'm a little reluctant to put the direct link up here, since we are trying to keep this unindexed for now, so I'm going to obfuscate it a bit.  To get there, go to http://www.colorado.edu/physics/phet/dev/html/beaker and then add the version number (from the title above) to the URL.  Then select the "links" file.  The linked demos will correspond to the tests listed below.

The testing that should be performed is:

+ Verify that the basic simulation runs with assertions enabled and that no bad behavior is seen and no assertions occur.
+ Verify that data is seen when data logging is enabled.
+ When the simulation is embedded in a wrapper, the data table of trials fills in with what appears to be correct values.
+ The version where concentration is configured to appear as a percentage (via a query parameter) appears to work correctly.

**Comment by jbphet** [comment]
@phet-steele is going to start working on this.

**Comment by jbphet** [comment]
Modified test matrix for this task: https://docs.google.com/a/colorado.edu/spreadsheets/d/1we2uhIFvBKQKtgt3DZ_ChAkl8fahOOPiXDU1EeG4s54/edit?usp=sharing

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele please make this sim your current top testing priority. Note that this is not a normal phet sim, and it is a prototype for some collaborations we are doing.

**Comment by samreid** [comment]
@bryo5363 @orejolaphet @phet-steele I wasn't sure if @jbphet mentioned it, but to see the data output for that test, you must open the browser javascript console.  Instructions for doing so vary from browser to browser.

**Comment by samreid** [comment]
Oops, accidentally hit close.  It's open again.

**Comment by orejolaphet** [comment]
@jbphet what data am I supposed to see? On Windows 7 IE 11, the console only displays the following after I interact with the simulation. 
"
SEC7119: XMLHttpRequest for https://kinesis.us-east-1.amazonaws.com/ required CORS preflight.
File: phet-metacog-wrapper.html
"

**Comment by ariel-phet** [comment]
Not sure this is a high priority to test at the moment reassigning to @jbphet to comment or close

**Comment by jbphet** [comment]
We've probably done all the testing that is needed on this release.  In answer to @orejolaphet, I'm not sure what you're seeing.  I just tried IE11 on Win7 and the data logging appears in the console as it should.  At any rate, I think we're done here.  Closing.
