### ISSUE TITLE
Teacher Appreciation Week Picture for Facebook

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#229]
Hey @mariahmaephet - next week is "Teacher Appreciation Week" and we wanted to do a fun and thankful post on our facebook page. It would be really helpful to have a great illustration for this post.

We were thinking about something with PhET girl. Maybe she could be holding up a big sign that says "Thanks Teachers!" or such. For some reason I think it would be fun to have her in a lab coat, but that was just a thought.

I think you can be pretty whimsical and creative with this design, and she could be in some sort of scene...in a school, in a lab, on top of a mountain even. Imagine just a really awesome thank you card cover.

**Comment by mariahmaephet** [comment]
@ariel-phet Sounds good! I'll get right on that

**Comment by ariel-phet** [comment]
@mariahmaephet - think you will have something for Monday?

**Comment by ariel-phet** [comment]
Great job on this artwork @mariahmaephet - excited to use it in our facebook post!
