### ISSUE TITLE
Artwork for Conference Paper

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#230]
I would like Mariah to work on two figures - only requiring some stylizing of text content - for a conference proceedings paper. Ideally, she would be able to have these completed by the middle of next week. I think it will be quite quick (maybe 1 hr of work).

**Comment by amanda-phet** [comment]
@mariahmaephet This seems like a pretty small task to fit in this week after you have finished #229. If you think it will take much longer than Emily is guessing then let me or @ariel-phet know.

**Comment by ariel-phet** [comment]
@mariahmaephet & @amanda-phet I think it would also be OK to do in parallel with #229 if you have time.

**Comment by mariahmaephet** [comment]
@emily-phet @amanda-phet @ariel-phet 

Seems easy enough--I can have that done this week

**Comment by emily-phet** [comment]
@mariahmaephet - just wanted to check in on how this is going. 

Also, there has also been a slight wording tweak to Figure 1. The second paragraph in Figure 1 should read "In this case, according to the Court meaningful access is shown: "
If you have any questions about this, let me know.

**Comment by mariahmaephet** [comment]
@emily-phet @amanda-phet How do these look? I wasn't really sure how to do Figure 2... 

![screen shot 2015-05-04 at 1 00 00 pm](https://cloud.githubusercontent.com/assets/11527557/7460057/983e3d2e-f25d-11e4-89a6-774b697973db.png)
![screen shot 2015-05-04 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/11527557/7460060/9a463b12-f25d-11e4-9d62-e58a6083bc9d.png)

**Comment by emily-phet** [comment]
@mariahmaephet - these look great! Two small suggestions:
- For the Section 504 figure, add a little more space above the line starting with (b)(4)
- For the Alexander v. Choate figure, can you remove the little white boxes that appear in the right side after the two headings?

After that, these look good to go! Thanks!

**Comment by mariahmaephet** [comment]
@emily-phet Like that? Or more space? 

And those little boxes won't appear--that's just illustrator showing me info about the text boxes. 

![screen shot 2015-05-04 at 1 56 24 pm](https://cloud.githubusercontent.com/assets/11527557/7461139/6308f51a-f265-11e4-803c-dcf407259817.png)

**Comment by emily-phet** [comment]
@mariahmaephet - this looks great. Can there be less space at the bottom?

**Comment by mariahmaephet** [comment]
@emily-phet 

![screen shot 2015-05-04 at 2 46 43 pm](https://cloud.githubusercontent.com/assets/11527557/7463938/2b6e2b50-f27b-11e4-8013-eedbe5e04e7b.png)
![screen shot 2015-05-04 at 2 47 24 pm](https://cloud.githubusercontent.com/assets/11527557/7463941/31453f82-f27b-11e4-95ed-dcadf06e97fe.png)

**Comment by emily-phet** [comment]
Looks great! @mariahmaephet Can you send these to me as jpg files?

**Comment by mariahmaephet** [comment]
@emily-phet I just sent them to you in an email and I can also put them in my folder on Google Drive
