### ISSUE TITLE
Accessibility About Page

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#231]
@aaronsamuel137 - can you update the http://phet.colorado.edu/en/about/accessibility page a little, ideally by May 5th?

Here's what I have in mind:
- Making the "Keyboard Navigation and Auditory Description Prototypes" section more similar to the "Sonification" section (e.g., with a table). Can you make one subheading for this section - "Forces and Motion: Basics (Net Force Screen)", and then include a table like the attached image just below?
![screen shot 2015-04-29 at 1 25 55 pm](https://cloud.githubusercontent.com/assets/5109055/7399637/5edbf374-ee74-11e4-8ee7-7261c333d4ca.png)

**Comment by ariel-phet** [comment]
@aaronsamuel137 - if this is quick (which it looks like), it would be good to squeeze in by the end of the week.

**Comment by aaronsamuel137** [comment]
Sounds good - I'll work on this today.

**Comment by aaronsamuel137** [comment]
Also, it is better to put issues having to do with the website in the website repo instead of tasks in the future. There is a higher chance I will miss issues in tasks since I don't follow it as closely.

**Comment by aaronsamuel137** [comment]
Deployed. Assigning to @emily-phet for review. Feel free to close if it looks good.

**Comment by emily-phet** [comment]
Looks fantastic, thanks!
