### ISSUE TITLE
test concentration sim in data collection wrapper

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#233]
An environment has been set up that wraps PhET's Concentration simulation in an environment that captures users' actions so that they can be played back and evaluated at a later time.  This environment should be tested on multiple platforms to make sure that it appears to run well, and that the activity associated with it can be done with no issues.  Testing this will require a link to the page and a user ID.  These can be obtained here: https://github.com/phetsims/special-ops/issues/4.

The test procedure should be:
+ go to the test matrix spreadsheet, select a row, enter tester initials
+ determine an unused user ID and enter it in the appropriate spot in the test matrix
+ execute the test, either activity testing or sanity testing
   + if activity testing, do the activity described by the PDF sheet available at the start page
   + if sanity testing, just test the general behavior of the sim
+ log the results in the spreadsheet
+ repeat until the spreadsheet is filled

**Comment by ariel-phet** [comment]
@bryo5363 and @orejolaphet please make this your current testing priority

**Comment by ariel-phet** [comment]
@jbphet reports issue can be closed. Closing.
