### ISSUE TITLE
"phet-dev" website testing for HTML5 sim pages deploy

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#236]
@bryo5363 @phet-steele @orejolaphet - we are ready to do final testing on the website to get ready for our HTML5 sim pages rollout. It is expected that full testing will take a couple of days (you guys are always thorough and the hope is deploy this weekend). See below for all the details!

**Testing link: http://phet-dev.colorado.edu/**
(you will likely want to make sure you have done a "hard refresh" the first time you look at these pages, which is Ctrl+Shift+R on windows and Cmnd+Shift+R for macs)

**Test Matrix:**
https://docs.google.com/spreadsheets/d/1Almjl_c4iYCigUUZLXu2_xwK48jOlfrPABxjsZ-4A6Y/edit#gid=2004409462

**Report bugs here:**
https://github.com/phetsims/website/issues

*When hammering on the site, pay attention to these pages that have changed:*

**1. Registering for an account.**

- register for an account
- confirm the email
- check on the profile (edit your profile and save changes)
- make mistakes when registering (such as blank fields, you should get error messages and red boxes highlighting the incorrect fields)
- (any accounts you register will be wiped from the database when deployed to the live site, so your phet gmail would be good to use if you haven't already)

**2. Submitting an activity.**

- submit an activity with a few files
- edit the activity information
- edit the uploaded files

**3. Look at the HTML5 sim pages and legacy sim pages.**

- bounce around between sections and pages
- activities, play video primers, download teacher tips, download translated versions

**4. Sign in from various places on the site.**
- from the banner
- submitting an activity
- commenting on an activity
- playing a video primer

**5. Try all of the above while viewing in different locales (with at least 1 RTL locale)**

**Comment by ariel-phet** [comment]
BTW @bryo5363 @phet-steele and @orejolaphet - when it comes to the website and iPad testing, please only use iPad 2. The iPad3 is helpful for finding performance issues in sims, but it is a very small percentage of devices actually used.

**Comment by bryo5363** [comment]
@ariel-phet I think for the most part this testing is complete. We still need to find a device w/ Win 7 IE 10 but every other browser has been tested on.

**Comment by ariel-phet** [comment]
I believe "phettest" has IE 10 on it? Am I mistaken?

**Comment by bryo5363** [comment]
Which device is phettest? I do not see it on the Asset Inventory.

**Comment by ariel-phet** [comment]
That is the computer that sits on my table that has the asset inventory spreadsheet on it and where you check devices out.

**Comment by bryo5363** [comment]
Ah, that computer runs IE9

**Comment by ariel-phet** [comment]
Ah...well we have removed IE9 as a supported platform, so lets put IE10 on that computer. When you do, check with @oliver-phet - there are some special settings we had to enforce to make sure that the browser did not get updated.

**Comment by ariel-phet** [comment]
Pages deployed! Thanks everyone for all the hard work. Closing.
