### ISSUE TITLE
Create a handle for movable reference line

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#237]
We have a reference line in some sims that has a handle to cue that you can grab and move it. However, it is still not the most intuitive handle and is pretty heavy. Can you mock up a few ideas for a handle that looks grippy/grabbable/movable and less heavy? 

Check out Wave on a String as an example: 
![screen shot 2015-05-13 at 9 39 54 am](https://cloud.githubusercontent.com/assets/7852916/7614445/0e2ec92a-f954-11e4-9e2b-7d999f099c67.png)

**Comment by mariahmaephet** [comment]
@amanda-phet are you thinking something like these? I guess they don't look much lighter though

![screen shot 2015-05-18 at 12 00 19 pm](https://cloud.githubusercontent.com/assets/11527557/7687141/57b8fb76-fd58-11e4-888a-13dd421ce2e4.png)
![screen shot 2015-05-18 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/11527557/7687142/596b88d0-fd58-11e4-82fc-a5720fab212b.png)
![screen shot 2015-05-18 at 12 20 10 pm](https://cloud.githubusercontent.com/assets/11527557/7687143/5c7138ea-fd58-11e4-8b8d-9ed744bf3d3b.png)

**Comment by ariel-phet** [comment]
Hey @mariahmaephet - seems there was a slight miscommunication on our part. The reference line to and "grabber" to which @amanda-phet was referring is this one:

![capture](https://cloud.githubusercontent.com/assets/4051174/7687352/f6d34e4a-fd59-11e4-862b-27b1902305a9.PNG)

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet  Oh! Yeah, you're right, I didn't even notice that. What kind of handle were you thinking? Is it supposed to be holding that line like a rope or something?

**Comment by amanda-phet** [comment]
Yes, the handle is holding the line, but often users might not know that they can grab it and move it around. Something like a hand, or generally grippy handle could work.

**Comment by mariahmaephet** [comment]
@amanda-phet  I just made a bunch of handle things you could use now or later--will one of these work? I uploaded the illustrator file to my Drive folder

![screen shot 2015-05-20 at 1 36 43 pm](https://cloud.githubusercontent.com/assets/11527557/7734777/a788b21a-fef5-11e4-9e6f-6b4944157b44.png)

**Comment by ariel-phet** [comment]
I kind of like the red ring for this one...goes with the line, but definitely seems grabbable

**Comment by amanda-phet** [comment]
I also like the red ring. I'm not sure it needs to be red if the line is red, but maybe the color can change on a sim-by-sim basis? 

I also like the top right rounded handle with the brown wood-like feel.

**Comment by amanda-phet** [comment]
Since we have a number of handle options to choose from I think we can close this issue.
