### ISSUE TITLE
clarify how to run a sim in "PhET Development Overview"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#238]
In several places in the "PhET Development Overview" document, the instructions to run a sim look something like this:

> Open a browser to the path for one of the simulations:  http://localhost:8080/example-sim/example-sim_en.html

At least one user had a problem with this. Here's a posting from the Google Group:

> I am using Windows and followed all the steps given in PhET Development Overview.
When I open any browser to the path : http://localhost:8080/example-sim/example-sim_en.html
The error message on Git bash is - "GET/joist/strings/joist-strings_en.json?bust=1431607520150" Error (404): "Not found"
 
The README.md for published sims is a little clearer about this, for example:

> (3) Open http://localhost/reactants-products-and-leftovers/reactants-products-and-leftovers_en.html (You will probably need to modify this URL based on your HTTP port and relative path.)

The "PhET Development Overview" should be modified to clarify.

**Comment by samreid** [comment]
I'm not opposed to clarifying the path/port, but wanted to point out two things:

(a) if the user followed the directions in the PhET development overview (including using npm+http-server), their port and path would be correct
(b) the purported problem on the Google Group may actually be another problem, see my response:

> It is unclear what Shailaja's problem is.  If it is erroring on "GET/joist/strings/joist-strings_en.json?bust=1431607520150", doesn't that mean that it found the HTML file itself (as a precursor to loading requirejs + joist strings) and hence the port and relative path are correct?  Perhaps there is some downstream error, such as joist not being checked out, or joist not being checked out in the right location?

**Comment by pixelzoom** [comment]
True, it sounds like this user's problem is probably a missing dependency. Let's deal with that in the Google Group.

I didn't read the full instructions in "PhET Development Overview".  Looks like those instructions do result in the correct URL, since they are using a specific path and a specific web server.  So closing this issue.
