### ISSUE TITLE
Update AP computer to IE10

### ISSUE THREAD

**Issue by bryo5363** [phetsims/tasks#239]

**Comment by ariel-phet** [comment]
@orejolaphet - can you take care of this task? This would be to update "phettest" the computer that sits on my table to IE10, however, you might want to talk to @oliver-phet - you need to be careful when you update that it does not automatically update to IE11 with normal windows updates. There is a way to force it to stay on IE10. (currently the computer is on IE9, but that is no longer a supported platform for our project)

**Comment by orejolaphet** [comment]
Bates has been updated with IE 10. Task is complete, closing.
