### ISSUE TITLE
Figuring out number of activity downloads for specific author

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#242]
@jonathanolson - one of our collaborators in Chemistry is hoping to know how many of the activities he authored have been downloaded from our website. @kathy-phet said you have gathered such numbers for @patricialoeblein before, so we would like to do this again for this collaborator and know the steps.

**Comment by jonathanolson** [comment]
This is a bit more time consuming. It would require going through Apache logs for the region in time we're curious about (100s of GB of processing if we need to search through "all time").

It's similiar to manually processing statistics for simulation/installer downloads. An intern may be best suited.

**Comment by oliver-phet** [comment]
I think this old issue can be closed. I occasionally provide GA page views on activities and the new activity interface also provides analytics for authors.
