### ISSUE TITLE
Test Flash Version of Calculus Grapher

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#243]
@orejolaphet and @phet-steele please test the flash version of Calculus Grapher for bugs. We plan to port this sim soon, so it would be good to flesh out any bugs in the original:

http://phet.colorado.edu/sims/calculus-grapher/calculus-grapher_en.html

Please report issues in the calculus grapher repo and assign them to @amanda-phet with the "flash version bug" label

https://github.com/phetsims/calculus-grapher/issues

**Comment by orejolaphet** [comment]
@ariel-phet I believe this task is complete.

**Comment by ariel-phet** [comment]
Excellent, closing
