### ISSUE TITLE
HTML5 sims that need a design doc

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#244]
No Doc yet:

- [x] Forces and Motion Basics
- [x] Fraction Matcher
- [x] Resistance in a Wire
- [x] Ohm's Law

Docs that needs to be brought to a modern standard:
- [x] Balancing act

**Comment by elisemorgan** [comment]
Do you mean Build an Atom instead of Build a Molecule? I can't find an HTML5 version of the Molecule but I did find the Java and HTML5 versions for the Atom. As far as I can tell, Build an Atom does not have an HTML5 design doc.

**Comment by ariel-phet** [comment]
@elisemorgan - yes I did mean Build a Molecule. That is sim is very much on hold, lets discuss what do with that in person.

**Comment by ariel-phet** [comment]
@elisemorgan - it turns out Build a Molecule did have a design doc (just not shared to the group), it should be shared with you now

**Comment by elisemorgan** [comment]
@ariel-phet the five listed above are complete, owned by phethelp, and linked on the master list.

**Comment by ariel-phet** [comment]
excellent @elisemorgan - I am going to leave this issue open since there might be a couple others as I am going through and cleaning things up

**Comment by ariel-phet** [comment]
Closing for the moment
