### ISSUE TITLE
Test all deployed sims for layout issue using "?stringTest=double"

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#245]
We need to test all of our redeployed sims to find problems where strings aren't being scaled and this interferes with the sim.

This will need to be done after pulling all on master go on to the computer called phettest (AP's table) > open gitbash > type "pull-all.sh".

Then testing the latest version on http://phettest.colorado.edu/git-dev/

For example (problem):
![screen shot 2015-05-21 at 12 03 30 pm](https://cloud.githubusercontent.com/assets/5090275/7755460/6e25459e-ffb1-11e4-8547-da00d4bc5152.png)

For example (good):
![screen shot 2015-05-21 at 12 02 35 pm](https://cloud.githubusercontent.com/assets/5090275/7755461/71b5825a-ffb1-11e4-8c55-60df7cba796c.png)

Please report 'X' if the sim is ok with double strings in the spreadsheet below.
If the double strings interferes with the sim, create an issue in the sim repo and paste the issue number in the spreadsheet.

https://docs.google.com/spreadsheets/d/1eBcV1O5o7IyB5Nh_z5iP_0w5tGP1ZVB4uZmBVnIf3q8/edit#gid=1627417351

**Comment by ariel-phet** [comment]
@pixelzoom said


> I reviewed the following sims where I've been primary developer. They all have i18n layout issues, and I've created issues in their respective repositories.
acid-base-solutions
balancing-chemical-equations
beers-law-lab (concentration)
graphing-lines
molarity
ph-scale (ph-scale-basics)
reactants-products-and-leftovers

**Comment by orejolaphet** [comment]
This task has been completed.

**Comment by ariel-phet** [comment]
Excellent, closing

**Comment by pixelzoom** [comment]
Reopening. As identified by @jessegreenberg in https://github.com/phetsims/hookes-law/issues/4, long strings aren't the only problem. Strings that are shorter than the English strings can also result in layout problems.  So sims should also be tested with something like stringText=X.

Assigning to @ariel-phet to decide whether to do another pass of testing, or whether just look for this in sims that have been identified as having problems with long strings.

**Comment by pixelzoom** [comment]
FYI... I've completed i18n layout fixes in all of my sims:

acid-base-solutions
balancing-chemical-equations
beers-law-lab (concentration)
graphing-lines
molarity
ph-scale (ph-scale-basics)
reactants-products-and-leftovers

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @elisemorgan - please test our html5 sims with the query parameter stringText=X (as mentioned by @pixelzoom above) and look for layout issues

I have added a column to the spreadsheet mentioned in this issue, please report issues there, and if a layout issue exists please make an issue in the appropriate sim repo.

**Comment by orejolaphet** [comment]
I reviewed all sims on the spreadsheet for ?stringTest=X and noticed only one issue for energy-skate-park-basics. No major issues arise with very small strings.

**Comment by ariel-phet** [comment]
Excellent @orejolaphet thanks!
