### ISSUE TITLE
identify common-code issues for "Summer 2015" redeploy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#246]
Identify common-code issues that should be addressed for "Summer 2015" redeploy.  Assigned to me at 5/21/15 dev meeting.

**Comment by pixelzoom** [comment]
Developers: I'm triaging common-code issues, setting "Summer 2015 redeploy" label and assigning issues. If you feel that an issue shouldn't be part of the redeploy, or shouldn't be assigned to you, please  comment in the relevant issue.

**Comment by pixelzoom** [comment]
sun: https://github.com/phetsims/sun/labels/Summer%202015%20redeploy

**Comment by pixelzoom** [comment]
Here's the set of all phetsims issues that are labeled "Summer 2015 redeploy":
https://github.com/search?utf8=✓&q=is%3Aopen+label%3A%22Summer+2015+redeploy%22+user%3Aphetsims+

**Comment by pixelzoom** [comment]
I don't have the background to complete this task for scenery, so assigning this subtask to @jonathanolson: https://github.com/phetsims/tasks/issues/250.

**Comment by pixelzoom** [comment]
I can't evaluate kite issues, many are too terse or lacking descriptions. Assigning a subtask to @jonathanolson, see https://github.com/phetsims/kite/issues/46.

**Comment by pixelzoom** [comment]
I completed this task, with the exception of scenery (#250) and kite (#251).

In retrospect, I should have used GitHub milestone instead of labels. Next time...

Here's the set of all phetsims issues that are labeled "Summer 2015 redeploy":
https://github.com/search?utf8=✓&q=is%3Aopen+label%3A%22Summer+2015+redeploy%22+user%3Aphetsims+

Here's the same set by repository:

assert: none
axon: https://github.com/phetsims/axon/labels/Summer%202015%20redeploy
babel: https://github.com/phetsims/babel/labels/Summer%202015%20redeploy
chipper: https://github.com/phetsims/chipper/labels/Summer%202015%20redeploy
dot: none
joist: https://github.com/phetsims/joist/labels/Summer%202015%20redeploy
kite: TBD by @jonathanolson, see #251
nitroglycerin: none
phet-core: none
phetcommon: https://github.com/phetsims/phetcommon/labels/Summer%202015%20redeploy
scenery: TBD by @jonathanolson, see #250
scenery-phet: https://github.com/phetsims/scenery-phet/labels/Summer%202015%20redeploy
sherpa: https://github.com/phetsims/sherpa/labels/Summer%202015%20redeploy
shred: https://github.com/phetsims/shred/labels/Summer%202015%20redeploy
sun: https://github.com/phetsims/sun/labels/Summer%202015%20redeploy
tandem: none
together: https://github.com/phetsims/together/labels/Summer%202015%20redeploy
vegas: https://github.com/phetsims/vegas/labels/Summer%202015%20redeploy
vibe: https://github.com/phetsims/vibe/issues?q=is%3Aopen+label%3A%22Summer+2015+redeploy%22

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet, so he can oversee completion of the issues.

**Comment by pixelzoom** [comment]
Breakdown by developer:

@jbphet 18
https://github.com/issues?q=is%3Aopen+is%3Aissue+assignee%3Ajbphet+label%3A%22Summer+2015+redeploy%22

@jonathanolson 15
https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Ajonathanolson+label%3A%22Summer+2015+redeploy%22+

@pixelzoom 5
https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Apixelzoom+label%3A%22Summer+2015+redeploy%22+

@jessegreenberg 4
https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Ajessegreenberg++label%3A%22Summer+2015+redeploy%22+

@aaronsamuel137 2
https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Aaaronsamuel137++label%3A%22Summer+2015+redeploy%22+

@samreid 0
https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Asamreid+label%3A%22Summer+2015+redeploy%22+

**Comment by jonathanolson** [comment]
Currently reviewing Scenery/Kite for issues, I'll note here when I'm done.

**Comment by jonathanolson** [comment]
Added tag to relevant issues. Depending on performance issues during testing, some of the other Scenery high-priority issues might be added to the list.

**Comment by ariel-phet** [comment]
Since we are now redeploying sims this issue can be closed
