### ISSUE TITLE
Find the number of open issues for every published sim

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#247]
We need a count of all of the open issues on a deployed sim basis. Add the number to this spreadsheet:
https://docs.google.com/spreadsheets/d/1eBcV1O5o7IyB5Nh_z5iP_0w5tGP1ZVB4uZmBVnIf3q8/edit#gid=1627417351

**Comment by phet-steele** [comment]
I went ahead and did this.

**Comment by phet-steele** [comment]
I should add, it was done at 11:51 AM, 5/22
