### ISSUE TITLE
[joist] test "Screenshot" feature

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#25]
Testing candidates are at http://www.colorado.edu/physics/phet/dev/olsonjb/scenery-0.2-unoptimized-tests-4/.

Please pick a sim or two and test the "Screenshot" feature here across all platforms. Expected behavior:

1. Pressing the "Screenshot" item in the PhET Menu should trigger either a download of a screenshot or open it in a new tab. If it opens in a new tab, it should be possible to download it (long-press on iPad I think?)
2. The downloaded screenshot should look identical to the state the sim was in. There may be slight differences due to anti-aliasing changes (it uses Canvas, while many things use SVG), so I don't expect it to be a pixel-perfect replica.

If there are difficulties downloading the screenshot, please create an issue.

Additionally, if you could pick one platform (Win8/Chrome or whatever is most convenient / working the best) and verify that screenshots for all sims look like the sim's state when it was taken, that would be great! Ideally, for each screen that is unique, make everything visible that is possible, take a screenshot, and compare.

Issues should be created in Joist.

Thanks!

**Comment by pixelzoom** [comment]
@ariel-phet Since scenery/joist 0.2 has been moved to master, this feature is now enabled, and will be included in any published sims. So perhaps the priority of testing should be raised.

**Comment by ariel-phet** [comment]
@pixelzoom could you close #24 and #25, and write a more appropriate testing task for each and assign to me for prioritization? Perhaps choose several sims that are 0.2 and you think we be good test cases to put these features through paces?

**Comment by pixelzoom** [comment]
@ariel-phet Can you clarify what you mean by "a more appropriate testing task", and why this task isn't sufficient as written? @jonathanolson's instructions appear to be quite clear.  And since I'm not familiar with this feature, so I don't have anything to add.  I suggested raising the priority because I was surprised when these features (#24 and #25) became publicly visible.

**Comment by pixelzoom** [comment]
@ariel, can you please review this? We need to keep this issue moving forward, since screenshot is now included in all sims, is untested, and apparently is not supported for IE9 (https://github.com/phetsims/joist/issues/212).

**Comment by pixelzoom** [comment]
I'll go out on a limb here and increase the priority to high. There are sims that will ship with this feature "soon",  Eg, Molecule Shapes is about to go into dev testing.  And there are probably others (Molecules and Light, Neuron, ...) that are close.

**Comment by ariel-phet** [comment]
@pixelzoom do you know if the screenshot functionality can be set as an option currently? My thinking is we want to have this not visible to users in any sims we publish until we have done more testing/refinement. I believe also right now the screenshot functionality lives in the PhET menu, we may want to have some discussion around whether that is actually where we should have it or not - could be a very large discussion.

**Comment by pixelzoom** [comment]
@ariel-phet This (and fullscreen) were optional features until we moved to scenery 0.2.  At that point that were made non-optional for some reason.  I was surprised to see that, asked about it, and was assigned to do cleanup (see https://github.com/phetsims/joist/issues/206).  So I'm not psyched to spend my time putting this option back in.

**Comment by pixelzoom** [comment]
I'll handle restoring the query parameter to make this optional, https://github.com/phetsims/joist/issues/213.

**Comment by pixelzoom** [comment]
This feature is now off by default (see phetsims/joist#213). When testing is completed, please create an issue to make it "on" by default.

Restoring priority to low.

**Comment by pixelzoom** [comment]
To make the "Screenshot" menu item visible in the PhET menu, run a sim with "screenshot" query parameter.

**Comment by pixelzoom** [comment]
This issue was accidentally closed, reopening.

**Comment by pixelzoom** [comment]
Note that screenshot is not supported on IE, see https://github.com/phetsims/joist/issues/212. Do we want to test this feature before addressing that issue?

**Comment by jonathanolson** [comment]
I just successfully took a screenshot on IE11 (with ?screenshot), do you mean a specific version?

**Comment by pixelzoom** [comment]
IE9, as noted in phetsims/joist#212.

**Comment by pixelzoom** [comment]
According to @jonathanolson, the current screenshot implementation with not work with sims that use WebGL.  There is some additional work required.  So perhaps we should defer this testing until that work is done?

**Comment by pixelzoom** [comment]
https://github.com/phetsims/joist/issues/237 (make screenshot work for WebGL) is a prerequisite for this testing.

**Comment by ariel-phet** [comment]
Closing this issue for the moment, until making screenshot functionality work with WebGL becomes a priority.
