### ISSUE TITLE
Update sim info content, starting with credits

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#253]
@phet-steele Please make this your top priority today. Each HTML5 sim has credits that can be found under About... 
![screen shot 2015-05-26 at 10 14 55 am](https://cloud.githubusercontent.com/assets/7852916/7817147/111f5d70-0390-11e5-9cb4-ff6f0e0c8aa1.png)

Please transfer this information to the new HTML5 sim pages by logging in as an administrator. I can show you how to do this. 

Track your progress using [this spreadsheet] (https://drive.google.com/open?id=19v98MXCCbfXF6gKOOtoTQ6jNvrGxHb02yKzzwD3BALQ&authuser=0).

**Comment by phet-steele** [comment]
Credits are done, with the exception of Build an Atom, Friction, and Molecules & Light. phetsims/website/issues/205

**Comment by phet-steele** [comment]
If I get the go ahead on crediting third-party libraries, I will. This would take awhile, though.

**Comment by amanda-phet** [comment]
Thanks, @phet-steele ! 

Moving on to sim topics and learning goals. We will use the same spreadsheet to record when the topics and learning goals have been reviewed and updated (if applicable).

**Comment by amanda-phet** [comment]
Making a new issue for the other content. Closing.
