### ISSUE TITLE
Camtasia for Mac file -> MP4 file export

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#254]
I need 11 Camtasia for Mac (*.camproj) files converted to MP4 files (or some movie format that is cross-platform compatible). This needs to be done as soon as possible to allow Argenta access to these data sets.

The Camtasia files are located in the following directories on phetbackup:
Individual/College Individual/2014_05_13_SOM_MolPol_Dev5_C2_F_KG_EM
Individual/College Individual/2014_05_13_SOM_PhotoElec_U2_F_HP_EM
Individual/K12 Individual/2011_03_22_SOM_G6_M_AS_EM
Individual/K12 Individual/2011_03_24_SOM_G7_M_GB_EM
Individual/K12 Individual/2011_04_06_SOM_EFH_G7_F_MG_EM
Individual/K12 Individual/2011_04_18_SOM_BAM_G4_M_EG_EM
Individual/K12 Individual/2011_04_19_SOM_FAM_EFH_G4_F_AW_EM
Individual/K12 Individual/2011_04_22_SOM_EFH_BAM_G6_M_JD_EM
Individual/K12 Individual/2011_10_11_SOMB_MolShap_Mag_G5_M_KR_EM
Individual/K12 Individual/2011_10_11_SOMB_MolShap_Mag_G6_M_JK_EM
Individual/K12 Individual/2011_10_17_SOMB_MolShap_BL_G7_F_AV_EM

I believe Oliver had figured out previously settings for high quality exporting...

**Comment by ariel-phet** [comment]
Hey @orejolaphet - can you hop on this conversion? 

Probably the best thing to do for downloading the files off phetbackup is to plug in to the ethernet right on my desk, that will give the fastest connection.

**Comment by orejolaphet** [comment]
Yeah, I can get that done!

**Comment by orejolaphet** [comment]
@emily-phet I went through every folder and noticed in each there already exists a " .MPG " video file which is cross compatible. I did see folders with a " .cmproj " extension, but these aren't Camtasia files. I suppose I'm confused, exactly what files I am to convert?

**Comment by emily-phet** [comment]
@orejolaphet - Here's a screen shot of one of the directories:
![screen shot 2015-05-27 at 11 05 18 am](https://cloud.githubusercontent.com/assets/5109055/7842471/77f369a8-0460-11e5-8f91-fa2b5a319ebc.png)

It's the *.cmproj file that needs to be converted. Are you opening this file with Camtasia for Mac? You'll need to use the Mac version of Camtasia to open the file and convert it. Let me know if this helps.

**Comment by orejolaphet** [comment]
Oh ok, I was using a windows computer earlier. That clears everything up. I'm currently downloading the files, thanks.

**Comment by emily-phet** [comment]
@orejolaphet - I just tried to open the Camtasia cmproj file in folder Individual/K12 Individual/2011_03_24_SOM_G7_M_GB_EM. It seemed to open just fine (I'm using Camtasia v2 on my Mac). Is this one of the files that you weren't able to open?

**Comment by emily-phet** [comment]
@orejolaphet - can you send me an update of how the files are progressing? I don't see any completed files yet, even in the newer directories. Thanks!

**Comment by orejolaphet** [comment]
@emily-phet The videos I was able to convert to .mp4 include:
Individual/K12 Individual/2011_10_11_SOMB_MolShap_Mag_G5_M_KR_EM
Individual/K12 Individual/2011_10_11_SOMB_MolShap_Mag_G6_M_JK_EM
Individual/K12 Individual/2011_10_17_SOMB_MolShap_BL_G7_F_AV_EM
Individual/College Individual/2014_05_13_SOM_MolPol_Dev5_C2_F_KG_EM
Individual/College Individual/2014_05_13_SOM_PhotoElec_U2_F_HP_EM

And yes, all the files from 2011_03 to 2011_04 (6 videos) I was not able to open on my version of Camtasia 2 Version 2.10.0 (91708)

I'm currently adding all of the videos I was able to convert to their respective directories in phetbackup

**Comment by orejolaphet** [comment]
@emily-phet so it turns out phetback has 31.3 MB of available space, definitely not enough space for these video files. How do you want me to transfer the converted videos that I do have?

**Comment by emily-phet** [comment]
Thanks @orejolaphet - can you start a Google Drive folder and upload them there for now. Share this folder with me and Argenta. I'll email you the appropriate email addresses.

**Comment by orejolaphet** [comment]
@emily-phet Ok, I'm currently uploading to a google drive folder.

**Comment by emily-phet** [comment]
Thanks @orejolaphet - it's so odd that converting some files turned into so much trouble... thanks for chugging along on this. I'll see what I can figure out about the files not opening on Camtasia.

**Comment by orejolaphet** [comment]
@emily-phet No problem! Also, the folder has been shared.

**Comment by ariel-phet** [comment]
@emily-phet - can this task be closed?

**Comment by emily-phet** [comment]
@ariel-phet - unfortunately no, we still haven't figured out how to convert the older Camtasia files. They won't open on version of Camtasia Oliver O. was using.

**Comment by orejolaphet** [comment]
@emily-phet - I added the remaining 6 files to the google drive folder I shared with you previously. All 11 videos have been converted to .mp4 format. 

Closing
