### ISSUE TITLE
Test sims with games for issues with sound on iPad 2

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#255]
@phet-steele this should be a quick task, please complete at your earliest convenience

This task is related to https://github.com/phetsims/vegas/issues/32

please test the following sims on iPad2 with iOS 8 (even though the orginal issues were reported with iOS7, if everything is fine with iOS8 it will not be worth investigating further) Just note if sound works. For any sims with an issue please note the sims in https://github.com/phetsims/vegas/issues/32

- [x] Area builder
- [x] Balancing act
- [x] Balancing chemical equations
- [x] Build an atom
- [x] Fraction matcher
- [x] Graphing lines
- [x] Reactants products and leftovers

**Comment by phet-steele** [comment]
Tested the live version of all these with Tycho. Everything was fine.
