### ISSUE TITLE
revise support for branding

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#256]
Branding is currently spread out across multiple GitHub accounts, multiple repositories and multiple branches. This makes is cumbersome to use, difficult to refactor, etc. 

First steps:

1. Identify the various brands (and their repos/branches) that currently exist.
2. Discuss what additional brands are (or may be) needed.

Requirements for the new approach:

1. Optionally specify a brand at build time.
2. Default to "PhET brand" for PhET developers.
3. Make it difficult (impossible?) for non-PhET organization to use the PhET brand.
4. Make it easy to refactor code in all brands.
5. All repositories owned by the phetsims GitHub account

**Comment by pixelzoom** [comment]
@ariel-phet @jonathanolson @samreid @jbphet Are there any additional requirements?

**Comment by pixelzoom** [comment]
Here are the repositories and branches involved:

https://github.com/phetsims/brand
  master
  adapted-from-phet

https://github.com/phetbrand/brand
    master
    together

The branches are not documented, so I don't know what they are for. I will create issues to document the branches.

**Comment by jonathanolson** [comment]
Depends a lot on how hard we would want to make it to put PhET branding on (if you aren't on the PhET team). If we support custom brands, remember users could replace their logo with the PhET logo, etc. to make it appear as a PhET sim, so I'd personally wouldn't worry too much about how easy it would be to switch to PhET branding (checking for existence of a file?)

Also, people may "publish" sims as the require.js non-built directory, so we'd presumably want the PhET brand to only show up when running a sim with require.js if a condition is met? Existence of a file would also work here, like loading a script that all PhET team members have (git ignored) in brand that does something like ```phet.joist.brand.isPhet = true```, and the build process would also check for it.

That would at least allow phet/adapted/custom in master. I'm not sure of the requirements of together's branding.

**Comment by samreid** [comment]
One goal I'd like to have for branding: everything should be in a single repository in master.  Globals or preload files or other logic chooses between different brands.  Changing repos or branches to test different brandings is too cumbersome.

**Comment by jbphet** [comment]
Perhaps we could encrypt the brand resources (such as the logo) that we want to use only for PhET and require a key to be in the local chipper directory.  This would be somewhat similar to what was done for jar signing back in JavaVille. If no key it defaults to 'adapted-from-phet' or unbranded, and we could have build options to select between these.

**Comment by pixelzoom** [comment]
@samreid wrote:
> One goal I'd like to have for branding: everything should be in a single repository in master. Globals or preload files or other logic chooses between different brands. Changing repos or branches to test different brandings is too cumbersome.

Agreed, everything in 1 repo is the way to go. Perhaps subdirs for various brand options. And I was thinking of something like $HOME/.phet/build-preferences.json to specify which brand option to use.  Still ruminating on ways to prevent unauthorized usage of the PhET brand.

**Comment by pixelzoom** [comment]
Another thought about Brand.js.  It's currently a template that looks like this:

```js
return {
    name: '',//For example: My Company
    copyright: '',//For example: Copyright © 2014, My Company
    links: [
      {
        text: '', //For example "My Company Support"
        url: ''
      } //For example, https://www.mycompany.com/support
    ],
    adaptedFromPhET: false
  };
```

Why not use JSON?  And since this is the only thing in the brand repository, does brand need to be a repository?

**Comment by samreid** [comment]
> does brand need to be a repository?

Where else could/should it go?  We need to decide for the following brands: phet, adapted from phet, custom.

**Comment by pixelzoom** [comment]
Email sent to all PhET developers:

As a baby step towards revising support for branding (https://github.com/phetsims/tasks/issues/256) ... 

(Note the difference between ‘phetsims’ and ‘phetbrand’ in this email.)

The repository phetbrand/brand is deprecated and will be deleted in the near future. 
All brands now live in phetsims/brand, with the following branches:

master: empty brand
phet: regular PhET sims
interoperable: interoperable PhET sims
adapted-from-phet: "Adapted from PhET” sims

Please do the following:

1. Delete your working copy of phetbrand/brand.
2. Check out the ‘phet’ branch of phetsims/brand.

Ariel, please inform any non-developers who may be using phetbrand/brand. 

All: Do any 3rd-party developers need to be notified?

**Comment by pixelzoom** [comment]
TODO: 
• Delete phetbrand/brand repo
• Discuss deleting phetbrand GitHub account

**Comment by pixelzoom** [comment]
phetbrand/brand/README.md now indicates that it's deprecated, and refers to phetsims/brand.

**Comment by samreid** [comment]
Today we discussed using build-local.json to specify brand for the build process and query parameters for selecting brand for requirejs mode.  We would move all brand branches to master.

**Comment by pixelzoom** [comment]
@samreid Has been doing a lot of work related to this issue.  So assigning to him to determine what (if anything) in this issue is not covered by some other open/closed issue.

**Comment by samreid** [comment]
I'm aggregating comments from above that are not addressed elsewhere:

> Make it difficult (impossible?) for non-PhET organization to use the PhET brand.

We decided to make this public.

> Perhaps we could encrypt the brand resources (such as the logo) that we want to use only for PhET and require a key to be in the local chipper directory. 

We decided against this.

> Why not use JSON?

We added some functions in there for dynamically generating the links.

> And since this is the only thing in the brand repository, does brand need to be a repository?

It seems like brand is a good place to encapsulate this.

> TODO: Delete phetbrand/brand repo
> TODO: Discuss deleting phetbrand GitHub account

see https://github.com/phetbrand/brand/issues/2 and https://github.com/phetbrand/brand/issues/3

I think that's everything.  Closing.
