### ISSUE TITLE
Test "Full Screen" functionality using molecule-shapes 1.01.-dev.1 [joist]

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#258]
@bryo5363 @orejolaphet @phet-steele please make this task your current top testing priority.

We would like to thoroughly test full screen functionality to see if it is appropriate to provide in all sims. As a test bed @jonathanolson has published a fresh version of molecule shapes that has full screen enabled by default (if available in the browser). Test as you would a release candidate, as we want to see if the fullscreen mode is introducing any problems, so make sure to go into the about dialog and such.

**Note**
Even though you will be testing molecule shapes, please report any weirdness in the joist repo
https://github.com/phetsims/joist/issues

**Testing Link**
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.1-dev.1/molecule-shapes_en.html

**Test matrix**
https://docs.google.com/spreadsheets/d/1wfA1SVvOKK-d26ozNNeGDuuq5OtUpInGcEkfK_Eqvgg

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet @phet-steele @elisemorgan I am setting this task back to the top priority with finishing off pendulum lab testing as a close second

**Comment by orejolaphet** [comment]
Is the full screen function require webGL? Internet Explorer 10 does not support webGL, and the option for "Full Screen" is not available under the PhET menu.

**Comment by jonathanolson** [comment]
They are unrelated, IE10 independently does not support WebGL and the full-screen API.

**Comment by bryo5363** [comment]
The matrix seems to be complete.

**Comment by ariel-phet** [comment]
Thanks, closing
