### ISSUE TITLE
Dev Test Bending Light 1.0.0-dev.3

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#259]
@bryo5363 @phet-steele @orejolaphet @elisemorgan please make this your current top testing priority.

Please review the opened issues in the Bending LIght repo before testing

**Platforms**
- [x] Windows + Chrome
- [x] Mac + Safari
- [x] iPad2 iOS8

**Testing Link**
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html

**Comment by bryo5363** [comment]
Mac and Safari testing is complete. Will continue on Windows. So far I have not noticed any issues w/ Windows that differ from the Mac

**Comment by ariel-phet** [comment]
@bryo5363 - thanks for the update, and good to hear

**Comment by ariel-phet** [comment]
@bryo5363 @phet-steele @orejolaphet @elisemorgan lets get this testing finished off today (Monday) if possible

**Comment by ariel-phet** [comment]
Dev testing complete, closing
