### ISSUE TITLE
Organize shared google docs

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#260]
Using the phethelp google account, organize google docs in to folders so that we can easily share folders of docs rather than individual ones.

**Comment by ariel-phet** [comment]
@elisemorgan can you go into the following google doc and fill in the Sim Design table with links for any google docs with which you are shared?

https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit

Some of these documents will not exist yet, or will not be shared with the google group yet (which is part of what we want to find out). Generally it should be pretty easy to find stuff. For instance if you search for a sim name and "test matrix" the test matrix should come up in the search if you are shared on it.

When you are finished with this issue, please assign it back to me. Thanks!

**Comment by elisemorgan** [comment]
Hey Ariel,
Some of the results I'm getting are dev docs and some are testing matrices,
is there a preference for which I should link to?
Elise

**Comment by elisemorgan** [comment]
I can also compile the dev docs and testing matrices together now and link
to that. I'll start doing that unless you say other wise.
Elise

**Comment by ariel-phet** [comment]
@phet-steele here is the issue for organizing google docs. The first priority is the published sim table.

To organize everything into folders you will need to be signed into the phethelp@gmail account, see the Area Builder example. Let me know as you have questions.

**Comment by ariel-phet** [comment]
Unassigning until we sort out https://github.com/phetsims/tasks/issues/505

**Comment by ariel-phet** [comment]
Can be closed since we have an organizational system now.
