### ISSUE TITLE
Update sim info content- topics and learning goals

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#261]
For any sims you have claimed (or have been claimed for you @ycarpenterphet ), review the Topics and Learning Goals on the current HTML5 sim page. If they look appropriate, keep them. If they need updating, log in as an administrator and make the necessary changes. After it is reviewed and/or updated, check it off using [this spreadsheet] (https://docs.google.com/spreadsheets/d/19v98MXCCbfXF6gKOOtoTQ6jNvrGxHb02yKzzwD3BALQ/edit#). 
@ariel-phet @oliver-phet @arouinfar

**Comment by ariel-phet** [comment]
My assigned topics and learning goals have all been reviewed

**Comment by arouinfar** [comment]
I've also finished reviewing/updating the topics and learning goals for the sims assigned to me.

**Comment by ycarpenterphet** [comment]
Mine are done as well - looks like the spreadsheet is complete. Tagging @amanda-phet to double-check and close this issue if no sims are remaining.

**Comment by amanda-phet** [comment]
Thanks everyone! Closing.

p.s. It's never too late to write a teacher tips document!
