### ISSUE TITLE
Do some multi-platform testing on beaker together.6

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#262]
We are delivering a bundle (i.e. sim plus demos) of the beaker simulation to a customer.  As of this writing, there has been no multi-platform testing - all testing has been done on Win7 and Chrome-latest.  It would be good to test this on some other platforms and make sure there are no major issues.  Major issues would include anything that prevents the simulation from being used, like failures to load, crashes, or misconfigurations.

Platforms should include:
- [x] Win7+, IE11
- [ ] Win7+, IE10
- [x] Win7+, Firefox latest
- [x] OSX, Safari
- [x] OSX, Chrome
- [x] OSX, Firefox
- [x] iOS8, Mobile Safari

**Comment by jbphet** [comment]
I'm intentionally not providing a link since this is a public repo.  Link available here: https://github.com/phetsims/beaker/issues/57#issuecomment-108571675.

**Comment by jbphet** [comment]
Assigning to @ariel-phet, but @phet-steele is already starting work on this.

**Comment by jbphet** [comment]
Please log versions of OS and browser used for this testing.

**Comment by jbphet** [comment]
The basic approach should be to test all the links in the links file and verify that they load, look reasonable, and behave as intended.  Each link is labeled with a brief description of what the sim should look/behave like.

**Comment by ariel-phet** [comment]
@phet-steele this can be your top priority, but the testing team top priority as a whole should currently be Bending Light

**Comment by jbphet** [comment]
Assigning to @arnabp to get a bit more coverage before we need to send this out.

**Comment by arnabp** [comment]
When using the "Simulation with Logging Enabled" on Firefox on OSX, with the web console open, framerate while running a trial drops to about 5 fps and becomes very choppy.

**Comment by jbphet** [comment]
Thanks @arnabp and @phet-steele - the testing you've done should be sufficient.  Closing.
