### ISSUE TITLE
[pendulum-lab] Test 1.0.0-dev.4

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#263]
Testing matrix: https://docs.google.com/spreadsheets/d/1otMWjgj2jCQHYhp_LebfnNk9H475fhxhw-cPjj_lp2g/edit#gid=2

Link: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html

Assigning to @ariel-phet.

**Comment by ariel-phet** [comment]
@bryo5363 @phet-steele @orejolaphet @elisemorgan some more testing work, but currently lower priority

**Comment by ariel-phet** [comment]
Since this testing is almost complete, lets making finishing off this testing matrix the current top QA priority

**Comment by orejolaphet** [comment]
@ariel-phet all major platforms have been tested for pendulum lab 1.0.0-dev.4

**Comment by ariel-phet** [comment]
Excellent thanks!
