### ISSUE TITLE
Test Joist #137

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#264]
This issue needs to be tested: https://github.com/phetsims/joist/issues/137

**Comment by ariel-phet** [comment]
Hey @bryo5363 - this seems like a quick test...can you try this in the near future

**Comment by bryo5363** [comment]
Should I test on iPad 2?

**Comment by ariel-phet** [comment]
Yes, iPad 2, iOS8

**Comment by bryo5363** [comment]
This issue is no longer present. Closing
