### ISSUE TITLE
Clipping Video Footage

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#265]
I have some video footage that needs some clips pulled over the next two weeks and also some organizational work. Elise is familiar with the footage setting (Tim's classroom) now, does she have some time she could put towards this? It's probably about 10 hours of work.

**Comment by elisemorgan** [comment]
I have time and can get started as soon as this weekend, just send me the details.

**Comment by ariel-phet** [comment]
@elisemorgan - please count this work towards your billable hours

**Comment by emily-phet** [comment]
@elisemorgan  

The first thing you'll want to do is access phetbackup (I'll email you details), and download the video footage you'll be working with. This will take awhile...

**Comment by ariel-phet** [comment]
@elisemorgan - can you comment on the progress of this task?

**Comment by elisemorgan** [comment]
@ariel-phet The files are converted and I started clipping them yesterday.
I'll keep working on them this weekend.

**Comment by elisemorgan** [comment]
@emily-phet is this ready to be closed?

**Comment by emily-phet** [comment]
Yes, great work @elisemorgan !

**Comment by emily-phet** [comment]
@elisemorgan - there are just a few more details here. Thought it might be easier to track than random emails if I just reopened this issue.

- Please add the timepoints to the spreadsheet regarding the "typo" that you originally found. We'll just go ahead and roll with that one.

- Can you please clip one new segment from the videos - the point where Tim asks students to start using their sim, and the next ~30 seconds after that (with students exploring the sim for the first time). Also, put these time points in the spreadsheet.
