### ISSUE TITLE
Poster Design

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#266]
I'll need to 2-3 posters designed as part of a conference proceeding submission due June 25th. I'll be able to have some mockups to start from around June 15th. Will Mariah have time to work on this?

**Comment by amanda-phet** [comment]
I know she is out of town for a good chunk of the summer and working intermittently. 

@mariahmaephet Can you comment on whether you'd be available mid-late July to work on this?

**Comment by mariahmaephet** [comment]
@amanda-phet @emily-phet For sure! The only time I will not be available is June 30-July 9

**Comment by amanda-phet** [comment]
Assigning to @emily-phet to coordinate with @mariahmaephet .

**Comment by emily-phet** [comment]
@mariahmaephet - I have the manuscript drafted that is associated with the first poster. I'll mockup something for you to start the poster with today or tomorrow. The poster will need to be a max of 3 feet wide x 4 feet high (though a bit smaller is good). I'm thinking that the ACS poster structure from last March (with the sim image in the center) would work well - though I think the color palette needs to be a bit more subtle. 

Would you be available to meet on-campus some time this week? I'll be on campus Tuesday @11:30, and Thursday @ 9:30 or 11:30am). Do any of these times work for you?

**Comment by mariahmaephet** [comment]
@emily-phet I'm actually on the road this summer! I'm working from coffee shops along the west coast so I'm not able to meet in person. If you don't think emails are enough we can set up phone/skype calls?

**Comment by emily-phet** [comment]
@mariahmaephet - Ahh, I see. Sounds like fun! The deadline got extended for this, so I still haven't quite gotten some of the content finished. How about this - can you take the ACS poster from this past March and come up with a few different color schemes (something that looks a bit less bright/childlike)? The sim that will be focused on is the first screen of Forces and Motion: Basics - so something that is complementary to that sim would be nice. I'll keep working on the content...

**Comment by ariel-phet** [comment]
looks like this is a duplicate issue of #299 closing

**Comment by emily-phet** [comment]
@ariel-phet - unfortunately, this is not a duplicate. These posters never got made. Not sure what happened. Turns out I didn't need to submit them with the manuscripts (unlike its sister CHI conference) but if accepted I will need to have these completed.

**Comment by mariahmaephet** [comment]
@emily-phet let me know

**Comment by emily-phet** [comment]
I met with Dave Underwood to discuss designing a template for PhET posters that are more on the slick/promotional end of the poster spectrum. He's planning to a draft something up.

**Comment by emily-phet** [comment]
@daveunderwood - I'll need to have a finished poster printed on October 21st. Do you think you'll have time to work on a template this week?

**Comment by emily-phet** [comment]
@daveunderwood - I found a cool magazine layout that could be adapted into a nice template.
<img width="1290" alt="screen shot 2015-10-12 at 11 52 08 am" src="https://cloud.githubusercontent.com/assets/5109055/10434729/91b8d186-70d8-11e5-9aef-2e165d9a277d.png">
 
I'm imagining the upper right area could have images/graphs layed out in an aesthetically pleasing way, with each labeled by a number that corresponds to the associated text column below. What do you think?

**Comment by emily-phet** [comment]
@daveunderwood - note, poster dimensions for my upcoming poster are a max of 3 feet wide x 4 feet high. Anything inside that will work.

**Comment by emily-phet** [comment]
I made an Powerpoint Presentation that contains the content for the poster. If @daveunderwood has time to work on a template this week, perhaps @mariahmaephet could add the content starting early next week? Would that work?
[ASSETS-Poster-Draft.pptx](https://github.com/phetsims/tasks/files/11992/ASSETS-Poster-Draft.pptx)

**Comment by daveunderwood** [comment]
Hey Emily, I think this will be a piece of cake. I'm thrilled that you're looking for inspiration in editorial layout. Very cool!! I'm off until Wednesday, then we'll hit it hard. And if we pull a useful template out of this, even better! D

**Comment by daveunderwood** [comment]
See if this looks okay. I'm dropping in two versions - a PPt and a jpg - to avoid machine-to-machine discrepancies w/ fonts. It should look like the jpg, which specs w/ Calibri and Times. Thanks, D
[FROM_DAVE.pptx](https://github.com/phetsims/tasks/files/13415/FROM_DAVE.pptx)
![slide1](https://cloud.githubusercontent.com/assets/13662881/10491766/81e7dc82-7265-11e5-97e7-8e73c839f384.jpg)

**Comment by emily-phet** [comment]
@daveunderwood - I'm shifting from email to here, for tracking. I'm not sure if you're working today or not...perhaps @mariahmaephet can pick up from here?
Here are a list of tweaks that will be needed to finalize the specific version that needs to be printed by mid-day Wednesday.

- Change in headers: Header 1: "Interactive Simulations", Header 2: "Goals", Header 3: Progress, Header 4 could be changed to just "Opportunities" if that looks much better than "Challenges & Opportunities", Header 5 can stay the same. I think these tell a better story.
- Text content: I have attached an updated powerpoint that has the correct text for the five columns of content. 
[ASSETS-Poster-Draft.pptx](https://github.com/phetsims/tasks/files/16183/ASSETS-Poster-Draft.pptx)

Images along bottom:
- First should be the attached bar chart: 
![emily_plot_prism](https://cloud.githubusercontent.com/assets/5109055/10584651/7bfff798-7650-11e5-83a9-ecec7bca9c96.jpg)
Caption: PhET simulation runs (online runs and downloads) from 2004-2014.
- Second should be an image of students using a sim - maybe this one:
[StudentPic.pptx](https://github.com/phetsims/tasks/files/16192/StudentPic.pptx)
If you have a better one, throw it in. It just needs to have multiple students in the pic, preferably working together (rather than one kid per sim...I like to indicate that collaboration is a goal with sims).
Caption: Students collaborating with PhET Interactive Simulation in a college chemistry class.
- Third, an Image of Forces and Motion: Basics. (Caption: Forces and Motion: Basics PhET simulation.) If there's room for a fourth, then Radiating Charge (Caption: Radiating Charge PhET simulation).

Left side panel:
I think it might work to put a short abstract here:

"Abstract
Interactive simulations are becoming increasingly important in education, but these tools are not accessible to many learners. Here, we share our goals in the development of accessible simulations, summarize early progress, and highlight opportunities for the ASSETS community. We hope to interest readers in participating in the growing community designing, developing, and researching accessible interactive simulations for learning."

I think that's it! Let me know if I've missed something, and more content is needed.

**Comment by ariel-phet** [comment]
@emily-phet not sure if you will have @daveunderwood or @mariahmaephet time before Wednesday...feel free to ask @amyh-phet to help you finish off this task

**Comment by amyh-phet** [comment]
@emily-phet 
Let me know if I can help.

**Comment by emily-phet** [comment]
@amyh-phet - if you have time to start implementing the changes I listed above, please go for it. My hope is that it won't take long - all of the structure is already in place if you can access @daveunderwood original files.

**Comment by amyh-phet** [comment]
@emily-phet   working on implementing changes now.

**Comment by amyh-phet** [comment]
@emily-phet   Just wanted to check on poster dimensions.  3 foot wide, 4 foot high is the maximum but smaller is okay?  The current poster mock up looks to be 28 inches by 21 inches.   I would like to make it a bit larger (32 inches by 43 in would be the maximum but I can try to keep it smaller).   This would allow us to include larger graphs/pictures at the bottom of the poster.

**Comment by amyh-phet** [comment]
@emily-phet    Sorry - maximum sizes would be 32 inches wide by 25 inches high.

**Comment by amyh-phet** [comment]
@emily-phet  Sorry - maximum dimensions would be  31 inches wide by 24 inches high.

**Comment by emily-phet** [comment]
@amyh-phet - the max dimension would be great. Were you imagining scaling it (for example, exporting to pdf and just setting the printed size from there) or trying to alter the powerpoint layout options to increase the size?

**Comment by amyh-phet** [comment]
@emily-phet   Just checking on  max size - 3 foot wide x 4 foot high?   This would produce a portrait style layout rather than landscape.   I'm attaching a copy of the file which  I can easily size to fit a maximum size of 4 foot wide x 3 foot high (landscape orientation).  

Let me know what else needs to be done for the poster.
[ASSETS_Poster_Draft_10_18_15.pptx](https://github.com/phetsims/tasks/files/16375/ASSETS_Poster_Draft_10_18_15.pptx)

**Comment by emily-phet** [comment]
@amyh-phet - Sorry, I think I was unclear. I meant to say that the max size you suggested (still in landscape) would be great. I'm not that picky for this one, so essentially if it's relatively easy for you to take what Dave did and make it slightly bigger (still with same ratios and landscape) that would be fine. If it's a lot of trouble, Dave's ppt sizing will also work.

**Comment by amyh-phet** [comment]
@emily-phet   I did alter the layout a bit in powerpoint to increase size.   The file I sent is for a poster that is 31 inches wide by 24 inches high.  Will that work?

**Comment by daveunderwood** [comment]
I can help today also. I just sent Emily three JPG variations on the poster theme that add a little punch. It may be a bit late for this project, but I'd like to head toward a template that can help in the future. See what you think. Also, if you want, I'd be happy to re-do the bar chart so that it's a bit more sophisticated. Just say the word and let me know which color(s) you've decided on. 

The three variations:
 
![text](https://cloud.githubusercontent.com/assets/13662881/10610973/5443caba-7707-11e5-86cb-28948b79adf3.jpg)

![bar](https://cloud.githubusercontent.com/assets/13662881/10610984/6388cbb0-7707-11e5-9e5a-96d31f601968.jpg)

![picture](https://cloud.githubusercontent.com/assets/13662881/10610993/699598f8-7707-11e5-99f2-e41fb25c278b.jpg)

**Comment by emily-phet** [comment]
@amyh-phet had started making some progress on finalizing this yesterday. @amyh-phet, I think I actually like the layout in the original sizing a touch better (not sure what feels different about the new one), so I think I'm fine going with the original, smaller size. 

@daveunderwood - I like the one with the picture, and I believe we have some pictures with students standing and pointing to a projected sim, which might fit the space better. Would there be some way to fade this into the background, so you still have the feeling of a classroom/student space, but can also put a bit of content there?
For the poster that needs to be printed tomorrow, it would be great if there could just be a touch of color (so maybe adding the color panel to that version). If you have time to update the look of the bar chart, that would be great, too.

@amyh-phet - could you send Dave a version of the poster with the original dimensions but the updated content?

**Comment by mariahmaephet** [comment]
@emily-phet Hey Emily--sorry I didn't see this until now. I was getting emails but I only saw Dave's name so I didn't read through them. Let me know if there's anything I can do today to help out

**Comment by amyh-phet** [comment]
@emily-phet  and @daveunderwood  attached is a version of poster with original dimensions and updated content (abstract and new graphics included)  

Let me know if you need me for anything else.
[FROM_DAVE_UPDATED_CONTENT.pptx](https://github.com/phetsims/tasks/files/16901/FROM_DAVE_UPDATED_CONTENT.pptx)

**Comment by daveunderwood** [comment]
Here's the little graph if it helps. I've color-matched it, and tightened it up a bit. Also, for higher-end stuff, I always like rotating axis labels to be more easily read. See what you think.

[sim_runs.pdf](https://github.com/phetsims/tasks/files/16951/sim_runs.pdf)

**Comment by emily-phet** [comment]
@daveunderwood - the graph looks wonderful! Would you have time today to add the following to the file from Amy above (with the updated content):
- add your new beautiful graph
- replace the student image (the center image) with this one (I like this one a bit more because the sim looks more central and active)
[StudentPic.pptx](https://github.com/phetsims/tasks/files/16982/StudentPic.pptx)
- If possible, include a screenshot of Radiating Charge as a fourth image (https://phet.colorado.edu/sims/radiating-charge/radiating-charge_en.html) - if you select "Circular" it will make a cool symmetric charge pattern. 
- Add the color panel to the top. 

I'm hoping you might be able to see if having four images across the bottom works, and you might like a different color for the top based on what happens with the four images on the bottom.

**Comment by emily-phet** [comment]
@amyh-phet or @mariahmaephet - Can either of you take a stab at the changes I suggested just above some time today?

**Comment by amyh-phet** [comment]
@emily-phet   I can work on this and get a version back to you this afternoon for review.   Is this what you were thinking for the Radiating Charge image?
![radiating_charge_circular_001](https://cloud.githubusercontent.com/assets/13650180/10620674/a4f751f2-7739-11e5-99f0-bd9f209ea478.png)

**Comment by emily-phet** [comment]
Thanks @amyh-phet! The screenshot looks great. That's such a cool looking sim. 

I hope you're feeling better this afternoon.

**Comment by amyh-phet** [comment]
@emily-phet    Just want to make sure I'm on the right track.  For the color panel on the top, you are referring to the second poster above with the blue panel behind the title?

Thanks - I am feeling better - mostly just didn't want to spread a cough and scratchy voice to the rest of the team, especially Amy R. who is stuck in the office with me.

**Comment by emily-phet** [comment]
@amyh-phet Glad you're feeling better.

Yes, you're exactly right. I like the color panel Dave suggested above, so if you could give that a shot I think it would a bit of depth to the poster.

**Comment by amyh-phet** [comment]
@emily-phet   I will get this back to you as soon as possible so you have time to review and request changes if needed.

**Comment by amyh-phet** [comment]
@emily-phet   Attached are two possible options for the poster.   Let me know of changes to make.  One has a blue color panel as in Dave's mock up above and one has a red color panel to match the bars on your graph at the bottom of the poster.    I'm happy to make changes as needed.   I'll be away from my computer for a few hours but can work on this after 6 pm tonight if needed.
[ASSETS_Poster_Draft_10_20_15_blue.pptx](https://github.com/phetsims/tasks/files/17185/ASSETS_Poster_Draft_10_20_15_blue.pptx)
[ASSETS_Poster_Draft_10_20_15_red.pptx](https://github.com/phetsims/tasks/files/17186/ASSETS_Poster_Draft_10_20_15_red.pptx)

**Comment by amyh-phet** [comment]
@emily-phet    In looking over the poster files tonight, I realized I had not changed the outlines of the box around the title.   Attached are new files with the outline on the color panel removed.

[ASSETS_Poster_Draft_10_20_15_blue.pptx](https://github.com/phetsims/tasks/files/17260/ASSETS_Poster_Draft_10_20_15_blue.pptx)
[ASSETS_Poster_Draft_10_20_15_red.pptx](https://github.com/phetsims/tasks/files/17261/ASSETS_Poster_Draft_10_20_15_red.pptx)

**Comment by amyh-phet** [comment]
@emily-phet    In looking over the poster files tonight, I realized I had not changed the outlines of the box around the title.   Attached are new files with the outline on the color panel removed.

[ASSETS_Poster_Draft_10_20_15_blue.pptx](https://github.com/phetsims/tasks/files/17759/ASSETS_Poster_Draft_10_20_15_blue.pptx)
[ASSETS_Poster_Draft_10_20_15_red.pptx](https://github.com/phetsims/tasks/files/17760/ASSETS_Poster_Draft_10_20_15_red.pptx)

**Comment by ariel-phet** [comment]
Looks done. Closing
