### ISSUE TITLE
Upgrade Copernicus to OSX 10.9

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/tasks#267]
We are planning to reserve the laptop Copernicus for video recording and production tasks, since it works well with the the modmic - this way, anyone needing to record a primer video can borrow the mic and laptop as a pair, and @schasteen can edit the final production videos there.

However, Camtasia will not work with OSX 10.8, which is the current OS, and Adobe Premiere (which we have a licensed copy of on this laptop and need for production) does not say it will work with the latest version of OSX (10.10).

So, please upgrade only as far as Mavericks (10.9), according to...

> if you have a machine that already downloaded Mavericks back in the day, you could use that to 
> download the item from your previous purchases and then use a flash drive to create a bootable
> installer (option 1, here: http://www.macworld.com/article/2056561/how-to-make-a-bootable-mavericks-install-drive.html)

<b>If it looks like this will require a clean install, please back up the laptop first</b> (since we're not 100% sure if we can even re-download Adobe Premiere anymore outside of a CC subscription).

Assigning @ariel-phet to prioritize and assign the most appropriate person for the task. We'd prefer to get this done asap, so that the computer will be available for recording primers as needed.

**Comment by ariel-phet** [comment]
Hey @arnabp - please get this done as soon as your time allows

**Comment by arnabp** [comment]
10.9 has now been installed on Copernicus!

**Comment by ariel-phet** [comment]
@ycarpenterphet - please verify if this upgrade solves your issues

**Comment by ycarpenterphet** [comment]
Looks great. Thanks @arnabp
