### ISSUE TITLE
Create some "PhET + Data" logo treatments

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#268]
Hey @mariahmaephet, @kathy-phet has requested that we explore some possibilities for agumenting our logo. Currently we are building in capabilities for our simulations to be able to collect data about user interactions to allow researchers and such to better understand the paths through which students use our sims.

For sims that have this capability activated we want to augment our logo. We are thinking something that conveys "PhET + Data". The idea would be not to change anything about our logo but add the word "Data" - perhaps overlayed in some clear fashion or to the right hand side somewhere with a "+" symbol preceding the logo. Such a treatment would appear in our sims, so it would have to work on a small scale. 

(The word "interoperable" has also been suggested, since that is the correct lingo, but it is a very long word to try to augment with our logo, and @amanda-phet has commented that since it is not a common usage word, she always reads it as "inoperable" which would be a very negative message to send!).

So for now, can we just try a bunch of different treatments that include the word "data" - I think the first pass should be pretty quick and dirty, just try some different things so we can get a feel of what might be a good direction, and we can refine from there.

In terms of artwork, please make this task your current top priority. Thanks!

**Comment by ariel-phet** [comment]
Tagging as related to https://github.com/phetsims/brand/issues/4

**Comment by samreid** [comment]
I'm interested to see what @mariahmaephet comes up with based on the above descriptions but wanted to add in 2¢ for discussion with @ariel-phet.  I am somewhat concerned that "data" misses out on the interoperable part of this feature set--many may think data just means that the sim is producing data.   The features we provide are the following:

* configuring the sim on startup (using query parameters)
* dynamic interoperability across iframe API (sending commands, receiving data, screenshots, etc.)
* event stream (for research)
* save/load
* record & playback

So this leads me to two suggestions for the logo:

1. Perhaps use the word "io" instead of "data", signifying "input/output", which is somewhat like interoperable but without the disadvantage @amanda-phet mentioned above.  On the other hand, is "io" really part of the lexicon of our target population for this?  Not sure.
2. Perhaps incorporate into the logo: an arrow coming into the word PhET and an arrow going of the word PhET to signify the input and output to some external system.  (One caveat here though: we would want to make sure that if the logo contains arrows they do not conflate with any arrows in the simulations).

@mariahmaephet please do not proceed with the above suggestions without hearing from @ariel-phet first--I haven't been in the loop on these discussions and I don't know how firm plans for "data" are, or if others will like the suggestions (or variants) above.

**Comment by samreid** [comment]
If we are thinking prospective clients will be primarily interested in the data output features, then perhaps calling it "PhET data" may be perfect--I don't know how heavily we wanted to market the configurable/controllable/interoperable angle.

**Comment by mariahmaephet** [comment]
@ariel-phet @samreid   Is this close to what you were thinking? And what's the best way for me to show you these? I thought I'd just collage them for now... 

also, do you want the 'university of colorado' parts included at the bottom, or just  'phet + ?'

![screen shot 2015-06-10 at 12 14 12 pm](https://cloud.githubusercontent.com/assets/11527557/8091696/493a0a26-0f6a-11e5-8a00-816a4cd546c6.png)

**Comment by ariel-phet** [comment]
@mariahmaephet I think this is a great way to display them, and gives us some good discussion ideas. 

Could you take all the ones with "data" to the right of the phet logo and also try incorporating a "+" symbol? No need to have any CU branding.

**Comment by mariahmaephet** [comment]
@ariel-phet 

![screen shot 2015-06-11 at 8 54 58 am](https://cloud.githubusercontent.com/assets/11527557/8111682/0ff04902-1018-11e5-988b-0db6c89d270b.png)
![screen shot 2015-06-11 at 8 55 21 am](https://cloud.githubusercontent.com/assets/11527557/8111684/110344a2-1018-11e5-8af4-ff46928a7aa0.png)
![screen shot 2015-06-11 at 8 58 02 am](https://cloud.githubusercontent.com/assets/11527557/8111687/15c69ab6-1018-11e5-90fc-7503ccc010cc.png)

**Comment by samreid** [comment]
I think another valuable step for us to effectively evaluate these proposed logos would be to see them in context.  @mariahmaephet Can you mock up one or two of your favorites in the context of a sim?

**Comment by amanda-phet** [comment]
You can find our mockup skeleton under PhET Ai Files > Design Assets > Homescreen Mockup.

**Comment by mariahmaephet** [comment]
@samreid @ariel-phet @amanda-phet   I think I'm set on keeping the addition that same greenish yellow

![screen shot 2015-06-11 at 10 32 32 am](https://cloud.githubusercontent.com/assets/11527557/8113994/83bb6fde-1026-11e5-9d6a-146f85893c69.png)
![screen shot 2015-06-11 at 10 33 23 am](https://cloud.githubusercontent.com/assets/11527557/8113995/859df7f4-1026-11e5-9d59-30ee39721f4c.png)
![screen shot 2015-06-11 at 10 33 41 am](https://cloud.githubusercontent.com/assets/11527557/8113998/89217e82-1026-11e5-9765-5abdee491c69.png)
![screen shot 2015-06-11 at 10 35 54 am](https://cloud.githubusercontent.com/assets/11527557/8114000/8c032a10-1026-11e5-80de-914d7b04d8cf.png)
![screen shot 2015-06-11 at 10 37 06 am](https://cloud.githubusercontent.com/assets/11527557/8114002/8deb9902-1026-11e5-8088-f3a5bbc1b2a8.png)
![screen shot 2015-06-11 at 10 39 33 am](https://cloud.githubusercontent.com/assets/11527557/8114007/91e91ca0-1026-11e5-8828-62e09ed43e77.png)
![screen shot 2015-06-11 at 10 40 12 am](https://cloud.githubusercontent.com/assets/11527557/8114009/93fd450c-1026-11e5-8b88-fad8a00eb5cb.png)
![screen shot 2015-06-11 at 10 41 16 am](https://cloud.githubusercontent.com/assets/11527557/8114012/9671ba20-1026-11e5-9887-0d8629f4e955.png)

**Comment by ariel-phet** [comment]
Thanks @mariahmaephet - we will look at these with @kathy-phet and then give some feedback!

**Comment by ariel-phet** [comment]
@mariahmaephet - can you paste that "PhET io" rough draft you had in this issue?

**Comment by mariahmaephet** [comment]
@ariel-phet I think the second one is what you had drawn for me? The others are just ideas if you wanted to play around with it more. I'll fix the O for the final drafts

<img width="622" alt="screen shot 2015-08-07 at 11 20 15 am" src="https://cloud.githubusercontent.com/assets/11527557/9141488/5da3c68c-3cf6-11e5-8490-1f1a10c700cb.png">
<img width="631" alt="screen shot 2015-08-07 at 11 20 21 am" src="https://cloud.githubusercontent.com/assets/11527557/9141490/5da9e558-3cf6-11e5-9918-64825f30898f.png">
<img width="599" alt="screen shot 2015-08-07 at 11 20 28 am" src="https://cloud.githubusercontent.com/assets/11527557/9141491/5db10b9e-3cf6-11e5-85fa-6aaf71fd1f11.png">
<img width="590" alt="screen shot 2015-08-07 at 11 20 33 am" src="https://cloud.githubusercontent.com/assets/11527557/9141489/5da95fc0-3cf6-11e5-9227-be5cc8aa93e2.png">

**Comment by ariel-phet** [comment]
@mariahmaephet - I am actually going assign this to @daveunderwood so those drafts are good enough for discussions. Thanks! Some cool ideas there.

**Comment by ariel-phet** [comment]
moved discussion to #308  now that we have decided on "PhET io" closing
