### ISSUE TITLE
Test iOS 9

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#269]
@arnabp Can you put iOS 9 on Tycho and start to perform some testing? ESPB, Molecule Shapes, Balancing Act, RPAL.

**Comment by oliver-phet** [comment]
@arnabp Also, test the scenery unit test: http://phetsims.github.io/scenery/tests/qunit/unit-tests.html

**Comment by oliver-phet** [comment]
Actually use this link: http://phettest.colorado.edu/git-dev/scenery/tests/qunit/unit-tests.html

**Comment by arnabp** [comment]
![img_0004](https://cloud.githubusercontent.com/assets/8583364/8140850/eaf7106c-111c-11e5-9856-9d53d4fe1410.jpg)
![img_0003](https://cloud.githubusercontent.com/assets/8583364/8140852/eafa2180-111c-11e5-9884-6411a59b5487.jpg)
![img_0001](https://cloud.githubusercontent.com/assets/8583364/8140848/eaf5f876-111c-11e5-8284-ea43f8dc20f1.jpg)
![img_0002](https://cloud.githubusercontent.com/assets/8583364/8140849/eaf6d4f8-111c-11e5-8ca0-d2ad861d44d1.jpg)
![img_0005](https://cloud.githubusercontent.com/assets/8583364/8140851/eaf7a2ac-111c-11e5-992e-66f27a38991e.jpg)
![screen shot 2015-06-12 at 3 45 31 pm](https://cloud.githubusercontent.com/assets/8583364/8140847/eaed29b2-111c-11e5-9cbc-ca87351ffdf1.png)

These are screenshots from running the scenery test on iOS 9 on the iPad. Most of the time, it would be stuck on the first image for a few seconds, then autorefresh the page and keep getting the error until it reached the second image. But I was able to get the other screens to show up occasionally before. The last image is also the error console I was able to get using Safari.

**Comment by samreid** [comment]
Tagging @jonathanolson since this should be on his radar.

**Comment by jonathanolson** [comment]
This is mostly looking like it's failing trying to download all the many hundreds of files necessary, except for the "checked" failure, which looks like a bug on my part of when the unit tests are attempted to be hidden.

Did it work when not tethered (which might slow things down?)

**Comment by arnabp** [comment]
No, the scenery test could never complete regardless of if it was tethered.

**Comment by jonathanolson** [comment]
Can you try http://phetsims.github.io/scenery/tests/qunit/compiled-unit-tests.html, as it doesn't load a ton of files?

**Comment by arnabp** [comment]
Unforunately, this test wasn't much different. The iPad auto-refreshed a few times before giving up. Here's a screenshot I was able to capture between refreshes:
![img_0006](https://cloud.githubusercontent.com/assets/8583364/8170577/e4a47b24-136e-11e5-9a1c-cde44469f700.jpg)

**Comment by jonathanolson** [comment]
Any clue if OS X 11 is needed to debug with a tether for this?

**Comment by arnabp** [comment]
No, anything from Mountain Lion Safari and up has the "Safari Web Inspector"

**Comment by jonathanolson** [comment]
I'd like to test this in-person to try to see what I can do with the console to debug.

**Comment by jonathanolson** [comment]
I'm not concerned about the unit tests failing, but I noticed this is a more general issue so I won't close this for now. Feel free to close if the unit tests are the only things blocking closure.

**Comment by oliver-phet** [comment]
When I was testing some audio using Balancing Act, @jonathanolson noticed a layout bug when the iOS 9 iPad was rotated between portrait and landscape:
![image1](https://cloud.githubusercontent.com/assets/5090275/8608279/7ec87544-2656-11e5-989d-b503790fce58.PNG)
![image2](https://cloud.githubusercontent.com/assets/5090275/8608277/7ec50e40-2656-11e5-9314-06f1e016060e.PNG)
![image3](https://cloud.githubusercontent.com/assets/5090275/8608278/7ec6a9d0-2656-11e5-8c6d-079444faa8ae.PNG)

**Comment by ariel-phet** [comment]
@jonathanolson - it seems this testing is generally complete, do you want to move the found issues to appropriate tickets in appropriate repos?

**Comment by jonathanolson** [comment]
I moved out https://github.com/phetsims/joist/issues/280, the unit-tests on iPad I probably wouldn't create an issue for.

If testing for this is complete, should it be closed?

**Comment by ariel-phet** [comment]
Sounds good, lets close.
