### ISSUE TITLE
Test OSX 10.11

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#270]
@arnabp Go ahead and put 10.11 on your computer and start taking a look at some sims: ESPB, Molecule Shapes, Balancing Act, RPAL.

**Comment by oliver-phet** [comment]
@arnabp Also, test the scenery unit test: http://phetsims.github.io/scenery/tests/qunit/unit-tests.html

**Comment by oliver-phet** [comment]
Actually use this link: http://phettest.colorado.edu/git-dev/scenery/tests/qunit/unit-tests.html

**Comment by arnabp** [comment]
Safari passed with no issues, Chrome failed on 3 issues (just like previous OSs: Opacity and Blending (canvas), Simple clipping (dom), Nested Node/Fill/Stroke Opacity (canvas))

**Comment by arnabp** [comment]
https://github.com/phetsims/molecule-shapes/issues/125

**Comment by pixelzoom** [comment]
OS X 10.11 will be publicly available on 9/30, and we're about to resume re-publication of sim, so we should wrap this up. 

phetsims/molecule-shapes#125 is closed, fixed on all platforms.  

@arnabp is there anything else to do here?

**Comment by pixelzoom** [comment]
@ariel-phet Can you please comment on whether this issue should be closed before resuming RC testing? If it's not necessary, then please remove the "Summer 2015 redeploy" label. If it is necessary, please escalate.

**Comment by arnabp** [comment]
Probably our biggest issue depends on how much we want to make sure our sims scale with having windows be in large vertical and small horizontal configurations, as this may become more prevalent with the split screen feature. Besides that I didn't notice anything that demanded immediate attention.

**Comment by ariel-phet** [comment]
@jonathanolson reports this was a very sim specific bug related to 3D scaling. Seems like not issue, closing.
