### ISSUE TITLE
Update Java requirements to be current

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#272]
@arnabp Can you update the text on our http://phet.colorado.edu/en/faqs System Requirements to basically be the Java system req's with 2 changes: 256 MB Ram, and remove the processor requirement.
http://java.com/en/download/help/sysreq.xml

**Comment by arnabp** [comment]
<b>Windows</b>
Windows 8
Windows 7
Windows Vista
RAM: 256 MB
Approximately 518 MB available disk space (for full installation)
Browsers: Internet Explorer 9 and above, Firefox, Chrome

<b>Mac OS X</b>
Intel-based Mac running Mac OS X 10.8.3+, 10.9+
Administrator privileges for installation
A 64-bit browser (Safari, Firefox, or Chrome for example) is required to run Oracle Java on Mac OS X. 

<b>Linux</b>
Oracle Linux 5.5+1
Oracle Linux 6.x (32-bit), 6.x (64-bit)2
Oracle Linux 7.x (64-bit)2
Red Hat Enterprise Linux 5.5+1, 6.x (32-bit), 6.x (64-bit)2
Ubuntu Linux 12.04 LTS, 13.x
Suse Linux Enterprise Server 10 SP2+, 11.x
Browsers: Firefox

**Comment by oliver-phet** [comment]
@aaronsamuel137 @zepumph Here is the updated Java/Flash sys req's for this page: http://phet.colorado.edu/en/faqs#q2-header
Also, add "Approximately 518 MB available disk space (for full installation)" to both Mac OS X and Linux

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph

**Comment by zepumph** [comment]
For the disk space section for the big installer, right now the available disk space is being dynamically loaded based on how big the installation actually is. @oliver-phet  would you like me to just hard code in 518MB? Or keep it dynamic?

**Comment by oliver-phet** [comment]
Oh I didn’t realize that - keep it dynamic.
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Jul 1, 2015, at 9:29 AM, Michael Kauzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


For the disk space section for the big installer, right now the available disk space is being dynamically loaded based on how big the installation actually is. @oliver-phet<https://github.com/oliver-phet> would you like me to just hard code in 518MB? Or keep it dynamic?

**Comment by zepumph** [comment]
Changes are up on phet-dev if you want to take a look at them.

**Comment by oliver-phet** [comment]
@zepumph Looks good. This should be ready to go live when you can get to it.

**Comment by aaronsamuel137** [comment]
Deployed to figaro. Closing
