### ISSUE TITLE
test installer made with httrack 3.48 for missing files

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#276]
The installers were recently found to be missing files, see https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3696 for details.  The problem seems to have been narrowed down to a bug in HTTrack, so I had OIT upgrade to the latest version and have re-run the installer builder.  Initial indications are promising - no missing files were seen in the rip.  I could use some help testing the installers.  Please download and test the Windows installers with and without activities (links below), testing the following for each:
+ Installation succeeds
+ Run the attached bash script and note whether any JNLP files are missing (log the output in this issue)
+ Test the installation for a while, following links in diverse places, noting any occurrences of missing files

For all tests please *uninstall any previous version and remove the PhET subdirectory in the Program Files (x86) directory!!*.

Version without activities: http://www.colorado.edu/physics/phet/dev/installer-testing/PhET-Installer_windows.exe.
Version with activites: http://www.colorado.edu/physics/phet/dev/installer-testing/PhET-Installer-with-activities_windows.exe

**Comment by jbphet** [comment]
Script for testing whether any JNLP files are missing - paste this into a text file (e.g. list-mising-jnlp-files.sh), put the file into the root directory of the PhET installation, and run it.  It may be necessary to modify permissions with the command ```chmod +x```.

```sh
#!/bin/sh

#############################################################################
# Script for analyzing a rip of the PhET web site and listing any missing
# JNLP files.  The list of files that SHOULD be present is determined by
# analyzing the sim pages.  That list is then tested agains the JNLP files in
# the sims directory.
#
# This is highly dependent on the structure of the web site, so it may not
# work if that structure has changed.
#
# This scrip was created in early June 2015 to help solve this issue:
# https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3696.
#############################################################################

# Change the following path var to use this script in different places
WEB_RIP_ROOT=.

# Use the legacy directory if it exists.  This depends on when the rip 
# occurred.  Before May 28 2015 it didn't exist, after that it did.
if [ -e $WEB_RIP_ROOT/en/simulation/legacy ]; then
  pathToSimPages=$WEB_RIP_ROOT/en/simulation/legacy;
else
  pathToSimPages=$WEB_RIP_ROOT/en/simulation;
fi

# Create a list of the JNLP files linked from the HTML files that define the "sim pages".
jnlpLinks=( $( grep "_.*\.jnlp" $pathToSimPages/*.html | grep -v textarea | sed -e 's/^.*\/sims\///' -e 's/jnlp.*$/jnlp/' | uniq | sort ) );

# Temp for testing
echo ${jnlpLinks[@]} > temp.txt;

# Test for missing JNLP files
count=0
for fileName in "${jnlpLinks[@]}"
do
  fileName=$WEB_RIP_ROOT/sims/$fileName
  if [ ! -e $fileName ]; then 
    echo $fileName ": file does not exist"; 
    let "count += 1";
  fi
done

echo "Number of missing JNLP files = "$count;
```

**Comment by jbphet** [comment]
Assigning to @ariel-phet, but @phet-steele is already working on it.

**Comment by phet-steele** [comment]
1. This issue is already known: the link to the version without activities still contains activity pages. The activities themselves, however, are not reachable and just lead to a file not found. An example location of a file not found on the Scaling Shapes Activity and Lesson activity, on Area Builder:

/C:/Program Files (x86)/PhET/services/download-servletb101.html?filename=/4015/Scaling_LessonPlan.pdf

2. A question really: the link to Share Your Activities doesn't work, but the words are still there why? It makes sense to me that you can't log in on the installer, and this link is trying to cause the sign in window to pop up.

3. Last but not least, neither had missing JNLP files!

**Comment by phet-steele** [comment]
Been resolved for awhile, according to @jbphet.
