### ISSUE TITLE
Test Charges-And-Fields Release Candidate 1.0.0-rc.1

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#277]
OK a release candidate was published here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/

And the test matrix is here: https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=2

Aside from the test matrix (linked above), please run the following tests:

This sim is somewhat unusual in the sense that it has multiple modes (one non webgl and two webgl modes):
* test a few platforms with ?webgl=false
* on tablets, test a change of orientation from portrait to landscape etc. check for responsiveness
* test a few platforms where you resize the window of the browser.
* on webgl mode, make sure to open several random tabs and switch from the sim tab to the tother tabs, verify that you dont lose the context...  
Thanks!

Reassigning to @ariel-phet to prioritize and reassign.

**Comment by ariel-phet** [comment]
Thanks @bereaphysics - can you also please transfer ownership of the testing matrix to phethelp?

**Comment by ariel-phet** [comment]
@elisemorgan @phet-steele @bryo5363 @orejolaphet please test this sim and in addition to the test matrix comment on the bullet point tasks @bereaphysics outlined above.

**Comment by bereaphysics** [comment]
phethelp is now owner.

**Comment by ariel-phet** [comment]
bumping to top testing priority now that Pendulum lab testing is finished.

**Comment by bryo5363** [comment]
The major platforms are nearly complete. We just need an official report on Wn 8 IE 11. @phet-steele could you verify that the sim works on this platform?

**Comment by elisemorgan** [comment]
@bryo5363 I just tried to open the sim on Win 8.1 IE 11 and it was unsuccessful

**Comment by bereaphysics** [comment]
We will need to issue a new release candidate because so many platforms could not render the sim because of the math.log10 command. It has been replaced by a polyfill and all the platforms should work on the next release candidate.

**Comment by ariel-phet** [comment]
@bereaphysics - sounds good, I will close this issue, please create another RC when ready, and create a new testing issue
