### ISSUE TITLE
Create icon that messages "interactivity" 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#278]
Hey @mariahmaephet - we are going to have a website that is "co-branded" with another company and one of the icons they have associated with our project should message "interactivity".

Since the website is not yet public. you can find the link in this private repo

https://github.com/phetsims/special-ops/issues/7

As you can see, they are using orange icons that are all from "font awesome" - we would like to keep the same style but ideally have a custom icon that connotes interactivity or motion. Perhaps the beaker is fine but maybe a beaker that is bubbling a bit? Or a beaker that is tilted down and pouring out, or one beaker pouring into another. So I think ideally the two words that would come to mind when looking at the icon are "science" and "action/motion". If you have a better idea than a beaker, that is great too, and feel free to try a couple of ideas and be creative :).

**Comment by mariahmaephet** [comment]
@ariel-phet Are these sort of what you were imagining?

![screen shot 2015-06-30 at 2 44 21 pm](https://cloud.githubusercontent.com/assets/11527557/8442891/cb3b7ff6-1f36-11e5-804b-3c3a2763d408.png)
![screen shot 2015-06-30 at 2 40 56 pm](https://cloud.githubusercontent.com/assets/11527557/8442895/cee07008-1f36-11e5-9b1d-3bf5c5cc7470.png)
![screen shot 2015-06-30 at 2 28 47 pm](https://cloud.githubusercontent.com/assets/11527557/8442897/d5a98564-1f36-11e5-8b4d-10ac584f53e5.png)
![screen shot 2015-06-30 at 2 47 55 pm](https://cloud.githubusercontent.com/assets/11527557/8442925/046551e4-1f37-11e5-818a-57d39ef08804.png)

**Comment by mariahmaephet** [comment]
@ariel-phet 

![screen shot 2015-06-30 at 2 52 41 pm](https://cloud.githubusercontent.com/assets/11527557/8443052/157d5570-1f38-11e5-9c16-aa8ac7f78a42.png)
![screen shot 2015-06-30 at 2 54 50 pm](https://cloud.githubusercontent.com/assets/11527557/8443053/157e1af0-1f38-11e5-9892-a57b9776a5a7.png)

**Comment by mariahmaephet** [comment]
@ariel-phet so you can see them smaller 

![screen shot 2015-06-30 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/11527557/8443095/88d67808-1f38-11e5-98be-f99d3ad17bfa.png)

**Comment by amanda-phet** [comment]
I like the top left of the orange set, personally!

**Comment by ariel-phet** [comment]
@mariahmaephet - yes, these were very much what I was thinking!

@amanda-phet - can you get @kathy-phet to take a look at these (and I agree with your choice @amanda-phet )

**Comment by amanda-phet** [comment]
@kathy-phet agrees that the top-left orange icon looks best. However, she perceived the bubbles as spilled chemicals. @mariahmaephet can you mockup that one up with the same open-circle bubbles as the icon just to the right? When that's finished I think you can just put the .ai file in the drive folder and I'll send it to Kathy. Thanks!

**Comment by ariel-phet** [comment]
@mariahmaephet - any progress on the changes above?

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet 

like this?

<img width="475" alt="screen shot 2015-07-13 at 4 15 04 pm" src="https://cloud.githubusercontent.com/assets/11527557/8662156/6e13a364-297a-11e5-93b2-7e5b566efbd7.png">

**Comment by amanda-phet** [comment]
Yes that is perfect. Can you put that icon in a file in google drive?

**Comment by mariahmaephet** [comment]
@amanda-phet done! (finalbeaker.ai)

**Comment by amanda-phet** [comment]
Awesome. Kathy just saw it and approves. Closing.
