### ISSUE TITLE
Test release candidate 2 for charges and fields

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#279]
A new release candidate was published here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.2/

And the test matrix is here: https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=2

The main focus of this release candidate is to check the performance on the (numerous)  platforms that did not run last time so check that they are  indeed running.
These included
- Mac OS X 10.8.5	Safari 6.2
- iPad 2	iOS 7 + Safari 
- Win 7 and Win 8 with	IE10 (latest) andI E11 (latest)

There are a number of issues that were logged for the release candidate 1 that have not been addressed yet. That will be done for release candidate number 3. 
 
Reassigning to @ariel-phet to prioritize and reassign.

**Comment by ariel-phet** [comment]
@bryo5363 @elisemorgan @orejolaphet @phet-steele please make this your top testing priority

**Comment by orejolaphet** [comment]
Simulation opens for Win 7 with IE 10 & IE 11 and Win 8 with IE 11

**Comment by orejolaphet** [comment]
Simulation opens on iPad 2 iOS 7 + Safari

**Comment by bereaphysics** [comment]
I think I got all the information I needed from this release candidate. So the sim opens but we have some performance issue on some platforms. @orejolaphet: I don't have access to most of the troublesome platforms. I'll contact you next week. Please send me your Skype handle by email

**Comment by orejolaphet** [comment]
@bereaphysics I won't have access to a computer from this afternoon to Sunday night as I will be camping in Wyoming. I will be in the office on monday.

**Comment by bereaphysics** [comment]
Issuing a new release candidate. Closing
