### ISSUE TITLE
bad copyright in LICENSE?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#280]
Here's the copyright in the LICENSE file for all PhET common-code repos (e.g., phetsims/scenery/LICENSE):

`Copyright (c) 2014 University of Colorado Boulder`

Here's the copyright in phetsims/brand/LICENSE (all branches):

`Copyright (c) 2014 phetsims`

Why is brand different? Should it be the same as other repos?

**Comment by pixelzoom** [comment]
@sam you created the brand repo. Do you have an insight into why this is different?

**Comment by samreid** [comment]
It is just an old stale bug, we should fix this in all brand branches.  Not sure how copyrights are supposed to work for files intended to be forked, but we should standardize the copyright statements for these files for now.

**Comment by pixelzoom** [comment]
Fixed in all branches. Closing.
