### ISSUE TITLE
Test release candidate 3 for charges and fields

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/tasks#281]
A new release candidate was published here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.3/

And the test matrix is here: https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=2

The main change  in this release candidate is the use of canvasNode to render the electric field arrows. This should hopefully addressed the most pressing concerns, https://github.com/phetsims/charges-and-fields/issues/47, 
 with regards to performance issues with the iPad as well as the other platforms..  

In addition beware of issues 

https://github.com/phetsims/charges-and-fields/issues/44
https://github.com/phetsims/charges-and-fields/issues/45
https://github.com/phetsims/charges-and-fields/issues/46

It is not necessary to set webgl=false for this release candidate.

Comment and/ or close the issues if your concerns have been addressed.

Reassigning to @ariel-phet to prioritize and reassign.

**Comment by bereaphysics** [comment]
Also, I'm punting on issues 
https://github.com/phetsims/charges-and-fields/issues/48
https://github.com/phetsims/charges-and-fields/issues/49
since both are  corner cases that are minor annoyances.
In addition, I don't have easily access to a touch device, and even i did 
i would not know how to start tackling them.

https://github.com/phetsims/charges-and-fields/issues/49 should be logged as a scenery issue

**Comment by ariel-phet** [comment]
@elisemorgan @orejolaphet @bryo5363 please make this sim your top testing priority

**Comment by elisemorgan** [comment]
@ariel-phet RC 3 has been retested on all platforms

**Comment by ariel-phet** [comment]
@elisemorgan - I am a bit confused, when I look at the test matrix, RC3 is not completely filled out.

It looks like the link Martin gave above takes you the test matrix with the RC1 sheet open.

Here is the direct link

https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=576424251

Did some entries for RC3 accidentally get put on the RC1 sheet?

**Comment by elisemorgan** [comment]
@ariel-phet Yes, my apologies that is exactly what happened. I'll update the rc3 sheet

**Comment by ariel-phet** [comment]
Thanks, closing testing task
