### ISSUE TITLE
Create a draft of a Linux troubleshooting entry for installer

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#282]
@arnabp Can you draft up a Linux troubleshooting entry about chmod, and modeunattended using the ticket: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3681

**Comment by arnabp** [comment]
1 - Download package.
2 - Open the console/terminal.
3 - Navigate to the folder where the download is.
4 - Give your system permissions to execute the file:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> chmod 777 PhET-Installer_linux.bin
5 - Run the installer:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> ./PhET-Installer_linux.bin 
5.1 - If you still do not have permissions use:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> sudo ./PhET-Installer_linux.bin
5.2 - If you get the error of a "segmentation fault":
<a>&#160;&#160;&#160;&#160;&#160;</a>>> ./PhET-Installer_linux.bin --mode text 
<a>&#160;&#160;&#160;&#160;&#160;</a>You will need to navigate the installer UI within terminal, pressing "enter" and "y" when prompted for a <a>&#160;&#160;&#160;&#160;&#160;</a>default install

**Comment by oliver-phet** [comment]
closing. repeat of phetsims/website#96  @arnabp Add in your instruction comment into that issue.
