### ISSUE TITLE
Artwork for Journal Publication

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#285]
I need two "graphic abstracts" for two upcoming journal publications - ideally before July 17th. The graphic abstract is a small image that will be shown with the article abstract in search lists. It needs to encapsulate the point of the paper in a single graphic. Examples can be found here (in the top left there is a panel where you can scroll through the most recent 10 graphic abstracts): http://pubs.acs.org/journal/jceda8 .
- The first graphic abstract will need to represent a paper introducing inclusive sims. My first thought is to include an image representing PhET sims in the center (the PhET logo, or something else) surrounded by the icons that were made to represent different types of inclusive features (e.g., sonification,text to speech, translation, etc.).
- The second graphic abstract needs to represent a paper about the evolution of disability law from the mid-19th century to now. My thought here is something symbolic that represents "disability" and "law". 

I'd be happy to discuss other ideas with @mariahmaephet.

**Comment by ariel-phet** [comment]
@mariahmaephet - please get in touch with @emily-phet and make this a high priority issues (since it has a tight deadline). Thanks!

**Comment by mariahmaephet** [comment]
@emily-phet 

Ok, I think I get what you're looking for. Will the graphic only been seen at that size on the homepage, or would you want a larger version as well?

Have there been icons created for the inclusive design features or do we need to come up with those? and you'll probably have to explain that second graphic a little bit more to me.

**Comment by emily-phet** [comment]
@mariahmaephet - I think that's the largest the graphics will be shown. 

There were some accessibility icons created for PhET awhile back - see Task Issue #176. For the first one, perhaps three of these accessibility icons surrounding a PhET sim, or surrounding an icon of a computer with the PhET logo surrounding it?

For the second, maybe an icon of a computer in the center, with a recognizable law symbol (maybe a thick textbook looking thing with the word "Law" on it) and a recognizable accessibility symbol (maybe the standard wheelchair one). Does that make sense?

**Comment by mariahmaephet** [comment]
@emily-phet I'll get to this tonight!

**Comment by mariahmaephet** [comment]
@emily-phet are these on the right track? 

<img width="862" alt="screen shot 2015-07-17 at 5 59 27 pm" src="https://cloud.githubusercontent.com/assets/11527557/8759289/3249cd36-2cae-11e5-8f7a-560009b72fca.png">
<img width="649" alt="screen shot 2015-07-17 at 6 03 38 pm" src="https://cloud.githubusercontent.com/assets/11527557/8759290/324e45dc-2cae-11e5-8c92-fc1593dfb67f.png">

**Comment by emily-phet** [comment]
@mariahmaephet - I like the computer icon a lot. How about something more like this for the first graphic abstract:
![slide1](https://cloud.githubusercontent.com/assets/5109055/8760195/23f87372-2ccc-11e5-9c6b-6d81b8a204f1.png)

One issue I see is that the icons all looks so different, they don't necessarily look related. What about putting them inside colorful circles like the icons from the PhET intro video - here:
![screen shot 2015-07-17 at 9 36 18 pm](https://cloud.githubusercontent.com/assets/5109055/8760203/5a349aec-2ccc-11e5-84d1-897194031b18.png)
Also, maybe inverting the colors (e.g., white on a colored background, instead of all black) would make them look a little softer, they are a bit harsh right now.

For the second graphic abstract, how about something more like this for the "law" representation:
<img width="67" alt="screen shot 2015-07-17 at 9 42 09 pm" src="https://cloud.githubusercontent.com/assets/5109055/8760217/d29ac592-2ccc-11e5-973e-b9f5b7713980.png">

**Comment by mariahmaephet** [comment]
@emily-phet is this what you were thinking?

<img width="427" alt="screen shot 2015-07-20 at 10 54 43 am" src="https://cloud.githubusercontent.com/assets/11527557/8781819/a6191af6-2ece-11e5-96ff-698cbbf7126f.png">
<img width="862" alt="screen shot 2015-07-20 at 11 00 52 am" src="https://cloud.githubusercontent.com/assets/11527557/8781849/dd8b775e-2ece-11e5-9619-a15e1e6f194b.png">

**Comment by emily-phet** [comment]
@mariahmaephet - Beautiful!

I love the colored circles - it really softens up the logos. 

For Graphic Abstract #1 (with the phet sim logo in the center) - can you make the scale of each of the colored circles a little more even. The keyboard one looks a bit larger than the others, and it looks like you might have added some more padding around the translation ("earth") one to make it more even with the keyboard. Could you make those a bit smaller to match the size of the the two talking heads? (That's a weird sentence... :)

For Graphic Abstract 2: Could you make the "law" and "accessibility" circles intersect with the laptop screen circle?

**Comment by mariahmaephet** [comment]
@emily-phet 

<img width="859" alt="screen shot 2015-07-21 at 10 10 56 am" src="https://cloud.githubusercontent.com/assets/11527557/8805894/fdb6603a-2f90-11e5-86a2-430bdfa6880b.png">
<img width="863" alt="screen shot 2015-07-21 at 10 12 03 am" src="https://cloud.githubusercontent.com/assets/11527557/8805895/fdc708cc-2f90-11e5-9a84-fcfcfc2c2414.png">

**Comment by emily-phet** [comment]
@mariahmaephet - the top one is perfect!
For the lower one (with three circles) can you try more of an interconnected triangular shape, with the "law" and the "accessibility" icons being lower.

**Comment by mariahmaephet** [comment]
@emily-phet 

<img width="862" alt="screen shot 2015-07-23 at 1 40 02 pm" src="https://cloud.githubusercontent.com/assets/11527557/8860371/9fac33d2-3140-11e5-9dce-8c0480dbd199.png">
<img width="863" alt="screen shot 2015-07-23 at 1 41 43 pm" src="https://cloud.githubusercontent.com/assets/11527557/8860372/a0169196-3140-11e5-80b2-f83902aa10e7.png">

**Comment by emily-phet** [comment]
@mariahmaephet - I think I like the upper one best, with more distance between the circles. Can you make a version that removes the outer circle (the thin line) for each of the three circles (just for this one image).

**Comment by mariahmaephet** [comment]
@emily-phet 
<img width="859" alt="screen shot 2015-07-24 at 9 19 19 am" src="https://cloud.githubusercontent.com/assets/11527557/8877861/1b5762a0-31e5-11e5-9e11-22207be40dbb.png">

**Comment by ariel-phet** [comment]
@mariahmaephet - can you upload this to your google drive?

**Comment by mariahmaephet** [comment]
@emily-phet  @ariel-phet Yep! I created a folder titled 'Emily' in 'Mariah Artwork' so I can keep the things that I do for her together.

**Comment by emily-phet** [comment]
@ariel-phet - can Dave take a look at the final versions of these two figures? I don't have any further feedback for Mariah on these, but I would be curious if Dave has any suggestions.

**Comment by emily-phet** [comment]
I met with Dave Underwood to discuss refining these a bit. He's going to take a look at them.

**Comment by emily-phet** [comment]
@daveunderwood - the journal has indicated reservations about the use of the graphic abstracts. They have currently agreed to approve versions of the graphic abstracts without the name/affiliations line (pending further approval by their lead editor). Could you send me versions without the name/affiliation line, and second versions without any added text (title or affiliation line) - just in case?

**Comment by daveunderwood** [comment]
Will do as soon as I'm back. What's your timeline, Emily? D

**Comment by emily-phet** [comment]
@daveunderwood - Unfortunately, as soon as possible. I wasn't told the graphic wasn't going to work as is until the point where they are ready to finalize...so the publisher is wanting it soon.

**Comment by daveunderwood** [comment]
>... so the publisher is wanting it soon._

Those rascals! Always in a hurry, eh?  ;-)

Like this?:

![conf_chem3](https://cloud.githubusercontent.com/assets/13662881/12901684/28fad7d4-ce7a-11e5-8eb1-c0360fc29dfa.jpg)
![conf_chem3b](https://cloud.githubusercontent.com/assets/13662881/12901685/29215ba2-ce7a-11e5-8585-485c164b0e64.jpg)
![interactive_chem3](https://cloud.githubusercontent.com/assets/13662881/12901698/37559490-ce7a-11e5-9b7a-acda57028ff3.jpg)
![interactive_chem3b](https://cloud.githubusercontent.com/assets/13662881/12901699/3758af40-ce7a-11e5-824b-7e587a7bf13f.jpg)
![disability_law3b](https://cloud.githubusercontent.com/assets/13662881/12901703/3a0d4f2a-ce7a-11e5-9ccf-f07cc99d7265.jpg)
![disability_law3](https://cloud.githubusercontent.com/assets/13662881/12901704/3a105a4e-ce7a-11e5-9e06-5377a6d9d6a3.jp

**Comment by emily-phet** [comment]
@daveunderwood - exactly! Except the last one didn't come through (the red accessibility sign with the title.

**Comment by daveunderwood** [comment]
![disability_law3](https://cloud.githubusercontent.com/assets/13662881/12902027/df2997ec-ce7b-11e5-8978-d623bc392279.jpg)

**Comment by emily-phet** [comment]
@daveunderwood - thanks!
