### ISSUE TITLE
Full-screen iframe testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#286]
Please test http://www.colorado.edu/physics/phet/dev/olsonjb/full-screen-iframe/molarity_en-iframe.html and check whether it is not possible to enter full-screen mode (from the PhET Menu) in any supported browser, particularly where it IS possible in the non-iframe version http://www.colorado.edu/physics/phet/dev/olsonjb/full-screen-iframe/molarity_en.html.

**Comment by ariel-phet** [comment]
@elisemorgan @orejolaphet please make this your top testing priority, it should be pretty quick

**Test Matrix**
https://docs.google.com/spreadsheets/d/1Ud6wAjmNnTqD0Hbv30SicWlHtakKZ2oPf_7hSqipPJ8/edit#gid=2

As @jonathanolson notes, please test all browsers, some may not support full screen. If the Iframe full screen does not work, please comment in the test matrix whether the regular non-iframe version works.

**Comment by orejolaphet** [comment]
@ariel-phet The testing matrix has been completed.

**Comment by jonathanolson** [comment]
Created https://github.com/phetsims/joist/issues/281, thanks! Closing this issue.
