### ISSUE TITLE
Wall and robotic arm "box" improvements for Hooke's Law

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#288]
@mariahmaephet - do you have some time to meet up and discuss some artwork for Hooke's Law. I have some ideas for improvements, but I think they will be easiest to iterate over in person.

**Comment by ariel-phet** [comment]
Are you available Friday afternoon potentially (7/17)?

**Comment by mariahmaephet** [comment]
@ariel-phet I am! Any time should be fine

**Comment by mariahmaephet** [comment]
@ariel-phet How does this look? 

<img width="940" alt="screen shot 2015-07-29 at 11 42 57 am" src="https://cloud.githubusercontent.com/assets/11527557/8965168/ffe20858-35e6-11e5-9fed-1b22b586f161.png">

**Comment by ariel-phet** [comment]
Better...can I see it in the context of the entire sim @mariahmaephet?

**Comment by mariahmaephet** [comment]
@ariel-phet 
<img width="718" alt="screen shot 2015-07-29 at 3 02 03 pm" src="https://cloud.githubusercontent.com/assets/11527557/8969782/d14293fc-3602-11e5-9d2e-8bb3dc3b6259.png">

**Comment by arouinfar** [comment]
I like the updated look of the box that the arm disappears into. Thanks, @mariahmaephet! I think we should go ahead and use this version, and it looks like something that @pixelzoom can implement in code. Should we go ahead and move forward with this implementation, @ariel-phet?

**Comment by pixelzoom** [comment]
Closing. This work will be completed in phetsims/hookes-law#17.
