### ISSUE TITLE
Schrodinger to Win 8, Socrates to Win 7

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#289]
@arnabp please reformat Schrodinger and make it a Win 8 testing machine (so most important to have all 3 browsers, java, and flash installed). Good to also have camtasia.

Wipe Socrates and make it Win 7 again. We want to make this computer pretty "lightweight" software wise since it is pretty slow already.

@arouinfar please comment on any other requirements

Also update the asset tracking spreadsheet when the task is complete. We will need these changes soon since we need a solid win 8 testing platform for our summer redeploys.

**Comment by arouinfar** [comment]
@arnabp, it would be best if Socrates could have the same software as Schrodinger. Namely:

1. Windows 7
2. Microsoft Office
3. Camtasia
4. Java
5. IE, Firefox, Chrome (with up-to-date Flash)

**Comment by oliver-phet** [comment]
I wasn't aware we were doing Win 7 on Socrates. Win7 and 8 are very comparable performance wise, and since Socrates has a touchscreen we may want to keep it Win 8 just so that we have a touchscreen computer we can test with.

**Comment by ariel-phet** [comment]
@oliver-phet good point...I think @arouinfar thought win7 might be faster. Maybe just try upgrading (is it Win8 right now? Maybe put it to Win 8.1?)

Additionally, is just not a very good machine, and sometimes has issues that are very specific to that machine, so it does not make a great test platform. Seems like we should look into a decent Win 8 touchscreen testing computer (that will eventually go to win 10) for the future. Something that has solid performance but is not too expensive.

**Comment by arouinfar** [comment]
Thanks for your input, @oliver-phet. It doesn't seem like Socrates' hardware can handle Windows 8 very well, and it is very sluggish. For example, PowerPoint would have a very noticeable lag when trying to switch between slides and Energy Forms & Changes ran at a snail's pace. I second @ariel-phet's comment that it does not make for a good testing platform. I don't particularly care what OS Socrates has, but something that would be less taxing on its system would be nice.

**Comment by ycarpenterphet** [comment]
I think the slowness is a new issue. I've used Socrates for ppt presentations in the past, as well as to run both HTML and Java sims without noticeable issue, with it running Win8.

Sure, the machine has had some weird issues of its own, and is not the best testing device for touch long-term, since it often has issues that are unique to that device (and don't generalize to other Win8 platforms).

It may be worth wiping it, reinstalling Win8, and seeing how the performance is, since I suspect the slowdown has resulted from other software or new settings that are more recent.

**Comment by arouinfar** [comment]
I agree with @ycarpenterphet. I have used Socrates before (we took it to NSTA this year) and I remember it being a little slow, but not terrible. However, when using it this week to give a presentation and demo a few Java sims it was <i>extremely</i> slugglish, despite having all other applications closed. 

It sounds like the consensus is to try wiping Socrates and clean installing Win8 or Win8.1 along with

> Microsoft Office
Camtasia
Java
IE, Firefox, Chrome (with up-to-date Flash)

**Comment by oliver-phet** [comment]
Yep, that's what we are doing.

**Comment by arnabp** [comment]
I've clean installed both computers to Windows 8.1, installed all listed software, updated the asset spreadsheet accordingly, and moved both to F1011.

**Comment by ariel-phet** [comment]
You rock @arnabp! Closing issue.
