### ISSUE TITLE
Converting Camrec files to Movie Files - ideally by July 23rd

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#290]
Please export the *.camrec recording in the following directories on phetbackup to a more user friendly movie format - e.g., *.mov, and upload to a Google Drive folder and share with me.

2013_07_08_BASE_OL_RIAW_HTML5_G5_F_SL1_Surface_Chrome_NP
2013_07_08_BASE_OL_RIAW_HTML5_G5_F_SL2_Surface_Chrome_NP
2013_07_10_BASE_OL_RIAW_HTML5_G5_M_QC_PC_NP
2013_07_10_BASE_OL_RIAW_HTML5_G7_M_ZC_PC_NP

**Comment by ariel-phet** [comment]
@orejolaphet can you get this done by the 30th? Especially since you have done this type of task before?

**Comment by orejolaphet** [comment]
@ariel-phet I'll get on this asap

**Comment by ariel-phet** [comment]
@orejolaphet - where is this task at?

**Comment by orejolaphet** [comment]
@ariel-phet I have been working out of the office the past few days, will be coming in today to convert the 4 videos.

**Comment by orejolaphet** [comment]
@emily-phet I have converted the four video files to .mp4 format, and I have uploaded the files to the google drive folder https://drive.google.com/drive/folders/0B1dDzrtWHaLbfjloNS1EOWRKSTlaYUJGYkJaRmtZMTQ3OUV4VDFXZG9pZXFGTjBvTEE4alk
