### ISSUE TITLE
Add email information to 3rd party google sheet

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#292]
@elisemorgan We need to enter some email data from (many) phethelp emails into a google sheet called '3rd party database'. The sheet tracks usages of PhET by various outside parties across the world and is useful to have as a reference for contact information and for reporting usage when applying for grants: https://docs.google.com/spreadsheets/d/1BbzXueD_ioifg1NchqZ2tvArd57t7fsWTXKQXmKJkL0/edit#gid=3

The general process for doing this: 

1. Open phethelp email to "3rd+Party+GoogleDoc" label: https://mail.google.com/mail/u/1/#label/3rd+Party+GoogleDoc/p2 (login information to the phethelp gmail is on unfuddle, or I can send it to you)

2. The last record that had been "added" to the 3rd party database was an email on 10/18/11 so start there.
Open the email and if the user responded with information about their use (organization name, contact info, email addresses, etc.), add that info in the appropriate columns. Most 3rd party use will fall under the '3rd party publications' tab, but if it is apparent that the use is another type, please record in the correct tab.
 1. If no information has been provided in the email, add the '3rd+Party+GoogleDoc%2FNeeds+info' label  and move on to the next one.
 2. If there is information in the email, record it into the sheet and add the "Added! to 3P-GD" label (in addition to any other labels already).

This can be a low priority, back burner project for you to work on whenever you have time.

**Comment by elisemorgan** [comment]
@oliver-phet I'm almost done with this but the last few organizations submitted the info through the PhET Licensing Use form. I've looked through the phethelp drive but can't seem to locate the responses to this form. Can you point me in the right direction?

**Comment by oliver-phet** [comment]
@elisemorgan Don't worry about the contacts that submitted via the google form (since they submitted via form an email record doesn't exist). As long as the other emails tagged with the "3rd+Party+GoogleDoc" label have been added to the google sheet, we are good to go.

**Comment by elisemorgan** [comment]
Great, this task has been completed.
