### ISSUE TITLE
PhET girl for donations splash dialogue 

### ISSUE THREAD

**Issue by mariahmaephet** [phetsims/tasks#293]
@amanda-phet met with @ariel-phet and he told me about this website issue that I'll work on--2 versions of PhET girl and banners for her to hold

https://github.com/phetsims/website/issues/251

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet   Eh? 

<img width="413" alt="screen shot 2015-07-21 at 12 42 36 pm" src="https://cloud.githubusercontent.com/assets/11527557/8809508/52cdcbca-2fa6-11e5-802a-0bda5c0ba3a7.png">

**Comment by ariel-phet** [comment]
Great for the HTML5 one...can you also do the lab coat one?

**Comment by ariel-phet** [comment]
Thoughts @amanda-phet ?

**Comment by amanda-phet** [comment]
I like the superhero idea for the HTML5 prompt a lot. 

Let's do a lab coat version for the other prompt (airplane on shirt, not HTML5 shield).

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet same pose different outfit? 
<img width="507" alt="screen shot 2015-07-22 at 8 28 11 pm" src="https://cloud.githubusercontent.com/assets/11527557/8841860/4b6985e4-30b0-11e5-94be-fedfc3da9576.png">

**Comment by amanda-phet** [comment]
Looks great Mariah. Would you mind putting this in Drive? @aaronsamuel137 is working on it today and tomorrow. Thank you!

**Comment by ariel-phet** [comment]
@mariahmaephet - once you have put this artwork in drive, please assign the issue to @amanda-phet 

@amanda-phet we probably want to have @aaronsamuel137 upload the .ai file to github and then we can close this issue

**Comment by amanda-phet** [comment]
There is a slight issue. I am trying to use live paint to get the lab coat to be white (since the image will be exported with a transparent background). The right side of the coat doesn't work for me and I'm not too familiar with live paint groups. Can you look at the _edited file in drive and help me with this?

**Comment by ariel-phet** [comment]
@amanda-phet since this "ask" is functional on the website, can this issue be closed? Or is there anything left to do?

**Comment by amanda-phet** [comment]
Yes we can close it! Thanks.
