### ISSUE TITLE
Update PhET logo on FB page to registered trademark

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#294]
@arouinfar can you update our FB page to use our trademark logo?

**Comment by arouinfar** [comment]
Done! I've also added a registered version of the square black logo to Drive.  While I'm at it, do you think it'd be okay to delete some of our older profile pictures? There are 10 or so iterations on the black logo in our profile pictures album. From a branding perspective, I think it's best to delete those earlier versions.

**Comment by ariel-phet** [comment]
@arouinfar - yes good idea, best to just have the current correct picture

**Comment by ariel-phet** [comment]
I also updated our twitter and github accounts with the registered trademark logo.

**Comment by arouinfar** [comment]
Done! Closing.
