### ISSUE TITLE
Write tweets to be shared from HTML5 sim pages

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#296]
In line with our updated social media strategy, we'd like to create more descriptive tweets for the Share on Twitter buttons on our HTML5 sim pages.  These tweets should include:
- [ ] Appropriate hashtags (e.g. #PhETsims)
- [x] Official screenshot of the sim 
- [ ] Descriptive text that doesn't just copy what's in the \<title> tags
- [x] Shortened link to the sim page, if necessary

Self-assigning this issue.

**Comment by ariel-phet** [comment]
Now that we are going to be doing "twitter cards" this will likely be unnecessary, I will work with @mattpen to wire up the cards to the "share on twitter" button
