### ISSUE TITLE
New Twitter header photo

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#297]
We'd like to create a new header photo for our Twitter account that incorporates sim screenshots and PhET Girl.

@ariel-phet will set up a time with @mariahmaephet to discuss the details.

**Comment by ariel-phet** [comment]
@mariahmaephet - let me know a time next week that might work (perhaps a Wednesday meeting). Although this is not yet a high priority, it would be good to toss around some ideas. I think you are going to be able to do something really fun with it!

**Comment by mariahmaephet** [comment]
@ariel-phet sounds fun! Wednesday would be good

**Comment by ariel-phet** [comment]
Ok, lets plan Wednesday at 1 pm @ Amanda's office

**Comment by ariel-phet** [comment]
Sims screenshots to use:
Color Vision, Forces and Motion: Basics, pH Scale:Basics, Area Builder, Energy Skate Park

**Comment by ariel-phet** [comment]
To get screenshots go to sim repository, then to assets, click on screenshot, click "raw", can save screenshot

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet  Just an update


Chem Lab 
<img width="898" alt="screen shot 2015-09-03 at 1 53 55 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669293/5828038c-5243-11e5-918c-c1f0f455eba6.png">

Vision - do you like them with or without the 3D glasses? 
<img width="823" alt="screen shot 2015-09-03 at 1 56 14 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669352/afc505ae-5243-11e5-9970-843d9af62a36.png">
<img width="857" alt="screen shot 2015-09-03 at 1 53 07 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669294/59e29570-5243-11e5-83f9-cf7f35ff5282.png">

And I'm still going to add a few objects to this one and play around with colors a bit, but I'd love feedback if it looks alright or if there's anything more you'd like to see in the scene. 
<img width="897" alt="screen shot 2015-09-03 at 1 50 28 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669296/5bbfed52-5243-11e5-9256-362e8ca6a233.png">

**Comment by mariahmaephet** [comment]
I'm also making files of all the objects so we have those individually for the future 

<img width="720" alt="screen shot 2015-09-03 at 1 59 22 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669424/46d0f5f2-5244-11e5-90f5-127107da0ce5.png">
<img width="718" alt="screen shot 2015-09-03 at 1 59 34 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669423/46ccff60-5244-11e5-8882-dec8733da47b.png">

**Comment by mariahmaephet** [comment]
and just for reference this is how they look with the simulations 
<img width="960" alt="screen shot 2015-09-03 at 2 18 31 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669863/daf1d34e-5246-11e5-97f9-9a6392fd96a2.png">
<img width="963" alt="screen shot 2015-09-03 at 2 19 03 pm" src="https://cloud.githubusercontent.com/assets/11527557/9669864/daf4ba1e-5246-11e5-82ec-c71d14cf0017.png">

**Comment by amanda-phet** [comment]
This looks amazing @mariahmaephet . 

Re: Color Vision, I think we should skip the 3D glasses since that sim is more about color perception.

**Comment by ariel-phet** [comment]
Looking great! For pedagogical reasons, the "tug of war" should be with a cart if we are comparing to the sim...so could we put a big cart in the scene?

**Comment by ariel-phet** [comment]
Oh and in the movie scene the girl in the top right should be given open eyes

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet comments on these and ideas for how the banner should be arranged?

I still want some sort of writing on the white board in the classroom scene but I'm still working on how to make it look good. Any ideas on what should be written?

<img width="598" alt="phet - skate park scene" src="https://cloud.githubusercontent.com/assets/11527557/10545024/b912ab86-73e3-11e5-8385-90c2a08f117a.png">
<img width="888" alt="phet - classroom scene" src="https://cloud.githubusercontent.com/assets/11527557/10545036/c93fceb2-73e3-11e5-9b50-5d20938d6692.png">
<img width="899" alt="screen shot 2015-10-16 at 9 03 28 am" src="https://cloud.githubusercontent.com/assets/11527557/10545227/d4a84580-73e4-11e5-8dae-1abf15a9258a.png">

**Comment by ariel-phet** [comment]
Hey @mariahmaephet really coming along amazingly! A few comments/tweaks but overall super awesome!

1. In the math scene the two students seem to be looking off into the distance, maybe have them looking at the teacher or at their work?

2. In the math scene maybe make the student look much more obviously african-american. I think we want at least one character pretty dark skinned, and like the teacher in balancing act more volume/"fro-iness" to his hair

3. In terms of on the board I think some examples of area and perimeter of geometric figures, I will paste in a good example in a comment below.

4. The skating scene is great -- even better would be if one of the front characters was in a wheel chair looking like they were having a blast. The detail of the shadow is fantastic by the way.

5. In terms of arrangement, any order of the scenes will do as long as the correct sim is associate with each scene. I think we will need some negative space (if we just tile them, I think they will feel cluttered).

**Comment by ariel-phet** [comment]
Here is an example of what the board should look like

http://images.wisegeek.com/chalkboard-geometry-shapes-and-equations.jpg

Definitely keep the triangle, but maybe replace the cylinder with  a rectangle with (A=L*w)

**Comment by ariel-phet** [comment]
Everything from these scenes looks great! Closing.
