### ISSUE TITLE
Updated Poster: Mid-day July 29th Deadline

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#299]
I need a 4 foot high x 3 foot wide version of the ACS poster (from Issue #173). I'll need to update the text a bit, but the overall design should be fine. Also, it would be ideal if it had less bright colors, and the first screen of Forces & Motion: Basics in the center. 

I'll need to have it done and printed by 4pm on Wednesday. Is this possible @mariahmaephet?

**Comment by mariahmaephet** [comment]
@emily-phet sure! Did you want the colors to be totally different colors or literally just dulled down versions of what they currently are? 
<img width="372" alt="screen shot 2015-07-24 at 9 25 53 am" src="https://cloud.githubusercontent.com/assets/11527557/8878027/03c4a746-31e6-11e5-848c-14661771dce9.png">

**Comment by emily-phet** [comment]
@mariahmaephet - the left side coloring looks fine to me. 
I was thinking of the poster you made before this one, the very large poster for the ACS conference in March. That poster had the description of inclusive design features, in color blocks around the central one. Do you have that one?

**Comment by mariahmaephet** [comment]
@emily-phet This guy? and you'd just want it changed to 4x3 with some edits?

<img width="719" alt="screen shot 2015-07-24 at 11 34 10 am" src="https://cloud.githubusercontent.com/assets/11527557/8880727/048b625c-31f8-11e5-98ad-f826182c7597.png">

**Comment by emily-phet** [comment]
@mariahmaephet - yes, do you think it can just be scaled down to the new dimensions, or should some redesign/reformatting happen. I can't remember what size it was originally (maybe it was used for the same size before...).

**Comment by emily-phet** [comment]
@mariahmaephet - just wanted to give you a heads up, I'm working on the text for the poster now. I'll send it along to you in an hour or so. Can you let me know when you'll be able to send me an updated draft?

**Comment by emily-phet** [comment]
@mariahmaephet - I just emailed you the poster text. Let me know if you have any questions!

**Comment by emily-phet** [comment]
@mariahmaephet - just a thought - you could add a PhET character to the top border if you wanted. No pressure, not sure how long what I've already sent you will take.

**Comment by mariahmaephet** [comment]
@emily-phet Cool! I'll get working on that shortly and let you know. It probably wouldn't be much extra effort to add PhET girl in it somewhere.

**Comment by mariahmaephet** [comment]
@emily-phet How does this look?

<img width="864" alt="screen shot 2015-07-28 at 12 16 41 pm" src="https://cloud.githubusercontent.com/assets/11527557/8939599/8b9b464a-3522-11e5-863e-3b91a478ffb2.png">

**Comment by emily-phet** [comment]
@mariahmaephet - this looks wonderful!

Some small tweaks:
- Can the white border of the center circle be narrowed a bit (or the font size increased for the text inside it - it seems a bit think for the text)
- Can you layer the sim screen in the center under the outer white border. I'm imagining this will look ok but if it looks weird to you then forget it.
- Can PhET girl be holding a white sign with the colorful PhET logo on it? Kind of like in the website registration screen?

Can you send me a slightly higher resolution version so that I can proof the text? I may have introduced a few typos, but I can't read the text if I zoom in on the image above.

Thanks! I'll email Oliver and see if he can print this tomorrow mid-day. Do you think you could make these tweaks and have time for me to take a look by ~10am tomorrow?

**Comment by emily-phet** [comment]
@mariahmaephet - I received the pdf file, but found two small issues (sent to you by email). If you can't get to this by about 10:30am today, I'll send it on to Oliver to be printed as is, but it would be great if you could tweak these last things before then.

**Comment by ariel-phet** [comment]
Since the deadline has passed, and I assume poster printed, I am closing
