### ISSUE TITLE
Dev test Trig Lab 1.0.0-dev.14

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#300]
@bryo5363 @orejolaphet @elisemorgan please Dev test Trig lab

As usual create issues in the Trig Lab repo and assign to @dubson 

**Platforms**
- [x] Windows + Chrome
- [x] Mac + Safari
- [x] iPad2 iOS8

**Testing Link**
http://www.colorado.edu/physics/phet/dev/html/trig-lab/1.0.0-dev.14/

**Comment by elisemorgan** [comment]
@ariel-phet I've tested all the platforms and haven't seen any new issues. I believe dev testing is complete

**Comment by ariel-phet** [comment]
Excellent, thanks @elisemorgan!
