### ISSUE TITLE
Install Microsoft Office on Curie & Jordan

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#301]
Last week I gave a remote workshop, and was broadcasting my slideshow via screen sharing. I wanted to use a second device so I could have access to my speaker notes while presenting, but discovered we do not have Microsoft Office installed on any of the Macs. I was able to use Office 365 to open the powerpoint, but it was a less than ideal environment. 

@amanda-phet and I often use one of the MacBook Airs as a secondary device, so it would be great if Microsoft Office could be installed on both Curie & Jordan. @arnabp has indicated that he has some time available, so I'm assigning this issue to him. Please update the asset inventory doc once you've finished.

**Comment by arnabp** [comment]
Curie and Jordan both now have updated versions of Office '11 and the asset inventory doc has been updated accordingly.
