### ISSUE TITLE
Create a test of the "Balloons" primer

### ISSUE THREAD

**Issue by schasteen** [phetsims/tasks#302]
This is a task for Arnab to try a draft version of the Balloons and Static electricity primer.

We'd like you to try making a walkthrough of the Balloons and Static Electricity simulation.  This is just to try out the process of someone using another person's script, so do as well as you can, but the goal is not to end up with a website-ready primer at the end of this test.  Let me know if you have questions.

Here is what I suggest for a task list:

1.  Look through our guidelines on making sim primers, to get a sense of how the process works.  As part of that, watch one or two of the posted primers on that page.  
https://drive.google.com/open?id=1LCEOvS-wLL68UH8Pc_L1y4MpPhs3QpN93OgRXfiuf1A

2.  Go to the Google Drive folder at 
https://drive.google.com/folderview?id=0B13Bt0HjlZfQfms4NUlLdXg2bHRmUEVjamcwNHF5bk5zU2FwNlprTTVURDFMWFZpTnN6a0U&usp=sharing
This has the outline for the primer, and is where you can put the Camtasia files for me to view.  If you give me your email, I can share it with you directly.

3.  Use that outline to run through the actions suggested a few times, so you get the flow.  Then practice with the script.  Let me know if you have questions.

4.  Then try recording using Camtasia.  Note it's often easiest to record in chunks -- choose a place where you will leave the cursor after each chunk (e.g., when you reset all).  Because this only has one screen, there may be fewer places when you can stop and restart without going back to the beginning.

5.  Send me what you think is your best shot (i.e., edit out the bad takes).

**Comment by arnabp** [comment]
https://drive.google.com/file/d/0BxerAx_XXHB2ajRkUDRSSzZuRjA/view?usp=sharing

Here is a link to the primer. I edited the script to clean up a few language and grammar issues, but otherwise the content should be all the same. Let me know if there's anything I should change.

**Comment by schasteen** [comment]
Arnab,
We think your test primer is great!  How long did this take you, and how many "takes" did you do?
I'd like to chat when you are back about a few changes we'd like to have you do, and re-record.  Please contact me to set up a time.   Copying @amanda-phet 
Stephanie

**Comment by arnabp** [comment]
I'll be back on Monday and will be available 1-4 PM every day that week. I can discuss everything then!

**Comment by schasteen** [comment]
Let's set up a meeting time when you're back.  Available times:

Thursday the 20th, 1 or 2
Friday the 21st, 2 or 3

Stephanie


I'll be back on Monday and will be available 1-4 PM every day that week. I can discuss everything then!

**Comment by arnabp** [comment]
https://drive.google.com/file/d/0BxerAx_XXHB2dkNKcm9VZ2VSZnc/view?usp=sharing

Here's the next draft. Resolution should be fixed by now. This took relatively little time (an hour if you include exporting), and I got the audio and video recordings on my first try for both (it's important to take into account that I'd said the script and gone through the mouse rouetines enough times that, at this point, I was quite familiar with both). My tone, I hope, should be a little more lively.
