### ISSUE TITLE
Put a copy of the HTML5 sim screenshots in google drive folder

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#303]
We have a google drive folder with the newest official screenshots for all java and flash sims. Since some team members are actively using this folder, we thought it would be a good idea to have the HTML5 sim screenshots included as well. 

Can you download the official screenshots for all HTML5 sims from Github and put them in the PhET Sim Screenshots folder?

Assigning to @arnabp since @oliver-phet said he has some availability this week. Should not take more than 30 minutes to complete.

**Comment by arnabp** [comment]
To clarify, the pictures in the folder now are screenshots of Java and Flash sims, and I just need to add all the HTML5 ones, correct?

**Comment by amanda-phet** [comment]
Yes that is correct. The HTML5 ones can all be found in their Github repositories.

**Comment by arnabp** [comment]
Okay, all screenshots have been added to the folder on Google Drive.

**Comment by amanda-phet** [comment]
Fantastic. Thank you @arnabp !
