### ISSUE TITLE
PhET Sticker Design

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#304]
@mariahmaephet I moved this to a new issue since the other one was specifically for the "Breaking Bad" T-shirt

When possible can you send me a 2000x2000 pixel png of this design with the proper transparency?

<img width="449" alt="44f2fca4-297b-11e5-80b9-a4d322894751" src="https://cloud.githubusercontent.com/assets/4051174/9024725/5e073392-389c-11e5-9261-5a69f04258be.png">

**Comment by ariel-phet** [comment]
And maybe shrink the PhET logo a little so that the "Interactive Simulations" tagline is not so tight to the airplane edges

**Comment by amanda-phet** [comment]
I'd also like to point out the PhET visual identity here: https://docs.google.com/document/d/1WnthgL675uxozx29siRB30zDRWZOgRFxqKC-mW0_q1c/edit?usp=sharing. Please be sure to use the correct PhET yellow!

**Comment by mariahmaephet** [comment]
@ariel-phet I'll have those in my drive shortly

@amanda-phet I made one with the yellow and one with the green. In the file you gave me with all the logos the logo with the black background is actually that green... that's probably why I did that. So it is one of your colors, just not the one you use on the website. So whatever you like best!


<img width="657" alt="screen shot 2015-08-07 at 11 13 50 am" src="https://cloud.githubusercontent.com/assets/11527557/9141411/ae68fafc-3cf5-11e5-88c5-7c90ea27d0e2.png">
<img width="655" alt="screen shot 2015-08-07 at 11 13 57 am" src="https://cloud.githubusercontent.com/assets/11527557/9141412/ae6cc3ee-3cf5-11e5-90f4-71398e1708d9.png">

**Comment by amanda-phet** [comment]
@mariahmaephet you're correct- the logo on black did originally use a "greener" yellow, but we have since changed it to use the same warmer yellow everywhere. The document has the hex/rgb values of the yellow. 

I like the second one :)

**Comment by ariel-phet** [comment]
@mariahmaephet agreed...second one. However, maybe it is just my eye, but it looks like the line of "interactive simulations" is not quite parallel to the line of the airplane edge. Can you check that?

**Comment by mariahmaephet** [comment]
@ariel-phet good catch! 

<img width="499" alt="screen shot 2015-08-07 at 11 30 38 am" src="https://cloud.githubusercontent.com/assets/11527557/9141687/c73d3bb8-3cf7-11e5-9654-d23d7a928a56.png">

**Comment by ariel-phet** [comment]
This issue can be closed.
