### ISSUE TITLE
phettest "refresh all" button not working

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#305]
The "refresh all sims" button does not seem to be working right now. In the meantime, we can pull all using git bash on the hp in Ariel's office, but I wanted to notify people that the button on phettest is not working at the moment.

**Comment by jonathanolson** [comment]
Should be fixed, let me know if there are any additional problems.

**Comment by amanda-phet** [comment]
I clicked it this morning and never saw the "status" image stop spinning, so I'm not sure how to tell if the button works or not.

**Comment by jonathanolson** [comment]
I'll check in person soon, reopening.

**Comment by jonathanolson** [comment]
Looks like the console program (where it was running) had been closed. I restarted it, and it seems to be working fine now. Definitely let me know if we run into any other issues.

If that happens again, I can figure out a way to get it to always run in the background.
