### ISSUE TITLE
review our use of visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#307]
Visibility annotations are @public @protected @private.

We've been marking stuff as @private, and assuming everything not marked is public.

Should we perhaps be making stuff as @public or @protected, and assuming everything not marked is private?  This would be a safer approach, and would make it easier to search for the public API.

**Comment by pixelzoom** [comment]
Another option would be to tag everything with an annotation.

**Comment by samreid** [comment]
We have been talking about adding annotations for each declaration.  We should discuss exactly how this should look. One way to do this:
```js
    // The position of the bar, in meters
    // @public
    this.x = 5;
```

**Comment by pixelzoom** [comment]
this.width = 30; // @public
this.model = options.model; // @private the model associated with this UI component

// @public
this.x = x;
this.y = y;
this.width = width;
this.height = height;

**Comment by pixelzoom** [comment]
PropertySet.call( {
 x: x,
 y: y,
 width: width,
 height: height,
 foo: options.foo // @private
} );

**Comment by samreid** [comment]
Here's a PropertySet subclass I saw in bending light:

```js
    PropertySet.call( this, {
        laserView: 'ray', // @public, Whether the laser is Ray or Wave mode
        wavelength: BendingLightConstants.WAVELENGTH_RED, // @public
        isPlaying: true, // @public
        speed: 'normal', // @public
        indexOfRefraction: 1, // @public
        showNormal: true // @public
      }
```

**Comment by pixelzoom** [comment]
Consensus: Let's try annotating all definitions. Revisit common code as we have time.

**Comment by pixelzoom** [comment]
To test drive this, I added annotations to all existing code in hookes-law.  It took me 9 minutes to annotate  5724 lines of code in 63 file.  That doesn't feel like much of a burden for the benefit.

**Comment by pixelzoom** [comment]
Should we update the section on coding guidelines in the PhET Development Overview? (http://bit.ly/phet-development-overview).  It currently says:

```
Annotations, such as “@public”, should be used to improve the maintainability of the code.  Information about the private and public annotations (as used by Google) can be found here and here.  In PhET simulation and library code, the main things we want to document are:
Mark as @private anything that would be likely to cause problems if set or invoked from outside the type
Mark as @public anything that is intended to be within the type’s external API
Mark as @protected anything that is intended for use only in sub-types
Also, we often use a comment like “// read only” to distinguish a property or 
```

**Comment by pixelzoom** [comment]
Looks like the guidelines currently match what we've decided to do. But perhaps we should emphasize that we want definitions (instance fields and prototype functions) annotated.

**Comment by pixelzoom** [comment]
As an additional test drive, I added annotations to acid-base-solutions - code I'm familiar with but did not write.  3798 lines of code in 46 files took me 12 minutes.

**Comment by pixelzoom** [comment]
Should the code-review checklist be amended?

**Comment by pixelzoom** [comment]
Ah... The code-review checklist doesn't need to be amended because it refers to the PhET Development Overview for issues related to code style.

**Comment by samreid** [comment]
@pixelzoom can you describe your strategy for annotating these?  Are you doing string searches to see if things are public or private?  Are you running code for any tests? Etc. etc.

**Comment by pixelzoom** [comment]
My strategy was visual inspection of the source code.

**Comment by pixelzoom** [comment]
8/13/15 dev meeting:
We're going to go with this. I will clarify the relevant code style paragraph in the PhET Development Overview.

**Comment by pixelzoom** [comment]
Discussion about qualifiers for these annotation took place in https://github.com/phetsims/scenery/issues/452.  Examples of what we decide to go with:

```
@public (read-only)
@public (scenery-internal)
@public (scenery-internal, read-only)
```

**Comment by pixelzoom** [comment]
Here are the changes that I made to the PhET Development Overview:

Because JavaScript lacks visibility modifiers (public, protected, public), PhET uses JSdoc visibility annotations to document the intent of the programmer, and define the public API. Visibility annotations are required for anything that JavaScript makes public. Information about these annotations can be found here and here. PhET guidelines for visibility annotations are as follows:
* Use @public for anything that is intended to be part of the public API.
* Use @protected for anything that is intended for use by subtypes.
* Use @private anything that is NOT intended to be part of the public or protected API.
* Put qualifiers in parenthesis after the annotation, for example:
** To quality that something is read-only, use “@public (read-only)” 
** To qualify that something is public to a specific repository, use (for example) “@public (scenery-internal)”
**Separate multiple qualifiers with commas. For example: “@public (scenery-internal, read-only)”

**Comment by pixelzoom** [comment]
I've create issues for all of my sim repos (assigned to me), and for all common-code repos (unassigned), to add visibility tags.

**Comment by pixelzoom** [comment]
I've completed adding visibility annotations to all of my sims. It was fairly quick, since I already was making consistent use of @private and @protected, so just had to confirm and add @public.

Assigning to @ariel-phet to decide how to get this done for common repos and other sim repos.

**Comment by samreid** [comment]
We'll discuss this in the developer meeting on Thursday.

**Comment by pixelzoom** [comment]
I took care of phetsims/axon#65, and wouldn't mind doing some of the other common repos if you want to assign to me. I probably shouldn't do dot/kit/scenery because I'm not as familiar with that code base.

**Comment by jbphet** [comment]
Discussed in 9/3/2015 meeting, will assign to @jonathanolson for dot/kit/scenery, he can assign back to @pixelzoom when he's done for the remaining common code.  For sims, each will have this done as they are prepared for the 2015 redeploy.

**Comment by pixelzoom** [comment]
Added developer-meeting label so that we can check in on the status of this.

**Comment by pixelzoom** [comment]
Here are the common repos that require visibility annotations (I did the others, will some help).

-[ ] dot
-[ ] joist
-[ ] kite
-[ ] phetcommon
-[ ] scenery
-[ ] sun
-[ ] vegas
-[ ] vibe
-[ ] nitroglycerin
-[ ] shed

All of my sims have also been done. I don't know the status of other sims.

**Comment by pixelzoom** [comment]
Here are the common repos that require visibility annotations. I did the others, with some help. I can do these because I don't know the intent (wrt visibility) of the authors (which is why this needs to be done).

- [ ] dot
- [ ] joist
- [ ] kite
- [ ] phetcommon
- [ ] scenery
- [ ] sun
- [ ] vegas
- [ ] vibe
- [ ] nitroglycerin
- [ ] shed

All of my sims have also been done. I don't know the status of other sims.

**Comment by pixelzoom** [comment]
Volunteers for handling the above repos?

**Comment by pixelzoom** [comment]
At developer meeting, let's put names next to remaining repos in https://github.com/phetsims/tasks/issues/307#issuecomment-154553345.

**Comment by samreid** [comment]
Developers will self-assign as above.

**Comment by samreid** [comment]
@pixelzoom asks when we should set the visibility annotations for old sims.

**Comment by samreid** [comment]
@jbphet points out that there are more issues at play than just visibility annotations.  When do we address them?

**Comment by samreid** [comment]
@jonathanolson finds it easy to "batch issues" and work on a group of them at once, though agrees it is good to keep code up to standard as we go.

**Comment by samreid** [comment]
@jessegreenberg says getting code up to standard is important for accessible content, though not sure *when* that work should be done.

**Comment by samreid** [comment]
@jessegreenberg points out that as we outfit sims for accessibility/phet-io we could get a better understanding of what quality level is acceptable and how much work should be done to standardize code before instrumentation will work well.

**Comment by samreid** [comment]
Consensus: we will leave it up to developers whether to keep things up to date (a) as we go (b) as the sim is republished or (c) before a developer leaves the team.

**Comment by samreid** [comment]
Since I have assigned https://github.com/phetsims/phetcommon/issues/25 to myself, I no longer need to have this issue assigned to me for my todo-list.  I'll reassign to @jbphet since he has a number of repos marked in the checkboxes above.

**Comment by pixelzoom** [comment]
11/17/15 consensus: Leave this open until all common repos are handled.

**Comment by aaronsamuel137** [comment]
I'll try to do this for color-vision before I leave.

**Comment by jbphet** [comment]
Discussed during the 12/3/2015 meeting and decided to close this, since there are individual issues in place for the remaining common code repos.  Individual developers are responsible for doing it for "their" sims, and an issues will be created for color-vision since the developer who ported it has left.  Closing.

**Comment by pixelzoom** [comment]
color-vision annotations moved to https://github.com/phetsims/color-vision/issues/98.
