### ISSUE TITLE
Redraw "John Travoltage" 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#309]
@mariahmaephet in the sim [**John Travoltage**](http://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_en.html) John's face and hand are from a picture to which we do not own the rights.

It would be good to redraw his face and hand - it can be _very_ close to the original, but it would be good for it to be our own.

You can find a .png here https://github.com/phetsims/john-travoltage/blob/master/images/body.png

But for the actual work please start from these .ai files:
https://github.com/phetsims/john-travoltage/blob/master/assets/arm.ai
https://github.com/phetsims/john-travoltage/blob/master/assets/body.ai

(to download the files click the "raw" button)

This work is part of https://github.com/phetsims/john-travoltage/issues/83

**Comment by samreid** [comment]
Please assign https://github.com/phetsims/john-travoltage/issues/83 to @samreid once the artwork is complete.  Please see this explanation https://github.com/phetsims/john-travoltage/issues/83#issuecomment-130497287 for why I've unassigned it for now.

**Comment by mariahmaephet** [comment]
@ariel-phet How does this look?
<img width="281" alt="screen shot 2016-01-27 at 3 00 45 pm" src="https://cloud.githubusercontent.com/assets/11527557/12629850/d759da28-c506-11e5-9d22-fe3ac2991bea.png">
<img width="489" alt="screen shot 2016-01-27 at 3 00 53 pm" src="https://cloud.githubusercontent.com/assets/11527557/12629851/d75d1b84-c506-11e5-9454-1172c00436f1.png">

**Comment by ariel-phet** [comment]
@mariahmaephet I think that is looking pretty good! Anyway you can drop him into a screenshot of the sim for scale and context?

**Comment by jessegreenberg** [comment]
@ariel-phet what is the status of this?  Should I add any new assets before I create an RC for the redeploy of John Travoltage?

**Comment by ariel-phet** [comment]
@jessegreenberg yes I think that would be good. I will get @mariahmaephet to upload a copy

**Comment by ariel-phet** [comment]
@mariahmaephet can you upload a cleaned up .ai file to your drive of this artwork? 

You and I will need to meet and discuss some other changes, but for the time being the current piece will go into our sim.

**Comment by mariahmaephet** [comment]
@ariel-phet what do you think of these? 
<img width="696" alt="screen shot 2016-03-20 at 3 17 58 pm" src="https://cloud.githubusercontent.com/assets/11527557/13906560/7fd289c6-eeaf-11e5-883c-04a4e6b78478.png">
<img width="703" alt="screen shot 2016-03-20 at 3 21 49 pm" src="https://cloud.githubusercontent.com/assets/11527557/13906561/7fd3cbec-eeaf-11e5-9b6d-729e3de02771.png">

**Comment by ariel-phet** [comment]
@mariahmaephet looking good! a few tweaks:

- lets make john's hair black in both
- in the first version it is important for his right hand to be in his pocket
- lets give the hand a bit more detail in both
- since the jacket and such have shading, the face in the first one seems a bit odd since it has no shading/chin line. the one flat tone does not seem to fit the rest of the piece
- I think in the first one, we still need the leg and arm to move in the same way as the original sim

**Comment by mariahmaephet** [comment]
How do these look? and the moving arm & leg are separate so you can have them move however much you want. 

<img width="448" alt="screen shot 2016-05-05 at 2 11 07 pm" src="https://cloud.githubusercontent.com/assets/11527557/15056251/de476778-12cd-11e6-97dc-db230530beff.png">
<img width="478" alt="screen shot 2016-05-05 at 2 14 51 pm" src="https://cloud.githubusercontent.com/assets/11527557/15056252/de4869b6-12cd-11e6-91cf-8b6c009f4631.png">

**Comment by ariel-phet** [comment]
Met with @mariahmaephet 5/10/2016 -- she is going to adjust position of left arm so that elbow is more forward as in the original sim (allowing full pivot). Also adjust left foot so that it will go flat to the ground

**Comment by pixelzoom** [comment]
6/9/16 status meeting: Don't forget to redraw his hand(s) to match the style of his head.

**Comment by pixelzoom** [comment]
6/9/16 status meeting: Don't forget to redraw his hand(s) to match the style of his head. Current iteration has an avatar-style head and photographic hand, which looks odd:

![screenshot_21](https://cloud.githubusercontent.com/assets/3046552/15939294/4364f428-2e34-11e6-8da8-ced8bb91258e.png)

**Comment by mariahmaephet** [comment]
@ariel-phet updating the arm and leg
<img width="606" alt="screen shot 2016-06-20 at 9 00 10 pm" src="https://cloud.githubusercontent.com/assets/11527557/16216675/0087ba38-372a-11e6-9807-1bef12689f20.png">

**Comment by pixelzoom** [comment]
Love the gold-toe socks.

**Comment by ariel-phet** [comment]
@mariahmaephet I think this is looking great, can you upload to your drive folder?

**Comment by pixelzoom** [comment]
My 2 cents... I really like the "pucker" of JT's lips in the original "photo" and in https://github.com/phetsims/tasks/issues/309#issuecomment-175882654. That's missing from the current image. Not a big deal, but it helps make him look a little goofier.

**Comment by jessegreenberg** [comment]
In the deployed version the left leg crosses over the right leg so that the draggable leg and electrons are always 'on top' of the rest of his body.  Would that work for https://github.com/phetsims/tasks/issues/309#issuecomment-227328131?  Otherwise, I am concerned that we will need to occlude the electrons behind the right leg or that it could be annoying to grab the left leg out from under the right one if it was dropped there.

**Comment by ariel-phet** [comment]
@jessegreenberg - the leg will be a separate piece of artwork and should stay layered on top, I think @mariahmaephet was just demoing the hinge point.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/tasks/issues/309#issuecomment-227542008 - Ok great.

**Comment by mariahmaephet** [comment]
@ariel-phet I realized I hadn't officially posted in here but the files for this are in my artwork folder if you haven't seen those already

**Comment by ariel-phet** [comment]
Closing this, as we seem to have not addressed this in 1.5 years
