### ISSUE TITLE
Test Bending Light Performance on iPad2 for a few scenarios

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#311]
Please test the performance for Bending Light in the scenarios given in: https://github.com/phetsims/bending-light/issues/153

There is a link there for testing and full details in the issue.  Please report your results in https://github.com/phetsims/bending-light/issues/153

@ariel-phet please delegate.

**Comment by ariel-phet** [comment]
Looks like @bryo5363 reported these results. Closing
