### ISSUE TITLE
PhET girl artwork for Trig Tour

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#313]
I need an image of PhET girl who looks like she just fell because she has been spinning around too much and is dizzy. Here is a rough idea:
![screen shot 2015-08-10 at 4 05 59 pm](https://cloud.githubusercontent.com/assets/7852916/9185513/bbc5bc22-3f79-11e5-9e4b-9577a55bc846.png)

I noticed in a lot of images that there is an "orbit" of stars around their head. Since this will appear after making theta too large in the Trig Lab sim, we would like to try using thetas instead of stars. We would also like the orbits, or spirals around the head, look like the simple black stroke seen in Trig Lab:

![screen shot 2015-08-10 at 4 04 22 pm](https://cloud.githubusercontent.com/assets/7852916/9185485/7dfb2d78-3f79-11e5-8d91-452139924b64.png)

It would be great to have a first stab by the end of this week or early next week.

**Comment by ariel-phet** [comment]
Hey @mariahmaephet, for some more context, here is a working version of the sim:

http://www.colorado.edu/physics/phet/dev/html/trig-lab/1.0.0-dev.16/trig-lab_en.html

You will notice that as you spin the red dot along the circle a spiral gets drawn that goes further and further out...we plan to have it stop when the spiral gets a bit bigger than the main circle (that is when this image will appear)

In contrast to the images above, I think it is important that PhET girl looks dizzy but still "smart" - we don't want to send the accidental message of math being hard...we want to make sure it is just whimsical and it might end up having some text that says "too many rotations!!" or such. She could even being spinning in sort of a figure skater/ballerina type pose so she looks active (but no tongue hanging out or such!)

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet like this? 

<img width="698" alt="screen shot 2015-08-18 at 2 14 19 pm" src="https://cloud.githubusercontent.com/assets/11527557/9341495/8b560a02-45b3-11e5-8279-5aeabeb7c247.png">
<img width="615" alt="screen shot 2015-08-18 at 2 15 00 pm" src="https://cloud.githubusercontent.com/assets/11527557/9341496/8b575f92-45b3-11e5-80cf-5f8a319b868e.png">

**Comment by amanda-phet** [comment]
They look great to me! Mike prefers the second one, but I think I like the first. It would be great to hear from @ariel-phet and @kathy-phet as well. 

@mariahmaephet can you go ahead and share the .ai file with me? We will be exporting this on a transparent background as well, if that affects any adjustments you want to make before sharing it.

**Comment by ariel-phet** [comment]
@amanda-phet the first one...she looks dizzy but happy in that one. In the second she looks upset.

**Comment by dubson** [comment]
I much prefer the second one.  In the first one, her smile makes it look like she's high. People don't smile when they're dizzy, except when they are high.  In the second one, the look is bemused, not upset.

**Comment by dubson** [comment]
When convenient, please give me png version so I can place in sim.

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet @dubson Is this a better in-between? (the .ai file 'dizzyphetgirl' is in my drive )

<img width="614" alt="screen shot 2015-08-23 at 5 05 59 pm" src="https://cloud.githubusercontent.com/assets/11527557/9430600/6e4595c2-49b9-11e5-927e-f2c9cb4ae111.png">

**Comment by ariel-phet** [comment]
@mariahmaephet - yes, I think that is a nice compromise, without the concerned eyebrows!

@dubson - does this look good to you?

**Comment by dubson** [comment]
love it!

**Comment by dubson** [comment]
Amanda,  where is your "my drive".    (the .ai file 'dizzyphetgirl' is in my drive ) -thanks! mike

**Comment by amanda-phet** [comment]
I emailed the image to you. I will email it again!

**Comment by dubson** [comment]
Hi Amanda, Got it.  Can I get an image without the white background?  I want phetGirl to appear in the sim without the background.  -thanks! mike

**Comment by mariahmaephet** [comment]
@amanda-phet @dubson I'm uploading a .png version (so no background) now. Amanda can forward that on to you!

**Comment by amanda-phet** [comment]
Thanks @mariahmaephet . It was transparent but my email converted it to a .jpeg and added the background! Apple mail is funky sometimes. 

I think we can close this issue now!
