### ISSUE TITLE
RC Testing for Molecules and Light

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#314]
Molecules and Light 1.1.0-rc.1 is ready or release candidate testing.

**Link to the file:**  http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.1/molecules-and-light_en.html

**Link to test matrix:** https://docs.google.com/spreadsheets/d/1SIuHF5V4TPR-H2FHugvL52cB6MvQ60gYgg-W-88A6mg/edit#gid=384018845

**Comment by ariel-phet** [comment]
@phet-steele @bryo5363 @orejolaphet @elisemorgan please make this sim your top testing priority.

Please note, some changes have been made "under the hood" to the navbar, so pay particular attention as to how the navbar layout looks (especially when doing string tests)

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over @pixelzoom's revamped code review checklist, decide if code review should be redone
- [ ] Review and update licensing info (source code and images/audio)
 - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md 
- [ ] Address RC issues and publish

**QA**
- [x] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] RTL language test
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by phet-steele** [comment]
Matrix complete.

**Comment by jessegreenberg** [comment]
Thank you @phet-steele.  New task here: https://github.com/phetsims/tasks/issues/332.  Closing.
