### ISSUE TITLE
Adjusting PhET Team page headshots

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#317]
@amanda-phet please describe to @mariahmaephet what you want done with the headshots. Assigning to you for the moment.

**Comment by amanda-phet** [comment]
As discussed with @mariahmaephet today, 8/19, she will make the pictures black & white and also brighten the faces of folks who had their picture taken on a sunny day. 

Another request, after playing around with some of the pictures myself... some "black and white" filters makes the picture look really gray and with not much contrast. (It could also be the colors in the original picture.) So, it would be great if they had some nice darks and lights and aren't too much like shades of medium gray.

**Comment by amanda-phet** [comment]
Also, Aaron is starting to work on the page and it needs to be live by the end of August. So, our timeline is pretty tight.

**Comment by mariahmaephet** [comment]
@amanda-phet Did you want color and b&w edits, or just b&w?

**Comment by amanda-phet** [comment]
Hm, if it's not too much trouble, the color edit could be nice so folks have a color version of their picture for other uses. The most critical piece is brightening the faces (however you do that) so if that's difficult to do while keeping the color looking good, then you can make a judgement call.

**Comment by amanda-phet** [comment]
Oops I meant to add a request above: 

Can you also crop them with a different aspect ratio? Kathy has requested that they be more like 8x10, and a little more zoomed in on the faces.

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet I'm uploading all of the edits now--they seem to already be 8x10? Would you still like them cropped in more?

**Comment by amanda-phet** [comment]
They are currently 2x3, so I'm not sure what you're seeing. Go ahead and upload the edits- I can always quickly crop them if they are not what Kathy wants!

**Comment by mariahmaephet** [comment]
@amanda-phet Ohhh you're right--one of my presets was labelled incorrectly. They should be done uploading in a few minutes

**Comment by amanda-phet** [comment]
They look SO good! I'm glad we went with b&w.

**Comment by amanda-phet** [comment]
There were some new ones taken in the last week, as well as 2 more coming on Wednesday. Do you want to wait until Wednesday to edit the final 6?

**Comment by mariahmaephet** [comment]
@amanda-phet I guess I might as well for them all at once on Wednesday

**Comment by amanda-phet** [comment]
Hey @mariahmaephet . The remaining 6 headshots are on drive!

**Comment by mariahmaephet** [comment]
@amanda-phet They're uploading now

**Comment by ariel-phet** [comment]
@amanda-phet - can this issue now be closed?

**Comment by amanda-phet** [comment]
Yes! I thought Mariah had closed it.
