### ISSUE TITLE
A fun PhET-girl 404 error page image

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#319]
@mariahmaephet - for when you are feeling inspired sometime...

@amanda-phet thought this might be another nice opportunity to connect with our users.

First, watch this 4 minutes video for some ideas:
http://www.ted.com/talks/renny_gleeson_404_the_story_of_a_page_not_found 

I was thinking maybe have safari PhET girl looking at a map scratching her head like she is lost. Or maybe make it look like she broke something in one of our sims or such? 

@amanda-phet had suggested maybe have her in the lab post-explosion, but I think that will be a bit on the violent side for @kathy-phet tastes...I would head towards more whimsical.

**Comment by ariel-phet** [comment]
And just as a note "wishlist" means lower priority than when time allows. Again, just when you feel inspired.

**Comment by mariahmaephet** [comment]
<img width="493" alt="screen shot 2015-09-29 at 2 29 05 pm" src="https://cloud.githubusercontent.com/assets/11527557/10177579/1336efde-66b8-11e5-9cf8-fc58a49b08fc.png">

**Comment by amanda-phet** [comment]
Looks perfect to me! We'll add this to the queue of website changes.

**Comment by mariahmaephet** [comment]
@amanda-phet uploaded to drive (phetgirl404page)

**Comment by amanda-phet** [comment]
Great. Thanks @mariahmaephet !
