### ISSUE TITLE
test auto-built installers that were created over the weekend

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#320]
In an attempt to track down an issue with the auto-build of the downloadable installers, the auto-build was scheduled to run on Sat Aug 15 2015.  From the logs, it appears that this build fully succeeded.  The resulting installers should be tested to make sure that they contain the sims, blogs, newsletters, and so forth.  For the activities-included version, the presence of several activities should be verified.  An exhaustive test would be too time consuming, so a reasonably thorough spot check is probably the best course of action.  I talked with @arnabp about this, and he has time today to do at least some of this testing.  We decided to do the testing on Windows only, at least for now.

The installers for Windows can be found here: http://www.colorado.edu/physics/phet/dev/installer-testing/2015-08-17/.  This link is not expected to be permanent, and I will likely remove the installers once testing is complete.

**Comment by arnabp** [comment]
I tested both versions and everything looks great! Non activity wouldn't load activities while offline and redirected to sign in page when online as expected. Activities would download the files without a hitch. The only noticeable issue was the flash on edge problem which I'll post on unfuddle tomorrow.
