### ISSUE TITLE
Create CLASS survey using Google Forms

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#321]
Hey @arnabp Can you recreate the following surveys in a google form (using either phethelp or phetstorage):
CHEM
http://www.colorado.edu/sei/surveys/Fall15/CLASSfa15-chem-1113-pre.html
http://www.colorado.edu/sei/surveys/Fall15/CLASSfa15-chem-1113-post.html
PHYS
http://www.colorado.edu/sei/surveys/Fall15/CLASSsp15-phys-1120-pre.html
http://www.colorado.edu/sei/surveys/Fall15/CLASSsp15-phys-1120-post.html
BIO
http://www.colorado.edu/sei/class/CLASS-Bio.html

**Comment by arnabp** [comment]
CHEM
http://goo.gl/forms/wszXyBHAZv
http://goo.gl/forms/nzGZEAqIQr
PHYS
http://goo.gl/forms/SLxrx6LhCM
http://goo.gl/forms/I9ldPeoD7p
BIO
http://goo.gl/forms/vwbvuBg2H7

**Comment by oliver-phet** [comment]
@arnabp Can you modify the questions to the template surveys (BIO, PHYS, CHEM) so that the questions are 1-5 responses. See example questions 1 in BIO: https://docs.google.com/forms/d/15yN7NSJJsrPnh7UIiXqrvLwfpDob8Fbqt4ukG5oR6H0/edit

CHEM: https://docs.google.com/forms/d/1QpWi2YAKTXPtYfkgCAtbwxT7eCtcQW8Euz4tpGsd43E/edit

PHYS: https://docs.google.com/forms/d/1Rj1oZ-kURjfoeeGGNgEp4RnXyTL9pchjZiOJTzSXyp8/edit

**Comment by arnabp** [comment]
Surveys have been updated.

**Comment by oliver-phet** [comment]
@arnabp Can you double check that all of the questions are present in the surveys? I noticed that the Physics survey was missing the question "I find that reading the text in detail is a good way for me to learn physics." (I fixed it, but check BIO and CHEM)
