### ISSUE TITLE
RC test: pH Scale 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#322]
Per @ariel-phet, I need to publish this and create the test matrix.

**Comment by pixelzoom** [comment]
RC version:
http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.0-rc.1/ph-scale_en.html

Text matrix:
https://docs.google.com/spreadsheets/d/1_GwEET-3UrACqvNyzWT-q8ANvvQGTFRVHYoXswjNDqs/edit#gid=1331742457

**Comment by pixelzoom** [comment]
Please halt RC testing. This is serious: https://github.com/phetsims/scenery/issues/455#issuecomment-133221684

**Comment by pixelzoom** [comment]
phetsims/scenery#455 was fixed and 1.2.0-rc.1 has been republished. Please resume testing.

**Comment by ariel-phet** [comment]
@elisemorgan @phet-steele @orejolaphet @bryo5363 - this testing should be next in line after molecules and light testing wraps up.

**Comment by pixelzoom** [comment]
This test task is on hold until we've done more beta testing of Rosetta. Assigning to me for now. I'll pass it back to @ariel-phet when I feel comfortable proceeding.

**Comment by pixelzoom** [comment]
I deleted 1.2.0-rc.1 from spot, will re-publish it when we resume RC testing.

**Comment by pixelzoom** [comment]
Unassigning until we resume RC testing.

**Comment by pixelzoom** [comment]
@ariel-phet said that ph-scale may not be first on the redeploy schedule. Assigning this back to him.  Assign back to me with instructions when ready.

**Comment by pixelzoom** [comment]
Since we'll be starting over on RC testing, I deleted the '1.2' branch of ph-scale-basics.

**Comment by pixelzoom** [comment]
@ariel-phet said to roll a release candidate, pending https://github.com/phetsims/acid-base-solutions/issues/138 (Chromebook layout issue).

**Comment by pixelzoom** [comment]
Since this RC test was aborted awhile back, I'm going to close this issue and start fresh, so that we don't have any confusion.
