### ISSUE TITLE
Add all troubleshooting and FAQ questions to google spreadsheets 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#324]
@phet-steele Can you copy paste (or re-type if you have to) all of the questions at the following URLS to the google spreadsheet below? Try to put them in the proper category (columns A-G), but use 'Not Sure' if there isn't a category that fits.

https://phet.colorado.edu/en/troubleshooting
https://phet.colorado.edu/en/troubleshooting/mac
https://phet.colorado.edu/en/troubleshooting/windows
https://phet.colorado.edu/en/troubleshooting/linux
https://phet.colorado.edu/en/troubleshooting/mobile (make into questions)
https://phet.colorado.edu/en/faqs
http://phet.colorado.edu/en/webgl-disabled-page

Add them this: https://docs.google.com/spreadsheets/d/1jirckePXaztwuackBhsqo2OfyKUCj81IloF9dhSpQOs/edit#gid=1937297895

**Comment by phet-steele** [comment]
Done, @oliver-phet . The questions in the "Getting Started" and "Running Sims - General" categories were ambiguous to me as to where they should go, so change those around if my judgement calls weren't the best.

**Comment by oliver-phet** [comment]
DOne.
