### ISSUE TITLE
regenerate all README files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#325]
When `babel` was introduced as a new dependency for all sims, the README.md files (for published and unpublished sims) were not regenerated. So the "Quick Start" instructions with commands to clone the needed repos are wrong.

Assigning to @jonathanolson since he added the new dependency.

**Comment by samreid** [comment]
Possibly related to https://github.com/phetsims/chipper/issues/311 

Sims can be launched in requirejs nonbuilt mode without babel, but cannot be built without babel (even if just building the english version).  So this is a high priority issue to resolve.

**Comment by samreid** [comment]
The failure when building the english version is:
Fatal error: ERROR on git SHA attempt: code: 128, signal: null with stderr:
fatal: Not a git repository: '../babel/.git'

**Comment by pixelzoom** [comment]
> Possibly related to phetsims/chipper#311

Not related to phetsims/chipper#311.  Non-English html files don't build because babel is a required repo. In afterRequirejsBuild.js:

`88 basePath = repository.path + '/../babel/' + repository.name + '/';

**Comment by jonathanolson** [comment]
Failures:
```
jon@LINE ~/phet/git/balloons-and-static-electricity (master)
$ grunt published-README
Running "published-README" task
Warning: Cannot read property 'value' of undefined Use --force to continue.

Aborted due to warnings.
```

**Comment by jonathanolson** [comment]
Presumably beaker/blast/etc. shouldn't have this done?

**Comment by pixelzoom** [comment]
Not sure why balloons-and-static-electricity is failing for this, I'll investigate.  I works fine for a half dozen other sims that I tried, e.g.:

```
% cd john-travoltage
% grunt published-README
Running "published-README" task

Done, without errors.
%
```

**Comment by pixelzoom** [comment]
> Presumably beaker/blast/etc. shouldn't have this done?

* `grunt published-README` for sims that have been published to the PhET website.
* `grunt unpublished-README` for sims that are in pre-1.0 development.
* No grunt task for common-code repos, they have their own specific README.md files.

**Comment by pixelzoom** [comment]
generateREADME.js is probably failing at line 25:

```js
23 var strings = grunt.file.readJSON( '../' + repositoryName + '/' + repositoryName + '-strings_en.json' );
24 var titleKey = simTitleStringKey.split( '/' ).pop(); // eg. 'EXAMPLE_SIM/example-sim.name' -> 'example-sim.name'
25 var title = strings[ titleKey ].value;
```

**Comment by pixelzoom** [comment]
Bug introduced in https://github.com/phetsims/balloons-and-static-electricity/commit/ea7b00aaf1d6a7dc980052ec9c77ff899a494ef9. simTitleStringKey was changed in the strings file, but not in package.json.

**Comment by pixelzoom** [comment]
@samreid Presumably you change balloons-and-static-electricity in reaction to https://github.com/phetsims/chipper/issues/302. Did you change simTitleStringKey for any other sims?

**Comment by pixelzoom** [comment]
@jonathanolson Elaborating on https://github.com/phetsims/tasks/issues/325#issuecomment-134329117... README.md files need to be generated for published sims only. They are the only README.md files that expose the dependencies, via clone commands listed in the "Quick Start" section. Easiest way to do this is probably to edit your working copy of active-runnables so that it includes only published sims, then run `grunt-all.sh published-README`.

**Comment by samreid** [comment]
> @samreid Presumably you changed balloons-and-static-electricity in reaction to phetsims/chipper#302. Did you change simTitleStringKey for any other sims?

Sorry, I don't recall.  Is there an easy way to check what other sims suffer from this kind of problem?

**Comment by pixelzoom** [comment]
`grunt-all.sh published-README` (but don't commit, because https://github.com/phetsims/tasks/issues/325#issuecomment-134333658).

**Comment by jonathanolson** [comment]
> Easiest way to do this is probably to edit your working copy of active-runnables so that it includes only published sims, then run grunt-all.sh published-README.

No, seems like I need to handle unpublished sims too. Had to go through by hand.

**Comment by jonathanolson** [comment]
Description of issue was "all" READMEs, not just published ones.

**Comment by pixelzoom** [comment]
> Description of issue was "all" READMEs, not just published ones.

You asked: https://github.com/phetsims/tasks/issues/325#issuecomment-134323166.
I replied: https://github.com/phetsims/tasks/issues/325#issuecomment-134333658

**Comment by jonathanolson** [comment]
> You asked: #325 (comment).
> I replied: #325 (comment)

The issue description states:
> the README.md files (for published and unpublished sims)

I had taken care of manually going through the sims before you replied with https://github.com/phetsims/tasks/issues/325#issuecomment-134333658, which might have saved some time.

Let me know if there are any issues however, since many unpublished sims show changes (states-of-matter-basics, function-builder, rutherford-scattering, protein synthesis, etc.). I can revert updates to non-published sims if needed.

**Comment by pixelzoom** [comment]
You're obviously put out with having to deal with this. Sorry you feel that way.

**Comment by jonathanolson** [comment]
> You're obviously put out with having to deal with this. Sorry you feel that way.

Not particularly, I just don't want to have committed things incorrectly that shouldn't have been done (does regenerating unpublished READMEs cause issues?) since what was in the issue description was different than what was desired.

**Comment by samreid** [comment]
I looked to see what change occurred in protein-synthesis, it was just changing the phrase:

> the sims, as well as other important issues.

to

> the sims, as well as other important information.

So this seems good.  Anything else to do here?
