### ISSUE TITLE
Summer Teachers'  Metadata Project

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#326]
At @patricialoeblein request:

Complete the summer teachers' projects of keyword/category metadata and course/standards alignment docs. The keywords and categories need to be sorted, reviewed, and added to the website. The standards need to also be sorted and added, as well as made into docs to be uploaded to the website.

**Comment by phet-steele** [comment]
As a quick update: all of the "Trish-mediated" work has been done. What's left to do is wait for an internal review of suggested keywords by myself and whomever @kathy-phet desires to look over them :smile:.

**Comment by amanda-phet** [comment]
Are these keywords for sims or activities? Just curious, so if anyone wanted to see the results, they would know where to go (since sim keywords are not public).

**Comment by ariel-phet** [comment]
@phet-steele can you answer the question above?

**Comment by phet-steele** [comment]
@amanda-phet @ariel-phet sims!

**Comment by phet-steele** [comment]
@arouinfar hi!

**Comment by arouinfar** [comment]
@phet-steele @amyh-phet and I have been working on a general template for PhET metadata. I've started filling in the relevant data for the HTML5 sims, but there is still some work that would be good for @phet-steele to take care of. You can find the spreadsheet in the "PhET Metadata Template" Google sheet.

- [ ] Ensure that the keywords in columns D, E, H, I in the Copy of Metadata Project 2015 file in the Metadata Template folder have been added to the database and sims have been tagged appropriately.
- [ ] Ensure that column G (Keywords) of the PhET Metadata Template includes the extra keywords from the step above -- they probably will need to be added manually
- [ ] Fill in columns H, I, N, R, S using the data on the sim pages.
- [ ] Fill in column J (Grades) using the PhETMetadata_DoNotLoad_revisedLearningObjectives.xlsx file in the Metadata Template folder. The relevant data can be found on the CurriculumItems sheet in columns C&D. If a sim has an upper grade level of 12, but it can be used at the University level, please enter a 16 instead. (Do this in the PhET Metadata Template file, not the .xlsx.)
- [ ] Convert Grades to Ages (Column K) by adding 5 to the low grade and 6 to the high grade.
- [ ] Fill in column AC (NGSS) using columns F & G from the Copy of Metadata Project 2015 file in the Metadata Template folder.
- [ ] Data for column AE (CCSS-M) can be found by going to the Standards sections of the design docs of relevant math sims
- [ ] Fill in columns L & M (date created/updated). I know the data exists somewhere, but I'm not sure where.

I also have a few larger questions...
* If this data will be delivered as a .csv, can there be commas in the cells?
* If so, we probably need to use semicolons to separate items that contain commas such as Sub-Category & Learning Goals. I've already done this in the Sub-Category column.

**Comment by arouinfar** [comment]
Actually, @ariel-phet should assign a priority for this task, so reassigning.

**Comment by phet-steele** [comment]
@arouinfar done, back to you.

**Comment by arouinfar** [comment]
I'm going to go ahead and close this issue. The original goal has been achieved. We reviewed the spreadsheet created by Trish's working group, and verified that the appropriate categories were tagged on the website. It's unclear what (if any) work needs to be done on the template we created. I will open new issues, if anything else arises.
