### ISSUE TITLE
Test release candidate 4 for charges and fields

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#327]
A new release candidate was published here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.4/

And the test matrix is here: https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=320070127

I have used some new SHAS for this release candidate.  As far as the QA team is concerned, this means that one should **NOT** assume that if something worked well in a previous release candidate, then it will perform well in this release candidate. In other words, do not take anything for granted and test thoroughly this release candidate (as if it was the first release candidate).

In addition, you should test the canvas version by setting webgl=false on chrome and firefox and ie.

Reassigning to @ariel-phet to prioritize and reassign.

**Comment by ariel-phet** [comment]
Hey @phet-steele - please chip away at this testing in between our summer redeploy testing.

**Comment by veillette** [comment]
So far, three issues have been raised as part of this task

https://github.com/phetsims/charges-and-fields/issues/63
https://github.com/phetsims/charges-and-fields/issues/64
https://github.com/phetsims/charges-and-fields/issues/65

@phet-steele: Two Questions: 
What is the current status on this task? It it considered done?
 
In addition, I see a bunch of slash in the test matrix with the iPad 2. Does it mean that it shouldn't be in the matrix in the first place or does it mean something else?

**Comment by phet-steele** [comment]
The slashes were put there in response to http://github.com/phetsims/tasks/issues/330#issuecomment-135515636. @ariel-phet please clarify if you meant we are no longer testing iOS7 in general, or just iOS 7.0.

As far as the status of testing this goes, RC testing was temporarily placed on hold while getting ready for our HTML5 translation utility to be beta tested. I think the utility is basically done (aside from a few things that I need to add to its help document) and RC testing as a whole can be done again shortly!

**Comment by ariel-phet** [comment]
@phet-steele - we have dropped iOS7 support for PhET sims.

**Comment by ariel-phet** [comment]
Closing, since with all the changes this sim will need to have another RC.
