### ISSUE TITLE
Naming for Util

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#328]
We have a few different conventions for our Util classes.

Util.js found in dot, mobius, scenery, optics-lab, trig-tour
Utils.js found in shred, build-an-atom
Sim-specific util files as noted below, such as ChipperStringUtils.js
![image](https://cloud.githubusercontent.com/assets/679486/9446076/d98b7714-4a4c-11e5-9d5f-9b3a50816d55.png)

It would be nice to standardize on a naming for our utility files.  Also, we decided long ago to use full names instead of abbreviations for many things--util seems to be one of the last holdouts.  Let's discuss where to go from here.  Also note having many files with the same name causes import conflicts and difficulty when navigating by filename.

Discovered this issue during https://github.com/phetsims/chipper/issues/116

**Comment by jbphet** [comment]
Discussed at 8/25/2015 meeting and the consensus was that this doesn't bother us too much but if someone wants to make them consistent, it would make life slightly easier.  Either Util or Utils is fine.

**Comment by pixelzoom** [comment]
It would make life slightly easier if we picked either 'Utils' or 'Util' and used it consistently.  I don't feel a need to expand to "Utilities", since it's such a common abbreviation.

**Comment by samreid** [comment]
What about renaming DOT/Util to DOT/DotUtil so that you can use it together with other Utils?

**Comment by pixelzoom** [comment]
> What about renaming DOT/Util to DOT/DotUtil so that you can use it together with other Utils? etc.

See https://github.com/phetsims/dot/issues/4

**Comment by samreid** [comment]
Ah right, thanks for reminding me about the dot issue.  I'll unassign this.

**Comment by ariel-phet** [comment]
What is the status of this issue, seems to have gone a bit stale?

**Comment by pixelzoom** [comment]
The consensus (summarized in https://github.com/phetsims/tasks/issues/328#issuecomment-134664688) is that this is a minor inconvenience and a major pain to change, so someone will work on it if/when they feel the urge. Imo it's not tragic if it's never addressed; we have much bigger fish to fry.

**Comment by ariel-phet** [comment]
considering comment above, closing
