### ISSUE TITLE
Update Lave information

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#330]
Hey @elisemorgan, can you get some clear labels on Lave that say to leave it on iOS 7?

**Comment by elisemorgan** [comment]
@ariel-phet Done, but it hasn't been reverted to iOS 7. @arnabp can you revert it?

**Comment by ariel-phet** [comment]
Reverting cannot be done easily apparently. We have decided to no longer test iOS7. Please remove the label from Lave, update to the latest iOS version, and then update the Assett matrix.

**Comment by elisemorgan** [comment]
@ariel-phet The asset inventory is updated

**Comment by ariel-phet** [comment]
excellent, closing
