### ISSUE TITLE
test Rosetta using a sim that draws most strings from other repos

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#331]
Atomic Interactions should serve as a good test case for this, since it draws all but one of its strings (the title) from the states-of-matter repository as well as possibly some common code repos.  @aaronsamuel137 has set Rosetta up such that it should be able to translate this sim, let's test and see how it does.

**Comment by ariel-phet** [comment]
@phet-steele please coordinate with @jbphet to complete this test. Submit issues in the rosetta repo

**Comment by phet-steele** [comment]
Done.
