### ISSUE TITLE
RC testing for Molecules and Light 1.1.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#332]
Molecules and Light version 1.1.0-rc.2 is ready for release candidate testing.  

**File:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.2/molecules-and-light_en.html

**iFrame:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.2/molecules-and-light_en-iframe.html

**Test Matrix:** https://docs.google.com/spreadsheets/d/1SIuHF5V4TPR-H2FHugvL52cB6MvQ60gYgg-W-88A6mg/edit#gid=1266819276 

**NOTE:**
This RC does not need full testing, but should be spot checked for the following issues:

- [x] Please make sure that https://github.com/phetsims/molecules-and-light/issues/120
has been resolved on all platforms with stringTest=someCrazyLongStringThatWouldLikelyBreakSpectrumWindowBounds...

- [ ] There was an update in joist where screen layout fires events.  It would be good to make sure that nothing is broken when the layout is resized.

- [x] Overall, we want to make sure that the molecular formulas look good in Internet explorer, and strings are not distorted or go out of bounds with stringTest=double.

**Comment by ariel-phet** [comment]
@elisemorgan @bryo5363 @phet-steele @orejolaphet please make this your current top testing priority. 

As mentioned above this can be a quicker test checking the checklist issues.

**Comment by bryo5363** [comment]
The strings do not go over the bounds on IE 11. We haven't seen any issues with strings so far.

**Comment by jessegreenberg** [comment]
That is great to hear, thanks for testing.  In the mean time, please stop testing of this release candidate.  We will have a new release candidate out soon to include some internal changes to joist and chipper. ( https://github.com/phetsims/molecules-and-light/issues/123 )

**Comment by elisemorgan** [comment]
@jessegreenberg Has testing resumed for this? I'm seeing on the dev that a new RC was published on 9/1.

**Comment by ariel-phet** [comment]
@elisemorgan - yes please resume testing with that RC

**Comment by elisemorgan** [comment]
@ariel-phet Testing matrix is complete

**Comment by ariel-phet** [comment]
Closing since test is complete
