### ISSUE TITLE
Rosetta beta testing with published S2015R Molecule Shapes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#333]
**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over @pixelzoom's revamped code review checklist, decide if code review should be redone
- [x] Review and update licensing info (source code and images/audio)
 - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md 
- [x] Address RC issues and publish

**QA**
- [x] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [x] RTL language test
- [x] Perform RC testing
 - [x] Include full screen test

**Design/Admin**
- [x] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@aaronsamuel137 and @oliver-phet we now have a sim we can beta test with translators live on the website. We should think about how best to proceed and if things are ready for a "live" dry run.

@oliver-phet - maybe give me the contact info I will need over email to contact some trusted translators.

**Comment by pixelzoom** [comment]
Issue to create doc for using Rosetta beta: https://github.com/phetsims/tasks/issues/335.

**Comment by aaronsamuel137** [comment]
We are going to go ahead with this. I will set up figaro with Rosetta and master branch of babel, then @ariel-phet will contact a trusted translator for the beta testing.

**Comment by aaronsamuel137** [comment]
We are ready for testing with trusted translators on phet-dev. molecules-and-light and concentration are up and ready to go.

Trusted translators must be marked as such on phet-dev (and probably on the main site too just so we don't forget). To do this, go into the admin section under users and edit another users profile. You'll need their phet email address to do this.

Assigning to @ariel-phet. Let me know if you have questions.

**Comment by aaronsamuel137** [comment]
Note that babel is now on branch master, so any changes they make to strings will show up even when we switch to figaro.

**Comment by aaronsamuel137** [comment]
The URL they start from is https://phet-dev.colorado.edu/translate/.

**Comment by aaronsamuel137** [comment]
Before we tell the trusted translator, there are a few clean up items that we decided to take care of, suggested by @pixelzoom. I'll let you know when it is ready.

**Comment by ariel-phet** [comment]
Closing this issue...we will have the updated checklist when we are ready for the newest RC.
