### ISSUE TITLE
document basic instructions for using Rosetta beta

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#335]

**Comment by pixelzoom** [comment]
Make sure this issue is addressed in the documentation: https://github.com/phetsims/rosetta/issues/48 (Unused strings are available to translate).

**Comment by ariel-phet** [comment]
@phet-steele since you are the most experienced user of Rosetta, could you create a google doc with instructions for translating a sim, including screen shots? When you have a document together please reassign to me so I can edit and add some caveats. Thanks!

**Comment by phet-steele** [comment]
If certain changes are made, I'll need to change some wording and the majority of the screenshots.

**Comment by phet-steele** [comment]
@ariel-phet I've updated the doc to match the new UI changes.

**Comment by ariel-phet** [comment]
Awesome I will check it out

**Comment by ariel-phet** [comment]
Looks good, will use for the Beta test, closing!
