### ISSUE TITLE
Upload all team profiles to Our Team page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#338]
We would like @phet-steele or @elisemorgan to upload the individual profiles and photos from the team bios doc via the administration page. See https://github.com/phetsims/website/issues/256. 

@phet-steele @elisemorgan  When are you working next? We need to coordinate the deployment of the new team page with when you are working so that the profiles can be promptly uploaded.

**Comment by ariel-phet** [comment]
Student work avaibility calendar says @elisemorgan should be around 2-5 pm today (but not sure if up to date).

**Comment by aaronsamuel137** [comment]
Ideally, we'd like to do this late afternoon or evening. I could aim to deploy around 4pm today if that works for @elisemorgan, or else we can set up a time for next week.

**Comment by ariel-phet** [comment]
@elisemorgan - also note this task should be considered top priority over any testing tasks when you are available

**Comment by amanda-phet** [comment]
@elisemorgan I've shared the necessary google drive folder with you that contains the Team Bios doc and Final B&W folder of headshots.

**Comment by elisemorgan** [comment]
@ariel-phet @amanda-phet I apologize for any inconvenience but that availability is no longer up to date and was a mistake on my part - I mixed up my schedule. I can get to this tonight or tomorrow if need be but no sooner. This week has been crazy, but I will be much more available next week.

**Comment by ariel-phet** [comment]
@elisemorgan - no problem, just let @aaronsamuel137 know in this issue when you will be available (ideally early next week), so we can schedule things smoothly.

**Comment by elisemorgan** [comment]
@aaronsamuel137 Monday 2-4 is my best time early next week and I'm available after 5 that day to finish stuff up. Does that work?

**Comment by amanda-phet** [comment]
I'm also available Monday afternoon and can help out. It shouldn't take us more than an hour, I would imagine.

**Comment by aaronsamuel137** [comment]
Monday should work fine. I am thinking I will deploy Sunday night so there is no potential to interrupt classroom use of the website. A few hours on Monday without a team page shouldn't be a big deal. Does this sound okay to you @ariel-phet?

**Comment by ariel-phet** [comment]
That sounds totally OK...our team page can be broken/in progress for awhile.

**Comment by aaronsamuel137** [comment]
The new team page is up. Feel free to start adding team members at your earliest convenience.

**Comment by elisemorgan** [comment]
Done, Steele did most of it

**Comment by ariel-phet** [comment]
Looks great!
