### ISSUE TITLE
Test Mac OS X 10.10-beta (Yosemite)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#34]
This is a similar need to iOS8-beta testing, https://github.com/phetsims/tasks/issues/28. It would be advantageous to find problems and report to Apple before 10.10 is generally released.  I'm not sure who should do this, or what hardware should be used. Assigning to @oliver-phet.

**Comment by ariel-phet** [comment]
Since Mac OSX 10.10.2 is now part of our testing matrix, I am closing this issue
