### ISSUE TITLE
Molecule Shapes 1.1.1-rc.1 RC testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#340]
Molecule Shapes 1.1.1-rc.1: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.1-rc.1/molecule-shapes_en.html, testing matrix: https://docs.google.com/spreadsheets/d/1wfA1SVvOKK-d26ozNNeGDuuq5OtUpInGcEkfK_Eqvgg/edit#gid=100360333

Molecule Shapes is mainly an update to common code (https and statistics fixes). Normal testing on a single platform, and then light testing across all platforms is what I'd recommend.

**Comment by jonathanolson** [comment]
Removed Molecule Shapes: Basics from this issue, as it seems best to put it on hold until more translator testing is done.

I'd like to get the Molecule Shapes statistics fixed ASAP, however.

**Comment by jonathanolson** [comment]
@ariel-phet, any preferences on testing for this? Should I test myself and redeploy, so we can get the fixed stats up?

**Comment by ariel-phet** [comment]
@phet-steele can you burn through this test this morning? Should be pretty quick.

**Comment by phet-steele** [comment]
On it.

**Comment by phet-steele** [comment]
Fin.

**Comment by ariel-phet** [comment]
Magnifique @phet-steele.

@jonathanolson - looks like you can publish this fix and close this issue.

**Comment by jonathanolson** [comment]
Will handle deployment tomorrow, VPN is causing some issues with production deploy.

**Comment by ariel-phet** [comment]
no worries, sounds good.

**Comment by jonathanolson** [comment]
Closing since it was published (I just tested and verified statistics collection).
