### ISSUE TITLE
Fill in FAQ answers

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#341]
@phet-steele The spreadsheet you filled in with the troubleshooting and FAQ questions has been super helpful. We've organized them a bit and added some new ones. Now we need the answers! Can you please fill in the answers from the website in the column to the right of each question? (If the column is hidden you'll see two arrows so you just need to make it visible). 

Thanks!

**Comment by phet-steele** [comment]
@amanda-phet this isn't the prettiest thing I've done, but it's mostly done. There are some green questions left unanswered as I figured it was better for someone else to get the wording right.

**Comment by oliver-phet** [comment]
Done.
