### ISSUE TITLE
sims have no team lead 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#342]
While working on resolving issues for S2105R, I'm repeatedly running into a problem: The team leader (or person who reported the issue) is no longer with the project. So I don't know who to assigning the issue to for questions or verification.  The sim that are currently have no team leader are as follows...

Yuen-ying (@ycarpenterphet) was team lead for:
atomic-interactions
balancing-chemical-equations
ph-scale / ph-scale-basics
reactants-products-and-leftovers

Julia (@learnthinkteach) was team lead for:
beaker
beers-law-lab / concentration
molarity

Assigning to @ariel-phet for guidance on who should be the contact person for the above sims.

**Comment by ariel-phet** [comment]
These are all chemistry sims. The lead for questions should be @amyh-phet - she can always turn to me if she needs advice.

**Comment by pixelzoom** [comment]
Got it. Closing.
