### ISSUE TITLE
[hookes-law] test 1.0.0-dev.29

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#343]
Hooke's Law is ready for dev testing.

**Dev version:**
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.29/hookes-law_en.html

Please test on the following platforms:
- [x] iPad2 iOS 8 
- [x] Windows Chrome
- [x] Mac Safari 

**Available query parameters:**
dev - Shows the "safe bounds" of the screen, selects all check boxes.

**Comment by ariel-phet** [comment]
@elisemorgan - can you take a look at dev testing this sim? Should be a fun one! As usual, report any issues in the sim repo.

**Comment by elisemorgan** [comment]
I can start a little bit this afternoon.

**Comment by elisemorgan** [comment]
@ariel-phet @pixelzoom The platforms listed above have been tested

**Comment by ariel-phet** [comment]
Thanks, closing!
