### ISSUE TITLE
Resize Team photos

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#344]
We need each team member's photo (found in the google drive folder "Final B&W") resized so that they have a width of 480px. Please use software that allows the photos to still be 'high quality' when resizing. 

1. Make a new folder and add the resized photos there, then add that folder to drive. 
2. Have someone review a resized photo to be sure the quality still looks good. 
3. Sign on to the site and click on Administration > Team Page > Edit 
4. Edit each profile and upload the new smaller photo.

**Comment by aaronsamuel137** [comment]
Where did the width of 480px come from? You could do a width of 304px and it would still be double resolution for the largest photos on the page (Kathy's and Carl's).

If you really want to be precise you could do double resolution for each individual role exactly, so 240px for team members and 200px for undergrads. Might be overkill to do this though.

**Comment by amanda-phet** [comment]
480 came from 4x120, the width of the team photos. I forgot about the larger photos for Kathy and Carl. Let's go with 304 if you think double is adequate.

**Comment by aaronsamuel137** [comment]
Double is adequate in my opinion. No real advantage to going higher since the browser will just scale it down anyway (until they come out with "double-retinas" or something). Definitely a good idea to save the original high res photos in drive though.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I had suggested 4 times bigger since 4K displays already exist (though fairly rare at the moment). But we can always up the resolution when they become more prominent :).

**Comment by arnabp** [comment]
I have to run for the day, but I put all the resized photos in a separate folder in the drive. Preview resampled them so they all look great, but you're free to check yourself. I'll have them uploaded to the website tomorrow.

**Comment by amanda-phet** [comment]
I think they look great. Tomorrow is fine to upload them to the website, but let me know if that doesn't happen so I can make sure it gets done by the end of the day tomorrow.

**Comment by arnabp** [comment]
All resized photos are up!

**Comment by amanda-phet** [comment]
Yes, it can take a while to update. We can wait a bit before closing the issue. I'll check as well.

**Comment by arnabp** [comment]
Site seems to have updated, everything looks good?

**Comment by amanda-phet** [comment]
Looks great. Thank you @arnabp !
