### ISSUE TITLE
Sponsor page mockup

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#345]
@daveunderwood our current "sponsor" page needs some love

http://phet.colorado.edu/en/about/sponsors

Right now it is tough to discern the different levels of sponsorship, and every logo is a different size and such.

We were wondering if we could get two mockups of an improved page:

1. A mockup with no logos (something like [this example] (https://www.khanacademy.org/about/our-supporters) from Khan Academy)

2. A mockup with logos of our sponsors, but the sponsor logos sized more consistently, and with small text listing the logos. Something like [this gridded example] (http://www.attpac.org/give-and-get/got-a-company/sponsorship/our-sponsors). Not the best example but gives the idea of what we were thinking.

**Comment by daveunderwood** [comment]
These sponsor inventories are a nightmare for designers. They often end up looking like a NASCAR entry. Ugh. That said, here's one idea. Simply flipping the format helps a lot - logo (all of which are aligned right) first, text next, justified left. That way we have an even gutter right down the middle, just like you see in movie credits. Also, logos should be sized first so as not to have wild jumps in scale AND logos reversed out of solid blocks should be inverted or rebuilt so as not to look "horsey."

![sponsors_1](https://cloud.githubusercontent.com/assets/13662881/9689680/e5083cca-52f4-11e5-819f-80332f4d98f3.jpg)

**Comment by daveunderwood** [comment]
@amanda-phet I was told you'd want to see this by @ariel-phet

**Comment by amanda-phet** [comment]
I like this a lot (of course!). I am pretty sure Kathy will want the logos so this seems like a great option for the page. Unfortunately, the page will be long with all the sponsors, but I like how the title makes it easy to see where the sections begin. 

Also, can you please clarify what you mean here:
>logos reversed out of solid blocks should be inverted or rebuilt so as not to look "horsey."

**Comment by ariel-phet** [comment]
@amanda-phet .... @daveunderwood was referring to a logo like the top one which had white text in a big green block. So he reversed it to be just the text and made the text green. So removing boxes where possible.

**Comment by amanda-phet** [comment]
I see. Many places have multiple versions of a logo so we can investigate that. Hewlett, for example, has a version with a white background.

**Comment by ariel-phet** [comment]
Sponsors page is updated, this issue no longer seems necessary. Closing
