### ISSUE TITLE
Find updated sponsor logos

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#347]
After a brief bit of searching, I found that many of the logos on our sponsors page are outdated. It would be great to have an undergrad find each sponsor's most current logo. 

I'd start by clicking on the direct link to their page (from https://phet.colorado.edu/en/about/sponsors) to see an obvious new logo. Then, google "x logo" to see if the company (usually the larger ones) has a branding page. They often share the official assets for downloading. If the company does not have a branding page, we can just right-click on the logo on their main web page and then view the image or "save image as...". Ideally, the version we want for every logo is one that does not have a colored background. 

Make a folder with all logos, named appropriately, and share it in google drive.

**Comment by ariel-phet** [comment]
@elisemorgan - this would be a nice little task to complete, but not very high priority. Good to do when testing work is slow.

**Comment by ariel-phet** [comment]
@elisemorgan - as part of this task ca you also verify sponsor links? It seems some are broken, such as in https://github.com/phetsims/website/issues/233

Perhaps when you do this task also create a simple spreadsheet with sponsor name, link to proper logo, link to proper website, and note if current link is broken on our site.

Thanks!

**Comment by amanda-phet** [comment]
We decided to up the priority of this issue at today's website design meeting. I'll leave it to @ariel-phet to prioritize for @elisemorgan .

**Comment by elisemorgan** [comment]
Sorry, I let this slip by! I can tackle it during my hours tomorrow.

**Comment by ariel-phet** [comment]
@elisemorgan good to keep the main focusing on testing, but would be great if you work on this tomorrow!

**Comment by elisemorgan** [comment]
Here is the spreadsheet that I started for this today https://docs.google.com/spreadsheets/d/1BPfMCA0-p5AB3sTYIDNqmKuikzjpE5MYsDSfQBXMR7A/edit?usp=sharing

**Comment by amanda-phet** [comment]
This looks great to me. The website cells that are empty- is the current website already correct? It might be good to just have them all filled in. 

Thanks for finding the updated logos as well. Should we assume the remaining logos stay the same? Or are you planning to upload them all?

**Comment by elisemorgan** [comment]
Yes, the empty cells assume that the current website is correct. I will fill them all in so that it is consistent. The logos are blank because I was immediately able to find a good file. I will also fill those in, but if they are blank assume that they stay the same.

**Comment by elisemorgan** [comment]
@amanda-phet All sponsors have been checked and are recorded on the spreadsheet

**Comment by mattpen** [comment]
@elisemorgan Should the sponsors marked in red in the spreadsheet be removed?  Or should we keep the name in the list and remove just the link and/or logo?

**Comment by amanda-phet** [comment]
I believe @kathy-phet wants to look over the sponsors and potentially make a section for past sponsors. As of now, do not remove any sponsors. I will figure out something for the logos. 

@mattpen  if you are updating logos, can you talk to @aaronsamuel137 about the sizing? The logos that show up on a sim page have a max height but the logos on the home page and sponsors page do not. A big change that needs to happen with this issue is fixing the max height and width so that logos are not wildly different in size.

**Comment by mattpen** [comment]
@amanda-phet I can make all the logos have a max height/width on the About Sponsors page specifically.  We don't need to change the image files themselves to make this happen.  Once Aaron has the front page deployed to the main site I can put up what I have done so far for review.

**Comment by mattpen** [comment]
@amanda-phet @elisemorgan - I have a few questions about some of the sponsors.

***Theresa Neil*** - There is a logo up on the website already.  Should the image be removed?
***C. Wieman and S. Gilbert*** This sponsor was not listed in the spreadsheet. Do they have a logo/website or should it be left as is?
***Gordon and Betty Moore Foundation*** -  This looks new.  Which level of sponsor is this?

**Comment by mattpen** [comment]
The Texas Instruments logo has a large whitespace on the right side.  Is this the right logo?

**Comment by amanda-phet** [comment]
**Theresa Neil** - Just use the current logo.
**C. Wieman** - keep them listed but there is no logo
**Moore Foundation** - I am pretty sure they are Platinum Level. 

**Texas Instruments** - that is the official logo from their site... however I think we should crop it. I will do that now and upload a cropped version.

**Comment by elisemorgan** [comment]
@mattpen The sponsors with a red X have broken or incorrect links on the website. The correct links are on the spread sheet or could not be found

**Comment by mattpen** [comment]
Carolina Biological Supply has a large white space on the right side as well.

**Comment by ariel-phet** [comment]
@mattpen any further action here? It seems the sponsors page is up to date?

**Comment by mattpen** [comment]
The sponsors page is up to date.  New sponsors should be requested in a new issue.
