### ISSUE TITLE
Test the translation utility with more unusual fonts

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#349]
@pixelzoom has reminded us that a number of issues arose when the Java sims were translated into languages that used more "exotic" fonts.  One of the things that was done to help us to respond to the issues that were encountered was to display the font being used, and @pixelzoom suggested that we consider that for Rosetta (see https://github.com/phetsims/rosetta/issues/56).  We have decided not to try to address this in v1 of Rosetta, but to keep it on the radar for v2 based on the issues that are reported.  We are thinking that it might be wise to try to get ahead of this and to test translation into several of the languages which required preferred fonts when Java sims were translated.  This could be done by making sure that the appropriate fonts are installed on a machine, then using Google translate, and cutting and pasting the results into the translation utility.

Here is a minimum set of locales that should be tested (these are some randomly chosen locales from PhetCommonResources.java):
+ Khmer (km)
+ Sinhala (si)
+ Tamil (ta)
+ Thai (th)

If time and resources permit, it would be good to test all locales for which preferred fonts were required in Java.  Here is the list of those locales, and the corresponding language can be looked up at http://www.science.co.il/Language/Codes.asp.

+ ja
+ ar
+ ar_SA
+ zh
+ zh_CN
+ zh_TW
+ el
+ th
+ lo
+ km
+ka
+ta
+kn
+am
+hy
+te
+si

**Comment by ariel-phet** [comment]
@phet-steele think you could give this a shot?

**Comment by phet-steele** [comment]
@ariel-phet of course.

**Comment by phet-steele** [comment]
These all check out :+1:

**Comment by ariel-phet** [comment]
Awesome, thanks for checking! Closing
