### ISSUE TITLE
Test new resend confirmation form and confirm email box

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#350]
It would be good to do a sanity check for the changes in https://github.com/phetsims/website/issues/263.

Here are some good things to test on phet-dev:
1. Create a new account with the new confirm email box.
2. Try to resend the confirmation email.
3. Check the UI and wording for anything that looks off.

Assigning to @ariel-phet for prioritization. Should be a quick one.

**Comment by ariel-phet** [comment]
@elisemorgan can you perform this testing on phet-dev?

**Comment by elisemorgan** [comment]
@aaronsamuel137 @ariel-phet Everything looks good from my end, I was able to resend the confirmation repeatedly. I honestly don't know how to actually check the UI but wording, etc is fine.

**Comment by aaronsamuel137** [comment]
Great! That's good enough. By check the UI, I just meant see if all of the layout looks normal, like nothing is look odd or out of place or broken. Thanks!

Closing
