### ISSUE TITLE
Find math classroom video clips 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#352]
@elisemorgan is going to review the raw footage from the Nov 2013 Fractions Intro classroom study to find useful clips involving teacher facilitation, student discovery, student discussion, etc. 

Hopefully we can find something useful by early next week!

**Comment by elisemorgan** [comment]
@amanda-phet Just want to check in now that you've done your presentation. Should I keep pulling files off of phetnackup and look at them?

**Comment by amanda-phet** [comment]
This is a task that we still want completed, but it does not need to be high priority anymore. Thanks so much for rushing for me last week! The presentation went well and the clips were very useful.

**Comment by amanda-phet** [comment]
I think this task is complete. Thank you!
