### ISSUE TITLE
rename 'tab' to 'screen' in string keys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#353]
There are several sims that use 'tab' in string keys, a holdover from Java terminology. For example, the 2 screens in Beer's Law Lab currently have these keys for their screen names:

```js
  "tab.concentration": {
    "value": "Concentration"
  },
  "tab.beersLaw": {
    "value": "Beer's Law"
  },
```

Since we are assuming that keys provide useful context in Rosetta, it's recommend to change 'tab' to 'screen'.  In the above example, the keys would become `"screen.concentration"` and `"screen.beersLaw"`.  

Searching for "tab." and ".tab", this occurs in the following sims:

- [x] beers-law-lab
- [x] energy-skate-park-basics
- [x] gene-expression-basics
- [x] graphing-lines
- [x] pendulum-lab

**Comment by pixelzoom** [comment]
At 9/10/15 developer meeting, we agreed that this would be good to address before S2015R milestone.

**Comment by pixelzoom** [comment]
Done. @jbphet randomly chosen to review.

**Comment by jbphet** [comment]
I spot checked the commits, and what I saw looked good.  I also searched the string files for ".tab" and found no occurrences.  Looks good, closing.
