### ISSUE TITLE
Balancing Act - Sitting Phet People

### ISSUE THREAD

**Issue by mariahmaephet** [phetsims/tasks#355]
<img width="1423" alt="screen shot 2015-09-11 at 3 14 37 pm" src="https://cloud.githubusercontent.com/assets/11527557/9826473/d7a33596-5897-11e5-9013-35e88095aa98.png">

**Comment by mariahmaephet** [comment]
<img width="1426" alt="screen shot 2015-09-11 at 3 18 15 pm" src="https://cloud.githubusercontent.com/assets/11527557/9826538/5cf49906-5898-11e5-9524-3ed13e2cc668.png">

**Comment by mariahmaephet** [comment]
<img width="802" alt="screen shot 2015-09-29 at 2 41 30 pm" src="https://cloud.githubusercontent.com/assets/11527557/10177607/36ce5932-66b8-11e5-87f6-b4b6e86beccf.png">

**Comment by jbphet** [comment]
These look great!  A few comments:
+ Let's make the male teach a bit more African-American looking.  That was the intent with the original artwork, though it may not have come across very clearly
+ The perspective on the face of the female teacher looks a little off to me, making it look like she is kind of half-smiling.  Can this be improved?
+ We'll need standing versions too, despite the title of this issue.  I mentioned this to @ariel-phet, and he said that he thinks you've created them, so please post them in this issue as well.

**Comment by mariahmaephet** [comment]
Are these better?

<img width="1073" alt="screen shot 2015-10-01 at 10 57 54 am" src="https://cloud.githubusercontent.com/assets/11527557/10227566/527e9ee8-682b-11e5-8a17-998aaaca96cc.png">

**Comment by jbphet** [comment]
Better.  It would be good if the male teacher's hair was a bit more curly.  As for the standing people, they look great, but I think their pose might take up a bit too much horizontal space with the hands on their hips, since space is pretty tight on the carousel.  See the screenshot below.  
![ba-people-in-carousel](https://cloud.githubusercontent.com/assets/3082831/10320161/46a4671c-6c2f-11e5-8fc5-7f13f931208d.png)

**Comment by ariel-phet** [comment]
@mariahmaephet - I think you can also give him a bit more of a "fro" - a little more volume to his hair.

**Comment by ariel-phet** [comment]
@mariahmaephet - @jbphet also requested a PhET t-shirt on either the boy or girl (or both). The one complication is that then the right facing and left facing images will not just be reflections (or the text is going the wrong way. So you probably need to reflect, and then redo the PhET logo. Does that make sense?

**Comment by mariahmaephet** [comment]
@ariel-phet @jbphet  How do these look? I wasn't sure how exactly you wanted the PhET tshirt to look--using the official logo looks a little weird cause it doesn't match the cartoon style. The original characters just had basic font.


<img width="1047" alt="screen shot 2015-10-07 at 6 18 10 pm" src="https://cloud.githubusercontent.com/assets/11527557/10354701/eeefbafc-6d1f-11e5-9189-75b524ad9a33.png">

**Comment by ariel-phet** [comment]
Looks good to me....what say you @jbphet ?

**Comment by jbphet** [comment]
These look good.  Let's leave it at this for now, and I'll integrate these into the Balancing Act simulation when it comes up for redeployment and will see if any other changes are needed.

@mariahmaephet - can you please send me the .ai files?  Thanks.

**Comment by mariahmaephet** [comment]
@jbphet How would you like me to send that to you? It's currently in my google drive folder if you have access to that (PhET Ai files > Design Assets > Mariah Artwork 'sitting phets.ai')

**Comment by jbphet** [comment]
Thanks @mariahmaephet - I can see the file, and will look at it in greater detail later today.

**Comment by ariel-phet** [comment]
@jbphet - if all looks good please close this issue

**Comment by jbphet** [comment]
Closing.  Will reopen or create a new issue if any of these images don't end up working well when integrated into Balancing Act.

**Comment by ariel-phet** [comment]
@mariahmaephet - we need a small tweak

please see https://github.com/phetsims/forces-and-motion-basics/issues/137

It looks like when you increased the hair volume on the man, you did not adjust his hands to a higher height in the sitting position. Lets make that tweak. Thanks!

**Comment by mariahmaephet** [comment]
@ariel-phet Good catch! Sorry I missed that. The new version is in my artwork folder

**Comment by ariel-phet** [comment]
I think this issue can be closed now.

**Comment by ariel-phet** [comment]
Actually reopening, the characters could use their hands adjusted so they sit totally flat when holding up boxes and such.

**Comment by mariahmaephet** [comment]
@ariel-phet  file is in my drive (Mariah Artwork > PhET Characters > "NEW sitting phets")

**Comment by jessegreenberg** [comment]
Thanks @mariahmaephet, I will add these new images.

**Comment by ariel-phet** [comment]
I believe this issue can be closed again, will reopen if any further tweaks needed
