### ISSUE TITLE
PC Laptop setup with new software 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#357]
I am in need of a PC laptop for the next couple of weeks that has the following software installed:
- Camtasia (with enough memory to keep Camtasia from crashing frequently...this is a problem on older computers, e.g., Schrodinger)
- Microsoft Office
- JAWS Demo
- NVDA
- Zoomtext demo

From the PhET Assets spreadsheet, it looks like there's only Mendeleev that is possibly available for this (does that seem right...seems like there's tons of testing Macs but not so many PCs). Elise is using Socrates, and will need to continue with that for the next few weeks also, to do some PC-specific Camtasia editing for me. 

Would it be possible to set up Mendeleev (or some other option) for me ASAP?

**Comment by ariel-phet** [comment]
@emily-phet - I think Schrodinger would be best option actually (that is my old laptop and should have plenty enough memory to use Camtasia, as I had used the program many times). Were you thinking of Socrates instead? Let me know if that would work, and I will get someone on it.

**Comment by emily-phet** [comment]
@ariel-phet - I believe Elise and I tried some video editing on Schrodinger, and it kept crashing (Camtasia crashes frequently on most computers, but it was so frequent it was unusable on Schrodinger). That's why Elise has Socrates right now. 

Actually, that's probably ok, as long as I can use some other screen capture software (not Camtasia) to record on Schrodinger, I can do the editing I need to do on a Mac. Elise has to do the editing on a PC for complex reasons, so she'll still need Socrates.

So, sure. If Schrodinger can run the above listed software reasonably, with a substitute screen capture software for Camtasia, that will work. I think John Blanco has it now, though.

**Comment by ariel-phet** [comment]
@arnabp can you take care of the above with Schrodinger?

**Comment by arnabp** [comment]
I've never dealt with the last few softwares. I found these links and will download, but if any of them aren't the correct software let me know.
http://www.freedomscientific.com/Downloads/JAWS
http://www.nvaccess.org/download/
http://www.zoomtext.com/download-zoomtext-free-trial/?_ga=1.207755986.1753445445.1442348126

**Comment by ariel-phet** [comment]
@emily-phet can you confirm the above?

**Comment by arnabp** [comment]
Assuming these are correct, I'm putting Schrodinger back in F101. If you I need to change anything I can go and get it back tomorrow. Other than that everything else should be running fine. I have installed OBS, a screen capture software that has been very reliable for me. I've set it up to capture the full screen and save the mp4 files into the user video folder. Simply hit Start Recording and you should be good to go (do not click on "Start Streaming").

**Comment by emily-phet** [comment]
Everything looks great @arnabp ! Thanks so much.
