### ISSUE TITLE
Spot testing for Bending Light 1.0.0-dev.29

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#361]
After Actual Concepts addressed numerous issues in the codebase for Bending Light, we should re-test the simulation (a) to see if any work remains for Actual Concepts to work on before making their final invoice and (b) catching issues that remain for me.  This does not need to be an exhaustive test, it would be sufficient to test on the following platforms:

- [x] iPad: Safari
- [x] OS X: Firefox
- [x] Win 7, 8 or 10: IE

This test will take a bit longer than usual because (a) there are many known broken issues at the moment that you will come across and (b) before submitting a bug report, the QA tester should look through the existing open issues for Bending Light and see if there is already an issue for the bug.

Assigned to @ariel-phet to delegate to a QA tester and decide priority.  The link to test is:
https://github.com/phetsims/bending-light/issues/157#issuecomment-140162051

**Comment by ariel-phet** [comment]
@orejolaphet it looks like you are scheduled to be available on 9/15 - please work on this testing then.

If it turns out you are not available let me know and I will reassign. Note what @samreid said above...there are many known issues so as you find them, make sure you are not creating duplicate issues.

**Comment by orejolaphet** [comment]
@ariel-phet currently the sim does not load off of phettest (completely white screen), maybe missing or moved repository? Is it appropriate to test dev.29 published 9/12/15?

**Comment by samreid** [comment]
I fixed the link in the issue description, thanks for pointing out that it was missing!

> The link to test is:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.29/bending-light_en.html

**Comment by orejolaphet** [comment]
Spot testing complete.

**Comment by ariel-phet** [comment]
Since spot testing is complete closing
