### ISSUE TITLE
Test GAO new algorithm

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#362]
@phetsims/bereaphysics implemented a new algorithm for the model code that improves performance quite a bit. Before merging this change into master, it would be good to do some side by side testing of the two algorithms and see if there are any differences in the sim behavior.

The old algorithm can be found here: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.20/gravity-and-orbits_en.html

The new one here: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.1/gravity-and-orbits_en.html

Testing on iPad will reveal that the new one gets much better performance.

Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@phet-steele - you are the man for the job

**Comment by aaronsamuel137** [comment]
I think enough testing has been done on this. @samreid and I decided it is okay to merge the new branch into master. Closing
