### ISSUE TITLE
Test for iOS 9 portrait/landscape bug

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#363]
See https://github.com/phetsims/joist/issues/280

If this bug is present, it would be a very high priority for me to resolve, so testing ASAP would be great.

**Comment by ariel-phet** [comment]
@elisemorgan - can you upgrade one our iPads to iOS9 (ask @oliver-phet if you need help with this), and check if this bug is still present or if it has been taken care of now that iOS9 is no longer in Beta.

**Comment by ariel-phet** [comment]
@elisemorgan - and of course, please update the PhET Asset Matrix when you make this upgrade.

**Comment by elisemorgan** [comment]
@jonathanolson Bug is still present 
![image 10](https://cloud.githubusercontent.com/assets/12610678/9945688/f509329e-5d4b-11e5-8f21-e02bef98d103.jpg)
![image 9](https://cloud.githubusercontent.com/assets/12610678/9945689/f50c9074-5d4b-11e5-9b47-7db4c6a758ef.jpg)
![image 8](https://cloud.githubusercontent.com/assets/12610678/9945687/f5046584-5d4b-11e5-82de-f93efdc16f88.jpg)

**Comment by jonathanolson** [comment]
Looks like iOS 9 beta was still on the testing iPad. I completed the upgrade to the latest iOS 9 version, and the bug disappeared. Closing.
