### ISSUE TITLE
RC test:  Hooke's Law 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#369]

**Comment by ariel-phet** [comment]
@pixelzoom - looks like RC testing can now proceed, please publish the RC version and test matrix and assign back to me once ready and in the issue.

**Comment by pixelzoom** [comment]
Test matrix:
https://docs.google.com/spreadsheets/d/1nXLDYtyugguh2kG23atx9zwECCGEtk-Pbs2Gj27e8vc/edit#gid=1389496089

Links to RC version are in the test matrix.

**Comment by ariel-phet** [comment]
@phet-steele @bryo5363 @elisemorgan @orejolaphet 

Yeah! we are ready to try to publish some new sims and republish our old HTML5 ones finally. Please make this testing and molarity testing a high priority.

**Comment by ariel-phet** [comment]
@elisemorgan also would be good to finish off this testing. Again will need one more RC, but should be pretty quick.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> Again will need one more RC, but should be pretty quick.

Again, not the case.  We need to pull in master of all common-code repositories to pick up critical bug fixes. And there have been 168 changes (and counting) to repos since 1.2.0-rc.1 was published.  So unless you want to inspect 168 commits and decide which ones need to be tested (and specify how to test them), we will need a *full* test suite for the next RC version.

**Comment by ariel-phet** [comment]
@pixelzoom - yes I am aware it will be a full RC test, but I do anticipate it being fairly quick in the grand scheme of things.

**Comment by ariel-phet** [comment]
Quick as in the model is now well vetted, so we will mainly be looking for interaction bugs/rendering bugs etc.

**Comment by elisemorgan** [comment]
@phet-steele Can you still do the Win 8 testing?

**Comment by ariel-phet** [comment]
I finished off the Win 8 testing. Closing.
