### ISSUE TITLE
RC test: Acid-Base Solutions 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#370]
@ariel-phet When you're ready to start this, assign back to me.

**Comment by pixelzoom** [comment]
@ariel-phet gave me the go-ahead for this.

**Comment by pixelzoom** [comment]
S2015R checklist

Developer

 Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
 Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
 Review and update licensing info (source code and images/audio)
 Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
 Standardize the string keys, since they will be difficult to change later
 Identify any strings in sims that should move to another repository, move them now
 Publish RC version and test matrix
 Address RC issues and publish
QA

 stringTest=double
 stringTest=long
 stringTest=X (short strings)
 stringTest=rtl (right-to-left)
 Perform RC testing
 Include full screen test
Design/Admin

 Rosetta test (Opening sim to trusted translators for beta)
 Check teacher tips are up to date
 Check sim primer is up to date

**Comment by pixelzoom** [comment]
Test matrix with links to RC version:
https://docs.google.com/spreadsheets/d/1-Zbwp9k0hB46r_cmmmSoyyZpf4uXozTAlRlz5RZlEGo/edit#gid=25241777

**Comment by ariel-phet** [comment]
Now that Molecules and Light testing is almost finished off, @BryceAG @bryo5363 @elisemorgan @phet-steele  @orejolaphet  @brroberts1231 please make this sim top testing priority

**Comment by elisemorgan** [comment]
@ariel-phet Looks like Steele is wrapping up the iPad 2 iOS 9. Testing is complete.

**Comment by ariel-phet** [comment]
Thanks @elisemorgan 

@pixelzoom seems like this will take a 2nd RC, please close this issue if you feel it is complete.

**Comment by pixelzoom** [comment]
The 2 issues discovered in this RC that must be addressed are:
https://github.com/phetsims/acid-base-solutions/issues/138
https://github.com/phetsims/acid-base-solutions/issues/139

**Comment by pixelzoom** [comment]
Closing. Next RC is tracked in https://github.com/phetsims/tasks/issues/413.
