### ISSUE TITLE
RC test: Balancing Chemical Equations 1.1.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#371]
@ariel-phet When you're ready to start this, assign back to me.

**Comment by pixelzoom** [comment]
12/10/15 status meeting: Go ahead and generate 1.2.0-rc.1.  I'll do this based on shas from graphing-lines 1.1, since that snapshot of common code seemed stable.

**Comment by ariel-phet** [comment]
@pixelzoom if you publish this RC soon, I might be able to get some testing resources on it this week.

**Comment by pixelzoom** [comment]
Test matrix with links to RC version:

https://docs.google.com/spreadsheets/d/122LHEriqD-9iBfdWA0gMh1OSXSxkjJGVyDHYwTd51T0/edit#gid=604790131

Additional QA items:

- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Perform RC testing

This sim has the following additional query parameters that you may find useful:

dev - shows the answers at bottom-center in both screens
playAll - plays all challenges for each level of the game, to get 100% test coverage
reward - shows the Game reward, regardless of score

**Comment by ariel-phet** [comment]
@elisemorgan @phet-steele @bryo5363 @orejolaphet this is the current top sim testing priority

**Comment by elisemorgan** [comment]
@ariel-phet Testing matrix is complete, once @bryo5363 confirms performance on Win 10 Edge

**Comment by phet-steele** [comment]
@pixelzoom @ariel-phet testing done!

**Comment by pixelzoom** [comment]
Self assigning to publish 1.1.0-rc.2.  That should be a short RC test, with https://github.com/phetsims/balancing-chemical-equations/issues/110 requiring verification on 1 or 2 platforms.

**Comment by pixelzoom** [comment]
RC 1.1.0-rc.2 has been published, testing tracked in https://github.com/phetsims/tasks/issues/466.

Closing.
