### ISSUE TITLE
RC test: Beer's Law Lab 1.3.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#372]
@ariel-phet When you're ready to start this, assign back to me.

Since Concentration is a subset of Beer's Law Lab, this should be done at the same time as #373.

**Comment by pixelzoom** [comment]
RC testing of beers-law-lab is blocked until https://github.com/phetsims/beers-law-lab/issues/111 is resolved.

**Comment by ariel-phet** [comment]
Believe we are ready for RC testing, please paste in checklist, matrix, link and such

**Comment by pixelzoom** [comment]
RC testing is still blocked pending resolution of https://github.com/phetsims/beers-law-lab/issues/111.

**Comment by pixelzoom** [comment]
phetsims/beers-law-lab#111 is resolved, RC publication desired on Wed 10/28.

**Comment by pixelzoom** [comment]
**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Test matrix with RC links:
https://docs.google.com/spreadsheets/d/1opT_0el4D08ezqlqrb4dgdYreiPRfjAG5gWRnADOyrk/edit#gid=2000275998

This RC requires a full regression test on all platforms. Please pay special attention to Win10 + Edge. Since the default render for Edge was changed to 'canvas', @jonathanolson has made a few Canvas-specific fixes.

**Comment by ariel-phet** [comment]
@elisemorgan @orejolaphet @bryceAG @brroberts1231 please work on this testing Thursday

**Comment by elisemorgan** [comment]
@ariel-phet All platforms have been tested

**Comment by pixelzoom** [comment]
@elisemorgan Please complete the checklist in the "QA" section ofhttps://github.com/phetsims/tasks/issues/372#issuecomment-151666444 above.

**Comment by pixelzoom** [comment]
Closing.  We'll need another RC - 1.3.0-rc.2, which uses master of common repos.
