### ISSUE TITLE
RC test: Concentration 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#373]
@ariel-phet When you're ready to start this, assign back to me. 

Since Concentration is a subset of Beer's Law Lab, this should be done at the same time as #372.

**Comment by ariel-phet** [comment]
Believe we are ready for RC

**Comment by pixelzoom** [comment]
RC testing is blocked pending resolution of https://github.com/phetsims/beers-law-lab/issues/111.

**Comment by pixelzoom** [comment]
phetsims/beers-law-lab#111 is resolved, RC publication desired on Wed 10/28.

**Comment by pixelzoom** [comment]
**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Test matrix with RC links:
https://docs.google.com/spreadsheets/d/1ghqNXGEAK4sApVwFIHIyZLuNb5QjQO-FyZiQCjE5_ZM/edit#gid=1968926819

This RC is being tested simultaneously with Beer's Law Lab 1.3.0-rc.1, see https://github.com/phetsims/tasks/issues/372.  Since Concentration is a subset of Beer's Law Lab (it's the first screen, with no changes), this RC does not require a full regression test on all platforms.  Spot testing will be sufficient.  As with Beer's Law Lab, pay special attention to Win10+Edge, since there have been significant rendering changes in scenery.

**Comment by ariel-phet** [comment]
@elisemorgan @orejolaphet @bryceAG @brroberts1231 please work on this testing Thursday

**Comment by ariel-phet** [comment]
And please note the above where @pixelzoom says this sim can be "spot tested" since it is a subset of Beer's Law Lab

**Comment by pixelzoom** [comment]
Because we need to pull in master for Beer's Law 1.3.0-rc.2, @ariel-phet decided that we should cancel testing on this release candidate.  Closing.
