### ISSUE TITLE
RC test: Molarity 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#375]
@ariel-phet When you're ready to start this, assign back to me.

**Comment by ariel-phet** [comment]
Looks like we can get this redeploy testing going. Lets begin with Molarity.

**Comment by ariel-phet** [comment]
with caveat that https://github.com/phetsims/chipper/issues/342 is not a blocking issue

**Comment by pixelzoom** [comment]
Test matrix:
https://docs.google.com/spreadsheets/d/1TGckOBNmvdCQvuHQCZ0hK5mOfAU_WdidNbirI24DJI0/edit#gid=1766847255

Links to RC version are in the test matrix.

**Comment by pixelzoom** [comment]
As part of testing this candidate, please verify that change https://github.com/phetsims/scenery/issues/472 has not affected non-iPad platforms.

**Comment by ariel-phet** [comment]
**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over @pixelzoom's revamped code review checklist, decide if code review should be redone
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md 
- [ ] Address RC issues and publish
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now

**QA**
- [ ] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] RTL language test
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@elisemorgan @bryo5363 @orejolaphet @phet-steele 
please test this sim at a similar priority level to hooke's law

@amyh-phet please hop in on testing this sim (even just on your work computer browsers is fine, should be fairly quick...but check in places like the about dialog and such for bugs)

@pixelzoom - please check off items done above (I believe you already took care of all prepublication items on your end)

**Comment by aaronsamuel137** [comment]
Testers, please let me know when this is finished so I can finish https://github.com/phetsims/scenery/issues/472

**Comment by pixelzoom** [comment]
@ariel-phet These 5 items from the checklist in https://github.com/phetsims/tasks/issues/375#issuecomment-144894353 should be done *before* publishing a release candidate, and they are currently *not* checked. Should the RC test be halted?

- [ ] Look over @pixelzoom's revamped code review checklist, decide if code review should be redone
- [ ] Review and update licensing info (source code and images/audio)
 Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now

**Comment by pixelzoom** [comment]
Btw... I'm not in a position to confirm whether PhET's third-party license information is correct. Someone from PhET will need to verify that information.  The license info is *complete* because the sim builds without error, but that doesn't mean that it's correct.

**Comment by ariel-phet** [comment]
@pixelzoom when you said this sim was ready to go for redeploy RC I had assumed you had looked over the S2015R redeploy checklist. Apparently that was not a good assumption. Not much testing has occured so far, so see what you can check off.

And though you are not in a position to *confirm* if the information is correct, please note anything suspicious :smile_cat:

**Comment by ariel-phet** [comment]
In addition since the was your port, I figure it probably passes the code review checklist you developed...

**Comment by pixelzoom** [comment]
>  I had assumed you had looked over the S2015R redeploy checklist.

Sorry, I didn't know that there was such a checklist. 

> so see what you can check off.

Everything checks out OK. I did not see anything obviously wrong with third-party-licenses.md, but cannot verify the correctness of the information therein.

OK to proceed with RC test.

**Comment by ariel-phet** [comment]
We developed the checklist awhile back in a dev meeting (but that was some time ago)...will paste it in to future.

**Comment by elisemorgan** [comment]
@bryo5363 please test on Win 10. This one is quick and easy

**Comment by bryo5363** [comment]
completed win 10 testing. noticed one issue on edge; posted to the repository

**Comment by pixelzoom** [comment]
@ariel-phet I see "RTL language test" in the checklist inhttps://github.com/phetsims/tasks/issues/375#issuecomment-144894353. Can you please clarify what that is, and how QA is supposed to accomplish it?  If you mean to test with an RTL language, that's going to be impossible until we have translations.

**Comment by ariel-phet** [comment]
@pixelzoom yes RTL is (right-to-left) language test. We did some of this testing previously in rosetta when on phet-dev. Can't it also be done using query parameters?

**Comment by pixelzoom** [comment]
I don't know of any query parameter support for RTL testing, and there is nothing indicated in chipper/initialize-globals.js - which is where all query parameters are documented.   So this sounds like new functionality.  I have no knowledge of how/whether this was done in Rosetta.

**Comment by pixelzoom** [comment]
@jbphet or @aaronsamuel137 can you please comment on what RTL testing was done in Rosetta, and whether anything is currently available for general RC testing of sims.

**Comment by ariel-phet** [comment]
@pixelzoom - when using rosetta and the "test" button I believe it injects all the strings into the sim using query parameters.

Here is an example of chains:

http://phet-dev.colorado.edu/sims/html/chains/latest/chains_en.html?strings=%7B%22CHAINS%2FplainString%22%3A%22test%22%2C%22CHAINS%2FmultilineString%22%3A%22asdas%22%2C%22CHAINS%2FhtmlString%22%3A%22Left%20%3Ci%3Ered%3C%2Fi%3E%20is%20a%20%3Cb%3Ebold%3C%2Fb%3E%22%2C%22CHAINS%2Fsize%22%3A%22%3Chello%3E%20hello!%22%2C%22CHAINS%2Fchains.title%22%3A%22Super%20Chains!%22%2C%22JOIST%2FmenuItem.about%22%3A%22dgsgsd%22%2C%22JOIST%2Fcredits.graphicArts%22%3A%22%7B0%7D%22%2C%22JOIST%2Fcredits.leadDesign%22%3A%22%7B0%7D%22%2C%22JOIST%2Foptions.title%22%3A%22asdf%22%2C%22JOIST%2Fcredits.qualityAssurance%22%3A%22%7B0%7D%22%2C%22JOIST%2Ftitle.settings%22%3A%22asdsad%22%2C%22JOIST%2Fcredits.softwareDevelopment%22%3A%22%7B0%7D%22%2C%22JOIST%2Fcredits.team%22%3A%22%7B0%7D%22%2C%22JOIST%2Fupdates.newVersionAvailable%22%3A%22%7B0%7D%22%2C%22JOIST%2FversionPattern%22%3A%22%7B0%7D%22%2C%22JOIST%2Fupdates.yourCurrentVersion%22%3A%22%7B0%7D%22%2C%22JOIST%2FtitlePattern%22%3A%22%7B0%7D%20%7B1%7D%22%7D

So it seems we could do some RTL testing with the published sim without actually pushing any strings to Babel

**Comment by ariel-phet** [comment]
I figured we would do a bit of this sort of testing on the first few published redeploys, make sure there are no major issues, and then take this piece off the checklist.

**Comment by pixelzoom** [comment]
Expecting the QA team to provide a specific RTL string has the same problems that the "long string" test did (see https://github.com/phetsims/chipper/issues/381).  Different strings will be used, and results will be inconsistent. I recommend adding a `stringTest=rtl` query parameter that substitutes a consistent RTL string for all strings (with a chipper issue to request this feature).  And I'd also like to hear from @jbphet and @aaronsamuel137.

**Comment by ariel-phet** [comment]
Sounds good.

**Comment by aaronsamuel137** [comment]
If I remember correctly, @jbphet did some rtl testing with rosetta, so I am not sure that we need to do it for every sim. There is not an easy way for the testers to use rosetta's test feature to test this, since the sim would need to be deployed to show up in rosetta.

If we want rtl testing, I think @pixelzoom's suggestion to add a stringTest=rtl option is the best way to go.

**Comment by ariel-phet** [comment]
@elisemorgan can you wrap up testing on the remaining platforms today?

**Comment by elisemorgan** [comment]
Yes if I can get my hands on the iPads. @arouinfar @jbphet If you're not going to still be in the office after four can you put the iPads (2 and 3 w/iOS9) on the QA shelf?

**Comment by arouinfar** [comment]
@elisemorgan, I've returned Tycho to the QA shelf.

**Comment by elisemorgan** [comment]
@ariel-phet All major platforms have been tested

**Comment by ariel-phet** [comment]
excellent, closing. We will need one more RC for this sim, but should be a quick test.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> We will need one more RC for this sim, but should be a quick test.

Not the case.  We need to pull in master of all common-code repositories to pick up critical bug fixes. And there have been 168 changes (and counting) to repos since 1.2.0-rc.1 was published.  So unless you want to inspect 168 commits and decide which ones need to be tested (and specify how to test them), we will need a *full* test suite for the next RC version.
