### ISSUE TITLE
RC test: Reactants, Products and Leftovers 1.1.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#376]
@ariel-phet When you're ready to start this, assign back to me.

**Comment by pixelzoom** [comment]
12/10/15 status meeting: Go ahead and generate 1.2.0-rc.1.  I'll do this based on shas from graphing-lines 1.1, since that snapshot of common code seemed stable.

**Comment by pixelzoom** [comment]
Test matrix with links to RC version:

https://docs.google.com/spreadsheets/d/10AeWzU1b-QoX7i_1N89-RFmMg-EKDkZzckcAjfiT_rs/edit#gid=1998116932

Additional QA items:

- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Perform RC testing

This sim has the following additional query parameters that you may find useful:

dev - adds 'Test', 'Skip', 'Replay' buttons to the Game, shows challenge answers at the bottom of the Game screen
guessCorrect - initializes game spinners to the correct answer
playAll - plays all challenges for each level of the game, to get 100% test coverage
showReward - shows the Game reward, regardless of score

**Comment by ariel-phet** [comment]
@elisemorgan @phet-steele @bryo5363 @orejolaphet please make this a high testing priority after balancing chemical equations.

**Comment by phet-steele** [comment]
@pixelzoom matrix complete!

**Comment by pixelzoom** [comment]
Thanks @phet-steele.

Self-assigning to create another RC version. The only issue to address is https://github.com/phetsims/reactants-products-and-leftovers/issues/42, but it requires touching common code, probably the sun repo.  If I can patch sun, then we may be able to just spot test the next RC.

**Comment by pixelzoom** [comment]
Issue addressed, sun patched, RC version created, tracking in https://github.com/phetsims/tasks/issues/469.

Closing.
