### ISSUE TITLE
pattern for namespacing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#378]
This came up in the context of together, where having namespacing is required for deserialization, JS type verification, and documentation of associated JS types.

Come up with a pattern that we like and apply it to existing code (sims and common).

**Comment by pixelzoom** [comment]
(1) Pattern similar to @jonathanolson repos (scenery, kite, dot,... )

```js
// functonBuilder.js
define( function( require ) {
  'use strict';
  return ( phet.functionBuilder = {} );
} )

// usage in PatternsModel.js
var functionBuilder = require( 'FUNCTION_BUILDER/functionBuilder' );
// immediately after constructor
functionBuilder.PatternsModel = PatternsModel;
```

**Comment by pixelzoom** [comment]
(2) Create a global function for namespacing. Requires duplication of the namespace token (e.g. 'functionBuilder').

```js
// after constructor
phet.namespace( 'functionBuilder.PatternsModel', PatternsModel );

// wrap the inherit
return phet.namespace( 'functionBuilder.PatternsModel', inherit( Object, PatternsModel, ... ) );
```

**Comment by pixelzoom** [comment]
@jonathanolson and I are leaning towards (1).

**Comment by pixelzoom** [comment]
To be clear on why I'm leaning towards (1)....

• The `require` statement will catch typos, you can't accidentally assign to some other global.
• If you add the `require` statement and forget to do the namespace assignment, lint will complain.
• The namespace assignment is done via an assignment statement - smells like a duck, looks like a duck. (My preference is for the assignment statement immediately following the constructor.)
• The pattern also looks nice in .js files that don't use `inherit`.

**Comment by pixelzoom** [comment]
@samreid @jbphet @aaronsamuel137 @jessegreenberg please comment. Propose additional patterns, and vote on your preferred pattern.

**Comment by aaronsamuel137** [comment]
+1 for pattern (1)

**Comment by samreid** [comment]
> • The `require` statement will catch typos, you can't accidentally assign to some other global.

Sure you could, there might be a copy paste error like this:
```js
var functionBuilder = require( 'SCENERY_PHET/sceneryPhet' );
```

> • If you add the `require` statement and forget to do the namespace assignment, lint will complain.

Yes, but if you forget both, you won't see any lint errors. (However, we could add custom ESLint rules to catch this issue).

> The namespace assignment is done via an assignment statement - smells like a duck, looks like a duck. 

Assignment using `=` operator cannot check for collisions.  What if a sim has two Electron.js files (one in the view and one in the model?)

> • The pattern also looks nice in .js files that don't use `inherit`. 

The following 
```js
phet.namespace( 'functionBuilder.PatternsModel', PatternsModel );
```
doesn't require any inherit call, and works for any type.

Why can't we use Tandem.addInstance for this?  It seems like it has *very similar* goals?

**Comment by samreid** [comment]
I'm also interested in discussing our plan for namespacing files:

1. On a file-by-file as-needed basis
2. Once any file in a repo needs it we namespace everything in the repo
3. We try to instrument everything all at once

If we are using (2) - (3) we may be incentivized to look into ESLint to check that files are namespaced (we may even be able to check the filename somehow?)

**Comment by pixelzoom** [comment]
I'd prefer to namespace all of my files at once. Will take me a couple of hours, then I won't have to deal with it again.

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:
• using Tandem doesn't seem to have significant advantages
• would be nice to create a namespace for a repo, error out if you try to attach something to a namespace that doesn't exist (or the wrong namespace?), check typos in names, etc.
• look at using ESLint to catch related errors
• @jonathanolson unsure how he would change scenery/dot/kite to work with function call (pattern 2, https://github.com/phetsims/tasks/issues/378#issuecomment-143042268), still leaning towards pattern 1
• @aaronsamuel137 still leaning heavily towards pattern 1
• @pixelzoom still votes for pattern 1
• main advantage of using a function is error checking (useful) or needing to know that a module was loaded (not currently needed)
• calling a function provides protection/flexibility to be able to do additional stuff in the future

Each developer will try out above patterns (or propose new patterns) and report back at next developer meeting.

**Comment by jonathanolson** [comment]
Pattern 3:

```js

// Namespace.js
define( require ) {
  'use strict';

  function Namespace( name ) {
    this._name = name;

    if ( window.phet ) {
      window.phet[ name ] = this;
    }
  }

  return inherit( Object, Namespace, {
    register: function( name, value ) {
      assert && assert( !this[ name ], 'Duplicate ...' );
      this[ name ] = value;

      console.log( this._name + ' ' + name + ' loaded' );
    }
  } );
}

////////////////

// functionBuilder.js
define( require ) {
  'use strict';

  var Namespace = require( '.../Namespace' ); 

  return new Namespace( 'functionBuilder' );
}

////////////////

var functionBuilder = require( 'FUNCTION_BUILDER/functionBuilder' );  <-- add

function SomeThing() {
  ...
}
functionBuilder.register( 'SomeThing', SomeThing ); // option 3

functionBuilder.SomeThing = SomeThing; // option 1
```

**Comment by pixelzoom** [comment]
Unassigning. Will be discussed at 10/6/15 developer meeting after we individually test-drive.

**Comment by pixelzoom** [comment]
I took pattern #3 for a test-drive, see these (committed) files in function-builder:

Namespace.js - namespace abstraction, would be moved to common code
functionBuilder.js - sim-specific namespace instance
PatternsModel.js - example of namespace in a file that uses inherit
FBColors.js - example of namespace in a file that does not use inherit, returns an object literal

**Comment by samreid** [comment]
Thoughts and reflections after testing this out?

**Comment by samreid** [comment]
The term `PatternsModel` appears 4 times in PatternsModel.js

**Comment by pixelzoom** [comment]
I like this pattern - I think it combines the best elements of the other 2.  I'm not crazy about duplication of the name of the thing being registered (e.g. PatternsModel). But that's an issue with all patterns that we've considered.

**Comment by pixelzoom** [comment]
One could eliminate one duplication of the thing being registered (e.g. PatternsModel) if the `inherit` call could be embedded, like this:

```js
return functionBuilder.register( 'PatternsModel', inherit( Object, PatternsModel, ... ) );
```

But I don't like the look of this, and it somewhat obfuscates the value of what's being registered.

**Comment by samreid** [comment]
BRAINSTORMING_EMOTICON_NOT_FOUND:

We could move inherit to Namespace and do something like this (only needs a require statement for functionBuilder, not for inherit):

```js
return functionBuilder.inherit( 'PatternsModel', Object, PatternsModel, { //...
```

**Comment by pixelzoom** [comment]
Responsibility for inheritance doesn't belong in Namespace.

**Comment by pixelzoom** [comment]
![images](https://cloud.githubusercontent.com/assets/3046552/10178864/b0f20a9a-66bf-11e5-94a5-c7cc2efc8e72.png) Responsibility for inheritance doesn't belong in Namespace.

**Comment by samreid** [comment]
Not advocating, just brainstorming still: Namespace could be renamed to ModuleSystem which provides namespacing and inheritance functions (related functions for creating a module).

**Comment by pixelzoom** [comment]
> Namespace could be renamed to ModuleSystem

How is this a module system? 
AMD is a module system, and is API specification is implemented by requirejs.  

If it's indeed a module system, then why do we need requirejs?  Or why would we want to have 2 module systems?

**Comment by pixelzoom** [comment]
And what is the advantage (other than the syntactic convenience described in https://github.com/phetsims/tasks/issues/378#issuecomment-144197582) of combining namespace and inheritance responsibilities?

**Comment by samreid** [comment]
Every time we call inherit, we also want to add something to the namespace.  Hence it seems like an opportunity to factor something out.

**Comment by pixelzoom** [comment]
... and we want to add things to the namespace that have nothing to do with inheritance. Again, sounds like combining responsibilities that should be decoupled.

**Comment by samreid** [comment]
Not to belabor the point unnecessarily, but I do want to understand your perspective: If I have a situation where every time x() is called y() must also be called, we should not necessarily create a method that calls both x() and y()?

**Comment by jonathanolson** [comment]
> Every time we call inherit, we also want to add something to the namespace.

This hasn't been true for Scenery, but that could be an argument for refactoring things into separate (30+) more files.

**Comment by samreid** [comment]
Trying to get context on your comment, I found inherit calls in scenery like this:
```js
inherit( DOMSelfDrawable, Circle.CircleDOMDrawable, {
```

CircleDOMDrawable is somewhat of an inner class--should it be put on the namespace?

Also, I think the issue of separate files is separate from namespacing (we could namespace multiple things from a single file if we wanted to).

**Comment by pixelzoom** [comment]
Just because 2 responsibilities both happen to be done in many situations doesn't mean that those responsibilities should be combined into 1 type that handles both responsibilities. The responsibilities should be related, and with clear advantages to handling them both in one type. I have yet to hear the answer to my original question: How are namespace and inheritance related, and what is the advantage to combining them instead of keeping them decoupled?

**Comment by samreid** [comment]
> How are namespace and inheritance related?

A and B are related if every time A happens, B also happens.

It is under discussion whether we want to namespace every type or not: https://github.com/phetsims/tasks/issues/378#issuecomment-145129656

> what is the advantage to combining them instead of keeping them decoupled?

Easier to remember, less opportunity for manual error, factoring out duplicated code, that sort of thing.

**Comment by pixelzoom** [comment]
Could we possibly get some other opinions on whether namespace and inheritance responsibilities should be combined? @jonathanolson @jbphet @aaronsamuel137 @jessegreenberg ?

**Comment by samreid** [comment]
I took pattern (3) for a test drive (in my working copy only--won't commit) by putting Namespace.js (from function-builder) in phet core, creating a sceneryPhet namespace in scenery-phet, adding the ResetAllButton to the namespace and adding this assertion to TogetherCommon.js

```js
assert && assert( instance instanceof phet.sceneryPhet.ResetAllButton );
```

The assertion worked properly.  Notes and thoughts:
(1) IDEA marks phet.sceneryPhet as unresolved:
![image](https://cloud.githubusercontent.com/assets/679486/10263613/df1bda78-69b1-11e5-91c1-6ff08c338fb2.png)

(2) Using `sceneryPhet.register( 'ResetAllButton', ResetAllButton );` between the constructor declaration and before the inherit call seemed fine.

(3) Namespace.js has this code:

```js
    if ( window.phet ) {
      window.phet[ name ] = this;
    }
```

We should assert that namespaces are only created once, or we could end up overwriting things and end up with trouble.

(4) If desired, we could use ESLint to check that each inherit call comes with a namespace.register call (and put code comment directives for cases where that is not necessary).  This is for brainstorming, I'm not necessarily recommending this.

**Comment by pixelzoom** [comment]
> We should assert that namespaces are only created once

Done in above commit.

**Comment by jonathanolson** [comment]
> Could we possibly get some other opinions on whether namespace and inheritance responsibilities should be combined?

and:
> CircleDOMDrawable is somewhat of an inner class--should it be put on the namespace?

I've been using "Nested" packaging, assigning things that would appear as scenery.Circle.CircleDOMDrawable. Since Circle is a function, it can't really be a new Namespace, right? If CircleDOMDrawable isn't handled with namespacing, I would have an explicit "inherit called but no namespacing done", which would argue that namespacing and inheritance should be separate. I'm curious about how that case should be handled.

Another good example of this pattern is dot.BinPacker.Bin, and it was very useful to be able to independently test bin code.

I also have an inherit call at CanvasSelfDrawable line 85, which is in a function call (where we presumably wouldn't know the namespace), also would tend to make me side towards separating the two.

That said, I'd personally be fine with a function that did both (namespace and inherit), as it is by far the most common case. Sometimes we'll have just inheritance, and sometimes just namespacing. I'd leave that up to other developer's opinions.

**Comment by jessegreenberg** [comment]
I tested out options 1 and 3, and my preferences is also for option 3.  I like the idea of having an explicit Namespace file in phet-core for isolation and documentation.  The use of  ```register``` reduced the number of references to the name space at the end of the file:

Option 1 in capacitor-lab-basics:
```js
capacitorLabBasics.CapacitorLabBasicsModel = CapacitorLabBasicsModel;
capacitorLabBasics.CapacitorLabBasicsModel = inherit( PropertySet, CapacitorLabBasicsModel, {
	...
} );
return capacitorLabBasics.CapacitorLabBasicsModel;
```
Option 3 in molecules-and-light:
```js
 moleculesAndLight.register( 'PhotonAbsorptionModel', PhotonAbsorptionModel );
```
I am a unclear about how many types will need to be added to the namespace.   If everything needs to be added to the namespace then we will see something like
```js
moleculesAndLight.register( 'PhotonAbsorptionModel', PhotonAbsorptionModel );
return inherit( PropertySet, PhotonAbsorptionModel, {
	...
} );
```
in every file, so coupling inheritance and namespacing could simplify things.

But the Namespace could get clogged up if smaller extended types are automatically added that do not need to be there.

**Comment by samreid** [comment]
Consensus, we'll use `functionBuilder.register( 'PatternsModel', PatternsModel );` as a single line immediately after the declaration of the constructor, with a blank line between the last `{` of the constructor and the `register` call.

**Comment by pixelzoom** [comment]
I'll move Namespace.js to phet-core.

**Comment by samreid** [comment]
Consensus: namespace will be applied to every top-level class.  It will be up to developers whether they want to revisit pre-existing code.  For nested types, we'll use a strategy like:

```js
  Circle.CircleSVGDrawable = function CircleSVGDrawable( renderer, instance ) {
    this.initialize( renderer, instance );
  };
```

**Comment by samreid** [comment]
Consensus: @jonathanolson will test out this strategy in scenery, kite & dot and report back before we instrument other sims.

**Comment by pixelzoom** [comment]
@samreid pointed out that we need to handle nested types, e.g. beers-law-lab.ATDetectorNode.

@jonathanolson will handle scenery, dot and kit first, in case there are issues with using this pattern to replace the namespacing in those repos.

**Comment by pixelzoom** [comment]
Make Namespace.register parse for '.' separators.  Eg in scenery.Circle, something like:

```js
function CircleSVGDrawable( renderer, instance ) {
  this.initialize( renderer, instance );
};

scenery.register( 'Circle.CircleSVGDrawable', CircleSVGDrawable );
```

**Comment by pixelzoom** [comment]
In case someone is planning to look at my namespace "test drive" described in https://github.com/phetsims/tasks/issues/378#issuecomment-144192399... I've removed it from function-builder.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/tasks/issues/378#issuecomment-145936041:
> @jonathanolson will handle scenery, dot and kit first, in case there are issues with using this pattern to replace the namespacing in those repos.

Adding developer-meeting label to check in on status of this.

**Comment by jonathanolson** [comment]
The last few times I've had this come up on my TODO list, we've been in common-code freeze situations.

I'll take care of it soon.

**Comment by jonathanolson** [comment]
Applied namespace patterns to Dot. Went well, plan to apply them to the repositories I'm responsible for.

**Comment by jonathanolson** [comment]
Hadn't hit ESPB yet, the following might be related:
```
Error: Module name "SCENERY/util/Color" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:166:13)
    at Object.localRequire [as require] (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1392:30)
    at requirejs (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1737:20)
    at http://192.168.0.2:8080/energy-skate-park-basics/js/energy-skate-park-basics/view/EnergySkateParkColorScheme.js?bust=1447106864362:11:15
    at Object.context.execCb (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Object.Module.enable (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1143:14)
    at Object.Module.init (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1170:55)
    at Object.context.completeLoad (http://192.168.0.2:8080/sherpa/lib/require-2.1.11.js:1544:11)
```

**Comment by jonathanolson** [comment]
Sorry, false alarm above, the require.js wrapper was missing the 'require' parameter, so require.js was treating it differently.

**Comment by jonathanolson** [comment]
Chicken and egg problem: Namespace depends on inherit, which depends on the namespace, which depends on Namespace.

Can solve this by:
1. Not using inherit, but define the prototype manually in Namespace.
2. Some other option...? I've thought of ~10 things that break in at least one way.

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/tasks/issues/378#issuecomment-143044428, I was a fan of the namespacing approach that @jonathanolson was using in scenery/dot/kite. Simple, effective, no inheritance. But we went and made it complicated :)

My vote would be for 1, punt on inherit and define the prototype manually in Namespace.

**Comment by samreid** [comment]
We could add some new eslint rule that automatically checks this and makes sure everything is up to standard.

@jonathanolson asks if we can have 2 lint levels.

@samreid: we could use lint level 1 to just print a warning.

**Comment by samreid** [comment]
@samreid will look into an eslint rule for checking this, after it is written we can decide when to turn on the rule.

**Comment by pixelzoom** [comment]
To test drive, I've added namespacing to function-builder. Two observations...

(1) Since keys must be unique for a namespace, and keys are typically the names of files, all filenames must be unique under `<repo>/js/`.   That means that I cannot have `myRepo/js/screen1/model/Solution.js` and `myRepo/js/screen2/model/Solution.js`.  Probably not wise to use the same names anyway, so probably not a big deal. 

(2) For the situation where sim1 is a subset of sim1, sim1 may have no namespace of its own.  For example, concentration is a subset of beers-law-lab. Since it has no source files other than `concentration-main.js` (which is not namespaced), there is no `window.phet.concentration`, and everything for concentration is found under `window.phet.beersLawLab`.

I don't think either of these is a necessarily a problem. Just wanted to mention them, in case they hadn't occurred to others previously (they hadn't occurred to me.)

**Comment by pixelzoom** [comment]
FYI… There’s a slight problem that you may run into when namespacing of inner type. For example:

```js
// file MeterNode.js
var someRepo = require( ‘SOME_REPO/someRepo’ );

function BodyNode() { … }
myNamespace.register( ‘MeterNode.BodyNode’, BodyNode );
inherit( Node, Part1 );

function ProbeNode() { … }
myNamespace.register( ‘MeterNode.Part2’, ProbeNode );
inherit( Node, ProbeNode );

function MeterNode() {
  this.addChild( new BodyNode() );
  this.addChild( new ProbeNode() );
}
myNamespace.register( ‘MeterNode’, MeterNode );
return inherit( Node, MeterNode );
```

The call to `myNamespace.register( ‘MeterNode.BodyNode’, BodyNode )` will fail because `'MeterNode’` does not yet exist in the namespace.  Is to define and register nested types after defining and registering the main type.  Not a big deal, a bit more work and reorganization of some source files.

**Comment by pixelzoom** [comment]
Btw... This "forced reorganization" for namespacing of inner types is (imo) a good thing. For quickly determining how to use a type, it's convenient to have the main type's constructor as the first function definition in the source file.

**Comment by pixelzoom** [comment]
I guess another way to fix this would be to move all `register` calls to the just before the `return` statement, like this:

```js
// file MeterNode.js
var someRepo = require( ‘SOME_REPO/someRepo’ );

function BodyNode() { … }
inherit( Node, BodyNode );

function ProbeNode() { … }
inherit( Node, ProbeNode );

function MeterNode() {
  this.addChild( new BodyNode() );
  this.addChild( new ProbeNode() );
}

myNamespace.register( ‘MeterNode’, MeterNode );
myNamespace.register( ‘MeterNode.BodyNode’, BodyNode );
myNamespace.register( ‘MeterNode.ProbeNode’, ProbeNode );

return inherit( Node, MeterNode );
```

But that would violate our agreed-upon convention of putting the `register` call immediate after the constructor.

**Comment by samreid** [comment]
This issue is getting a bit long, I'll create separate issue(s) for creating the eslint rule(s) for checking namespacing.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
We should probably prioritize adding namespace to common repos, and divide up the work.

**Comment by pixelzoom** [comment]
Here are the common repos that don't currently have a namespace. Let's put names next to these at developer meeting.

- [ ] brand (a little tricky)
- [ ] joist
- [ ] nitroglycerin
- [ ] phetcommon
- [ ] scenery-phet
- [ ] shred
- [ ] sun
- [ ] tandem (namespace needed?)
- [ ] together (namespace needed? together.js is used for something else)
- [ ] vegas
- [ ] vibe

**Comment by pixelzoom** [comment]
I've created individual issues for all of the common repos that need a namespace. After assigning those issues, we can close this issue.

**Comment by pixelzoom** [comment]
@jbphet says that sun will be done today. Closing.
