### ISSUE TITLE
Test Scenery mouse/input handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#380]
I've put up http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en.html and the iframed http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en-iframe.html as testing for a potential fix for https://github.com/phetsims/scenery/issues/464. The change is basically us no longer telling the browser "Don't do anything else with the mouse/touch/etc. besides what we do" but instead "Please don't do X/Y/Z in addition to what we do".

Can both HTML files be tested for general input-related issues (mouse/touch/scroll wheel/stylus/etc.) across a range of platforms? I'm most interested in behavior that didn't happen before that now might happen, e.g.:
- Can you scroll/pan/zoom where it wasn't possible before (causing issues)?
- Can you select text/elements in the sim (like highlighting text)?
- Can you drag things that couldn't be dragged before?
- Does tapping highlight anything different than before?

I'm aware that https://github.com/phetsims/scenery/issues/464 can still occur occasionally, but that it usually doesn't happen (in Chrome) and still happens in IE. Other browser-specific buggy interaction is mainly what I'm worried about. Please continue testing like normal on all platforms after discovering anything.

Assigning to Ariel for prioritization/tagging (testing will be blocking for https://github.com/phetsims/scenery/issues/464).

**Comment by ariel-phet** [comment]
@phet-steele are you available for this testing today?

**Comment by phet-steele** [comment]
@ariel-phet yup, I'm looking into this. I didn't come in to the office today so I won't have access to a touch device until Wednesday.

**Comment by ariel-phet** [comment]
@bryo5363 @elisemorgan @orejolaphet if you have access to a touch device please also help out with this testing

**Comment by jonathanolson** [comment]
Testable version with improved IE support:
http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en.html
http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en-iframe.html

**Comment by ariel-phet** [comment]
@phet-steele did you notice any issues in your testing?

**Comment by ariel-phet** [comment]
@orejolaphet looks like you are available on Tuesday...can you try this testing?

**Comment by orejolaphet** [comment]
Yes, can do.

**Comment by jonathanolson** [comment]
Recommended testing platforms:
- [ ] iPad 3 (iOS 9)
- [ ] Safari (OS X)
- [ ] Firefox (OS X)
- [ ] Chrome (OS X)
- [ ] IE 10 (Win7?)
- [ ] Chrome (Win7)
- [ ] Firefox (Win7)
- [ ] IE 11 (Win8?)
- [ ] Edge (Win10)
- [ ] Chrome (Win10)
- [ ] Firefox (Win10)
- [ ] Chrome (Chromebook)

Recommend brief test for iframe and non-iframe, in both mainly trying to test mouse/touch interaction patterns. Try dragging things out of the frame/window, etc. Try the mouse wheel if available. Try things with other mouse buttons.

Thanks!

**Comment by orejolaphet** [comment]
iframe http://www.colorado.edu/physics/phet/dev/olsonjb/friction_en-iframe.html does not work on iPad iOS 8.3. Screen starts with the PhET loading then changes to a white screen that fills the web page.
![unnamed](https://cloud.githubusercontent.com/assets/5631059/10173408/4a7f473c-66a1-11e5-823f-d0224fc028b2.jpg)
Is there a particular repository I should place these issues?

**Comment by ariel-phet** [comment]
@orejolaphet best to place issues in Scenery for the moment

**Comment by orejolaphet** [comment]
Issue https://github.com/phetsims/scenery/issues/464 still occurs on Win 7 IE 10.

**Comment by orejolaphet** [comment]
@bryo5363 Can you test the Win 10 on your new machine?

**Comment by bryo5363** [comment]
Why yes I can. I'm on it

**Comment by jonathanolson** [comment]
Can you verify the URLs being used to test? The latest are:

> http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en.html
> http://www.colorado.edu/physics/phet/dev/olsonjb/friction-iframe-test/friction_en-iframe.html

The above URL reported in the test is the older http://www.colorado.edu/physics/phet/dev/olsonjb/friction_en-iframe.html

**Comment by jonathanolson** [comment]
I've updated the URLs in the first description of the issue.

**Comment by bryo5363** [comment]
The sim is compliant with Windows 10 on all browsers.

**Comment by orejolaphet** [comment]
My mistake I tested the older version http://www.colorado.edu/physics/phet/dev/olsonjb/friction_en-iframe.html

I went through the new links on my machine (OSX) platforms and no new issues arise. Will check latest links on Windows 7 platforms shortly.

**Comment by orejolaphet** [comment]
Tested on newest links. Behavior still occurs IE 10 Win 7

**Comment by phet-steele** [comment]
@jonathanolson other than phetsims/scenery#464, there's not really any issues cropping up for me on Win 8 after some pretty thorough testing. There was something in the first versions posted in this issue, but I can't reproduce in the subsequent versions.

**Comment by ariel-phet** [comment]
testing complete, plan to leave IE 10 as will not fix.
