### ISSUE TITLE
Updating testing devices and asset matrix to reflect

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#382]
We our updating our supported devices/platforms 

We our dropping IE10 support, only supporting Safari 9+, and dropping OSX 10.8

You can see the supported platforms in the example testing matrix.

We are going to be able to start RC testing of our redeploys today so it would be good to get devices in line.

https://docs.google.com/spreadsheets/d/1vk0QUOOOj_Jr4ePVgwiQ5L7HOsvgor7jkbNYqmCVWnQ/edit#gid=2

@elisemorgan @phet-steele @arnabp @bryo5363 @orejolaphet please work together on this

**Comment by elisemorgan** [comment]
@ariel-phet for OS X 10.9.5 and 10.10.5 it is not possible to update safari without updating the OS because they are bundled together

**Comment by ariel-phet** [comment]
@elisemorgan - OK, don't update, we will get someone to look into it. Maybe @arnabp can figure out a workaround.

@arnabp do you know of (or can find a way) to just update safari?

**Comment by elisemorgan** [comment]
![screen shot 2015-10-01 at 3 33 22 pm](https://cloud.githubusercontent.com/assets/12610678/10234443/da515600-6851-11e5-913f-89da0473dae6.png)
@arnabp If I select only the Safari update, will it not update the OS X? The wording isn't very clear so I'm cautious. This is on Jordan

**Comment by elisemorgan** [comment]
Trying to install 10.11 on Dirac but I need an administrator password. Nothing on the asset spreadsheet or Unfuddle is doing the trick. Any suggestions?

**Comment by ariel-phet** [comment]
@oliver-phet do you know the administrator password for this machine?

**Comment by arnabp** [comment]
@elisemorgan updating safari there will be totally fine. The only time you get a major OS iteration upgrade will be in the form of its own application called by the installer (eg "Install OS X Yosemite"). As long as you're in no such application all installations will be for specific software as opposed to major OS updates. 

I'm installing 10.11 on Dirac now.

**Comment by elisemorgan** [comment]
@arnabp That worked for Jordan, but Dirac and Curie do not have an individual update displayed for safari. Any suggestions?

**Comment by arnabp** [comment]
Hm, that's odd, there's nothing in the app store huh? I will be able to give it a look tomorrow afternoon.

**Comment by arnabp** [comment]
To get the notification for the Safari 9.0 update you have to download and install all other existing OS updates first. I went ahead and did that, Dirac and Curie are now up to date on Safari 9.

**Comment by ariel-phet** [comment]
@arnabp can you take care of any other devices also included in this issue?

**Comment by arnabp** [comment]
My attempts to update Magnus ended in the entire partition getting corrupted, and Dirac is refusing to recognize that a Safari 9 update exists on its Yosemite partition for reasons I can't comprehend. Turing was updated to Safari 9 successfully.

**Comment by ariel-phet** [comment]
Is it possible a clean install is necessary on those partitions with the desired OS?

**Comment by ariel-phet** [comment]
@arnabp did you see my comment above?

**Comment by oliver-phet** [comment]
I do think a clean install will be necessary. @arnabp Could we make a timemachine of Dirac and use that to restore Magnus?

**Comment by arnabp** [comment]
Magnus will almost certainly need a clean install and I may try to just reinstall Yosemite on Dirac. Does Magnus has important information that we need to use Time Machine for?

**Comment by oliver-phet** [comment]
@arnabp and I discussed today. He's going to do a fresh wipe and a new time machine backup so that if this happens again it can be easily fixed.

**Comment by ariel-phet** [comment]
@arnabp - let us know when this task is complete, and thanks for getting the fresh installs and such done!

**Comment by arnabp** [comment]
The time machine backup has been created and Magnus is up to speed, going to look into reinstalling yosemite on Dirac now

**Comment by arnabp** [comment]
Magnus and Dirac are now both outfitted with 10.9, 10.10, and 10.11 with Safari 9 on all three partitions, and we have a full backup of this setup.

**Comment by oliver-phet** [comment]
@elisemorgan Is this issue ready to be closed now that the macs are done?

**Comment by elisemorgan** [comment]
Yes. All devices are updated
