### ISSUE TITLE
Flyer Design for Interview Recruiting - by Oct. 19th.

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#383]
We're going to start putting up flyers around Boulder to ask for interview participants with disabilities. It would be great to have a nicely designed, high contrast, flyer. It would be great to have this finalized by October 19th.

Here's the content that will need to be included:

________________________________________________________________________________
Volunteers Needed! The PhET Interactive Simulations project at the University of Colorado Boulder is currently designing and testing new accessibility features for science and math simulations. 

•	Do you rely on a keyboard to navigate web pages?
•	Do you use a screen reader?
•	Do you have a vision impairment or learning disability that affects how you use your computer?
•	Do you have a friend that fits any of these descriptions?

We are seeking people with diverse needs to try out math and science simulations and to tell us what you think. Volunteers will be paid $30 per hour to try out our simulations. Each volunteer opportunity typically takes about 60-90 minutes. If you would like to volunteer, please email: Interview.Contact.Name@colorado.edu for more information.  Thanks!

__________________________________________________________________________________
I'm also attaching a flyer Taliesin made for recruiting in Canada. The wording is different, but we could print on gold paper to get a similar high contrast effect.
![phet-poster-midschool](https://cloud.githubusercontent.com/assets/5109055/10231827/21c9ae20-6842-11e5-843a-1546f8da5ca8.png)

**Comment by daveunderwood** [comment]
Two ideas: one kind of unusual, one very predictable:

[volunteers.pdf](https://github.com/phetsims/tasks/files/7758/volunteers.pdf)
[volunteers_2.pdf](https://github.com/phetsims/tasks/files/7761/volunteers_2.pdf)

**Comment by emily-phet** [comment]
@daveunderwood - These are really cool! I particularly like the second one (high contrast and probably easier to print). We don't need the IDRC logo, so just the PhET logo will be fine.

**Comment by ariel-phet** [comment]
@emily-phet I saw that @daveunderwood sent you some files in regards to this task. If all looks good can you close?

**Comment by emily-phet** [comment]
@daveunderwood - @ariel-phet just reminded me of this issue. Can you update the text on "Volunteers_2" so that it looks like "volunteers_D". Once that's done I think we're all set and I can edit the content as needed. Thanks!

[volunteers_D.pdf](https://github.com/phetsims/tasks/files/105730/volunteers_D.pdf)
[volunteers_2 copy.pdf](https://github.com/phetsims/tasks/files/105734/volunteers_2.copy.pdf)

**Comment by daveunderwood** [comment]
Hi Emily,


The copy you sent of "volunteers_2.copy" simply has a blank text box. Do you want the text from "volunteers_D" to go into that design (black and white/hand)?


D



Dave Underwood

Design and Media Teaching Consultant

PhET Interactive Simulations, Department of Physics

Program for Writing and Rhetoric

University of Colorado Boulder

303 728 4600


________________________________

**Comment by emily-phet** [comment]
Hi Dave,

Yes, the idea is that they are two versions of the same poster, so the text can be same.

Thanks,

~ Emily
—
Director of Research & Accessibility
PhET Interactive Simulations
http://phet.colorado.edu
Department of Physics
University of Colorado Boulder

On Jan 26, 2016, at 4:01 PM, daveunderwood <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Emily,


The copy you sent of "volunteers_2.copy" simply has a blank text box. Do you want the text from "volunteers_D" to go into that design (black and white/hand)?


D



Dave Underwood

Design and Media Teaching Consultant

PhET Interactive Simulations, Department of Physics

Program for Writing and Rhetoric

University of Colorado Boulder

303 728 4600


________________________________

**Comment by ariel-phet** [comment]
deadline long since passed. Closing
