### ISSUE TITLE
Balance for Isotopes and Atomic Mass

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#384]
@ariel-phet   Can we have Mariah work on creating a new balance for Isotopes and Atomic Mass?

![electronic_balance](https://cloud.githubusercontent.com/assets/13650180/10290507/d48f36a2-6b61-11e5-9f8f-59d9e24b45a5.jpg)

Above is a picture to give an idea of what we would like the artwork to emulate.  Here is what the current balance looks like:
![old_balance_isotopes](https://cloud.githubusercontent.com/assets/13650180/10290706/f0bb436a-6b62-11e5-8d2a-f3a6178e57d1.png)

The balance should have: 
- a more modern look than previous version (rounded and a bit cartoonish is okay)
- a silver/metal looking surface (pan) at the top
- a place for the mass of an atom to be displayed (up to 6 numbers in display)
- space for radio buttons to allow user to change between mass number and atomic mass

I'm happy to meet in person if needed.

**Comment by mariahmaephet** [comment]
@ariel-phet @amyh-phet Sorry for the late response--how does this look? 

<img width="457" alt="screen shot 2015-10-19 at 8 25 16 pm" src="https://cloud.githubusercontent.com/assets/11527557/10596259/918cb138-769f-11e5-9446-978539e5db8b.png">

**Comment by amyh-phet** [comment]
Mariah -

Looks so much better than my drawing!   Thanks for your help.

**Comment by amyh-phet** [comment]
@mariahmaephet   Looks so much better than my attempt!  Thanks for your help.

**Comment by ariel-phet** [comment]
@mariahmaephet can you upload this file to drive?

**Comment by mariahmaephet** [comment]
@ariel-phet @amyh-phet Yep! It's in my folder (scale.ai)

**Comment by jbphet** [comment]
An observation about this: In the code, I can't add perspective, at least not very easily.  That means that the text, the checkboxes, and the readout will look flat while the scale itself appears to have perspective.  I find this a bit disturbing, and I just asked @jonathanolson for his opinion (because he was in the office at the time), and he feels the same way.  I think that this should be modified so that the portion that contains the text, checkboxes, and readout can look flat without it causing cognitive dissonance.

**Comment by mariahmaephet** [comment]
@jbphet Makes sense to me. I'll try changing that up today

**Comment by amyh-phet** [comment]
@jbphet    Thanks for the suggestion.
@mariahmaephet mariahmaephet    Thank you for implementing changes.

**Comment by ariel-phet** [comment]
@mariahmaephet - if you are doing some modification, please also have the light source coming from the upper left (looks to me right now it is from the upper right, at least on the silver tray)

**Comment by amyh-phet** [comment]
@ariel-phet    I notice in the original sim that the light source was a bit strange on the Mix Isotopes tab was a bit odd.   The buckets were shaded as if the light source was coming from the upper left, but the atoms were shaded as if the source was to the upper right.   I'm assuming the upper right was chosen for the atoms to accommodate the label with with the mass number.   
![hydrogen_bucket](https://cloud.githubusercontent.com/assets/13650180/10616453/8663ada6-7722-11e5-8d4f-88e7a3695085.png)

When doing the mock ups, I went with the light source coming from the upper right so you could clearly read the labels on the atoms.   Does this cause an inconsistency between the screens that I need to fix?

**Comment by mariahmaephet** [comment]
@jbphet @amyh-phet @ariel-phet Is this what you were thinking? And let me know if you want the light source changed

<img width="425" alt="screen shot 2015-10-20 at 12 50 12 pm" src="https://cloud.githubusercontent.com/assets/11527557/10617713/22a40494-7729-11e5-9380-4f1bd42b16dc.png">

**Comment by amyh-phet** [comment]
@mariahmaephet    I like the new balance.  Let's leave the light perspective for now.  I'll check with @ariel-phet and the rest of the sim design team to see if this is an issue.
@jbphet - Will this new perspective work better in code?

**Comment by ariel-phet** [comment]
Looks good to me...that will work in code since it is a "flat" perspective on the items that matter (display, text, radio buttons)

**Comment by amyh-phet** [comment]
@mariahmaephet   I don't see the scale.ai file in your folder.  Can you try uploading again.

**Comment by ariel-phet** [comment]
@amyh-phet two things
1. I think the mixed light source is a bit odd, but I think just keep the atoms the way they are
2. Mariah went to organize her folder a bit yesterday and makes subfolders, I can find the subfolders, but I cannot see the contents. Looks like she might need to individually share those. I will get in touch with her.

**Comment by jbphet** [comment]
This scale looks much better.  As far as the shading on the bucket and particles goes, this is a super easy thing to fix in the code, so I'll make sure that we draw all code-rendered elements as though the light source is up and to the left.

**Comment by amyh-phet** [comment]
@jbphet   i think that a light source up and to the left will work well for the first screen.  My concern is with the second screen. With a light source up and to the left on the mixture screen, it could make it  difficult to read the labels on the atoms in the buckets in the mixtures screen.
