### ISSUE TITLE
Test for Balloons and Static Electricity (manually patched 1.0.1)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#386]
URL for version to test: http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.1/balloons-and-static-electricity_en.html

Can we have brief testing for each platform below, to see whether the sim launches and whether you can drag the balloon like normal. I'd like testing for the "online" and "downloaded" forms for each platform. I'm imagining ~15 seconds of testing once the sim has loaded at most.

- [ ] iPad 3 (iOS 9)
- [x] Safari (OS X)
- [x] Firefox (OS X)
- [x] Chrome (OS X)
- [x] IE 11 (Win7?)
- [x] Chrome (Win7)
- [x] Firefox (Win7)
- [x] IE 11 (Win8?)
- [x] Edge (Win10)
- [x] Chrome (Win10)
- [x] Firefox (Win10)
- [x] Chrome (Chromebook)

If this testing passes, I'll have it put up as the public release. Manually patched version from https://github.com/phetsims/balloons-and-static-electricity/issues/96.

**Comment by ariel-phet** [comment]
@elisemorgan do you have time for this test this afternoon?

**Comment by ariel-phet** [comment]
@phet-steele - if this task is not complete, please work on it first thing Friday morning, thanks!

**Comment by elisemorgan** [comment]
@phet-steele please test on the remaining devices since I don't have access to them. For future reference @ariel-phet how should I be testing Win 10? Asset inventory doesn't list devices running on that OS

**Comment by ariel-phet** [comment]
Good question @elisemorgan! I think most of the win 10 testing had been taking place on personal machines, but PhET should get a dedicated Win 10 machine. I will look into it.

**Comment by ariel-phet** [comment]
@bryo5363 - if possible help finish off the Win 10 stuff here

**Comment by phet-steele** [comment]
@ariel-phet yea I can't actually do anything pending getting devices for the last four tests. This issue wants an iPad 3 with iOS 9, but our only iPad 3 is iOS 8.3. We only have an iPad 2 that is iOS 9. I could update this iPad 3 if we want to, but we would lose our only iPad 3 + iOS 8.3 combination.

**Comment by ariel-phet** [comment]
@phet-steele yes, please update the ipad3 to iOS 9 and update the asset matrix. We want to make sure we have an iPad2 on iOS 8.3, but the iPad3 should be on the latest.

**Comment by bryo5363** [comment]
Everything looks great on Windows 10

**Comment by phet-steele** [comment]
@jonathanolson I can't get the downloaded version to finish loading on IE11 (Win 8.1)

**Comment by elisemorgan** [comment]
I observed the same behavior on Win 8 IE 11 but thought it was slow
internet because when I opened it a second time it was fine.

**Comment by phet-steele** [comment]
Online version of iPad3 iOS 9 was fine, but the downloaded version had this as a loading screen after refreshing:
![img_0077](https://cloud.githubusercontent.com/assets/5863899/10400440/fb32b93e-6e75-11e5-93d1-74a0ef29041e.PNG)

And dragging the balloon revealed a second balloon behind the first that is unresponsive:
![img_0076](https://cloud.githubusercontent.com/assets/5863899/10400445/00c251f2-6e76-11e5-93a7-1387ee69f6a9.PNG)

**Comment by bryo5363** [comment]
I noticed this behavior as well

On Microsoft Edge we see the same thing...




<img width="937" alt="balloons" src="https://cloud.githubusercontent.com/assets/7717368/10400735/5fdd1fc0-6e6f-11e5-988d-6301fe163486.png">

**Comment by phet-steele** [comment]
@jonathanolson as an update to my previous comment about IE11 on Win 8.1, I came back to it after awhile and it had loaded. However, it takes at least 5 minutes to load (that's how long I waited until I got bored and did other things).

**Comment by jonathanolson** [comment]
For all mentioned issues, can you test the published website version of the sim (http://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html) to see if it has the same issue?

**Comment by jonathanolson** [comment]
> @jonathanolson I can't get the downloaded version to finish loading on IE11 (Win 8.1)

Sounds like https://github.com/phetsims/joist/issues/164, presumably was still a problem in the old version.

**Comment by ariel-phet** [comment]
@elisemorgan see @jonathanolson comment above. For the issue can you test the version on the website and see if these issues also exist in the published version?

**Comment by ariel-phet** [comment]
@elisemorgan forget previous comment. Looks like fixing this file is going to need to wait until redeploy. Closing.
