### ISSUE TITLE
Win 10 machine

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#387]
@oliver-phet we probably need to purchase another windows laptop for testing windows 10. Can you look into (or have @arnabp look into) purchasing a reasonably priced laptop? I don't think we have any machines that would currently be a good candidate.

**Comment by bryo5363** [comment]
I have a windows 10 device that I use for testing now. Any windows 10 tasks can be assigned to me

**Comment by ariel-phet** [comment]
We seem to have this covered for the moment, closing
