### ISSUE TITLE
Dev test Neuron 1.0.0-dev.13

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#388]
This sim is getting closer to being ready for a release candidate, but I thought it would be good to do a round of dev testing first so that I can fix anything that is found on master prior to creating an rc branch.

Please test this version, looking primarily for functional issues:
http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.13/neuron_en.html

**Comment by ariel-phet** [comment]
@orejolaphet looks like you are available today, can you do some dev testing on the following:

- [ ] iPad2 iOS9
- [ ] Windows Chrome
- [ ] Mac OSX Safari

**Comment by ariel-phet** [comment]
since @jbphet is addressing issues with neuron, closing this issue since there will likely be a new dev version
