### ISSUE TITLE
Dev Test: trig-tour 1.0.0-dev.18

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#391]
Trig Tour code review is complete and all issues have been resolved, except for
 - [x] phetsims/trig-tour#16 (i18n, solution pending design review)

dev.18 is deployed and ready for dev testing:
http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.18/trig-tour_en.html

If you would rather wait until phetsims/trig-tour#16 is closed, another version can be published testing at that time.  But it seems like dev testing could begin at this point.

**Comment by ariel-phet** [comment]
@elisemorgan if you have a little time today, this would be a great sim to dev test, although Hooke's law will be the priority (there will be an RC later today).

- [ ] iPad 2 iOS 9
- [ ] Windows Chrome
- [ ] Mac OSX Safari

**Comment by ariel-phet** [comment]
@bryo5363 @orejolaphet please also hop on this dev test if you have time

**Comment by elisemorgan** [comment]
@ariel-phet Dev test is complete

**Comment by ariel-phet** [comment]
excellent thanks!
