### ISSUE TITLE
Cautionary Java Security Tale

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#393]
From the developer of Jmol:

Hello, PhET developers,

I am the principal developer of Jmol. I had a recent experience with my code signing certificate that I thought you should at least be aware of. It may be completely not relevant to you because you no longer feel Java applets are significant to your operation. In any case, I offer the following as a cautionary tale.

On October 15, 2015, all deployed Jmol applets ceased to function. Instantly. Without warning, and without explanation. The event knocked out every site developed to date that still uses the Jmol Java applet. It did not have any affect on stand-alone Java applications. But it does affect all applets, whether embedded or downloaded with JNLP.

The cause of the event was an unexpected certificate revocation when I switched to SHA-2 from SHA-1 at the advice of my certificate authority, GoDaddy, just before extending my certificate for another 2 years. I was advised to upgrade to SHA-2, and the customer service rep failed to mention that this would trigger a revocation of my current certificate. Upon the single click of a link on the GoDaddy web site, all distributed Jmol applets on any website anywhere in the world failed to function. Instantly. They are dead and cannot ever be resurrected. This rep as well as a second rep whom I talked with later both had no idea this would happen.

I note that PhET simulations are also signed as SHA-1.

You might think that certificate revocation should not have had any effect. I certainly wondered about that. My JAR files are signed in exactly the same way that PhET applets are signed, with a timestamp. Jarsigner verifies this timestamp the same for both Jmol and PhET. So you would have the same experience as I if/when you ever upgrade your certificate to (the soon to be required) SHA-2 level. Revocation should not be an issue. Yes, well, there's a catch....

Despite the fact that my code was signed with a timestamp, revocation prior to the expiration date of the certificate results in Oracle's Java applet initializer to disregard the timestamp and not allow such applets to start. Ever again.

So, the lesson learned is that if you choose to upgrade your certificate to SHA-2, you must NOT do so prior to the expiration date of your certificate (which in the PhET case is Jan 7, 2017). If you do, then all working Java PhET siimulations already distributed will be immediately made inoperable. Permanently. Instantly. Irrevokably. Your "Download" and "embed" links will not deliver anything usable, and any page anyone has ever developed with your "embed" link will be broken.

Just thought I would let you know.

Sincerely,

**Comment by ariel-phet** [comment]
@samreid - please discuss at the next developer meeting and comment in this issue if there is anything we should be aware of for the near future. I checked Molecule Polarity (which I believe uses Jmol) and it runs just fine, I assume because it is a "stand-alone" Java application.

**Comment by samreid** [comment]
@jbphet & I discussed this, and we've concluded we are at minimal risk for now since our SHA-1 certificate should continue to work until Jan 2017, and we are not too worried about our certificate being compromised by hash collisions or other issues that are making HTTPS website developers favor SHA-2.

Before we renew our certificate in late 2016, we will re-evaluate and see if SHA-1 is still suitable.

Immense thanks to the developer of Jmol for pointing out this serious issue!

**Comment by ariel-phet** [comment]
@samreid should this issue be closed...or perhaps left opened and put in a different repo/moved to unfuddle?

**Comment by samreid** [comment]
@jbphet & I added reminders in our personal calendars to address the upcoming certificate renewal process for Oct 2016, and we have also added an entry in the PhET Availability Calendar (with a note to stay on SHA-1) to remind others on our team in case @jbphet and @samreid both forget.  That should be sufficient, and we can close this issue.
