### ISSUE TITLE
license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#394]
Doing a build with latest npm/node, I'm seeing this new warning:

> npm WARN package.json area-builder@1.1.0-dev.1 license should be a valid SPDX license expression

According to https://spdx.org/licenses/ 'GPL-3.0' is a license but we are using the string `GPLv3`.  We should probably change this to use the SPDX version.  Our MIT licenses seem ok.  @jonathanolson @jbphet @pixelzoom @aaronsamuel137 @jessegreenberg I'll schedule myself to work on this at medium priority unless/until I hear otherwise.

**Comment by pixelzoom** [comment]
Why do we care whether it's in SPDX format? Disable the warning?

**Comment by samreid** [comment]
From https://spdx.org/licenses/

> The SPDX License List is a list of commonly found open source licenses and exceptions for the purposes of being able to easily and efficiently identify such licenses and exceptions in an SPDX document (or elsewhere). The SPDX License List includes a standardized short identifier, full name for each license, vetted license text, other basic information, and a canonical permanent URL for each license and exception. By providing a short identifier, users can efficiently refer to a license without having to redundantly reproduce the full license.

If this in the npm standard and we are developing using npm, why would we want to do something different?

I am unaware of ways to disable specific warnings here.

**Comment by jbphet** [comment]
@samreid - we can split this up if you like.  I ran into it yesterday when trying to run the test-server, and everything was essentially failing the build as a result.

**Comment by samreid** [comment]
@jbphet can you clarify--an npm install *warning* was failing the build?

**Comment by jbphet** [comment]
Perhaps I shouldn't say 'failed'.  Basically, I ran the test-server, and the middle column of the indicators (the one that is supposed to represent the build result) ended up being some color other than green.  I can't recall if it was red or something else, and the machine has done an auto-reboot-update since then, so I'd have to recreate it if you want to know for sure.  Do you need that, or should we just address it?

**Comment by samreid** [comment]
So far, nobody has provided a good reason *not* to fix it.  It should just take <5 minutes to do a global query replace in the right file pattern.

**Comment by jbphet** [comment]
I went ahead and did this, @samreid can verify at his convenience.

**Comment by samreid** [comment]
I spot checked the commits and did not see any problems.  I also pulled the changes and verified that the warning no longer appears during npm install.  Thanks @jbphet, closing.
