### ISSUE TITLE
RC test: Friction 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#396]
Test Matrix: https://docs.google.com/spreadsheets/d/1xs2_pAvLnEGoC7a1a0IqD29B8gyhGyvBPaD9iCSSZJM/edit#gid=184957754

**Comment by jbphet** [comment]
This redeployment is being done in support of translation, which is connected to the S2015R milestone, so below is the associated checklist.

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@bryo5363 @elisemorgan @orejolaphet @phet-steele this should be the next top QA priority. Now that Molarity and Hooke's Law are published, we will be regularly releasing redeploys. We are going to try to start with some quicker to test sims like this one.

**Comment by jbphet** [comment]
We should abandon this RC due to a couple of issues identified in this GitHub issue: https://github.com/phetsims/friction/issues/31.  Fixes are in place, so I'll roll a new RC.
