### ISSUE TITLE
RC test: Friction 1.2.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#397]
A second release candidate had to be created due to https://github.com/phetsims/friction/issues/31.  The test matrix can be found here:
https://docs.google.com/spreadsheets/d/1xs2_pAvLnEGoC7a1a0IqD29B8gyhGyvBPaD9iCSSZJM/edit#gid=190932211

**Comment by jbphet** [comment]
This redeployment is being done in support of translation, which is connected to the S2015R milestone, so below is the associated checklist.

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@elisemorgan @bryo5363 @phet-steele @orejolaphet please make this new RC your top testing priority

**Comment by ariel-phet** [comment]
@amyh-phet can you take care of the Win 8 testing on this one (should be pretty quick)

**Comment by amyh-phet** [comment]
@ariel-phet   Win 8 testing complete.  Let me know if you need me to test on other platforms today.

**Comment by elisemorgan** [comment]
@ariel-phet all platforms have bee tested. The issues on Edge appear to be resolved

**Comment by ariel-phet** [comment]
Sim has been opened to translators. Moving remaining checklist items to specific issues.
