### ISSUE TITLE
RC test: Faraday's Law 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#398]
Test matrix can be found here: https://docs.google.com/spreadsheets/d/163WcaZ6ZAEoVjYbg0pEJrGVvl_nW-NYvDugrd86pqow/edit#gid=156295433

**Comment by jbphet** [comment]
This redeployment is being done in support of translation, which is connected to the S2015R milestone, so below is the associated checklist.

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@phet-steele @orejolaphet @elisemorgan @bryo5363 

Please make this the next testing priority after friction

**Comment by ariel-phet** [comment]
Testing basically complete, waiting on check on iPad 3 issue

**Comment by ariel-phet** [comment]
Sim redeployed, closing
