### ISSUE TITLE
Investigate "IE-on-Chrome"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#399]
@oliver-phet and @arnabp one of our twitter users reported the following:

>Want run a non-HTML5 @phETsims through a chromebook? Take the phET URL and try it through here https://www.ieonchrome.com/  works pretty well!

Could we investigate and see:

1. Does this work well?
2. Are there any unintended consequences? Seems like it is a freemium model...

Seems like it could be nice to tell teachers about, but I don't want to advertise something that is a bad idea. (Since it looks like it is a pay service but has some model for "EDU") if you go under "plans"

**Comment by oliver-phet** [comment]
@samreid and I looked this a bit in my office. It took several tries using the test feature: https://ielatest.ieonchrome.com/#http://phet.colorado.edu/

We were able to get Molecule Polarity (Java) to open after several tries. The full extension doesn't appear to be available on Chromebooks and you can only use the free version for 1 hr per month. It uses a "streaming" process where their servers open the sim and stream the screen via the browser. The whole process seemed very flaky. Probably not worth recommending for now.

**Comment by ariel-phet** [comment]
Thanks for investigating @oliver-phet!
