### ISSUE TITLE
Error when embedding sims

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#400]
I got this email thread (below) from one of the directors of Go-Labs in Europe. Can someone take a look at this? 

---------------------------------------------------------------------------------------------------------------------------------------

Hi,

That would be great. Indeed, if it was possible, it would be great if they could provide some other simple mechanism for listing the simulations (even a manually edited listing in a json/xml/text format would be enough). Until now we haven't had any problem but whenever they perform any major change in their web layout, we would need some readaptation.

Best,
Pablo

On Oct 23, 2015 8:13 PM, 
Hi Pablo,
 
I am in touch with Emily Moore, director of PhET, and also the UTE team knows her. Should we report this to her?
 
Best regards,
 
Ton
 
 
From: Technical Cluster On Behalf Of Pablo
Sent: vrijdag 23 oktober 2015 14:55

Subject: Re: [GO-LAB_TC] PhET lab error in Graasp "Unable to resolve the server's DNS address"
 
Hi,
 
It should be fixed now.
 
In PhET, they're providing wrong links for some reason. For example, in: http://phet.colorado.edu/en/simulation/acid-base-solutions
 
![image001](https://cloud.githubusercontent.com/assets/5109055/10702179/4b51861a-7985-11e5-8ac6-ce283a40e5c3.png)
 
When clicking on "EMBED", the link they're providing is "http://phet.colorado.eduhttps://phet.colorado.edu/sims/...." which is incorrect. The Smart Gateway brings you there but that URL is invalid (since that domain -colorado.eduhttps- can't exist). However now we handle this situation, and if that kind of URL is provided we change it to the valid one.
 
Thank you for reporting!
 
Best,
 
On Fri, Oct 23, 2015 at 2:32 PM, Pablo wrote:
Hi,
 
This is an issue in the Smart Gateway. Let me check it.
 
Best,
 
On Fri, Oct 23, 2015 at 2:30 PM wrote:
Hi Go-Lab TC,
 
I am having a problem with opening the PhET labs in graasp (see screenshot.jpg). The error I get is Unable to resolve the server's DNS address. Could someone check this out.
 
Thanks,
Leo

**Comment by aaronsamuel137** [comment]
Thanks for bringing this to my attention. That looks like an error introduced by a deploy I did last night. I will fix it today.

**Comment by aaronsamuel137** [comment]
Should be fixed now

**Comment by emily-phet** [comment]
@aaronsamuel137 - Thanks! I let the Go-Lab folks know.

**Comment by emily-phet** [comment]
@aaronsamuel137 - here's a response and suggestion from the Go-Lab folks:
Thank you! It works! Additionally, would it be possible to add in the future some index file so we can retrieve a listing in a computer format (e.g., json/xml/txt...)? Right now, what we do is check all the PhET websites and find the links inside. However, this process is certainly fragile, since if you change the web layout in the future, our side will not work. Having something more reliable (e.g., a simulations index such as "http://phet.colorado.edu/en/simulations.rss") would be definitely helpful for us.

**Comment by aaronsamuel137** [comment]
I can work on adding such a feature to the website, but I'll need to know more specifically what kind of data they want. A list of simulations with embed links? Anything else?

There is already a way of getting metadata about simulations, see for example http://phet.colorado.edu/services/metadata/simulation?simulation=build-an-atom&format=phet-master. But they may want different data.

@emily-phet, feel free to put the Go-Lab folks in touch with me directly or refer them to this issue.

**Comment by porduna** [comment]
@aaronsamuel137 - thank you for your response.

What we have been doing at [gateway4labs/rlms_phet](https://github.com/gateway4labs/rlms_phet/blob/master/g4l_rlms_phet.py#L209) is to parse the HTML to extract the information.

The link you point out is great help for us, since it provides much more useful information. However, it misses:

 * the link to the final lab (e.g., [this link in your example](https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_en.html); or in [this one which is Adobe Flash](http://phet.colorado.edu/services/metadata/simulation?simulation=buoyancy&format=phet-master) we would need [this link for English](https://phet.colorado.edu/sims/density-and-buoyancy/buoyancy_en.html), and [this other link for Spanish](https://phet.colorado.edu/sims/density-and-buoyancy/buoyancy_es.html), and the other languages supported).

 * A list of all the simulations (couldn't find anything like /services/metadata/simulations).

Thank you very much!

**Comment by aaronsamuel137** [comment]
We are going to be working on a new JSON API for simulation information soon, which might be relevant for you. I will let you know when this happens.

In the mean time, you can use http://phet.colorado.edu/services/project-sorted-simulations.csv to get a list of all valid simulations.

To get the final lab links, you can use oai_ilox format: http://phet.colorado.edu/services/metadata/simulation?simulation=buoyancy&format=oai_ilox

Let me know if there is anything else I can help you with.

**Comment by porduna** [comment]
Thank you! Both links are super useful!

In the oai_ilox format, is there any way to know that one link is for one language, other than checking the landing_page and parse the URL (not a big issue)?

Do you have a super-approximate estimate on when are you releasing the JSON API? I mean, if it was for January or so, we might wait with the current HTML parsing, but if you plan a web layout change or the JSON API will come at some point in the longer future, it is better for us to reimplement it with the formats you mention.

Thank you!

**Comment by aaronsamuel137** [comment]
I would guess that we will implement this in the next few months, take a look at https://github.com/phetsims/website/issues/297 to see our current thoughts about the API.

**Comment by ariel-phet** [comment]
This issue can be closed, related discussion to the API tracked in another issue.
