### ISSUE TITLE
RC test: Molecules and Light 1.1.0-rc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#402]
Molecules and light version 1.1.0-rc.4 is deployed and ready for RC testing.

**Sim link:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.4/molecules-and-light_en.html

**iFrame:** http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.0-rc.4/molecules-and-light_en-iframe.html

**Test matrix:** https://docs.google.com/spreadsheets/d/1SIuHF5V4TPR-H2FHugvL52cB6MvQ60gYgg-W-88A6mg/edit#gid=553184252

I recommend a fresh RC test for this version.  All common code SHAs updated to the stable set that is being used by Friction.

**Comment by jessegreenberg** [comment]
**Checklist for S2015R milestone:**

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @orejolaphet @bryo5363 please make the current top testing priority

**Comment by ariel-phet** [comment]
@elisemorgan I believe this testing is basically done, can you check the QA items (the string tests and such)

**Comment by elisemorgan** [comment]
@ariel-phet Testing is complete

**Comment by jessegreenberg** [comment]
Great, thanks @elisemorgan.  @ariel-phet does the design-admin section of the checklist or anything else need to be completed before redeploy?

**Comment by ariel-phet** [comment]
@jessegreenberg, I will move the couple remaining items to Molecules and Light repo. Please go ahead and publish and redploy!
