### ISSUE TITLE
Vanity PhET link shortener

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#404]
@mattpen this is very "wish listy" so very very low priority, but at some point I think it might be nice to have vanity shortened phet links especially for our social media. I am curious if this could be done by actually getting another university domain (instead of purchasing one or such). Could you investigate at some point when the feeling moves you?

How to create vanity short links: http://computers.tutsplus.com/tutorials/create-your-own-vanity-url-shortener--mac-54425

**Comment by mattpen** [comment]
@ariel-phet I'm not sure that the university has any shortened domains (I've never seen one anyway), but I can contact OIT and inquire about it.  If you want a short URL particular to phet I think it would need to be purchased.  [phetsi.ms](https://www.godaddy.com/domains/searchresults.aspx?ci=83269&checkAvail=1&domainToCheck=phetsi.ms&isc=gofd2003ae) is available, although its not the cheapest domain.

**Comment by ariel-phet** [comment]
@mattpen I guess I am wondering if it can just be treated as a redirect on some level...I guess that depends on the DNS policies of the university...can we just create a domain, or does there have to be support for shortened domains and such. Seems like a great question for OIT

**Comment by mattpen** [comment]
@ariel-phet - Response from OIT below.  This is possible, but we would need to purchase the domain and park it outside of the university.

Matt,

  If you purchased a shortened domain we can configure the figaro server to answer for this domain though it would still show phet.colorado.edu in the browser URL (if you don’t want this, it will be a bit more challenging).  The University can not park the domain name so you would have to park this with the registrar and have the registrar serve the DNS for the domain.  So, if you register phet.org for example, the registrar would have to host the DNS for phet.org and point this to 128.138.128.89, which points to phet.colorado.edu.

  Orrie

**Comment by ariel-phet** [comment]
@mattpen thanks for looking into it

**Comment by ariel-phet** [comment]
@arnabp can you look into what it would cost to purchase a shortened domain like phet.org? Doubt we would do this, but I am curious as to the cost.

**Comment by ariel-phet** [comment]
Especially now that we have "twitter cards" this seems no longer particularly relevant to even look into.
