### ISSUE TITLE
RC test: Beer's Law Lab 1.3.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#405]

**Comment by pixelzoom** [comment]
Publication desired ASAP on 11/3/15. Currently blocked by phetsims/scenery-phet#204.

**Comment by pixelzoom** [comment]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by pixelzoom** [comment]
Test matrix with links to RC version:
https://docs.google.com/spreadsheets/d/1opT_0el4D08ezqlqrb4dgdYreiPRfjAG5gWRnADOyrk/edit#gid=771847087

Since master of common repos is required, this RC requires a full regression test. 

Pay particular attention to these issues that were discovered in the previous RC. If any of these is still present, reopen the issue and provide details.

• https://github.com/phetsims/beers-law-lab/issues/114
• https://github.com/phetsims/beers-law-lab/issues/116
• https://github.com/phetsims/beers-law-lab/issues/118
• https://github.com/phetsims/beers-law-lab/issues/120

**Comment by ariel-phet** [comment]
After #370 Acid-Base solutions testing, lets make this the next QA priority @BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 

Several fixes for this RC required updates to the code, so we again require a full RC test, but Concentration can still be "spot tested" as described in #406

**Comment by ariel-phet** [comment]
bumping to current top testing priority

**Comment by pixelzoom** [comment]
Test matrix appears to be complete, but QA check list above is not completed.

**Comment by elisemorgan** [comment]
@pixelzoom How do I test touchArea?

**Comment by elisemorgan** [comment]
@pixelzoom Checklist is complete

**Comment by pixelzoom** [comment]
Thanks @elisemorgan!

RC test is complete. Tracking publication in https://github.com/phetsims/tasks/issues/423.
