### ISSUE TITLE
RC test: Concentration 1.2.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#406]

**Comment by pixelzoom** [comment]
Publication desired ASAP on 11/3/15. Currently blocked by https://github.com/phetsims/scenery-phet/issues/204.

**Comment by pixelzoom** [comment]
**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Test matrix with links to RC version:
https://docs.google.com/spreadsheets/d/1ghqNXGEAK4sApVwFIHIyZLuNb5QjQO-FyZiQCjE5_ZM/edit#gid=1474124696

This RC is being tested simultaneously with Beer's Law Lab 1.3.0-rc.2, see #405. Since Concentration is a subset of Beer's Law Lab (it's the first screen, with no changes), this RC does not require a full regression test on all platforms. Spot testing will be sufficient.

**Comment by ariel-phet** [comment]
As mentioned above, when Beer's Law Lab testing is finished, please spot test this sim as the next testing priority @BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 please make this sim top testing priority

**Comment by ariel-phet** [comment]
@pixelzoom looks like this is pretty well spotted tested now?

**Comment by pixelzoom** [comment]
@ariel-phet Yes, matrix looks complete. Assuming that https://github.com/phetsims/beers-law-lab/issues/122 verifies ok, we can publish 1.2.0 off of the 1.2 branch.

Closing.

**Comment by pixelzoom** [comment]
@ariel-phet Yes, matrix looks complete. Assuming that https://github.com/phetsims/beers-law-lab/issues/122 verifies ok, and no other beers-law-lab issues are found (its testing is not complete), we can publish 1.2.0 off of the 1.2 branch.

Closing.
