### ISSUE TITLE
Energy-related Sims: # of annual runs

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#407]
Can someone send me the number of runs over the past year for the following sims (if available in HTML5 and Java, then both numbers over the past year):

*Collision
Forces & Motion: Basics
*Friction
*Chemical Reaction
Reversible Reaction
*Energy Skate Park: Basics
Molecules and Light
*Greenhouse Effect
*Photoelectric Effect
*Charges and Fields
*Generator
*Molecular Polarity
Salts & Solubility
*Energy Forms and Changes

@ariel-phet - not sure if it's ok for me to ask for this here. I usually ask Oliver for this sort of thing directly, but it occurred to me that he might not be the only person who knows how to look this up. Is it pretty straightforward? If so, I'll just ask someone to show me how to do it next week.

**Comment by ariel-phet** [comment]
@emily-phet when you say "over the past year" do you mean up until the present, or for instance last academic year? Last academic year should be easy, but up to the present may require us to import some data.

**Comment by emily-phet** [comment]
@ariel-phet - just something that represents a calendar year, it doesn't need to be up to current month.

**Comment by ariel-phet** [comment]
@emily-phet that should be pretty easy with our current stats database. JO is sick today, but I will ask him when he is better (and might be something you can easily grab yourself).

**Comment by ariel-phet** [comment]
results and procedure emailed to @emily-phet, closing
