### ISSUE TITLE
Prepping for NSF / White House STEM Forum

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/tasks#408]
Representing PhET, I will be giving a 10 minute talk, and hosting a demo session a quickly-planned NSF Forum on STEM Education. 

Attendees will be diverse:  school leaders, policy makers, journalists, philanthropists and other influences. Focus on contributing a broader message that would engage this audience, not the nuts and bolts of conducting research. Your chair can help you think about a message that will work.

Demo session will be 1.25 hours, and will have a poster and any electronics we have. This demo can be more general - but poster should have some assistive / accessibility forward looking aspects on it. 

For the talk, I am in the following session: 
Assistive Technologies for Learning: Broadening Participation in STEM
Technology has propelled personalized learning for students and has expanded our ability to understand and address disability-based differences in STEM education and workforce participation. This session could provide compelling examples of innovative technologies, resources, and research discoveries that inform further consideration of approaches for promoting productive learning and participation of persons with both cognitive and physical disabilities in STEM education and workforce. 

I will layout what I need help with below.

**Comment by kathy-phet** [comment]
I'll need help preparing the following items: 

- [ ] Poster: 48" wide x 36" tall: Covering basics of PhET (sims, transforming classrooms and STEM learning, and Reach), and future innovations of PhET-iO and Accessibility and what they enable. Maybe a "PhET is transforming STEM learning in ...." then split the poster ... "Today's Classroom" and "Tomorrow's Classroom" framing? 
- [ ] General Flyer: Perhaps the politician facing flyer we did for Polis
- [ ] Forward Looking Next-Generation Sim Flyer: Messaging to potential funders regarding PhET-iO and Assistive Technologies and what is possible for learning ... perhaps caturing what the classroom would look like somehow (this is new, so if possible)
- [ ] General PhET Business Cards 
- [ ] 2 iPads ready-to-go. One with ability to lock down and stand, if possible. 
- [ ] Possibly screen and projector ... as it might be possible to set this up, and would draw attention, but I don't know if this will be feasible.

**Comment by ariel-phet** [comment]
@kathy-phet - please let us know when you depart so we have a date

**Comment by ariel-phet** [comment]
@oliver-phet @amanda-phet @amyh-phet @arouinfar 

This will be an "all hands on deck" mission and trumps priority of pretty much everything else :)

**Comment by amanda-phet** [comment]
Should we claim an item or would you like to assign them to us?

**Comment by ariel-phet** [comment]
If you feel solid claiming an item certainly do (for instance I imagine @amanda-phet is on top of the business cards) but we probably need to have @oliver-phet looking into where we could get some news printed with a fast turnaround

**Comment by oliver-phet** [comment]
Are we going to be printing new business cards? Not sure if it's feasible to have them by Friday.

**Comment by amanda-phet** [comment]
@oliver-phet I thought @kathy-phet said you just had a bunch printed for her, so I'll ask her if she wants new ones or not. If it's possible to get the new ones by Friday we should do it!

**Comment by ariel-phet** [comment]
@oliver-phet I think we might be able to get a quick turn around for a small batch somewhere...there appear to be one day printing services on the net

**Comment by ariel-phet** [comment]
FedEx claims they can do "same day business cards"

**Comment by amyh-phet** [comment]
Just let me know how I can help.

**Comment by ariel-phet** [comment]
@amyh-phet - probably have you start working on the poster using one of the two templates we have. And @arouinfar perhaps you and I will work on the general flyer using some updates from Dave's recent flyer.

**Comment by amanda-phet** [comment]
@ariel-phet , @kathy-phet is here now and is letting us know how we can be helpful. We may not be able to start anything until tomorrow.

**Comment by amyh-phet** [comment]
@ariel-phet  Kathy has the files for both posters and will be working on content tonight.   Sounds like I will use tomorrow to make sure the poster is in order.

**Comment by arouinfar** [comment]
@ariel-phet, that works for me. We'll need to wait and see what feedback @kathy-phet has in terms of the overall messaging, which will guide the flyer redesign.

**Comment by kathy-phet** [comment]
Thanks, team!
