### ISSUE TITLE
Update naming convention of CLA's on unfuddle

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#409]
@samreid, @kathy-phet requested that we update to a standard naming convention for CLA's kept on unfuddle.

Year_Last_First_Affiliation_githubname-CLA.pdf

Organization could be "ActualConcepts" or "Independent" if they don't have an affiliation. Year is year they started contributing and signed a CLA. 

I made these updates for the PhET app team as well as for Martin. Can you take care of the other ones (since I am not sure I know the source of all of them)

**Comment by ariel-phet** [comment]
And please note, high priority (since fairly quick) and Kathy needs some of the updates for work with the tech transfer office.

**Comment by samreid** [comment]
One down, seven to go...

**Comment by samreid** [comment]
I finished renaming all of the files, please double check that everything looks correct.  Also, do we need CLAs from the rest of Ashraf's team including rizwanspeaks, umar and mrsafi?  I left the `@` symbol out of their github usernames here so they won't get automatically linked on this thread.

**Comment by ariel-phet** [comment]
Ashraf is the only one currently making commits so we are in the clear so far. For MLL didn't the company sign in some way?

**Comment by samreid** [comment]
I added the contract signed by MLL in 2012.  It has a section about rights and ownership of the created software, but it is different than the standard CLA we began using afterwards.

**Comment by ariel-phet** [comment]
Got it, I will ask Ashraf for CLA's from the rest of his team

**Comment by ariel-phet** [comment]
All CLA's in the notebook have now been updated to the standard naming convention, and the naming convention has been documented in https://github.com/phetsims/phet-info/blob/master/contributors/CLA.md
