### ISSUE TITLE
mitigate ventilator noise in @jbphet's office

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#410]
The ventilator in @jbphet's office generates an unusually high level of white noise, to the point where it tends to interfere with Skype calls.  @ariel-phet and I discussed tracking down some sound absorbing materials as well as lumber to build something that could help to reduce the sound pressure level (SPL).  For the record, the unmitigated level is 53 dBA, placing a whiteboard in front of the vent takes it down to 49 dBA, with a blanket over the vent the level is 47 dBA.  The SPL of the vent in the neighboring office is 43 dBA, and it seems like a much more tolerable amount of white noise.

**Comment by ariel-phet** [comment]
Mitigated.

**Comment by jbphet** [comment]
Thank you!
