### ISSUE TITLE
Dev Test: bending-light 1.0.0-dev.40

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#414]
All known issues are complete, developer testing and design-team-testing went well, so this sim is ready for dev testing.  I just published this version, which could be used for dev testing:

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.40/bending-light_en.html

@ariel-phet can you prioritize and reassign?

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 please begin dev testing on this sim as Beer's Law Lab and Concentration testing wrap up.

**Please test on the following platforms:**
- [ ] Windows Chrome
- [ ] Mac Safari
- [ ] iPad2 iOS 9
- [ ] Windows Edge

**Please note the following:**

1. If you begin testing on a device, please comment in the issue, so other know what you are testing on, then check off when testing is complete on the that platform
2. Report any found issues in the bending light repo
3. One new feature is the "angles" checkbox on the more tools screen, please pay special attention to this feature
4. On the prisms screen performance is known to get slow with multiple objects. No need to report an issue if performance starts to degrade with more than 3 objects, but do try out more objects just to see if anything catastrophic happens (and it is fun!)

**Comment by orejolaphet** [comment]
I will be testing OS X 10.11 Safari

**Comment by orejolaphet** [comment]
This is more of a design question, but what is the purpose of having a protractor if there is now an "angles" option?

**Comment by samreid** [comment]
Good question @orejolaphet--our ideas are the following:

1. The protractor on the initial screen cues that angles are important, and provides a playful tool for students to manipulate to get qualitative results on the 1st and 2nd screens.
2. On the "more tools" screen, the Angles option is provided to give more quantitative results as well as to quantify the angle as a function of wavelength.  The protractor is still provided here for consistency with the 1st screen, for qualitative results and so students can compare the protractor and angle outputs.

I recommend we keep both, but thanks for bringing it up for discussion!

**Comment by orejolaphet** [comment]
I see! Thanks for the clarification.

**Comment by phet-steele** [comment]
I've been handling Win 8 Chrome.

**Comment by ariel-phet** [comment]
Looks like this sim will require a new dev version, closing.
