### ISSUE TITLE
Create a tutorial video for adding a sim to iPad reading list

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#415]
@arnabp We discussed in person, but we'd like to have a step-by-step video about how to add a sim to an iPad reading list for offline use.

**Comment by amanda-phet** [comment]
As part of this task, can you also create *brief* (1-2 sentences) written instructions for how to do this?

**Comment by phet-steele** [comment]
@oliver-phet @amanda-phet do you still see this being useful once the app can just be put on our iPads?

**Comment by amanda-phet** [comment]
Since the app won't be free, it might still be valuable to have these instructions for users who won't/can't buy the app. If a video is too much, we could just do some screenshots with text. I'll put it on the agenda for next week's website meeting.

**Comment by oliver-phet** [comment]
Assigning to @arnabp for when you are back in the office.

**Comment by amanda-phet** [comment]
8/16 meeting we decided that this video would still be useful.

**Comment by arnabp** [comment]
Script for the video: 

This tutorial will show you how to access PhET simulations without wifi. To save a PhET sim to your iPad for offline use you can use the “Reading List” tool. Navigate to the simulation you would like to save while connected to the internet. Go to the drop down menu and select “Add to Reading List.”

Now, when your iPad cannot connect to Wifi, you can simply go to your reading list and find the simulation saved and ready to be used.

**Comment by ariel-phet** [comment]
I wonder if now we should also have something in this video at the end which says "alternatively, you can download our 99 cent iPad app, etc etc"

**Comment by oliver-phet** [comment]
Yep, @arnabp were discussing this. I think we should add a sentence at the start of the video. "We offer a convenient app that includes offline versions of all of the HTML5 sims, etc. ... If you would like to save a sim one-at-a-time to your iPad..." continue with rest of script above.

**Comment by ariel-phet** [comment]
This just no longer seems like a relevant need for the project. Closing
