### ISSUE TITLE
PhET email designs

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#416]
We should update our outgoing email design - account setup, newsletters, donation emails, etc. 

There isn’t a common design for any of our email communication and since we are likely going to be sending much more donation ask/thank you emails via salesforce in the future, It might be nice to get a solid email design worked out.

Some examples:
[PhET Spring 2015 Newsletter.pdf](https://github.com/phetsims/tasks/files/30397/PhET.Spring.2015.Newsletter.pdf)
[PhET Fall 2014 Newsletter.pdf](https://github.com/phetsims/tasks/files/30398/PhET.Fall.2014.Newsletter.pdf)
[Please Donate Now to Support PhET in 2014.pdf](https://github.com/phetsims/tasks/files/30400/Please.Donate.Now.to.Support.PhET.in.2014.pdf)
[Will PhET get your vote in NSFs Video Showcase.pdf](https://github.com/phetsims/tasks/files/30401/Will.PhET.get.your.vote.in.NSFs.Video.Showcase.pdf)
[PhET Sims Work around for recent Java update and incompatibility with PhET.pdf](https://github.com/phetsims/tasks/files/30402/PhET.Sims.Work.around.for.recent.Java.update.and.incompatibility.with.PhET.pdf)

**Comment by ariel-phet** [comment]
@oliver-phet here is @daveunderwood first pass at an updated newsletter template. Thoughts/feedback?

![newsletter_1](https://cloud.githubusercontent.com/assets/4051174/11196940/6703e434-8c77-11e5-9a5c-5f775bee7618.jpg)

**Comment by oliver-phet** [comment]
@daveunderwood

**Comment by ariel-phet** [comment]
@oliver-phet it seems you have a pretty good working design at the moment. Closing.
