### ISSUE TITLE
Update iPad's that are on iOS9 to iOS 9.1

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#417]
@arnabp @orejolaphet @phet-steele @elisemorgan @BryceAG @brroberts1231 @bryo5363 

If you are testing on an iPad that is CURRENTLY on iOS 9, please make sure it is up to date on iOS 9.1 and make the change to the asset tracking matrix accordingly

https://docs.google.com/spreadsheets/d/1PzD7H2xGrkZewcuYXtAKtmwWe9I3syU6rtAZAaobA-Y/edit#gid=0

For the iPad2 that is on iOS 8.4 (Lave) please leave that on iOS 8

**Comment by elisemorgan** [comment]
@ariel-phet Both Tycho and Disessa are now running on iOS 9.1

**Comment by ariel-phet** [comment]
@elisemorgan can you also upgrade Witten?

**Comment by elisemorgan** [comment]
@ariel-phet Witten is currently on iOS 8.3. Do you want it on iOS 9.1?

**Comment by ariel-phet** [comment]
Yes please

**Comment by elisemorgan** [comment]
@arnabp An error is preventing the update. Can you check this out?

**Comment by arnabp** [comment]
Witten has now been upgraded to iOS 9.1

**Comment by ariel-phet** [comment]
Excellent, closing!

**Comment by ariel-phet** [comment]
Actually reopening...Can we also upgrade Leibniz?

**Comment by ariel-phet** [comment]
@arnabp if you get a chance to upgrade Leibniz

**Comment by BryceAG** [comment]
@ariel-phet Leibniz has been updated

**Comment by ariel-phet** [comment]
Excellent, closing!
