### ISSUE TITLE
Reminder about test devices and platform information in Issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#418]
@arnabp @orejolaphet @phet-steele @elisemorgan @BryceAG @brroberts1231 @bryo5363 

The developers would appreciate if you put both the testing platform and the device name when you report issues

This way they know the platform (for instance Windows 8.1 Chrome) but if they believe the issue is device specific or difficult to reproduce they can go to the actual same device (for instance Tycho)

Please give a :+1:  in the comments after you have read this issue.

**Comment by orejolaphet** [comment]
👍🏼

**Comment by phet-steele** [comment]
:-1:

**Comment by elisemorgan** [comment]
👍🏻

**Comment by arnabp** [comment]
:+1:

**Comment by bryo5363** [comment]
(Thumbs up)

**Comment by BryceAG** [comment]
:+1:

**Comment by brroberts1231** [comment]
👍

**Comment by ariel-phet** [comment]
Thanks all, closing
