### ISSUE TITLE
Updates to Research List

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#419]
Here are some updates to the PhET research page list.

In "Important features for effective simulation design":

Designing accessible interactive chemistry simulations. Moore, E. B.  Spring 2015 ConfChem: Interactive Visualizations for Chemistry Teaching and Learning. (2015) 
Link: http://confchem.ccce.divched.org/2015SpringConfChemP8

Tilting the Tablet: The Effect of Tablet Tilt on Hand Occlusion. Moore, E. B. In Proceedings of the 33rd Annual ACM Conference Extended Abstracts on Human Factors in Computing Systems (pp. 1633-1638). ACM. (2015)
Link: http://dl.acm.org/citation.cfm?id=2732790&dl=ACM&coll=DL&CFID=559767761&CFTOKEN=29555661

In "Research on In-class Use":

Using an interactive simulation to support development of expert practices for balancing chemical equations. Carpenter, Y., Moore, E. B., & Perkins, K. K. Spring 2015 ConfChem: Interactive Visualizations for Chemistry Teaching and Learning. (2015)
Link:  http://confchem.ccce.divched.org/2015SpringConfChemP4

Effective Student Learning of Fractions with an Interactive Simulation. Hensberry, K., Moore, E., & Perkins, K. Journal of Computers in Mathematics and Science Teaching, 34(3), 273-298. (2015)
Link: http://www.editlib.org/p/148049/

The existing listing for "Assessing the implicit scaffolding design framework: Effectiveness of the Build a Molecule simulation" needs to be updated to look like this: 

Assessing the implicit scaffolding design framework: Effectiveness of the Build a Molecule simulation. Moore, E. B., & Perkins, K. K. NARST 2014: Awakening Dialogues - Advancing Science Education Research Practices and Policies. Proceedings of the National Association for Research in Science Teaching, Annual International Conference. National Association for Research in Science Teaching. (2014)
Link: https://drive.google.com/file/d/0B44Uycdx6JGdLWxzRFFWZnpJc3M/view?usp=sharing

In "Other Work by PhET Researchers":

Grand Challenge Problem 3: Empowering Science Teachers Using Technology-Enhanced Scaffolding to Improve Inquiry Learning. Pedaste, M., Lazonder, A., Raes, A., Wajeman, C., Moore, E. B., & Girault, I.  In J. Eberle, K. Lund, P. Tchounikine, & F. Fischer (Eds.), SpringerBriefs in Education (pp. 17–20). Springer International Publishing. (2016)
Link: http://link.springer.com/chapter/10.1007/978-3-319-12562-6_4#page-1

Opportunity: Inclusive Design for Interactive Simulations. Moore, E. B., & Lewis, C. In Proceedings of the 17th International ACM SIGACCESS Conference on Computers & Accessibility (pp. 395-396). ACM. (2015)
Link:http://dl.acm.org/citation.cfm?id=2811387

The Cutting Edge: Educational Innovation, Disability Law, and Civil Rights. Grossman, P. Adapted by Moore, E. B. Submitted to the 2015 ConfChem Online Conference: Interactive Visualizations for Chemistry Teaching and Learning. (2015)
Link: http://confchem.ccce.divched.org/2015SpringConfChemP6

**Comment by ariel-phet** [comment]
@emily-phet since this is a website task it should really go in the website repo. I will close and repoen there
