### ISSUE TITLE
RC test: pH Scale 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#420]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [x] Address RC issues
- [x] publish

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] Perform RC testing
 - [x] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by pixelzoom** [comment]
Test matrix with RC links:

https://docs.google.com/spreadsheets/d/1_GwEET-3UrACqvNyzWT-q8ANvvQGTFRVHYoXswjNDqs/edit#gid=269371545

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 please make this the next top testing priority

**Comment by orejolaphet** [comment]
RC testing has been completed

**Comment by ariel-phet** [comment]
@pixelzoom possible to publish with branching process?

**Comment by pixelzoom** [comment]
Yes. I will patch scenery to address #65, then publish 1.2.0.

**Comment by pixelzoom** [comment]
1.2.0 is published. Remaining check list items moved to https://github.com/phetsims/ph-scale/issues/66. Closing.
