### ISSUE TITLE
RC test: pH Scale: Basics 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#421]
Since ph-scale-basics is a subset of ph-scale, this RC test will be done in conjunction with https://github.com/phetsims/tasks/issues/420.

**Comment by pixelzoom** [comment]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by pixelzoom** [comment]
Test matrix with RC links:

https://docs.google.com/spreadsheets/d/1F0JBJ2MyPkKk4LmFSs224OpPKUNR8lQpUPOeOw56uqk/edit#gid=1948749108

This sim is the first screen from the "pH Scale" sim (being RC tested in #420), so only requires a spot test. The only difference here is that the beaker does NOT automatically fill when changing solutions via the combo box (it does auto-fill in "pH Scale").

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 please make this a high testing priority after #420  is done (since this sim should only need spot testing)

**Comment by pixelzoom** [comment]
Test matrix looks complete, and no need to repeat QA checklist above. So this sim is ready to publish, at the same time as ph-scale 1.2.0.  I will patch scenery to address phetsims/ph-scale#65, then publish 1.2.0.

**Comment by pixelzoom** [comment]
1.2.0 is published. Remaining check list items moved to https://github.com/phetsims/ph-scale-basics/issues/41.  Closing.
