### ISSUE TITLE
publish Concentration 1.2.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#422]
Remaining issues from check list:

- [x] publish
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Sim is published. Assigned to @ariel-phet for remaining check list item (above).

**Comment by ariel-phet** [comment]
moved to repo specific issue
