### ISSUE TITLE
Prepare a simulation for S2015R

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#424]
@ariel-phet requested @samreid to prepare a simulation for S2015R redeploy.

**Comment by samreid** [comment]
@ariel-phet suggested Forces and Motion: Basics.  Its a popular sim, the friction changes and art changes would be nice.

@samreid suggested to check in with @jessegreenberg to make sure accessibility is in a good place before bringing this to production for S2015R.

**Comment by jessegreenberg** [comment]
Accessibility is in active development for forces-and-motion-basics.  Net force screen is getting some revamped accessibility designs after an initial round of student testing.  Accessible content for the remaining screens are being implemented for the first time now.  

However, references in code to accessibility changes should be safely hidden in blocks starting with ```this.accessibleContent = { ...```, never being called without query parameter ```?accessibility```  .  

So FAMB could be ready for redeploy.  

I could also continue accessibility in a branch, which is what I have started doing for other sims.

**Comment by samreid** [comment]
Thanks @jessegreenberg, let's keep everything in master for now and we can re-evaluate if issues arise.

**Comment by samreid** [comment]
Closing, we'll track this in the forces-and-motion-basics issue now.
