### ISSUE TITLE
Test formula (KaTeX) browser support

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#425]
I've added support for displaying mathematical formulas as part of https://github.com/phetsims/scenery/issues/457, however there's a good chance of platform-specific bugs or incompatibilities.

Please test http://www.colorado.edu/physics/phet/dev/olsonjb/scenery-phet-formula-node.html across our supported platforms. To test:
1. Visit http://www.colorado.edu/physics/phet/dev/olsonjb/scenery-phet-formula-node.html
2. Go to the 'Components' screen
3. Select 'FormulaNode' from the drop-down.
4. Compare appearance with below. It should have a mathematical formula tightly contained in a light gray box (if the box is too big, or to small and doesn't contain all/almost all of the formula, that is an issue). Any significant visual differences should be reported.

Reference screenshot (centered formula with fitting light gray rectangle):
![screen shot 2015-11-11 at 11 04 34 pm](https://cloud.githubusercontent.com/assets/480878/11111716/eac9e2a8-88c8-11e5-8957-c1fbb034f241.png)

Platforms to test:
- [x] iPad 2 (iOS 8)
- [x] iPad 2 (iOS 9)
- [x] iPad 3 (iOS 9)
- [x] OS X 10.9 (Safari)
- [x] OS X 10.10 (Safari)
- [x] OS X 10.11 (Safari)
- [x] OS X 10.11 (Firefox)
- [x] OS X 10.11 (Chrome)
- [x] Win7 (IE11)
- [x] Win7 (Chrome)
- [x] Win7 (Firefox)
- [x] Win8 (IE11)
- [x] Win8 (Chrome)
- [x] Win8 (Firefox)
- [x] Win10 (Edge)
- [x] Win10 (Chrome)
- [x] Win10 (Firefox)
- [x] Chromebook (Chrome)

Thanks!

**Comment by ariel-phet** [comment]
@amanda-phet can you begin this testing on a few platforms since you are going to have the eye for if everything is looking acceptable to you? (and it should be exciting!). If things are looking solid, assign back to me, and I will have the QA team take care of remaining platforms.

**Comment by ariel-phet** [comment]
Larger screenshot (win 7 FF, and looking pretty good to me)

![capture](https://cloud.githubusercontent.com/assets/4051174/11111977/9b0d7506-88cb-11e5-8a7d-dcf8cb6da920.PNG)

**Comment by jonathanolson** [comment]
@amanda-phet, also let me know if appearance improvements should be made. The lower limit of the integral would usually be shifted to the left (more flush with the integral sign), and the real-number symbol seems offset slightly.

**Comment by amanda-phet** [comment]
This looks good on my Mac (still running OS X 10.10) on all three browsers, as well as the two iPads that I looked at. 

I see the offset Real number symbol and the lower limit but agree that they don't bother me enough to investigate right now. I don't imagine we'll use either in the near future (potentially the integral when we do Calculus Grapher but that seems a ways off!).

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @elisemorgan @phet-steele @orejolaphet @brroberts1231 

Please work on this testing (might be easy to do as you are on a device doing RC/dev testing of other sims)

**Comment by orejolaphet** [comment]
I noticed while testing on "Bates" Windows 7, for both Chrome 46.0.2490.86 m and IE 11.0.9600.17843 have slight alignment issues. 
Notice:
The upper bar of the square root symbols do not align.
The 2 in the exponents of the (x^2(sub2) + x^2(sub3))^1/2 term overlap with the upper bar of their square root symbol.

![formulanode](https://cloud.githubusercontent.com/assets/5631059/11186763/7e12ac64-8c40-11e5-842c-f314677c3026.PNG)

**Comment by orejolaphet** [comment]
The alignment issue of the square root upper bar also occurs on OSX 10.11.0: FireFox 42.0, Chrome 46.0.2490.86, Safari 9.0

**Comment by jonathanolson** [comment]
Looks related to https://github.com/Khan/KaTeX/issues/40, unless we submit code changes to KaTeX, I don't see much else I can do about it.

**Comment by phet-steele** [comment]
Win8 (IE11) has the square root issue noted by @orejolaphet above, and on Win8 (FF 42.0) the vertical lines look like this on both sides:

![broken lines](https://cloud.githubusercontent.com/assets/5863899/11189392/1b48999c-8c4d-11e5-946c-672d9bee7018.PNG)

**Comment by ariel-phet** [comment]
@jonathanolson I think KaTeX would be very open to changes if you think you have a solution (being a project of Khan academy, this would also be a nice collaboration move if you think you have good changes)

**Comment by jonathanolson** [comment]
@ariel-phet, I don't have a solution, it would require getting up-to-speed on their code and finding a fix. Let me know about the priority of visual artifacts, and whether I should do that.

**Comment by ariel-phet** [comment]
@jonathanolson not a priority at the mometn

**Comment by amanda-phet** [comment]
If the square root is an issue that can't be fixed, we may want @jessegreenberg to pause on implementing this in Trig Tour (which uses square roots).

**Comment by orejolaphet** [comment]
KaTex browser support testing is complete

**Comment by ariel-phet** [comment]
@jonathanolson any other testing to do here?

**Comment by jonathanolson** [comment]
Nope, thanks! Noted links to the testing problems in the main KaTeX issue.
