### ISSUE TITLE
Get one time password set up for rc backups

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/tasks#426]
Currently, I am the only one that has access to the research computing backups. @ariel-phet suggested that we should get @oliver-phet set up to access this data.

To do this, you need a one-time-password device set up with OIT.

Feel free to discuss this with me @oliver-phet.

**Comment by oliver-phet** [comment]
@aaronsamuel137 I have an OTP device. What is needed to setup the access?

**Comment by aaronsamuel137** [comment]
I have sent an email to rc-help to ask what they recommend given that I am leaving, but I haven't heard back.

Basically, you'll just need to set up an account with research computing and email them to ask for access to the phet files. Though you might actually have access already because you set up the account.

You could try typing `ssh [identikey]@login.rc.colorado.edu` in a terminal, and then enter your one time password and see if it works. If you are using a mac, you should be able to find the Terminal app pretty easily by searching with spotlight.

**Comment by oliver-phet** [comment]
I now have the OTP device setup and successfully ssh'd in!

**Comment by oliver-phet** [comment]
@jonathanolson
