### ISSUE TITLE
Redeploy LSR

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#428]
As part of the Summer 2015 Redeploy, Least Squares Regression will also need to be redeployed by someone.

**Comment by jessegreenberg** [comment]
This is one that I could do since MAL was the only sim I have had to redeploy so far.

**Comment by ariel-phet** [comment]
@jessegreenberg sounds good, assigning to you. Lets make getting Trig tour out the priority, and then we can figure out where getting this ready for redeploy lands.

**Comment by ariel-phet** [comment]
Closing, dealt with in other issues like https://github.com/phetsims/least-squares-regression/issues/48
