### ISSUE TITLE
Re-produce primer videos

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#430]
Please produce these with the newest bumpers and send to @schasteen for review. We suggest using the original camtasia file (since it may have some sound edits) and swapping out the bumper video. 

- [x] Balancing Chemical Eqns
- [x] pH Scale
- [x] pH Scale: Basics
- [x] Reactants Products & Leftovers
- [x] Area Builder
- [x] Fraction Matcher
- [x] Color Vision
- [x] ESPB
- [x] Faraday's EL

This should be completed after #429. Please check in with @oliver-phet and let us know if you are not able to start these by December 1st.

**Comment by arnabp** [comment]
All sims have been re-produced with the new bumpers and are in their respective folders, let me know if everything checks out!

**Comment by schasteen** [comment]
I've reviewed them all and put some comments in a new column G about any changes needing to be made.  Most are OK to upload to Vimeo (and to then archive on PBU2 as detailed in Production Notes), but I couldn't review ESPB (file didn't work), and the screenshot for Fraction Matcher looked fuzzy.  Also, if any of these mention other simulations, we might want to do the slide-in to highlight that sim, so wait to upload until we make that decision.  If we do decide to use slide-ins, you may have to just listen back to all these primers to see if they mention other sims.

**Comment by schasteen** [comment]
Arnab, the items above are still currently needing to be done for these primer videos, let us know if you need anything else from us on them.

**Comment by schasteen** [comment]
ESPB is OK, and it looks like Fraction Matcher screenshot is no longer fuzzy.  @arnabp, did you check this list of sims for needed slide ins as well?
For Color Vision, we want to add some on-screen text to clarify an issue we've found with the sim.  At 0:36 please add on-screen (perhaps in the blank space at top right) the following text: 
Note:  Balloon is not filled with helium; see Teacher Tips.

Let me know when this is done, and when you have archived on PBU2.

**Comment by schasteen** [comment]
@Arnab, can you please submit a status update?

**Comment by arnabp** [comment]
These should all be done, I've swapped out all the bumpers for all these sims with the v15 one.

**Comment by schasteen** [comment]
All the new primers, and previous primers, appear to have been updated and archived appropriately.  @amyh-phet , could you close this issue, and the other on on the new sims, and get started on the captioning aspect of the project?  Also, can you find out if these can all get pushed to the site, and the captions will update as they get completed?  @arnabp , seems like you're all done with your part, let me know if that's not the case.  Thanks for everything!
