### ISSUE TITLE
Add an eslint rule to check that files register with a namespace

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#431]
From: https://github.com/phetsims/tasks/issues/378#issuecomment-155523001

> @samreid will look into an eslint rule for checking [namespace checks], after it is written we can decide when to turn on the rule.

**Comment by samreid** [comment]
I added a rule (commented out) in https://github.com/phetsims/chipper/commit/44f5105f55c51d7016aaf5464b4a779589392499

Described as:
> Check for the existence of the string '.register( \'' as a coarse measurement
> for whether a file is namespaced.  Please note, this may generate false negatives from cases that have
> a different kind of .register function (unrelated to namespace), or .register mentioned in comments, etc.

Also, the implementation ignores filenames ending in -config.js and -main.js, and ignores files that instantiate a namespace (since namespaces don't namespace themselves).

I tested it on molarity, and it correctly indicated no problems.  I tested `grunt lint` on hookes-law, and it correctly reported 54 problems.

**Comment by samreid** [comment]
I should have made this issue in chipper instead of here in tasks.  Well, let's roll with it.

**Comment by samreid** [comment]
In my opinion, this rule (though coarse) is sufficient to help us know whether a sim is namespaced and roughly how many of its files are namespaced.  I skimmed through the existing 602 occurrences of `.register( '` in our source and it seemed like there are no false positives at the moment (though future introduction of register methods will cause false positives).

Turning on the rule now would be yield thousands of problems, perhaps we should discuss how/when to turn on this rule?  Tagging @pixelzoom @jbphet @jonathanolson @jessegreenberg for discussion.

**Comment by samreid** [comment]
Also, we could consider writing another linting task that checks that *at least one* of the register calls matches the filename of the file.  Actually, that could go a long way toward ruling out false positives (as long as there are no corner cases where there is *supposed* to be a mismatch).  I'll leave this assigned to myself to investigate that.

**Comment by samreid** [comment]
In the above commit, I'm checking for a register call that matches the filename.  This drops the probability of false positives to negligible.  We still have to manually make sure the inner types are namespaced properly (as before).

**Comment by samreid** [comment]
With the above rule, all of the @pixelzoom sims crossed off in #378 still pass, and hookes-law still shows 54 issues.

This may actually lead to a script that automatically inserts the namespace call immediately after its declaration in the majority of our files.  We have the parsed AST, we can find the declaration of the function or instance that matches the filename.  Perhaps we can somehow insert this text immediately after the declaration.

**Comment by samreid** [comment]
Unassigning while I await feedback from those mentioned above.

**Comment by samreid** [comment]
Marked for developer-meeting in case we don't discuss it before then.

**Comment by pixelzoom** [comment]
> and hookes-law still shows 54 issues.

hookes-law and ph-scale have not been namespaced yet.

**Comment by pixelzoom** [comment]
Does this rule verify that inner types are also namespaced?

**Comment by jonathanolson** [comment]
> Does this rule verify that inner types are also namespaced?

How would that be detected?

**Comment by samreid** [comment]
We could use the rule that every time there is a `function MyType` pattern, where MyType is capitalized, it must be accompanied by a namespace export.  Not sure if there are occurrences of this sort where we don't want namespacing, or occurrences of the opposite sort (things that don't match this pattern that should be namespaced).

**Comment by samreid** [comment]
> Does this rule verify that inner types are also namespaced?

From a comment above:

> We still have to manually make sure the inner types are namespaced properly (as before).

**Comment by jonathanolson** [comment]
> Not sure if there are occurrences of this sort where we don't want namespacing

Things like phet-core's inherit, we don't want phetCore.F:
```js
function F() {}
```

> or occurrences of the opposite sort (things that don't match this pattern that should be namespaced)

Also things like phet-core's inherit, as it isn't capitalized. Namespaced things don't need to be types. scenery.js has a lot of non-type things that are currently on the namespace also.

**Comment by samreid** [comment]
I still find it a bit odd that we cannot leverage requirejs to automatically namespace all the things for us.

**Comment by jonathanolson** [comment]
> I still find it a bit odd that we cannot leverage requirejs to automatically namespace all the things for us.

Wouldn't work for things like Text, where we need to have it namespaced before the define() function returns the Text reference.

**Comment by samreid** [comment]
I'm moving this subconversation over to #435, see you there!

**Comment by samreid** [comment]
@jonathanolson and I worked on a rule that runs in requirejs mode when ?ea is turned on--it seems like a simpler and more robust way to check namespaces than a linting rule.  I'll remove the in-progress linting rule and close this issue.

**Comment by samreid** [comment]
Removed in https://github.com/phetsims/chipper/commit/4a6a4f669d53c9303840df22baafbfffe142b2dd
