### ISSUE TITLE
New server needs a new name

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#432]
This week we were discussing names for the new server machine.  I thought I'd create a thread here in case any wants to propose server names, ideas, etc or upvote others' suggestions.  Tagging @kathy-phet @jonathanolson @jbphet @aaronsamuel137 @jessegreenberg @mattpen @ariel-phet @aadish @arnabp @phet-steele @oliver-phet @orejolaphet  since I thought they might be interested.  Invite your friends or anyone I forgot as well.  I think I'll assign this to @jonathanolson since he'll probably be involved with getting the domain name etc set up with OIT when it is time.

For reference, the machine it will replace is named "figaro" and its cousin is named "simian" aka "phet-dev".

**Comment by samreid** [comment]
"rocky"

**Comment by jonathanolson** [comment]
In the cat theme:
- lion.colorado.edu
- tiger.colorado.edu
- ocelot.colorado.edu
- lynx.colorado.edu
- [colocolo](https://en.wikipedia.org/wiki/Colocolo).colorado.edu

Bad puns:
- sky.colorado.edu (it's always up)
- entropy.colorado.edu (never goes down)
- light.colorado.edu (doesn't slow down)

Other (non-cat)
- dog.colorado.edu (yup, not taken)
- penumbra.colorado.edu
- chimera.colorado.edu

Passing to @aaronsamuel137 for ideas.

**Comment by aaronsamuel137** [comment]
Here's a few suggestions:

- ox.colorodo.edu (strong animal, easy to type :)
- apollo.colorado.edu (greek god, like the sound of it)
- vishnu.colorado.edu (indian god, makes sure the creation is stable)

I like apollo the best of the proposed suggestions so far.

Anyone else have suggestions?

**Comment by ariel-phet** [comment]
I have to admit, I kind of like "ox"

**Comment by jonathanolson** [comment]
My current top two preferences:
- tiger.colorado.edu
- ox.colorado.edu

Both are quite type-able (excludes apollo for me) and don't sound weird out loud.

@samreid, @mattpen, @aaronsamuel137, @jbphet any further thoughts?

**Comment by samreid** [comment]
I like "ox", nice suggestion.

**Comment by pixelzoom** [comment]
+1 for ox.colorado.edu

**Comment by jessegreenberg** [comment]
I like "ox" too.  Short, sweet, and easy to type.

**Comment by aaronsamuel137** [comment]
Seems like ox is the consensus. I am going to leave this open but unassign.

**Comment by ariel-phet** [comment]
Request for "ox" sent to OIT. Closing!
