### ISSUE TITLE
Test Help Center and Translatabilty

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#434]
@oliver-phet and I discussed and we need to test the following for the new help center admin page (test question key numerical ordering vs. presented order for all):
1. Entering questions
2. Deleting questions
3. Editing questions
4. Translating questions (for all 3 above scenarios)
5. When translating, admin page switches between "up to date" and "out of date" instead of "not translated". (not correctly happening as of 11-16).

**Comment by amanda-phet** [comment]
I think we should add that the appearance of the pages should be tested on different browsers and OSes for layout or interaction issues.

**Comment by phet-steele** [comment]
Help Center is already being translated by our very proactive translators, and any problems I've seen have been fixed.
