### ISSUE TITLE
Investigate using RequireJS for namespace

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#435]
After seeing what an immense amount of work #378 will be, I'm wondering again why we cannot use RequireJS to automatically add objects to a namespace.  @jonathanolson and I looked into it at one point and had a hack/monkeypatch that allowed us to use requirejs names to access declared instances.  Could we take this further and get this working as an alternative to adding manual namespaces everywhere?  We could even patch in the names as desired.  Say, changing BENDING_LIGHT/model/Photon to map to bendingLight.Photon or whatever.

Issues:
1. Inner types would not automatically be exposed using this pattern.  We would have to do something different for them, such as defining them in a define statement, moving them to separate files or manually adding them to the requirejs namespace somehow.
2. Objects are only added to the namespace after the module is loaded, not immediately after a function is declared.

Benefits:
1. No need to manually visit every file and add namespace.register() calls, to maintain them or get their names right, or create/maintain eslint rules to do all of the aforementioned.

Flagging for discussion at developer meeting, but may be even better if some subset of @jonathanolson @jbphet @pixelzoom @jessegreenberg @samreid can come up on a consensus earlier.

**Comment by samreid** [comment]
@jonathanolson said:

> Wouldn't work for things like Text, where we need to have it namespaced before the define() function returns the Text reference.

**Comment by samreid** [comment]
Why does Text need to be namespaced before the define function returns the Text reference?

**Comment by pixelzoom** [comment]
@samreid wrote:
> After seeing what an immense amount of work #378 will be,

Immense amount of work?  I've done the work for all but 1 of my sims (ph-scale) and most of the common repos (6 to go), and it really wasn't a bit deal, pretty easy.

**Comment by samreid** [comment]
Aside from the work to add these to each file, it adds a permanent footprint in every file like:

```js
var balancingChemicalEquations = require( 'BALANCING_CHEMICAL_EQUATIONS/balancingChemicalEquations' );
//...
balancingChemicalEquations.register( 'BCERewardNode', BCERewardNode );
```

What if I now need to rename BCERewardNode?  Then I have to go through and rename all the vars.  And we are in the midst of creating a eslint rule just to make sure we get all of this right, and it cannot even check for all cases, such as inner types which will have to be checked manually.

Let me turn the question around and pose it this way: If RequireJS already had a built-in support for namespacing objects, so that they could be looked up by name after the had been `define`d, is there any reason we would *not* want to use it?

**Comment by pixelzoom** [comment]
We decided on the current approach on 10/6/2015, over a month ago. And as part of #378, all developers were supposed to test drive the approach that we decided on.  Perhaps I missed some commits, but other than @jonathanolson and myself, I didn't see any serious test driving taking place, or any real evaluation of how long it takes to namespace a sim. So I'm not going to be too happy if we decide to change this after I've done the work.  That said, if you find a better approach, I'll redo my work.

**Comment by samreid** [comment]
@jonathanolson reminded me that it is important to have namespace declarations before the requirejs module declaration is complete and it looks like https://github.com/phetsims/joist/issues/307 will be a good strategy for making sure most of the things are namespaced properly, closing.
