### ISSUE TITLE
Satellite Artwork for Gravity & Orbits

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#436]
@mariahmaephet, we would like you to create new artwork to replace the satellite that's currently in Gravity and Orbits. 

![image](https://cloud.githubusercontent.com/assets/8419308/11278297/86d9acda-8ea7-11e5-872a-9555a153fd0a.png)

You can see the current artwork in context at http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.24/gravity-and-orbits_en.html

I like the look of this satellite:
![image](https://cloud.githubusercontent.com/assets/8419308/11284442/feff34f4-8ec6-11e5-9e44-0d401cdc55a3.png)

I also like the look of these panels:
![image](https://cloud.githubusercontent.com/assets/8419308/11284474/3deb5a26-8ec7-11e5-8897-4bdfcb3965b6.png)

Perhaps @mariahmaephet and @ariel-phet can discuss this more at their meeting this upcoming Monday. Assigning to @ariel-phet for prioritization.

**Comment by mariahmaephet** [comment]
@ariel-phet @arouinfar something like this or do you want more detail? 

<img width="725" alt="screen shot 2015-12-01 at 12 26 53 pm" src="https://cloud.githubusercontent.com/assets/11527557/11511545/f2f3d5e8-9826-11e5-83d2-9bbfd0cc4d31.png">

**Comment by ariel-phet** [comment]
@mariahmaephet I might try putting some "gold foil" on the satellite body (just to brighten it up against the black background) - maybe just on the bottom half. But otherwise, looking nice!

**Comment by ariel-phet** [comment]
@arouinfar - your thoughts?

**Comment by arouinfar** [comment]
Great start @mariahmaephet! 

I would like to see a little bit more tiling detail on the solar panels. The tiling could be subtle -- no need to be as detailed as the reference photos.

I would also like to see the "gold foil" @ariel-phet proposed.

**Comment by mariahmaephet** [comment]
@ariel-phet @arouinfar 

<img width="451" alt="screen shot 2015-12-09 at 11 09 41 am" src="https://cloud.githubusercontent.com/assets/11527557/11694092/612ff656-9e65-11e5-98a5-d773bffa8f6d.png">

**Comment by ariel-phet** [comment]
@arouinfar feedback on this?

**Comment by arouinfar** [comment]
@mariahmaephet sorry for not noticing this sooner! The gold foil looks good to me. I also like what you've done with the tiling, but it feels just a tad too heavy. Perhaps the colors of the tiles could be a bit more similar so they don't have quite so much contrast/visual weight.  

Anything to add @ariel-phet?

**Comment by mariahmaephet** [comment]
@arouinfar @ariel-phet is this better?
<img width="655" alt="screen shot 2016-01-27 at 2 59 32 pm" src="https://cloud.githubusercontent.com/assets/11527557/12629785/99618b30-c506-11e5-92b1-4639fa4630da.png">

**Comment by arouinfar** [comment]
Looks great! Thanks @mariahmaephet. I don't have any other tweaks to request, but perhaps @ariel-phet does.

**Comment by ariel-phet** [comment]
Looks great to me! Can you upload to drive and reassign to me?

**Comment by mariahmaephet** [comment]
@ariel-phet in my artwork folder

**Comment by ariel-phet** [comment]
excellent, closing
