### ISSUE TITLE
Testing website in other locales for oddness

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#438]
@phet-steele this is a bit of a background task, but when you get a chance it would be good to poke around the site and see if we have missed anything in terms of oddness to do with viewing in another locale.

For instance, some "oddness" we fixed was that when you went to "by device" and viewed in another locale a bunch of non-HTML5 sims were populating the iPad category. Basically be on the look out for things like that do not seem to make sense. We are pretty sure we covered most of the bases and fixed the problems, but it would be good to have another set of eyes.

**Comment by phet-steele** [comment]
Roger. I'll keep my eyes peeled while translating the Help Center, too.

**Comment by ariel-phet** [comment]
doesn't seem like anything problematic has been observed or reported. Closing.
