### ISSUE TITLE
Get JB's computer setup

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#439]
Software for @jbphet computer:
CU Windows 10
Git
Skype
Adobe CS6
Intellij
Secure Shell Client
All Browsers
CU VPN client
7 zip
Office
Zoom
WinHTTrack
Collabnet Subversion Client

**Comment by oliver-phet** [comment]
Looks like everything is good to go except Collabnet (requires login) and Secure Shell Client (which specific client?)

**Comment by oliver-phet** [comment]
@arnabp We got adobe licensed properly. Just need you to fix the dpi scaling and look into moving @jbphet email archives on his old computer to the new one.

**Comment by arnabp** [comment]
DPI scaling is fixed. When do you want to look at the email archives next week? (my times on the student calendar are accurate)

**Comment by jbphet** [comment]
I think I can take it from here.  Thanks for your help on this!
