### ISSUE TITLE
dev test arithmetic 1.0.0-dev.16

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#440]
This sim is getting close to publication, and it would be good to do a round of dev testing.  Please first emphasize basic functionality testing, then test on a few browsers, including on an iPad.

**Comment by jbphet** [comment]
Link: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/

**Comment by ariel-phet** [comment]
- [ ] Chrome/Windows
- [ ] Mac/Safari
- [ ] Win/Edge
- [ ] iPad2/iOS9

**Comment by orejolaphet** [comment]
Testing Mac/Safari

**Comment by phet-steele** [comment]
Win/Chrome for this guy!

**Comment by elisemorgan** [comment]
iPad2

**Comment by brroberts1231** [comment]
Win/Edge

**Comment by bryo5363** [comment]
I tested Win/Chrome since it was the last element left. Testing is now complete.

**Comment by ariel-phet** [comment]
Testing complete, closing
