### ISSUE TITLE
Revolutions off by a factor of 2 in Ladybug Revolution

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#441]
From phethelp:

> We are working on the Lady Bug Revolution simulation today.  I had my students set the angular velocity to 60 degrees per second.  I asked them to determine the number of revolutions per minute of the lady bug.  At 60 degrees per second, the bug should travel one lap in about 6 seconds, since there are 360 degrees in one revolution.  This would give about 10 laps in one minute.  Our results were getting about 5 laps in one minute.  You may want to check the programing for accuracy in these numbers.

**Comment by samreid** [comment]
@ariel-phet said:

>  Hey Sam,

> See below...(I will write the teacher back).

> I checked this on my home desktop, and the revolution was in fact off by a factor of 2. Is there some java update that screwed this up? I have a hard time believing it has been wrong all this time?

> Ariel

**Comment by samreid** [comment]
@ariel-phet said:

> Did some testing and easy to reproduce. CM produced on Java 7 as well. Teacher was running on windows 7, java 8 update 60, I ran and reproduced on Win 7 Java 8 update 66

**Comment by samreid** [comment]
Thanks!  The next step would be to check historical versions on spot here: http://www.colorado.edu/physics/phet/dev/rotation/  I was planning to do that but really anyone could check it.

**Comment by samreid** [comment]
@ariel-phet said:

> Feel free to make a task and assign it to me

**Comment by samreid** [comment]
Thanks, I'll take a quick look first.

**Comment by samreid** [comment]
It looks like you can see the same problem if you set angular velocity to 360 degrees per second.  I did so and saw that it took the ladybug 10.1 seconds to go around 5 times.

**Comment by samreid** [comment]
Problem noted in 1.12.00 published on 26-Oct-2012
In 1.00.00 published on 27-Jul-2007 the problem is more exaggerated, taking 11.5 seconds to go around 5 times (at a purported 360 deg/s).

I also noticed that the 1.00.00 version of the simulation is charts-only (no intro screen).

I recall in our older simulations we struggled with having simulations consistently match "wall time" across devices of varying speeds.  In this case, we may have just settled with having the simulation be internally consistent but not match "wall time" at all.  Looking into this further:

RotationClock.java reports:

```java
    private static final double FPS = 20;
    public static final int DELAY = (int) ( 1000.0 / FPS );
    public static final double DEFAULT_CLOCK_DT = DELAY / 1000.0 / 2;
```

It looks like this factor of 2 was introduced in commit 18277:  "10-17-2007: Torque - Fixed: Changed time slider to vary from slow to fast, default time should be in the middle".

When I put the speed to "Fast" in the 2nd screen, I see that 10 revolutions at 360deg/sec takes 10.0 seconds.  So I suspect at realtime the angle was going offscreen too quickly and we wanted it to run a bit slower by default and we kept the reduced speed on the 1st screen for consistency between screens.

Reassigning to @ariel-phet to discuss what's next.

**Comment by pixelzoom** [comment]
@samreid wrote:
> `public static final double DEFAULT_CLOCK_DT = DELAY / 1000.0 / 2;`
> It looks like this factor of 2 was introduced in commit 18277: "10-17-2007: Torque - Fixed: Changed time slider to vary from slow to fast, default time should be in the middle".

For @ariel-phet's benefit... This is the line of code that I said looked suspect when we were discussing on Skype yesterday.

**Comment by pixelzoom** [comment]
@samreid wrote:
> `public static final double DEFAULT_CLOCK_DT = DELAY / 1000.0 / 2;`
> It looks like this factor of 2 was introduced in commit 18277: "10-17-2007: Torque - Fixed: Changed time slider to vary from slow to fast, default time should be in the middle".

For @ariel-phet's benefit... This is the line of code that I said looked suspect when we were discussing on Skype yesterday.  Removing the `2` made the rotation occur faster, but still not at the correct wall-clock time.

**Comment by pixelzoom** [comment]
Related note... I realize that @ariel-phet probably create this issue in GitHub because Unfuddle is harder to deal with.  But if we start spreading issues across Unfuddle and GitHub, then future maintainers won't know where to look.  So I suggest that we keep Java/Flash issues in Unfuddle, and recommend moving this issue there.

**Comment by ariel-phet** [comment]
@pixelzoom I had merely suggested making a task for checking historical versions (that seemed appropriate since it could be something a QA student does), But I agree, this code related discussion should be in unfuddle.

**Comment by ariel-phet** [comment]
@samreid please move to an unfuddle issue, and if an easy fix, here is what I suggest:

1. Leave the second tab "as is"...since there is a time readout on the graphs, I see no issue here, someone can see what is going on with the timing.

2. On the first screen, set the timing to match realtime, since if teachers want to do experiments like the one who wrote to phethelp, their students will be able to get accurate results.

**Comment by ariel-phet** [comment]
@samreid please also close this issue once move to unfuddle

**Comment by pixelzoom** [comment]
@ariel-phet Thanks for the clarification in https://github.com/phetsims/tasks/issues/441#issuecomment-161474734. It looked to me by the title and comments (eg https://github.com/phetsims/tasks/issues/441#issuecomment-161437077)that this issue was being investigated and debugged here.

**Comment by samreid** [comment]
Status update:
Moved to https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3713
Committed a fix
Building from OS X has this failure:
![image](https://cloud.githubusercontent.com/assets/679486/11658734/63d21c02-9d81-11e5-81e4-4f89530b9614.png)

I should try building from my Win8.  Next step will be to publish a dev version for verification.

**Comment by samreid** [comment]
I published a new version here http://www.colorado.edu/physics/phet/dev/rotation/1.12.02/ 
@pixelzoom @jonathanolson @jessegreenberg @mattpen @jbphet let's code freeze simulations-java until this is published.

@ariel-phet can you test this version and make sure it is satisfactory?  After that, we can create a tasks issue to perform broader dev testing before we republish the sim.

**Comment by pixelzoom** [comment]
Re the Java error on Mac OS X...  It used to be the case that, if you had an old Java 6 installed, it would continue to run.  Starting with OS X 10.10, Apple crippled Java 6 by removing some critical files.  So you'll need to install Oracle Java 7 or 8.

**Comment by ariel-phet** [comment]
@samreid I tested and all looks good. I assume this was a very small change in terms of being invasive? I am hesitant to do dev testing...the sim has many types of interaction that do not really go with our current way of doing things...I think you will get lots of unnecessary bug reports. No offense to the original creators, but this one needs some serious overhauling.

Can you give me thoughts on percentage chance everything is fine considering your change and my testing?

**Comment by samreid** [comment]
The change to rotation was trivial and not a significant source of risk.  The larger issue is if other changes have crept in to the dependencies.  The only significant change I see to common code since August 2015 are related to the "Ask" feature.  @pixelzoom is that to a stable point?

**Comment by pixelzoom** [comment]
All work on the "Ask" feature was backed out, since it's no longer an "in sim" feature.

**Comment by samreid** [comment]
Based on my brief investigation into the SVN history and @pixelzoom remarks, it seems safe to republish.  @ariel-phet if you agree, give the go-ahead and I'll push the button.

**Comment by ariel-phet** [comment]
Yes please republish

**Comment by samreid** [comment]
Ladybug Revolution 1.13
and
Torque 1.13

were republished and spot tested.  Torque crashed on Mac on angular momentum screen after playing audio--probably not a new problem and I can't seem to reproduce it.

Reassigning to @ariel-phet to do any desired verification steps and to notify the customer.

**Comment by ariel-phet** [comment]
Customer notified. Closing
