### ISSUE TITLE
Check local printing companies about business cards

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#442]
@ariel-phet

**Comment by oliver-phet** [comment]
http://www.8days.com/
http://www.mpboulder.com/

**Comment by oliver-phet** [comment]
@mariahmaephet If you are available, could you create 8.5"x11" pdf's (front and back) of our latest business card? Add bleeds to the cards. The latest file is called "kathy-perkins-card.ai" Put some of both the general orange card and Kathy blue card on the sheet. 

The two local printers need this to do proofs of the card so that we can compare quality and decide who to go with for our next batch order.

**Comment by mariahmaephet** [comment]
@oliver-phet Hey Oliver--I'm just a little confused which ones you want (there's a bunch on drive and that .ai file only has the backs).

**Comment by ariel-phet** [comment]
@mariahmaephet 

I think you might be looking in the wrong place, try here:

https://drive.google.com/drive/folders/0B5JSfRAuRHDzZnFDOGt5dl92WDg

**Comment by oliver-phet** [comment]
@mariahmaephet The link Ariel shared is correct - please create the pdf's from the 'kathy-perkins-card.ai'  file.

**Comment by ariel-phet** [comment]
Seems we have found a solution with CU imaging services, closing
