### ISSUE TITLE
Update student availability calendar

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#444]
@brroberts1231 
@BryceAG 
@phet-steele 
@bryo5363 
@orejolaphet 
@arnabp 
@elisemorgan 
Can all of you guys (as soon as you know) please update the student availability calendar for the holiday break? @ariel-phet and I need to have a gauge on who is going to be around. Thanks!

**Comment by ariel-phet** [comment]
@brroberts1231
@BryceAG
@phet-steele
@bryo5363
@orejolaphet
@arnabp
@elisemorgan please comment in this issue when you have made updates. Thanks!

**Comment by elisemorgan** [comment]
@ariel-phet I am up to date
