### ISSUE TITLE
create a mailing list for PhET developers

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#446]
During the 12/8/2015 developer meeting @pixelzoom suggested setting up an email list for PhET developers.  Group consensus was that this would be a good thing to have.  The suggested name is phet-dev@lists.colorado.edu.  This list should include anyone who is on the PhET mailing list who also is a developer.

**Comment by jbphet** [comment]
I'm guessing that this should be assigned to @oliver-phet, but am not certain, he can reassign as appropriate.

**Comment by oliver-phet** [comment]
This has now been created and all devs have been added to the list.
