### ISSUE TITLE
add instructions related to branch-and-patch to sim_deployment.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#447]
From 12/8/15 dev meeting notes:

CM: beware that if you branch-and-patch a common repo, you’ll need to manually check out that repo’s branch after doing ‘grunt checkout-shas’
Example:
% cd graphing-lines
% git checkout 1.1
% grunt checkout-shad
% cd ../vegas
% git checkout graphing-lines-1.1
% cd ../graphing-lines
5 grunt

JG: add something to sim_deployment.md? 
https://github.com/phetsims/phet-info/blob/master/sim_deployment.md

**Comment by pixelzoom** [comment]
sim_deployment.md has been update. @jessegreenberg please review.

**Comment by jessegreenberg** [comment]
Looks great @pixelzoom.  This should be a helpful reminder for sims that need a branch and patch of a common repo.  Thanks for including the example. Closing.
