### ISSUE TITLE
Determine method for allowing IDRC to contribute to repositories

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#448]
IDRC is going to start contributing code to PhET repositories.  Specifically, they will add some content to John Travoltage for accessibility.  We need to determine what needs to be done to allow these contributions.

Developer consensus is to allow IDRC to push to sim repositories but not common code.  For changes to common repositories, we can collaborate to implement changes.

IDRC will also need a signed CLA.  Developer understanding is that this will need to be executed by IDRC and the contributing developer.

@ariel-phet, are you OK providing IDRC with rights to push to a simulation?  How should we proceed with the CLA?

**Comment by ariel-phet** [comment]
Yes, I think we are fine providing IDRC with those rights. @jessegreenberg feel free to email a copy of the CLA to the appropriate devs or give me their contact and I will take care of it. If you send it to them please cc me.

**Comment by jessegreenberg** [comment]
It looks like the CLA document is private, I am unable to access it.  @ariel-phet, I will send an email to you with the contact information of the contributing dev.  Does a copy of the CLA also need to be completed on behalf of the IDRC in addition to the dev?

**Comment by jessegreenberg** [comment]
Before I send the contact info, I will check to see if any other devs from IDRC plan to contribute code to PhET.

**Comment by jessegreenberg** [comment]
Email sent to @ariel-phet, reassigning.

**Comment by ariel-phet** [comment]
Email sent to the IDRC folks. Will close this issue once CLA's are returned and uploaded to unfuddle.

**Comment by ariel-phet** [comment]
IDRC asked for an "institutional version" of the CLA, CU's lawyers have provided one, and it has been sent to IDRC

**Comment by ariel-phet** [comment]
IDRC signed the institutional version, and it has been uploaded to the unfuddle notebook. Closing.
