### ISSUE TITLE
PhET Email Signature logo/look

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#449]
We need to create a standardized, clean, signature logo or look that should start to be used in all "outward-facing" emails (phethelp, phetmail, donation asks, etc)

Assigning to myself for now.

**Comment by oliver-phet** [comment]
Current list of automatic emails:

1. Confirm your account
2. Welcome to PhET
3. Email change confirmation
4. PhET Newsletter Subscription Confirmation (when confirmed)
5. Please Confirm Your PhET Subscription (newsletter only)
6.

**Comment by mattpen** [comment]
Additionally the website automatically sends an "Email change success" message.

**Comment by mattpen** [comment]
@oliver-phet - Can you send me the html/css code that you wrote for the salesforce emails so I can import the style into the website template?

**Comment by ariel-phet** [comment]
@oliver-phet it seems this issue has moved forward (and you have a pretty good template at this point). I am closing it, reopen if you feel necessary.
