### ISSUE TITLE
update test machines to iOS 9.2 and Mac OS X 10.11.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#451]
iOS 9.2 and Mac OS X 10.11.2 were released in the past few days. Time to update the test machines. Assigning to @ariel-phet to decide which machines and who will do the updates.

**Comment by oliver-phet** [comment]
@brroberts1231 @BryceAG

**Comment by ariel-phet** [comment]
For any iPad's **already** on iOS 9, please put them to the latest version, but leave the iOS 8 iPad on iOS8 (Lave), the two iPad minis can also be upgraded to iOS9

**Comment by ariel-phet** [comment]
Please upgrade the 10.11 on Dirac and Erdos to Mac OS 10.11.2

**Comment by BryceAG** [comment]
Dirac, Witten, Tycho, diSessa, Euler, and Leibniz have all been updated. Bjork is being updated through iTunes on Dirac.

**Comment by pixelzoom** [comment]
I updated the test matrix template, https://docs.google.com/spreadsheets/d/1vk0QUOOOj_Jr4ePVgwiQ5L7HOsvgor7jkbNYqmCVWnQ/edit

**Comment by ariel-phet** [comment]
Looks good. Closing. Thanks @pixelzoom
