### ISSUE TITLE
Test Bending Light 1.0.0-rc.1

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#456]
The first release candidate for Bending Light is ready for testing.  

**Test Matrix**
https://docs.google.com/spreadsheets/d/1__9A1CBoW9C5xrWVfADcR1zR09PhuKbIJC-b275LMKM/edit#gid=2

**Main Testing Link**
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-rc.1/bending-light_en.html

**Additional QA items:**

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] webgl=false

@ariel-phet I added the **Additional QA items** based on what I saw in the 1st Arithmetic RC task (@jbphet surmised that you may have added them).  Feel free to add/remove items as you see fit.

Reassigning to @ariel-phet to review the links and items above, then to prioritize/reassign for testing.

**Comment by ariel-phet** [comment]
@elisemorgan sounds like you will be around so please help with this testing

@BryceAG @bryo5363 @phet-steele @orejolaphet @brroberts1231 if any of you are around next week it would be great to have your work on this sim

@amyh-phet @arouinfar @oliver-phet @amanda-phet if you have time it would be go to work on a couple platforms (I will also hop in on testing as it would be great to get this sim finished off and published!)

**Comment by amanda-phet** [comment]
FYI, on OS X 10.10, having the sim open in Firefox (never touched) used 71% of my CPU. It's not in the testing matrix but I wanted to share it here in case there is a memory leak.

**Comment by ariel-phet** [comment]
@amanda-phet FF in Win 7 is only at ~10% cpu on my home desktop when playing with white light on the prisms screen. Can you try restarting your computer and only having FF open and seeing if you get the same sort of heavy CPU usage?

**Comment by samreid** [comment]
My OS X 10.11.1 + Firefox 42.0 (on 2012 Macbook Air) reports high CPU during startup, then settles down once to <10% the sim has launched (never touched):

![image](https://cloud.githubusercontent.com/assets/679486/11909403/91c4d1c0-a5a3-11e5-9a43-e680a04f4c0f.png)

When I checked FF version, it wanted to update, so I'll report on that next.

**Comment by samreid** [comment]
I'm seeing about the same CPU usage on FF 43.0.1

**Comment by amanda-phet** [comment]
@ariel-phet I did as you instructed and it still happens (up to 96% CPU). However, it is when one of the three screens is open, not the homescreen. I'm not interacting with the sim. It seems to resolve itself if I open Github in another tab, though. But a third tab sends Firefox to 150% CPU. 

It also happens with Safari (up to 34% CPU) and Chrome (well, [Google Chrome Helper] (http://www.wired.com/2014/10/google-chrome-helper/)) (up to 77%).

**Comment by ariel-phet** [comment]
@amanda-phet can you try another sim? like ESPB and see if you are seeing similar issue?

**Comment by ariel-phet** [comment]
And @amanda-phet - please update FF (that is a *very* old version)

**Comment by amyh-phet** [comment]
@ariel-phet    This will be top priority for me on Monday.   I'll coordinate with @arouinfar @elisemorgan and the rest of the QA team to get this done quickly.

**Comment by amanda-phet** [comment]
@ariel-phet the CPU hogging still happens with FF 43.0.1 when the tab is open to a screen or I am using the screen. It is happening with ESPB as well. It is also still happening with Safari. I use FF all the time and haven't noticed this with other sims, so I thought it was worth mentioning, but if you're thinking it's only my machine or we're no longer supporting OS X 10.10 then we can let it go. 

Also, the actual performance of the sim does not seem to be an issue, only the computer fan turning on (which no one likes, but it's not making my computer crash or anything).

**Comment by arouinfar** [comment]
Everything's been looking good over here! When starting out on 10.11.2/Chrome, my fan almost immediately kicked itself on, but I didn't notice abnormally high CPU usage. I'm going to give it a try on my personal Mac (running 10.10) to see if I have similar issues.

Looks like the testing matrix is complete, except for the optional Win 10/Edge iFrame test which may be tricky to do since we've been relying on JB's Win10 machine for testing.

**Comment by elisemorgan** [comment]
@ariel-phet the testing matrix is complete. 
@samreid Just to let you know, when the I used webgl=false on the iPad, the graphics quality improved significantly and the wave light no longer disconnected from the generator.

**Comment by ariel-phet** [comment]
Excellent, closing
