### ISSUE TITLE
Test Bending Light 1.0.0-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#457]
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-rc.2/bending-light_en.html

There are 3 issues in Bending Light marked as "ready for review".  Each just requires minimal spot testing on a single platform.  Aside from this, there should also be a "sanity test" on a single platform that nothing has been disturbed.

@arouinfar volunteered over email, so I'll assign this to her.

**Comment by arouinfar** [comment]
I'm on it @samreid!

**Comment by arouinfar** [comment]
Testing completed on Mac OS X 10.11.2 and Chrome 47.0.2526.106. Everything looks great! Should we do a sanity test on a PC as well?

**Comment by ariel-phet** [comment]
I will do one right now..

**Comment by samreid** [comment]
The differences between rc.1 and rc.2 are minor and are not expected to create differences across platforms, but a quick windows test would be nice.

**Comment by ariel-phet** [comment]
Spot testing all looking good! I think you have the green light to publish @samreid 

@arouinfar once Sam has published you will need to go through and upload categories, related sims and such.

**Comment by arouinfar** [comment]
Awesome! I'll go ahead and close this issue.

> @arouinfar once Sam has published you will need to go through and upload categories, related sims and such.

Will do! @samreid please let me know when the sim is up and ready for this. I can take care of the categories, etc. and then make the sim visible.
