### ISSUE TITLE
Make Trish's iPad a test device

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#458]
@patricialoeblein returned her iPad to the project, and it should probably be turned into a testing device (reformatted, iOS 9 installed, named, labelled, and added to our asset inventory). The iPad and charger are currently sitting on the desk in device office (F1011). The iPad has something to the effect of "Trish PhET" written in sharpie on the back.

Assigning this to @ariel-phet to reassign and prioritize (though @oliver-phet may also be able to do this).

**Comment by ariel-phet** [comment]
Hmm, I might grab this for myself @arouinfar - there are several time now when a developer has asked me to evaluate performance or such on an ipad and I have been working from home. It would certainly be handy.

**Comment by ariel-phet** [comment]
I have taken this iPad as a personal test device. I have named it "Loeblein" in honor of @patricialoeblein :). It has been added to the asset matrix. Closing.

**Comment by patricialoeblein** [comment]
Phunny name  Thanks☺

Trish
