### ISSUE TITLE
Test Neuron 1.0.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#459]
Neuron is ready for some release testing.  There are several issues that I have left open because they are a bit complex to duplicate, and were challenging to fix, so I'd like someone else to verify that they no longer occur.  These issues are:

- [x] https://github.com/phetsims/neuron/issues/88
- [x] https://github.com/phetsims/neuron/issues/91
- [x] https://github.com/phetsims/neuron/issues/92
- [ ] https://github.com/phetsims/neuron/issues/93

The test matrix is here: https://docs.google.com/spreadsheets/d/13lSN1kUHkqDnar9EkoMerj-WCuVfxAZwnqgxjUGTSe0/edit#gid=2

The release candidate itself is here: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.1/neuron_en.html

**Comment by ariel-phet** [comment]
@elisemorgan it looks like you are the only tester currently working this week.

@orejolaphet please help on this next week if it is not yet finished

@amanda-phet @amyh-phet @arouinfar @oliver-phet  if you have a little time would be great to test a platform, but OK if this waits until after the holidays (if not complete)

**Comment by ariel-phet** [comment]
**Additional QA items:**

- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] webgl=false

**Comment by bryo5363** [comment]
I noticed that issue phetsims/neuron#93 is present on Microsoft Edge 25.10586.0.0

**Comment by bryo5363** [comment]
It appears that testing is complete. The only previous issue that remains is phetsims/neuron#93 for Microsoft Edge

**Comment by elisemorgan** [comment]
Noticed phetsims/bending-light#335 is present on Chromebook

**Comment by arouinfar** [comment]
The testing matrix is complete @jbphet @ariel-phet.

**Comment by ariel-phet** [comment]
Good, closing
