### ISSUE TITLE
Test Java version of Isotopes and Atomic mass

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#461]
@bryo5363 can you test the Java version of Isotopes and Atomic Mass. We are porting this sim, and it would be good to identify any existing bugs.

**Comment by ariel-phet** [comment]
Report any existing bugs in the repo and please label "java bug"

**Comment by bryo5363** [comment]
I'm on it

**Comment by ariel-phet** [comment]
@bryo5363 - is there any more to do here, or do you feel testing is complete?

**Comment by bryo5363** [comment]
I do not believe so. Most of the issues have been addressed.

**Comment by ariel-phet** [comment]
Excellent, closing
