### ISSUE TITLE
Transferring ownership of Trish google docs

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#463]
@phet-steele could you work on transferring ownership of all @patricialoeblein google docs so that they are:

 - owned by phethelp@gmail.com
 - shared with phet-team@googlegroups.com

@patricialoeblein said she may have several accounts, and she will be willing to share account info with you over the phone.

You should be able to do much of this transfer in bulk (if you have questions ask myself or @oliver-phet) 

In addition, sharing with the google group and changing of ownership should be done **WITHOUT** sending an email notification (this is an option, and will avoid people being bombarded with notification emails)

**Comment by phet-steele** [comment]
10-4

**Comment by phet-steele** [comment]
Taken care of!
