### ISSUE TITLE
Forwarding messages from phetmail@colorado.edu account 

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#464]
It was discovered that there is a significant number of email received at the phetmail account that was not being handled as this should be an account for sending out newsletters etc.  In a discussion with @jonathanolson we decided to setup a filter to forward the mail to phethelp in order to respond.  

However, the majority of the mail received at this account is delivery status delay or failure notifications from the newsletter mailings. @oliver-phet - if you have some time it would be good to collaborate on choosing a filter so that phethelp isn't inundated with junk.

**Comment by mattpen** [comment]
@oliver-phet - Any thoughts on which messages should be forwarded (if any)?

**Comment by oliver-phet** [comment]
Non-spam, personal emails either in reply to a newsletter or sent directly to phetmail. Would that be possible? Or perhaps it would make more sense to setup an auto-reply from phetmail so that users know the email will not be received?

**Comment by oliver-phet** [comment]
Assigning this back to @mattpen. Let me know if/how we can setup forwarding.

**Comment by mattpen** [comment]
> Non-spam, personal emails either in reply to a newsletter or sent directly to phetmail

@oliver-phet - This is a stale issue, but should probably be addresed.  I don't think its possible to create a reliable filter for this.  The amount of legitimate email to this account is very small and the volume of email received is quite large.  Perhaps it would be better if we just setup an automatic reply that said please contact phethelp@colorado.edu?

**Comment by oliver-phet** [comment]
Yeah, I like that idea.

**Comment by oliver-phet** [comment]
@mattpen Did you setup the automatic reply you suggested in your last comment, or should I do that?

**Comment by mattpen** [comment]
@oliver-phet - I haven't found time to set it up yet, I'm sorry.  Feel free to set it up if you want to.  Do you need credentials?

**Comment by mattpen** [comment]
@oliver-phet - It looks like there has been more "legitimate" mail to this inbox recently.  I added a filter to this account that may work.  I'm currently sending the mail that passes this filter to the folder "Potential Whitelist".  Can you take a look and see if that would be reasonable for forwarding to phethelp?

**Comment by oliver-phet** [comment]
@mattpen That all looks fine to forward. Another alternative I thought might be to just send an automatic return to any mail received that says something like "This email account is not monitored. To contact PhET, please email phethelp@colorado.edu." ?

**Comment by mattpen** [comment]
@oliver-phet - I thought of that also, but I'm worried that it creates a less than ideal user experience.   I can put that in place using the vacation responder if you don't think it will be a problem.

**Comment by oliver-phet** [comment]
How about for now, setup the automatic forwarding. If that isn't working we can change it to a vacation responder.

**Comment by mattpen** [comment]
@oliver-phet - OK the forwarding is in place.  If the inbox gets overwhelmed we can filter it out with "to:phetmail@colorado.edu".

**Comment by mattpen** [comment]
@oliver-phet - Please reassign me if we need any further changes.

**Comment by oliver-phet** [comment]
This looks to be setup and working properly. Closing.
