### ISSUE TITLE
RC test: Balancing Chemical Equations 1.1.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#466]
Here's the RC version:

http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.0-rc.2/balancing-chemical-equations_en.html

This RC does not require a test matrix.  It requires spot testing this feature enhancement on 1 or 2 platforms: 

- [x] https://github.com/phetsims/balancing-chemical-equations/issues/110 (display best times in the game)

@ariel-phet Please assign this to someone to test. 

Tester: Please indicate which platforms the above feature was tested on.  If you find any problems, please reopen the above issue and make notes there. Thanks.

**Comment by ariel-phet** [comment]
@phet-steele please take care of this spot test. Thanks!

**Comment by phet-steele** [comment]
:+1: good to go on Win 8.1 FF and OS X 10.11.2 Chrome (Dirac).

**Comment by pixelzoom** [comment]
Thans @phet-steele.

RC testing completed. Self-assigning to publish 1.1.0.

**Comment by pixelzoom** [comment]
1.1.0 published. Closing.

Thanks to all the testers!
