### ISSUE TITLE
test Gravity Force Labs 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#467]
Release candidate is ready for testing.

Test Matrix: https://docs.google.com/spreadsheets/d/1Hbe-bDR0VC23nS-pyl4UpsO16HPZ1ayt-yWgyZh1OL0/edit#gid=59768831

RC itself: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/1.2.0-rc.1/gravity-force-lab_en.html

**Comment by jbphet** [comment]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Perform RC testing

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
This sim should be current top testing priority @phet-steele @elisemorgan @orejolaphet @BryceAG @brroberts1231 @bryo5363

**Comment by ariel-phet** [comment]
Testing complete closing
