### ISSUE TITLE
Artwork for Proportion Playground

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#468]
As discussed with @mariahmaephet and @ariel-phet today, the following artwork is needed for this sim:
- [x] Two differently colored beads: one round, one square
- [x] A paint splotch that can easily be drawn in code (it will scale and change color), perhaps with some dimension or a fun appearance that is not reminiscent of nickelodeon 
- [x] A paint can pouring out some paint into a small puddle (color can be easily changed)
- [x] A pile of paint-balloons 
- [x] A simple red apple 
- [ ] Two storefronts or fruit stands with different names on top (possibly different appearances), a clear playspace, room for the unit price below
- [x] A shallow basket to contain up to 20 apples (they must all be visible/countable) 
- [x] Modified PhET girl coin that is viewed at an angle and has some dimension to it so that it can be stacked 

See the [design doc](https://docs.google.com/document/d/1Wxllib53wfCG2qbTmKFI--OImBgsM9Yx3VrxwTu7lJg/edit#) for simple mockups of these items.

**Comment by amanda-phet** [comment]
After we see how the storefronts/fruit stands turn out, I am thinking we might want similar "scenes" to set the, well, scene, for different contexts in this sim. 

I'm thinking a brick wall for the paintball scene but am not sure about the others. We have to be sure these kinds of things can scale well when users drag a browser window to be larger.

**Comment by mariahmaephet** [comment]
@amanda-phet @ariel-phet 
<img width="318" alt="screen shot 2016-01-27 at 2 11 10 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628361/0655a520-c500-11e5-9a9f-d868fc74af19.png">
<img width="550" alt="screen shot 2016-01-27 at 2 11 23 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628362/065aa142-c500-11e5-82e7-4f391e4cf442.png">
<img width="513" alt="screen shot 2016-01-27 at 2 11 31 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628363/065b2f68-c500-11e5-8161-f33cf8367f82.png">
<img width="201" alt="screen shot 2016-01-27 at 2 12 08 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628364/06622d18-c500-11e5-91ee-3682419d4a13.png">
<img width="257" alt="screen shot 2016-01-27 at 2 12 17 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628366/06680e68-c500-11e5-95ca-f5349744ae68.png">
<img width="517" alt="screen shot 2016-01-27 at 2 13 01 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628375/190da172-c500-11e5-88a4-0e6037d1538d.png">
<img width="566" alt="screen shot 2016-01-27 at 2 15 31 pm" src="https://cloud.githubusercontent.com/assets/11527557/12628449/72e36ff6-c500-11e5-81a8-49efb2ec625f.png">
<img width="412" alt="screen shot 2016-01-27 at 2 45 13 pm" src="https://cloud.githubusercontent.com/assets/11527557/12629322/98c12944-c504-11e5-8dbf-61a79b9193ef.png">

**Comment by mariahmaephet** [comment]
Let me know about any modifications--I wasn't sure about the beads... they're so simple I can't really think of a way to change them without getting too complicated.

**Comment by amanda-phet** [comment]
I will start putting these in the mockups to see how well they work and let you know if I see places for modifications. Thanks!

**Comment by mariahmaephet** [comment]
@ariel-phet @amanda-phet 
<img width="476" alt="screen shot 2016-02-05 at 3 24 21 pm" src="https://cloud.githubusercontent.com/assets/11527557/12860874/a8ee2e2e-cc1c-11e5-932f-4eb7bb48a2bb.png">

<img width="407" alt="screen shot 2016-02-05 at 3 25 27 pm" src="https://cloud.githubusercontent.com/assets/11527557/12860906/d4562bc0-cc1c-11e5-92f1-59e8c8775fef.png">
<img width="322" alt="screen shot 2016-02-05 at 3 26 20 pm" src="https://cloud.githubusercontent.com/assets/11527557/12860907/d45c9014-cc1c-11e5-9dec-fe7b00176caa.png">

**Comment by ariel-phet** [comment]
@amanda-phet handing this back to you if any feedback is needed.

**Comment by ariel-phet** [comment]
@amanda-phet Can this be closed now?

**Comment by amanda-phet** [comment]
Yes.
