### ISSUE TITLE
RC test: Reactants, Products and Leftovers 1.1.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#469]
Here's the RC version:

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.0-rc.2/reactants-products-and-leftovers_en.html

This RC does not require a test matrix. It requires spot testing this bug fix on 1 or 2 platforms:

- [ ] https://github.com/phetsims/reactants-products-and-leftovers/issues/42 (Infinite Sandwiches!)

I'm going to assign this to @phet-steele, since he reported this diabolical bug and is therefore uniquely qualified to help consign it to the dustbin of history (or something like that).  Please indicate which platforms you tested on. If you find any problems, please reopen the above issue and make notes there. Thanks.

**Comment by phet-steele** [comment]
@pixelzoom I tested on iPad 3 iOS 9.2 (disessa) and Win 8.1 Chrome. All looks good, you got the green light from me!

**Comment by pixelzoom** [comment]
Thanks @phet-steele. Back to me.

**Comment by pixelzoom** [comment]
1.1.0 deployed, closing.
