### ISSUE TITLE
Test release candidate 5 for charges and fields

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#471]
A new release candidate was published here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.5/charges-and-fields_en.html 

And the test matrix is here: https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=32007012

You should test the canvas version of the simulation by setting webgl=false on chrome and firefox and i.e.
e.g. 
http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.5/charges-and-fields_en.html?webgl=false

Reassigning to @ariel-phet to prioritize and reassign.

**Comment by ariel-phet** [comment]
@veillette thanks for getting this setup. @jonathanolson and I are going to make a couple minor tweaks to handle some i18n issues, but otherwise things are looking really good!

**Comment by ariel-phet** [comment]
Since we made some tweaks, and JO has made some recent performance improvements, we are first going to dev test the latest version before full RC. Closing.
