### ISSUE TITLE
Add help center questions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#473]
We need to add all of the help center questions via the admin interface.
Administration>Help Center> Choose subject, copy/paste question and answer

@phet-steele was going to lead this effort, but @brroberts1231 and @BryceAG can start on it for now.

Google doc of questions and answers:
https://docs.google.com/spreadsheets/d/1jirckePXaztwuackBhsqo2OfyKUCj81IloF9dhSpQOs/edit?usp=sharing

Let me know what questions you have!

**Comment by mattpen** [comment]
If you are adding html tags and you want to test out how it will look once it goes live, please let me know and I can publish the full version on phet-dev.

**Comment by phet-steele** [comment]
@oliver-phet this is very close to being wrapped up. I've added all the links, might do one last grammar check, and still want to see how things look on phet-dev first, but after that we should be good. You still need to add the new "Account" question you wanted to add.

**Comment by mattpen** [comment]
@oliver-phet @phet-steele The full helpcenter is up on phet-dev for testing.

**Comment by oliver-phet** [comment]
This can be closed as part of https://github.com/phetsims/website/issues/288
