### ISSUE TITLE
Dev testing of published versions of Resistance in a Wire and Ohm's Law

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#474]
Both Ohm's Law and Resistance in a Wire are some of the very first HTML5 sims we published, and did not get certain QA steps (like all the string tests)

Before redeploy it would be good to test the **published** versions on the website for some of the various QA issues we have been seeing in Gravity Force Lab. It will be much easier to fix any found issues instead of first doing an RC candidate and finding issues there.

Please test both these sims and report any issues in the respective repos, in particular look for issues with bounds and such. You will not be able to do the string tests since the string tests did not yet exist in the published versions. Please test on the following platforms

- [x] iPad 2 iOS 9+
- [x] Windows edge
- [x] Windows chrome
- [x] Mac Safari

@brroberts1231 @BryceAG @bryo5363 @orejolaphet @elisemorgan this is a good "back burner" task. Please note in the issue what platform you are testing.

**Comment by orejolaphet** [comment]
I will test Mac Safari

**Comment by bryo5363** [comment]
I'll get win/edge

**Comment by orejolaphet** [comment]
The query parameters ?stringTest=double, rtf, long, and none  do not change anything on the both published sims "Ohm's Law" and "Resistance in a Wire" on OS X 10.11 Safari 9.0

**Comment by orejolaphet** [comment]
To clarify, the strings in both sims do not change at all with addition of the query parameter.

**Comment by ariel-phet** [comment]
@orejolaphet yes, as I said in the initial comment in the issue:

>You will not be able to do the string tests since the string tests did not yet exist in the published versions.

**Comment by orejolaphet** [comment]
Ahh my mistake, I miss read the comment. Thanks for the clarification.

**Comment by elisemorgan** [comment]
IPad 2

**Comment by BryceAG** [comment]
Windows chrome

**Comment by ariel-phet** [comment]
@orejolaphet @elisemorgan @BryceAG @bryo5363 please check off your platform if testing is complete

**Comment by phet-steele** [comment]
@ariel-phet I finished this and checked it off. Closing.
