### ISSUE TITLE
Setup MP's new SSD

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#475]
- Win 7 64-bit
- IntelliJ
- GIT / Git Bash
- SVN (SlikSVN/1.9.2) https://sliksvn.com/download/
- Sublime 
- MS Office - Word/Excel
- Java 7 SDK
- Node / NPM
- Oracle Virtualbox

**Comment by oliver-phet** [comment]
@arnabp There's a samsung SSD on your desk - can you put it in any test computer and install the above onto it?

**Comment by oliver-phet** [comment]
@mattpen What did we decide on Adobe? Do you currently have a license you would want to transfer to the new machine?

**Comment by mattpen** [comment]
@oliver-phet I'll be able to figure the adobe part out. I'll remove it from the list.

**Comment by arnabp** [comment]
SSD is set up and ready to go!

**Comment by mattpen** [comment]
@arnabp @oliver-phet - I installed the new SSD tonight, but my PC says no boot device found.  Can I bring it in sometime tomorrow or next Monday?

**Comment by ariel-phet** [comment]
@mattpen - just a thought have you tried looking at the bios?

**Comment by mattpen** [comment]
Well.... It might help if I actually plug the drive into the port! That's embarrassing.  Please disregard my previous comment, it's working now.

**Comment by mattpen** [comment]
@oliver-phet @arnabp I've got everything setup except for Adobe.  My Adobe ID is registered under an email address for an education institution that I no longer have access to.  It would be really useful to have access to Flash and Illustrator for work on porting sims and the website.  Is it possible to obtain a license?

**Comment by oliver-phet** [comment]
Yep, I can look into getting the licenses.

**Comment by oliver-phet** [comment]
@mattpen I forgot - did we still need an Adobe license for you?

**Comment by mattpen** [comment]
@oliver-phet Yes, it would be nice to have for porting masses-and-springs.  

Also, do we have any external DVD drives that I could use?  I have a disc for Visio that I'd like to install but my DVD drive appears to no longer be working.

**Comment by oliver-phet** [comment]
I don’t have any external drives, but we have several testing computers with physical drives and we could make a flash drive with a disk image of whatever you need.

**Comment by oliver-phet** [comment]
This is done.
