### ISSUE TITLE
Test sims awaiting redeploy for string issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#479]
@elisemorgan @BryceAG @brroberts1231 @orejolaphet @bryo5363 we would like to test the following sims for string issues before we move onto the redepoly process. Many of these sims are old enough that the will not have the full set of ?stringTest available on the published version.

**How to test**
Please test using phettest.colorado.edu (you will need to be on campus or using VPN to access phettest)

**What to test**
Do not worry about performance yet, but please test the following
- stringTest=double
- stringTest=long
- stringTest=X (short strings)
- stringTest=rtl (right-to-left)
- showPointerAreas (touchArea=red, mouseArea=blue)
- Full screen test

**Sims to test**
Please test sims in the following order, and report any issues in the appropriate sim repo.

- [x] Ohm's Law
- [x] Resistance In A Wire
- [x] Build An Atom
- [x] Area Builder
- [x] Balancing Act
- [x] Wave On A String
- [x] Balloons and Static Electricity
- [x] Color Vision
- [x] Energy Skate Park: Basics
- [x] Forces and Motion: Basics
- [x] Fraction Matcher
- [x] John Travoltage
- [x] Least Squares Regression
- [x] Under Pressure

**Comment by elisemorgan** [comment]
@ariel-phet So far I am having trouble testing because the String Tests fail to load on the first few sims 
![screen shot 2016-01-15 at 12 58 14 pm](https://cloud.githubusercontent.com/assets/12610678/12363781/df9d841a-bb87-11e5-83fc-da841624fbfa.jpg)

Is this because they don't have string tests available? (I am inferring that phettest allows for string tests but I might be wrong there)

**Comment by jessegreenberg** [comment]
Looks like a query parameter issue.  Since phettest seems to use some query parameters automatically, try ```&stringTest``` instead of ```?stringTest```.

**Comment by elisemorgan** [comment]
That worked. Thanks @jessegreenberg !

**Comment by orejolaphet** [comment]
I noticed this on Safari Version 9.0 (11601.1.56) on every sim using the query ?stringTest=double 
double and overlaps all the text in the "About" section 
Area builder for example

<img width="1209" alt="screen shot 2016-01-21 at 10 11 43 am" src="https://cloud.githubusercontent.com/assets/5631059/12488232/db02c74a-c027-11e5-8314-e3db009a7c6a.png">

**Comment by jessegreenberg** [comment]
This distortion looks related to https://github.com/phetsims/scenery/issues/469, a Safari specific issue with the requireJS version of the sim.

**Comment by phet-steele** [comment]
@ariel-phet checklist complete. If @elisemorgan @BryceAG @brroberts1231 @orejolaphet @bryo5363 feel good about what they tested and have reported all issues they've found, then this task is complete.

**Comment by ariel-phet** [comment]
Task complete, closing
