### ISSUE TITLE
Test new login functionality on phet-dev

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#480]
@phet-steele we need you to test consequences of https://github.com/phetsims/website/issues/361

This will probably require making up (or using) several different email addresses, checking confirmation, and checking edge cases for logging in. Some cases you might want to try are to create an account but at first do not confirm the email. Then try logging in in various ways (ie):
- logging in with the sign in button
- clicking on an sim activity when not logged in
- clicking on a teacher primer video when not logged in
- perhaps going to rosetta when not logged in?
- trying to access activities from the teaching resources
- any other action that requires a login (I think leaving comments on sims might as well)

I would think in all these cases you would get a message about awaiting email confirmation. Then for all cases, confirm email and try logging in and out and such

From @mattpen 
>In order to implement the change requested in #361, I needed to change some code that may potentially have other side effects.  If a user logs in and has not confirmed their email, instead of getting a password error they now get redirected to the Awaiting Email Confirmation page.  We should test to make sure this happens when it is supposed to and does not happen if they have indeed confirmed their email.

This task would be good to test soon, as we have been getting a fair number of emails to phethelp regarding email confirmation.

**Comment by phet-steele** [comment]
@mattpen @ariel-phet ignore the reference above from the balancing act repo.

**Comment by phet-steele** [comment]
@ariel-phet @mattpen done what I can here, and it all behaves as expected for me.

**Comment by mattpen** [comment]
phetsims/website#361 has been deployed to figaro and appears to be working as planned.  Closing.
