### ISSUE TITLE
Create Team Member page for downloading all sims in a Zip file

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#482]
Discussed at the phet-io meeting on 1/21/2016.  It was requested to make a page where a PhET team member can download a zip file of all sims and all sims in a given technology.  It was agreed to make this available on the Admin page of the website.

**Comment by mattpen** [comment]
@kathy-phet Can you comment on the translation requirements?  Should the zip files contain all translated sims or do we need the ability to select a particular locale?

**Comment by ariel-phet** [comment]
@mattpen I suggest bringing up this question quickly during status meeting

**Comment by mattpen** [comment]
Script was implemented in February.
