### ISSUE TITLE
Testing embed using https on phet-dev

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#484]
@phet-steele this test is related to https://github.com/phetsims/website/issues/368

We would like to change the Embed code such that it serves the sims from "https" not "http" 

@mattpen has made this change on phet-dev, please test that the embed code works for several HTML5, Flash, and Java sims. Also double check a few sims that have both an HTML5 version and a legacy version (a few that have flash legacy a few that have Java legacy)

Not a super high priority, but should be a quick test and would be nice to have done in the near future.

**Comment by phet-steele** [comment]
@mattpen copy and pasting works fine, but how much do we support "customizing" the embedding ex. changing dimensions, adding borders, etc.? (if that's even a question that matters)

**Comment by mattpen** [comment]
@phet-steele, we provide help with embedding on an ad hoc basis. It really depends on the situation.   We mostly would support getting the iframe to work as is on another page, but not editing the internal content.  There is an infinite number of ways you can break things if you start editing the internal html or JavaScript.  The sim itself should be pretty rigorously tested.

**Comment by ariel-phet** [comment]
@phet-steele please comment if you checked the various scenarious I mentioned above...if so please feel free to close the issue.

**Comment by phet-steele** [comment]
@ariel-phet @mattpen looks good on my end :+1:
