### ISSUE TITLE
test neuron 1.0.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#485]
A new release candidate for the Neuron sim is ready for testing.  Changes that could have significant implications were made in the process of fixing issues found during the testing of the previous release candidate, so a thorough retest is warranted.

**Testing Matrix**
 https://docs.google.com/spreadsheets/d/13lSN1kUHkqDnar9EkoMerj-WCuVfxAZwnqgxjUGTSe0/edit#gid=1479477481

**Testing Link**
 http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html

**Note: Will Not Fix**
https://github.com/phetsims/neuron/issues/109 (only occurs with vigorous zoom in/out)

**Issues to Verify Fixes**
Please verify the following issues have been fixed (on the platform they were reported). Comment and close the issue if it can be checked off.
- [x] https://github.com/phetsims/neuron/issues/110
- [x] https://github.com/phetsims/neuron/issues/106
- [x] https://github.com/phetsims/neuron/issues/104
- [x] https://github.com/phetsims/neuron/issues/103
- [x] https://github.com/phetsims/neuron/issues/93

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @BryceAG @bryo5363 @orejolaphet @brroberts1231 please make this RC testing the current top testing priority

**Comment by elisemorgan** [comment]
@ariel-phet Testing is complete

**Comment by jbphet** [comment]
Closing, will follow up on the issues that were logged as a result.
