### ISSUE TITLE
Dev testing Trig Tour 1.0.0-dev.19

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#486]
This sim is almost ready for publication, so it would be good to do a round of dev testing.  Here is the link to the version to be tested:
http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.19/trig-tour_en.html

There have been many changes related to code review and performance, so as part if this dev test, it would be great if we could include the following:

  - [x] Test the sim for performance on iPad2
  - [x] Make sure that the simulation is the same in look, feel, and behavior as a previous version: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.17/trig-tour_en.html
    - NOTE: Only for the first two rotations, version 1.0.0-dev.17 is capped at 2 rotations.

**Comment by ariel-phet** [comment]
@phet-steele please make this your personal top testing priority (above Neuron)

**Comment by phet-steele** [comment]
@jessegreenberg performance on IOS 9.3 beta (Tycho), iOS 9.2 (Witten), and iOS 8.4 (Lave) was all great.

**Comment by phet-steele** [comment]
@jessegreenberg I'd say I've finished this. There was nothing too crazy :disappointed:

**Comment by ariel-phet** [comment]
@jessegreenberg feel free to close this issue unless you want to keep it open for reference.

**Comment by jessegreenberg** [comment]
Closing, this task was referenced as issues were created :thumbsup:.  Thank you for testing @phet-steele!
