### ISSUE TITLE
Text edits to journal graphic abstracts - by Jan. 28th

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#487]
@daveunderwood designed some beautiful journal graphic abstracts last October (last email I believe was Oct. 8th). I now need final versions to submit by Thursday - which requires some text tweaks to the originals. 

1) The Red Accessibility Sign graphic should read: 

The Cutting Edge: Educational Innovation, 
Disability Law, and Civil Rights
Emily B. Moore, Department of Physics, University of Colorado Boulder
Paul D. Grossman, US Dept. of Education, Office of Civil Rights (Retired)

2) The Girl with Computer abstract should read: 

ConfChem Conference on Interactive Visualizations for
Chemistry Teaching and Learning: An Introduction
Robert Belford, Department of Chemistry, University of Arkansas at Little Rock 
Emily B. Moore, Department of Physics, University of Colorado Boulder

--- title could be shortened to ---
ConfChem Conference on Interactive Visualizations
for Chemistry Teaching and Learning

3) Blue Icon abstract should read:

Accessibility for PhET Interactive Simulations: 
Progress, Challenges, and Potential
Emily B. Moore, Department of Physics, University of Colorado Boulder

(jpg files attached for reminder - and because they're so pretty)

![cutting_edge](https://cloud.githubusercontent.com/assets/5109055/12565763/58273640-c373-11e5-87c5-4970491e1fcc.jpg)

![designing_accessible](https://cloud.githubusercontent.com/assets/5109055/12565768/5d530892-c373-11e5-9c34-4fb3ec8d6e09.jpg)

![interactive_chem](https://cloud.githubusercontent.com/assets/5109055/12565771/61bb2b58-c373-11e5-8fe4-d6dfe266ea4c.jpg)

**Comment by daveunderwood** [comment]
Here ya' go, Emily. 

![disability_law](https://cloud.githubusercontent.com/assets/13662881/12583615/e9829a20-c400-11e5-9a2a-2c4c8e67d97c.jpg)
![conf_chem](https://cloud.githubusercontent.com/assets/13662881/12583616/e9852fec-c400-11e5-8cc9-033c2c60532f.jpg)
![interactive_chem](https://cloud.githubusercontent.com/assets/13662881/12583617/e989c084-c400-11e5-961c-f2945d807a12.jpg)
Thanks, D

**Comment by emily-phet** [comment]
@daveunderwood - perfect! Thanks!
