### ISSUE TITLE
Dev Test Isotopes and Atomic Mass V1.0.0-dev.5

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#488]
This version is ready for dev testing here is the link : http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.5/isotopes-and-atomic-mass_en.html

At this point we are looking for thorough functionality testing (there are a few known performance issues, mainly a lag when generating "nature's mix")

Please test on the following platforms:

- [x] iPad2 iOS 9+
- [x] Windows Edge
- [x] Windows Chrome
- [x] Mac Safari (latest OS)

**Comment by ariel-phet** [comment]
@phet-steele assigning to you but feel free to enlist help of other QA members

**Comment by phet-steele** [comment]
@aadish I'm looking forward to the next dev version :smile:, this one is complete.

**Comment by aadish** [comment]
Thanks for testing this finding the bugs. The bugs have been recorded and fixed. This task is complete.  Closing it.
