### ISSUE TITLE
Single Slide for Funder Meeting - Due Monday Feb. 1st

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#489]
I have been asked to present a story about an individual the PhET project has impacted. I am allowed one slide that includes an image of that person. Since this is a funder meeting, and this will be the only presentation by the project at this conference, I figure it should look snazzy. 

I have decided to tell a story about a student who has been helping with our accessibility efforts, who is blind. She sent me a very nice headshot of herself. It would be ideal if we could figure out a way to have on the one slide I'm allowed: the student's headshot and name, an image of students working in the classroom on a computer, and the PhET logo (even better would be to have some sort of logo that indicates PhET and accessibility, but probably not enough time for that). 

The story I will tell about this picture is about the student's experience of not being able to join in with her peer's when using computer-based learning tools, and how she often felt left out in K-12 because basic learning games were not accessible - e.g., Oregon Trail. Since working with us, she has enjoyed being able to play with the simulations herself, and explore and learn independently, and looks forward to seeing accessible sims in her classrooms so she can use them with her peers. This focus on shared use in the classroom is why I would like to have some sort of reference to that setting in the slide.

Once I know who will be working on this I'll send the headshot by email - I would prefer not to have the student's image on Github. I've also emailed to request information about the aspect ratio of the slides to be used (I have to send this to the organizers and they put together the slide deck). I expect it will be 4:3, but I should know tomorrow if it may be 16:9.

**Comment by ariel-phet** [comment]
Definitely a @daveunderwood project, he is working on Friday so this should be doable.

**Comment by daveunderwood** [comment]
Yup, I've got this one. Send me the particulars as soon as you have them, Emily. 
I'm not planning on working until Friday, so it'll be a tight turnaround. I'd like to be ruminating on the design before then, though.

D

**Comment by daveunderwood** [comment]
Hey Emily,

If you get a chance, please send along the pieces for the slide. I know it's due tomorrow, but I'm in meetings, etc., for much of Friday. It would be nice getting a head start. Also, do you have final text available from "volunteers_D.pdf?" I have several iterations, but I want to be certain it's right. It would be easiest to start fresh. (Pasting that text into "volunteers_2.copy.pdf." 

Thanks!
Dave

**Comment by ariel-phet** [comment]
I believe this issue is complete. Closing
