### ISSUE TITLE
Molecule Shapes 1.1.2-rc.2 spot checks

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#490]
See http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.2-rc.2/molecule-shapes_en.html

Modified maximum widths of components (panels and real/model radio buttons) and fixed layout of the electron/molecule shape geometry panel so it won't change size with longer strings.

Should be no other changes in the sim or common code that would need testing.

**Dev**
- [ ] Address RC issues

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@phet-steele please do a few spot checks on this sim and with the longer string tests (I think a quick test on ipad, safari, and chrome should be sufficient).

**Comment by phet-steele** [comment]
@jonathanolson you said to not test this, right?

**Comment by jonathanolson** [comment]
Correct, will create new spot testing issue.
