### ISSUE TITLE
Molecule Shapes (normal/basics) spot testing for RCs

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#491]
Changed geometry name panel layout and constraints for large strings (test double/long and a few general checks).

Molecule Shapes: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.2-rc.4/molecule-shapes_en.html
Molecule Shapes: Basics: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.0-rc.4/molecule-shapes-basics_en.html

**Comment by phet-steele** [comment]
@jonathanolson :+1:

**Comment by jonathanolson** [comment]
Assigned to me, QA label removed? @ariel-phet, does this mean since the one issue created is will-not-fix, I should publish both Molecule Shapes and Molecule Shapes: Basics?

**Comment by ariel-phet** [comment]
@jonathanolson yes, you can go ahead and redeploy and close this issue.

**Comment by jonathanolson** [comment]
Both deployed:
Molecule Shapes 1.1.2
Molecule Shapes: Basics 1.1.0

Closing.
