### ISSUE TITLE
Test Rutherford Scattering to prepare for port

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#493]
@phet-steele (feel free to delegate) 

Please test the Java version of Rutherford Scattering and report any found issue in the rutherford scattering repo and mark them with a "java bug" label

Testing on one platform (windows or mac) is fine, mainly looking for model bugs and such.

http://phet.colorado.edu/en/simulation/rutherford-scattering

**Comment by phet-steele** [comment]
@ariel-phet I tested on Win 8.1 and OSX 10.11.2. No issues found :+1:

**Comment by ariel-phet** [comment]
Excellent, thanks @phet-steele!
