### ISSUE TITLE
Phetbackup is moving!

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#494]
Phetbackup has been moved (and will probably need to be moved again in the near future), and we need to get it set up.

Assigning to @ariel-phet to take care of.

**Comment by ariel-phet** [comment]
Will deal with when offices eventually move, unless some pressing need occurs to access phetbackup.

Likely we will also migrate all of phet-backup onto our "phet-storage.colorado.edu" account once that is all sorted out in #505

**Comment by ariel-phet** [comment]
unassigning for the moment

**Comment by emily-phet** [comment]
@ariel-phet - I need access to some files on phetbackup - ideally by early next week. Is there a way this can be set back up. Alternately, I (after seeing a list of folders) can let you know what I need - it's specific files in a particularly folder - and these can be transferred to the Google drive storage.

**Comment by ariel-phet** [comment]
@emily-phet I believe you can connect your computer directly to it

I will look into this next week, we should transfer all these files onto our private google drive anyhow

(and @emily-phet please always assign me issues if you want action, they will get lost if you merely mention me)

self-assigning

**Comment by emily-phet** [comment]
@ariel-phet - whoops, sorry about not assigning you.

I tried to connect but was unsuccessful, so I guessed phetbackup was still not set up. I could connect with phetbackup2, but not phetbackup.

**Comment by ariel-phet** [comment]
@emily-phet it is not connected to the network currently, but I believe you can actually hook an ethernet cable from your computer to the actual physical box

**Comment by ariel-phet** [comment]
JR from JILA is coming today to get things functional...I tried to get things running with a direct connection, and I was able to connect, but I could not see the shared folders. Seems like I need admin privileges. Hopefully things should be sorted out later this afternoon.

**Comment by ariel-phet** [comment]
JR helped @phet-steele connect and see the files. He is going to get info from @oliver-phet on where to transfer everything (likely phetstorage gmail account).

@emily-phet you might want to coordinate with @phet-steele on Thursday to get the files you need, he can easily transfer those first.

**Comment by ariel-phet** [comment]
and @phet-steele feel free to delegate

**Comment by emily-phet** [comment]
@phet-steele - just sent you an email describing the location of the folder that I need to be copied first.
@ariel-phet and @oliver-phet - we decided at status meeting awhile back that it would be ideal to have a separate Drive account for research files. Could this be put in place?

**Comment by ariel-phet** [comment]
@emily-phet I believe it is already in place. We have "phetstorage" for research files and "phetdocs" for all design docs and such. @oliver-phet can correct me if I am wrong

**Comment by oliver-phet** [comment]
We actually have a phet-docs, phet-storage, and phet-research. It sounds like these are research files so @phet-steele please put them in phet-research.

**Comment by phet-steele** [comment]
Currently, half of the files should be in phet-storage (phet-research is not ready). The other half had issues when transferring from phetbackup to an external hard drive. Quite a few gigabytes of files had an error and were unable to be transferred in bulk. A diff was ran to see which files still need to be transferred, and the files will have to be cherry-picked.

The error, by the way, was that file names were too long and exceeding the destination path character limit. The error did not occur during the first half of the files, so hopefully no files are missing from Drive.

**Comment by ariel-phet** [comment]
@phet-steele - any updates on this issue?

**Comment by phet-steele** [comment]
@ariel-phet nope!

**Comment by ariel-phet** [comment]
@phet-steele - we should continue to chip away, I do not want to see this linger too long. Feel free to enlist other QA members to help out

**Comment by ariel-phet** [comment]
@oliver-phet this issue seems to be stalled. Now that we have made the google docs migration happen and such perhaps you can finish this off, as QA work continues to take priority. Perhaps @arnabp can help here (higher priority than captioning videos)

**Comment by oliver-phet** [comment]
I'll need to check with @phet-steele about this. I remember thinking that this would be very time intensive because files would need to be manually located and migrated. @phet-steele Do we have a list of files yet to be copied?

**Comment by phet-steele** [comment]
> Do we have a list of files yet to be copied?

Yes, in a word document on Schrodinger.

**Comment by ariel-phet** [comment]
@oliver-phet @phet-steele considering the glitches that happened in the initial transfer, it might be worth looking trying to do it from scratch so things do not need to be manual?

**Comment by oliver-phet** [comment]
Yep, I have a few ideas to test to hopefully avoid manually finding and copying 70 pages of files!
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Nov 29, 2016, at 4:44 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@oliver-phet<https://github.com/oliver-phet> @phet-steele<https://github.com/phet-steele> considering the glitches that happened in the initial transfer, it might be worth looking trying to do it from scratch so things do not need to be manual?

**Comment by oliver-phet** [comment]
This has been completed. @emily-phet all files that were previously on PhET Backup can now be accessed via phet-storage. Closing!
