### ISSUE TITLE
RC test Trig Tour 1.0.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#495]
Trig Tour is ready for release candidate testing!

**Release Candidate:** http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-rc.1/trig-tour_en.html

**iFrame:** http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-rc.1/trig-tour_en-iframe.html

**Testing Matrix:** https://docs.google.com/spreadsheets/d/114EUr7wY3aZo-YFfjdzXsgvP37PQHitBmWUpnYKEsag/edit?ts=56abcb7f#gid=0

**_Additional items for the deploy:_**

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [ ] Address RC issues

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Perform RC testing
 - [x] Reference issues to RC test task

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@bryo5363 @phet-steele @elisemorgan @brroberts1231 @BryceAG @orejolaphet please make this the top testing priority

**Comment by phet-steele** [comment]
@jessegreenberg matrix complete

**Comment by jessegreenberg** [comment]
Thanks! Since phetsims/trig-tour#76 is assigned to me, reassigning to @ariel-phet to handle Design/Admin section of checklist.

**Comment by ariel-phet** [comment]
@jessegreenberg will phetsims/trig-tour#76 require another RC?

**Comment by jessegreenberg** [comment]
Yes, the fix to https://github.com/phetsims/trig-tour/issues/76 involved a change in Scenery.  Since 1.0 will require a new version of scenery, another RC will be necessary.

**Comment by ariel-phet** [comment]
another RC necessary. Closing
