### ISSUE TITLE
PhET brand standards documentation

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#496]
@kathy-phet requested that I work with @daveunderwood to create a brand standards document

I have asked @amyh-phet to create a google doc skeleton based on the CU brand standards document.

This doc should have two main divisions between PhET and PhET-iO and probably some mention of where to use the registered logos for each.

Assigning to @amyh-phet for the moment. @amyh-phet - when you have made the document skeleton please paste the link in this issue and assign back to me. Not a big rush, but perhaps have the skeleton created by sometime next week?

**Comment by amyh-phet** [comment]
Will do.

**Comment by ariel-phet** [comment]
And just to document what was said by @kathy-phet 

> As part of our partnerships, we should develop a "brand standard document" that provides guidance to companies about using our logos. CU has a standards document. We should have several logos available for use at different pixel sizes - since we have been varying the size of the R and TM.

> We should include among these the one that has the interlocking CU Boulder, that we have been providing to companies. But I imagine they will have some places where that larger logo doesn't work. We could also supply the small airplane as an icon that they may use to identify in a search or something. I think we did that for Nelson.

> would be good to have it available soonish. Maybe 1 month? Perhaps its a topic for web design group to get some broader input too?

**Comment by amyh-phet** [comment]
Initial document created in google docs.

https://docs.google.com/document/d/1Rn8-M5i61M9aR2NLEZ9DFevnR3i3b7_6jSoo3U1ZUxs/edit?usp=sharing

Let me know of other work that needs to be done in the document.

**Comment by ariel-phet** [comment]
This is fine for now. Closing
