### ISSUE TITLE
Make a spreadsheet of sims and 1.0.0 date

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#497]
Currently, the database has some inconsistent information about when our HTML5 sims were published. This task shouldn't take long but is very important. 
Go to http://www.colorado.edu/physics/phet/dev/html/ and for every published HTML5 sim, find the date of the 1.0.0/ version of the sim. 

For example, if you click on acid-base-solutions, the date for 1.0.0 is 18-Apr-2014. 
<img width="761" alt="screen shot 2016-02-01 at 3 31 12 pm" src="https://cloud.githubusercontent.com/assets/7852916/12733576/d3a70766-c8f8-11e5-90d4-eba20ad8dea2.png">

Please make a google spreadsheet with a column for the sim name (use the naming convention acid-base-solutions) and a column for the date, and share with the phet google group.

**Comment by phet-steele** [comment]
@amanda-phet on it!

**Comment by phet-steele** [comment]
@amanda-phet Voila:

https://docs.google.com/spreadsheets/d/1WfYjEWBv5bdoelxZrCnQDd5OtSd7RrbXplWPWMV-pq8/edit?usp=sharing

**Comment by amanda-phet** [comment]
Awesome! Thank you!!
