### ISSUE TITLE
Dev test Pendulum Lab 1.0.0-dev.8

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#498]
**Testing Link**
http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.htm

**Platforms**
- [x] iPad2 iOS 9+
- [x] Windows Edge
- [x] Windows Chrome
- [x] Mac Safari

Let others know in this issue what platform you have claimed

**Additional Tests**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan please make this your current top testing priority

**Comment by ariel-phet** [comment]
Bueller....bueller?

**Comment by ariel-phet** [comment]
Changed to high priority since Trig tour is current top priority test

**Comment by BryceAG** [comment]
Windows Chrome

**Comment by brroberts1231** [comment]
Safari

**Comment by bryo5363** [comment]
I'll get Edge

**Comment by ariel-phet** [comment]
back to top testing priority for the moment

**Comment by elisemorgan** [comment]
iPad 2

**Comment by orejolaphet** [comment]
Mac Safari

**Comment by jonathanolson** [comment]
Sorry, I was closing some issues as I fixed them. All fixes I've applied (closed issues for this sim today) will apply to all platforms.

**Comment by ariel-phet** [comment]
Moving back to high priority as testing Neuron will be top priority

**Comment by ariel-phet** [comment]
dev complete, closing
