### ISSUE TITLE
RC Test: trig-tour 1.0.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#499]
Trig Tour 1.0.0-rc.2 is ready for an RC test.  this RC includes changes to the pointer areas and the way Scenery draws line segments.

No major changes, but we should spot check to make sure that Scenery related changes are OK across platforms.

**Link to RC:** http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-rc.2/trig-tour_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-rc.2/trig-tour_en-iframe.html

**Link to test matrix:** https://docs.google.com/spreadsheets/d/1v_swo8iPQTR5z9evu7zq7Fjo1qt2RNtlBp5M3k582lA/edit#gid=109371867

**Checklist for the deploy:**

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [x] Address RC issues

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Perform RC testing
 - [x] Reference issues to RC test task

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele  please make this your current top testing priority (now above dev testing pendulum lab). Hopefully we can publish this one soon!

**Comment by jessegreenberg** [comment]
Going through hoops to change ownership of test matrix to phethelp.  Test matrix above may be down momentarily, I will post another link when it is back up.

**Comment by jessegreenberg** [comment]
New document made, and phethelp is new owner. Link to new test matrix updated in initial comment.

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet matrix complete! :tada:

**Comment by ariel-phet** [comment]
Deployed! closing
