### ISSUE TITLE
Gooru Collaboration assitance for Trish

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#5]
Hey @phet-steele, please track your progress in this issue

Ariel has approved you helping me get the information Gooru needs into a spreadsheet. (they don’t crawl our data). Getting this done quickly and correctly is imperative. I shared the collaboration doc with you.

https://docs.google.com/document/d/1HFB4UQs-Knczdpxlpe5y1AY5H8uHlhdzbs71BntxDpw/edit

 

Also I shared the spreadsheet.

https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774

 

Two things that you could do right away are items 3d and 3e. I still need to get the Keywords process verified with Kathy; that’s another thing I could use your help with. Do you have Admin rights so you can see the meta data pages?

**Comment by phet-steele** [comment]
@ariel-phet @patricialoeblein  what's the latest from Gooru? It's been awhile since I've heard anything new aside from we were moving to each HTML sim having its own page.

**Comment by patricialoeblein** [comment]
We have not done any work for gooru for a while. We have been updating the shared spreadsheet whenever a new sim is published. Our plan was to contact them when the new sim pages go live because the urls that they use will be broken.
Trish

**Comment by phet-steele** [comment]
@patricialoeblein did u make Gooru aware of our new sim pages yet? I may recollect a recent-ish email to someone at Gooru about this.

**Comment by phet-steele** [comment]
@ariel-phet :cry:

**Comment by ariel-phet** [comment]
well @phet-steele it seems like this issue is quite old (and Trish is now retired...so)
