### ISSUE TITLE
Test uploading translated teacher's guides

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#500]
@ariel-phet - It would probably be a good idea to test the new locale-specific teacher's guides in phetsims/website#324 before deploying to figaro.

Here's an list (not necessarily complete) of things to test:
1. Upload a new English guide.
2. Upload a new translated guide.
3. Change the locale of a translated guide.
4. Remove a translated and an English guide.
5. Add a translated guide to a locale without an English guide.

**Comment by ariel-phet** [comment]
@phet-steele this would be good to tackle at some point, but currently low priority

**Comment by ariel-phet** [comment]
@phet-steele feel free to delegate this task, it is rising in priority

**Comment by phet-steele** [comment]
@mattpen I couldn't find anything wrong with this after a solid 1.5 hrs of testing, nice job.

**Comment by mattpen** [comment]
Thanks @phet-steele
