### ISSUE TITLE
New robot "pusher" for forces and motion basics

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#501]
The current pusher is very pixelated, we want to redraw, need the following poses:

- standing (front view)
- fallen down
- a number of incremental "pushing" harder stances (at least 15 increments, but could up to 30)

@mariahmaephet this would be great to have soon

**Comment by mariahmaephet** [comment]
<img width="636" alt="screen shot 2016-02-17 at 6 49 16 pm" src="https://cloud.githubusercontent.com/assets/11527557/13131216/49a45bca-d5a7-11e5-85bf-1d37ea035716.png">

**Comment by ariel-phet** [comment]
Double :+1: :+1: from me @mariahmaephet!

**Comment by mariahmaephet** [comment]
@ariel-phet How does this look? These are just the 'landmark' poses and then I'll go in and add a bunch of incremental changes (and fix the glares). 

<img width="715" alt="screen shot 2016-02-18 at 2 39 37 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159187/c26c4850-d64d-11e5-9a95-5214422daf13.png">
<img width="733" alt="screen shot 2016-02-18 at 2 40 54 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159188/c26f2f02-d64d-11e5-95e3-8097362d2f6a.png">
<img width="689" alt="screen shot 2016-02-18 at 2 40 59 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159189/c2723fc6-d64d-11e5-90ad-2b815eb3c9cf.png">
<img width="790" alt="screen shot 2016-02-18 at 2 41 04 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159190/c2767550-d64d-11e5-8212-d9da78ae02a7.png">
<img width="778" alt="screen shot 2016-02-18 at 2 41 09 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159191/c27aa346-d64d-11e5-963e-c32fb061cdcd.png">
<img width="889" alt="screen shot 2016-02-18 at 2 41 31 pm" src="https://cloud.githubusercontent.com/assets/11527557/13159192/c27cbaaa-d64d-11e5-8cc9-de3a7dc32ec9.png">

**Comment by ariel-phet** [comment]
@mariahmaephet I love going into the splits! I think that is great for a "fall off" pose, however, I think there needs to be a tweak for the "leaning" poses...

Notice in the frame three above the front foot is to the left of the knee, I think that is important. If you are leaning in an pushing really hard, you will go into a deep and deeper lunge, so the foot should stay behind the knee. Kind of like this really crappy mod of your pic:

<img width="790" alt="c2767550-d64d-11e5-8212-d9da78ae02a7" src="https://cloud.githubusercontent.com/assets/4051174/13164238/ea7e19ea-d670-11e5-82e5-f3e0410e08a9.png">

Other than that modification, looking really good!

**Comment by mariahmaephet** [comment]
@ariel-phet right! I was basing it more off of smooth motion from first to final pose, but I can change the final pose to still having the leg vertical below the knee. Are these better?

<img width="947" alt="screen shot 2016-02-19 at 11 25 35 am" src="https://cloud.githubusercontent.com/assets/11527557/13184906/c75cf2d4-d6fb-11e5-9bfb-5df6f1c57551.png">
<img width="949" alt="screen shot 2016-02-19 at 11 48 15 am" src="https://cloud.githubusercontent.com/assets/11527557/13185499/b4e42cdc-d6fe-11e5-8a1e-5f03412a98c9.png">
<img width="947" alt="screen shot 2016-02-19 at 11 48 22 am" src="https://cloud.githubusercontent.com/assets/11527557/13185500/b4e7cd1a-d6fe-11e5-99b3-df43384fced8.png">

**Comment by ariel-phet** [comment]
@mariahmaephet yes, looks great!

**Comment by mariahmaephet** [comment]
@ariel-phet so this is 32 poses. Do you want to have the developer people use this and see if we need more? 

<img width="999" alt="screen shot 2016-02-23 at 11 36 18 am" src="https://cloud.githubusercontent.com/assets/11527557/13262372/b99423e2-da21-11e5-96ba-75cae93ae19d.png">

**Comment by ariel-phet** [comment]
@mariahmaephet I think that is a good idea, and probably will be enough. Can you upload the .ai file of just the pusher?

**Comment by mariahmaephet** [comment]
@ariel-phet it's uploaded

**Comment by ariel-phet** [comment]
thanks @mariahmaephet! unassigning for now, but leaving open in case any tweaks are needed.

**Comment by ariel-phet** [comment]
Working really well! If you want to see these in action @mariahmaephet check out http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.5-dev.15/forces-and-motion-basics_en.html

Closing as this work is complete.
