### ISSUE TITLE
New cyclist girl for Energy Forms and Changes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#502]
will need the bike artwork for Mariah so she can work on this project.

**Comment by ariel-phet** [comment]
All current images can be found here:
https://github.com/phetsims/energy-forms-and-changes/tree/master/images

**Comment by ariel-phet** [comment]
Here is the current bike .png for @mariahmaephet reference

![bicycle_frame_3](https://cloud.githubusercontent.com/assets/4051174/12895652/b7aba942-ce5a-11e5-83ea-2034a020b97c.png)

will try to locate .ai files

**Comment by mariahmaephet** [comment]
@ariel-phet here's an update of her biking. I just need to find a way to animate it myself to make sure it looks right in motion

<img width="476" alt="screen shot 2016-07-16 at 1 02 22 pm" src="https://cloud.githubusercontent.com/assets/11527557/16896575/903c6d42-4b55-11e6-859c-2f9fccd24e75.png">

**Comment by KateLRN** [comment]
@mariahmaephet I can ask our animator for advice if that would be helpful. 

Looks great, by the way!

**Comment by ariel-phet** [comment]
@mariahmaephet can you upload this to your drive? We can have the developer put the images into the sim, and animate from there

**Comment by ariel-phet** [comment]
Oh and please assign back to me once uploaded.

**Comment by mariahmaephet** [comment]
@ariel-phet Here's a gif of the movement. Obviously the layering will be different so she straddles the bike in the game and the pedals will be added--this was just faster :) 
![phetbikingfix](https://cloud.githubusercontent.com/assets/11527557/18035274/1834c414-6d21-11e6-84c0-8a39c947c20b.gif)

**Comment by ariel-phet** [comment]
@mariahmaephet looks great, definitely upload to drive!

**Comment by andrewadare** [comment]
Nice! I assume she won't be as happy looking when she bonks...

**Comment by ariel-phet** [comment]
@andrewadare correct

**Comment by ariel-phet** [comment]
@mariahmaephet we also need the "feed me" pose where PhET girl is slumped over the handle bars a bit and looking a bit tired (but math sim and projectile motion stuff are higher priority)

**Comment by mariahmaephet** [comment]
@ariel-PhET Right! I'll get on that. I might not be able to upload the .ai files until Friday when I get internet at my place but I'll take a picture of the slump pose to get confirmation on that today or tomorrow

**Comment by ariel-phet** [comment]
Sounds good, thanks @mariahmaephet

**Comment by arouinfar** [comment]
I found the assets on [Drive](https://drive.google.com/file/d/1_QBh_076HSgT4P2ciYVsa0bdrxJsIY08/view), thanks to @megan-phet! 

The asset file will need to be reformatted before it's checked into the `energy-forms-and-changes` repo, which I can take care of.

However, we're still missing artwork for tired PhET girl to replace the [original](https://github.com/phetsims/energy-forms-and-changes/blob/master/images/bicycle_rider_tired.png):
![image](https://user-images.githubusercontent.com/8419308/45236274-9f2b7a80-b298-11e8-954d-8c010b074cb6.png)

@megan-phet can you work on this? Please let me know if you have any questions!

**Comment by megan-phet** [comment]
Yes, I can do that.

**Comment by arouinfar** [comment]
@megan-phet created this awesome series of fatiguing torsos.

![image](https://user-images.githubusercontent.com/8419308/45312238-c4162c80-b4e8-11e8-9d08-ab226054a15d.png)

All that's left to do is to reformat/export the assets for implementation, which I'll take care of this afternoon.

**Comment by ariel-phet** [comment]
@arouinfar those are pretty awesome, but I think we want her to look less "distressed" and more tired. That last pose definitely gets the message across, but she looks like she is in bad pain discomfort. I think we want to go for more "happily exhausted" if possible.

**Comment by megan-phet** [comment]
[Updated](https://github.com/phetsims/tasks/files/2384277/phetgirlbiking.pdf)

**Comment by arouinfar** [comment]
@megan-phet made these tweaks to the tired pose. @ariel-phet if these look good to you, I'll work on exporting the assets for implementation.

![tiredpose](https://user-images.githubusercontent.com/8419308/45566184-276acc00-b813-11e8-827e-e87173d387fc.png)

**Comment by arouinfar** [comment]
The artwork was missing the bike pedals, which @megan-phet added last week. She also made some tweaks to the bike.

Currently, the leg layers are mis-ordered, leading to pairings like this:
![image](https://user-images.githubusercontent.com/8419308/47041308-af5f3100-d145-11e8-97f0-81dcd72792a6.png)

@megan-phet the file you shared with me on Friday still has the funny layering. Did you accidentally attach the wrong file, by chance?

**Comment by arouinfar** [comment]
@megan-phet finalized the cyclist assets, and everything is looking great! I've formatted/exported the assets for implementation, so we can go ahead and close this issue.

[phetgirlbiking+tiredfaces.pdf](https://github.com/phetsims/tasks/files/2497841/phetgirlbiking%2Btiredfaces.pdf)

Thanks @megan-phet!!
