### ISSUE TITLE
PhET icon work for iPad app and perhaps favicon

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#503]
It would be good to work on a new PhET icon to conisder for our "favicon" (the little icon in browser bars/tabs) as well as an for the PhET iPad app. I think something in the style of the sticker @mariahmaephet made could work. I like the way the white outline brings some "pop" and energy to the design

<img width="655" alt="icon" src="https://cloud.githubusercontent.com/assets/4051174/12925070/caa44f58-cf19-11e5-8601-e162c52c8017.png">

I am not sure if it would be too much but it seems like some "wisps" that suggest motion might work

**Comment by ariel-phet** [comment]
Note: icon probably needs to work at least 32x32 pixels

Note 2: above is just to show the general style

**Comment by ariel-phet** [comment]
reassigning to @daveunderwood

**Comment by daveunderwood** [comment]
29 X 29 pixels is a tough size to do anything interesting with. I love the white outline in the example above, but in the size required, I can't make it work. Here's the closest thing I have to an icon that imparts a little motion. See what you think.
![icon_1](https://cloud.githubusercontent.com/assets/13662881/13434380/d5f0af76-df92-11e5-9376-93d2f8254fb2.jpg)

**Comment by ariel-phet** [comment]
Hey @daveunderwood I think we actually have a bit more leeway. Looking at the guidelines, that very small icon could be what you have, but we could have a more detailed one for the iPad homescreen. Looks like 76x76 is by far the more important size to work with and get looking nice (the 29x29 only appears when you go into settings). So lets try doing something we love at 76x76 and can be simplified at 29x29

![ipad](https://cloud.githubusercontent.com/assets/4051174/13451682/7508489c-dffe-11e5-813c-768166f3b858.PNG)

**Comment by ariel-phet** [comment]
Closing this issue for the moment, we are going to go with the PhET logo for the first iteration of the app
