### ISSUE TITLE
Sorting out our Google doc issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#505]
@amanda-phet mentioned that sorting out how we are using google docs as an organization needs to be sorted out sooner than later.

Creating this issue to track thoughts and progress. Will plan to work with @oliver-phet to come up with a clear plan.

It seems one of the first steps is going to be to migrate all files to our colorado.edu gmail accounts.

**Comment by ariel-phet** [comment]
Link to info on making an organization for google docs:

https://apps.google.com/learning-center/products/drive/set-up-file-share/

Chrome app for migrating files

https://chrome.google.com/webstore/detail/drive-migrator/nakklajdcijlkfagghhcdofbgbhddoed?hl=en

**Comment by ariel-phet** [comment]
from @oliver-phet 

> It looks like the best solution, given the existing CU organization structure, is for our team to start using CU-identikey google accounts for creating/managing Google Drive. We get free unlimited storage and a 5-day backup window if we need to get anything restored. 
> 
> The other benefit is that we can all create docs and maintain ourselves as owners. If anyone were to leave and is de-provisioned, we have 5 days to restore their user account and transfer the files to a new owner.

**Comment by ariel-phet** [comment]
@oliver-phet definitely agrees the right solution is first to migrate all phet relevant to colorado.edu gmail accounts. This migration has major advantages, but might have some hiccups in the migration phase.

- how to move docs over if you have an existing file/folder structure
- making sure not funkiness occurs with shared folders

We will plan to test a few migration strategies.

**Comment by ariel-phet** [comment]
What about new google-group in colorado domain

**Comment by ariel-phet** [comment]
@oliver-phet suggests using same google group but deleting "personal" addresses and putting in only colorado.edu addresses

**Comment by ariel-phet** [comment]
Drive migrator appears to be working, once you follow the steps carefully. @oliver-phet is going to try a more robust test.

Current plan is probably to have people make sure they have moved all google doc ownership to phethelp@gmail, and then to an enormous batch migration.

**Comment by oliver-phet** [comment]
Sent request for two new accounts to be provisioned to OIT:
‘phet-storage@colorado.edu'
‘phet-docs@colorado.edu’

**Comment by oliver-phet** [comment]
These accounts are now active and receiving email.
 
Kathy can claim these secondary accounts by logging into CUIdM https://cuidm.colorado.edu
with identikey and then clicking on the "Activate My Secondary Accounts" link.
http://www.colorado.edu/oit/tutorial/identikey-secondary-account-activation
 
Instructions for configuring these accounts may be found at:
http://www.colorado.edu/oit/services/messaging-collaboration/google-apps

**Comment by oliver-phet** [comment]
Accounts have been fully activated.

**Comment by oliver-phet** [comment]
@arnabp and I are investigating. Here are some notes:

1. When using Drive migrator, all folder structure and file types are preserved
2. All previous sharing setting are removed (no one is shared on any migrated docs except the new owner 'phet-docs@colorado.edu')
3. Hyperlinks within google docs are preserved, but reference to the original copy - this means people will need to manually update links to the new version of the file
4. It may be possible to run a script on the original version of the files to add something like "DEPRECATED:" to the beginning of each file name.
5. We'll likely want to move all the folders/docs into one "master" folder, then migrate that master folder.

**Comment by oliver-phet** [comment]
@ariel-phet: @arnabp and I have tested a few different scenarios using the drive migrator and we think we are ready to kick off this process soon. However, a few questions that need to be sorted out:

> After the migration has occurred, new folders created within the phet-docs structure will be owned by the creator. When they are shared with phet-docs, the shared folder will not be organized within the folder structure of phet-docs (it goes to the root)

I'm not sure how we would like to handle this. 

So, after we do the migration and create a nice, clean folder structure within phet-docs, if anyone would like to create new folders and files (new sims!), they will create folders/files in their personal @colorado drive. They then share/make owner that new folder to phet-docs. The issue is that the new folder will be placed in the root of phet-docs (not organized in the structure above). This will require manual organization if we would like to keep the drive of phet-docs "clean".

**Comment by oliver-phet** [comment]
We are thinking about public sim assets (.ai files, teacher tips) be stored on github.

**Comment by oliver-phet** [comment]
Will discuss this during 2/25 status meeting.

**Comment by oliver-phet** [comment]
Also will need to migrate the google calendars to @colorado

**Comment by amyh-phet** [comment]
We should also keep @phetsims/schasteen in the loop on this.

**Comment by oliver-phet** [comment]
Setup new organization structure:

1. Someone no longer works with PhET
2. Someone adds new ai assets
3. Someone creates new subfolder

**Comment by oliver-phet** [comment]
@arnabp has created a script that will append files with "Redacted_". This script can be run on the phethelp drive once we have the new file structure setup in phet-docs.

**Comment by amanda-phet** [comment]
Awesome!

**Comment by oliver-phet** [comment]
This issue can now be closed. If any missing docs are found on the new 'PhET Files' folder structure, they can be documented here: https://github.com/phetsims/tasks/issues/739
