### ISSUE TITLE
Paring duplicated accounts from the database.

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#508]
The basic description of the issue is in phetsims/website#377.  We need to manually go through the list of duplicated accounts, which I'll send to @phet-steele via email, and decide which account to keep.  It should be pretty clear which account of the two has the more complete profile, and that is the one we'll keep.  If they are the same then we can just delete one arbitrarily.  

One problem might be if both accounts have associated activities/contributions.  We would want to somehow merge the accounts so the user still has access to edit the activity.

**Comment by mattpen** [comment]
Discussed with @ariel-phet via skype.  

This will probably not be a task that can be done by @phet-steele because the admin utility gives an internal error for duplicated accounts.  I'll write a script to delete the older account as long as there are no associated contributions. If there are contributions, I'll flag the user and process the resulting list manually.

**Comment by ariel-phet** [comment]
This is fine to track in the website repo in this case, comment above copied to original issue and closing.
