### ISSUE TITLE
Create a status:on-hold label for all repos

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#510]
@samreid said:

Hi there,

I have a number of issues that I want to keep assigned to me, but that I cannot actually work on because I am awaiting feedback from someone outside of the team.  I'd like to keep these issues assigned to me so I will remember to check up on the person if I don't hear from them in a while.

I considered adding a label `status:on-hold` or `status:awaiting-3rd-party` but wanted to first discuss what you do in this case, or if there is already a pre-existing label I should use for this case.  Also, I'm not sure how easy/difficult it is to add/remove labels across all repos now that we are standardized.  Or if this is a rare case, I can just track it outside of GitHub somehow.

Best Regards,
Sam

**Comment by samreid** [comment]
@mattpen replied:

Hello all,

I've also run into this same problem, but I don't really have a great solution working at present.

I'd vote for adding two labels - status:on-hold and status:pending. "On-hold" would signify if the issue is waiting on some thing, ( shipment of hardware, fulfillment of OIT request, deployment of dependent code, etc ), and "pending" would indicate that the issue is waiting on some person (non-assignee).

It's fairly easy for me to make changes across the repos now that I have a working script.

-Matt

**Comment by samreid** [comment]
@ariel-phet said:

Hey Sam,

It would be easy to add a new label to all repos.

Ariel

**Comment by samreid** [comment]
@pixelzoom said:

'status:on-hold’ is probably the most general, can apply to needing feedback, being blocked because of some other issue, etc.

Chris

**Comment by samreid** [comment]
@samreid said:

Sounds good, I'll create an issue for Matt.

**Comment by samreid** [comment]
@mattpen, can you please create a `status:on-hold` label for us all to use?

**Comment by ariel-phet** [comment]
@mattpen self-assiging so I can decide on a color, will do a "mockup" in masses and spring

**Comment by samreid** [comment]
I'm going to use `priority:4-low` until `status:on-hold` is ready.

**Comment by ariel-phet** [comment]
@mattpen color chosen #F0FFF0, modeled in masses and springs,

please go ahead and propogate through the repos and adjust the json file.

**Comment by mattpen** [comment]
The label has been added across the organization and I adjusted the json.  I verified by checking the website, tasks, and special-ops repos.
