### ISSUE TITLE
RC test: Color Vision 1.1.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#511]
Color Vision 1.1.0-rc.1 is ready for testing.

**NOTE**
Please do a full test on all platforms. But be aware that the priority for this release is making the sim translatable, and we've chosen not to address some known issues (https://github.com/phetsims/color-vision/issues). We will be doing several of these kinds of tests, mainly addressing the translation issues

**So before you test** look over the known issues in the sim

**Test Matrix**
https://docs.google.com/spreadsheets/d/1oGY221Y-50_DO15xOMYg8AE4CwSSjXpnT_Ojba9TX_4/edit#gid=714391574

Please run these string tests:

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)

If you discover a non-translation problem, and it is not a known issue, please make a new issue and reference it to this test

**Comment by pixelzoom** [comment]
Assigned to me until the RC is actually published.

**Comment by pixelzoom** [comment]
RC version is published. @ariel-phet feel free to assign test resources.

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan please make this the next testing priority after the completion of Neuron testing

**Comment by ariel-phet** [comment]
Other testing currently finished (neuron and pendulum lab), moving up to top priority for QA

**Comment by phet-steele** [comment]
@ariel-phet the matrix appears complete!

**Comment by pixelzoom** [comment]
No new issues found, #104 deferred until a future release. So I'll proceed with publishing 1.1.0.
