### ISSUE TITLE
Test new website login procedures

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#512]
@ariel-phet 

It would be a good idea to test the changes to the login procedures from phetsims/website/issues/167 and phetsims/website/issues/361.  Can we have @phet-steele test registering, submitting change email requests and logging in with emails in a variety of case structures?

**Comment by ariel-phet** [comment]
@mattpen can you make a (simplified) checklist of case structures for this issue?

**Comment by mattpen** [comment]
1. Create an account with email address in each of these forms:
    - all caps
    - mixed case
    - all lower case

2. Try to login with each of the previous accounts by typing the email in the following form:
    - all caps
    - mixed case
    - all lower case

**Comment by ariel-phet** [comment]
@phet-steele since this is a quick test and is important for users lets bump this to top priority

@mattpen should this testing be done on phet-dev, or the main site? Are the changes pushed to the main site?

**Comment by phet-steele** [comment]
@ariel-phet it hasn't been quick so far! And I've been testing on phet-dev.

**Comment by ariel-phet** [comment]
@phet-steele "quick" qualifier removed...:)

**Comment by mattpen** [comment]
Nothing has been pushed to Figaro yet.  Testing should be done on PhET-dev.

**Comment by phet-steele** [comment]
@mattpen this is working on my end.

**Comment by mattpen** [comment]
Thanks @phet-steele.  I've merged changes for phetsims/website#167 and phetsims/website#361 in with the master branch. Closing.
