### ISSUE TITLE
RC Test Balloons and Static Electricity 1.2.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#513]
Balloons and Static Electricity 1.2.0-rc.1 is ready for testing.

**Link to Sim:** http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.1/balloons-and-static-electricity_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.1/balloons-and-static-electricity_en-iframe.html

**Link to test matrix:** https://docs.google.com/spreadsheets/d/1mIXF1ksvJ12Xign_sUO-d1NFoSVADYErCUS3dWhZLms/edit#gid=0

Please do a full test of this RC on all platforms, and run the following to check internationalization:
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=x
- [x] stringTest=rtl

The purpose for this release is making the sim translatable, and we are not resolving all known issues in this release.
If you notice an issue that is not already logged in https://github.com/phetsims/balloons-and-static-electricity/issues, please create a new issue and reference this one.

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please make this the next testing priority after the completion of Color-Vision testing

**Comment by elisemorgan** [comment]
Assigning to @phet-steele to wrap up Win8/10 testing

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet I had done most of that without marking it, so testing complete!

**Comment by ariel-phet** [comment]
@jessegreenberg looks like this this is good to go

**Comment by jessegreenberg** [comment]
Thanks @phet-steele!  Need to go through https://github.com/phetsims/balloons-and-static-electricity/issues/130 after 2/18/16 dev meeting discussion.  Then will be ready for redeploy.

**Comment by jessegreenberg** [comment]
Will need a new RC after recent scenery/joist patches.  Closing.
