### ISSUE TITLE
Preliminary PhET-iO dev testing

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#515]
Similar to #514, @ariel-phet and I pruned the set of platforms and applications to be tested:

## Windows + Edge running Faraday's Law

http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.2.0-dev.1/phet-io/protected/wrappers.html
- [x] Events (JSON).  Open the console and confirm that every user action has a corresponding message in the event stream, and one or more corresponding model responses.  Test the performance
- [x] State.  Confirm that the state on the left is replayed to the right.  Try launching several scenarios using the "Launch" button and make sure it comes up looking exactly like the original simulation. Test the performance
- [x] Playback. Make sure the playback simulation on the right matches the one on the left. Test the performance
- [x] Screenshot.  Make sure that screenshots look good for a few scenarios
- [x] Active.  Make sure the sim can be disabled
- [x] Instance Proxies. Make sure it launches properly and shows items in the box. Try a few checkboxes or fire buttons to make sure they take effect in the simulation.

## OS X + Firefox running Color Vision

http://www.colorado.edu/physics/phet/dev/html/color-vision/1.2.0-dev.1/phet-io/protected/wrappers.html
- [x] Events (colorized for Chrome/Firefox).  Open the console and confirm that every user action has a corresponding message in the event stream, and one or more corresponding model responses.  Test the performance
- [x] State.  Confirm that the state on the left is replayed to the right.  Try launching several scenarios using the "Launch" button and make sure it comes up looking exactly like the original simulation. Test the performance
- [x] Playback. Make sure the playback simulation on the right matches the one on the left. Test the performance
- [x] Screenshot.  Make sure that screenshots look good for a few scenarios
- [x] Active.  Make sure the sim can be disabled
- [x] Instance Proxies. Make sure it launches properly and shows items in the box. Try a few checkboxes or fire buttons to make sure they take effect in the simulation.

## iPad2 + Mobile Safari running Beer's Law Lab

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.4/phet-io/protected/wrappers.html
- [x] Events (JSON/Frame).  Open the console and confirm that every user action has a corresponding message in the event stream, and one or more corresponding model responses.  Test the performance
- [x] State.  Confirm that the state on the left is replayed to the right.  Try launching several scenarios using the "Launch" button and make sure it comes up looking exactly like the original simulation. Test the performance
- [x] Playback. Make sure the playback simulation on the right matches the one on the left. Test the performance
- [x] Screenshot.  Make sure that screenshots look good for a few scenarios
- [x] Active.  Make sure the sim can be disabled
- [x] Instance Proxies. Make sure it launches properly and shows items in the box. Try a few checkboxes or fire buttons to make sure they take effect in the simulation.

The location of the password is described in https://github.com/phetsims/phet-io/issues/334#issuecomment-184841553

As part of the testing, we will have to test that authentication happens and works nicely across platforms.  Please report anything buggy or weird about passwords/logging in.
Assigning to @ariel-phet for review/scheduling/assignment.

**Comment by ariel-phet** [comment]
Note, this test will be done just by @phet-steele - not a general QA task

**Comment by phet-steele** [comment]
@samreid authentication has been working well across platforms.

**Comment by samreid** [comment]
Nice! I am glad to hear it, thanks for testing it out @phet-steele.

**Comment by phet-steele** [comment]
@samreid probably totally okay, but I wanted to say that the PhET menu and about dialogue do not appear in a screenshot. This correct?

**Comment by samreid** [comment]
Let's create an issue for it, we should ask @jonathanolson whether this is the expected behavior, and it is not the desirable behavior.

**Comment by jonathanolson** [comment]
Is expected, as I thought it would be desired (by me) at the time, since you had to open the menu to take a screenshot. Thus hiding the menu was beneficial.

Comment in ScreenshotGenerator:
```js
// only render the desired parts to the Canvas (i.e. not the overlay and menu that are visible)
```

**Comment by samreid** [comment]
Ah, thanks for commenting about the screenshot, I'll create an issue for it in phet-io.

**Comment by phet-steele** [comment]
@samreid alright, found what I could with these.

**Comment by samreid** [comment]
Thanks @phet-steele, closing.
