### ISSUE TITLE
PhET scenes for offices

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#519]
print some artwork to hang in 9th floor offices

**Comment by ariel-phet** [comment]
@arouinfar @amyh-phet here are your choices:

![camp phet](https://cloud.githubusercontent.com/assets/4051174/13132630/bfc08fe0-d5b1-11e5-8ff9-a2f1ae92d4dd.PNG)
![skatepark](https://cloud.githubusercontent.com/assets/4051174/13132631/c18002a2-d5b1-11e5-883a-6aa40835024d.PNG)
![movie](https://cloud.githubusercontent.com/assets/4051174/13132632/c344b704-d5b1-11e5-8ad5-6322000b97f6.PNG)
![chemlab](https://cloud.githubusercontent.com/assets/4051174/13132633/c59f5180-d5b1-11e5-88d0-e2e7b91ad908.PNG)

There is a math one...but that might have to be for the math office!

**Comment by amyh-phet** [comment]
Think I'm going to have to choose the chem lab scene.  Shocking I know!

**Comment by arouinfar** [comment]
I also really like the chem lab. It feels a bit more science-y than the others, but they are all really great!

**Comment by ariel-phet** [comment]
@amyh-phet can you make a .pdf of the chem scene from the .ai file on drive at the appropriate poster size (poster prints 36" in one dimension). And once you have the file assign this issue to @phet-steele.

@phet-steele once this issue is assigned to you, please work with @oliver-phet to get the poster printed. I know this seems like a low priority, but it will actually be very beneficial to have you learn how to print posters and this is a nice low stress poster to start with!

**Comment by amyh-phet** [comment]
@phet-steele   Here's the file for the chem scene.  Should print a 36" x 48" poster.

[chem.scene.office.pdf](https://github.com/phetsims/tasks/files/155139/chem.scene.office.pdf)

**Comment by phet-steele** [comment]
The poster was printed and hanged yesterday! Anyone else get a poster?

**Comment by ariel-phet** [comment]
@amyh-phet can you prep a pdf for the "math" scene?

@phet-steele please print the math scene and hang in your office

**Comment by amyh-phet** [comment]
@phet-steele    Math poster attached.
[mathclassroom.office.pdf](https://github.com/phetsims/tasks/files/157415/mathclassroom.office.pdf)

**Comment by ariel-phet** [comment]
This is now low priority

**Comment by ariel-phet** [comment]
@amyh-phet can you prep a "camp phet" one ( @jbphet requested that one for his office )

**Comment by amyh-phet** [comment]
@phet-steele   Here's "Camp PhET" too.
[campphet.pdf](https://github.com/phetsims/tasks/files/165610/campphet.pdf)

**Comment by amyh-phet** [comment]
Lets try again.
[campphetsized.pdf](https://github.com/phetsims/tasks/files/165775/campphetsized.pdf)
[mathclassroom3.pdf](https://github.com/phetsims/tasks/files/165776/mathclassroom3.pdf)

**Comment by phet-steele** [comment]
@amyh-phet @ariel-phet printed!

**Comment by ariel-phet** [comment]
All these have been, printed, and look fantastic. Closing!
