### ISSUE TITLE
RC Test Balloons and Static Electricity 1.1.0-rc.6

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#520]
Balloons and Static Electricity 1.1.0-rc.6 is ready for RC testing.

**NOTE**
This version is identical to 1.2.0, other than the version number and a patch to joist for setting the renderer on Edge.  Another full RC test is not necessary.  However, please spot check all platforms to make sure that nothing is broken after the recent patch, and fill out the test matrix as spot checking is completed.

Since 1.2.0-rc.1 passed all internationalization tests, this version does not need further internationalization string testing.

**New Test**
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)

*This is a new test we will be performing on all releases, if it fails, the sim will redirect to another website. Just test on one desktop platform, ie a Windows or Safari browser. Please note the platform used in this issue*

**Link to Sim:** http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.0-rc.6/balloons-and-static-electricity_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.0-rc.6/balloons-and-static-electricity_en-iframe.html

**Link to test matrix:**https://docs.google.com/spreadsheets/d/1mIXF1ksvJ12Xign_sUO-d1NFoSVADYErCUS3dWhZLms/edit#gid=1988058000

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please currently make this the next testing priority in the queue after #517

**Comment by ariel-phet** [comment]
#517 complete, bumping to top priority

**Comment by elisemorgan** [comment]
xss tested, passed, on OS X 10.10.5 Safari 9.0.3 (10601.4.4)

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet matrice completato.

**Comment by ariel-phet** [comment]
@jessegreenberg feel free to close (no noted issues)

**Comment by jessegreenberg** [comment]
Excellent, thanks!  The redeploy is being tracked in https://github.com/phetsims/balloons-and-static-electricity/issues/130, so closing this issue.  We are ready to deploy 1.1 of balloons!
