### ISSUE TITLE
RC test: Ohm's Law 1.3.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#521]
Ohm's Law 1.3.0-rc.2 is ready for testing.  The previous version passed almost all tests, but a general issue on the latest version of MS Edge is forcing a new RC, see https://github.com/phetsims/joist/issues/321.  Also, I decided to go ahead and attempt a fix for an issue with artifacts on some letters, see https://github.com/phetsims/ohms-law/issues/26.  Given the minimal changes to the code, a full retest is not needed.

Please verify that the following issues are fixed and that there is no obvious performance degradation:
- [x] Artifacts occur sometimes around the "R" (https://github.com/phetsims/ohms-law/issues/26)
- [x] Edge 25 NavBar and Menu problems (https://github.com/phetsims/joist/issues/321)

**Comment by ariel-phet** [comment]
@phet-steele this seems pretty quick to bang out, feel free to do yourself, or delegate to another QA team member

**Comment by phet-steele** [comment]
@jbphet artifacts resolved on IE11, and Menu problem resolved in Edge 25.

**Comment by jbphet** [comment]
Thanks all.  Looks like this one is good to go for production release.  Closing.
