### ISSUE TITLE
HTML5 Sims missing teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#524]
The following sims need teacher tips

- [x] Arithmetic 
- [x] Balancing Act (legacy tips exist)
- [x] Faradays Law 
- [x] Forces and Motion Basics (new features coming, legacy tips exist)
- [x] Gravity Force Lab (new features coming)
- [x] John Travoltage
- [x] Neuron
- [x] Ohm's Law
- [x] Resistance in a Wire 
- [x] Under Pressure (legacy tips exist)
- [x] Wave on a String (legacy tips exists)

**Comment by ariel-phet** [comment]
@phet-steele since you have now worked on some teacher tips, can you draft teacher tips of any of the above sims where they are marked "legacy tips exist"

You can either do this yourself, or show one of the the other QA team members how the current tips template. The idea would be to take the legacy tips, put them into the new format with fresh screenshots, then clean up by myself, @amyh-phet, or @arouinfar should be quick and straightforward to publish them.

**Comment by ariel-phet** [comment]
@phet-steele said arithmetic tips have been made, were sent to @amanda-phet but need review by someone else now that she is on leave.

**Comment by amyh-phet** [comment]
I'll take Ohm's law

**Comment by arouinfar** [comment]
I'll take care of Resistance in a Wire this Friday/Monday. I'd also like to work on FAMB and GFL, but time the tips with the release of updated versions.

**Comment by arouinfar** [comment]
@phet-steele we can work together on FAMB since it has legacy tips.

**Comment by amyh-phet** [comment]
I can also work on Neuron so tips are ready when sim gets released.

**Comment by amyh-phet** [comment]
I can also work on Neuron so tips are ready when sim gets released.

**Comment by arouinfar** [comment]
I've just uploaded the Tips for Gravity Force Lab, so checking it off this list. I've also finished up the tips for FAMB, but will hold off on posting them until the sim has been redeployed. John Travoltage tips have been started, and should be finished up this week.

**Comment by arouinfar** [comment]
GFL and FAMB tips have also been uploaded to Drive.

**Comment by phet-steele** [comment]
I've been taking at crack at Balancing Act.

**Comment by arouinfar** [comment]
I'll be working on Wave on a String.

**Comment by arouinfar** [comment]
FAMB tips are now live on the site.

**Comment by ariel-phet** [comment]
@arouinfar can we knock another of these tomorrow?

**Comment by arouinfar** [comment]
Can do @ariel-phet!

**Comment by ariel-phet** [comment]
@arouinfar lets get Balancing Act up next week so we can close this issue

**Comment by arouinfar** [comment]
Sounds good @ariel-phet. I've been meaning to check this one off my list.
