### ISSUE TITLE
Make sure things are shared/owned with phethelp

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#525]
We need to ensure that every collaborative Google file and folder (docs, sheets, etc) are shared and owned by the phethelp gmail. When all of your files have been transferred, check your name off the list.

All non-google files (.ai, .pdf, etc.) can't be transferred to google, so those will need to be manually updated later.

- [x] Oliver
- [x] Amy R
- [x] Amy H
- [x] Steele
- [x] Ariel
- [x] Amanda
- [x] Trish (by Steele) take all of Trish's non-google doc file and store in one folder
- [x] Arnab (primer documents)
- [x] Stephanie

**Comment by arouinfar** [comment]
Done!

**Comment by oliver-phet** [comment]
All of my "collaborative" google docs are now owned by phethelp.

I also migrated the folder 'PhET - sharon's files' to phet-docs. She is still the owner of the folder, but the migration copied and retained all of the files.

**Comment by oliver-phet** [comment]
Assigning to @amyh-phet, she is next on the list!

**Comment by amyh-phet** [comment]
@phet-steele   Your up next!

**Comment by phet-steele** [comment]
Did mine...Trish's is up next, yaaay.

**Comment by amyh-phet** [comment]
Can we add @arnabp to the list as we need to move primer documents that he owns?

**Comment by phet-steele** [comment]
@amanda-phet you up for this? Your turn!

**Comment by amanda-phet** [comment]
I think I did this a long time ago but I can double-check that all new files are transferred.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Mar 9, 2016 at 11:12 AM -0800, "phet-steele" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #525<https://github.com/phetsims/tasks/issues/525> to @amanda-phet<https://github.com/amanda-phet>.

-

**Comment by schasteen** [comment]
@kdessau-PhET needs to be added to this list; I've found several items from the Moore Foundation Meeting and Carl Wieman folders that are owned by her.

**Comment by oliver-phet** [comment]
@schasteen and @kdessau-PhET - Please keep in mind that we only need to transfer ownership to phethelp of files that are collaborative - if files are private or are only used by a subset of the team, they do not need to be transferred and can instead be transferred to your CU google account.

**Comment by schasteen** [comment]
I have also found a few documents in the Moore meeting folder owned by @kathy-phet

**Comment by kdessau-PhET** [comment]
let me know if you see any files that you'd like on the phethelp

**Comment by schasteen** [comment]
I have completed mine, but am not sure how to check my name off the list.

While doing it, I noticed some that would be good to be owned by PhET, I think:

Kathy P
https://drive.google.com/open?id=1928viGJhUVxdsrQdsrWXQZXeq3M2G-lqcunENiSlZw4

Kathy D
https://drive.google.com/folderview?id=0B8P9FsNfemDDNldoZG90SWhxRms&usp=sharing
https://drive.google.com/open?id=0B8P9FsNfemDDNldoZG90SWhxRms

John Blanco
https://drive.google.com/open?id=1kygJluQKIOz6jxDE7BZ1xNgvi7k39lfZT2fZkO17yYA

**Comment by kdessau-PhET** [comment]
I changed the folders above. Let me know if you have more items that you'd like me to change.

**Comment by amyh-phet** [comment]
@arnabp  When you have a chance, can you transfer ownership of the primer documents to phet-help?  I know we can't change video files, but we should be able to move the outlines, review documents, and documentation of procedures.

Thanks!

**Comment by amyh-phet** [comment]
@arnabp  and @oliver-phet Can we get the primer document ownership transferred soon?  Thanks.

**Comment by arnabp** [comment]
All docs that were under my ownership have now been transferred to phethelp

**Comment by oliver-phet** [comment]
Everyone's files are now shared. All new files should be uploaded using @colorado.edu accounts. Closing this for now.

Task to upload files to phet-docs: https://github.com/phetsims/tasks/issues/714
Other issue: https://github.com/phetsims/tasks/issues/505
