### ISSUE TITLE
RC test: Wave on a String 1.1.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#526]
**Test URL:** http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.0-rc.1/wave-on-a-string_en.html

**Iframe URL:** http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.0-rc.1/wave-on-a-string_en-iframe.html

**Test matrix:** https://docs.google.com/spreadsheets/d/1av1hvj2t8V7dkKOX4NhhC_mOBo_1Aw1WpOxKxfClaTA/edit#gid=1447851188

**NOTE**
This is a translation "S2015R" RC test, so it's mainly to fix i18n issues, and ensure nothing else broke. Please check over the current known issues in the sim before testing.

String tests should be explicitly tested.

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Reference issues to RC test task

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please makes this the current top testing priority

**Comment by ariel-phet** [comment]
@phet-steele looks like this one is close, would be great to finish off soon

**Comment by phet-steele** [comment]
@ariel-phet done.

**Comment by ariel-phet** [comment]
testing complete, closing
