### ISSUE TITLE
RC test: Neuron 1.1.0-rc.6

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#527]
Neuron 1.0.0-rc.6 is ready for testing.  This release was created for in order to resolve one very specific issue, but fixing the issue involved significant changes to the code that controls the concentration readouts.  Please verify that the the issue, listed below, is resolved on the platform where it was originally found, then regression test the behavior of the concentration readouts on our major platforms.

The issue is:
- [x] iPad 2 concentration label artifacts (https://github.com/phetsims/neuron/issues/122).

Please record the results of the testing and close the issue if it is fully resolved.

Link to RC: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.6/neuron_en.html

**Comment by ariel-phet** [comment]
@phet-steele since you are intimately familiar with this issue can you verify the fix and test on some major platforms? As @jbphet noted, please mark in this issues what platforms you tested on. Would be great to get this one published!!

**Comment by phet-steele** [comment]
@jbphet @ariel-phet All good to go. Tested on:

iPad2 iOS 9.2 (Witten)
OSX 10.9.5 Safari (Jordan)
OSX 10.11.3 Safari & Chrome (Dirac)
Edge 20+ (Steele & Galileo)
Win 10 Chrome (Steele)

**Comment by ariel-phet** [comment]
@jbphet does this mean we can publish?

**Comment by ariel-phet** [comment]
Testing complete, closing
