### ISSUE TITLE
Test fix for iPad 2 phet-io playback

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#530]
Please test http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.6/phet-io/protected/wrappers/mirror-input-events.html?sim=beers-law-lab on iPad 2/3 to ensure that https://github.com/phetsims/phet-io/issues/341 fixes the issue.

**Comment by phet-steele** [comment]
@jonathanolson it's fixed!

**Comment by jonathanolson** [comment]
Thanks!
