### ISSUE TITLE
Test new batch of phet-io sims

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#532]
I've published a new batch of phet-io sims here:

The wrappers links are here:

http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-dev.5/phet-io/protected/wrappers.html
http://www.colorado.edu/physics/phet/dev/html/color-vision/1.2.0-dev.2/phet-io/protected/wrappers.html
http://www.colorado.edu/physics/phet/dev/html/concentration/1.3.0-dev.3/phet-io/protected/wrappers.html
http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.2.0-dev.2/phet-io/protected/wrappers.html
http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.3.0-dev.2/phet-io/protected/wrappers.html

I'd like to share these links to BrainPOP, Ido/Sarah, and Go-Lab, since they contain numerous significant fixes, but I am wondering if @phet-steele can spare an hour or so to test out some of these wrappers on various platforms and see if anything seems amiss.

@ariel-phet can you prioritize and assign?

**Comment by ariel-phet** [comment]
I think @phet-steele can spare an hour or so. @phet-steele marking as high priority

**Comment by pixelzoom** [comment]
@phet-steele please verify these issues for beers-law-lab as part of testing 1.4.0-dev.5:

https://github.com/phetsims/beers-law-lab/issues/148
https://github.com/phetsims/beers-law-lab/issues/149
https://github.com/phetsims/beers-law-lab/issues/150
https://github.com/phetsims/beers-law-lab/issues/151

**Comment by phet-steele** [comment]
@samreid @ariel-phet well, that was more than an hour, but I'd say I'm done with this batch. @pixelzoom the query parameters associated with the above issues worked in all wrappers not embedding the sim in an iframe.

**Comment by pixelzoom** [comment]
>  the query parameters associated with the above issues worked in all wrappers not embedding the sim in an iframe.

I'm not sure what that means. Was there problems with these features when embedded in an iframe?

**Comment by pixelzoom** [comment]
Also https://github.com/phetsims/beers-law-lab/issues/151 is not a query parameter, it's a layout change, which I would expect to be independent of PhET-iO and iframes.

**Comment by phet-steele** [comment]
> Also phetsims/beers-law-lab#151 is not a query parameter, it's a layout change, which I would expect to be independent of PhET-iO and iframes.

@pixelzoom yup, I know, and it was fine.

> Were there problems with these features when embedded in an iframe?

The query parameters simply did nothing in the sim. The why is really a question for @samreid, and something I think he answered for me in Skype a few days ago:

"Ah, the wrappers that embed the sim in an iframe have a different way of passing through those query parameters, a way that you will not be able to use.  (Editing the HTML file).  OK to skip those tests for now but write a note that you are leaving those parts untested because you cannot easily edit the HTML wrapper file."

**Comment by pixelzoom** [comment]
Thanks for the clarification. Thanks for the clarification. I've closed the beers-law-lab issue mentioned in https://github.com/phetsims/tasks/issues/532#issuecomment-191917299.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll share the links with our collaborators.
