### ISSUE TITLE
Investigate "retractable posters" for PhET booth

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#534]

**Comment by oliver-phet** [comment]
http://www.tradeshowplus.com/Exhibit-Accessories-s/130.htm
https://www.4imprint.com/tag/540/Retractable-Banners/product/8922-32/Economy-Retractor-Banner-Display-32
https://www.postupstand.com/narrow-base-24-x-80-banner-stand

**Comment by oliver-phet** [comment]
@ariel-phet What do you think of something like this: https://www.postupstand.com/narrow-base-33-x-80-banner-stand

Would this size (33x80") work for us?

**Comment by ariel-phet** [comment]
That size could certainly work...I wonder if the 24"x80" might be better (33" wide is pretty darn big), and smaller might be a bit easier for transporting. I assume this will go kind of the corner of our booth, a bit into the foot traffic so we probably don't want it blocking too much space. Either way, I am sure Dave can lay something out that will look good.

Thoughts?

**Comment by oliver-phet** [comment]
Yep, I think the 24" would work. Can we have Dave mockup a poster that is 24x80"?

**Comment by ariel-phet** [comment]
Yes, I will have him work on it.

**Comment by ariel-phet** [comment]
We are trying out the 24"x80", @oliver-phet has ordered for NCTM. Closing
