### ISSUE TITLE
Artwork request for the new footer

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#535]
As part of the [new footer](phetsims/website#390), we'll need new image files for the four sponsors (Hewlett, NSF, O'Donnell, Moore) that are black and white with transparent background.  There is a mockup [here](https://cloud.githubusercontent.com/assets/4051174/13240423/b8dee662-d99f-11e5-97ed-f649c53a495f.PNG).  The dimensions should roughly be 115X45 or less.

Assigning to @ariel-phet for priority and assignment.

**Comment by ariel-phet** [comment]
@amyh-phet is this something that would be easy for you to take care of? If not please assign back to me.

**Comment by ariel-phet** [comment]
marking as low priority since we will not need these until the footer is almost ready to go.

**Comment by amyh-phet** [comment]
@ariel-phet I'm happy to take care of this.

**Comment by mattpen** [comment]
@amyh-phet - Is there any update on this yet?


Changing priority to medium after discussion with @ariel-phet

**Comment by mattpen** [comment]
The O'Donnell sponsor image will be replaced by [New Schools](http://www.newschools.org/)

**Comment by amyh-phet** [comment]
@mattpen   Sponsor logos are ready to go including New Schools.  Current artwork has each image at 115 x 45 or less, and all type is in white.  I'll send you the AI files this morning.

**Comment by amyh-phet** [comment]
Here you go @mattpen. Let me know if you need anything else.
![hewlett_logo_footer_vv](https://cloud.githubusercontent.com/assets/13650180/13821186/2e0e4568-eb66-11e5-8253-62e69f6ca429.png)
![moore_foundation_logo_footer-01](https://cloud.githubusercontent.com/assets/13650180/13821187/2e100060-eb66-11e5-8b5c-aa78e3326d8a.png)
![new_schools_logo_footer-01](https://cloud.githubusercontent.com/assets/13650180/13821188/2e1076bc-eb66-11e5-8da3-9a58ce89daee.png)
![nsf_logo_footer-01](https://cloud.githubusercontent.com/assets/13650180/13821189/2e14bd9e-eb66-11e5-87bd-f37fbe366a33.png)

**Comment by amyh-phet** [comment]
@mattpen   Sending the pngs by email as well - white text doesn't show up well here!

**Comment by mattpen** [comment]
Thanks Amy!
