### ISSUE TITLE
Maintenance Release testing for https://github.com/phetsims/chipper/issues/429

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#536]
For this, I'd recommend:
1. Open the sim in Chrome, ~30 seconds of "does it run" testing
2. Save the sim file to your computer, and open it using the file:// protocol in Chrome (can probably be done by navigating to the file and opening it with chrome).
3. On the tab with the sim, open Chrome's Dev-tools (Ctrl-Shift-J or Command-Option-J) and select the "network tab in the tools.
4. Reload the sim
5. Scroll through the list of "requests" until you find an entry usually called "collect?v=1&....", e.g.:
![screen shot 2016-03-07 at 12 21 04 pm](https://cloud.githubusercontent.com/assets/480878/13580368/2ae7a37e-e45f-11e5-8fe8-6227f7bee807.png)
6. If there is no request that is similar, please comment in this issue.

This should only require Chrome on one computer to complete all the recommended testing.

RCs for testing:

- [x] http://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.3-rc.1/acid-base-solutions_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.3-rc.1/arithmetic_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.3-rc.1/balancing-chemical-equations_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.1-rc.1/balloons-and-static-electricity_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.4-rc.1/beers-law-lab_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.2-rc.1/bending-light_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.2-rc.1/color-vision_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.3-rc.1/concentration_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.3-rc.1/faradays-law_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/friction/1.2.4-rc.1/friction_en.html
- [ ] http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.3-rc.1/graphing-lines_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.3-rc.1/hookes-law_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.3-rc.1/molarity_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.4-rc.1/molecule-shapes_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.2-rc.1/molecule-shapes-basics_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.3-rc.1/molecules-and-light_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.1-rc.1/neuron_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.1-rc.1/ohms-law_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.3-rc.1/ph-scale_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.3-rc.1/ph-scale-basics_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.3-rc.1/reactants-products-and-leftovers_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.2-rc.1/trig-tour_en.html
- [x] http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.1-rc.1/wave-on-a-string_en.html

**Comment by jonathanolson** [comment]
Associated issue: https://github.com/phetsims/chipper/issues/429

**Comment by ariel-phet** [comment]
@phet-steele current top testing priority. Please test yourself or delegate as you see appropriate.

**Comment by phet-steele** [comment]
@jonathanolson, only sim with no collect was Graphing Lines. All sims passed a sanity test.

**Comment by jonathanolson** [comment]
Thanks! I figured out the graphing-lines issue (why it didn't get the patch) and have tested it also.

Will be pushing out maintenance release production deployments.
