### ISSUE TITLE
RC Test: John Travoltage 1.2.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#537]
John Travoltage 1.2.0-rc.1 is ready for testing.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.0-rc.1/john-travoltage_en.html							

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.0-rc.1/john-travoltage_en-iframe.html							

**Test Matrix:** https://docs.google.com/spreadsheets/d/1m1FlqB8-1u8ZDxU1P1VGKiKzPwjKIHDVC_69SUzayX0/edit#gid=0

**NOTE:**
This is the first release candidate for the 'Summer Redeploy' of John Travoltage.  Normally, we would want to make sure that the sim passes all string tests, but John Travoltage does not have any translatable strings, so it is not necessary.

Please do a full retest of this sim to make sure that no new issues were introduced.  If you notice any issues that are not listed in https://github.com/phetsims/john-travoltage/issues, please create a new issue and reference this one.

**Comment by ariel-phet** [comment]
@BryceAG @brroberts1231 @elisemorgan @bryo5363  @phet-steele please makes this the current top testing priority

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet matrix has been filled out!

**Comment by ariel-phet** [comment]
@phet-steele can you comment on the performance difference between iOS 9 and iOS 8 on the iPad 2, I am surprised it is marked "OK" for iPad2 iOS9

Can you further comment on how iPad2 iOS9 performance of this RC compares to the published version? I want to know if equivalent or not. I am fine if they are equivalent, but if this RC has degraded performance it would be good to know how and why.

**Comment by phet-steele** [comment]
@ariel-phet I personally would have labeled iOS 8 performance as "OK" (BR tested that platform). For both iOSs, the performance between the RC and the published was equivalent.

**Comment by ariel-phet** [comment]
Sounds good, thanks for the info @phet-steele (I noted your comments in the test matrix

@jessegreenberg assigning back to you to complete the redeploy!

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, closing this tasks issue.  Completing the redeploy will be tracked in https://github.com/phetsims/john-travoltage/issues/86
