### ISSUE TITLE
Test rotating text on Balancing Act 1.1.0-dev.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#538]
The Balancing Act simulation is currently being worked on in order to create and publish a translatable version.  There was previously a workaround in this sim for the handling of rotating text, see https://github.com/phetsims/balancing-act/issues/16 and https://github.com/phetsims/balancing-act/issues/25.  I did some light testing to see if the problem with rotating text had been solved in the browsers, and it appears that it has.  I've removed this workaround, and would like a more thorough test of the text rotation behavior on several platforms so that we can feel confident in this change.

Please read through the issues linked about, then test version 1.1.0-dev.2 (http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.0-dev.2/balancing-act_en.html) on all of our major platforms looking only for whether or not the text looks decent when rotating, which is generally seen when the plank moves.  Turning on the ruler or markers adds more text, so this should be done a lot.  If the behavior is reasonably close to what is seen in the currently published version of the simulation, and no major problems are seen, I'll conclude that the workaround can be safely removed.  If you *do* notice text rotation issues, please note them both in this issue and in https://github.com/phetsims/balancing-act/issues/25.

If other new issues happen to be found in the course of this testing, please log them in separate issues in the balancing-act repository.

**Comment by ariel-phet** [comment]
@phet-steele can you check this out or delegate if you are crunched for time?

**Comment by phet-steele** [comment]
@jbphet there are some noticeable issues in FF and Chrome. The text on Chrome "swims" around while FF text strobes. The catch is that this really only happens when the see saw is rotating slowly. Fast rotating text makes these issues less discernible.

**Comment by ariel-phet** [comment]
@jbphet reverted to the rasterized text as noted in https://github.com/phetsims/balancing-act/issues/25

Closing task
