### ISSUE TITLE
accounts for schmitzware on PhET servers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#539]
Moving this from https://github.com/phetsims/rutherford-scattering/issues/30#issuecomment-194538227. @phetsims/schmitzware will need accounts on the PhET dev and production servers in order to deploy simulations.  Assigned to @ariel-phet, since I have no idea who handles this.

**Comment by pixelzoom** [comment]
Looks like there was some discussion about this on Skype, and @jessegreenberg is contacting the relevant parties. So assigning to him.

**Comment by schmitzware** [comment]
I've sent OIT a note.. waiting for a response.

**Comment by jessegreenberg** [comment]
OIT responded, an account for @phetsims/schmitzware should be ready for activation.  I have forwarded the activation link to @phetsims/schmitzware.

**Comment by jessegreenberg** [comment]
@phetsims/schmitzware provided OIT with the information and activated his account on spot.  We are now trying to add him to the physphet group  so that he as proper access.  OIT is working on this and may contact @jessegreenberg for confirmation.

**Comment by jessegreenberg** [comment]
@phetsims/schmitzware has been added to physphet group and now has proper spot access.  He has successfully deployed a dev version to spot for testing.  Closing.
