### ISSUE TITLE
Dev testing for Energy Skate Park: Basics 1.1.0-dev.1

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#540]
Energy Skate Park: Basics underwent major implementation changes regarding WebGL and requires dev testing before moving into a formal RC.  The main parts this will impact are the pie chart, bar chart and skater, so please focus testing on those components and performance.  You can tell WebGL is enabled if the pie chart has no inner lines/strokes on the slices, webgl is disabled if the pie chart has strokes on the slices.

Here's the link:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.1/energy-skate-park-basics_en.html

- [x] iPad2/Safari
- [x] Win/IE
- [x] Win/IE with ?webgl=false
- [x] Win/Edge
- [x] Win/Edge with ?webgl=false
- [x] Win/Firefox
- [x] OS X/Chrome
- [x] Chromebook

This set of tests seems like it would have a high probability (though not 100% of revealing problems if there are any), @ariel-phet let me know if you want to augment this list of platforms or save that for broader RC testing.  Also assigning to @ariel-phet to prioritize and delegate.

**Comment by ariel-phet** [comment]
@BryceAG @brroberts1231 @elisemorgan @bryo5363 @phet-steele please makes this the current top testing priority

**Comment by elisemorgan** [comment]
testing complete @samreid

**Comment by samreid** [comment]
Thanks @elisemorgan and @phet-steele, I'll move to the next step in https://github.com/phetsims/energy-skate-park-basics/issues/336
