### ISSUE TITLE
RC Test: Gravity Force Lab 2.0.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#543]
Gravity Force Lab 2.0.0-rc.1 is ready for testing.

**Test Link:** http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-rc.1/gravity-force-lab_en.html

**Link to test matrix:** https://docs.google.com/spreadsheets/d/1Hbe-bDR0VC23nS-pyl4UpsO16HPZ1ayt-yWgyZh1OL0/edit#gid=1441111908

Please do a full test of this RC on all platforms, and run the following to check internationalization:

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=x
- [x] stringTest=rtl
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Reference issues to RC test task

The purpose for this release is to make the sim translatable, but also adds a major new feature (constant radius masses), fixes an issue where the masses were not constant density, and increases the mass value ranges.  There are two outstanding issues, please do not duplicate these if found during testing  (see https://github.com/phetsims/gravity-force-lab/issues/41 and https://github.com/phetsims/gravity-force-lab/issues/40).  Any other issues found are fair game.

**Comment by ariel-phet** [comment]
@BryceAG @brroberts1231 @elisemorgan @bryo5363 @phet-steele next in line for redepoly testing after #542

**Comment by ariel-phet** [comment]
bumping to top testing priority

**Comment by phet-steele** [comment]
@ariel-phet @aadish finito.

**Comment by jbphet** [comment]
Thanks all.  Closing, and will follow up with fixes for what looks like a couple of minor issues in GitHub and either do an new RC or, if changes are small, straight to a production deployment.
