### ISSUE TITLE
Dev test Rutherford Scattering 1.0.0-dev.1

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#545]
**Testing Link**
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.1/rutherford-scattering_en.html

- [x] iPad2/Safari
- [x] Win/Edge
- [x] Win/Chrome
- [x] OS X/Safari

**General Tests**
The following tests should also be performed as part of this testing
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Reference issues to dev test task

**Comment by ariel-phet** [comment]
@phet-steele assigning to you (feel free to complete yourself or delegate)

**Comment by bryo5363** [comment]
I will test chrome and edge

**Comment by phet-steele** [comment]
@brroberts1231 @BryceAG @elisemorgan please take a crack at this sim.

**Comment by elisemorgan** [comment]
OS X / Safari

**Comment by ariel-phet** [comment]
bumping to high priority (after forces and motion testing)

**Comment by phet-steele** [comment]
@schmitzware @ariel-phet this dev version is done with testing.

**Comment by ariel-phet** [comment]
Looks as though all referenced issues have been addressed. Closing
