### ISSUE TITLE
implement PhetButton.dispose?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#549]
Noted while investigating https://github.com/phetsims/tasks/issues/546.

In https://github.com/phetsims/joist/commit/dc0a0a3ca18462d06950c943089f793135d1b374, @jessegreenberg added this to PhetButton:

```js
    /**
     * Dispose function for the accessible check box.
     * @public (accessibility)
     */
    dispose: function() {
      // TODO
    }
```

What is "accessible check box"? (there is no CheckBox in PhetButton)
Does this function need to be implemented?
While it's not implemented, is it a memory leak?

**Comment by jessegreenberg** [comment]
Yikes! Very sloppy, I am sorry.  References to check box should have no place here.  Dispose function implemented in commit above.

Not likely to have been a memory leak previously.  AccessiblePeer exists for as long as the PhetButton.  But should be covered by dispose now.

Closing, but @pixelzoom feel free to review changes if you wish.
