### ISSUE TITLE
RC Test: Fraction Matcher 1.1.0-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#552]
@ariel-phet I fixed the issues that appeared in Fraction Matcher 1.1.0-rc.1:

https://github.com/phetsims/fraction-matcher/issues/95
https://github.com/phetsims/fraction-matcher/issues/97

And published a new version here:
http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.0-rc.2/fraction-matcher_en.html

This uses the same SHAs for all common code repos as rc.1 and I manually diffed rc.1 and rc.2 to make sure rc.2 only differed by the expected fixes.

In my opinion rc.2 does not require a full RC test matrix.  At a minimum we will need QA to verify the fix for the two issues linked above (preferably with @phet-steele verifying the issue he reported).  Any testing beyond that is at your discretion, perhaps spot testing 1-2 platforms would be nice just as a sanity test but I will leave it up to you.

**Comment by ariel-phet** [comment]
@phet-steele this would be good to finish off. I agree with @samreid a quick spot test on 2 platforms would be good (iPad and one desktop sounds good to me)

**Comment by phet-steele** [comment]
@samreid @ariel-phet above issues verified as good. Spot testing on Win 10 Chrome and iPad 2 & 3 was good to go.

**Comment by samreid** [comment]
Excellent, thanks, I'll continue publication in https://github.com/phetsims/fraction-matcher/issues/92
