### ISSUE TITLE
Standardizing Performance Testing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#553]
Alright @ariel-phet and anyone else, here is where we shall brainstorm ideas. The suggestion here is to make performance testing a much more objective process for QA. Right now it is quite the opposite, and is a very opinionated test. Really the sim passes performance if it "looks" good. Among the QA team, this has caused discrepancy when reporting performance as "Good", "OK", or "Poor" since we have different ideas of what looks good and what doesn't. I'm hoping we can change this to include some sort of quantitative reasoning with the end goal of releasing a better product.

_Begin my brainstorming:_

So far my thoughts have been to include some sort of benchmark for each sim when it is put out for testing. I say "each sim" since it is more than likely impossible to create generalized performance requirements. Neuron, as the best example, was deemed acceptable when it was visually bad (no offense @jbphet). No other sim would have been acceptable in this case, so a sim by sim benchmark would probably be most appropriate here. As to what this benchmark would include, I'm thinking

**Written in rc task issue**
- A video showing acceptable performance (_I think this will be most important_)
- Minimum average fps
- Maximum memory usage
- Load time

Then when a sim reaches the QA team, we compare how the sim runs on our device to what's reported in the rc task.  How I'm thinking this would affect testing matrices is we do away with "Good", "OK", and "Poor" and replace them with "Better", "Meets Benchmark", "Worse". If results turn out to be 'Worse", make a specific issue in a repo detailing the performance discrepancy (alongside a video if it's a visual problem).

**Tests during development and design**
- Any noticeable lag when dragging objects?
- Any noticeable lag when the sim is animating?
- Any noticeable lag when switching between screens/game challenges?
- Any miscellaneous lag issues?
- Any issues during interviews?
- Does the sim reach the desired fps? (using ?profiler q. param.)
- Does the sim fall within the maximum desired memory usage?
- Does the sim have the desired load time?

I'm thinking that we keep these subjective questions separate from rc testing (notice the rc task list has no questions, but the development/design list does). The last three in the above list would be quantitative tests comparing to predetermined numbers (60 fps, 30 fps min, <= 20 mb memory usage, 3-5 sec load time, as examples). As to whom would decide if a sim reaches a benchmark, it would either be developers or designers. I'm leaning more towards the designers; they would go through the above list at stages in development and ruthlessly make sure it is up to snuff, particularly when dealing with lag. We would also have to decide which platform, and more importantly which device, would serve as setting the benchmark and perform this checklist on that device.

_End my brainstorming_

@ariel-phet bring people into this discussion as you see fit. I'd prefer input from developers and one of the Amys, and maybe an undergrad.

**Comment by ariel-phet** [comment]
@phet-steele - what are your current thoughts on this issue?

**Comment by phet-steele** [comment]
@ariel-phet my current thoughts are the same. two months later and I still think we need to care about quantifying performance for QA passes.

**Comment by KatieWoe** [comment]
This may be discussed more in QA.  For now we will try to add definitions for the three levels of performance
