### ISSUE TITLE
Update some devices to new versions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#554]
QA should update Tycho from iOS 9.3 Beta to the released version (iOS 9.3), and presumably update Dirac's 10.11.3 partition to 10.11.4.

**Comment by phet-steele** [comment]
Tycho and Leibniz are iOS 9.3, Dirac has a 10.11.4 partition (replaced 10.11.3). Asset spreadsheet updated.

**Comment by phet-steele** [comment]
@elisemorgan please also update diSessa to 9.3

**Comment by elisemorgan** [comment]
Done and updated on asset inventory

**Comment by phet-steele** [comment]
Thanks
