### ISSUE TITLE
Getting headshot of New People

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#555]
@oliver-phet assigning this to you for now, we should get a headshot of @andrewadare for the Team page.

I will try to remind @kathy-phet to bring her camera to work perhaps on Thursday for status meeting.

**Comment by andrewadare** [comment]
I will try and remember to wear a nice shirt.

**Comment by ariel-phet** [comment]
@oliver-phet did @kathy-phet leave her camera around?

**Comment by oliver-phet** [comment]
I don't see it around here.

Sent from Outlook Mobile<https://aka.ms/thuyj7>. Yes, it works with Gmail.



On Mon, May 9, 2016 at 9:39 AM -0700, "Ariel Paul" <notifications@github.com<mailto:notifications@github.com>> wrote:


@oliver-phet<https://github.com/oliver-phet> did @kathy-phet<https://github.com/kathy-phet> leave her camera around?

-

**Comment by ariel-phet** [comment]
Ah...KP reports brought it home for mothers day...will bring back Thursday

**Comment by amanda-phet** [comment]
Thursday June 23 I will bring my camera and take pictures of new people: 
@andrewadare 
@andrea-phet 
@alynne-phet 
Susan (if on-campus) 
Wear a professional-casual top (no graphic tees, please). 
I'll be available at 9:50am and 11:30am-1:30. Let me know what time you are available. 

I will either edit the photos myself or give to someone else to do, but @phet-steele can you get the info needed from these team members (including @schmitzware as a consultant/contractor) and upload to the team page?

**Comment by andrea-phet** [comment]
9:50 am is good for me. Thank you!

**Comment by andrewadare** [comment]
I will plan for the earlier time as well.

**Comment by amanda-phet** [comment]
Great! Let's meet in the quad just south of Duane and take the pictures there.

**Comment by alynne-phet** [comment]
That works for me as well!

**Comment by phet-steele** [comment]
> can you get the info needed from these team members and upload to the team page?

👍

**Comment by phet-steele** [comment]
@amanda-phet I have everyones info, thank you all!

**Comment by phet-steele** [comment]
Headshots taken. @amanda-phet are we all done here?

**Comment by amanda-phet** [comment]
I believe so! Closing.
