### ISSUE TITLE
Screenshot testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#556]
I've added support for WebGL in screenshots (https://github.com/phetsims/joist/issues/212), and fixed a few other things related to screenshots. It should now be available in the PhET menu.

I'm curious to spot-check the following sims:
1. Energy Skate Park: Basics (the energy pie chart is WebGL exclusively, and should appear as normal in screenshots)
2. Molecule Shapes (the 3D molecule view is in WebGL via three.js, but should appear as normal in screenshots)

Additionally, please do a general test of the 'Screenshot' feature (in the menu), ideally on our supported platforms.

Sims can be run from phettest.colorado.edu. I generally recommend running 'built' sims for the iPad if they won't open in the normal mode.

**Comment by phet-steele** [comment]
@jonathanolson quick testing on ESPB and MS looked great. I'll wait on @ariel-phet before putting more time into this.

**Comment by ariel-phet** [comment]
@phet-steele what platforms did you test on?

**Comment by phet-steele** [comment]
@ariel-phet Win 10 chrome for maybe 10 minutes

**Comment by ariel-phet** [comment]
@phet-steele since @jonathanolson also asked for a general test on "our supported platforms" we should probably test these two sims on all supported platforms. Feel free to make a simplified "Screenshot Test Matrix"

**Comment by brroberts1231** [comment]
I noticed while writing phetsims/energy-skate-park-basics#346 that when I took a screenshot with the phet menu option, and it didn't show what was actually being displayed on screen. 

The issue I was seeing: skater is invisible
![screen shot 2016-04-08 at 3 16 24 pm](https://cloud.githubusercontent.com/assets/11947677/14397972/d231554c-fd9d-11e5-9168-36e1d2b2ad56.png)

vs. what the screenshot took:
![energy skate park- basics screenshot](https://cloud.githubusercontent.com/assets/11947677/14397998/079b1fb0-fd9e-11e5-928f-9288e1ac7efb.png)

**Comment by ariel-phet** [comment]
@phet-steele any movement on this issue?

**Comment by phet-steele** [comment]
@ariel-phet, only slight. Hasn't been priority.

**Comment by ariel-phet** [comment]
@phet-steele we are no shipping this feature with published sims, so I think we need to bump priority...

**Comment by phet-steele** [comment]
@jonathanolson I'm not seeing any major problems (hooray!) except *super* minor problems with kerning in the resulting screenshot, and iPad screenshots only looking nice with two tabs open beforehand (see phetsims/joist/issues/234 for the sort of related issue).

**Comment by jonathanolson** [comment]
Sounds great, thanks!
