### ISSUE TITLE
Testing new minimal PhET-iO instrumentation sims

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#557]
From https://github.com/phetsims/phet-io/issues/383#issuecomment-201375267

Here is a list of sims that should be tested:

- [x] Balancing Act: https://phet-io.colorado.edu/0.1/sims/balancing-act/1.1.0-dev.3/phet-io/protected/wrappers.html
- [x] Graphing Lines: https://phet-io.colorado.edu/0.1/sims/graphing-lines/1.2.0-dev.1/phet-io/protected/wrappers.html
- [x] Wave on a String: https://phet-io.colorado.edu/0.1/sims/wave-on-a-string/1.1.0-dev.1/phet-io/protected/wrappers.html
- [x] Energy Skate Park: Basics: https://phet-io.colorado.edu/0.1/sims/energy-skate-park-basics/1.1.0-dev.2/phet-io/protected/wrappers.html
- [x] Arithmetic: https://phet-io.colorado.edu/0.1/sims/arithmetic/1.1.0-dev.1/phet-io/protected/wrappers.html

The tests we need:
1. launch each sim and make sure screenshots can be taken from the screenshots wrapper
2. spot test each sim on 2 desktop platforms (one Mac and one Win) to see if there are any obvious problems (since published from master and not stable SHAs)

Reassigning to @ariel-phet to review/prioritize/delegate.

**Comment by phet-steele** [comment]
Balancing Act, Graphing Lines, and Arithmetic each suffer from phetsims/scenery/issues/514. There's nothing really we can do about this but wait, just figured I'd note it.

**Comment by phet-steele** [comment]
These look great on Win 10 Chrome, switching to Mac.

**Comment by phet-steele** [comment]
And everything is good on 10.11.4 Safari as well!

**Comment by samreid** [comment]
@phet-steele thanks for taking these for a test drive, I'll continue in https://github.com/phetsims/phet-io/issues/383#issuecomment-201375267
