### ISSUE TITLE
NCTM supplies and prep

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#558]
- [x] New Math Flyer? @amyh-phet 
- [x] Check banner (new sponsors?)
- [x] Print Flyers
- [x] Setup iPad air with sims/app
- [x] Business cards (general and Ariel) new cards ordered 3/31

**Comment by amyh-phet** [comment]
I can take care of the flyer.

**Comment by amyh-phet** [comment]
@oliver-phet   New Math flyer is in Drive.   Files saved in:  PhET Ai files > Flyers > 2016.04_NCTM.
