### ISSUE TITLE
Check whether Energy Skate Park: Basics 1.1.0-dev.3 crashes the iPad

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#559]
@jonathanolson and I published a proposed fix for the crash problem for Energy Skate Park: Basics here

http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.3/energy-skate-park-basics_en.html

It needs to be tested on the device where it was previously crashing.  @ariel-phet can you please prioritize and reassign?  @elisemorgan and @phet-steele reported the problem before in https://github.com/phetsims/energy-skate-park-basics/issues/343

**Comment by phet-steele** [comment]
The sim runs beautifully on iPad 2 & 3, huzzah! Now maybe we tackle phetsims/energy-skate-park-basics/issues/299? :wink:

**Comment by ariel-phet** [comment]
Looks like this was checked by @phet-steele closing
