### ISSUE TITLE
Sim testing with phet-app query parameter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#560]
Would be great to get testing on two sims (one with an options dialog available via the phet menu, e.g. Molecule Shapes, and one without) with the ?phet-app query parameter added.

Testing on one platform should be sufficient, but please test the require.js AND built modes on phettest.colorado.edu.

Testing should look for the changes from https://github.com/phetsims/phet-app/issues/24, namely:
1. "Fullscreen" / "Screenshot" / "Report a Problem" / "Check for Updates" should be gone from the PhET Menu (About, PhET Website, and if applicable Options should still be available).
2. Update information should not be shown in the About dialog (i.e. no "simulation is up to date").
3. Otherwise (besides a Google Analytics difference that I've tested), things should be the same as normal simulations.

**Comment by ariel-phet** [comment]
@phet-steele this would be good test soon.

The appropriate platform would be iPad2 latest iOS, since iPad is the only platform where the ?phet-app will be relevant.

**Comment by phet-steele** [comment]
@ariel-phet @jonathanolson works as expected on Tycho with Bending Light & Charges and Fields.

**Comment by jonathanolson** [comment]
Thanks!
