### ISSUE TITLE
Dev Test: Forces And Motion Basics 2.0.0-dev.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#562]
A few new features have been added to Forces and Motion: Basics, so it would be good to an initial dev test before pushing through last steps of the redeploy.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.1/forces-and-motion-basics_en.html

Please do a dev test of this sim on the following platforms:
 - [x] iPad2/Safari
 - [x] Win/Edge
 - [x] Win/Chrome
 - [x] OS X/Safari

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG please make this the current top testing priority. Please mention in this issue the platform you are testing so other QA members know

**Comment by phet-steele** [comment]
I'll probably do them all eventually, but I've been doing both Win platforms.

**Comment by phet-steele** [comment]
@jessegreenberg looks like the team finished up the testing, your move now.

**Comment by jessegreenberg** [comment]
Excellent, thanks for the test!
