### ISSUE TITLE
Maintenance release testing for the phet-app

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#563]
Main issue: https://github.com/phetsims/phet-app/issues/24

For this, I'd recommend doing very similar testing to https://github.com/phetsims/tasks/issues/560. For the following sim URLs (RCs), please ensure that:

1. The first link seems to run normally (15-30 seconds?), and has the same PhET Menu options as before, etc.
2. The second (phet-app) link should have the changes mentioned in #560, but otherwise seems to run normally.

- [x] [Acid-Base Solutions](http://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.4-rc.1/acid-base-solutions_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.4-rc.1/acid-base-solutions_en.html?phet-app))
- [x] [Arithmetic](http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.4-rc.1/arithmetic_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.4-rc.1/arithmetic_en.html?phet-app))
- [x] [Balancing Chemical Equations](http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.4-rc.1/balancing-chemical-equations_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.4-rc.1/balancing-chemical-equations_en.html?phet-app))
- [x] [Balloons and Static Electricity](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.2-rc.1/balloons-and-static-electricity_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.2-rc.1/balloons-and-static-electricity_en.html?phet-app))
- [x] [Beer's Law Lab](http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.5-rc.1/beers-law-lab_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.5-rc.1/beers-law-lab_en.html?phet-app))
- [x] [Bending Light](http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.3-rc.1/bending-light_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.3-rc.1/bending-light_en.html?phet-app))
- [x] [Color Vision](http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.3-rc.1/color-vision_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.3-rc.1/color-vision_en.html?phet-app))
- [x] [Concentration](http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.4-rc.1/concentration_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.4-rc.1/concentration_en.html?phet-app))
- [x] [Faraday's Law](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.4-rc.1/faradays-law_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.4-rc.1/faradays-law_en.html?phet-app))
- [x] [Fraction Matcher](http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.1-rc.1/fraction-matcher_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.1-rc.1/fraction-matcher_en.html?phet-app))
- [x] [Friction](http://www.colorado.edu/physics/phet/dev/html/friction/1.2.5-rc.1/friction_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/friction/1.2.5-rc.1/friction_en.html?phet-app))
- [x] [Graphing Lines](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.4-rc.1/graphing-lines_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.4-rc.1/graphing-lines_en.html?phet-app))
- [x] [Gravity Force Lab](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.1-rc.1/gravity-force-lab_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.1-rc.1/gravity-force-lab_en.html?phet-app))
- [x] [Hooke's Law](http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.4-rc.1/hookes-law_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.4-rc.1/hookes-law_en.html?phet-app))
- [x] [John Travoltage](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.1-rc.1/john-travoltage_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.1-rc.1/john-travoltage_en.html?phet-app))
- [x] [Molarity](http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.4-rc.1/molarity_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.4-rc.1/molarity_en.html?phet-app))
- [x] [Molecule Shapes](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.5-rc.1/molecule-shapes_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.5-rc.1/molecule-shapes_en.html?phet-app))
- [x] [Molecule Shapes: Basics](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.3-rc.1/molecule-shapes-basics_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.3-rc.1/molecule-shapes-basics_en.html?phet-app))
- [x] [Molecules and Light](http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.4-rc.1/molecules-and-light_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.4-rc.1/molecules-and-light_en.html?phet-app))
- [x] [Neuron](http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.2-rc.1/neuron_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.2-rc.1/neuron_en.html?phet-app))
- [x] [Ohm's Law](http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.2-rc.1/ohms-law_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.2-rc.1/ohms-law_en.html?phet-app))
- [x] [pH Scale](http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.4-rc.1/ph-scale_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.4-rc.1/ph-scale_en.html?phet-app))
- [x] [pH Scale: Basics](http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.4-rc.1/ph-scale-basics_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.4-rc.1/ph-scale-basics_en.html?phet-app))
- [x] [Reactants, Products and Leftovers](http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.4-rc.1/reactants-products-and-leftovers_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.4-rc.1/reactants-products-and-leftovers_en.html?phet-app))
- [x] [Resistance in a Wire](http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.2-rc.1/resistance-in-a-wire_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.2-rc.1/resistance-in-a-wire_en.html?phet-app))
- [x] [Trig Tour](http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.3-rc.1/trig-tour_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.3-rc.1/trig-tour_en.html?phet-app))
- [x] [Wave on a String](http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.2-rc.1/wave-on-a-string_en.html) ([phet-app](http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.2-rc.1/wave-on-a-string_en.html?phet-app))

**Comment by ariel-phet** [comment]
@phet-steele feel free to complete yourself or delegate

**Comment by ariel-phet** [comment]
FYI I checked Acid-Base all looked good.

**Comment by phet-steele** [comment]
@jonathanolson all good.

**Comment by phet-steele** [comment]
@jonathanolson are you aware that none of them had "Screenshot" in the menu?

**Comment by jonathanolson** [comment]
Yes, it's not supposed to be there. Thanks!
