### ISSUE TITLE
RC Test: Energy Skate Park: Basics 1.1.0-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#564]
Energy Skate Park: Basics 1.1.0-rc.2 is ready for testing (as prepared in phetsims/energy-skate-park-basics#336 )

First, before doing anything else, test that it doesn't crash on iPad2

- [x] Doesn't crash on iPad2.

After verifying that it doesn't crash on iPad2, let's continue through the test matrix.  This sim is published off master, many things could have changed in common code, so please be vigilant. Also make sure to open the PhET menu and such and poke around.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.2/energy-skate-park-basics_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.2/energy-skate-park-basics_en-iframe.html

**Test Matrix:** https://docs.google.com/spreadsheets/d/1D-qTre2wNUoDpCMvTtytWfW9pN72YITkHf2Qe0-P5uc/edit

**Redeploy General Tests** (copied from https://github.com/phetsims/tasks/issues/528 )
String tests were already passed, but please perform the following 
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Reference issues to RC test task

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG please make this the next testing priority after #562

**Comment by brroberts1231** [comment]
Just to be sure, we are working on rc.2, not rc.1which is written at the top of this issue, correct?

**Comment by samreid** [comment]
I updated the issue description to point to rc.2 (was incorrectly pointed at rc.1).

**Comment by elisemorgan** [comment]
This matrix is complete

**Comment by samreid** [comment]
Thanks, I'll continue in the ESPB issue.
