### ISSUE TITLE
RC Test: Balancing Act 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#565]
Test link: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.0-rc.2/balancing-act_en.html

There were only a few changes since v1.1.0-rc.1, so a full retest is not required.  Please do a sanity test on the major supported platforms, then verify that the following have been fully fixed (and close them if so):

- [x] move the reset button (https://github.com/phetsims/balancing-act/issues/68)
- [x] ?stringTest=double issues (https://github.com/phetsims/balancing-act/issues/60)

**Comment by ariel-phet** [comment]
@phet-steele this looks a job for you to polish off at high priority

**Comment by phet-steele** [comment]
@jbphet you're good to go on this.

**Comment by jbphet** [comment]
Thanks for the testing, closing.
