### ISSUE TITLE
Dev Test: Keyboard navigation for FAMB, CLB, BASE 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#566]
As part of the updates to the accessibility page, we are going to publish prototypes for keyboard navigation for Capacitor Lab: Basics, Forces and Motion: Basics, and Balloons and Static Electricity.  It would be good to do some dev testing of the keyboard navigation for these prototypes before they are added to the updated page.

Here are the links to each dev version:

**CL:B**
http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.15/capacitor-lab-basics_en.html?accessibility

**BASE:**
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-accessible-instance.15/balloons-and-static-electricity_en.html?accessibility

**FAMB:**
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-accessible-instance.1/forces-and-motion-basics_en.html?accessibility&screens=1

@phet-steele these don't necessarily need rigorous testing, but it would be good to spot check each one to make sure that they work on multiple platforms with a keyboard

- [x] OSX + Safari
- [x] OSX + Chrome
- [x] OSX + Firefox
- [x] Windows 10 + IE11
- [x] Windows 10 + Edge
- [x] Windows 10 + Chrome
- [x] Windows 10 + Firefox

**Comment by jessegreenberg** [comment]
Also here are a few notes on the keyboard interactions for each sim:

Balloons and Static Electricity:
- Press 'H' anywhere to pull up a keyboard help dialog
- 'Tab' should navigate to the next interactive element
- 'Shift + Tab' should navigate to the previous interactive element
- 'Enter or Spacebar' to press buttons and toggles
- Press 'Enter' or 'Spacebar' to pick up a balloon
- Once a balloon is picked up, it can be dragged with the 'WASD' keys

Forces and Motion: Basics
- 'Tab' should navigate to the next interactive element
- 'Shift + Tab' should navigate to the previous interactive element
- 'Enter or Spacebar' to press buttons and toggle switches
- 'Spacebar' toggle checkboxes
- Press 'Enter' or 'Spacebar' to enter a group of pullers
- Press 'Escape' to leave a group of pullers, 'Tab' to leave group and go to next element
- If in group, use 'Arrow' keys to choose which puller you wish to select
- Press 'Enter' or 'Spacebar' to select puller and move to knot selection
- Use 'Arrow' keys to choose between different knots
- Press 'Enter' to place puller on a knot

Capacitor Lab: Basics
- 'Tab' should navigate to the next interactive element
- 'Shift + Tab' should navigate to the previous interactive element
- 'Enter or Spacebar' to press buttons and toggle switches
- 'Spacebar' toggle checkboxes
- Press 'Enter' to enter into circuit elements, 'Escape' to exit circuit elements
- Use 'Arrow' keys to drag arrows to change capacitor geometry

**Comment by phet-steele** [comment]
@jessegreenberg I'd say testing is done. Awaiting fixes!
