### ISSUE TITLE
Upload new Donation Video to YouTube

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#568]
@arnabp we would like to upload the following video to youtube (probably grab the high res version)

https://www.hightail.com/download/ZWJWZ280NHZwaFNybHNUQw

It would also be great to caption voice over properly.

**Youtube Text**
Title: PhET for Every Classroom

Description: For over a decade, PhET has developed interactive simulations to help learning come alive. By converting our sims to HTML5, we make them seamlessly available across platforms and devices. Whether you have laptops, iPads, chromebooks, or BYOD you can now have PhET sims at your fingertips. 

By donating to PhET, you can support the continued development of our awesome HTML5 simulations, become part of our mission to advance STEM literacy worldwide, and transform the learning experiences of students everywhere.  

Be an HTML5 hero! Please donate today: https://phet.colorado.edu/en/donate

Tags: 
PhET,HTML5,iPad,Chromebook,STEM,Physics,Chemistry,Math,Crowdfunding,Interactive,
Simulation,Science,Biology,STEAM,EdTech,Education,Technology,Fundraising,Development,
Lab,BYOD,Game

**Comment by ariel-phet** [comment]
@oliver-phet also tagging you in this issue

**Comment by oliver-phet** [comment]
@ariel-phet Do we already have the caption text?

**Comment by ariel-phet** [comment]
At PhET, we believe everyone has the right to a great education.
For PhET, HTML5 is the key to delivering our interactive resources everywhere.
We also believe the best educational resources should always be free.
By supporting our mission, you can help us bring high quality interactive simulations to every classroom. Today, and tomorrow.
Be an HTML5 hero. Please donate today.

**Comment by oliver-phet** [comment]
Video is up and captioned here: https://youtu.be/zsTFNkVnbOY

**Comment by ariel-phet** [comment]
Excellent! Closing
