### ISSUE TITLE
Make donate link in donation video clickable 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#569]
Hey @oliver-phet, I think it would be a nice touch if in the ending screen of the donation video the donation link were clickable. 

Do you think you or @arnabp could make that happen?

**Comment by oliver-phet** [comment]
I don't believe youtube allows links to other sites. @arnabp do you know if there is a way?

**Comment by oliver-phet** [comment]
Figured it out. Should be live now.

**Comment by ariel-phet** [comment]
Looks good, thanks!!
