### ISSUE TITLE
Dev test: Least Squares Regression 1.1.0-dev.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#570]
Before we go through a full RC process, it would be good to verify that the following issues have been fixed in Least Squares: Regression:

- [x] https://github.com/phetsims/least-squares-regression/issues/61
- [x] https://github.com/phetsims/least-squares-regression/issues/60
- [x] https://github.com/phetsims/least-squares-regression/issues/57
- [x] https://github.com/phetsims/least-squares-regression/issues/52

@phet-steele would you mind making sure that these issues are fixed?

Here is the dev version:
http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-dev.1/least-squares-regression_en.html

**Comment by phet-steele** [comment]
@jessegreenberg tested, ball is in your court now.

**Comment by jessegreenberg** [comment]
Thanks for the test and verification!
