### ISSUE TITLE
Create new email address - phet-licensing@colorado.edu

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#573]
@oliver-phet - Could you please help create this address and make sure its documented and forwarded correctly?  This was requested as part of the phet-io website partnerships page, see the comment in the powerpoint file in phetsims/phet-io-website#53

@ariel-phet Can you please comment on priority?

**Comment by oliver-phet** [comment]
Request sent to OIT.

**Comment by oliver-phet** [comment]
This is completed.
