### ISSUE TITLE
Formatting set of 2-page docs - Need by April 14th

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#574]
I have seven 2-page documents that need to be formatted the same way. I will have more over the course of this week, for a total of 18-20 2-page documents. Most are in the correct format or close.

**Comment by ariel-phet** [comment]
@emily-phet are these written or word or what?

**Comment by emily-phet** [comment]
@ariel-phet: some are in Word, others are PDF.

**Comment by ariel-phet** [comment]
@arouinfar do you think you will be available to help out with this work?

**Comment by arouinfar** [comment]
I can work on this @ariel-phet.

@emily-phet can you please send me the documents and the formatting guidelines?

**Comment by arouinfar** [comment]
@emily-phet can you please send me the relevant information so I can get started on this?

**Comment by arouinfar** [comment]
I've formatted the documents and have sent them off to @emily-phet for review. I'll self-assign this issue for now. Once @emily-phet approves them, I'll close this issue.
