### ISSUE TITLE
Dev test: Capacitor Lab: Basics

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#575]
Capacitor Lab: Basics is ready for some dev testing.  Here is the link to a deployed dev version:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.16/capacitor-lab-basics_en.html

As part of this dev test, please test the simulation on the following platforms and create issues for any problems that you find:

 - [x] iPad2/Safari
 - [x] Win/Edge
 - [x] Win/Chrome
 - [x] OS X/Safari

Thanks!

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG @bryo5363  please make this a high testing priority

@jessegreenberg - please note that @phet-steele will be away at the NCTM conference with us most of this week so testing will be mainly dependent on other QA team availability

**Comment by BryceAG** [comment]
Testing Win Chrome

**Comment by arouinfar** [comment]
Testing Mac/Safari

**Comment by brroberts1231** [comment]
Tested iPad 2 safari

**Comment by ariel-phet** [comment]
Looks like dev testing is complete, assigning back to @andrewadare to address open issues

**Comment by ariel-phet** [comment]
@andrewadare feel free to close this issue...some people like to keep open since open issues are all referenced here, but your choice
