### ISSUE TITLE
Poster/Flyer Printing

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#582]
Can someone print the following for me - by 2pm tomorrow (Tuesday 4/26):

- a conference poster (I can send the PDF tomorrow)
- 25 Accessibility flyers

**Comment by ariel-phet** [comment]
@phet-steele should be able to handle this tomorrow. @phet-steele let me know if that will be an issue.

**Comment by phet-steele** [comment]
@emily-phet I'll do it. I get in to the office at 9, so I'll start then or as soon as the poster is sent.

**Comment by phet-steele** [comment]
@emily-phet is the flyer file ready? I can do those today/

**Comment by phet-steele** [comment]
@emily-phet oh wait they probably already exist. Are they somewhere in google drive?

**Comment by emily-phet** [comment]
@phet-steele - Great! The flyer is an older one, I'll send it to you in an email. The poster I'm finishing up this evening. I'll send you the PDF file and the final dimensions tonight so it's ready for you in the morning. Thanks!

**Comment by emily-phet** [comment]
@phet-steele - Just wanted to check in. I emailed you the flyer file and the poster pdf. Let me know if you've had any issues with them. I should be in the office around 2:30-ish to pick them up. Thanks!

**Comment by phet-steele** [comment]
@emily-phet, I'm currently standing next to the printer

**Comment by phet-steele** [comment]
@emily-phet, your items await your presence in your office.
