### ISSUE TITLE
dev test Under Pressure v1.1.0-dev.5

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#585]
A translatable version of Under Pressure is nearly ready for publication.  Since there have been a lot of internal changes and cleanup, we should do a round of dev testing before creating the release candidate branch and starting the RC process. 

**Link to dev version:**
 http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.5/under-pressure_en.html

**NOTE**
 Any and all issues reported should be clearly identified in the GitHub issue description as either being new since version 1.0.0 (the version that is currently live on the web site) or having already been present in that version.

**Dev Test Platforms**
- [x] iPad 2 iOS 9.3.1
- [x] Mac Safari
- [x] Win Chrome
- [x] Win Edge

**The following tests should be performed as part of this testing**

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG @bryo5363 please make this a high testing priority (and note any platform your are testing)

**Comment by ariel-phet** [comment]
@aadish and @jbphet I tested on Win 7 Chrome and found some minor issues

Also tested all physics and verified everything is correct (pressure at depth, unit conversions, pressures with atmosphere off, etc.)

**Comment by brroberts1231** [comment]
Testing on Mac Safari

**Comment by phet-steele** [comment]
Handling Edge.

**Comment by phet-steele** [comment]
Working on iPad, stay tuned.

**Comment by phet-steele** [comment]
Done

**Comment by aadish** [comment]
thanks for testing this, closing it
