### ISSUE TITLE
User reported issue: embedding in Canvas

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#586]
Hi,
 
I’m trying to run the PHET simulations on a CANVAS page and they always seems to need refreshing a few times to get them to
work.
 
 
Is this a known problem and is there a way to fix it?
 
 
For example, the embed code for vectors, I used was:
 
`<iframe src="https://phet.colorado.edu/sims/vector-addition/vector-addition_en.html" width="600" height="300" allowfullscreen="allowfullscreen"></iframe>` 
 
 
Thanks

**Comment by oliver-phet** [comment]
Developers - any ideas on this issue?

**Comment by ariel-phet** [comment]
My guess is it has to do with Vector Addition being a flash sim. CANVAS is an LMS that apparently other people have embedded us in without issue (once we changed embed code to serve from //https)

@oliver-phet can you email back and see if the HTML5 sims embed seamlessly?

**Comment by oliver-phet** [comment]
Same problem reported when embedding HTML5 sims.

**Comment by ariel-phet** [comment]
The code he is saying he is using looks a little different from what we supply on our website. For instance we supply:

`<iframe src="https://phet.colorado.edu/sims/vector-addition/vector-addition_en.html" width="800" height="600" scrolling="no" allowfullscreen></iframe>`

and he has a piece that says 
`
allowfullscreen="allowfullscreen"`

**Comment by samreid** [comment]
The embed code in the issue description works perfectly for me in Chrome.

![image](https://cloud.githubusercontent.com/assets/679486/15052449/fd0bc90a-12ba-11e6-9695-8309ef2fde24.png)

I only had to refresh once.

**Comment by ariel-phet** [comment]
@oliver-phet please also inquire as to browser being used 

Potentially have the user send us the link for what he is doing? Or open the web browser console and let us know any errors showing up?

**Comment by oliver-phet** [comment]
I was finally able to reproduce this problem. Console screenshot:
<img width="1440" alt="screen shot 2016-05-06 at 12 49 33 pm" src="https://cloud.githubusercontent.com/assets/5090275/15083175/084ebdbc-1389-11e6-8cd9-e48d4b3be3ea.png">

"637energy-skate-park-basics_en.html:586 Uncaught TypeError: Cannot read property 'width' of undefined"

Code used:
<iframe src="https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html" width="800" height="600" allowfullscreen="allowfullscreen"></iframe>

**Comment by oliver-phet** [comment]
It appears code should be:
`<iframe src="https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html" width="800" height="600" scrolling="no" allowfullscreen></iframe>`

Email to user sent to see if this fixes the issue.

**Comment by oliver-phet** [comment]
Reply from user: 

> Unfortunately, for some reason  the html editor in canvas won't allow this change.  It auto deletes the "no scrolling" part when I save .

Any ideas on a fix?

Browser console output:
<img width="774" alt="screen shot 2016-05-09 at 10 13 41 am" src="https://cloud.githubusercontent.com/assets/5090275/15119582/cc2ea494-15ce-11e6-986d-908d269cda96.png">

**Comment by ariel-phet** [comment]
@oliver-phet can you also ask this user to email Canvas support and see if they have any suggestions?

**Comment by ariel-phet** [comment]
and what browser are they using? have they tried Chrome?

**Comment by oliver-phet** [comment]
Browser is Chrome. As mentioned above I was also able to reproduce the issue on Chrome. I'll ask user to contact Canvas support.

**Comment by ariel-phet** [comment]
@oliver-phet did we ever get word back on this issue?

**Comment by ariel-phet** [comment]
@oliver-phet pinging to see if we can close this issue

**Comment by oliver-phet** [comment]
Haven't heard back from the user. Closing for now.
