### ISSUE TITLE
RC Test: Area Builder 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#588]
Area Builder 1.1.0-rc.1 is ready for RC testing.

Link to sim: http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.0-rc.1/area-builder_en.html

Link to iFrame: http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.0-rc.1/area-builder_en-iframe.html

Test Matrix: https://docs.google.com/spreadsheets/d/1FQLci5g_LzLhmb7YVdZBpiKhc3dgbop_mcviwKaiVl4/edit#gid=1712820847

Please do a full RC test for this version. This is the first translatable version of this simulation, and a number of fixes were made to handle long strings.  Other fixes were also made that touched important portions of the code, so thorough testing is needed.

Please verify the following issues are resolved and, if so, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/area-builder/issues/88
- [x] https://github.com/phetsims/area-builder/issues/87
- [x] https://github.com/phetsims/area-builder/issues/86
- [x] https://github.com/phetsims/area-builder/issues/85
- [x] https://github.com/phetsims/area-builder/issues/80
- [x] https://github.com/phetsims/area-builder/issues/69
- [x] https://github.com/phetsims/area-builder/issues/68

Please also test and see if you can duplicate this issue (a potential fix has been added, but we were unable to duplicate the issue, so it's hard to know if it has really been addressed):

- [x] https://github.com/phetsims/area-builder/issues/90

If any new issues are found, please see if the issue also exists on the currently published version and include this information in the issue description.

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG @bryo5363 please make this the next top testing priority after #587

**Comment by ariel-phet** [comment]
Bumping to top priority

**Comment by alynne-phet** [comment]
@ariel-phet @jbphet Testing matrix is complete.

**Comment by ariel-phet** [comment]
Excellent! :birthday: 

@jbphet back to you to move to quick RC-2 and redeploy!

**Comment by jbphet** [comment]
Thanks for the testing.  I'll close this issue and move forward with RC2
