### ISSUE TITLE
Function Builder: preliminary testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#589]
We're at a point where some preliminary testing of Function Builder would be a good idea, as a sanity check.  I'd like to have some of @phet-steele's time to do this.

Here's the dev version to be tested:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html

There is no test matrix. If you find anything, create GitHub issues. Please link any issues that you create to this issue.

The main things that I'm interested in are:
• Are there issues on Edge? This sim has not been tested on Edge yet.
• Are there multi-touch issues? Test on iPad, you should be able to do everything simultaneously.
• Are there any situations where performance is unacceptable (or could be improved) on iPad2?

Sim-specific query parameters that you may find useful when testing:
• `populateOutput` - puts 1 of each card in the output carousel
• `slow` - reduces animation speed to 25% of normal, useful for testing multitouch

Features that are not implemented or have known issues, please skip these:
• Reset All button, all screens
• Contents of the "drawers" that slide out of the builder, all screens
• Mystery screen

Terminology, useful when describing things in GitHub issues:
• builder - the apparatus in the center of the screen
• slots - places where you can drop functions in the builder
• input carousel - vertical carousel on the left
• output carousel - vertical carousel on the right
• cards - the things in the input and output carousel, that you drag through the builder
• function carousel - horizontal carousel at bottom
• functions - the things in the functions carousel, that you drag into slots in the builder
• drawers - things that slide out of the top & bottom of the builder, to reveal additional representations

Let me know if you have any questions about how the sim is supposed to work. You can contact me through email or Skype (preferred), or ask questions via GitHub issues labeled with "type:question". You can also consult the [Function Builder HTML5 design document](https://docs.google.com/document/d/1S6pkoJODPNZFtkLaSmk2MKzh2aAH6lk30pqCTxTX8z8/edit).

**Comment by ariel-phet** [comment]
@phet-steele this would be good to tackle after current high priority QA tests are finished, or if you just need to bang on a different sim for awhile :smiling_imp:

**Comment by phet-steele** [comment]
@pixelzoom yesterday was a pretty fullfillin

**Comment by pixelzoom** [comment]
Thanks you @phet-steele.

**Comment by pixelzoom** [comment]
Closing this issue, testing completed.
