### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/tasks#590]
Test device: Personal MacBook Pro

Operating System: OS X 10.11.4

Browser: Chrome

Problem description: Photons disappear when changing color and will not reappear when the flashlight is turned on and off. Relate task to phetsims/tasks/issues/553

Steps to reproduce:
1. Go to single bulb screen
2. Click on photon view
3. Change colors of the photon rapidly

Severity: High, major feature not working properly

Screenshots:
![screen shot 2016-05-10 at 11 59 53 am](https://cloud.githubusercontent.com/assets/19288972/15156994/dbef88d4-16a6-11e6-8223-376e776ab314.png)

Troubleshooting information (do not edit):
Name: ‪Color Vision‬
URL: http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.3/color-vision_en.html
Version: 1.1.3 2016-04-05 19:43:02 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Language: en-US
Window: 1270x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"60213ff7","branch":"HEAD"},"babel":{"sha":"d0dcba98","branch":"master"},"brand":{"sha":"f4905d94","branch":"HEAD"},"chipper":{"sha":"b296e642","branch":"HEAD"},"color-vision":{"sha":"e1b0cd0c","branch":"1.1"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"dc0f9d1c","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"c1d016e7","branch":"HEAD"},"scenery":{"sha":"6bd54e23","branch":"HEAD"},"scenery-phet":{"sha":"f995e3ee","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2f236352","branch":"HEAD"},"tandem":{"sha":"d0be78dd","branch":"HEAD"}}

**Comment by alynne-phet** [comment]
@phet-steele Can you check this issue out?

**Comment by alynne-phet** [comment]
> @phet-steele Can you check this issue out?

**Comment by phet-steele** [comment]
@alynne-phet it's fixed!

**Comment by alynne-phet** [comment]
Thanks!
