### ISSUE TITLE
RC Test: Under Pressure 1.1.0-rc.1

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#591]
Under Pressure 1.1.0-rc.1 is ready for RC testing.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-rc.1/under-pressure_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-rc.1/under-pressure_en-iframe.html

**Test Matrix:** https://docs.google.com/spreadsheets/d/1ReiXqlgvJUG4GHNtZ4wAP_nZwhXLOq9zaXnaGChNvNo/edit?ts=57323494#gid=544857704

Please do a full RC test for this version. This is the first translatable version of this simulation, and a number of fixes were made to handle long strings.  Other fixes were also made that touched important portions of the code, so thorough testing is needed.

**Issues to Verify**
Please verify the following issues are resolved and, if so, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/under-pressure/issues/141
- [x] https://github.com/phetsims/under-pressure/issues/140
- [x] https://github.com/phetsims/under-pressure/issues/139
- [x] https://github.com/phetsims/under-pressure/issues/136
- [x] https://github.com/phetsims/under-pressure/issues/135
- [x] https://github.com/phetsims/under-pressure/issues/134
- [x] https://github.com/phetsims/under-pressure/issues/133
- [x] https://github.com/phetsims/under-pressure/issues/132
- [x] https://github.com/phetsims/under-pressure/issues/130
- [x] https://github.com/phetsims/under-pressure/issues/138
- [x] https://github.com/phetsims/under-pressure/issues/137

**Please also verify**
Although the following were checked during dev testing, it would be good to check them over

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test

If any new issues are found, please see if the issue also exists on the currently published version and include this information in the issue description.

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG @alynne-phet  please make this the next top testing priority after #588

**Comment by phet-steele** [comment]
@aadish @ariel-phet all done!

**Comment by aadish** [comment]
Thanks @phet-steele  and QA team, issues have been noted and will roll out a new RC resolving the issues
