### ISSUE TITLE
Testing demos on phet-io website

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#592]
@kathy-phet requested that the demos on the phet-io website get fully tested as she has seen a number of bugs on iPad 

Please test the following available at https://phet-io.colorado.edu/io-solutions/:

- [x] Virtual Laboratory
- [x] Online Homework
- [x] eTextbook

Report any issues in https://github.com/phetsims/phet-io-website and please reference this test task as usual

**Comment by phet-steele** [comment]
@ariel-phet @kathy-phet @samreid I'm pretty confident in saying that any errors I've seen are caused by phetsims/phet-io/issues/420

**Comment by ariel-phet** [comment]
Thanks @phet-steele, @samreid feel free to close

**Comment by samreid** [comment]
Since issues are tracked elsewhere, I'll close this one.  Thanks @phet-steele!
