### ISSUE TITLE
Preliminary interviews on Function Builder

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#594]
Interviews scheduled with 2 MS students on 5/16/2016.  Will use latest dev version of sim for interviews:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.28/function-builder_en.html

@pixelzoom noted the following issues with sim:

Known issues on all platforms, try to avoid these:
• Reset All applies only to functions in the builder, and cards in the output carousel.  Functions and cards anywhere else will not be properly reset.
• The “table drawer” feature is not implemented (Numbers and Equations screens)
• The “equation drawer” feature is not implemented (Equations screen)
• In the Equations screen, if you drag ‘x’ through the builder, the equation shown in the output carousel is incorrect.
• Mystery screen is blank, not implemented yet

Will interview sim on Dell laptop using Chrome.

**Comment by amyh-phet** [comment]
@pixelzoom and @ariel-phet   Below is a short summary of things I noticed while conducting interviews yesterday.  Both students were 7th graders and were in Algebra 1 this year.

1)  Flow and interactions seemed good.  Both students quickly figured out how to place functions on the builder and drag input cards to the slot and into the builder.   Both students also discovered that cards in the output carousel could be dragged to slot on right side of builder and would move through builder to input carousel.

2) One student found non-invertable functions on the Patterns screen, the other student did not due to bug reported by @phet-steele [https://github.com/phetsims/function-builder/issues/39].

3) One student managed to place several cards in the builder when using the "see through" feature, including stacking cards on top of each other in the same "see through" slot.  In speaking with @ariel-phet, it sounds like this has come up in design meetings previously.  The student was confused when he did this as he lost track of what cards he had placed in the builder, especially when the cards stacked. This seemed especially confusing in the Numbers and Equations screen as reading the function and outputs from left to right no longer made sense. Based on what I noticed from student interactions, it would be best if only one card was allowed in the builder at a time.

4) On the Patterns screen, both students realized that the icons on the functions gave hints as to what the functions did to each image. This was helpful to an extent, but led the students to analyze each icon. Neither student understood the identity function, and they mentioned they thought the function might make the image on the input card brighter. Neither student connected the soup can with Warhol, but one student mentioned Picasso and both students were able to describe what the function did despite not being able to use the term Warhol.  Both students liked the Warhol effect. One student attempted to ascribe meaning to the shapes behind the letters on the mystery functions.  One thing that we might need to think about is how much we want the function icons to give cues to students.

5) Both students spent time placing functions on the builder, making predictions, and then testing their predictions.  They were especially engaged in this on the Patterns and Numbers screens.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/function-builder/issues/44 created to track concern in observation (3) above.

**Comment by pixelzoom** [comment]
#45 and #46 created to address observations in (4) above about meaning associated with function icons.

**Comment by pixelzoom** [comment]
Issues have been created to address all concerns related to the interview observations. @amyh-phet feel free to close this issue, unless there's more to be done here.

**Comment by amanda-phet** [comment]
Thank you for conducting these interviews, @amyh-phet !

**Comment by amyh-phet** [comment]
@amanda-phet    Happy to help!
