### ISSUE TITLE
RC Test: Isotopes And Atomic Mass 1.0.0-rc.1

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#595]
Isotopes and Atomic Mass 1.0.0-rc.1 is ready for RC testing. It is the first RC for the HTML 5 version of this simulation

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.1/isotopes-and-atomic-mass_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.1/isotopes-and-atomic-mass_en-iframe.html

**Test Matrix:** https://docs.google.com/spreadsheets/d/1nrGez8Z4HXelhgDXNkfVAd_qxWiC5z0nnG3a8Dzxwlc/edit?ts=573a195e#gid=2

Please do a full RC test for this version. 
**Issues to Verify**
Please verify the following issues are resolved and, if so, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/53
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/51
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/49
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/40
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/39
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/33

**Please also verify**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test

If any new issues are found, please note them in the issues

**Comment by ariel-phet** [comment]
@brroberts1231 @alynne-phet @elisemorgan @phet-steele please make this top priority along with #584

**Comment by brroberts1231** [comment]
Matrix complete.

**Comment by ariel-phet** [comment]
@aadish assigning back to you

**Comment by aadish** [comment]
thanks for testing this issues have been noted and will be rolling out the next RC candidate, closing this
