### ISSUE TITLE
RC Test: Under Pressure 1.1.0-rc.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#596]
Under Pressure 1.1.0-rc.2 is ready for release candidate testing.

Link to sim: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-rc.2/under-pressure_en.html

Link to iframe: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-rc.2/under-pressure_en-iframe.html

There were only a few issues identified during the testing of 1.1.0-rc.1, and those issues should be addressed in this release, so a full re-test is not required.  My recommendation is to perform basic sanity testing on the primary supported platforms, and then verify that the following issues are addressed, closing them if so, updating them if not:

- [x] Win7 IE11 Artifacts https://github.com/phetsims/under-pressure/issues/142
- [x] Update Credits https://github.com/phetsims/under-pressure/issues/132
- [x] iPad performance on weight screen https://github.com/phetsims/under-pressure/issues/86

**Comment by ariel-phet** [comment]
@phet-steele can you bang this out today? if possible would be great to finish off S2015R!!

**Comment by phet-steele** [comment]
@aadish @ariel-phet Tested on Win 7 IE11, Win 10 Chrome, OSX 10.11.5 Safari, and iPad2 iOS 9.3.2. Molto bene.

**Comment by ariel-phet** [comment]
Alright...lets publish!

**Comment by aadish** [comment]
Thanks for the testing
Deployed and it is live :+1:
