### ISSUE TITLE
RC Test: Isotopes And Atomic Mass 1.0.0-rc.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#599]
Isotopes and Atomic Mass 1.0.0-rc.2 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.2/isotopes-and-atomic-mass_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.2/isotopes-and-atomic-mass_en-iframe.html)**

There were only a few issues identified during the testing of 1.0.0-rc.1, and those issues should be addressed in this release, so a full re-test is not required. My recommendation is to perform basic sanity testing on the primary supported platforms and verify the issues.

**Issues to Verify** 
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/74
- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/73

If any new issues are found, please note them in https://github.com/phetsims/isotopes-and-atomic-mass/issues and reference this issue.

**Comment by brroberts1231** [comment]
@aadish @ariel-phet Both issues resolved. Looks good to go.

**Comment by phet-steele** [comment]
Tested on all Win browsers, iPad 2 iOS 9.3.2, and OSX 10.11.5

**Comment by ariel-phet** [comment]
Sim published (though not yet visible). Closing
