### ISSUE TITLE
RC Test: Beer's Law Lab 1.4.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#600]
Beer's Law Lab 1.4.0 is a minor release that will pick up the following changes:

https://github.com/phetsims/beers-law-lab/issues/169 (add solute Sodium Chloride)
https://github.com/phetsims/beers-law-lab/issues/146 (change "fixed" string key to "preset")

@ariel-phet When ready to proceed with RC testing, please assign this issue back to me, and I'll flesh it out using the RC test template.

Mentioning @samreid in case this work conflicts with PhET-iO goals.

Note that Concentration 1.3.0 will be tested and released simultaneously. See https://github.com/phetsims/tasks/issues/602.

**Comment by ariel-phet** [comment]
@pixelzoom I think I can assign for testing starting 5/23/2016

So sending back your way.

**Comment by pixelzoom** [comment]
Beer's Law Lab 1.4.0-rc.1 is ready for RC testing.  This release candidate requires a full regression test.

**Test Matrix**
Links to sim and iframe test are in the test matrix.
https://docs.google.com/spreadsheets/d/1opT_0el4D08ezqlqrb4dgdYreiPRfjAG5gWRnADOyrk/edit#gid=2102595442)

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [ ] https://github.com/phetsims/beers-law-lab/issues/169
- [ ] https://github.com/phetsims/beers-law-lab/issues/146

**Please also verify**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test

If any new issues are found, please note them in https://github.com/phetsims/beers-law-lab/issues and reference this issue.

**Comment by pixelzoom** [comment]
Beer's Law Lab 1.4.0-rc.1 is ready for RC testing. This release candidate requires a full regression test.

**Test Matrix**
Links to the sim and iframe test are in the test matrix. See:
(https://docs.google.com/spreadsheets/d/1nrGez8Z4HXelhgDXNkfVAd_qxWiC5z0nnG3a8Dzxwlc/edit?ts=573a195e#gid=2)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [ ] https://github.com/phetsims/beers-law-lab/issues/169
- [ ] https://github.com/phetsims/beers-law-lab/issues/146

**Please also verify**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test

If any new issues are found, please note them in https://github.com/phetsims/beers-law-lab/issues and reference this issue.

**Comment by ariel-phet** [comment]
@alynne-phet @brroberts1231 @elisemorgan @phet-steele please move forward on this test (currently at medium priority)

**Comment by alynne-phet** [comment]
@pixelzoom The matrix is complete!

**Comment by pixelzoom** [comment]
Another RC will be required.
