### ISSUE TITLE
Artwork for Unit Rates

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#601]
Development on Unit Rates is progressing, and will need some graphic arts work from @mariahmaephet.  The sim has two contexts -- shopping and racing (see the <a href="https://docs.google.com/document/d/1D4FBgMwvvQvo_jITN5a675KWMxseWiMZ-oN0rd7nG9A/edit?usp=sharing">design doc</a> for more details). The Shopping screen is currently being developed, so artwork for this screen should be prioritized over the Racing screen. 

<b>Shopping Screen</b>
The Shopping Screen has three scenes -- fruit, veggies, and candy. In all of these scenes there will be semi-transparent bags sitting on a shelf at the bottom of the screen. Once a bag is placed on the scale/register, the fruit bags will open up, but veggies and candy stay in the bag. Here are a few reference screenshots. 

![image](https://cloud.githubusercontent.com/assets/8419308/15401783/3c157ce2-1dae-11e6-9aca-2f4864281bbd.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15401804/5ae3b68e-1dae-11e6-8c01-37f483914da3.png)

Artwork needed for the Shopping Screen:
- [x] Shelf for bags to sit on -- wooden with some depth (match perspective of scale), but not too much detail
- [x] Single lemon
- [x] Single orange
- [x] Single pear (green)
- [x] Bag of 5 apples (please use the apple artwork from #468)
- [x] Bag of 5 lemons
- [x] Bag of 5 oranges
- [x] Bag of 5 pears
- [x] Single carrot
- [x] Single tomato
- [x] Single potato
- [x] Single cucumber
- [x] Bag of 4 carrots
- [x] Bag of 4 tomatoes
- [x] Bag of 3 potatoes
- [x] Bag of 3 cucumbers
- [x] Single piece of red candy
- [x] Single piece of green candy
- [x] Single piece of blue candy
- [x] Single piece of purple candy
- [x] Bag of red candy
- [x] Bag of green candy
- [x] Bag of blue candy
- [x] Bag of purple candy

Each color of candy will have a different silhouette (e.g. gumdrops, jellybeans, taffy). We've found four colors that work together nicely in colorblind preview mode which should be the dominant shade of the candy. 
* Red: ef3c24
* Green: 00ff01
* Blue: 5ab3d3
* Purple: b452cd

<b>Racing Screen</b>
 - [x] Single, monochromatic car silhouette with sporty feel. The car's color should be easy to change in Illustrator, and there needs to be room to overlay a number on the side. 

Here's an example of what I'm looking for in terms of car orientation.
![image](https://cloud.githubusercontent.com/assets/8419308/16601131/086923dc-42c8-11e6-9cff-a53405b8a0a2.png)

Assigning this issue to @ariel-phet for prioritization. 

@mariahmaephet we should also set a time to chat about the Shopping screen artwork.

**Comment by ariel-phet** [comment]
@mariahmaephet lots of fun artwork in this upcoming project! Assigning to you to arrange a time with @arouinfar

**Comment by arouinfar** [comment]
I emailed @mariahmaephet to set up a meeting time. Typically my schedule is pretty open Mondays, Tuesdays, and Fridays.

**Comment by mariahmaephet** [comment]
@arouinfar, are you free tomorrow (friday) or next week to meet?

**Comment by arouinfar** [comment]
@mariahmaephet I'm going to be out of the office tomorrow, but I'll be available 11:00-1:00 and 3:00-5:00 next Tuesday, and all day Wednesday.

**Comment by mariahmaephet** [comment]
@arouinfar how about 3pm on tuesday?

**Comment by arouinfar** [comment]
Sounds good @mariahmaephe! Let's meet in Duane F915.

**Comment by arouinfar** [comment]
I met with @mariahmaephet this afternoon and made a few changes to the descriptions and list in the original post.

For all produce and candy, we'll need artwork for a single item as well as a bag of items. The bag will be a transparent sack that has some structure, similar to this:
![image](https://cloud.githubusercontent.com/assets/8419308/16601040/7b5e2ff0-42c7-11e6-9b90-76e01b03d68c.png)

**Comment by mariahmaephet** [comment]
<img width="505" alt="screen shot 2016-07-13 at 12 01 10 pm" src="https://cloud.githubusercontent.com/assets/11527557/16859917/37c1e298-49f0-11e6-86fa-b475b041800d.png">

**Comment by mariahmaephet** [comment]
and these aren't the right colors, but what do you think about the design?
<img width="561" alt="screen shot 2016-07-14 at 6 48 17 pm" src="https://cloud.githubusercontent.com/assets/11527557/16860266/8bf7d1c6-49f3-11e6-8f7d-eb8aef22ca46.png">

**Comment by mariahmaephet** [comment]
<img width="829" alt="screen shot 2016-07-14 at 7 10 20 pm" src="https://cloud.githubusercontent.com/assets/11527557/16860568/9f6ad598-49f6-11e6-9c70-0a33085b4326.png">

**Comment by arouinfar** [comment]
@mariahmaephet looks great! Can you put the .ai files for the cars and fruits/veg in your Google drive folder? I also like the look of the candies, particularly the top row and the gumdrop.

**Comment by mariahmaephet** [comment]
@arouinfar I put all of them in the drive. I might keep tweaking them a little bit if you're able to replace them later?

**Comment by arouinfar** [comment]
Thanks @mariahmaephet! Have you made any progress with the candy or bag artwork?

**Comment by arouinfar** [comment]
@mariahmaephet any updates? So far, things are looking great. I've checked off the items from the list that have been completed, but there are still quite a few to go.

**Comment by mariahmaephet** [comment]
@arouinfar @ariel-phet I currently don't have wifi so I'm just doing this over my phone--I should be able to upload actual files tonight or tomorrow. 

Let me know your thoughts on the bags. the candies still have arbitrary colors while I play around with them, but since the plastic changes their color slightly do you want the final colors to be the ones you asked for or is it alright if they're slightly altered by the grey when inside the bags?

![image](https://cloud.githubusercontent.com/assets/11527557/17457838/08779df0-5bd1-11e6-8ef6-b181f351ffbd.jpeg)
![image](https://cloud.githubusercontent.com/assets/11527557/17457839/087fb774-5bd1-11e6-90ba-20bcd1540f25.jpeg)
![image](https://cloud.githubusercontent.com/assets/11527557/17457840/0881bcf4-5bd1-11e6-85b6-0373d841f187.jpeg)
![image](https://cloud.githubusercontent.com/assets/11527557/17457841/0885626e-5bd1-11e6-8589-fcf15ced9034.jpeg)

**Comment by arouinfar** [comment]
@mariahmaephet these all look great!

We'll want the ribbon on the candy bags, since it will help cue students that the bags will remain closed when placed on the scale. Please go ahead and switch the medium shade of the candies to the colors I gave you, and then adjust the shading accordingly. Don't worry about the bag slightly altering the colors, since they will most likely remain distinguishable during colorblind preview mode.

I prefer the bag on the right for the produce, because it feels more consistent with the candy bags.   It will also be helpful from a development perspective if you can keep the same dimension on all of the produce bags -- just replace/rearrange the artwork inside.

Please go ahead and put the artwork in your Drive folder whenever you get things ready.

**Comment by arouinfar** [comment]
@mariahmaephet can you give an estimate of when you'll be able to upload the .ai files to Drive?

**Comment by mariahmaephet** [comment]
@arouinfar They should be uploading right now. Do you want a ribbon on the produce bags as well? 

<img width="1044" alt="screen shot 2016-08-11 at 9 18 37 am" src="https://cloud.githubusercontent.com/assets/11527557/17593882/9f1321ae-5fa4-11e6-8815-21a952cfe46e.png">
<img width="672" alt="screen shot 2016-08-11 at 9 18 56 am" src="https://cloud.githubusercontent.com/assets/11527557/17593884/9fe84488-5fa4-11e6-8de4-81a1f64f28d2.png">

**Comment by arouinfar** [comment]
@mariahmaephet this all looks great!! We may eventually decide to add a ribbon to the vegetable bags, since they don't open up in the sim, but I can take care of that on my end.

Looks like the only artwork left in this issue is the shelf or bags to sit on.  We're looking for wooden shelf with a little depth that matches the perspective of the scale. I think a lighter wood like pine would look nice here, and the grain detail can be pretty subtle.

**Comment by mariahmaephet** [comment]
@arouinfar How about this? I have it added to the fruits and veggies file in my drive
<img width="476" alt="screen shot 2016-08-28 at 1 29 34 pm" src="https://cloud.githubusercontent.com/assets/11527557/18035401/82f5ad84-6d23-11e6-8397-4da278da9ccf.png">

**Comment by arouinfar** [comment]
@mariahmaephet thanks, the shelf looks great! I'm going to try it out in the mockup to see how it looks in context.

**Comment by arouinfar** [comment]
Here's the shelf in context:

![image](https://cloud.githubusercontent.com/assets/8419308/18139508/18fc04b6-6f6f-11e6-96c1-c00d5b44ec64.png)

Looks like I can go ahead and close this issue and send the shelf artwork off to @schmitzware.

Thanks again @mariahmaephet!!
