### ISSUE TITLE
RC Test: Concentration 1.3.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#602]
Related to https://github.com/phetsims/tasks/issues/600.  When publishing Beer's Law Lab 1.4.0, we'll also be publishing Concentration 1.3.0.   Since Concentration is a subset of Beer's Law Lab, Concentration will not require a full RC test matrix - we can do spot testing. 

@ariel-phet When ready to proceed with RC testing, please assign this issue back to me, and I'll flesh it out using the RC test template.

Mentioning @samreid in case this work conflicts with PhET-iO goals.

**Comment by ariel-phet** [comment]
Testing should be able to commence 5/23/2016

**Comment by pixelzoom** [comment]
Concentration 1.3.0-rc.1 is ready for RC testing, and requires only "spot testing".  This sim is a subset of Beer's Law Lab, and this release candidate is built with the same sources as Beer's Law Lab 1.4.0-rc.1 (see #600). So the two sims should be tested together. 

**Test Matrix**
Link to sim and iframe test are in the test matrix. See:
https://docs.google.com/spreadsheets/d/1ghqNXGEAK4sApVwFIHIyZLuNb5QjQO-FyZiQCjE5_ZM/edit#gid=1887244586

**Issues to Verify**
- [ ] https://github.com/phetsims/beers-law-lab/issues/169
- [ ] https://github.com/phetsims/beers-law-lab/issues/146

**Comment by ariel-phet** [comment]
@alynne-phet @brroberts1231 @elisemorgan @phet-steele please move forward on this test (currently at medium priority)

**Comment by alynne-phet** [comment]
@pixelzoom Matrix is complete

**Comment by pixelzoom** [comment]
Another RC will be required.
