### ISSUE TITLE
Test requirejs mode phet-io wrappers

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#603]
Now that the phet-io-require-2 branches have been merged to master, it would be great to test the requirejs (not built) version of these simulations, since the launch sequence has been changed significantly.  The built version was already tested by @phet-steele.

What would be best:
Test 1-2 wrappers each, sampling from Beer's Law Lab, Capacitor Lab: Basics and Faraday's Law (others not up-to speed yet), sampling from our supported platforms.  I say "sampling" because there is no need to test every wrapper for every sim on every platform, but as long as we try a wrapper from each sim at least once and hit all platforms once, that would be good.

Start at http://phettest.colorado.edu/phet-io/html/dev-wrappers.html and let me know if you have questions or problems arise.

Assigning to @ariel-phet for prioritization and delegation.

**Comment by ariel-phet** [comment]
@phet-steele probably do this before the phet-io website wrapper tests. Feel free to do yourself or delegate.

**Comment by phet-steele** [comment]
@samreid this has been given a solid effort, I'd say we are all done.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll continue in the referenced issues, closing.
