### ISSUE TITLE
Function Builder: preliminary interviews (iOS)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#604]
Time for some preliminary interviews on iOS. 

Use this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.37/function-builder_en.html

Please do NOT use an iPad2 for the interviews, due to https://github.com/phetsims/function-builder/issues/35.  Should be fine on later models, but you may want to test drive before the interviews, so that there are no surprise that disrupt/skew the interviews.

Known issues on all platforms, try to avoid these:
• Reset All is not fully functional.
• The “table drawer” feature is not implemented (Numbers and Equations screens)
• The “equation drawer”  feature is not implemented (Numbers and Equations screens)
• Mystery screen is blank, not implemented yet

Assigning to @amyh-phet. Please note interview observations in this issue.

**Comment by pixelzoom** [comment]
@amyh-phet I published a new dev version (1.0.0-dev.37) with changes requested at today's design meeting, and edited the above comment accordingly.  The changes related to your interview observations in https://github.com/phetsims/tasks/issues/594 are:

https://github.com/phetsims/function-builder/issues/45 (change mystery function icons)
https://github.com/phetsims/function-builder/issues/46 (change identify function icon)

**Comment by amyh-phet** [comment]
@pixelzoom   After interviewing on an iPad air with two students, here's what I noticed.

- No issues observed with the icons on the function cards in the Pattern screen.  Question marks seemed to indicated students should guess what the function would do.  Students still were confused by the output of the identity function (no change), but the icon was not misleading (e.g., students did not expect a different outcome based on the icon).

- Both students were right handed.  No occlusion issues were observed during the interviews.

- On the Equations screen, both students initially ended up changing the number on the function card the first time they tried to move the card onto the builder.  Both students quickly learned that they could move the function without changing the number by touching a different area on the function card. 

- Students intentionally used the number pickers to change function both when the function card was in the carousel and on the builder. 

- It seems to take students a while to realize the output carousel updates when they change a function.

**Comment by pixelzoom** [comment]
@amyh-phet Re:
> Students still were confused by the output of the identity function (no change), but the icon was not misleading (e.g., students did not expect a different outcome based on the icon).

Did the students eventually figure out the identity function? Eg, did they say anything like "what goes in is what comes out"?

**Comment by amyh-phet** [comment]
@pixelzoom 

Students realize the identity function doesn't change the image on the card.  One student though it might rotate the image "all the way around".  Others expressed that they realized no change happened, but weren't sure why.   I think this is function will be a great teaching point as students are expecting the image to change but it doesn't.

**Comment by pixelzoom** [comment]
Observation about identity function has been noted in #46.

Closing.
