### ISSUE TITLE
Poster Printing - by May 31st

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#605]
I have a poster that needs printing for the DRK-12 PI conference next week. Kathy will be taking my poster, along with her own, to DC. Can someone print my poster and leave it in Kathy's office by end of day Tuesday the 31st? (Ideally with a rubber band around it so it doesn't expand fully inside the tube)

Once someone is assigned, I can send along the pdf file.

**Comment by phet-steele** [comment]
Yes @emily-phet, please send it to me.

**Comment by phet-steele** [comment]
@emily-phet poster is printed and in Kathy's office.
