### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/tasks#606]
Test device: Lenovo W540 (Personal device)

Operating System: Windows 7

Browser: Chrome 51.0.2704.63 m

Problem description: I tried to find a bug and the problem is I couldn't find one. @alynne-phet  @phet-steele 

Steps to reproduce: 

1. Go to the concentration screen.
2. Click on anything
3. Notice you can't find any bugs

Severity: not severe at all 

Screenshots:
<img width="882" alt="test_issue_pic_1" src="https://cloud.githubusercontent.com/assets/7988696/15683620/8c731930-2720-11e6-82bb-227ddfc00433.PNG">

related to phetsims/tasks/issues/600

Troubleshooting information (do not edit):
Name: ‪Beer's Law Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-rc.1/beers-law-lab_en.html
Version: 1.4.0-rc.1 2016-05-23 15:41:35 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Language: en-US
Window: 1280x597
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9bf8f88c","branch":"master"},"babel":{"sha":"37077fff","branch":"master"},"beers-law-lab":{"sha":"27ef4131","branch":"1.4"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"22a9ffe2","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"3931eb76","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"d36b3155","branch":"master"},"scenery-phet":{"sha":"2b60b8e4","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"6f66368f","branch":"master"},"tandem":{"sha":"29f64233","branch":"master"}}

**Comment by phet-steele** [comment]
@andrea-phet good job finding this bug! It's caused because we have great developers!!!!!

**Comment by phet-steele** [comment]
@alynne-phet can you verify that this is fixed in master?

**Comment by phet-steele** [comment]
I mean @andrea-phet, you verify

**Comment by andrea-phet** [comment]
I'm reopening so I can reclose.

**Comment by andrea-phet** [comment]
Now closing it.
