### ISSUE TITLE
Getting Andrea started

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#607]
@ariel-phet @oliver-phet not in any specific order, just things that have been done and still need to be done:
- [x] GitHub email/account, join the organization
- [x] Enter info into the planning document (including Skype)
- [x] Go over GitHub workflow
- [x] Website account
- [x] Practice creating an issue
- [x] Introduce test-server
- [x] Introduce the website
- [x] Introduce PhET-iO
- [x] Acquainted her with the calendar
- [x] Picture for website
- [x] Access to phet@lists.colorado.edu
- [x] Share to google-group
- [x] Key
- [x] Finish all admin paperwork

**Comment by oliver-phet** [comment]
@andrea-phet You'll just need to activate your identikey, and update your W-4 and Direct Deposit information, then you'll be good to go!

**Comment by andrea-phet** [comment]
>  Finish all admin paperwork

I have my identikey and have successfully submitted a timesheet (and it was approved)!

**Comment by ariel-phet** [comment]
@phet-steele seems to be taking care of team page updates, so will leave this last checklist item for him

:cake:

**Comment by phet-steele** [comment]
:+1:, @andrea-phet you're all set
