### ISSUE TITLE
Dev Test for Plinko-Probability

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#608]
We are ready for a round of dev testing on plinko probability. In addition we would like you to keep an eye on performance.

Link to dev version:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.3/plinko-probability_en.html

Dev Test Platforms:

-  [x] iPad 2 iOS 9.3.1
-  [x] Win Chrome

The following tests should be performed as part of this testing
 showPointerAreas (touchArea=red, mouseArea=blue)
 Full screen test

Please create separate issue for any problems that you find.

**Comment by ariel-phet** [comment]
@phet-steele this should be at the top of the sim testing list...since there isn't any other sim testing currently :)

**Comment by ariel-phet** [comment]
Feel free to designate as appropriate

**Comment by alynne-phet** [comment]
I tested the iPad 2 iOS 9.3.1. The performance seems to be pretty slow

**Comment by phet-steele** [comment]
@veillette @ariel-phet testing here is done. It appears that master is an insane amount of commits ahead anyway 😄

**Comment by veillette** [comment]
We solved many issues and some performance bottlenecks. Before closing this issue I would like to know what kind of slowness on the iPad we are dealing with.   Is it janky due to garbage collection, or is it unresponsive to events, or something else?

**Comment by veillette** [comment]
@alynne-phet, can you chime in?

**Comment by alynne-phet** [comment]
@veillette The balls don't fall smoothly. Also, the erase button stays depressed after pushing it initially on the first screen. Most of the performance problems are because of gc and master has fixed many of these problems.

**Comment by veillette** [comment]
We made great progress regarding vector allocations which should greatly diminished the number of garbage collection events. Also the balls are now rendered as images so we don't end up paying the cost drawing radial gradients over and over.

**Comment by veillette** [comment]
Thanks, closing this issue. I'll open a ticket about the erase button
