### ISSUE TITLE
Dev Test: States of Matter 1.0.0-dev.6

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#609]
Dev release for states of matter is out 

Link to the simulation: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.6/states-of-matter_en.html

This dev release is aimed at seeing whether the performance is acceptable on iPad or not 

Other issues which are fixed and need to be tested are
- [x] Internationalization
- [x] Interaction Potential is too deep https://github.com/phetsims/states-of-matter/issues/60
- [x] Container Lid Movement https://github.com/phetsims/states-of-matter/issues/17
- [x] https://github.com/phetsims/atomic-interactions/issues/48
- [x] https://github.com/phetsims/atomic-interactions/issues/30

Many critical code changes have been made so any new issue is welcome and please report it

**Comment by ariel-phet** [comment]
@phet-steele this would be good to do at a similar priority to testing plinko. Especially since @aadish is only here for a few more days.

**Comment by phet-steele** [comment]
@aadish I believe this dev testing is complete.

**Comment by aadish** [comment]
Thanks @phet-steele and QA team for testing this. Issues have been noted and being worked upon. 
closing this issue.
