### ISSUE TITLE
PhET app recording

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#610]
@ariel-phet requested a short video to be made highlighting the use of the PhET app. This will be done before the end of the week probably.

**Comment by phet-steele** [comment]
Will need to wait until Monday for use of Leibniz.

**Comment by ariel-phet** [comment]
Looks like @kathy-phet might be in later today

**Comment by phet-steele** [comment]
@ariel-phet video made. Close if acceptable.

**Comment by ariel-phet** [comment]
Looks good, thanks @phet-steele !! :kissing_cat:
