### ISSUE TITLE
Dev Test: States of Matter 1.0.0-dev.7

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#611]
Dev 1.0.0-dev.6 release is out and includes fixes for the issues found in last dev release.

Link for the simulation: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.7/states-of-matter_en.html

It will be good to test and close these issues, to have a clean slate before some-one else starts on it.

Issues to test for

- [x] https://github.com/phetsims/states-of-matter/issues/128
- [x] https://github.com/phetsims/states-of-matter/issues/127
- [x] https://github.com/phetsims/states-of-matter/issues/126
- [x] https://github.com/phetsims/states-of-matter/issues/125
- [x] https://github.com/phetsims/states-of-matter/issues/123
- [x] https://github.com/phetsims/states-of-matter/issues/122
- [x] https://github.com/phetsims/states-of-matter/issues/120
- [x] https://github.com/phetsims/states-of-matter/issues/119
- [x] https://github.com/phetsims/states-of-matter/issues/118
- [x] https://github.com/phetsims/states-of-matter/issues/117
- [x] https://github.com/phetsims/states-of-matter/issues/60

**Comment by ariel-phet** [comment]
@phet-steele please assign any issues than cannot be closed to @jbphet

**Comment by ariel-phet** [comment]
bumping down to medium priority for the moment

**Comment by ariel-phet** [comment]
moving to low priority temporarily in testing queue

**Comment by phet-steele** [comment]
@jbphet this is ready for fixing.

**Comment by jbphet** [comment]
Okay, thanks for the testing.
