### ISSUE TITLE
Dev Test: Atomic Interactions 1.0.0.dev.10

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#612]
Dev release for Atomic Interactions 1.0.0.dev.10 is out for testing. Majority of the simulation is similar to third screen of SOM but have few added features and would be good to test fixes for those issues.

Link to the Simulation: http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.10/atomic-interactions_en.html

Issues to check
- [x] https://github.com/phetsims/atomic-interactions/issues/24
- [x] https://github.com/phetsims/atomic-interactions/issues/20
- [x] https://github.com/phetsims/atomic-interactions/issues/16
- [x] https://github.com/phetsims/atomic-interactions/issues/8

**Comment by ariel-phet** [comment]
@phet-steele -- you and the crew do your thing

**Comment by ariel-phet** [comment]
@phet-steele please assign any issues than cannot be closed to @jbphet

**Comment by ariel-phet** [comment]
bumping down to medium priority for the moment

**Comment by ariel-phet** [comment]
moving to low priority temporarily

**Comment by phet-steele** [comment]
@jbphet this is ready for fixing.

**Comment by jbphet** [comment]
Thanks for the testing, I or @aadish will address the issues shortly.  Closing.
