### ISSUE TITLE
ISTE conference booth needs and staffing

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#614]
- [ ] @kathy-phet,  need to register as individual (KP is getting our included Full Conference Badge) 
- [x] Print flyers (any updates?)
- [x] Decide who all is attending and when (7 exhibitor badges + 10 free exhibitor admissions): AP, ON (half days), JB, AL, SR, JG
- [x] New rotating video @phet-steele Neuron, Color Vision, Bending Light, ESPB, Area Builder, Graphing Lines, BaA, Molecule Shapes, Under Pressure

- Others interested? @alynne-phet @phet-steele @amyh-phet @arouinfar would any of you be interested? (sign up below or comment)

AM/PM | Saturday (setup) | Monday | Tuesday | Wednesday
------------ | ------------ | ------------- | ------------- | -------------
morning          | AP/ON/   | AP/AM/SD/SR/AH          | AP/SD/JB/AH/AL         | AR/SD/JG/AH
afternoon          | AP/ON/   | ON/AP/SD/AR/AH      | ON/AP/SD/AR/AL     | AR/SD/AH

**Monday, June 27	9:30 a.m.–5:30 p.m.**
Continental breakfast in the Expo	9:45–10:15 a.m.
**Tuesday, June 28	9:30 a.m.–5 p.m.**
Continental breakfast in the Expo	9:45–10:15 a.m.
**Wednesday, June 29	9:30 a.m.–2:30 p.m.**

Note: we'll be "exhibiting" at the TedXMileHigh conference on Saturday 6/25 and will tear down the booth there at 4pm, head over to ISTE and setup.

**Comment by ariel-phet** [comment]
Will have 7 booth badges - John Blanco, Andrea Lin, Sam Reid, Jesse are interested in attending

**Comment by oliver-phet** [comment]
- [ ] @kathy-phet, @amanda-phet and Susan Miller need to register as individual (KP is getting our included Full Conference Badge) 
- [ ] Print flyers (any updates?)
- [ ] Decide who all is attending (7 exhibitor badges): AP, ON (half days), JB, AL, SR, JG
- [ ] New rotating video @phet-steele Neuron, Color Vision, Bending Light, ESPB, Area Builder, Graphing Lines, BaA, Molecule Shapes, Under Pressure

- Others interested? @alynne-phet @phet-steele @amyh-phet @arouinfar would any of you be interested? (sign up below or comment)


AM/PM | Sunday (setup) | Monday | Tuesday | Wednesday
------------ | ------------ | ------------- | ------------- | -------------
AM          | AP/ON/   | AP            | AP            | AP
PM          | AP/ON/   | ON/AP      | ON/AP     | AP


**Monday, June 27	9:30 a.m.–5:30 p.m.**
Continental breakfast in the Expo	9:45–10:15 a.m.
**Tuesday, June 28	9:30 a.m.–5 p.m.**
Continental breakfast in the Expo	9:45–10:15 a.m.
**Wednesday, June 29	9:30 a.m.–2:30 p.m.**

**Comment by arouinfar** [comment]
I'm available to work at the booth all day Mon-Wed. If we end up doing partial-day shifts, I have a slight preference for afternoons.

**Comment by amyh-phet** [comment]
@ariel-phet   I'm happy to attend any or all of the days.  I'm an early bird and live close, so am sessions would be easy for me to fill.  If it would save someone a trip from Boulder on Sunday, I can help set up.

**Comment by phet-steele** [comment]
> New rotating video

Putting it on my to-do list.

> Print flyers (any updates?)

@oliver-phet I think I have an .ai of these, come check with me sometime after today.

@ariel-phet and of course, yes I would love to go! I could be at the booth for as long as needed. I live close by the building so there is no travel hassle.

**Comment by amanda-phet** [comment]
I edited the table above to include myself. Oliver will and I will complete my registration on Thursday 6/16.

**Comment by ariel-phet** [comment]
@amyh-phet I put you both down for a full day on Monday and Wednesday. half day Tuesday morning

@arouinfar I put you down for Monday and Tuesday afternoon.

Lets see how things go on Monday and we can readjust if needed

**Comment by arouinfar** [comment]
Sounds good @ariel-phet

**Comment by amanda-phet** [comment]
I completed my registration.

**Comment by amyh-phet** [comment]
Sounds good.

**Comment by andrea-phet** [comment]
I edited the table

**Comment by phet-steele** [comment]
@ariel-phet flyers are printed and you should look at them.

**Comment by amanda-phet** [comment]
@phet-steele Can you please print two of these flyers to display at the booth? 
[conference_flyer_outlines.pdf](https://github.com/phetsims/tasks/files/328144/conference_flyer_outlines.pdf)

You may want to print directly from the .ai file found [here](https://drive.google.com/open?id=0Bz7jTh2s-5L5UTZKRWpCREJ4TGc)

**Comment by oliver-phet** [comment]
@amanda-phet Can you embed the images of you/Susan in the flyer?

**Comment by amanda-phet** [comment]
Done. Sorry about that!

**Comment by amyh-phet** [comment]
@oliver-phet    Updated flyers are in drive.  Let me know if you still get the message about unsupported fonts when you open the file.

**Comment by amanda-phet** [comment]
@amyh-phet are you referring to my flyer? I uploaded it with outlines so it should not be a problem.

**Comment by amyh-phet** [comment]
@amanda-phet    I was referring to the flyer we would hand out at the booth, not your flyer.

**Comment by phet-steele** [comment]
> Can you please print two of these flyers to display at the booth?

@amanda-phet done.

**Comment by arouinfar** [comment]
Added myself to Wednesday and removed @ariel-phet, at his request.

**Comment by oliver-phet** [comment]
I'm packing an iPad Air and Macbook Air (that will be used to show video) and Steele is going to bring Turing (15" MBP). If AP brings his computer for Monday and Tuesday, we'll want either/both AH and AR's computers for Wednesday. 

Summary of computers to bring:
Mon: AP
Tues: AP
Wed: AH/AR

**Comment by amyh-phet** [comment]
@oliver-phet    I'll have my computer along each day.

**Comment by arouinfar** [comment]
@oliver-phet I'll also be bringing my computer every day.

**Comment by oliver-phet** [comment]
Everyone staffing the booth will need to register and pick up their (free) exhibitor badge at registration.

**Comment by ariel-phet** [comment]
I think we are all set here, closing the issue. Great conference so far!!
