### ISSUE TITLE
Dev Test: Capacitor Lab: Basics 1.0.0-dev.22

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#615]
We are getting ready for a release of Capacitor Lab: Basics so it would be good to do another dev test.  There have been quite a few changes since the last version so it would be good to make sure that everything is behaving correctly.

As far as we are aware, the sim is 'bug free' so if you notice any buggy behavior, poor performance, or incomplete features please create issues under https://github.com/phetsims/capacitor-lab-basics/issues.

Link to Sim: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.23/capacitor-lab-basics_en.html

Please check the following platforms:
 - [x] Win Chrome
 - [x] Edge
 - [x] Mac Safari
 - [x] iPad 2 iOS 9+

Also, please verify that all text is good for i18n:
 - [x] stringTest=double
 - [x] stringTest=long
 - [x] stringTest=X (short strings)
 - [x] stringTest=rtl (right-to-left)
 - [x] showPointerAreas (touchArea=red, mouseArea=blue)

Also, as part of this dev test, please pay special attention to the following (which have changed since the last dev test):
- [x]  The voltmeter readout should be correct for all possible probe locations and circuit states

**Comment by ariel-phet** [comment]
@phet-steele this should be the current highest sim testing priority after function builder tests

**Comment by ariel-phet** [comment]
iO version delivered to Ido, so with current testing priorities moving to medium

**Comment by ariel-phet** [comment]
Moving back to high priority with current testing needs

**Comment by brroberts1231** [comment]
All platforms tested.

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet lõppenud

**Comment by ariel-phet** [comment]
@jessegreenberg feel free to close or use as reference

**Comment by jessegreenberg** [comment]
Thanks for the dev test!  Closing.
