### ISSUE TITLE
ISTE video

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#616]
From #614:

Video will contain Neuron, Color Vision, Bending Light, ESPB, Area Builder, Graphing Lines, BAA, Molecule Shapes, and Under Pressure

**Comment by phet-steele** [comment]
@ariel-phet any specific recommendations for Color Vision, Graphing Lines, BAA, and MS?

**Comment by ariel-phet** [comment]
I would say...
- RGB screen on color vision, move a few sliders see perceived color obviously change
- One of the game challenges on graphing lines, perhaps "set the slope" and get it right
- BAA perhaps build some atom, open up some panels, and then change a few particles
- MS add a few bonds, rotate molecule, turn on angle measurment

**Comment by phet-steele** [comment]
@ariel-phet approved, the video lives in emails and on Curie.

**Comment by ariel-phet** [comment]
Video upload to https://github.com/phetsims/phet-info/blob/master/conferences/ISTEProjectionVideo_06-15-2016.mp4

Also created a "conferences" folder in phet-info where we could put some misc stuff
