### ISSUE TITLE
Dev Test: Circuit Construction Kit: Black Box 1.0.0-dev.17

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#617]
We are getting ready to deliver CCK: Black Box for use in a study at Stanford. I have done some testing on the latest version, but it could use some follow-up QA testing from @phet-steele. This isn't technically a full dev test, as there's no need to use multiple platforms or do the usual i18n checks. The goal is determine if there are any major usability issues that @samreid should address before delivering the sim to Stanford.

The testing link and relevant issues are tagged here:
https://github.com/phetsims/circuit-construction-kit/issues/134

@ariel-phet can you assign a priority for this task? If at all possible, it would be good for @phet-steele to get to this sometime this week.

**Comment by ariel-phet** [comment]
@phet-steele I would say this is "on par" with CL:B

**Comment by ariel-phet** [comment]
bumping to top testing priority for QA team

**Comment by samreid** [comment]
New version incoming, please hold off testing until the new version is posted.

**Comment by samreid** [comment]
@ariel-phet I've fixed other bugs and would like to publish a new version for testing, instead of testing dev.16 which is stale.  I'll try to publish something before tomorrow morning.  Reassigned to @ariel-phet so that he can discuss/re-evaluate priorities, etc.

**Comment by ariel-phet** [comment]
marking status as on-hold but leaving top priority label for when next version is available

**Comment by ariel-phet** [comment]
@samreid please reassign to @phet-steele when you have a new version

**Comment by samreid** [comment]
Version dev.17 is ready for testing as described in https://github.com/phetsims/circuit-construction-kit/issues/140

@phet-steele, you are approved for launch.

**Comment by phet-steele** [comment]
@arouinfar @samreid This testing has been done.

**Comment by samreid** [comment]
Thanks everybody!
