### ISSUE TITLE
Testing for BrainPOP GameUp SnapThought

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#620]
We are adding support for BrainPOP GameUp SnapThought in the following simulations before ISTE.

Area Builder
Balancing Act
Color Vision
Concentration
Energy Skate Park: Basics
Graphing Lines
Molecules and Light
Wave on a String

Deploying these as maintenance releases (instead of from master) will allow us to guarantee bug-free simulations without having to retest the entire sim on many platforms.  However, deploying maintenance releases is a time consuming process and we would prefer to do it only once.  Therefore it is important to test whether the proposed solution will work well on our supported platforms before we spend a lot of time releasing the versions with the SnapThought code.

I've published a proposed version here:
http://s4.brainpop.com/games/phetsimtest/

And you must log in with username and password given in special-ops 26.

What to test:
- [x] Does the SnapThought toolbar appear?
- [x] Does the SnapThought toolbar appear quickly?
- [x] Does the SnapThought toolbar flicker?
- [x] Does the toolbar allow you to capture images, review them and write text below them?
- [ ] Any other issues identified?

Testing should be performed on all of our supported platforms.

The only other problems I'm aware of that do not need to be reported are:
1. This console error on startup: GET http://s4.brainpop.com/games/phetsimtest/undefined 404 (Not Found)
2. There is a broken image behind the Play Game button:
![image](https://cloud.githubusercontent.com/assets/679486/16099270/a8aa14aa-3314-11e6-9b9d-a9c91c9f329a.png)

@ariel-phet can you please prioritize and assign to testers?  I was going to ask that this be completed 7 business days before ISTE (counting 2 days to deploy and 1 week to address other integration issues with BrainPOP after the maintenance release is done), but I realized that is in only 37 minutes.  So let's go with "sooner is better" 😄

**Comment by ariel-phet** [comment]
Should be done after (or if possible in parallel with) latest CCK testing

**Comment by phet-steele** [comment]
OSX 10.11.5 browsers behave well.

**Comment by phet-steele** [comment]
Win 10 browsers check out as well, iOS did something funking that I'm still looking into.

**Comment by phet-steele** [comment]
List of platforms tested on, good enough @samreid?

- OSX 10.11.5 (Chrome, FF, Safari)
- Win 10 (Chrome, FF, Edge, IE11)
- iOS 9.3.2
- Win 7 (Chrome, IE11)
- Chromebook

**Comment by samreid** [comment]
Looks great, thanks @phet-steele!  I'll move on to next steps.
