### ISSUE TITLE
Dev Test: Rutherford Scattering 1.0.0-dev.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#621]
Now that the new 'Atom' scene is complete, Rutherford Scattering is ready for dev testing.

**Link to Sim:** http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.3/rutherford-scattering_en.html

Please check the following platforms:
- [ ] Win Chrome
- [ ] Edge
- [ ] Mac Safari
- [ ] iPad 2 iOS 9+

In this dev test, please pay special attention to the particle behavior in the 'Atom' scene of the 'Rutherford Atom' screen, as well as performance of these particles on all testing devices.  But please also test the whole sim since much of the simulation was modified for these new features.

**Comment by ariel-phet** [comment]
@phet-steele since this was part of the donation drive, please put slightly above CL:B testing

**Comment by jessegreenberg** [comment]
@ariel-phet should we hold off on dev testing until after we investigate handling multiple deflections?  Particle implementation could change quite a bit, and we will probably want to dev test again if/when multiple deflections are supported.

**Comment by jessegreenberg** [comment]
Yes, lets put this on hold until we take a look at https://github.com/phetsims/rutherford-scattering/issues/20#issuecomment-226576125 or reducing cases of multiple deflections.  New dev version will be up for testing shortly.
