### ISSUE TITLE
RC Test: Beer's Law Lab 1.4.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#622]
New RC version:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-rc.2/beers-law-lab_en.html

One issue to verify:
https://github.com/phetsims/beers-law-lab/issues/177

Here's the test matrix. You don't need to cover all platforms. Just check the above issue on 2 or 3 platforms.
https://docs.google.com/spreadsheets/d/1opT_0el4D08ezqlqrb4dgdYreiPRfjAG5gWRnADOyrk/edit#gid=1712417985

**Comment by ariel-phet** [comment]
@phet-steele low priority (but seems quick so feel free to delegate and knock it off)

**Comment by pixelzoom** [comment]
@phet-steele It looks like @brroberts1231 has tested on a few platforms, so I believe this is complete. Do you agree? If so, I'll proceed with publishing.

**Comment by brroberts1231** [comment]
@pixelzoom , @phet-steele asked me to quickly test on iPad as well. phetsims/beers-law-lab#177 is verified on iOS 9.3.3 Safari. Should be complete now.

**Comment by phet-steele** [comment]
@pixelzoom you may proceed.

**Comment by pixelzoom** [comment]
1.4.0 deployed to PhET website.
