### ISSUE TITLE
Test iOS 10 Beta and macOS Sierra 10.12 Beta

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#623]

**Comment by ariel-phet** [comment]
In this test please check https://github.com/phetsims/joist/issues/234

**Comment by ariel-phet** [comment]
bumping to medium priority, we definitely want to test before the school year starts.

**Comment by phet-steele** [comment]
@ariel-phet since these betas are public, to get the ball rolling I'll sign up with a personal account.

**Comment by phet-steele** [comment]
Turing will receive macOS Sierra.

**Comment by phet-steele** [comment]
iOS 10 is not compatible with iPad 2 (Tycho), so the beta will be put on a different device (an iPad Air 2).

**Comment by phet-steele** [comment]
iOS 10 is now loaded on the iPad Air 2 named....."Dalton".

**Comment by phet-steele** [comment]
@brroberts1231 can you make a note of which sims you tested and any comments you have? Also, if you haven't tried a Java or Flash on Turing yet, can you choose one or two of each to run and similarly make note?

**Comment by brroberts1231** [comment]
So far I've tested Graphing Lines, Gravity Force lab, Balancing Chemical Equations, Balancing Act, and Hooke's Law. Only html5 so far. All worked well.

**Comment by brroberts1231** [comment]
Confirmed that phetsims/joist#234 still occurs on iOS 10.0

**Comment by brroberts1231** [comment]
On Turing, I've tested Faraday's Law and Wave on a String in Flash, which automatically work in Chrome, but of course still require installing Flash Player to work on Safari or Firefox. Once you do that, though, there's no problem. On the Flash Player download page, when you select your operating system, they list OS X 10.6 - 10.11, but that version will still work for 10.12.

**Comment by brroberts1231** [comment]
For Java, I tested Graphing Lines and Balancing Act with no problem.

**Comment by phet-steele** [comment]
@brroberts1231 can you test Molecule Shapes and ESPB (both HTML5). Close this issue if all is good.

**Comment by brroberts1231** [comment]
Molecule Shapes and ESPB both look good. Closing
