### ISSUE TITLE
RC Test: Concentration 1.3.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#624]
Since Concentration is a subset of Beer's Law Lab, recommended to do this at the same time as https://github.com/phetsims/tasks/issues/622.  (These RCs are built from the same code base.)

New RC version:
http://www.colorado.edu/physics/phet/dev/html/concentration/1.3.0-rc.2/concentration_en.html

One issue to verify:
phetsims/beers-law-lab#177

Here's the test matrix. You don't need to cover all platforms. Just check the above issue on 2 or 3 platforms.
https://docs.google.com/spreadsheets/d/1ghqNXGEAK4sApVwFIHIyZLuNb5QjQO-FyZiQCjE5_ZM/edit#gid=1564648115

**Comment by ariel-phet** [comment]
@phet-steele low priority (but seems quick so feel free to delegate and knock it off)

**Comment by pixelzoom** [comment]
@phet-steele It looks like @brroberts1231 has tested on a few platforms, so I believe this is complete. Do you agree? If so, I'll proceed with publishing.

**Comment by brroberts1231** [comment]
@pixelzoom , @phet-steele asked me to quickly test on iPad as well. phetsims/beers-law-lab#177 is verified on iOS 9.3.3 Safari. Should be complete now.

**Comment by phet-steele** [comment]
@pixelzoom you may proceed.

**Comment by pixelzoom** [comment]
1.3.0 published to PhET website.
