### ISSUE TITLE
Function Builder: interviews (round 3)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#625]
@amanda-phet has interviews scheduled for 6/29/16 and 7/5/16.  This issue is for reporting outcomes. 

Things that I'm interested in:
• Mystery screen (which wasn't included in previous interviews)
• Identity function icon (does the revised icon work better? same? worse?)

**Comment by pixelzoom** [comment]
In the Mystery screen, we have a blank space after '6' in the cards carousel.  Does that credit any problems or distractions?

**Comment by pixelzoom** [comment]
@amanda-phet Here's the dev version for interviews:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.67/function-builder_en.html

**Comment by pixelzoom** [comment]
6/29/16 interview didn't happen because the interviewee canceled.

**Comment by pixelzoom** [comment]
Skype with @amanda-phet:
[7/5/16, 1:12:31 PM] Chris Malley: How many interviews do you have scheduled for this week?
[7/5/16, 1:12:56 PM] Amanda McGarry: two today (siblings), one thursday

**Comment by pixelzoom** [comment]
Lastest version is now:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.69/function-builder_en.html

**Comment by pixelzoom** [comment]
@amanda-phet When you get a chance, please summarize your interview results here (or in the design doc) to satisfy the master checklist requirements in https://github.com/phetsims/function-builder/issues/2.

**Comment by pixelzoom** [comment]
For posterity, the issues that resulted from this round of interviews were:
https://github.com/phetsims/function-builder/issues/90
https://github.com/phetsims/function-builder/issues/91

**Comment by amanda-phet** [comment]
I'm working on this in the design doc and will copy and paste in this issue.

**Comment by amanda-phet** [comment]
7/5/16 - Student 1, M, grade 7
Student particularly enjoyed the mystery screen. He discovered that you can reveal the function after 3 inputs are dragged through and used the reveal buttons to verify whether he was correct or not. Was determined to figure out what all of the Patterns functions did and got stuck on the identity (“selfie”) function. He determined that it did nothing, but did not connect it to the icon. He figured out all of the other functions (even knew the soup can was “that artist”). 

7/5/16 - Student 2, M, grade 9
While exploring the sim this student saw “slope-intercept” and immediately though about graphing the linear function. He was then disappointed that the graph was scaled such that you could not accurately see the slope or y-intercept. When playing on the mystery screen he also was focused on how the graph was not zoomed in enough to figure out the function. 

7/7/16 - Student 3, M, grade 6
Student was very interested in Equations screen and effect of function on inputs. He spends a fair amount of time trying to interpret patterns in the table and the graph. He then goes on to figure out all of the functions on the Patterns screen. He tries to drag output cards back through the builder and realizes some will go back and some will not. He thinks the identity function does something when composed with other functions. He figures out which functions are non-invertible and figures out why (with some interviewer questions). He was familiar with the terms input and output from elementary school. When working on the Mystery screen he found the double and triple functions to be challenging but was able to figure out some single ones.

**Comment by pixelzoom** [comment]
Thanks for the summary @amanda-phet.  This issue can now be closed.
