### ISSUE TITLE
Double check links and password in Pearson email

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#626]
In https://github.com/phetsims/phet-io/issues/474#issuecomment-227500520 I wrote a proposed email for Pearson, once the contract is signed.  @ariel-phet is @phet-steele or someone else available to click through the links and verify that all links and passwords work properly?  Would be nice to do before sharing this to Pearson and probably wouldn't take too long.

**Comment by ariel-phet** [comment]
@phet-steele please do yourself or delegate. Assigning as high priority, partially because should be quick.

**Comment by phet-steele** [comment]
@samreid I've needed a password for each wrapper, and the supplied credentials worked.
