### ISSUE TITLE
Dev Test: Rutherford Scattering 1.0.0-dev.5

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#627]
Now that the new 'Atom' scene is complete with multiple deflections, Rutherford Scattering is ready for dev testing.

Link to Sim: http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-dev.5/rutherford-scattering_en.html

Please check the following platforms:

 - [x] Win Chrome
 - [x] Edge
 - [x] Mac Safari
 - [x] iPad 2 iOS 9+

In this dev test, please pay special attention to the particle behavior in the 'Atom' scene of the 'Rutherford Atom' screen.  Also check performance of these particles with and without traces on all testing devices. But please also test the whole sim since much of the simulation was modified for these new features.

**Comment by phet-steele** [comment]
@jessegreenberg I believe testing for this dev version is complete.

**Comment by jessegreenberg** [comment]
Thanks for the testing!  Closing, a new dev version will be out to verify the fixes for issues that came out of this test.
