### ISSUE TITLE
dev testing for plinko probability 1.0.0-dev.5

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#630]
We are ready for a round of dev testing on plinko probability. In addition we would like you to keep an eye on performance.

Link to dev version:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.5/plinko-probability_en.html

Dev Test Platforms:

- [x] iPad 2 iOS 9.3.1]
- [x] Win Firefox
- [x] Win Chrome

You can check that the following issues have been addressed:
- [x] https://github.com/phetsims/plinko-probability/issues/21
- [x] https://github.com/phetsims/plinko-probability/issues/20
- [x] https://github.com/phetsims/plinko-probability/issues/19
- [x] https://github.com/phetsims/plinko-probability/issues/18
- [x] https://github.com/phetsims/plinko-probability/issues/17

The QA team may want to use the query parameter 'lowerBallMaximum'  which reduces the maximum amount of balls to 25 (In this way you won't have to wait for 9999 balls on the second screen)

Please create separate issue for any problems that you find.

Assigning to @ariel-phet

**Comment by ariel-phet** [comment]
@alynne-phet @brroberts1231 @phet-steele please make this current top testing priority.

Assinging to @brroberts1231 since @phet-steele is at ISTE

**Comment by brroberts1231** [comment]
@veillette testing complete. Other than phetsims/plinko-probability#26, performance on iPad looks good overall.

**Comment by ariel-phet** [comment]
assigning to @veillette - feel free to close or keep open as a reference until (#26) is addressed

**Comment by veillette** [comment]
Thanks to the qa team for the good work. Closing
