### ISSUE TITLE
testing the thumbNode in SUN

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#633]
We have made some changes to SUN (see https://github.com/phetsims/sun/commit/c5dbf7cdfa530d559f8d1ded3d9714d84a5c3570 and issue #https://github.com/phetsims/sun/issues/202) that might have unintended effect.  The changes affect the thumb node and the touchArea of the thumbNode. 
Can you make a regression test between published sims and sims from master and see if the query paraameter  ?showPointerAreas give the same result and if the thumb nodes behaves different in any way.

I suggest to use 

wave-on-a-string
least-square-regression

and two simulations that have custom nodes

force-and-motion-basics
molecules-and-light.

Assigning to @phet-steele

**Comment by phet-steele** [comment]
@brroberts1231 and I performed these regression tests on multiple platforms. Sliders behave the same.

**Comment by veillette** [comment]
Thanks for the regression test. Closing
