### ISSUE TITLE
Testing for Circuit Construction Kit: Black Box Study 1.0.0-dev.18

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#636]
Circuit Construction Kit: Black Box Study 1.0.0-dev.18 was published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html

The following issues should be reviewed and tested in this version:
- [x] Back layer is prioritized when measuring overlapping wires https://github.com/phetsims/circuit-construction-kit/issues/143
- [x] Vertices don't connect in build screen https://github.com/phetsims/circuit-construction-kit/issues/141
- [x] Vertex pushing https://github.com/phetsims/circuit-construction-kit/issues/128

This is also the first version with electrons in the black box study version and it would be good for that feature to be tested thoroughly.

Testing on several platforms would be great, but it does not need to be exhaustive for the study (so a small handful of platforms would be fine).

@ariel-phet can you please prioritize and reassign?

**Comment by samreid** [comment]
For the 3 issues mentioned above, I have assigned them to the original reporters and removed the "hold" label, but it remains for @ariel-phet to indicate priority.

**Comment by ariel-phet** [comment]
@phet-steele and QA team please make current top testing priority, however, this priority will be immediately superseded #634

**Comment by phet-steele** [comment]
@samreid we're done! :+1:

**Comment by samreid** [comment]
Thanks @phet-steele @alynne-phet and @brroberts1231!  Everything is tracked elsewhere, closing.
