### ISSUE TITLE
Planning Kate visit 18th and 19th of July

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#637]
This issue is to help organize purpose and planning around @KateLRN visit

**Comment by KateLRN** [comment]
People to meet with for About PhET video and other intel:
- Mike Dubson
- Oliver Nix
- Emily
- Andrea Lin
- Amy Hansen

Things Kate will do on the ground:
- Work on Edmodo blog post
- Brainstorm ideas for the About PhET video
- Making connections to get more involved with the team
- Drafting blog post for LRN blog about PhET
- Compile feedback and advice for Ariel
- Shadow Ariel to gather insight into management style (autonomous work culture)
- Ad hoc opportunities that come up on the ground

**Comment by ariel-phet** [comment]
Kate Schedule


AM/PM | Saturday (setup) | Monday | Tuesday | Wednesday
------------ | ------------ | ------------- | ------------- | -------------
morning          | AP/ON/   | AP/AM/SD/SR/AH          | AP/SD/JB/AH/AL         | AR/SD/JG/AH
afternoon          | AP/ON/   | ON/AP/SD/AR/AH      | ON/AP/SD/AR/AL     | AR/SD/AH

**Comment by ariel-phet** [comment]
@oliver-phet, @samreid @kdessau-PhET if available for dinner

**Comment by kathy-phet** [comment]
Here are times I have, but 1 of these hours will be taken. I don't know which yet.

Monday, 10-11, or 1-4.

Tuesday, 12-1 or 2-4:30

**Comment by oliver-phet** [comment]
I can plan to be available.

**Comment by kdessau-PhET** [comment]
I might be available...my sister is planning on driving through and not sure when she's arriving. Let me know when and where on Monday and I can try to be available.

**Comment by KateLRN** [comment]
Great, I look forward to seeing you all! @ariel-phet, I'll let you make the call on where we have dinner.

@kathy-phet Should we plan to meet at 3pm Monday and we can reschedule to Tuesday if necessary?

**Comment by kathy-phet** [comment]
Sure. Monday at 3pm sounds good.

**Comment by kdessau-PhET** [comment]
Can't go to dinner as my sister is coming in to town.

**Comment by samreid** [comment]
At the moment it seems like a 30% chance I'll be available for dinner on Monday, but I won't know for certain until then.  I'll let you know!

**Comment by ariel-phet** [comment]
@KateLRN @kathy-phet @oliver-phet @jessegreenberg we will be doing dinner at 7pm at Centro

950 Pearl St, Boulder, CO 80302

**Comment by samreid** [comment]
I'll be unable to make it, have a nice dinner!

**Comment by oliver-phet** [comment]
Incase I'm not the first one there, the reservation is under my name!

**Comment by KateLRN** [comment]
@oliver-phet Are you in the office today? It would be great to chat with you before I take off, but no pressure!

**Comment by oliver-phet** [comment]
I'm around. I'll come down in a few minutes to chat!

**Comment by KateLRN** [comment]
Great, thanks!

**Comment by ariel-phet** [comment]
Visit a success, closing!
