### ISSUE TITLE
RC test: Function Builder 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#638]
Test matrix for 1.0.0-rc.1:
https://docs.google.com/spreadsheets/d/1crnipxdR5PEn8QBWQKMzPSA6sUMWdaBLRL0j8ZEzvEo/edit#gid=2

The matrix contains links to the RC version, and links to documentation for common and sim-specific query parameters.

See [FBQueryParameters.js](https://github.com/phetsims/function-builder/blob/master/js/common/FBQueryParameters.js) for documentation of sim-specific query parameters. Most useful for RC testing are: `populateOutput`, `slow`, `showAnswer` and `playAll`.

See also the Terminology section of [implementation-notes.md](https://github.com/phetsims/function-builder/blob/master/doc/implementation-notes.md). This will be useful for creating and discussing issues, so that we're all speaking the same language.

In addition to the test matrix, please perform these specific tests on 1 or 2 platforms:

- [x] ?stringTest=double (double all strings)
- [x] ?stringTest=long (excessively long strings)
- [x] ?stringTest=X (short strings)
- [x] ?stringTest=rtl (right-to-left text direction)
- [x] full screen test

**Comment by pixelzoom** [comment]
Test matrix:
https://docs.google.com/spreadsheets/d/1crnipxdR5PEn8QBWQKMzPSA6sUMWdaBLRL0j8ZEzvEo/edit#gid=2

**Comment by pixelzoom** [comment]
See the Terminology section of [implementation-notes.md](https://github.com/phetsims/function-builder/blob/master/doc/implementation-notes.md). This will be useful for creating issues, so that we're all speaking the same language.

**Comment by pixelzoom** [comment]
See [FBQueryParameters.js](https://github.com/phetsims/function-builder/blob/master/js/common/FBQueryParameters.js) for documentation of sim-specific query parameters. The query parameters that will be most useful for RC testing are: `populateOutput`, `slow`, `showAnswer` and `playAll`.

**Comment by pixelzoom** [comment]
In addition to the test matrix, please perform these specific tests:

- [ ] ?stringTest=double (double all strings)
- [ ] ?stringTest=long (excessively long strings)
- [ ] ?stringTest=X (short strings)
- [ ] ?stringTest=rtl (right-to-left text direction)
- [ ] full screen test

**Comment by pixelzoom** [comment]
RC version is published, test matrix is shared with the team. You may begin RC testing. Please mention this issue in any issues that you create.

**Comment by phet-steele** [comment]
@pixelzoom this RC test is done.

**Comment by pixelzoom** [comment]
Thank you testing team!  All issues discovered during this RC test have been addressed.  Three of those issues will need to be spot tested in another RC (coming soon).

Closing.
