### ISSUE TITLE
Backup GitHub data

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#64]
We have a large amount of important information in GitHub that is not backed up elsewhere.  Each PhET developer has a full copy of the repository code, but we may wish to back up the issues in each repository.  GitHub has a very good record of keeping our data safe and sound, but a backup might be nice "just in case".  Can anyone else think of anything else that needs to be backed up from GitHub? @ariel-phet can you assign someone to investigate how we can back up our GitHub data?

**Comment by ariel-phet** [comment]
Going to close this issue and reopen if necessary (hopefully not!)
