### ISSUE TITLE
Dropping support of iOS 8

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#640]
From phetsims/function-builder/issues/94, @ariel-phet stated
> Looks like iOS 8 is a little less than 1 percent of our overall usage, so probably time to cut the cord.

List of things to do for this change, to be updated at developer meeting.

- [x] Update Example Testing Matrix
- [x] Update Help Center system requirements
- [x] Update Lave, the iPad running iOS 8
- [x] Update Bjork, the iPad Mini running iOS 8
- [x] Development overview google doc Platforms section should point to http://phet.colorado.edu/en/help-center/running-sims#q11-header

**Comment by ariel-phet** [comment]
Yes we are going to drop support. @phet-steele will proceed

**Comment by phet-steele** [comment]
Forgot about our iOS 8 iPad Mini, Bjork. Updating that as well.

**Comment by phet-steele** [comment]
Above checklist list done! Sayonara iOS 8.
