### ISSUE TITLE
Test new search bar

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#641]
@mattpen made an update to the auto-complete feature of our search bar. For example, if you search for "Build" you will now see "Area Builder" and "Build a Fraction" whereas it used to only show sims that started with exactly "Build...". However, it isn't perfect yet and could use some refining. 

Examples: 
Search for "fraction" and you should see 
* Build a Fraction
* Fractions Intro
* Fraction Matcher 

Search for "build" and you should see
* Area Builder
* Build a Fraction
* Build a Molecule
* Build an Atom

The original issue: https://github.com/phetsims/website/issues/228

It would be great to have this tested and issues reported. Please respond to this issue with problems/suggestions.

**Comment by mattpen** [comment]
The updates are published at http://phet-new.colorado.edu

**Comment by phet-steele** [comment]
Currently the above examples are not working, @mattpen is aware and working on it.

**Comment by mattpen** [comment]
@phet-steele - I fixed the autocomplete class so that the examples should function as described above.  The fix is deployed to phet-new.

**Comment by mattpen** [comment]
@phet-steele Reported that queries with two words that start with the same string were producing duplicate results.  For example the query "c" would return each of the CCK sims twice.  

I deployed a fix to phet-new that should fix this bug.  Steele, please confirm.

**Comment by phet-steele** [comment]
@mattpen @amanda-phet the search bar is functioning great. Close if there is nothing else to do here.

**Comment by amanda-phet** [comment]
Thanks @phet-steele !!
