### ISSUE TITLE
Remove 'iPad' and 'Chromebook' keyword from Java sims, Remove 'iPad' from 'Flash' sims

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#642]
@phet-steele Several Java and Flash sims still have 'iPad' and 'Chromebook' as keywords. Can you go through and remove 'iPad' and 'Chromebook' keyword from Java sims, Remove 'iPad' from 'Flash 'sims?

To find the sims, try searching "ipad" in the search bar.

Once done, you can verify by looking at the sidebar (while signed in) to ensure 'iPad/Tablet' and 'Chromebook' are no longer highlighted. 

<img width="928" alt="screen shot 2016-07-12 at 2 05 59 pm" src="https://cloud.githubusercontent.com/assets/5090275/16781747/e018c88e-4839-11e6-867c-70296bab024a.png">

**Comment by phet-steele** [comment]
@oliver-phet completed and verified by @alynne-phet.
