### ISSUE TITLE
RC test: Function Builder 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#644]
The previous RC test cycle (https://github.com/phetsims/tasks/issues/638) discovered a few minor issues, all of which need to be verified in this RC.   A complete test matrix is not necessary, it's sufficient to verify these issues on 1 or 2 platforms.  So this should be a quick RC cycle.

The RC version is:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.2/function-builder_en.html

Please test the following issues. Indicate what platforms they were verified on. And close the issues after they are verified.

- [x] https://github.com/phetsims/function-builder/issues/92, Double Warhol
- [x] https://github.com/phetsims/function-builder/issues/95, Builder lengths
- [x] https://github.com/phetsims/function-builder/issues/96, Invisible stick figure

Thanks!

**Comment by amanda-phet** [comment]
I did a quick check on macbook pro OSX 10.10 and these issues looked good to me (but I'll leave them for @phet-steele to close).

**Comment by phet-steele** [comment]
Verified all these on Win 10 Chrome, OSX 10.11.5 Chrome, and iPad2 iOS 9.3.3. @andrea-phet verified on Win  7 Chrome.

**Comment by pixelzoom** [comment]
Thank you again testing team! Onward to deploying 1.0.0.  Closing.
