### ISSUE TITLE
Preliminary accessibilty testing for PhET App

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#645]
@phet-steele as we move the PhET app towards publication, one important step will be to verify that it meets accessibility requirements. 

I am not sure how much will work "out of the box" - I believe if proper coding practices were followed a fair amount should work, but I do not think the CS senior project team made an explicit effort to check a11y.

[Apple's intro to testing a11y](
https://developer.apple.com/library/ios/technotes/TestingAccessibilityOfiOSApps/TestingtheAccessibilityofiOSApps/TestingtheAccessibilityofiOSApps.html#//apple_ref/doc/uid/TP40012619-CH2-SW2)

[Testing a11y with Voiceover](https://developer.apple.com/library/ios/technotes/TestingAccessibilityOfiOSApps/TestAccessibilityonYourDevicewithVoiceOver/TestAccessibilityonYourDevicewithVoiceOver.html#//apple_ref/doc/uid/TP40012619-CH3-SW1)

For any issues you find, please report them in the PhET App repo, and tag with the `dev:a11y` label, as well as referencing this issue.

If pretty much nothing works, please just make one issue that is something like "address a11y", make a preliminary checklist and assign to me.

**Comment by phet-steele** [comment]
Tested, issues made.
