### ISSUE TITLE
New video for BCCE

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#646]
@ariel-phet @amyh-phet please make a list of sims with any specific sim states you'd like.

**Comment by ariel-phet** [comment]
I will leave this to the discretion of one @amyh-phet (although molecule shapes has to be in there!)

**Comment by amyh-phet** [comment]
@phet-steele 

I think we should include:

- [ ]  BAA - use ISTE version
- [ ] Molecule Shapes - use ISTE version
- [ ] Balancing Chemical Equations - pick an equation to balance and a tool to use (scale or bars) 
- [ ]  Beer's Law Lab - screen 2 - pick a solution, turn on source, move ruler to measure pathlength, adjust concentration and wavelength of source
- [ ]  Concentration - pick solute, drag in meter, add solute, add water, drain solution, evaporate solution
- [ ]  Isotopes and Atomic Mass (Mixtures screen - pick an element (oxygen?) use sliders to create mixture on screen with panels open)
- [ ]  pH scale (micro screen -pick a solution, check hydronium/hydroxide view, add solution, add water, drain solution. 
- [ ] Acid-Base Solutions - highlight features on My Solution screen
- [ ] Molecules and Light - carbon monoxide and different light sources

- [ ] Rutherford Scattering - highlight new scene on first screen

If you can do 10, this is would be my list.  If you only can do 9, then my preference would be to drop Concentration .

**Comment by phet-steele** [comment]
@amyh-phet video lives on Curie and here: https://github.com/phetsims/phet-info/blob/master/conferences/BCCE_2016.mp4
