### ISSUE TITLE
New video for STEM forum

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#647]
We should see about revamping the video used in ISTE. @ariel-phet @amyh-phet @arouinfar please review the sims used in the ISTE video and inform if any should be swapped for something else. If not I'll just close this and we won't have a new video:

Neuron
Color Vision
Bending Light
ESPB
Area Builder
Graphing Lines
BAA
Molecule Shapes
Under Pressure

**Comment by arouinfar** [comment]
@phet-steele I think Area Builder is the only sim on the list that wouldn't be appropriate for the NSTA audience. Can you swap it out for Balancing Chemical Equations?

**Comment by ariel-phet** [comment]
Sounds good to me

**Comment by amyh-phet** [comment]
I also like the idea of adding Balancing Chemical Equations.

**Comment by phet-steele** [comment]
@arouinfar @amyh-phet @ariel-phet video lives here: https://github.com/phetsims/phet-info/blob/master/conferences/NSTA_STEM_2016.mp4
