### ISSUE TITLE
Get Andrea account on spot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#648]
To deploy dev versions, Andrea will need a spot account.

**Comment by jessegreenberg** [comment]
Email sent on 7/15/16, waiting for response from OIT.

**Comment by ariel-phet** [comment]
@jessegreenberg no response still? Might be good to ping them again

**Comment by andrea-phet** [comment]
@ariel-phet OIT responded, I sent my information to @jessegreenberg to proceed.

**Comment by jessegreenberg** [comment]
Thanks @andrea-phet, information passed along to OIT, waiting for a response again.

**Comment by jessegreenberg** [comment]
OIT responded and asked for us to verify some information over the phone.  @andrea-phet and I will be calling later this morning.

**Comment by jessegreenberg** [comment]
@andrea-phet has her account on spot, she just needs to be added to the correct group for permission to publish dev versions.

**Comment by jessegreenberg** [comment]
Called OIT again, they confirmed that someone will add @andrea-phet to the correct group and send a notification when it is done.

**Comment by jessegreenberg** [comment]
OIT has added @andrea-phet to the correct group. We can verify 7/28/16 before closing this issue.

**Comment by andrea-phet** [comment]
I was able to deploy my first dev version! (It is of proportion playground.) Thanks @jessegreenberg and feel free to close.

**Comment by jessegreenberg** [comment]
Looks great, I can see it up there!  Closing.
