### ISSUE TITLE
Artwork for projectile motion

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#649]
@arouinfar and @andrea-phet it would be good for us to enumerate what artwork we want redrawn for projectile motion, and have a clear list for our graphic artist.

**Comment by arouinfar** [comment]
@ariel-phet is this something for me or for @amanda-phet? I'm happy to take care of it, but AM is technically the lead on this one.

**Comment by ariel-phet** [comment]
As discussed today...yes, for you @arouinfar, sorry for the unclear communication that was in my head

**Comment by andrea-phet** [comment]
Here is what I can think of so far:
- cannon
- picture on fire button
- statue of David
- different projectile objects that the design team would like (cannonball, pumpkin, piano, etc.)

**Comment by arouinfar** [comment]
@andrea-phet that's a great start.

I think the items that we'd want our graphic artist to work on would be 
* Cannon
* David
* Pumpkin
* Human
* Piano
* Buick
* Fire button (maybe)

I can draw the smaller items like the tank shell, balls, and fire button (if we go with the design in the mockups).

**Comment by ariel-phet** [comment]
@mariahmaephet it would be good to have a skype call with @arouinfar regarding this artwork (next big sim artwork project). Although finishing off any math sim artwork is still the top priority.

Thanks!

**Comment by arouinfar** [comment]
@mariahphet my schedule is generally pretty flexible except for Thursdays. Will you be able to chat this week?

**Comment by arouinfar** [comment]
Pinged @mariahmaephet via email to set up a Skype chat.

**Comment by arouinfar** [comment]
@mariahmaephet here's an updated list of the artwork needed. As we discussed, please take care of the cannon first.

- [ ] Cannon - more circus-like than war-like. I like the starburst pattern and base of this cannon, but the circus-y look could be dialed down a bit.
![image](https://cloud.githubusercontent.com/assets/8419308/18643960/9e126678-7e64-11e6-8e40-1c1bd0f6c71d.png)
- [ ] David statue with fig leaf - doesn't need to be 3D like the one currently in the sim. Line art that is less detailed, but still recognizable, would work nicely.
- [ ] Shorts for the David statue in PhET colors (maybe PhET blue with yellow stripe?)
- [ ] Pumpkin - not overly detailed, similar in style the Unit Rates produce.
- [ ] Smashed pumpkin split into a few pieces
- [ ] PhET girl with safety helmet & googles flying through the air - maybe one arm in front like this (without the cape)
![image](https://cloud.githubusercontent.com/assets/8419308/18644184/870cb0b8-7e65-11e6-94e2-79bbef27406d.png)
- [ ] PhET girl standing in Wonder Woman pose
- [ ] Grand piano
- [ ] Smashed grand piano, broken into a few pieces
- [ ] Buick, or similar classic car
- [ ] Smashed car, broken into a few pieces
- [ ] Background with Flatirons in the distance with a CU flag planted on top (used when the altitude is set to a mile high)

**Comment by mariahmaephet** [comment]
<img width="490" alt="screen shot 2016-11-23 at 6 59 08 pm" src="https://cloud.githubusercontent.com/assets/11527557/20582435/2e039f68-b1af-11e6-8246-8e9244e4f7f8.png">

@arouinfar @ariel-phet still working on the superhero pose but how do you like the outfit?

**Comment by ariel-phet** [comment]
@mariahmaephet LOVE the outfit!!

**Comment by arouinfar** [comment]
@mariahmaephet as usual, looks awesome! I absolutely love PhET girl's outfit.

A few suggestions
* Remove PhET girl's cape. The cape may lead some students to believe she's floating, or that it somehow has influence on her trajectory.
* I think the stripes on the cannon's base are what make me think the reference cannon was too circus-y. Can you try a solid yellow or red ring instead?

**Comment by mariahmaephet** [comment]
@arouinfar @ariel-phet 

<img width="624" alt="screen shot 2016-12-02 at 6 01 46 pm" src="https://cloud.githubusercontent.com/assets/11527557/20853400/9cbf8686-b8b9-11e6-8996-be611d0bbbca.png">
<img width="1077" alt="screen shot 2016-12-02 at 6 02 09 pm" src="https://cloud.githubusercontent.com/assets/11527557/20853401/9cc9fb5c-b8b9-11e6-832f-91bf1a9d6087.png">

**Comment by arouinfar** [comment]
Love it @mariahmaephet!! Let's go with the right version of the cannon and PhET girl.  Any other thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
@mariahmaephet I agree on the version on the right (and goggles could look good)

A few minor tweaks:

1. PhET girl's right hand looks a little funky to me while flying, I think it would just have it wresting on her side instead of in a fist
2. I like the red "gauntlet gloves" but she should also have those on while flying!
3. The yellow ring on the base of the cannon looks a little "wavy" - can we make it a consistent width?

**Comment by mariahmaephet** [comment]
@arouinfar @ariel-phet does the hand still look weird with the gloves? 

<img width="557" alt="screen shot 2016-12-09 at 3 51 13 pm" src="https://cloud.githubusercontent.com/assets/11527557/21064158/612882d0-be27-11e6-8605-68d26ea78c61.png">

<img width="505" alt="screen shot 2016-12-09 at 3 48 42 pm" src="https://cloud.githubusercontent.com/assets/11527557/21064081/feb81930-be26-11e6-86ae-c567a66c6b3b.png">

**Comment by ariel-phet** [comment]
@mariahmaephet looks fine with the gloves now :)

**Comment by arouinfar** [comment]
Looks awesome @mariahmaephet!

**Comment by arouinfar** [comment]
@mariahmaephet can you please upload the .ai files to your Google Drive folder?  I've just granted you edit privileges to the "Mariah's Artwork Files" folder through your CU email, so you should be getting an automated email with the link to the folder. Otherwise, you can access the folder here:
https://drive.google.com/drive/u/0/folders/0B6CMwxdP0NGYbVlQRU53RFNhdDQ

**Comment by ariel-phet** [comment]
@clmccutchan finishing up this artwork would be next on the priority list at the moment. I think we are pretty solid on the cannon and PhET girl, but the various other items need to be done.

You can see the original sim here:
https://phet.colorado.edu/en/simulation/projectile-motion

And it might be worth a discussion with @arouinfar if anything is unclear.

Feel free to upload a png of the buick and pumpkin you have already done, and @arouinfar might have some feedback.

As a note, we generally have the light source coming from the upper left as a convention (I believe you did that in the pumpkin), but just wanted to make sure that was clear as a convention.

**Comment by ariel-phet** [comment]
@clmccutchan and as for timeline...we are still developing this simulation, but having the artwork all worked out by the end of February would be nice.

**Comment by clmccutchan** [comment]
@ariel-phet @arouinfar  There is a list of possible assets dated Sept. 19 above. Has that list been altered or should I use that to determine what I am illustrating?

**Comment by ariel-phet** [comment]
@clmccutchan please also assign people when you have a question. So for instance please assign @arouinfar on this issue (she is in the best position to answer your question)

**Comment by arouinfar** [comment]
@clmccutchan yes, the list of assets are in this comment from Sept. 19: https://github.com/phetsims/tasks/issues/649#issuecomment-248084499.  I don't anticipate that we'll be adding anything else to that list for now.  Please let me know if you have any questions about the artwork. I'd also be happy to chat with you over Skype if that'd be easier.

As @ariel-phet said, it's generally best to assign an issue to me if you want feedback. That way, the issue will show up in my list of assigned issues which is easier to keep track of.

**Comment by clmccutchan** [comment]
@arouinfar How do you get it to tag a comment like you did above??

**Comment by arouinfar** [comment]
Great question @clmccutchan. Right click on the comment's timestamp, copy the link address, paste it as-is into your comment, and then GitHub will automatically format the link. You can also do the same to reference other GitHub issues. If you want to reference an issue in the same repo, type # and then the issue number, otherwise paste in the URL to the issue and GitHub will automatically format the link text.

**Comment by clmccutchan** [comment]
@arouinfar Here's a first draft of the pumpkin and the Buick. Let me know what you want me to tweak.
![projectilemotion_649_buick](https://cloud.githubusercontent.com/assets/25354670/22389459/d848af10-e4a2-11e6-954b-86b431f52c0a.png)
![projectilemotion_649_pumpkin](https://cloud.githubusercontent.com/assets/25354670/22389458/d82db5b6-e4a2-11e6-9d84-84982614ec13.png)

**Comment by arouinfar** [comment]
@clmccutchan these look good. I absolutely love the Buick! 

For the pumpkin, can you try something a bit more cartoony?  We're developing a new math sim, Unit Rates, that has quite a bit of produce in it. If possible, I'd like the style of the pumpkin to be similar to what's been done for Unit Rates.

Here are a few screenshots showing examples of the produce:
<img width=250, src="https://cloud.githubusercontent.com/assets/8419308/22799289/80e0e9d4-eec2-11e6-902f-0e37bef5e57e.png">  <img width=250, src="https://cloud.githubusercontent.com/assets/8419308/22799298/8a6d49a2-eec2-11e6-984a-e98ba7d4f902.png">

You can also take a look at in the context here:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.44/unit-rates_en.html

**Comment by clmccutchan** [comment]
Thanks, @arouinfar! The additional examples are very helpful. Much simpler than my pumpkin.

**Comment by arouinfar** [comment]
@clmccutchan if it would be helpful for us to have a Skype chat about the remaining artwork, please let me know! I'd be happy to chat with you about any questions you may have.

**Comment by clmccutchan** [comment]
@arouinfar A Skype or Zoom chat would be very helpful! Thanks. Here are some times that would work for me: Tues: 8:30-1:30, Wed 10-4, Fri: 8:30-3.

**Comment by arouinfar** [comment]
Sounds good @clmccutchan. How about tomorrow at 12:00?

**Comment by clmccutchan** [comment]
@arouinfar Sounds good. Skype or Zoom?

**Comment by arouinfar** [comment]
@clmccutchan I've emailed you a Zoom link we can use tomorrow.

**Comment by arouinfar** [comment]
@clmccutchan I've made a few slight tweaks to the checklist in https://github.com/phetsims/tasks/issues/649#issuecomment-248084499 based on our discussion today.

**Comment by clmccutchan** [comment]
@amanda-phet I believe this is everything on the list except for David's shorts on the ground. I'll get those to you later today. I left one wheel by the broken Buick; it could potentially roll off of the screen when the car hits the ground. Let me know what needs to be tweaked on these.

![projectile motion_buicks](https://cloud.githubusercontent.com/assets/25354670/23226602/5eca408a-f8f3-11e6-8be5-96e9a49c6021.png)
![projectile motion_fig_david](https://cloud.githubusercontent.com/assets/25354670/23226605/5ed970a0-f8f3-11e6-8bf1-2848f838aab8.png)
![projectile motion_flatirons](https://cloud.githubusercontent.com/assets/25354670/23226604/5ed35c4c-f8f3-11e6-93e7-6b4486071027.png)
![projectile motion_shorts_david](https://cloud.githubusercontent.com/assets/25354670/23226603/5ecda9b4-f8f3-11e6-96e0-38f2de03b45e.png)

**Comment by arouinfar** [comment]
I love it @clmccutchan!! When you get the chance can you put the .ai file in your Drive folder?
https://drive.google.com/drive/u/0/folders/0B6CMwxdP0NGYbDZ4Qmt2UDZlOEU

I think these will all work nicely, but I'd like to drop them into the mockups to check if anything needs tweaking.

**Comment by clmccutchan** [comment]
@arouinfar I don't have access to the Google drive folder. I just requested access. The .ai file is small enough for me to email. Here are the shorts.

![projectile motion_shorts](https://cloud.githubusercontent.com/assets/25354670/23228987/dbdab3fe-f8fb-11e6-9e4d-57516a706c1f.png)

**Comment by arouinfar** [comment]
All artwork has been delivered to the developers, closing.
