### ISSUE TITLE
NSTA STEM booth needs and staffing

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#651]
- [x] Print flyers (any updates?)
- [x] Decide who all is attending and when 

Wednesday (setup) | Thursday | Friday 
------------ | ------------- | ------------- 
SD/AR/AP |SD/ON/AR | SD/ON/AH

Exhibit Schedule
Wednesday, July 27, 4:30–6:30 p.m.
Thursday, July 28, 9:15 a.m.–3:00 p.m.
Friday, July 29, 9:15 a.m.–3:00 p.m.

Exhibit Installation and Dismantling Schedule
Installation
Wednesday, July 27
8:00 a.m. – 2:00 p.m.
Dismantling
Friday, July 29
3:00–Midnight

**Comment by amyh-phet** [comment]
@oliver-phet   I can staff as needed.  I was planning to take the booth bag from NSTA to BCCE so it doesn't need to go back to Boulder between conferences.

**Comment by arouinfar** [comment]
@oliver-phet I can also staff as needed.

**Comment by amyh-phet** [comment]
@oliver-phet    I added an updated version of the ISTE flyer to drive in the PhET Ai files folder.  Only change was to fix a typo.

**Comment by oliver-phet** [comment]
@ariel-phet Do you have any availability/interest to work the booth during NSTA STEM?

**Comment by oliver-phet** [comment]
@ariel-phet will figure out how to take the booth bag on Wednesday.

**Comment by oliver-phet** [comment]
All flyers printed.

**Comment by oliver-phet** [comment]
Badges registered for ON, AP, SD, AR (limit 4). AR can leave badge on Thursday for AH to use on Friday.

**Comment by arouinfar** [comment]
Will do @oliver-phet @amyh-phet.

**Comment by amyh-phet** [comment]
Thanks @arouinfar.

**Comment by oliver-phet** [comment]
Booth bag is ready to go. @ariel-phet Let me know if you will be taking it.

**Comment by ariel-phet** [comment]
@oliver-phet yeah, looks like I am good to go, will probably just plan on picking it up Wednesday

**Comment by phet-steele** [comment]
Good times!
