### ISSUE TITLE
Install Camtasia on a Mac test device

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#653]
@phet-steele    I'd like to have Camtasia installed on Mac so that we can produce primers.  Can you do this or work with one of the QA team members to make this happen?

**Comment by phet-steele** [comment]
@amyh-phet I installed it on Magnus (10.11.6 partition). Close this if the computer suits you.

**Comment by amyh-phet** [comment]
@phet-steele    Thanks!
