### ISSUE TITLE
Some sims are missing their parent category

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/tasks#655]
A handful of sims are missing their parent category. They show up correctly on the website but are missing on the PhET app.

Someone from the QA team should go through all the sims and add any missing parent categories so they show up correctly on the app.

**Comment by phet-steele** [comment]
HTML5 sims have been addressed. Culprits were Faraday's Law, Friction, GFL, Ohm's Law, and Resistance in a Wire (all Physics!).

**Comment by ariel-phet** [comment]
Since this has been addressed for HTML5 sims (which affects the app), and those have all been checked over, closing
