### ISSUE TITLE
Dev Test: Unit Rates 1.0.0-dev.10 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#657]
As discussed in today's status meeting, @phet-steele and I should do some testing on Unit Rates. The priority should be Macbook testing (since interviews are coming soon), but it wouldn't hurt to do a little testing on the iPad too.

Testing Link:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html

I've encountered two bugs but haven't had much luck in reproducing them. Please be on the lookout for these issues @phet-steele. 
* Occasionally, the vegetable bags will re-spawn. For example, all four bags of carrots are placed on the scale. Switch to other fruits and veggies, play for awhile, and then come back to carrots. The four bags of carrots will still be on the scale, but four additional bags will be on the shelf below. I've seen it happen twice, but I can't remember much other than it happened when revisiting a vegetable I hadn't interacted with for awhile.
* When manually adding lines to the double number line, both sides of the line must be a match for a line to get locked in place. Sometimes, two numbers will correctly correspond (eg. 9 carrots & $1.35) but the line will not lock in place. The desired behavior is described in the [Manually Building the Double Number Line](https://docs.google.com/document/d/1D4FBgMwvvQvo_jITN5a675KWMxseWiMZ-oN0rd7nG9A/edit#heading=h.3w2xcrg1yovd) section of the design doc.

Assigning to @ariel-phet for prioritization.

**Comment by phet-steele** [comment]
@arouinfar @schmitzware this has been pretty well tested.

**Comment by arouinfar** [comment]
I'm going to go ahead and close this issue since testing on dev.10 has been completed. I suspect we'll need to do another round of dev testing once @schmitzware finishes up the change requests we've made, but we can create a new issue for that when the time comes.
