### ISSUE TITLE
Can we create a plugin that automatically inserts require statements?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#658]
One of the hassles during development is adding the require statements for importing modules.  Can we create a plugin with the following specs?
- it takes what you have in the clipboard as the type you want to import.
- automatically determines the correct path to import from 
- parses the JS file to find the place with require statements 
- automatically adds the import statement in the correct spot

Ideally, this plugin would be usable from Sublime/IDEA/command line

**Comment by ariel-phet** [comment]
@samreid status of this issue? Should we bring up at developer meeting?

**Comment by samreid** [comment]
I recommend to leave this issue open and unassigned.  It may be nice to have in the long run (not sure how useful it would be in practice, unless it can be used directly from IDE) but it will not be easy to build and we have our hands full at the moment.

**Comment by samreid** [comment]
I've got this working (must be in another issue), but I press alt+shift+cmd+R and it inserts a require statement at the right spot. Closing.
