### ISSUE TITLE
Workshop Materials for BCCE

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/tasks#659]
@oliver-phet  and @phet-steele 

I've put all workshop materials in a folder on Google drive:  https://drive.google.com/open?id=0BwW3aJP5Cq8oQnJSc1VRVmFVN28

We need 26 copies of each document. Please double side any document that is over 1 page in length and staple any document that is over 2 pages in length.

Let me know if you have any questions.

**Comment by phet-steele** [comment]
@amyh-phet how do you want these grouped?

- All copies together in one group (17 stacks)
- 26 groups of one copy each (would there be a special order)
- Some other type of grouping?

**Comment by amyh-phet** [comment]
Let's go with 17 stacks-all copies together.

**Comment by phet-steele** [comment]
@amyh-phet should be good to go.
