### ISSUE TITLE
Move video files to phet-storage google account

### ISSUE THREAD

**Issue by schasteen** [phetsims/tasks#662]
The video files from PhET Backup 2 need to be moved to the phet-storage google drive.

All files from:
PhET Backup 2 / PhET-Media / PhET Classroom and Interview Footage
Should be moved to:
phet-storage / Production quality video footage (B-roll, Camtasia, Classroom)

And the files from:
PhET Backup 2 / SEI-Media / PhET Interviews
Should be moved to:
phet-storage / Production quality video footage (PhET Interviews)

Now that the production quality video footage is in phet-storage along with the research video footage, you may wish to rename your research footage folders to distinguish them.

I have made blank folders in that "Production quality video footage" folder for each of the subfolders:  B-roll, Camtasia, Classroom, Classroom video annotations.

I am not moving the "workshops and talks" footage from PhET-Media because I don't foresee a need to keep that footage.

I don't see a way to assign this issue, so am copying @ariel-phet.  Let me know if I need to do something different.

**Comment by ariel-phet** [comment]
@oliver-phet this issue has been lingering for quite some time. Now that we have been deep in the google drive migration and such, is it possible @arnabp could tackle this issue?

**Comment by arnabp** [comment]
Migration started, B-roll looks like it'll take 6 hours but the whole thing should be done in a few days.
