### ISSUE TITLE
dev testing for Plink-probability 1.0.0-dev.6

### ISSUE THREAD

**Issue by veillette** [phetsims/tasks#664]
Plinko Probability is ready for a test. Most of the issues raised during the code review have been addressed. 

Mostly I would like to know where we stand on

- [x] https://github.com/phetsims/plinko-probability/issues/26
- [x] https://github.com/phetsims/plinko-probability/issues/48

also poke around to see if there are any additional issues.

Testing Link
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.6/plinko-probability_en.html

Please test on the following platforms:

- [x] iPad 
- [x] Firefox

**Comment by veillette** [comment]
Assigning to @ariel-phet

**Comment by veillette** [comment]
In addition, I would like to know if the pegs can disappear when losing the context. 

For this test, you should simply load the link below, and toggle back and forth between the simulation and some external tabs. Use a variety of browsers for this text.

http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.6/plinko-probability_en.html?screens=2

**Comment by ariel-phet** [comment]
@phet-steele this should be nearly as high a sim testing priority as #661

**Comment by phet-steele** [comment]
@veillette issues above have been addressed. Additionally, I could not induce a context loss.

**Comment by veillette** [comment]
Thanks @phet-steele for all the testing. Closing.
