### ISSUE TITLE
Edit credits for Mike Dubson

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#666]
I noticed that some places list him as "Mike Dubson" and others as "Michael Dubson". I find this inconsistency to be annoying so I confirmed with Mike and he would like to consistently use "Michael Dubson" in sim credits. 

Can you (or someone you assign) change his name to be "Michael Dubson" in any place where it currently says "Mike Dubson" on the PhET site? (I changed a few already.) 

Also review the HTML5 sim credits within the sim and make issues in the appropriate repositories (they likely won't be updated until a new release of the sim is published but that's ok).

**Comment by veillette** [comment]
All the sims credits have been changed.

There are two more mentions of Mike that I have not changed (but could if wanted)
(1) in the repo website, under some 2012 survey (probably irrelevant)
(2) in  the PhET-IO-website (see below)


```
   <div class="col-xs-12 col-sm-4 col-md-3  team-member">
      <img src="/assets/img/team-photos/M Dubson edited bw.jpg" alt="Photo of Mike">
      <h4 class="name">Mike Dubson</h4>
      <div class="title">Physics Faculty</div>
      <div class="keywords">Sim Design &middot; Development &middot; Physics &middot; College</div>
      <div class="bio">
        <div>
            <span class="bio-text"
                  data-full-bio="Mike is an experienced physics teacher and an expert in undergraduate curriculum development. He develops new sims and provide science expertise for the physics engines in many sims. He has a PhD in experimental condensed matter Physics (Cornell, 1984).  In 2007, he received the Teacher of the Year Award from the American Association of Physics Teachers.">Mike is an experienced physics teacher and an expert in undergraduate curri...</span>
          <span class="toggle-bio more">MORE</span>
          <span class="toggle-bio less" style="display: none">LESS</span>
        </div>
      </div>
    </div>
```
Assigning back to @amanda-phet

**Comment by amanda-phet** [comment]
So, to be clear on what happened, the credits are changed and will go into effect when a sim is republished? 

(1) Not concerned about this
(2) If possible to change here go ahead. However that team page in general seems to be outdated so I can wrap this change into a set of other changes later on.

**Comment by veillette** [comment]
The credits in the sims have been changed. The corrections were done in master, therefore they will be present in future releases of the simulations.

I'll go ahead and make the change on the phet-IO page.

**Comment by amanda-phet** [comment]
Perfect! Thanks so much. I'll go ahead and close this issue then.
