### ISSUE TITLE
RC Test: Rutherford Scattering 1.0.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#667]
Rutherford Scattering is ready for an RC test.

**Link to Sim**
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.1/rutherford-scattering_en.html

**Link to iFrame**
http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.1/rutherford-scattering_en-iframe.html

**Link to Test Matrix**
https://docs.google.com/spreadsheets/d/14Nwt9RWUcWIUJaHTp1fGqHMiTVHQj8snQmbDSjwrjyw/edit#gid=0

In addition to the full RC test, please do the following checks:
 - [x] ?stringTest=double (double all strings)
 - [x] ?stringTest=long (excessively long strings)
 - [x] ?stringTest=X (short strings)
 - [x] ?stringTest=rtl (right-to-left text direction)
 - [x] full screen test
 - [x] verify projector mode (?projectorMode or from options dialog)

Assigning to @phet-steele but pinging @ariel-phet and @amyh-phet so they are aware of this task.

**Comment by phet-steele** [comment]
@jessegreenberg matrix is complete.

**Comment by jessegreenberg** [comment]
Thanks very much @phet-steele, new RC will be out soon.
