### ISSUE TITLE
RC Test: Rutherford Scattering 1.0.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#669]
Rutherford Scattering is ready for the next RC test.  Assigning to myself, once the build server is up and working the next RC can be deployed.

**Comment by jessegreenberg** [comment]
The next RC has been deployed.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.2/rutherford-scattering_en.html

**Link to iFrame:** http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.2/rutherford-scattering_en-iframe.html

**Link to Test Matrix:** https://docs.google.com/spreadsheets/d/14Nwt9RWUcWIUJaHTp1fGqHMiTVHQj8snQmbDSjwrjyw/edit#gid=1012468318

There were a large number of changes in this RC so it is worth doing a full RC test for this version.  In addition, please make sure that the following issues have been resolved from the last test:

 - [ ] https://github.com/phetsims/rutherford-scattering/issues/97
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/100
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/101
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/102
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/103
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/104
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/105
 - [ ] https://github.com/phetsims/rutherford-scattering/issues/106

Assigning to @phet-steele and @ariel-phet.

**Comment by phet-steele** [comment]
@jessegreenberg RC testing done. I await the spot checks or phetsims/rutherford-scattering/issues/104.

**Comment by jessegreenberg** [comment]
Thanks very much @phet-steele.  Closing, next RC for spot checks out shortly.
