### ISSUE TITLE
Spot check for phet website

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#670]
@phet-steele - The new server is now live at phet.colorado.edu.  Can you do a brief look through and make sure everything is acting as expected?  The items tested in #584 would be good candidates for review here.

**Comment by phet-steele** [comment]
A few things I've tried so far, with appropriate issues made:

- Browsing the website in RTL languages and alternate fonts
- Running and downloading simulations
- Translating the website and deploying new website translations (a trusted translator happened to unknowingly do this for me)
- Downloading and uploading contributions
- Translating and deploying a translation of an HTML5 sim with rosetta (@jbphet performed this and I agreed with him that what he had done is sufficient)
- Creating a user account
- Editing the profile
- Changing the email address
- Changing the password
- Editing the Help Center
- Checking around for broken links
- Checking access to primers/activities based on being logged in

**Comment by phet-steele** [comment]
@mattpen things are working well.

**Comment by mattpen** [comment]
Thanks for checking, I'm going to take the maintenance message down.
