### ISSUE TITLE
Dev Test: Circuit Construction Kit: Black Box Study 1.0.0-dev.23

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#674]
CCK Black Box Study 1.0.0-dev.23 was published as described in https://github.com/phetsims/circuit-construction-kit-common/issues/203

@phet-steele and @arouinfar can you please test as described in the issues above?  I'm not sure how the priority relates to the remainder of your workload.

**Comment by arouinfar** [comment]
@samreid I can work on this today. @phet-steele I'm not sure what you have on your plate right now, can this be high priority?

**Comment by phet-steele** [comment]
@arouinfar this can be high for the time being. @alynne-phet is also available today/this week.

**Comment by phet-steele** [comment]
This testing has been finished.
