### ISSUE TITLE
RC Spot Check: Rutherford Scattering 1.0.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#675]
Rutherford Scattering 1.0.0-rc.3 is ready for a spot check.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.3/rutherford-scattering_en.html

The only changes between 1.0.0-rc.3 and 1.0.0-rc.2 are related to the control panel to fix phetsims/rutherford-scattering#104, so only a spot check is necessary.  Please check the simulation on one or two platforms and verify the following

- [x] https://github.com/phetsims/rutherford-scattering/issues/104 is resolved
- [x] multitouch works as expected
- [x] control panel behavior is correct

Assigning to @phet-steele.

**Comment by phet-steele** [comment]
Performance tested on:

Win 10 Chrome
OSX 10.11.6 Chrome
iPad 2 iOS 9.3.4
Chromebook

All good.

**Comment by phet-steele** [comment]
@jessegreenberg 1.0.0-rc.3 testing is done.
