### ISSUE TITLE
Test contributions on ox-dev

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#676]
@phet-steele Can you please test the changes from phetsims/website#464, phetsims/website#478, and phetsims/website#473?  The changes have been applied on ox-dev.

Things that need to be confirmed:
- [x] Activity downloads still work, especially for greek/korean alphabet filenames. 
- [x] Activities are displayed using the original filename on the website.
- [x] Adding activity files. If filename is a duplicate an error occurs and the file is not uploaded.
- [x] Removing activity files.  Send me a list of Activity #'s and filenames of files that you delete so I can confirm the storage was purged.
- [x] Admin panel is not cached.  Please try visiting the pages signed out and signed in with a few different accounts, team member and non.  
- [x] ~~No more duplicate activities exist.~~

**Comment by phet-steele** [comment]
> Adding activity files. If filename is a duplicate an error occurs and the file is not uploaded.

Are you throwing this error only after the contribution has been created? Or are you throwing it when the user hits submit?

**Comment by mattpen** [comment]
When the user hits submit.

**Comment by mattpen** [comment]
No need to check duplicate activities, I checked these programatically.

**Comment by mattpen** [comment]
Added admin panel check to checklist in https://github.com/phetsims/tasks/issues/676#issue-171515588

**Comment by phet-steele** [comment]
@mattpen very recent problem: I can't seem to create a contribution with 3+ activities (ox-dev). I encounter an internal error.

**Comment by mattpen** [comment]
@phet-steele - creating contributions with 3+ files should be working now.

**Comment by mattpen** [comment]
@phet-steele - The zip files should be working now as well.  Is there anything remaining that hasn't been fixed?

**Comment by mattpen** [comment]
@oliver-phet @amanda-phet - The changes to the activity pages in the related issues are in a finished state.  It might be a good idea to deploy these changes to phet-server now, before I start adding changes for the file replace button.  Is that ok with you?

**Comment by oliver-phet** [comment]
OK with me.

**Comment by amanda-phet** [comment]
I have not tested any of this myself, but if it's working it seems like a good idea to deploy before making more changes.

**Comment by mattpen** [comment]
OK, I'll deploy this tonight and start on the replace function tomorrow.

**Comment by mattpen** [comment]
This was deployed to phet-server.  Thanks @phet-steele for the exhaustive testing.  I'll continue tracking changes for the new file replace button in phetsims/website#473
