### ISSUE TITLE
RC Spot Check: Rutherford Scattering 1.0.0-rc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#677]
Rutherford Scattering 1.0.0-rc.4 is ready for a spot check.

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.0-rc.4/rutherford-scattering_en.html

The only changes between 1.0.0-rc.4 and 1.0.0-rc.3 are related to the control panel to fix phetsims/rutherford-scattering#104, and phetsims/rutherford-scattering#109  so only a spot check is necessary. Please check the simulation on one or two platforms and verify the following:

 - [x] phetsims/rutherford-scattering#104 is resolved
 - [x] phetsims/rutherford-scattering#109 is resolved
 - [x] multitouch works as expected
 - [x] control panel behavior is correct

Assigning to @phet-steele.

**Comment by phet-steele** [comment]
@jessegreenberg @jbphet @amyh-phet This looks good to go!

Tested on:
iPad 2 iOS 9.3.4
OSX 10.11.6 Chrome
Win 10 Chrome

**Comment by jessegreenberg** [comment]
Thanks so much @phet-steele and @alynne-phet!
