### ISSUE TITLE
Boolean, Number and String should be lower-case

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#683]
I'm seeing a large number of

``` js
 @param {Boolean}
 @param {Number}
 @param {String}
```

These should be lower case.  There is no practical ramification at the moment, but this should be fixed.

**Comment by andrewadare** [comment]
Is Object supposed to remain capitalized? Seems inconsistent, but is in far more common usage.

A search for `@param {Object}` returns 1002 matches across 856 files.
A search for `@param {object}` returns 24 matches across 21 files.

**Comment by samreid** [comment]
Yes, according to http://usejsdoc.org/tags-param.html Object is uppercase (not a primitive).

**Comment by andrewadare** [comment]
Interesting cultural phenomenon how quirks inherited from C/C++ become formalized.

So the 24 `{object}` --> `{Object}` replacements should also be added to the list. Probably best to do all this some quiet evening to avoid merge conflicts.

**Comment by andrewadare** [comment]
I self-assigned this a while back, but realistically, I may not get to it for a while. Tagging for developer meeting to put it "up for grabs" and to see if there are any takers.

**Comment by andrewadare** [comment]
On second thought, I'll just do it soon and get it off my plate.
