### ISSUE TITLE
Verify Grade Level categories for HTML5 sims

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#684]
@ariel-phet @amanda-phet @amyh-phet @arouinfar If you would, please go through the HTML5 sims you are responsible for and verify their grade level categories are correct. Just go to their sim page and see which categories are bolded in the navbar, and make sure they are correct. If there is a problem, no need to change anything. Just comment here and I'll take care of the changes. Please check a sim off from the list after it has been checked. This shouldn't take more than a few minutes, thanks!

- [x] Acid-Base Solutions
- [x] Area Builder
- [x] Arithmetic
- [x] Balancing Act
- [x] Balancing Chemical Equations
- [x] Balloons and Static Electricity
- [x] Beer's Law Lab
- [x] Bending Light
- [x] Build an Atom
- [x] Color Vision
- [x] Concentration
- [x] Energy Skate Park: Basics
- [x] Faraday's Law
- [x] Forces and Motion: Basics
- [x] Fraction Matcher
- [x] Friction
- [x] Function Builder
- [x] Graphing Lines
- [x] Gravity Force Lab
- [x] Hooke's Law
- [x] Isoptopes and Atomic Mass
- [x] John Travoltage
- [x] Least-Squares Regression
- [x] Molarity
- [x] Molecules and Light
- [x] Molecule Shapes
- [x] Molecule Shapes: Basics
- [x] Neuron
- [x] Ohm's Law
- [x] pH Scale
- [x] pH Scale: Basics
- [x] Reactants, Products and Leftovers
- [x] Resistance in a Wire
- [x] Rutherford Scattering
- [x] Trig Tour
- [x] Under Pressure
- [x] Wave on a String

**Comment by arouinfar** [comment]
Done!

**Comment by amyh-phet** [comment]
@phet-steele   Only one change:

- [ ] Remove Elementary from Build an Atom

**Comment by amyh-phet** [comment]
Done!

**Comment by amanda-phet** [comment]
@phet-steele only one change: removed "high school" from Area Builder.

**Comment by phet-steele** [comment]
Thank you all!
