### ISSUE TITLE
dev test State of Matter 1.0.0-dev.10

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#687]
This sim is ready for a round of dev testing.  A lot of the internals of the model have changed in order to improve performance on devices like iPads, so making sure the model behavior is correct is probably the most important thing.  Quite a number of layout and other appearance issues have also been resolved, feel free to scan through the closed issue on the states-of-matter and atomic-interaction repos for more information.

Two things that should **not** be tested are:
+ the fast forward feature on the Atomic Interactions screen - this stands a good chance of going away, so no use spending time on it
+ the performance of water on the Phase Changes screen - this is a known issue and will continue to get attention

Here is a link:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.10/states-of-matter_en.html

Platforms:

- [x] iPad2
- [x] Mac Safari
- [x] Win Chrome

**Comment by ariel-phet** [comment]
moving to medium for the moment (since Atomic Interactions is closer to publication)

**Comment by ariel-phet** [comment]
Back up to high priority. Might get bumped if a new GAO version is put out for testing

**Comment by BryceAG** [comment]
phetsims/states-of-matter#149 and phetsims/states-of-matter#150 still occur with iPad 2 safari. Simulation gets very laggy with more than a few particles

**Comment by ariel-phet** [comment]
@phet-steele is this task complete since everything is checked off?

**Comment by jbphet** [comment]
Closing this, since a new dev version has been published and a task has been set up to test it, see #694.
