### ISSUE TITLE
Test Java of Gene Expression - The Basics

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#688]
@aadish is resuming the port of Gene Expression Essentials (title pending) and the legacy sim should be tested for any bugs. As usual, please report any issues in the Gene Expression Essentials repo and mark them as a "type:legacy-bug".

**Comment by ariel-phet** [comment]
Moving to low priority for now

**Comment by ariel-phet** [comment]
@phet-steele - progress is going steadily on the HTML5 implementation, moving this test to medium priority.

**Comment by phet-steele** [comment]
Testing did not reveal much, closing. 😢
