### ISSUE TITLE
RC Test: Charges and Fields 1.0.0-RC.6

### ISSUE THREAD

**Issue by andrewadare** [phetsims/tasks#689]
Charges and Fields 1.0.0-rc.6 is ready for RC testing.

After discussion with the developer team last week, it was decided to merge C&F master into an existing branch called 1.0, and also to keep around the old RCs to avoid any possibility of confusion. So that's what was done, and that's why we're starting here with RC.6.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.6/charges-and-fields_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.6/charges-and-fields_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/13LTW0wpaZcvWRPLFjQCwmkfbpkmFdqAlm65Mg5OpNl4/edit#gid=2070547191)**

**Please also verify**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/charges-and-fields and reference this issue.

**Comment by ariel-phet** [comment]
@phet-steele this sim should be current top testing priority (and hopefully publish soon!)

**Comment by phet-steele** [comment]
Now that everything should be compatible with the PhET menu screenshot feature, I'm adding that to the above list to verify.

**Comment by alynne-phet** [comment]
@andrewadare Matrix is complete!

**Comment by ariel-phet** [comment]
Testing complete, and @andrewadare working on publishing. Closing
