### ISSUE TITLE
Dev Testing for Record/Playback over Metacog for Function Builder 1.1.0-dev.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#690]
In https://github.com/phetsims/phet-io/issues/548 @kathy-phet said:

> Priority [amongst the math sims] is definitely Function Builder. So let's focus on getting that one tested and published to see if input/playback works.

We need to test that the simulation can deliver events to Metacog, and that we can retrieve and play back the events afterwards.

Steps are described in https://github.com/phetsims/phet-io/issues/566 and most discussion should take place in that issue, since this is a PhET-iO issue.  This tasks issue is for prioritization and assignment.

@ariel-phet can you please prioritize and assign?

**Comment by ariel-phet** [comment]
@samreid is there a timeline associated with this goal of which you are aware - did we promise delivery at a certain date?

**Comment by samreid** [comment]
I don't know when @kathy-phet hopes to run this study.  All I know is from @kathy-phet's comments in https://github.com/phetsims/phet-io/issues/548 and https://github.com/phetsims/phet-io/issues/553#issuecomment-241566676

**Comment by ariel-phet** [comment]
@phet-steele places at medium priority currently, but could change if @kathy-phet requires action sooner.

**Comment by samreid** [comment]
I asked @kathy-phet about priority today, and she said that sims destined for the PhET website are at a higher priority.  Function Builder/metacog is at relatively high priority compared to everything not destined for the PhET website.

**Comment by pixelzoom** [comment]
I just finished doing maintenance release 1.0.6 to patch phetsims/function-builder#107 and phetsims/function-builder#108., closed up the issue, and figured that I was done.   Then quite by accident, I ran across this issue.  I had no idea that here was a 1.1-phetio branch, or that it might need patching.  @samreid How should I proceed?

**Comment by samreid** [comment]
I don't know of any upcoming usages of the phet-io "lite" instrumentation, so I think it's fine to leave it alone.

**Comment by ariel-phet** [comment]
@samreid can this issue be closed?

**Comment by pixelzoom** [comment]
Note that the 1.1.-phetio branch should be considered obsolete.  It was not maintained and is way behind master and 1.0 branches.

**Comment by samreid** [comment]
We delivered a function-builder to Ian months ago, closing.
