### ISSUE TITLE
dev test Atomic Interactions 1.0.0-dev.12

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#691]
This sim is ready for some dev testing in order to weed out any obvious bugs before starting to do release candidates. 

Here is a link:
http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.12/atomic-interactions_en.html

Platforms:

- [x] iPad2
- [x] Mac Safari
- [x] Win Chrome

**Comment by ariel-phet** [comment]
@phet-steele this test should currently be next in line after #689 for sim testing (as it is quite close to being ready for RC)

**Comment by ariel-phet** [comment]
Making current top sim testing priority

**Comment by ariel-phet** [comment]
Testing complete, closing

**Comment by ariel-phet** [comment]
Emailed @jbphet about getting an RC going
