### ISSUE TITLE
Dev Test Gravity and Orbits 1.0.0-dev.30

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#692]
It has been a while since gravity-and-orbits was dev tested, and now would be a good time to find any remaining issues..

Link to sim: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html

Also please check the performance on a few of the slower devices to gauge the status of performance for this sim.

- [x] iPad2
- [x] Chromebook
- [x] Win Firefox
- [x] OSX Firefox

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
@phet-steele marking as high priority (atomic interactions will be top priority when that RC is ready)

**Comment by jessegreenberg** [comment]
Sorry for the late addition, but I just added OSX + Firefox to the list since there have been reports of high CPU usage for that platform.  If this sim is noticeably worse on that platform, we should decide if it should be addressed or not.

**Comment by ariel-phet** [comment]
@phet-steele would be good to finish this task by tomorrow EOB (9/27/2016)

**Comment by phet-steele** [comment]
@ariel-phet if this was finished by today (it won't be), this would still require another dev cycle. Keeping this one open for longer so we have a chance to flesh out its bugs and move toward rc.1.

**Comment by phet-steele** [comment]
@ariel-phet @jessegreenberg done. Lots of changes so another dev would be nice.

**Comment by jessegreenberg** [comment]
Thanks for the testing!  New dev version out shortly.  Closing.
