### ISSUE TITLE
high CPU usage on Mac + Firefox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#695]
As noted in https://github.com/phetsims/plinko-probability/issues/48#issuecomment-246032890, PhET sims in general are seeing high CPU usage on Mac + Firefox.

As noted in https://github.com/phetsims/plinko-probability/issues/48#issuecomment-246036398, Mac + Firefox accounts for 1.14% of sim usage (YTD).

Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
@amanda-phet @arouinfar I believe both of you have seen this behavior on sims. Are there any sims where you recall high CPU usage NOT occurring for Mac+FF?

**Comment by ariel-phet** [comment]
Marking for dev meeting for some quick brainstorming. We could consider dropping Mac + FF support.

**Comment by arouinfar** [comment]
@ariel-phet I recall seeing high CPU usage for Mac/FF in Bending Light, but can't remember any others (Chrome is my daily browser). 

@amanda-phet is a regular Firefox user, so she can probably say more about this particular issue.

**Comment by amanda-phet** [comment]
I only regularly open sims NOT in FF when dev testing, so no I can't think of sims with high CPU usage in places like Chrome or Safari.

**Comment by ariel-phet** [comment]
@amanda-phet, since you use FF regularly, I meant have you used any sims that when using FF do not have high usage. @pixelzoom seemed to report it appeared to be a general problem, so are you only seeing this on certain sims(high CPU) or on all sims. We are thinking it is a more general issue.

**Comment by amanda-phet** [comment]
Ah, yes that was unclear. 

Most sims do not have high usage. I remember ESPB and Bending Light both having high usage when I did dev testing.

**Comment by pixelzoom** [comment]
The sims that will have high CPU usage are the ones where the screen is updating frequently - e.g., there are a lot of continuously moving objects.

**Comment by pixelzoom** [comment]
9/15/16 consensus: Do nothing for now, revisit when a later version of FF 48 is released.

**Comment by ariel-phet** [comment]
Considering the age of this issue and no known user or QA complaints (as well as chrome being our dominant browser), closing
