### ISSUE TITLE
Plinko Probability: dev testing (round 1)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#696]
Ready for a dev test of Plinko Probability.  The dev version is:

http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.16/plinko-probability_en.html

There is no test matrix, and some testing on all supported platforms is desired. 

Of special interest:
• Are there issues on Edge?
• Are there multi-touch issues?
• Are there situations where performance is unacceptable (or could be improved) on iPad2?

If you find anything, please create GitHub issues (linked to this issue).

Terminology, useful when describing things in GitHub issues:
• Galton board, or "the board" - the triangular area
• hopper - the thing above the center of the board
• hopper mode buttons - the radio buttons to the right of the hopper on the Lab screen
• balls - the spheres that fall out of the hopper and bounce around on the board
• pegs - the things that the balls bounce off of on the board
• bins - the cylinders below the board, where balls stack up
• histogram - the graph below the board (occupies same space as bins)
• histogram mode bottons - the buttons to the left of the histogram, above the eraser button
• statistics panel - on the Lab screen, the panel that can be expanded/collapsed to show statistics
• play mode buttons - the radio buttons to the right of the green Play button

Assigned to @ariel-phet for scheduling and prioritization.

**Comment by ariel-phet** [comment]
Currently putting at high priority for the QA team since this sim appears close to RC testing

**Comment by pixelzoom** [comment]
Mentioning @amanda-phet so that she's in the loop. This sim is now in dev testing.

**Comment by ariel-phet** [comment]
Moving to current top testing priority

**Comment by pixelzoom** [comment]
All issues found during dev testing (linked above) have been resolved or deferred.

Discussed status with @phet-steele via Skype, and we both feel that we're ready to start RC testing. 

Closing.
