### ISSUE TITLE
RC Test: Friction 1.3.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#698]
The Friction sim wasn't able to support the screen shot feature due to its use of an outdated approach for rendering particles, see https://github.com/phetsims/friction/issues/35.  This has been resolved and a new version is ready for testing.

**Link to sim:**
http://www.colorado.edu/physics/phet/dev/html/friction/1.3.0-rc.1/friction_en.html

**Link to iFrame:**
http://www.colorado.edu/physics/phet/dev/html/friction/1.3.0-rc.1/friction_en-iframe.html

**Test Matrix:**
https://docs.google.com/spreadsheets/d/1xs2_pAvLnEGoC7a1a0IqD29B8gyhGyvBPaD9iCSSZJM/edit?usp=sharing

The code for particle rendering has changed dramatically, and the simulation will be using updated versions of all common libraries, so a pretty thorough test is required.  

Also, the screenshot capability should be verified on all platforms and the issue (https://github.com/phetsims/friction/issues/35) closed if the tests pass.

**Comment by ariel-phet** [comment]
bumping to medium as the sim is pretty easy to test, and the QA backlog is quite reduced

**Comment by phet-steele** [comment]
@jbphet, this sim is ready after phetsims/friction/issues/36.

**Comment by phet-steele** [comment]
This was deployed, closing.
