### ISSUE TITLE
Use `this` where appropriate

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#701]
In many circumstances, `self` is used instead of `this`.  For instance, I see 39 occurrences of this pattern:

```js
    var self = this;
    Node.call( self );
```

And there are other occurrences of `self` where `this` should be used instead.  We should endeavor to use `this` where appropriate.  I don't know a way to enforce this through lint, but perhaps I'll flag this for developer meeting to make sure others are aware of this concern, and we can add it to review and code style checklists.

**Comment by pixelzoom** [comment]
@samreid said:
>  We should endeavor to use this where appropriate.

We'll need to define what is "appropriate".

It sounds like your saying that "appropriate" is to use `self` only where a closure var is absolutely required.

But in some earlier code (e.g. beers-law-lab, molarity) I experimented with using the `self` alias everywhere, avoiding the use of `this` altogether, and that certainly made it less likely to use `this` where `self` was required.  I'm not saying that I like that approach (and I have since removed it from most of my sims), but I don't think it's necessarily inappropriate.

**Comment by samreid** [comment]
I agree there are some cases where `self` could be used instead of `this` even though `this` would work.  However, for cases where `self` is declared and *never* used in a closure, it would be inappropriate.

**Comment by pixelzoom** [comment]
> However, for cases where self is declared and never used in a closure, it would be inappropriate.

Agreed. When we switch to `self`, I attempted to eliminate unnecessary declarations of `self` throughout my sims and common code. I may have missed a few.

**Comment by pixelzoom** [comment]
Related to the title of this issue:
> Use `this` where appropriate

@samreid  Do you have something you want to propose? 

My opinion: It is appropriate to define `var self` only when a closure variable is necessary. When `self` is defined, it is then appropriate to use `self` either (1) wherever a closure variable is needed, or (2) consistently as an alias for `this`. Examples:

Inappropriate: no need for a closure variable
```js
function MyType( someProperty ) {
  var self = this;
  SuperType.call( self );
  self.somePropery = someProperty;
}
```

Appropriate: `self` used in closures
```js
function MyType( someProperty ) {
  var self = this;
  SuperType.call( this );
  this.someProperty = someProperty;
  this.someProperty.link( function( value ) {
    self.someFunction( value );
  } );
}
```

Appropriate: `self` used consistently as an alias for `this`:
```js
function MyType( someProperty ) {
  var self = this;
  SuperType.call( self );
  self = someProperty;
  self someProperty.link( function( value ) {
    self.someFunction( value );
  } );
}
```js

Inappropriate: `self` used inconsistently as an alias for `this`:
```js
function MyType( someProperty ) {
  var self = this;
  SuperType.call( self );
  this = someProperty;
  self.someProperty.link( function( value ) {
    self.someFunction( value );
  } );
}
```

**Comment by samreid** [comment]
Your proposal sounds good, the only one I see as controversial is the 3rd one.  I recommend that only `this` be used outside of closures, and use `self` a contextual cue that the code is inside a closure.  Let's chat on Thursday.

**Comment by pixelzoom** [comment]
I'm not a fan of Example 3 either, though I did experiment with it awhile back. That said, it does have the advantage that using `self` everywhere eliminates 2 common errors that occur when you mix `this` and `self`: (1) using `this` where you should have used `self`, and (2) forgetting to swap `this` and `self` when you move line of code in/out of closures.

**Comment by jonathanolson** [comment]
I'm also hesitant about example 3. If there's a decently sized function and we add a closure, I now have to change potentially a lot of lines. Then when I remove the closure, I have to changes a lot of lines again?

**Comment by pixelzoom** [comment]
9/22/16 consensus: 
(1) Define self only when a closure var is necessary.
(2) Use self only in closures.

@jbphet has previously noted this in the PhET Development Overview (Coding Guidelines).

Closing.
