### ISSUE TITLE
RC test: Plinko Probability 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#702]
@phet-steele, @ariel-phet, @amanda-phet Plinko Probability 1.0.0-rc.1 is ready for RC testing. (@phet-steele requested that I assign this directly to him with 'top' priority.)

Sim:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-rc.1/plinko-probability_en.html

iFrame:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-rc.1/plinko-probability_en-iframe.html

Test matrix:
https://docs.google.com/spreadsheets/d/1AqxWhgXNdqqbhadppBMznDt0KI7KBVIfuHlClj1RLnA/edit#gid=2

See [PlinkoProbabilityQueryParameters.js](https://github.com/phetsims/plinko-probability/blob/master/js/common/PlinkoProbabilityQueryParameters.js) for documentation of sim-specific query parameters.

See also the Terminology section of [implementation-notes.md](https://github.com/phetsims/plinko-probability/blob/master/doc/implementation-notes.md). This will be useful for creating and discussing issues, so that we're all speaking the same language.

In addition to the test matrix, please perform these specific tests on 1 or 2 platforms:

- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any issues are found, please link them to this issue.

**Comment by pixelzoom** [comment]
Note that that the 1.0 release branch is using this set of shas that have been previously vetted:
https://github.com/phetsims/forces-and-motion-basics/blob/2.1/dependencies.json

**Comment by brroberts1231** [comment]
@pixelzoom Matrix complete

**Comment by pixelzoom** [comment]
Closing.  Another RC test cycle will be required, to spot test #89 and #90.
