### ISSUE TITLE
Giving presentation to OIT 12 noon Oct 5.

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#704]
Vasa at OIT requested that we give a presentation at OIT regarding PhET technologies

Anyone free/interested (we will definitely do the talk, but obviously would prefer is someone is excited to present)

Possible topics:
- @jonathanolson presenting about scenery libraries
- @samreid or @andrewadare talking about iO features
- @jbphet talking more generally
- @jessegreenberg talking about a11y stuff

If you are definitely interested just note in this issue

**Comment by samreid** [comment]
Can you elaborate on why we were requested to give a presentation?

**Comment by ariel-phet** [comment]
@samreid OIT has been having a weekly presentation series. Vasa asked Kathy if we would be willing (he is our contact for the App and such at OIT). I think he is just trying to build more community

**Comment by ariel-phet** [comment]
![capture](https://cloud.githubusercontent.com/assets/4051174/18805273/eae64e24-81c5-11e6-9ad6-8b535e8f5a8a.PNG)
