### ISSUE TITLE
RC test: Plinko Probability 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#707]
Test version:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-rc.2/plinko-probability_en.html

This RC test does not require a full test matrix.  Spot testing of these issues will be sufficient:

- [x] Verify phetsims/plinko-probability#89 (QA credits) on 1 platform.

- [x] Verify phetsims/plinko-probability#90 (Balls frozen on board) on 3 platforms (1 Mac, 1 Win, 1 iPad).  Please note the platforms tested in an issue comment.

**Comment by pixelzoom** [comment]
Per @ariel-phet, assigning directly to @phet-steele.

Assign back to me when done.

**Comment by BryceAG** [comment]
@pixelzoom both issues have been fixed

**Comment by pixelzoom** [comment]
@BryceAG Please indicate which platforms you tested (OS + browser) for  phetsims/plinko-probability#90.

**Comment by phet-steele** [comment]
@BryceAG @pixelzoom I took a pass as well on macOS 10.12 Chrome, Win 10 Edge, and iPad 2 iOS 9.3.5. phetsims/plinko-probability#90 would not occur.

**Comment by pixelzoom** [comment]
Sim is ready for publication, closing this issue.  Tracking publication in https://github.com/phetsims/plinko-probability/issues/97.
