### ISSUE TITLE
Test-Issue #394

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/tasks#709]
Issue: Shy Labeling Text

Browser: Chrome

OS: Windows 10

Description: "My Isotope" text in the isotope making module moves away from any neutrons brought at or above it's level vertically-wise

Steps to Reproduce:

1.)Enter the isotope mixing module

2.)Grab any neutron from the bottom left bucket

3.)Drag it to the same vertical level as the "my isotope" text just above the atom outline

At any position, the text will always stay above the grabbed neutron

Additional Notes:
-Text can be brought off screen on a touch device 

RELATION:
https://github.com/phetsims/tasks/issues/708

Name: ‪Isotopes And Atomic Mass‬
URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.5/isotopes-and-atomic-mass_en.html
Version: 1.0.0-dev.5 2016-01-26 23:09:01 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"isotopes-and-atomic-mass":{"sha":"3d0c3bb9","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"e903fad2","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"shred":{"sha":"c1d4863f","branch":"master"},"sun":{"sha":"45c7d334","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"}}

**Comment by phet-steele** [comment]
Everyone say hi to @EthanWJohnson !!!!

**Comment by EthanWJohnson** [comment]
fixed?
