### ISSUE TITLE
Updating presentation to modern template

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#715]
@kathy-phet requested that the following presentation be updated to our modern template/branding (but content kept the same)

@phet-steele could you work on this or delegate to a student worker? Talk with @amanda-phet for the modern power point template.

[Mikes_PhET_NewFaculty_Nov2014.pptx](https://github.com/phetsims/tasks/files/548536/Mikes_PhET_NewFaculty_Nov2014.pptx)

**Comment by ariel-phet** [comment]
@phet-steele marking as low since not a rush, but would be good not to let slip too far into the future

**Comment by phet-steele** [comment]
> Talk with @amanda-phet for the modern power point template.

@amanda-phet, may you point me to where the correct template resides?

**Comment by amanda-phet** [comment]
@phet-steele [Here](https://drive.google.com/drive/u/0/folders/0Bz7jTh2s-5L5ZEZobm14aGpfRVE) is the current folder of presentation resources. You'll find a few different templates (one in ppt and the rest in keynote). There is also an illustrator file for the research schematic, which you may find helpful if any artwork needs to be created.

**Comment by lmulhall-phet** [comment]
I think this would be a good task for @megan-phet.

**Comment by lmulhall-phet** [comment]
Just to clarify, this is a backburner task. @amanda-phet told me this would also be a good task for @CWilson4960.

**Comment by CWilson4960** [comment]
@lmulhall-phet I'd be happy to work on this!

**Comment by lmulhall-phet** [comment]
Thanks, @CWilson4960. Again, not super high priority, so if you have other things you're doing for @amanda-phet, don't worry about this until you get some time. But if you have time to work on it, have at it.

**Comment by lmulhall-phet** [comment]
What's going on with this issue? Can it be closed?

**Comment by amanda-phet** [comment]
I uploaded the presentation to the template folder. Closing.
