### ISSUE TITLE
RC Testing for PhET-iO Batch

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#718]
From https://github.com/phetsims/phet-io/issues/724 we would like to RC test a large batch of PhET-iO simulations.  
- [x] faradays-law See https://docs.google.com/spreadsheets/d/1m6Zo5fQEBRDNFebTYTuq5NSTPGrhQpELkLg4PG4vVGs/edit#gid=2
- [x] concentration
- [x] color-vision
- [x] molecules-and-light
  https://docs.google.com/spreadsheets/d/12YDd291uDUoCHeVTc3FKxoNQkx9eiyg14cCYz31Fmjg/edit#gid=2
- [x] beers-law-lab
  https://docs.google.com/spreadsheets/d/1CVot9X_bW4fGCe77jRo3NuIPvixK7T9q9mQGf34uk38/edit#gid=2
- [x] capacitor-lab-basics
- [x] forces-and-motion-basics
- [x] energy-skate-park-basics

https://docs.google.com/spreadsheets/d/11f_g-or9NiZ12-u5JD6Y0qh1XiL0bOSLNbjXcZ5UWEo/edit?usp=sharing
- [x] circuit-construction-kit-black-box-study
- [ ] function-builder (PLAYBACK ONLY)
- [ ] proportion-playground (PLAYBACK ONLY)

**Comment by samreid** [comment]
Also assigning @ariel-phet so he is aware of this work.

**Comment by samreid** [comment]
Another recommendation for testing I forgot to mention to @phet-steele earlier.  Using the "Events: colorized" test on Chrome or Firefox, make sure that each object in the simulation gives a user interface event and a nested model event.  This needs to be done on one platform per sim, for each sim.

**Comment by samreid** [comment]
Also to test: In the instance proxies wrapper: do all of the objects in the simulation have a proxy in the wrapper?  (i.e. is everything instrumented?)

**Comment by samreid** [comment]
Beer's Law Lab RC is ready for testing:
http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.5.2-phetiorc.1/

**Comment by samreid** [comment]
@phet-steele please give us status updates during testing this so @zepumph can be ready with the next one when you are ready for it.

**Comment by ariel-phet** [comment]
@phet-steele should this issue remain open? Certainly the status should be changed?

**Comment by phet-steele** [comment]
This is okay to close.
