### ISSUE TITLE
Dev Test: Gravity and Orbits 1.0.0-dev.31

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#719]
Gravity and Orbits is ready for another dev test.

**Link to Sim:** http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html

A lot has changed since the last test, so please do a full test of this sim.  In addition, please verify that the following issues have been resolved:
- [x] https://github.com/phetsims/gravity-and-orbits/issues/233
- [x] https://github.com/phetsims/gravity-and-orbits/issues/230
- [x] https://github.com/phetsims/gravity-and-orbits/issues/226
- [x] https://github.com/phetsims/gravity-and-orbits/issues/220
- [x] https://github.com/phetsims/gravity-and-orbits/issues/207
- [x] https://github.com/phetsims/gravity-and-orbits/issues/168

Assigning to @ariel-phet to prioritize.

**Comment by brroberts1231** [comment]
@jessegreenberg Dev test for this version looks about done.

**Comment by jessegreenberg** [comment]
@brroberts1231 thanks very much.  If you have time, could you please review https://github.com/phetsims/gravity-and-orbits/issues/238 and close if acceptable?

**Comment by jessegreenberg** [comment]
Also, can #https://github.com/phetsims/gravity-and-orbits/issues/220 and https://github.com/phetsims/gravity-and-orbits/issues/207 be closed?

**Comment by jessegreenberg** [comment]
All the issues above were closed.  https://github.com/phetsims/gravity-and-orbits/issues/210 is the last thing I want to address before we are ready for an RC! Thanks a lot QA team.
