### ISSUE TITLE
Test Chrome Dev Tools for debugging Node

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#720]
I have often wanted a nice debugger for Node, and heard about the possibility of using Chrome Dev Tools for it.  I saw this link and wanted to take it for a test drive:

> Chrome DevTools can now hotswap (live edit) Node.js code natively, made a gif of how to try it out
> https://umaar.com/dev-tips/119-node-js-hot-code-swap/

**Comment by samreid** [comment]
I followed these directions:
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.z0veumm7n

Short summary: by running node from the command line with: `node --inspect --debug-brk index.js` it printed out a URL to open in chrome, which connected it to the dev tools, and I could see console output and user chrome dev tools.  Super awesome!  I wonder if there is a way to use this from grunt?

**Comment by samreid** [comment]
Wow, I put a debugger statement in chipper/Gruntfile and it worked very nicely when I launched it like so:

``
~/github/faradays-law$ node --inspect --debug-brk node_modules/grunt/bin/grunt 
``

![image](https://cloud.githubusercontent.com/assets/679486/19843472/68b49326-9ee8-11e6-8460-de069a34dcf0.png)

This seems like it will become an important part of my workflow when developing with node or grunt, and it seems likely to be beneficial to other team members as well.  I'll flag for developer meeting for discussion.

**Comment by jonathanolson** [comment]
That looks amazing, thanks!

Is there any way we could add a grunt flag to do this, or reuse --debug, so that all we would need to do would be:
```sh
grunt --debug
```

**Comment by samreid** [comment]
Maybe you can make a bash alias or script that could be used like this:

`dgrunt`

That script/alias would just call the `node --inspect --debug-brk node_modules/grunt/bin/grunt` command and pass options through.

**Comment by samreid** [comment]
@jbphet said this may be good to use for the installer builder, rosetta, etc.

**Comment by samreid** [comment]
If anyone wants to investigate the `dgrunt` or `grunt --debug`, go for it!

@pixelzoom suggests to parse the output and call `open` so it automatically pops open the browser?  This would work on Mac, there is probably another way to do this on Windows.

**Comment by zepumph** [comment]
@samreid and I were able to get this to run recently as `node --inspect-brk node_modules/grunt/bin/grunt` in a sim repo. Then all arguments afterward are args to grunt.

Then in the chrome dev tools, now there is an icon that appears when the debugger is listener on a port:
![image](https://user-images.githubusercontent.com/6856943/29252074-5e621d38-800d-11e7-8245-e1a7ba775899.png)

When you click that, you are taken to a dedicated chrome tools for debugging node code.

**Comment by zepumph** [comment]
`--inspect-brk` will pause in the debugger on the first line of code, where `--inspect` will just go, and the debugger will attach at some point during the run.

**Comment by samreid** [comment]
This is somewhat of a moving target as node/chrome evolve, but it's good to know it exists.  Closing.

**Comment by jbphet** [comment]
I use Chrome all the time for debugging rosetta (which is a Node.js server app), and it works well and has been extremely helpful.
