### ISSUE TITLE
Revisit latest batch of PhET-iO sims

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#724]
It was recommended to take a quick second pass at testing the batch of PhET-iO sims in #718 and phetsims/phet-io/issues/724. This would allot time for QA to report the issues that were otherwise deemed unworthy to pursue before the deadline. These include:

- Highlighting nodes that are not instrumented.
- Cleaning up sliders in Instance Proxies (their ranges and worthiness to be sliders at all).

Mentioning @samreid.
@ariel-phet please prioritize, note QA would not be actively looking for bugs. I'm already expecting this work to begin, at minimum, after #721. I'm not good at making truthful time estimates, but maybe a couple days?

**Comment by ariel-phet** [comment]
@phet-steele putting at medium priority for the moment, lets focus on QA testing for a few sim (FAMB, CL:B, and soon GAO and SOM) with the understanding the GAO and SOM will take priority once those are ready. There are not too many big sim tests on the horizon after those wrap up.

**Comment by ariel-phet** [comment]
@phet-steele I think at this point this issue is quite stale. What say you? If so go ahead and close

**Comment by phet-steele** [comment]
@ariel-phet I do not think this issue is stale, however developer work on resolving any issues with these sims is unlikely to happen anytime soon. By extension, I think QA time on this would be nice, but also somewhat wasted. Closing since it would be better to test when developers are ready (and it would presumably be one sim at a time, not a large batch).
