### ISSUE TITLE
Spot Check: Forces and Motion: Basics 2.1.0-rc.6

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#726]
Forces and Motion: Basics 2.1.0-rc.6 is ready for a spot check.

@phet-steele could you please spot check this version
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.6/forces-and-motion-basics_en.html

and make sure that these issues are fixed:
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/212
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/207

If so, this sim is ready for a redeploy.  The changes needed for the above issues are very small so a full RC is not necessary.

**Comment by phet-steele** [comment]
![greenlight](https://cloud.githubusercontent.com/assets/5863899/20154956/ec09d4fc-a686-11e6-9144-fa127496bbfc.png)

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, redeploy will now be tracked in https://github.com/phetsims/forces-and-motion-basics/issues/201.  Closing.
