### ISSUE TITLE
Capacitor Lab Basics 1.0.0-dev.36

### ISSUE THREAD

**Issue by andrewadare** [phetsims/tasks#729]
There have been a some big refactoring passes, layout changes, and a fix or two. The changes are tracked in CLB issues 150-158. A dev test is in order before submitting an RC.

Testing link:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.36/capacitor-lab-basics_en.html

Please test on the following platforms:

- [x] iPad 2
- [x] Win Chrome
- [x] Mac Safari

**Comment by ariel-phet** [comment]
@phet-steele putting at medium priority until #725 is complete

**Comment by ariel-phet** [comment]
moving back to high, as this sim is close to publication

**Comment by brroberts1231** [comment]
Dev test complete
