### ISSUE TITLE
bit.ly/phet-development-overview now points to a deprecated file

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#734]
bit.ly/phet-development-overview now points to a deprecated file, can this be fixed?

**Comment by samreid** [comment]
I have a bit.ly account, but cannot change the target of bit.ly/phet-development-overview:

![image](https://cloud.githubusercontent.com/assets/679486/20460610/46a571a2-aea5-11e6-9ed4-4835eef44e61.png)

I don't see any bit.ly account mentioned on unfuddle.  I don't remember who created this bit.ly shortcut.  Tagging for developer meeting to see if anybody else remembers, or has suggestions to work around this problem.

**Comment by mattpen** [comment]
http://support.bitly.com/customer/portal/articles/2191623?b_id=5612

This doesn't look possible, even if we had access to the account that created it:

> HOW DO I REDIRECT A BITLINK?
> When you shorten a link with Bitly, the Bitlink is considered permanent and does not have the capability of being redirected or deleted. 

Should we create a new shortened URL and replace the existing bit.ly links?  Another possibility is adding a redirect to a path from phet.colorado.edu.

**Comment by ariel-phet** [comment]
@mattpen I think creating a new shortened URL would be best.

**Comment by mattpen** [comment]
I created this link, http://bit.ly/2fjcG0D.  Do we need one that is human-readable?

**Comment by ariel-phet** [comment]
I would say create a new shortened URL and replace

**Comment by mattpen** [comment]
This was handled in https://github.com/phetsims/special-ops/issues/46
