### ISSUE TITLE
dev test Expression Exchange 1.0.0-dev.18

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#735]
This version is going to be used for interviews and sharing with teachers, so it should have a round of dev testing.  Please test only the first three screens, **not** the game screen, which is still in early development.

Link: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.18/expression-exchange_en.html

**Comment by ariel-phet** [comment]
@phet-steele when you get to this test, @jbphet may have a newer version, please adjust accordingly

**Comment by ariel-phet** [comment]
Reassigning to myself to discuss with @jbphet, my guess is there is a much more current version worthy of testing

**Comment by jbphet** [comment]
This is the latest version that is stable enough to trust for interviews.  I've been making major changes to the code that underlies the first three screens in order to add support for the game.  @ariel-phet - it's probably better for you to talk with @amanda-phet and see if any interviews are planned within the next few weeks.  If not, this can be closed.

**Comment by amanda-phet** [comment]
I plan to do interviews again once the game is ready. I think we can probably dev test again around that time.

**Comment by ariel-phet** [comment]
OK, closing in that case. We can make a test when we have the game ready.
