### ISSUE TITLE
Charges and Fields PhET-iO RC test

### ISSUE THREAD

**Issue by andrewadare** [phetsims/tasks#736]
Charges and Fields was omitted from the recent Pearson PhET-iO batch-deployment. I took the opportunity to bring the instrumentation up to date this week.

@phet-steele according to whatever schedule is appropriate, can you test this as was done for the other Pearson sims? There are no custom wrappers, just the standard set.

Testing Matrix:
https://docs.google.com/spreadsheets/d/1W2PT3koA-4McsbxEjrrq_fZJ1nKLBlHuIYTD62qOk7E/edit#gid=2

On spot:
http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-phetiorc.1/
On phet-server:
https://phet-io.colorado.edu/sims/charges-and-fields/1.0.0-phetio/wrappers/index/

There's a known Chrome bug that you may encounter: https://github.com/phetsims/charges-and-fields/issues/114. It's fixed in Canary (Chrome 56), but we haven't found a workaround in the meantime.

cf https://github.com/phetsims/phet-io/issues/863 and https://github.com/phetsims/phet-io/issues/865

**Comment by ariel-phet** [comment]
Marking low for the moment, until we clear a few high priority QA tasks

**Comment by ariel-phet** [comment]
@phet-steele, once #746 is complete this should move to the top of the sim testing line. Basically this test and app testing will be next top priorities

**Comment by phet-steele** [comment]
@ariel-phet @andrewadare there has been some solid coverage on this with some issues noted above. A session was sent to metacog to test playback of the sim, but the results of that test will not come until later. For now, testing can be done.

**Comment by ariel-phet** [comment]
@phet-steele thanks! Assigning back to @andrewadare (feel free to close unless you want to keep it open for tracking found issues)
