### ISSUE TITLE
Google docs to migrate (issue will remain open)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#739]
Please comment with a URL to a non-migrated file that is owned by phethelp@gmail.com I'll migrate the file to phet-docs@colorado.edu and organize it as needed.

**Comment by pixelzoom** [comment]
A few of the documents that I can't locate:

HTML5 Translation
https://docs.google.com/document/d/1YzO_sCKg_ndXqMBMuiVXj_H1So4FUGhZ0bTaIJFMpPg/edit

PhET Developer Meeting 2013
https://docs.google.com/document/d/1Lt0t9FxxmTXdqW4Qy1yrM66aI6GHsBCRftWNgHdCs1U/edit?usp=drive_web

HTML5 Developer Plan - Phase 1
https://docs.google.com/document/d/1sH5XB2kv1Te6XokebWJdmgZWW34k6mRPYPC_bTjQ1tU/edit

HTML5 Developer Plan - Phase 2
https://docs.google.com/document/d/14-jLhozybv7VMbGkf1Xj-YhtxaLkJLIiGwoZD65mAPU/edit

PhET hours 2010-2014
https://drive.google.com/drive/folders/0B0TcamSqEJ6EMHMwSW90cWgtUEE

Sim color scheme
https://docs.google.com/spreadsheets/d/1fd4O4Ec7vPpL3DisaXyPKm3BcZL78B3eyRE7cH-TpA8/edit?usp=drive_web

Sim Sponsorship
https://docs.google.com/document/d/1U4JI-6K1RU6hPoSZnt9JI27cwWC51go8oRCMAIo1tlg/edit

HTML5 and Tablet Design Considerations
https://docs.google.com/document/d/1oQ479vRtAq_2RXEG0M9N4AKtEJ-6ja8tfxAu-ifsQYk/edit#heading=h.dwlgqv1dlf5s

HTML5 Sim Navigation (initial Designs)
https://docs.google.com/document/d/1Dzj9HGARBVw5CIV8zq0o1DpXuV2UbXVAuxo07kJW2_Q/edit

PhET: HTML5 Porting Overview
https://docs.google.com/spreadsheets/d/1u4aX2yJRzGgIL2O17PqmcHgKOWMNQco8-lIUU6JYmQ0/edit

Acid Base Solutions
(Java design, owned by Kelly Lancaster)
https://docs.google.com/document/d/18z2Z3r-lGSzUTZPTZK58AyLaxzaVRGGUbqwDdE87wU8/edit

Balancing Chemical Equations Java
https://docs.google.com/document/d/1UgvPv_mPXxiDtAduYYe3KUIReFN1OcQBii5sA6_eSxA/edit?usp=drive_web

Capacitor Lab
(Java design)
https://docs.google.com/document/d/19o2BLVtr7ktFULYUiC4uIlmTmU-CSsIA3uHxE_29plw/edit?usp=drive_web

Dilutions
(Java design)
https://docs.google.com/document/d/1H9-ZJznqsh_YFwiRTsPGriqbcKo8AfNMRvq_y9m3dHo/edit?usp=drive_web

Molarity
(Java design)
https://docs.google.com/document/d/11Vdn8Lwgp0Pe4ozuPJgY_fboV-Vy7srg10BQcGOALPA/edit?usp=drive_web

Molecule Polarity
(Java design)
https://docs.google.com/document/d/1fzKjSF0yGmy9lCJ_zBZvWo3F6FqKpzy-EqaBh1EFyEk/edit?usp=drive_web

Beer’s Law Lab
(Java design)
https://docs.google.com/document/d/1F7un6uWdG9Nm41IUUjnRazFeNOTAbFlHKDLwgGQS7Qg/edit?usp=drive_web

Graphing Lines
(Java design)
https://docs.google.com/document/d/1551QblT5yKjIrkB9vQ-GFwXP-qby3Fo_yO1ksZFTNS4/edit

**Comment by pixelzoom** [comment]
"PhET Developer Meeting 2014" got renamed to "PhET Developer Meeting 2014.docx", and it's not a Word document, confusing.

**Comment by pixelzoom** [comment]
Redacted_Graphing_Lines (Java) is at https://docs.google.com/document/d/1551QblT5yKjIrkB9vQ-GFwXP-qby3Fo_yO1ksZFTNS4/edit.  It's "new version can be found link" takes you to parent directory https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc, which does not contain the migrated document.

**Comment by pixelzoom** [comment]
"Redacted_Fraction_Relationships" is at https://docs.google.com/document/d/1mGGp7fj2ECcK4YiIFx6NUe5-agUj2uyv_HvobiDbpHg/edit.  It's "new version can be found link" takes you to parent directory https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc, which does not contain the migrated document.

**Comment by pixelzoom** [comment]
"Redacted_Sugar and Salt Solutions Java" is at https://docs.google.com/document/d/1qaUmUgBL7oYkbg6TH8a47h7WGIzqHxi6lKzS2VRUlBA/edit. It's "new version can be found link" takes you to parent directory https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc, which does not contain the migrated document.

**Comment by pixelzoom** [comment]
Looks like the 3 comments above are a general migration problem. About half of the Java design documents that I've tried to find are missing.  And their "new version can be found link" all point to parent directory https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc, which is the "PhET Sim Design" directory.  We cannot afford to lose Java design documents - they contain information that is absolutely essential to sim porting.

**Comment by oliver-phet** [comment]
I updated the big list above to track when those are migrated. "PhET Developer Meeting 2014" name has been corrected.

Re: the Legacy design docs, we decided that the lead designer of the HTML5 version would be migrating the legacy docs. @amyh-phet @arouinfar @ariel-phet @amanda-phet See CM's comments above about missing legacy docs.

**Comment by pixelzoom** [comment]
How to create a PhET GitHub issue
https://docs.google.com/document/d/1snxCn_qN5lrlNc-0ZU-3Wp8dG3eoJx8mNzT5jfL4nuQ/edit

**Comment by oliver-phet** [comment]
@pixelzoom phethelp doesn't have access to:
Molecule Polarity (Java design) https://docs.google.com/document/d/1fzKjSF0yGmy9lCJ_zBZvWo3F6FqKpzy-EqaBh1EFyEk/edit?usp=drive_web

PhET hours 2010-2014 https://drive.google.com/drive/folders/0B0TcamSqEJ6EMHMwSW90cWgtUEE

Can you share those with phethelp so that I can migrate?

**Comment by pixelzoom** [comment]
Shared.

**Comment by oliver-phet** [comment]
Haven't had new migration docs. Closing for now.
