### ISSUE TITLE
Yotta sim message testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#741]
Please test to determine if there is any platform/browser-specific failures with the latest statistics code in simulations. All supported platforms should be tested.

This should consist of:
1. Open the simulation, and do a quick sanity check to ensure basic things work (check the About dialog in the menu?)
2. If dev tools (console) are available in the browser (most non-mobile browsers), open the dev tools and reload. If there are no dev tools, move to another platform/browser.
3. Report any warnings/errors that show up in the console/dev tools (no need to open issues).
4. If there is a network tab in the dev tools, open it up. There should be files named 'immediate.gif' and 'sanity.gif' (with query parameters) that were loaded successfully.

Please note any discrepancies in this issue (I'll create/handle anything that comes up).

Testing URL: http://www.colorado.edu/physics/phet/dev/html/chains/1.0.0-dev.3/chains_en.html

Platforms (from example testing matrix, please correct if it's not up-to-date):

- [x] iPad 2 - iOS 9.3.5 + Safari
- [x] iPad Air 2 - iOS 9.3.5 + Safari
- [x] iPad Air 2 - iOS 10.0.1 + Safari 
- [x] Mac OS X 10.9.5 - Safari 9
- [x] Mac OS X 10.10.5 - Safari 9
- [x] Mac OS X 10.11.6 - Safari 9
- [x] Mac OS X 10.11.6 - Firefox
- [x] Mac OS X 10.11.6 - Chrome
- [x] macOS 10.12 - Safari 10
- [x] macOS 10.12 - Firefox
- [x] macOS 10.12 - Chrome
- [x] Win 7 (laptop) - IE11
- [x] Win 7 (laptop) - Chrome
- [x] Win 7 (laptop) - Firefox
- [x] Win 8.1 (laptop) - IE11
- [x] Win 8.1 (laptop) - Chrome
- [x] Win 8.1 (laptop) - Firefox
- [x] Win 10 (laptop) - Edge
- [x] Win 10 (laptop) - Chrome
- [x] Win 10 (laptop) - Firefox
- [x] Chromebook - Chrome (latest)

**Comment by ariel-phet** [comment]
@phet-steele marking as high priority as this test would be good to verify before we move yotta over to our new server (bayes). Ideally please complete this week in parallel with finishing off CL:B testing.

**Comment by phet-steele** [comment]
Done, @jonathanolson. Everything had the two .gifs w/ query params.

**Comment by jonathanolson** [comment]
Thanks!
