### ISSUE TITLE
PhET app 1.1(4) testing - ensuring no or slow internet causes no issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#742]
@phet-steele version 1.1(4) of the PhET-app is now available on test flight, please make testing the app your top priority for 11/29/2016. There might be some minor tweaks before tomorrow, if so, I will update this issue accordingly (tweaks are summarized in https://github.com/phetsims/phet-app/issues/242 )

The new version of the app bundles all the sims into the app download. So for instance, it should now be possible to download the app, turn off the internet, and all works fine on first open even without internet).

It would be good to hammer thoroughly on the app in different scenarios, several of which will probably require removing the app and re-downloading it. In particular it would be good to try some of the following:

| | iOS 9 | iOS 10 |
| --- | --- | --- |
| Open without internet | &#10004; | &#10004; |
| Open with internet, then interrupt internet | | |
| Open with simulated slow internet | &#10008; | &#10008; |
| Simulate slow internet after opening | &#10008; | &#10008; |
| Toggle internet to break it whenever | &#10004; | &#10004; |

No need to look into voice-over at the moment, but do report any other issues if they are new.

**Comment by phet-steele** [comment]
Lowering priority until 1.1(5) is released. (It's on the way!)

**Comment by ariel-phet** [comment]
@phet-steele  will do, closing this one
