### ISSUE TITLE
Gravity Force Lab - phet-io test

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#743]
Gravity Force Lab was just instrumented for phet-io.  @samreid and I did a fair amount of testing as the work was being done, and now it would be good to have someone else make sure that we didn't miss or break anything.

Testing Matrix:
https://docs.google.com/spreadsheets/d/15Galf54GoI--GuRreo_p-hzIsZ7MlitRmiwc4dIUctg/edit#gid=2

EDIT: <s>This should be tested from master.</s>  It should be verified with all working phet-io wrappers, and the instance-proxies in particular should be carefully checked.

Assigning to @ariel-phet for prioritization and assignment.

**Comment by jbphet** [comment]
@phet-steele requested that the testing be done on a built version rather than from master, and I'm down with that, so I've built and deployed such a beast and it can be found at http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-phetiodev.1/.

**Comment by jbphet** [comment]
The GitHub issue for instrumenting this sim is https://github.com/phetsims/gravity-force-lab/issues/76.  @phet-steele - if this testing is successful, please close the issue in the GFL repo.  If not, assign it back to me.

**Comment by samreid** [comment]
I'm curious why testing was requested for a dev version instead of an RC version.  Is this getting ready for production?  Also, I recall gravity force lab was getting re-implemented as Coulomb's Lab was created.  So it may need re-testing?

**Comment by ariel-phet** [comment]
This issue seems way stale and problematic, closing reassigning parent issue to @jbphet
