### ISSUE TITLE
dev test States of Matter v1.0.0-dev.15

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#746]
Four issues were found during the previous dev test of States of Matter.  I've added code to address these issues and could use help in verifying them.  The sim should also be regression tested to make sure that the changes didn't introduce any new problems.

All of these issues were related to particle motion, particularly at low temperatures and/or with few particles, so those behaviors should get the most attention.

The issues are:
- [x] https://github.com/phetsims/states-of-matter/issues/179
- [x] https://github.com/phetsims/states-of-matter/issues/180
- [x] https://github.com/phetsims/states-of-matter/issues/181
- [x] https://github.com/phetsims/states-of-matter/issues/182

Please also test:
- [x] https://github.com/phetsims/states-of-matter/issues/176

If the issues are resolved, please go ahead and close them.

Link to sim: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html

**Comment by ariel-phet** [comment]
@phet-steele please make this the top sim testing priority after #742

**Comment by phet-steele** [comment]
@ariel-phet @jbphet testing complete.

**Comment by jbphet** [comment]
Thanks, closing.
