### ISSUE TITLE
Fix lint errors in non sim repos

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#747]
Carried from phetsims/special-ops#49:

Now that we have a `grunt lint-everything` we should start tackling the issues themselves. Currently there are 453 errors spread across all repos. The grunt task takes a while to run, so we created a `chipper/data/lint-everything.txt` that shows all the lint errors. assigning to @jonathanolson because he expressed interest in taking on his repos [here](https://github.com/phetsims/special-ops/issues/49#issuecomment-263815350).

IMPORTANT: When you fix some lint errors and want to update `lint-everything.txt` do these two commands:
`grunt lint-everything > lint-everything.txt`
`sed -i -e 's/PATH//g' lint-everything.txt` where 'PATH' is the path to your github repos
This second line will take out the path up to the github repos so that our personal file structure doesn't effect diffing lint-everything.txt.

**Comment by pixelzoom** [comment]
Quick link to see the current lint-everything.txt:
https://github.com/phetsims/chipper/blob/master/data/lint-everything.txt

**Comment by samreid** [comment]
> The grunt task takes a while to run, so we created a `chipper/data/lint-everything.txt` that shows all the lint errors.

Also, so we can track progress over time.

**Comment by samreid** [comment]
I fixed a lint issue above, unassigning myself for now.

**Comment by zepumph** [comment]
Alright there are 9 lint errors now showing in grunt lint-everything. I'm going to delete lint-everything.txt because it is no longer needed. @jonathanolson would you tackle the rest of them since they are mostly in tests. Also will you look at 'fastmath.js' for an example of how I got rid of many of the no-undef problems in test suites, I want to make sure that was an alright method. Thanks!

**Comment by jonathanolson** [comment]
I think we're planning on upgrading to a newer QUnit that doesn't use more than 1 global for tests. I'll also look at creating a top level global for use in unit tests.

**Comment by jonathanolson** [comment]
grunt lint-everything is now passing. Closing, will handle QUnit upgrade in the relevant issue.
