### ISSUE TITLE
test Build an Atom PhET-iO version for Georgia Tech collaboration

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#748]
@samreid and I have added PhET-iO instrumentation to the Build an Atom simulation that should allow it to meet the initial request from the Georgia Tech group that wants to work with it for sonification and other accessibility research.  The directory containing the instrumented version can be found here: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.3.0-phetiodev.1/.

The objectives for this version are described in https://github.com/phetsims/build-an-atom/issues/140.

The sim should be regression tested for basic functionality, especially on the first two screens (Georgia Tech isn't planning to work with the game at all yet).  It has been a while since anything was published from the master branch of this sim, so things could have crept in.  The sim should also be tested with instance-proxies and any other wrappers that will help to verify that the requests made in the issue linked above have been met.

**Comment by ariel-phet** [comment]
Placing at high priority, since it would be good to know any issues well in advance of the Georgia Tech milestone (but best to be done after #735)

**Comment by phet-steele** [comment]
@jbphet instance proxies and event wrappers both show the expected requests. Even though the sim is far from complete instrumentation, it should be well enough for Georgia Tech. Regression tests also proved stable.

**Comment by jbphet** [comment]
Thanks @phet-steele.  Closing.
