### ISSUE TITLE
Add '/* eslint-env node */ ' to all node files in the project

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#750]
From https://github.com/phetsims/perennial/issues/27:

First step is to go through and decide how much time this will take. If it is only to be a few hours, then I will just do it, otherwise I should pass this off to @ariel-phet to assign priority.

**Comment by zepumph** [comment]
This will involve removing iifE if there is one and the file is only used for node. And example of when NOT to remove the iife is `chipper/js/data/localeInfo.js` because it is used both in the browser and in node.

**Comment by zepumph** [comment]
In chipper I changed all files that had module.exports, but I didn't touch the requirejs-plugins folder because it looked like there was a reason that they were using AMD 'define' even though they didn't export to both global or window. @jonathanolson do you know anything about this, or could you point me in the right direction?

**Comment by zepumph** [comment]
Added to rosetta, perennial, chipper, installer builder, and yotta. @jbphet do you think there are any other repos that may have node code in them?

**Comment by jonathanolson** [comment]
Aqua, most Gruntfiles too. And some files are made to run in Node and in the browser (like the plugins).

**Comment by zepumph** [comment]
We decided earlier in this issue that we won't change the modules that were to be used in both. Do you think we should somehow @jonathanolson?

**Comment by jonathanolson** [comment]
What do you mean "change the modules"?

**Comment by zepumph** [comment]
'Change' meaning add env node to the top of these files. 'These files' (the modules) being those that are loaded both in the browser and in node, i.e. chipper/js/requirejs-plugins and chipper/js/data/localeInfo.js.

**Comment by zepumph** [comment]
Also @jonathanolson, most Gruntfiles that look like this:

```js
// Copyright 2016, University of Colorado Boulder

// use chipper's gruntfile
module.exports = require( '../chipper/js/grunt/Gruntfile.js' );
```

I thought wouldn't need these extra lines since they are so simple, do you disagree?

**Comment by zepumph** [comment]
@jonathanolson would you mind commenting on my thoughts about adding this to the Gruntfiles?

**Comment by jonathanolson** [comment]
> 'Change' meaning add env node to the top of these files, and include the global form of use strict. 

Sounds worth a try. Does eslint support a "node.js and browser" mode?

> I thought wouldn't need these extra lines since they are so simple, do you disagree?

I'm not worried about those files, so whatever helps them pass lint sounds good.

**Comment by zepumph** [comment]
@jonathanolson thanks for the recommendation, after some research I found that just as easily we can add `eslint-env node, browser`; there doesn't have to be just one. I think that is all of the node files in the project.

**Comment by zepumph** [comment]
Closing.
