### ISSUE TITLE
Test Energy Skate Park: Basics

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#751]
Internal renaming of variables was done in https://github.com/phetsims/energy-skate-park-basics/issues/358 and in https://github.com/phetsims/energy-skate-park-basics/issues/358#issuecomment-265312947 we decided it would be nice to test it out and make sure all is well.

Link:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.2.4-dev.3/energy-skate-park-basics_en.html

Tests only need to be run on one platform, because they are logic issues.  We are looking for incorrect behavior related to the skater physics, which may manifest as the skater stopping, falling through track, or the application crashing (due to undefined value access).  Assigned to @ariel-phet for priority and reassignment.

Please reassign https://github.com/phetsims/energy-skate-park-basics/issues/358 to me after testing completes.

**Comment by ariel-phet** [comment]
Marking low priority at the moment since we have more urgent needs in the testing hopper, will bump up as priorities allow.

**Comment by ariel-phet** [comment]
@phet-steele perhaps @maggiewiseman would be willing to work on this issue as it is quite stale

**Comment by phet-steele** [comment]
@samreid is the link above still viable to be tested, or do we need a more updated link?

**Comment by samreid** [comment]
Since these are sim-specific logic issues and one-platform testing, the link above is still good.

**Comment by phet-steele** [comment]
Alright, thanks @samreid. @maggiewiseman, can you look into this testing? Read the first post for the details.

**Comment by maggiewiseman** [comment]
yes! Will check it out @phet-steele later tonight!

**Comment by maggiewiseman** [comment]
@phet-steele @samreid  I played with the sim for about 4 hours over the last few days.  Other than the two minor issues I submitted (368 and 369), I could not find anything wrong. All seemed to be working as expected.

**Comment by samreid** [comment]
Excellent, thanks @maggiewiseman.  It seems like no new bugs were introduced in the refactoring so this issue can be closed.  We will continue with #368 and #369 separately.
