### ISSUE TITLE
Icons for inside the nav bar's phet menu 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#752]
We need very simple icons for:

- Take screenshot
- Full screen
- Report a problem

similar to what is drawn here: https://github.com/phetsims/a11y-research/issues/12#issuecomment-265805839

It would be ideal to have these completed in the next two weeks.

**Comment by ariel-phet** [comment]
@emily-phet kicking back to you. As a first course of action please identify if there are any "font-awesome" icons that would fulfill these needs. We use font-awesome in multiple other parts of the sim and this would be the simplest solution.

**Comment by terracoda** [comment]
And here's a slightly updated sketch with the "a" removed from "Report a Problem."

![sketch-phetmenu_02](https://cloud.githubusercontent.com/assets/1902116/21058871/971a16ea-be1a-11e6-9cab-e290e417f6b8.jpg)

**Comment by jessegreenberg** [comment]
@emily-phet @terracoda you can browse the list of Font Awesome icons here:

http://fontawesome.io/icons/

**Comment by terracoda** [comment]
Yep, I picked out the same ones. And then there is also an ellipsis

http://fontawesome.io/icon/ellipsis-h/

And if an icon is required for the PhET Website, I would recommend a link
http://fontawesome.io/icon/link/

Or the PhET version of the paper airplane
http://fontawesome.io/icon/paper-plane/
http://fontawesome.io/icon/paper-plane-o/

**Comment by emily-phet** [comment]
Great! These font awesome icons are perfect. The only one I'm unsure about is the paper airplane. Let's try creating the menu without the paper airplane. Ideally I think we'd be able not have this icon - I'd prefer to not make that menu link too attractive. I think we should only add the airplane if the menu is less usable or aesthetically off without it. (though if we need a visual icon there the airplane is a great idea!

**Comment by terracoda** [comment]
@emily-phet, I agree. I don't think we need an icon for the PhET Website link.

**Comment by jessegreenberg** [comment]
Great!  @emily-phet @terracoda can this issue be closed?

**Comment by terracoda** [comment]
Yep, I think, we are good.
