### ISSUE TITLE
RC Test: States of Matter 1.0.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#753]
@ariel-phet, @phet-steele, and @arouinfar, States of Matter 1.0.0-rc.1 is ready for RC testing.

Link to sim:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.1/states-of-matter_en.html

Link to iFrame:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.1/states-of-matter_en-iframe.html

Test Matrix:
https://docs.google.com/spreadsheets/d/15oDRy4E5kqXxhZVZSfU-EvZvm6eeZKMQAjcU_6B3ExU/edit#gid=2

This is the first RC, so a full test on all platforms is needed.

In addition, please verify that the following issues have been addressed:

- [x] https://github.com/phetsims/states-of-matter/issues/187
- [x] https://github.com/phetsims/states-of-matter/issues/176
- [x] https://github.com/phetsims/states-of-matter/issues/166
- [x] https://github.com/phetsims/states-of-matter/issues/71

Please also verify:

- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/states-of-matter/issues and reference this issue.

**Comment by phet-steele** [comment]
Finished. ☃️

**Comment by ariel-phet** [comment]
task for RC.2 has been created, closing
