### ISSUE TITLE
RC Test: States of Matter 1.0.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#755]
States of Matter 1.0.0-rc.2 is ready for RC testing.  This RC fixes for issues identified while testing v1.0.0-rc.1, so the focus should be to verify that those issue are resolved and to complete any testing that wasn't already performed on the previous RC.

Link to sim:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.2/states-of-matter_en.html

Link to iFrame:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.2/states-of-matter_en-iframe.html

Test Matrix:
https://docs.google.com/spreadsheets/d/15oDRy4E5kqXxhZVZSfU-EvZvm6eeZKMQAjcU_6B3ExU/edit#gid=1494117673

Issues to verify:
- [x] https://github.com/phetsims/states-of-matter/issues/202
- [x] https://github.com/phetsims/states-of-matter/issues/201
- [x] https://github.com/phetsims/states-of-matter/issues/200
- [x] https://github.com/phetsims/states-of-matter/issues/198
- [x] https://github.com/phetsims/states-of-matter/issues/197
- [x] https://github.com/phetsims/joist/issues/389

Also, an issue was logged about code duplication, and some code was consolidated related to setting the phases in order to address this issue.  So, the feature of the first screen that allows users to set the phase using the buttons should get some special attention.

- [x] verify setting of phases using buttons on first screen

**Comment by phet-steele** [comment]
![greenlight](https://cloud.githubusercontent.com/assets/5863899/21369542/aea90f16-c6c4-11e6-83ef-0049d343ae26.png)
