### ISSUE TITLE
RC Test: States of Matter: Basics 1.0.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#756]
States of Matter: Basics 1.0.0-rc.1 is ready for RC testing.  This is the first RC of the "basics" version, but the full version just went through the test-and-release process, so all of the code that underlies this simulation has been pretty well tested.  A basic verification on all supported platforms should be sufficient for this.

Link to sim:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter-basics/1.0.0-rc.1/states-of-matter-basics_en.html

Link to iFrame:
http://www.colorado.edu/physics/phet/dev/html/states-of-matter-basics/1.0.0-rc.1/states-of-matter-basics_en-iframe.html

Test Matrix:
https://docs.google.com/spreadsheets/d/1-bBeW6JcfLnAsxM4-EIeNVLn0rBcI8J1ph15_rvtT5g/edit#gid=2

**Comment by ariel-phet** [comment]
@phet-steele please create a testing matrix for this issue if you would be so kind. Sounds like a quick tests on platforms should do nicely for verification.

**Comment by phet-steele** [comment]
Matrix has been made.

**Comment by jbphet** [comment]
I received the following text message from @kathy-phet:

> Hi @jbphet,
>
> Sanity testing on SOMB completed!! @ariel-phet approved publication.
>
> Please publish to the main server when you have a chance.
>
> Then we'll do metadata and send the email announcement.
>
> Thanks!

Based on this, I assumed that RC testing is considered complete.  Closing.
