### ISSUE TITLE
The PhET-iO Sim Status looks like it isn't configured properly

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#757]
This document can only be accessed from my gmail.com account and not from my colorado.edu  account.  @amanda-phet or @oliver-phet can you please take a look?

https://docs.google.com/spreadsheets/d/1ToW8wc9zOFpMglIf63jB1j8YA9Qmh2dxNLH2Sm4qxEo/edit#gid=0

**Comment by phet-steele** [comment]
New link here https://docs.google.com/spreadsheets/d/1pU9izdNQkd9vr8TvLAfXe_v68yh-7potH-y712FBPr8/edit#gid=0

@samreid may close if everything is in order.

**Comment by samreid** [comment]
Looks great, thanks, closing.
