### ISSUE TITLE
How should we refer to the view coordinates?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#759]
In the Circuit Construction Kit, the coordinates of model objects matches the view.  These coordinates aren't "pixels" because of the scaling in joist.  Should we call these "view coordinates" or is there a better term?

**Comment by samreid** [comment]
It looks like I've used the term "screen coordinates" and "view coordinates" for this before.

**Comment by pixelzoom** [comment]
PhET sims typically have 2 coordinate frames: model and view.  So "model coordinates" and "view coordinates" seems appropriate.

**Comment by jbphet** [comment]
I have generally used the term "screen coordinates" to describe the coordinate system that corresponds to the layout bounds.

**Comment by pixelzoom** [comment]
"Screen coordinates" is an example of a view coordinate that applies to one node (ScreenView).  So I'd still argue that the more general term is "view coordinate".

**Comment by samreid** [comment]
"screen coordinate*" occurs 52 times across our repos. I'm also seeing some incorrect usages of "Pixels" such as in shred's AtomNode.  Area Builder also has this comment `// In screen coords, which are roughly pixels`.

**Comment by pixelzoom** [comment]
"view coordinate" occurs 126 times.

**Comment by jonathanolson** [comment]
My impression:

- View coordinates: The coordinate frame of the view, which is usually the local coordinate frame of the ScreenView.
- Screen/global coordinates: The coordinate frame in screen 'px', where (0,0) is the upper-left of the inside of the window. Goes down to (window.innerWidth,window.innerHeight) in the lower-right. You get here by applying the ScreenView's coordinate transform to view coordinates.

Also note that one 'px' (one unit in the screen/global coordinate system) may span multiple physical pixels (think of a retina device, where a 1px square contains 4 pixels). This is an important difference for manual Canvas operations and WebGL.

**Comment by jessegreenberg** [comment]
I generally think of "view coordinates", terms "model coordinate" and "view coordinate" run parallel to the MV* pattern to me.  I wasn't aware of the distinction in https://github.com/phetsims/tasks/issues/759#issuecomment-270520987.

**Comment by pixelzoom** [comment]
Screen coordinates is when something actually gets mapped to the screen.  View coordinates are relative to the "view" portion of the code, in PhET's case is scenery.  There is not (and should not be) a single view coordinate frame - hence the need for local, parent, and global coordinate frames in scenery.  As @jonathanolson said, in PhET sims the model coordinate frame is usually the ScreenView coordinate frame.  But I can think of plenty of example where this is not the case -- for example, a "box" like in RutherfordScattering, where model coordinates are mapped to coordinates relative to the box (and not the ScreenView).

**Comment by samreid** [comment]
From today's meeting: the "ScreenView coordinate frame" is the one that Joist scales up and down.

**Comment by samreid** [comment]
@pixelzoom said there is really no need to go back and update incorrect terminology, because it is generally clear that "pixels" means "ScreenView coordinate frame" in the appropriate context (though not when referring to canvas or webgl).
