### ISSUE TITLE
Replace {DOMElement} with {HTMLElement} or {Element}

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#760]
In phetsims/scenery#596 @samreid said

>This code refers to type DOMElement which does not exist. * @param {DOMElement} domElement - the parent element to linearize. Should this be HTMLElement or Element? If SVGElement can be used for accessibility, then we should use Element here.

A local search shows 29 matches for ```{DOMElement}``` across 8 files, mostly in scenery (and mostly added by me!).  These should probably all be switched to ```{HTMLElement}``` or ```{Element}```.

**Comment by jessegreenberg** [comment]
Replaced in the above commits.  Pinging @jonathanolson because a few were added by him.  If any of these should actually be DOMElement, please let me know but it seems the standard is HTMLElement or Element.  Closing.

**Comment by jonathanolson** [comment]
HTMLElement looks correct, thanks!
