### ISSUE TITLE
Dev test: CCK: Black Box Study 1.0.6-phetio

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#761]
Shima conducted some pilot testing last semester with 1.0.4-phetio and requested that we add wire stubs to the black box (https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/21) before her studies this semester.  I will be testing 1.0.6-phetio, but it would also get some light testing from @phet-steele since it's been awhile since he's had a go at CCK:BB.

Shima's Upcoming Studies:
* Jan 9th: Pre-test for study at Stanford (wire stubs nice to have, but not necessary)
* February: High school classroom study (wire stubs necessary)

@ariel-phet can you please prioritize this task?

**Links for testing**

Standard version:
https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.6-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines

With play/pause button:
https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.6-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&showPlayPauseButton

"Show Electrons" panel hidden:
https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.6-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&phet-io.expressions=[[%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,[false]]]

**Comment by arouinfar** [comment]
@phet-steele and I have completed testing. Back to you @samreid.

**Comment by samreid** [comment]
Thanks @arouinfar and @phet-steele, closing.
