### ISSUE TITLE
Dev test: Make a Ten 1.0.0-dev.15

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#762]
(NEW): Testing link: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.15/make-a-ten_en.html

(OLD): Testing link: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.13/make-a-ten_en.html

**Comment by phet-steele** [comment]
To the QA team, reviewing the adding logic for this sim may be helpful while testing. Second section of this document: https://docs.google.com/document/d/1CBjNti_ZArayAqulgwEQNQPDjJhsC_IR-gg5aGU3bpQ/edit

**Comment by jonathanolson** [comment]
Updated release to test: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.15/make-a-ten_en.html

**Comment by amanda-phet** [comment]
@phet-steele has the testing started for this sim yet? I am wondering about the priority because it looks like there are a few other dev testing tasks open already.

**Comment by phet-steele** [comment]
@amanda-phet it has indeed been in testing.

**Comment by kathy-phet** [comment]
Adding a high priority tag to this -- since it is close to publication if it can pass dev testing! Interviews done, code ready. 

However iPad App testing would be priority over this -- when that comes up.

**Comment by ariel-phet** [comment]
@phet-steele lets make this current top testing priority

**Comment by phet-steele** [comment]
@jonathanolson @ariel-phet @kathy-phet Done.

**Comment by jonathanolson** [comment]
Thanks for the testing!
