### ISSUE TITLE
QA testing for the scaled splash/progress bar screens

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#764]
See https://github.com/phetsims/joist/issues/382

I published http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-dev.3/faradays-law_en.html which demonstrates the resizing splash screen.  
UPDATE: new version described here https://github.com/phetsims/tasks/issues/764#issuecomment-278850431

This needs to be tested on all of our platforms, since we have never used CSS to resize the splash screen before (and indeed the splash screen is now loaded in a very different way through JS instead of HTML) and we would like to check the following:

* Does this make the splash screen take longer to appear? How much longer?
* Does this make the splash screen look aliased? How bad is it?
* Are there any rendering artifacts or problems on any platform?

On iPad, you can reshape the browser by rotating the device.

If it looks reasonable on each platform, we can move it from branches to master.  Assigned to @ariel-phet for scheduling/prioritization/reassignment.

**Comment by ariel-phet** [comment]
@phet-steele marking this task P2...it should be pretty quick to test on each platform, perhaps could be done in parallel with ESPB testing as you are on each platform? Just would be better to complete sooner than later so it can be moved to master.

**Comment by BryceAG** [comment]
On Win 7, IE the splash will pop up in the top left corner for a brief moment, then center itself. Happens regardless of window size.

**Comment by ariel-phet** [comment]
@phet-steele bumping to top since this would be good to finish off

**Comment by samreid** [comment]
To address https://github.com/phetsims/joist/issues/400 I published http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.3/energy-skate-park-basics_en.html

It can now be used for subsequent testing.

**Comment by samreid** [comment]
@ariel-phet what is the expected timeline for completing testing for this issue?

**Comment by ariel-phet** [comment]
@phet-steele can this be finished today?

**Comment by phet-steele** [comment]
@samreid @ariel-phet this has been chipped away as we go, and most everything runs well except for one issue that may be indicative of something more sinister: phetsims/joist/issues/407

Other than that, testing here is done.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll continue in the joist issue.
