### ISSUE TITLE
Testing for Circuit Construction Kit: Prototype 1.0.0-prototype.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#765]
See https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/29 and the sim is published at:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-prototype.2/circuit-construction-kit-dc_en.html

On 1/13/17 2:17 PM, @kathy-phet wrote:
> We can give an effective "RC" to Steel and see what he comes up with, and then reassess this idea. I'm sure he will find some bugs ... and it will depend on the severity of the bugs. Shima has used it a fair amount so far.

If I understand correctly, the main point of this test is to see if there are major physics or graphics issues on our standard platform set.  Minor issues will not be addressed (unless they also appear in master), but it would be nice to know about them so we can decide whether this version is worthy of being shared.

Assigning to @ariel-phet and @kathy-phet to clarify about what is desired for testing, and to prioritize/schedule/assign.

**Comment by arouinfar** [comment]
@samreid where should I log relevant issues, `circuit-construction-kit-dc`?

**Comment by samreid** [comment]
Yes, please log issues here: https://github.com/phetsims/circuit-construction-kit-dc/issues/new

**Comment by ariel-phet** [comment]
moving this task to low priority for the moment, many other priorities above it

**Comment by ariel-phet** [comment]
Closing this issue, as it will be superseded by a CCK testing issue @samreid will create soon.
