### ISSUE TITLE
Update Our Team page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#766]
We need to add @Denz1994 and remove Andrew. 

@Denz1994 I can take your photo today or Thursday if you have some time. Please come up with key words and a bio, following the guidelines here: https://docs.google.com/document/d/16cDM5qYaFXzddaG5JtJ5jyiib4rk4bKvpUJzkehXeM0/edit#heading=h.iu4exno4bfbw

**Comment by amanda-phet** [comment]
@phet-steele am I forgetting anyone?

**Comment by Denz1994** [comment]
I will have the bio complete for our photo on Thursday. Thanks!

**Comment by phet-steele** [comment]
@amanda-phet I know I'm going to regret saying this....but do we remove Trish? (ahh it pains me to even think of it!)

**Comment by amanda-phet** [comment]
We should ask @kathy-phet about that.

**Comment by Denz1994** [comment]
Just sent an email with my bio and keywords to @amanda-phet.

**Comment by amanda-phet** [comment]
Done.
