### ISSUE TITLE
RC Testing for Make a Ten 1.0.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#767]
@amanda-phet, @bethstade, @ariel-phet, Make a Ten 1.0.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.1/make-a-ten_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.1/make-a-ten_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1aWJdfQl7BV4-qWiBz-oN-mesnT4_6Eo0wO6l0ss3Oso/edit#gid=2)**

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/make-a-ten/issues and reference this issue.  
**(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?exploreNumbers=X` - Where X is a list of two numbers separated by a comma. They are used as the initial explore screen numbers

**Comment by ariel-phet** [comment]
Next in priority line after #768

**Comment by phet-steele** [comment]
To the QA team, reviewing the adding logic for this sim may be helpful while testing. Second section of this document: https://docs.google.com/document/d/1CBjNti_ZArayAqulgwEQNQPDjJhsC_IR-gg5aGU3bpQ/edit

**Comment by phet-steele** [comment]
@jonathanolson @amanda-phet @ariel-phet, rc done. Back to JO.
