### ISSUE TITLE
Fire artwork for Circuit Construction Kit

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#769]
@clmccutchan this would be the first high priority artwork task.

The original sim can be seen here:
https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc

Basically, when a battery is short circuited it catches on fire, and we need updated artwork.

A preliminary version of the HTML5 sim is here (thought not feature complete it will help give an idea of the new layout and look and such):
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-prototype.2/circuit-construction-kit-dc_en.html

For more detailed discussion, see this related issue:
https://github.com/phetsims/circuit-construction-kit-common/issues/72

Also, please get in touch with @arouinfar if you need clarification on anything.

In terms of preferred timeline, this week would be ideal if you have time.

**Comment by ariel-phet** [comment]
Assigning @arouinfar as well just so she is aware of this issue, and can get in touch with @clmccutchan as needed

**Comment by clmccutchan** [comment]
@ariel-phet  What's the best way to include images on tickets? jpg, screenshot, pngs?

**Comment by arouinfar** [comment]
@clmccutchan a screenshot is perfectly fine for initial feedback. Once the artwork is finished, you'll move it over to a folder on Google Drive, which I imagine @ariel-phet will set up for you. If you have any other questions about the artwork, please let me know!

**Comment by ariel-phet** [comment]
@clmccutchan screenshots are fine, although I prefer pngs

**Comment by clmccutchan** [comment]
@arouinfar Here's a screenshot with some possible options for the fire. Let me know what you think, and then I can combine feedback into a single image.
![769_fire_draft1](https://cloud.githubusercontent.com/assets/25354670/22344598/f0c3055c-e3b9-11e6-99c7-07c6908afd1c.png)

**Comment by arouinfar** [comment]
@clmccutchan these options are a great start! I'm leaning more towards option (2). I like its softer gradient and orange outline, but I have a few tweaks to suggest.

You've matched the Java look quite well, but I think a slightly less jagged flame would better match our modern aesthetic. I'd also like to see what it would look like with a flatter (though not completely flat) bottom. I think a flatter-bottomed flame will look a bit better when it gets layered over the circuit elements.

**Comment by clmccutchan** [comment]
@arouinfar Here's (2) with a flatter bottom and simplified flames. Let me know if those could be even more simplified.
![phet_circuitcontr_769_fire_2](https://cloud.githubusercontent.com/assets/25354670/22346534/b19bbaba-e3c1-11e6-8d73-79b27d34332b.png)

**Comment by arouinfar** [comment]
Looks good @clmccutchan! I'd like to take a look at the flame in context. Can you email me the .ai file? (Generally, you'll place .ai files into a designated Google Drive folder, but I think @oliver-phet is still in the process of getting you added to our Google group.)

**Comment by clmccutchan** [comment]
@arouinfar I just emailed the .ai file to you.

**Comment by arouinfar** [comment]
Everything looks good! Thanks @clmccutchan.
