### ISSUE TITLE
Get materials ready for Office Mix

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#772]
Tagging @ariel-phet 

Ideas:

- [x] Help Center entry ("How do I embed PhET simulations?")
- [x] Email to teacher users
- [ ] Social media posts
- [ ] Flyers for conferences?

**Comment by oliver-phet** [comment]
@ariel-phet Did you want to create social media posts for Office Mix?

**Comment by ariel-phet** [comment]
@oliver-phet I have echoed a few people who have mentioned office mix, but it does not seem like it has huge traction. I think an email to our users would be more powerful than a social media post. I think I would also forgo flyers personally.

**Comment by ariel-phet** [comment]
@oliver-phet I forget, did you already do an email?

**Comment by oliver-phet** [comment]
Yep, email was sent to all users 5/26:
<img width="472" alt="screen shot 2017-09-21 at 8 26 18 am" src="https://user-images.githubusercontent.com/5090275/30701042-91cbd9f4-9ea6-11e7-9f03-6d59c6fd8ea7.png">

**Comment by oliver-phet** [comment]
I agree, I think email was the priority. Is this all that needs done on this issue?

**Comment by oliver-phet** [comment]
No posts or flyers planned. Closing this issue.
