### ISSUE TITLE
Update on Yotta use

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#774]
A graduate student at Georgia Tech would like to include sim usage as part of her analysis of cultural aspects of PhET sims and resources this semester. Kathy mentioned that yotta was being updated, can someone let me know when the student would be able to access the database of sim and resource use, and what data (if anything) we might have access to in the meantime?

**Comment by ariel-phet** [comment]
@emily-phet I think you will need to discuss with @kathy-phet 

My general understanding is Yotta is slowly churning through data at the moment to remove hits from bots and generally get more accurate counts.

There is also an effort to move Yotta onto a new server we have, which should allow for faster processing. However there is still a fair bit to do for this move, it will likely be a couple weeks before the move is complete, things are running, and then seeing if the processing is faster. it could be quite awhile before access to "clean" data is available.

I believe the Yotta data "as is" can be accessed currently, but again you should discuss with @kathy-phet for details on the inaccuracies. 

Alternatively, google analytics can be used, although that can allow some qualitative comparisons, but there are multiple issues with getting "true" counts.

**Comment by emily-phet** [comment]
@ariel-phet I see. I misunderstood the comment from Kathy, I thought it was something wrapping as JO had time, not as elaborate a process as you describe. I'll check with Kathy.
