### ISSUE TITLE
RC Test Gravity Force Lab: 2.1.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#775]
@ariel-phet @oliver-phet @phet-steele Gravit Force Lab 2.1.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1/gravity-force-lab_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1/gravity-force-lab_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1dPp2zsj4WW577vQNgCnx9d3cPNxh_JrJj_EQ8CaNqOc/edit#gid=1973577447)**

**Issues to Verify** 
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/gravity-force-lab/issues/83
- [x] https://github.com/phetsims/gravity-force-lab/issues/73

If any new issues are found, please note them in https://github.com/phetsims/gravity-force-lab/issues and reference this issue.

This sim includes changes to the navigation bar from joist, as well as a few items in the PhET menu, so please be sure to test the menu as part of this test.

Assigning to @phet-steele and @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
@phet-steele plan for after #765

**Comment by phet-steele** [comment]
Done, back to @jessegreenberg

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, closing, next version for spot checking fixes will be ready soon.
