### ISSUE TITLE
Dev Test: Gene Expression Essentials 1.0.0-dev.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#776]
@ariel-phet 

This sim is feature complete and can have some testing flush out some bugs and unwarranted behavior. 
Performance still lags and would be using this dev release as benchmark to make performance better
 
Link to the Sim: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html

**Comment by ariel-phet** [comment]
Would be good to do after #767

**Comment by ariel-phet** [comment]
bumping to current top priority

**Comment by ariel-phet** [comment]
Moving back to top priority for the moment

**Comment by ariel-phet** [comment]
@phet-steele is this dev-test complete yet? Putting at current top priority again

**Comment by phet-steele** [comment]
> @phet-steele is this dev-test complete yet?

Yes testing is done, I was leaving it open as a personal reminder to discuss something with @aadish pertaining to this dev test. It doesn't need to be open for that anymore.

**Comment by aadish** [comment]
Thanks @phet-steele  and others for testing this, issues have been noted and working in them to fix,

closing this
