### ISSUE TITLE
RC Testing for Balloons and Static Electricity PhET-iO version 1.2.0-phetiorc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#777]
Link: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-phetiorc.2/wrappers/index/

This version needs spot checking and verification of some specific issues before sharing with collaborators/customers.  Those issues are:

- [x] https://github.com/phetsims/phet-io/issues/994
- [x] https://github.com/phetsims/phet-io/issues/996
- [x] https://github.com/phetsims/phet-io/issues/997

**Comment by jbphet** [comment]
Assigning directly to @phet-steele since this is fairly urgent and should be quick.

**Comment by phet-steele** [comment]
Issues verified, spot checked on macOS 10.12.3 Chrome. Back at you, @jbphet.

**Comment by jbphet** [comment]
Looks good.  I've published the production phetio version.  Closing.
