### ISSUE TITLE
Artwork for Equality Explorer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#778]
Hey Cheryl, We are working on a sim about solving equations (and maintaining equality) and I need a balance. I'm currently using a very simple triangle with two flat lines for "plates" to get the point across: 
![screen shot 2017-02-01 at 1 47 13 pm](https://cloud.githubusercontent.com/assets/7852916/22525633/2783b7f6-e885-11e6-8e05-fd6f7147b340.png)

but something more like the image below would make sense (but should fit in with our "cute" PhET style.. perhaps a bit less 2-D, and maybe brown?). It shouldn't have too much visual weight, though, since it is not an interactive element in the sim. 
<img width="219" alt="8b03f7c4d94fcbeadf470d48ce79bc1150e5c340" src="https://cloud.githubusercontent.com/assets/7852916/22525652/4a69a884-e885-11e6-9d67-922950df38af.png">

A few things must be included: 
1. the fulcrum must be slightly above the horizontal of the balance (as you see here in Balancing Act)
![screen shot 2017-02-01 at 1 53 11 pm](https://cloud.githubusercontent.com/assets/7852916/22525962/a6d452e4-e886-11e6-988f-b738ba4c1f51.png)

2. Each plate needs to have some sort of joint since the plate can remain flat even while unbalanced

Please let me know if you are free to discuss this over Skype one day! I just wanted to be sure I made an issue here as a starting place.

**Comment by clmccutchan** [comment]
@amanda-phet It looks like the scale will need to have 3 illustrated pieces: the base, the horizontal stick, and a plate (the plate would be used twice). Sure I'd be able to discuss over Skype. My schedule tomorrow is a bit weird, but I would have time between 1-2 Thurs or Friday (Feb 3) anytime after 10.

**Comment by amanda-phet** [comment]
Updated mockup based on today's conversation: slightly taller fulcrum and showing an exaggerated balance (ignore the misalignment between the readout and what is on the scale!) 

![screen shot 2017-02-06 at 2 39 19 pm](https://cloud.githubusercontent.com/assets/7852916/22668425/f3a054b0-ec7d-11e6-883a-ef9e8dbfc5bc.png)

**Comment by clmccutchan** [comment]
![scale](https://cloud.githubusercontent.com/assets/25354670/22720770/0f10f9ce-ed6a-11e6-9398-a1fe7978134e.png)
@amanda-phet Here's a first stab at the scale. The base, cross bar, and pans are separate elements that can move independently.

**Comment by amanda-phet** [comment]
I like the style of this a lot! I put a screen shot into the design and it looks pretty nice. 
![screen shot 2017-02-15 at 1 36 33 pm](https://cloud.githubusercontent.com/assets/7852916/22994424/1e90c15c-f384-11e6-91cc-123083ae7bae.png)

A few details are still needed:
1. The joint at the fulcrum should look like it can move, and be slightly higher than the horizontal bar
2. The joint where the vertical plate-holders and the horizontal bar meet should also look "flexible" since the angle where those two pieces meet will vary. 

Let me know if we should discuss over zoom for clarification. Otherwise, feel free to drop a screenshot here!

**Comment by clmccutchan** [comment]
@amanda-phet It actually might be helpful to chat over zoom tomorrow or Fri so we can figure out how to make the joints more flexible. Thursday's weird for me but I'll give you some times anyway.

Thurs: 8:15-9:15, 12:15-2
Friday: anytime between 8:30 and 3:30

**Comment by clmccutchan** [comment]
@amanda-phet  Take a look at this draft of the scale. What do you think? If you like it, I'll send you the .ai file.

![scale](https://cloud.githubusercontent.com/assets/25354670/23075820/217ad86c-f4fb-11e6-95db-5ff3d747e8c4.png)

**Comment by amanda-phet** [comment]
I was thinking the hinge would be at the meeting place for the plate stand and horizontal bar. Can you also make a version like this? I'll run both by the design team and see what feedback they have. 

![screen shot 2017-02-20 at 9 10 37 am](https://cloud.githubusercontent.com/assets/7852916/23132990/aac77c9e-f74c-11e6-864f-11bcca4ab758.png)


Thanks!

**Comment by clmccutchan** [comment]
@amanda-phet How about this instead?
![scale](https://cloud.githubusercontent.com/assets/25354670/23138685/f99e3e84-f765-11e6-961c-e79534b9710c.png)

**Comment by amanda-phet** [comment]
Thanks @clmccutchan . Now that I see it I realize that doesn't work as well as I thought.. let me show these to some design team members to get feedback and I'll be in touch about further tweaks!

**Comment by clmccutchan** [comment]
@amanda-phet Most pan balances have some kind of rod under each pan to keep it aligned vertically. I wonder if there is some way to design the scale like that. Maybe that's the problem with the hinges; it looks like the pans can just flop over to the sides.
![images-5](https://cloud.githubusercontent.com/assets/25354670/23178608/5b9b34ee-f828-11e6-8918-cbd9fe0a28fd.jpeg)
![unknown](https://cloud.githubusercontent.com/assets/25354670/23178641/798fad0e-f828-11e6-85b6-7d80f5dd4ac4.jpeg)

**Comment by amanda-phet** [comment]
I agree- it does seem floppy! 

The rod might be a good way to go... I just wanted the balance to look clean and not distracting from the important stuff (the items ON the balance). Perhaps we could make it gray/steel instead of brass, give it a base (I prefer something like the second picture but maybe shorter vertically), put the pans on a vertical rod, and put something in the center that would help us cue when the balance is in fact balanced. These look like they have a pin that moves- I like that. When the pin is centered (balanced) it could be a bright bold color. 

Do you feel like you have enough info here to try a new balance?

**Comment by clmccutchan** [comment]
@amanda-phet  I think so. The two examples I put up have a lot of extra parts that aren't needed in a cartoon scale. I'll make a super simple example so we can get the lengths of the components correct. Then, I can doll it up a bit once you're happy with the general proportions.

**Comment by clmccutchan** [comment]
@amanda-phet You did have a scale in the comment above (ahttps://github.com/phetsims/tasks/issues/778#issue-204703710) that is fairly simple. Want to go back to that design without the stabilizing rods?

**Comment by amanda-phet** [comment]
Let's try the stabilizing rods. The scale I included was a starting point, but the plates would likely get in the way of the horizontal bar when unbalanced. However if the new ideas are proving difficult feel free to try whatever you want!

**Comment by clmccutchan** [comment]
@amanda-phet I'm trying to envision how the scale will move in the animation and did one little mock-up in Flash. No rods, but I can alter the components really quickly to add them. what do you think?

**Comment by clmccutchan** [comment]
@amanda-phet  Eeek! I think I just did something bad to this ticket! I may have

**Comment by amanda-phet** [comment]
The team really liked the scale you emailed to me that was animated. A few tweaks: 

1. If the vertical bar holding the plate can be shorter but still accommodate the maximum tilt, let's make it a tiny bit shorter. 
2. The vertical post in the center can probably be shorter - perhaps just to the horizontal bar?
3. Can you change the point of rotation to the *base* of the red arrow rather than the middle of it? Not sure if that matters or not for the .ai file but if it does that would be helpful. 

The ultimate scale will probably be drawn in code in the sim, but the .ai file will be most helpful for me in my mockups. I think that after the tweaks above are done we should be done with the balance! Please feel free to email it to me or drop in your drive folder (if you have access now). Thanks!

**Comment by clmccutchan** [comment]
@amanda-phet Here's a new draft of the scale. I'll send you an animation via email so that you can see its range of motion.
![scale](https://cloud.githubusercontent.com/assets/25354670/23377511/84ad9df8-fced-11e6-99fa-6f2bcc72f37b.png)

**Comment by clmccutchan** [comment]
@amanda-phet  I think I've successfully put the .ai file in my shared drive. Let me know if you need me to tweak some more things.

**Comment by amanda-phet** [comment]
Thanks @clmccutchan this looks great! I'll go ahead and close this issue.
