### ISSUE TITLE
Add more screenshots to each HTML5 sim repository

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#779]
@phet-steele this is a bit of a "chip-away" task, but would be useful to do any time you are testing a sim, or need to do something semi-mindless for a bit

When we implement the new web design we will want more screenshots of sims, and more immediately, customers have asked for more screenshots on our Edmodo posts.

**Screenshot Guidelines**
1. Maximum of 3 more screenshots (for a total of 4 including the existing one)
2. For multiple screen sims we should ideally show each screen  
3. Screenshots should not "give too much away" but be visually interesting (ie not an answer to a game)  For some sims 4 total screenshots may be a stretch (ie John Travoltage), we should add at least one   more, but use your discretion
4. As usual use a retina iPad
5. A naming convention will be necessary, perhaps `sim-name-screenshot-2` or such. Currently the screenshot file is not numbered, so perhaps additional ones start at 1 and go up?

- [x] Acid-Base Solutions https://github.com/phetsims/acid-base-solutions/commit/ad1f952d42eab425afb206e54ea4e24a6275d665
- [x] Area Builder https://github.com/phetsims/area-builder/commit/64db584ac800c0ebc9d6ae399a96132d4d76ccbc
- [x] Area Model Algebra https://github.com/phetsims/area-model-algebra/commit/bd6bc1f3848f8efab369b943cace8d3f99a4e276
- [x] Area Model Decimal https://github.com/phetsims/area-model-decimals/commit/5c53a8d60e15ee82e8840511e537bda4b953102f
- [x] Area Model Introduction https://github.com/phetsims/area-model-introduction/commit/9e96d5ba751cdaa078cf66b8e1e4031f37048a74
- [x] Area Model Multiplication https://github.com/phetsims/area-model-multiplication/commit/5650aa33ad4d819e43313b106cea78666c5e278a
- [x] Arithmetic https://github.com/phetsims/arithmetic/commit/a936415161b97b3f395d2439e075d65f19df70dc
- [x] Atomic Interactions https://github.com/phetsims/atomic-interactions/commit/f0e59b740c96a2b5c2ab48bc91b919297c0b2eb1
- [x] Balancing Act https://github.com/phetsims/balancing-act/commit/fe6fe8dfb5fd31251c116c33889e302a964d7d46
- [x] Balancing Chemical Equations https://github.com/phetsims/balancing-chemical-equations/commit/eae0f3f5814532ab4430f14f843730d566fc85ec
- [x] Balloons and Static Electricity https://github.com/phetsims/balloons-and-static-electricity/commit/4e72e6ab4dee0dc226280a9f56a1ff5e9dfc60ec
- [x] Beer's Law Lab https://github.com/phetsims/beers-law-lab/commit/80a9183619d4eb09fb2692d89d508bdba327360b
- [x] Bending Light https://github.com/phetsims/bending-light/commit/f590fe010e484bcf2b5f00fee4a81e4220e441e9
- [x] Build an Atom https://github.com/phetsims/build-an-atom/commit/34970eb445058dc92c4409b0d240b6f4e2acf32d
- [x] Capacitor Lab: Basics https://github.com/phetsims/capacitor-lab-basics/commit/e3eaa641452c937d1e3554fb1204ec6fea8d16da
- [x] Charges And Fields https://github.com/phetsims/charges-and-fields/commit/074befdb16372e1c4710dce57d58ec7713adb260
- [x] Circuit Construction Kit: DC https://github.com/phetsims/circuit-construction-kit-dc/commit/8a1f3b0f1f2e0ae076116cecaea4455e78e1fee2
- [x] Circuit Construction Kit: DC - Virtual Lab https://github.com/phetsims/circuit-construction-kit-dc-virtual-lab/commit/d636b72cfcf42189cf0211bd8c07721bcf7040c3
- [x] Color Vision https://github.com/phetsims/color-vision/commit/f383688744ee7a1cb5b557cdf8f44e40921263c1
- [x] Concentration https://github.com/phetsims/concentration/commit/b4073dc889cc1607ddb1f44ec6f0c8bfa743a912
- [x] Energy Skate Park: Basics https://github.com/phetsims/energy-skate-park-basics/commit/93c0486e9baa7c8cdae42e57e0454097754a1158
- [x] Expression Exchange https://github.com/phetsims/expression-exchange/commit/fb4c8c02e4f0db35f8630fcb01646e3ae5487753
- [x] Faraday's Law https://github.com/phetsims/faradays-law/commit/499906581125512fcdfed95188b30416b45b2d56
- [x] Forces and Motion: Basics https://github.com/phetsims/forces-and-motion-basics/commit/0746ed27bb04ad14f821382bf64d35b47b911d02
- [x] Fraction Matcher https://github.com/phetsims/fraction-matcher/commit/dae4320724e3ceaa3d5da274273b0da74a6ad5be
- [x] Friction https://github.com/phetsims/friction/commit/070e1057be622d6d960a374c880304fa2ecba75b
- [x] Function Builder https://github.com/phetsims/function-builder/commit/c19c37cced479d83349a293e4a7a6644aaa83d87
- [x] Function Builder: Basics https://github.com/phetsims/function-builder-basics/commit/aabdc48260b4f66258db8fd32fccf8fde2a43f57
- [x] Gene Expression Essentials https://github.com/phetsims/gene-expression-essentials/commit/cf72efb4f6c62d8830d2b26f657c9217e539b080
- [x] Graphing Lines https://github.com/phetsims/graphing-lines/commit/5af80f760c834420f4e8ba613bd30e6134f3b5e2
- [x] Graphing Slope-Intercept https://github.com/phetsims/graphing-slope-intercept/commit/b7d552a2f5795d6783be4b07e8c875113bab8bb4
- [x] Gravity And Orbits https://github.com/phetsims/gravity-and-orbits/commit/4a542071156fcdc65eb7a6686b3849fa0e825235
- [x] Gravity Force Lab https://github.com/phetsims/gravity-force-lab/commit/684c24467f8133b6a44ef37513aad2a11d82c2bc
- [x] Hooke's Law https://github.com/phetsims/hookes-law/commit/3cc43b13b6b021479ec8b5421a362c7cccde608c
- [x] Isotopes and Atomic Mass https://github.com/phetsims/isotopes-and-atomic-mass/commit/d0407465bbe3327f1ae2907035d5c6d453cd11d4
- [x] John Travoltage https://github.com/phetsims/john-travoltage/commit/997ef0f618c057559515eae48fcf6aa19328d1d1
- [x] Least-Squares Regression https://github.com/phetsims/least-squares-regression/commit/c3d828f8d3a1d98169d6732ef251330bff3ce892
- [x] Make a Ten https://github.com/phetsims/make-a-ten/commit/061a1449c4b2e0426340f5eeab5d497e1341294d
- [x] Molarity https://github.com/phetsims/molarity/commit/36126e63dd1e96d91f4b6996108fabadde8c14b0
- [x] Molecules and Light https://github.com/phetsims/molecules-and-light/commit/6afc3fa81a3f5b044217c7b290567471a148735c
- [x] Molecule Polarity https://github.com/phetsims/molecule-polarity/commit/15ca54766878c049837c203f00d2407814e81072
- [x] Molecule Shapes https://github.com/phetsims/molecule-shapes/commit/b38edca20011b221c87ae2eea0bca970604739f0
- [x] Molecule Shapes: Basics https://github.com/phetsims/molecule-shapes-basics/commit/30387bf6e183014569709b9b2bc3aa78cafe6592
- [x] Neuron https://github.com/phetsims/neuron/commit/1616407df114e43bf5a856b371fd77f44913a857
- [x] Ohm's Law https://github.com/phetsims/ohms-law/commit/e1e5643876b71f96bb4fd9fe0f84ac858877db26
- [x] Pendulum Lab https://github.com/phetsims/pendulum-lab/commit/4da2c92646d305946c018b5191ef92e1deae62f8
- [x] pH Scale https://github.com/phetsims/ph-scale/commit/9ddb3462db34502cf06d0e6070bd29c377bd3689
- [x] pH Scale: Basics https://github.com/phetsims/ph-scale-basics/commit/40cbdc4c8d25baedf14e22fb70d1995cecf6ec90
- [x] Plinko Probability https://github.com/phetsims/plinko-probability/commit/5008c76d6d0701fc715463d0ea85c8e056968af7
- [x] Projectile Motion https://github.com/phetsims/projectile-motion/commit/661ac7121f87b668a6dd05b3fe36a88653bc99b6
- [x] Proportion Playground https://github.com/phetsims/proportion-playground/commit/931c905b038610aaccfc2e5b20ec8f3ea7123790
- [x] Reactants, Products and Leftovers https://github.com/phetsims/reactants-products-and-leftovers/commit/7f1d1db8faa1dbca13ce3950442c57e0217dfdf3
- [x] Resistance in a Wire https://github.com/phetsims/resistance-in-a-wire/commit/8fe1146f412763763f4b9c8aa50f1fb1b2d54c58
- [x] Rutherford Scattering https://github.com/phetsims/rutherford-scattering/commit/fe12ad9921e63d835a1332398d488803d6fa3457
- [x] States of Matter https://github.com/phetsims/states-of-matter/commit/bd836a4b9455c565a64f60643bc2057075f2e87d
- [x] States of Matter: Basics https://github.com/phetsims/states-of-matter-basics/commit/30fc8bccb4ab8528dcd25ba2764c9136b8feae27
- [x] Trig Tour https://github.com/phetsims/trig-tour/commit/f79206be69d6b95b42e86254c68f92bde3e920a2
- [x] Under Pressure https://github.com/phetsims/under-pressure/commit/4539917a164f1f299893739b33ee5bc5bed7f52f
- [x] Unit Rates https://github.com/phetsims/unit-rates/commit/48dc4b5d414b2b54d10daa9d0d605add63ea48e2
- [x] Wave on a String https://github.com/phetsims/wave-on-a-string/commit/0541c2e436b6b0c8d62eb57bcf75fdba96b9464d

**Comment by ariel-phet** [comment]
- test 
- test

**Comment by ariel-phet** [comment]
- [ ] Acid-Base Solutions
- [ ] Area Builder
- [ ] Arithmetic
- [ ] Atomic Interactions
- [ ] Balancing Act
- [ ] Balancing Chemical Equations
- [ ] Balloons and Static Electricity
- [ ] Beer's Law Lab
- [ ] Bending Light
- [ ] Build an Atom
- [ ] Charges And Fields
- [ ] Color Vision
- [ ] Concentration
- [ ] Energy Skate Park: Basics
- [ ] Faraday's Law
- [ ] Forces and Motion: Basics
- [ ] Fraction Matcher
- [ ] Friction
- [ ] Function Builder
- [ ] Graphing Lines
- [ ] Gravity And Orbits
- [ ] Gravity Force Lab
- [ ] Hooke's Law
- [ ] Isotopes and Atomic Mass
- [ ] John Travoltage
- [ ] Least-Squares Regression
- [ ] Molarity
- [ ] Molecules and Light
- [ ] Molecule Shapes
- [ ] Molecule Shapes: Basics
- [ ] Neuron
- [ ] Ohm's Law
- [ ] pH Scale
- [ ] pH Scale: Basics
- [ ] Plinko Probability
- [ ] Reactants, Products and Leftovers
- [ ] Resistance in a Wire
- [ ] Rutherford Scattering
- [ ] States of Matter
- [ ] States of Matter: Basics
- [ ] Trig Tour 
- [ ] Under Pressure 
- [ ] Wave on a String

**Comment by phet-steele** [comment]
@ariel-phet naming convention will probably go `sim-name-screenshot-alt1(++)`

**Comment by ariel-phet** [comment]
@phet-steele can this be handed off to @CWilson4960 perhaps?

**Comment by phet-steele** [comment]
Updated what master checklists I could to say its sim has alts, but no guarantees.
