### ISSUE TITLE
RC Test: John Travoltage PhET-iO 

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#780]
John Travoltage has been instrumented for PhET-iO in https://github.com/phetsims/john-travoltage/issues/182 and a 1st RC has been published at http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-phetiorc.1/wrappers/index/

Testing Matrix
https://docs.google.com/spreadsheets/d/1Pg8HhMCdSVtiZAM7qXTo1kweL72VreW8qSpf1sl_W1c/edit#gid=2

The normal PhET-iO testing process should be used.  @emily-phet wants to share the simulation with ETS but it will also join the ranks of the other PhET-iO simulations.  Please be aware of known issues such as https://github.com/phetsims/phet-io/issues/998 which have not yet been addressed.  This simulation also includes implementation changes such as https://github.com/phetsims/scenery/issues/603 and https://github.com/phetsims/phet-io/issues/926 which will be good to test.

Reassigning to @ariel-phet to prioritize/schedule/reassign.  Please consult with @emily-phet regarding desired ETS usage timeline.

**Comment by ariel-phet** [comment]
@phet-steele please make this top QA priority

**Comment by samreid** [comment]
@emily-phet and I are wondering about the anticipated schedule for this issue.  @phet-steele @ariel-phet: When do you think testing will complete?

**Comment by phet-steele** [comment]
@samreid it would be okay if this were deemed complete now. The testing matrix is not filled out but that's not to say the sim was not tested on those platforms.

**Comment by samreid** [comment]
Excellent, thanks @phet-steele.  I'll leave this issue open as a reference/index to the discovered issues.

**Comment by samreid** [comment]
@emily-phet, will you please review the open issues marked above to see if they must be solved before delivering something to ETS?

**Comment by phet-steele** [comment]
> I'll leave this issue open as a reference/index to the discovered issues.

I'll reference this one, too. https://github.com/phetsims/phet-io/issues/1037

**Comment by emily-phet** [comment]
@samreid Just sent you an email about this. Here's the list:
Issues likely important to address before sending to ETS:
https://github.com/phetsims/phet-io/issues/1035 
https://github.com/phetsims/john-travoltage#193
https://github.com/phetsims/phet-io/issues/1039
https://github.com/phetsims/john-travoltage/issues/194
https://github.com/phetsims/john-travoltage#198

Not sure about importance of: 
https://github.com/phetsims/john-travoltage#187 
https://github.com/phetsims/john-travoltage#195

**Comment by samreid** [comment]
@emily-phet reviewed the issues and it looks like rc1 should be promoted to production for ETS.  We can discuss if we want to pick up the other master changes and do another test cycle before sharing to other groups and listing in our PhET-iO set.

**Comment by samreid** [comment]
I published 1.3.0-phetio.  Still getting this error in playback:

![image](https://cloud.githubusercontent.com/assets/679486/23040920/6ec777de-f450-11e6-96fa-730a367f5830.png)

**Comment by samreid** [comment]
The above issue will probably be fixed when the phet-io website gets republished.  1.3.0 was shared with @emily-phet and ETS and this issue is ready to close.
