### ISSUE TITLE
Test Circuit Construction Kit: Black Box Study 1.1.0-phetiorc.6

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#781]
In https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/40 I prepared a new version of Circuit Construction Kit: Black Box Study which will be used by our collaborators at Stanford in an upcoming study.

The first 1.1 RC is published here
UPDATE: see new version here https://github.com/phetsims/tasks/issues/781#issuecomment-278657028
UPDATE: see newer version here: https://github.com/phetsims/tasks/issues/781#issuecomment-280099072
UPDATE: rc4 is available here: https://github.com/phetsims/tasks/issues/781#issuecomment-280559234
UPDATE: we are up to 6

The previous version we had been supporting for them in the branch was getting so stale it was no longer able to semi-automatically maintain it with corresponding changes in master.  Hence we are creating a new version based on master to update the SHAs.  There have been numerous significant refactoring steps, so it will need to be tested rigorously.  If it passes testing, these SHAs will become the new maintenance SHAs and will be able to be kept in sync with master much easier.

I do not think this version requires exhaustive multi-platform testing.  Many of the refactoring steps are in the simulation logic (not, say, in WebGL or other parts that may behave differently on different platforms).  On the other hand, if this version does well in testing, it may supercede #765 (in which case we would want pretty broad platform testing, including iPad).

According to https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/25 another usage of this simulation is coming up soon, which will use the data stream and visual record/playback, so at a minimum those PhET-iO features should be tested.  The wrapper index is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.1/wrappers/index/ . 
(UPDATE: see new version here https://github.com/phetsims/tasks/issues/781#issuecomment-278657028 ):

@arouinfar should be on this testing team since she is most familiar with the requested features and desired behavior for this application.  Support from the rest of the QA team will also be valuable.  @arouinfar can you please review this issue and add anything I've missed, or any other recommendations?  Also assigning to @ariel-phet for prioritization, scheduling and delegation for the QA team side.

Also, @arouinfar I recall the last time we shared this with Stanford, there were numerous links with different query parameters.  Do you know if they still need all those variants?  If so, please post the links here (for the new 1.1.0-phetiorc.1 version) and we can test them too.

**Comment by ariel-phet** [comment]
@phet-steele next in line after #780

**Comment by arouinfar** [comment]
There are three query parameters to test (including in combination with one another).

?showPlayPauseButton  
* A play/pause button appears in the lower left corner of the sim. 
* In "pause" mode the sim background is gray.
* In "pause" mode voltmeter and current meter will have a blank display.
* Electrons will not flow until "play" is pressed. 
* In "play" mode, most actions will trigger "pause" mode. The exception is translation of a circuit component within the play area.

?showRevealButton=false
This will remove the Reveal button from the Black Box screen

The third query parameter doesn't appear to be working (see https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/45), but it should remove the "Show Electrons" checkbox from both screens. I'll update this comment once it's been fixed.

**Comment by samreid** [comment]
These query parameters came in handy during debugging and I realized they may also come in handy during testing:

`&vertexDisplay=index&dev` shows the vertex indices and makes the black box semi-transparent:
![image](https://cloud.githubusercontent.com/assets/679486/22768012/612bf858-ee3c-11e6-82d6-c21d02b2c82f.png)

`&vertexDisplay=voltage` shows the voltage for each vertex (no ground).
![image](https://cloud.githubusercontent.com/assets/679486/22768026/7c23fa66-ee3c-11e6-9af8-5e8f20bd61df.png)

**Comment by samreid** [comment]
I have fixed 5/6 issues noted above.  The sixth is https://github.com/phetsims/circuit-construction-kit-common/issues/251 about the layering of electrons.  The layering of electrons and circuit elements has proved tricky, there are many open issues about layering and this will need a significant amount of work.  Hence we may leave that one out of RC.2.

**Comment by samreid** [comment]
I do not believe that testing on rc.1 has completed.  Still, since I have addressed 5 of the discovered issues, I decided to publish rc.2.  I will leave it up to @phet-steele and @arouinfar whether they want to finish testing rc.1 or switch over to rc.2 now.

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/wrappers/index/

**Comment by arouinfar** [comment]
I will switch my testing over to rc.2. Thanks @samreid.

**Comment by phet-steele** [comment]
> I will switch my testing over to rc.2. Thanks @samreid.

Ditto.

**Comment by arouinfar** [comment]
@samreid I've finished testing rc.2.

**Comment by samreid** [comment]
All above issues have been addressed.  I'll use master for sun to pick up the slider fix.  Otherwise I'll use same SHAs as in RC.2 to minimize testing overhead.

**Comment by samreid** [comment]
Sun also picked up some changes with respect to dispose(), we should make sure disposing sun components is still OK in RC.3

**Comment by samreid** [comment]
I published RC.3 here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.3/wrappers/index/
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.3/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

I'll test each of the above open issues myself before turning this over to @arouinfar and @phet-steele

**Comment by samreid** [comment]
I noted this issue in RC.3: https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/36#issuecomment-280100528

@phet-steele and @arouinfar can you please test out RC3 (links above) and see what else remains to be done before sharing with Shima?

**Comment by ariel-phet** [comment]
@phet-steele moving to top priority for the moment until complete

**Comment by samreid** [comment]
I published rc.4 here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.4/wrappers/index/

It addresses 4 of the above open issues.  For the remaining open issues, I'm hoping we can "punt" on them for our February deadline.

**Comment by samreid** [comment]
I also published rc.5 here http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.5/wrappers/index/ which contains these new black boxes: https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/41

**Comment by phet-steele** [comment]
For all intents and purposes, this testing is done. The sim has a production version and will soon be delivered. Lowering priority and passing back to @samreid.

**Comment by samreid** [comment]
Thanks @phet-steele and @arouinfar for all your discoveries during testing, closing.
