### ISSUE TITLE
RC check: Gravity Force Lab 2.1.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#785]
@ariel-phet @phet-steele @arouinfar @oliver-phet, Gravity Force Lab 2.1.0-rc.3 is ready for an RC spot check after the last RC. The last issue should be fixed, and required minor changes.  @phet-steele could you please verify that it can no longer be produced? OSX Safari was the last platform to spot check in the previous RC, could you also check that platform before we redeploy?

[Link to sim](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.3/gravity-force-lab_en.html)

[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.3/gravity-force-lab_en-iframe.html)

 - [x] OSX Safari

Issues to Verify
Please test the following issues and check them off after addressing. If they are resolved, close them. If not, they should be updated.

 - [x] phetsims/gravity-force-lab#73
If any new issues are found, please note them in https://github.com/phetsims/gravity-force-lab/issues and reference this issue.

Assigning to @phet-steele  and adding medium priority (last task had medium priority)

**Comment by phet-steele** [comment]
@oliver-phet @jessegreenberg This rc has been spot checked!

**Comment by jessegreenberg** [comment]
@ariel-phet @phet-steele @oliver-phet 2.1.0 has been deployed to the website! Closing.
