### ISSUE TITLE
RC Test Bending Light 1.1.4-rc.3

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#786]
@kathy-phet pointed out that the reflected wave color in bending light was incorrect.  When @jonathanolson solved that problem in https://github.com/phetsims/bending-light/issues/359, it revealed a latent bug in the geometry which manifested as in incorrect wave propagation direction in the transmitted wave.  RC.3 fixes both of these issues (at least on my device that exhibited the problems):
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.4-rc.3/bending-light_en.html

Additionally, it adds a 6th prism of each type for https://github.com/phetsims/bending-light/issues/369

Note: this is a minor maintenance patch (only about 6 lines of code changed since last full test), so it will not require as much testing time as a full new version from master.

Reassigned to @ariel-phet for prioritization/scheduling/delegation.

I'll link the issues to test below.

**Comment by phet-steele** [comment]
@samreid I checked:

- macOS 10.12.3 Chrome, everything looked fine.
- iOS 10.2 retina, wave direction was good
- iPad 2, performance was not different
- JB's iPhone 5c, wave direction was good
- Win 10 Chrome & Edge, everything looked fine.

@samreid @ariel-phet, is this enough testing?

**Comment by samreid** [comment]
In my opinion, that is sufficient testing for these changes, thanks @phet-steele!

**Comment by ariel-phet** [comment]
Sounds good to me

**Comment by samreid** [comment]
Thanks for testing @phet-steele, I'll continue with publishing in https://github.com/phetsims/bending-light/issues/370
