### ISSUE TITLE
Screenshot for Make-A-Ten

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#790]
Can you please take the official screenshot for Make-A-Ten using an iPad? I believe it then gets uploaded to the sim repo.  

For some reason my screenshot won't upload... I've been trying for at least an hour! What I had in mind is the explore screen with a few different combined numbers. If you are feeling up to it, maybe be in the process of breaking apart a number while the hand cue starts fading. Might need a helper to take the screenshot. 

If you have another idea, I trust your judgment!

**Comment by phet-steele** [comment]
Pick a screenshot, any screenshot!



![img_0027](https://cloud.githubusercontent.com/assets/5863899/23434532/01ea4d22-fdc3-11e6-8973-a05459fe8889.png)

![img_0028](https://cloud.githubusercontent.com/assets/5863899/23434956/d199775a-fdc3-11e6-8e33-8bb750bfcfe0.png)






> For some reason my screenshot won't upload... I've been trying for at least an hour!

It was not easy to upload these, either.

**Comment by phet-steele** [comment]
Or this one:

![img_0026](https://cloud.githubusercontent.com/assets/5863899/23435834/b3d27f8a-fdc5-11e6-8f85-e9feb9e52de2.PNG)

**Comment by phet-steele** [comment]
To simulate how each would look on the site:

![img_0026](https://cloud.githubusercontent.com/assets/5863899/23437003/c14b2ff0-fdc9-11e6-9a02-b4055563c87d.PNG)


![img_0026](https://cloud.githubusercontent.com/assets/5863899/23436808/1558902a-fdc9-11e6-8451-28442d89803c.PNG)


![img_0027](https://cloud.githubusercontent.com/assets/5863899/23436962/96927854-fdc9-11e6-81de-46f307bdd91b.png)

![img_0027](https://cloud.githubusercontent.com/assets/5863899/23436927/75850fdc-fdc9-11e6-9749-4b4b5b019cdb.png)

![img_0028](https://cloud.githubusercontent.com/assets/5863899/23437109/20c6fe50-fdca-11e6-9ac3-cb8d1a8c4699.png)

![img_0028](https://cloud.githubusercontent.com/assets/5863899/23437100/16c0466e-fdca-11e6-9216-e86d92d2f436.png)

**Comment by amanda-phet** [comment]
I like the first one the best, but am fine with either of the "506=" if others have strong opinions. Thank you for taking these!

**Comment by phet-steele** [comment]
@jonathanolson @amanda-phet uploaded the bottom aligned "506=" image!
