### ISSUE TITLE
RC Check: Isotopes And Atomic Mass 1.0.6-rc.1

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#791]
@ariel-phet , @phet-steele  Isotopes and Atomic Mass 1.0.6-rc.1 is ready for RC testing. It does not involve invasive changes to code base therefore a complete testing is not required. Spot Check should work 

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.6-rc.1/isotopes-and-atomic-mass_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.6-rc.1/isotopes-and-atomic-mass_en-iframe.html)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/isotopes-and-atomic-mass/issues/38

If any new issues are found, please note them in https://github.com/phetsims/isotopes-and-atomic-mass/issues and reference this issue.  

@ariel-phet assigning to you for prioritizing

**Comment by ariel-phet** [comment]
Marking high since should be quick

**Comment by phet-steele** [comment]
@aadish it works! Thanks!

Checked on macOS 10.12.3 Chrome.

**Comment by aadish** [comment]
@phet-steele thanks, will go ahead and publish it

**Comment by aadish** [comment]
deployed and its live at: https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass_en.html

closing
