### ISSUE TITLE
RC Test: Build an Atom v1.4.0-phetiorc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#792]
A PhET-iO release candidate of Build an Atom is ready for testing.  This version is intended to be demonstrated at the South by Southwest conference in early March 2017 and then shared with customers.  This version covers only screens 1 and 2 and does not include the game screen (i.e. the game screen is entirely omitted from this build).

A fairly thorough test should be performed, since a lot of phet-io code has been added to the simulation and the common code libraries on which it depends, and a fair amount of refactoring of the sim code was also done during the process of instrumentation.

Link to the index of wrappers (this is password protected): http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.4.0-phetiorc.1/wrappers/index/

Testing Matrix:
https://docs.google.com/spreadsheets/d/16nsbXx_2r7_FoCxSQyZSOtLcoYs4VddA3mLfCaX3btw/edit#gid=2

**Comment by ariel-phet** [comment]
Considering the priority for @kathy-phet this should be top of the heap.

**Comment by jbphet** [comment]
Superseded by #801, closing.
