### ISSUE TITLE
Proportion Playground dev testing (1.0.0-dev.19)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#794]
http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.19/proportion-playground_en.html could use some initial dev testing.

Please check on the following platforms

- [x] Mac Safari
- [x] Windows Chrome
- [x] iPad

**Comment by ariel-phet** [comment]
Moving to current top testing priority

**Comment by phet-steele** [comment]
@jonathanolson @ariel-phet this is done.
