### ISSUE TITLE
RC Test: Balloons and Static Electricity 1.2.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#795]
@ariel-phet @phet-steele @jbphet @arouinfar, Balloons and Static Electricity 1.2.0-rc.2 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.2/balloons-and-static-electricity_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.2/balloons-and-static-electricity_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/153iOnhpi5IHdqFp3JBC9QDOmToPjhf4idY9YXQkqtac/edit#gid=646295854)**

**Issues to Verify**
This simulation has seen many changes for instrumentation of PhET-iO and accessibility.  It has also had several model changes to fix miscellaneous bugs and outstanding issues.  There are no specific issues to verify in this RC, but it requires full testing to deploy a version that has fixes for the model.

**NOTE:** This version should not include any accessibility features - tab navigation should be disabled.

If any new issues are found, please note them in https://github.com/phetsims/balloons-and-static-electricity/issues and reference this issue.

Assigning to @ariel-phet to prioritize.

**Comment by phet-steele** [comment]
@jessegreenberg there was already an rc test for a version 1.2.0-rc.1 in #513. Can you verify that the link you supplied above is the most up to date and not the same sim from a year ago?

**Comment by jessegreenberg** [comment]
Good catch @phet-steele.  I bumped to RC.2, and built a new sim.  I updated the links in the original issue ticket.

Here is the history and reason there was previously an 1.2.0 that went through an RC test:
- Before the summer redeploy, there was an a branch for 1.1.0 in balloons-and-static-electricity that went through some RC testing, but never passed, and was never deployed.
- Rather than update the SHAs for the version in this branch @jessegreenberg created a new branch 1.2.0 off of master and created an RC for this version for the summer redeploy.
- Shortly after, the dev team decided it was best to have continuous versioning, and that it was better to continue the 1.1 branch, pulling master SHAs into that branch and starting over.
- So the 1.2 branch was then deleted, though the 1.2.0 version on spot (and its testing task) remained.

But now we are ready to continue with a 1.2.0 release. I bumped the rc version number so that internal testing documentation can continue with the next RC version, but the deployed version will continue with 1.2.0.

Assigning back to @phet-steele and @ariel-phet for priority.

**Comment by phet-steele** [comment]
> I bumped the rc version number so that internal testing documentation can continue with the next RC version

Specifically, so the testing matrix doesn't become confusing with multiple tabs of the same version.

**Comment by phet-steele** [comment]
Issue above was referenced wrong, ignore it.

**Comment by phet-steele** [comment]
@jessegreenberg see the one issue above and to add Ethan to the credits, and don't forget to grab changes from phetsims/special-ops/issues/68. Testing is done!

**Comment by jonathanolson** [comment]
@phet-steele noted this passed except for the patches. It would be easier for me to include it directly with the maintenance patches I'm applying.

**Comment by jonathanolson** [comment]
Next RC link for BASE: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.3/balloons-and-static-electricity_en.html.

Do you want a separate testing task, or treat it as part of https://github.com/phetsims/tasks/issues/818?

**Comment by phet-steele** [comment]
@jonathanolson the only changes made were the patches, which are part of the maintenance release anyway. We will wrap this rc in with #818.

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson!

**Comment by jessegreenberg** [comment]
@phet-steele BASE was bumped to rc.4 for https://github.com/phetsims/balloons-and-static-electricity/issues/72, but a spot check in #818 should still be fine.

**Comment by phet-steele** [comment]
Going to go ahead and close this. rc.4 testing went well in #818 and will be deployed from that issue.
