### ISSUE TITLE
RC Check: Make a Ten 1.0.1-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#796]
@ariel-phet, @phet-steele  Make a Ten 1.0.1-rc.1 is ready for RC testing. It does not involve invasive changes to code base therefore a complete testing is not required. Spot Check should work 

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.1-rc.1/make-a-ten_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.1-rc.1/make-a-ten_en-iframe.html)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/make-a-ten/issues/273
- [x] https://github.com/phetsims/make-a-ten/issues/275

If any new issues are found, please note them in https://github.com/phetsims/make-a-ten/issues and reference this issue.

**Comment by phet-steele** [comment]
@jonathanolson spot check done. Checked,

- macOS 10.12.3 Chrome
- macOS 10.12.3 FF
- Win10 Chrome
- iPad iOS 9.3.5

**Comment by jonathanolson** [comment]
Deployed, thanks!
