### ISSUE TITLE
Dev test: Unit Rates 1.0.0-dev.68

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#797]
Unit Rates is ready for its first round of dev testing.

Here's the dev version:

http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.68/unit-rates_en.html

Familiarize yourself with the domain by reading [model.md](https://github.com/phetsims/unit-rates/blob/master/doc/model.md). Then read the Terminology section of [implementation-notes.md](https://github.com/phetsims/unit-rates/blob/master/doc/implementation-notes.md), which will be useful for communicating in GitHub issues.

Query parameters are documented in [URQueryParameters](https://github.com/phetsims/unit-rates/blob/master/js/common/URQueryParameters.js). Most useful for testing are `showAnswers`, `randomEnabled` and `animationSpeed` (for multi-touch).

For example: `?showAnswers&randomEnabled=false&animationSpeed=100`

Most of my testing during development has been on Chrome, Safari and Mobile Safari. So please check other platforms (especially Edge).

Please mention this issue in any GitHub issues that you create.

Let me know if you have any questions.

**Comment by pixelzoom** [comment]
@ariel-phet please assign and prioritize.

**Comment by ariel-phet** [comment]
@phet-steele also a current top priority

**Comment by phet-steele** [comment]
@pixelzoom this dev testing is done. I (personally) tested Win 10 Edge, macOS 10.12.3 Chrome & Safari, and iOS 10.2.

**Comment by pixelzoom** [comment]
Thank you @phet-steele for your usual thoroughness. 

Closing.

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet  Dev testing is completed. Ready for RC testing as soon as https://github.com/phetsims/unit-rates/issues/176 is verified by @arouinfar.

**Comment by arouinfar** [comment]
@pixelzoom please hold off on publishing an RC version. I may have some minor change requests, but I'll be speaking with @amanda-phet about them first. We're meeting in about an hour, but I'll let you know the final decision ASAP @pixelzoom.
