### ISSUE TITLE
Test: Installer-builder

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#798]
The links to test can be found here:
http://www.colorado.edu/physics/phet/dev/installer-testing/2017-03-09/

A few key points:
* Hammer the pages focused around the sims. Make sure that there aren't any places that the sims aren't served correctly, or if they aren't working. That's the core function of the installer after all.
* Look at the url as you click around, it is easy to get redirected back to the website.  Note any pages that you think should be in but aren't, or vice versa.
* Look for bugs where javascript is run on the site, often httrack mangles that, like in https://github.com/phetsims/installer-builder/issues/25
* Watch for 404 errors where it looks like there shouldn't be.

I'm also assigning to @ariel-phet for a priority.

Thanks guys!

**Comment by oliver-phet** [comment]
Also assigning @arnabp if he has availability to test.

**Comment by phet-steele** [comment]
@zepumph testing of the installer revealed it was solid enough to start the weekly installer testing again. We do not need a dedicated test task anymore. In case no one has told you @zepumph, the installer will now be downloaded from the website and tested every Monday.
