### ISSUE TITLE
RC Test: Build an Atom v1.4.0-phetiorc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#801]
A new RC has been built from the 1.4-phetio branch and is ready for testing.  This issue supplants the testing that was in progress for v1.4.0-phetiorc.1.

Link to the index of wrappers (this is password protected): http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.4.0-phetiorc.2/wrappers/index/

Testing Matrix:
https://docs.google.com/spreadsheets/d/16nsbXx_2r7_FoCxSQyZSOtLcoYs4VddA3mLfCaX3btw/edit#gid=1961266680

The changes that have been made versus v1.4.0-phetiorc.1 are not huge, but are also not trivial, so a moderate amount of focused testing is probably best.  Below is the list of issues that are believed to be fixed and should be verified.

- [x] https://github.com/phetsims/build-an-atom/issues/143
- [x] https://github.com/phetsims/build-an-atom/issues/144
- [x] https://github.com/phetsims/build-an-atom/issues/145 (this one may require assistance from @jonathanolson to verify)
- [x] https://github.com/phetsims/build-an-atom/issues/146
- [x] https://github.com/phetsims/build-an-atom/issues/147
- [x] https://github.com/phetsims/build-an-atom/issues/148

**Comment by ariel-phet** [comment]
Marking medium for the moment (since the SXSW goal was already reached)

**Comment by jbphet** [comment]
Yes, the SXSW goal has been reached, but I spoke with @kathy-phet after she got back from the conference and she said that there was a lot of interest in the phet-io version of BAA and she would like to have a production release of this ready to go this week (i.e. the week of March 13 2017).  Also, the collaborators from Georgia Tech need an update pretty badly, please see https://github.com/phetsims/build-an-atom/issues/140#issuecomment-285140691.  Given these goals, I'd like to advocate for a higher prioritization of this task.

**Comment by ariel-phet** [comment]
Bumping to parallel top priority with proportion playground testing.

**Comment by phet-steele** [comment]
@jbphet we can consider this done, no major bugs! Congrats!

**Comment by jbphet** [comment]
Thanks @phet-steele - I'll move forward with the production release.  Closing.
