### ISSUE TITLE
Materials for elementary school STEM night

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#802]
@oliver-phet @phet-steele I was asked to do a table at a local elementary school STEM night this Thursday March 16. A few things I will need:

- [x] Our banner poster
- [x] Some general PhET flyers (if we have some leftover ones that will be fine). I am sure ~100 would be plenty
- [x] An iPad air with the PhET app loaded
- [x] One extension cord and surge protector 
- [ ] Perhaps a first stab at our parent aimed "app" flyer if available (again ~100 copies would be plenty)
- [x] Perhaps one pack of general PhET business cards

**Comment by phet-steele** [comment]
@ariel-phet all materials will be in my office.

**Comment by oliver-phet** [comment]
@ariel-phet If we are going to try to print the parent flyer, we’ll need to come up with some copy (it is currently Greeked).

**Comment by ariel-phet** [comment]
@oliver-phet perhaps Jackie is willing to take a stab? Or you and I can put something together? I look at this as a potential test run

**Comment by ariel-phet** [comment]
STEM night attended, closing
