### ISSUE TITLE
Export of older Camtasia Recordings to video file

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#803]
I need the following camtasia files from phet-storage exported as video files for sharing with collaborators:
2013_07_10_BASE_OL_RIAW_HTML5_G7_M_ZC_PC_NP.camrec
2013_07_10_BASE_OL_RIAW_HTML5_G5_M_QC_PC_NP.camrec
2013_07_10_BASE_OL_RIAW_HTML5_00010_G5_F_SL2_Surface_Chrome_NP.camrec

By March 24th would be ideal.

**Comment by ariel-phet** [comment]
@oliver-phet @phet-steele it seems this would be good to take care of in the near future (given the time line). Is this something @arnabp has some time to do? If not could one of you handle it?

**Comment by oliver-phet** [comment]
@emily-phet It looks like all 3 of these have already been converted to .mpg and stored on phet-storage. The 3rd file, I couldn't find (exactly) is the one I linked the correct file?

2013_07_10_BASE_OL_RIAW_HTML5_G7_M_ZC_PC_NP.camrec https://drive.google.com/drive/folders/0BxY3hgNdnYNHVlgyN0tkLUhjdWc?usp=sharing
2013_07_10_BASE_OL_RIAW_HTML5_G5_M_QC_PC_NP.camrec
https://drive.google.com/drive/folders/0BxY3hgNdnYNHYVdrU2ZCREFYV0k?usp=sharing
2013_07_10_BASE_OL_RIAW_HTML5_00010_G5_F_SL2_Surface_Chrome_NP.camrec
https://drive.google.com/drive/folders/0BxY3hgNdnYNHaWhHVVhFaUYyLWs?usp=sharing

**Comment by emily-phet** [comment]
@oliver-phet The .mpg files in these folders are actual video recordings of the interviews, not the  converted camtasia files.

**Comment by oliver-phet** [comment]
@emily-phet: @phet-steele and I just uploaded the new exported videos into the accompanying folder on phet-storage (they are the new .mp4 files).
2013_07_10_BASE_OL_RIAW_HTML5_G7_M_ZC_PC_NP
https://drive.google.com/drive/u/1/folders/0BxY3hgNdnYNHVlgyN0tkLUhjdWc
2013_07_10_BASE_OL_RIAW_HTML5_G5_M_QC_PC_NP
https://drive.google.com/drive/u/1/folders/0BxY3hgNdnYNHYVdrU2ZCREFYV0k
2013_07_08_BASE_OL_RIAW_HTML5_G5_F_SL2_Surface_Chrome_NP
https://drive.google.com/drive/u/1/folders/0BxY3hgNdnYNHaWhHVVhFaUYyLWs

Also, Camtasia created a lot of other files during the export, did you need any of those? ex:
<img width="805" alt="screen shot 2017-03-20 at 1 20 17 pm" src="https://cloud.githubusercontent.com/assets/5090275/24117476/022292ba-0d70-11e7-88b8-350ba7bc96a6.png">

**Comment by phet-steele** [comment]
@emily-phet is everything good here? Can this be closed?
