### ISSUE TITLE
"train coupler" needed for Equality Explorer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#804]
I'd like to have something that looks like a train coupler to show when two boxes are detached and attached. Ideally they have a simple appearance (perhaps two-tone but no more than two colors). I'd also like to be able to change the color of the arms separately, but I'm not sure what the final colors will be. So, the left arm might be blue and the right arm might be red. 

Here is a picture for reference. I like the general shape of this but the style could use some improvement to match the PhET aesthetic.

![screen shot 2017-03-17 at 11 18 37 am](https://cloud.githubusercontent.com/assets/7852916/24054981/e43a7010-0b03-11e7-8bc7-c1b0765803a3.png)

Let me know if you'd like to discuss over zoom for further clarification!

**Comment by clmccutchan** [comment]
@amanda-phet Here's a first draft of the train coupler open and closed. I've made the coupler with a background color (blue or red in these examples), but you can change the background to any color you like in Illustrator. The highlights/shadows are created with gray transparency filters so you can change that background color and the shadows/highlights should still work. I tested them with a number of bright colors.

![804 train coupler_closed](https://cloud.githubusercontent.com/assets/25354670/24225123/69590fa8-0f24-11e7-9a34-dc933893a684.png)
![804 train coupler_open](https://cloud.githubusercontent.com/assets/25354670/24225124/69808a9c-0f24-11e7-9344-fae1d1951d41.png)

**Comment by amanda-phet** [comment]
I found a way to integrate what you made and it looks great! The team likes the appearance, too. I don't have any tweaks. I will just want to change the colors (which you made possible- thank you!) and extend the arm to be a bit longer (which seems easy enough). Please feel free to share your .ai file!

**Comment by clmccutchan** [comment]
@amanda-phet Awesome! The .ai file is in my artwork folder. Let me know if you have any questions.

**Comment by amanda-phet** [comment]
For some reason I'm having trouble opening the file. I know you use a newer version of illustrator but this time it's saying the file is a pdf (it is clearly an ai file though). Can you try saving it as an older version? We are using CS6.

**Comment by clmccutchan** [comment]
@amanda-phet Oh yes, I forgot you guys use CS6. I've saved the file in the older format and reloaded it in the google drive.

**Comment by amanda-phet** [comment]
Perfect! Thank you so much.
