### ISSUE TITLE
Balloons and Static Electricity - The Animated Movie! (Needed by March 27th)

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#805]
I would like a very special screen capture made of Balloons and Static Electricity.

As part of the sonification work, we will need a short (screen capture) video of Balloons and Static Electricity, where the video shows use of the sim as a narrative - a short story about a balloon that discovers it can pick up charges from a sweater, induce charge in a wall, find a friend (Green Balloon), battle, and race. We will use this video for a design exercise where we ask sound designers to create a score and sound effects for this video. This activity will help us refine the "sound and feel" of the audio display created for this sim and others (and seems like a lot of fun!).

Are there any folks on the team (perhaps some of the QA folks or others) that would like to take a stab at creating "Balloons and Statice Electricity - The Animated Movie"? If not, I can certainly write the screenplay, but I thought someone might enjoy this as a creative outlet. 

Mentioning @terracoda so she can follow along.

**Comment by ariel-phet** [comment]
@phet-steele - you have certainly done lots of our screen capture work (for conference and website rotating videos), I feel like this would be in your wheelhouse.

**Comment by phet-steele** [comment]
@emily-phet a few questions:

- What would the ideal length of this video be?
- Do we need to see the cursor or would it be better to hide it?
- High resolution?
- Is there an ideal screen size?

**Comment by emily-phet** [comment]
@phet-steele Attempted answers...
- Length - 2 minutes max, more like 90 seconds would be ideal.
- Ideally the cursor would not be seen, but I'm not sure if that will actually make sense...e.g., you might need to distinguish between "grabbed" and not "grabbed" so that it's clear to the audience when the balloon is being moved vs attracted/repelled. So, probably cursor will need to be seen.
- For the screen resolution - can you create a high resolution and a lower (e.g., for Youtube and easy downloads) version? We'll use this for different purposes so would be good to have options re screen resolution.
- Screen size - Hmm, I don't think this is too important. As long as the sim isn't stretched so that the black borders are large (I find this asthetically unpleasing) it should be fine. So, don't "full screen" the sim but keep it at the scaling it is upon opening. Though let me know if you had other considerations in mind regarding screen size.

**Comment by emily-phet** [comment]
@phet-steele - how is this coming along? Is it still possible to get this by end of day today? Thanks!

**Comment by phet-steele** [comment]
@emily-phet I sent an email to @arnabp to check on the status.

**Comment by terracoda** [comment]
@emily-phet, @phet-steele, and @arnabp, I created one that might do, and just in case people are short on time.
I am uploading it to the Phet Acessibility/Sonification Work folder.

It is done in QuickTime. The screen capture is a full 95 seconds, but can be clipped on either end. I included a bit of button clicking at the start, and a reset at the end. Those bits could be cut.

**Comment by terracoda** [comment]
My connection is slow. It will take some time to upload :-)

**Comment by terracoda** [comment]
Hmm, upload failed a few times. I'll try again at night.

**Comment by arnabp** [comment]
I'm working on it now. To be clear, the clip we're creating won't have any sound in it for now right?

**Comment by phet-steele** [comment]
> I'm working on it now. To be clear, the clip we're creating won't have any sound in it for now right?

@arnabp that is correct.

**Comment by arnabp** [comment]
[How does this look?](https://drive.google.com/open?id=0B4YbviHsDyYITllNcWc5Q0ZZZUk)

**Comment by phet-steele** [comment]
@emily-phet @arnabp I'm not sure and this probably should have been asked sooner, but what version should this be recorded with? The most up to date version (below) has a slack string and different balloon behaviour when compared to the production version.

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.2/balloons-and-static-electricity_en.html

That being said, if we went with the video @arnabp has above, there would be functionality that doesn't exist in the newest version. Specifically, you can no longer repel balloons off the sweater with another balloon.

**Comment by arnabp** [comment]
I think the older version definitely has more content in the way of the balloon interactions, so if it doesn't have to be up to date the already recorded version would probably be better.

**Comment by terracoda** [comment]
@emily-phet, the one I made is in the [Sonfication Work](https://drive.google.com/drive/folders/0B50Cor5oitKqaVRGU0hnbWhodms) folder.

It did actually upload 2 days ago :-)

**Comment by phet-steele** [comment]
Thanks @arnabp and @terracoda. @emily-phet will these videos work and can this issue be closed?
