### ISSUE TITLE
Prepare stuff for NSTA

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#806]
- [x] Print general flyers (800?)
- [x] 2x iPads with app
- [x] Potentially new stickers?
- [x] Booth bag ready
- [x] Print app flyers (200?)
- [x] Macbook Air conference video (@ariel-phet, is this video sufficient or does @phet-steele need to remake? https://github.com/phetsims/phet-info/blob/master/conferences/NSTA_STEM_2016.mp4)
- [x] Send NSTA email
- [x] KP business cards

**Comment by arouinfar** [comment]
@oliver-phet 800 flyers sounds about right. I think Trish and I handed out about 700 flyers last time we were at NSTA.

**Comment by ariel-phet** [comment]
@oliver-phet I think that video is good, if I were going to change anything I would add function builder, but I think it is fine as is

**Comment by oliver-phet** [comment]
Closed.
