### ISSUE TITLE
Dev test: Expression Exchange 1.0.0-dev.21

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#807]
We are about to start interviews on Expression Exchange, and it would be good to do a round of dev testing to make sure that the sim is ready for this.  The game screen has been recently implemented and hasn't been tested much, so a fair amount of testing effort should be spent on that.  Also, implementing the game code caused a lot of code refactoring that could have impacted the other screens, so they should be regression tested as well.

Link to sim: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.21/expression-exchange_en.html

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
Seems like this should get top billing currently.

**Comment by phet-steele** [comment]
@jbphet @ariel-phet @amanda-phet testing done.

**Comment by jbphet** [comment]
Thanks! Closing.
