### ISSUE TITLE
Website QA: Activity page and file access

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#808]
@phet-steele - Can QA please test the latest state of activity page and file access on ox-dev as described in phetsims/website#580?

The changes are that unapproved activities, both pages and files, should only be accessible to users signed in as the owner of the file or phet team members.  All approved activity pages should be accessible by anyone, and all approved activity files should be accessible by anyone who is signed into the website.

I marked as medium priority as its currently blocking website deploys.  If we can't schedule a test within the next week I can adjust this, but please let me know.

**Comment by phet-steele** [comment]
@mattpen @ariel-phet on hold until https://github.com/phetsims/website/issues/580#issuecomment-288849926

**Comment by mattpen** [comment]
@phet-steele - The blocking issues in https://github.com/phetsims/website/issues/580#issuecomment-288849926 have been resolved.  Please continue testing.  New activities should now be unapproved by default.

**Comment by phet-steele** [comment]
@mattpen everything worked on my end, nice work! 🤞

**Comment by mattpen** [comment]
Thanks @phet-steele
