### ISSUE TITLE
RC test: Unit Rates 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#809]
@arouinfar @ariel-phet Unit Rates 1.0.0-rc.1 is ready for RC testing.

Link to sim:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-rc.1/unit-rates_en.html

Link to iframe:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-rc.1/unit-rates_en-iframe.html

Testing Matrix
https://docs.google.com/spreadsheets/d/1nsZJqZvbLbPE0ZzsF2DQRSN-EwoeiQii3_W_unDO-f8/edit#gid=2

@phet-steele please create the associated test matrix. (Done)

In addition to the test matrix, please perform these specific tests on 1 or 2 platforms:
- [ ] ?stringTest=double (double all strings)
- [ ] ?stringTest=long (excessively long strings)
- [ ] ?stringTest=X (short strings)
- [ ] ?stringTest=rtl (right-to-left text direction)
- [x] ?stringTest=xss (test for security issues, passes if it does NOT redirect to another page)
- [ ] full screen test

See [URQueryParameters.js](https://github.com/phetsims/unit-rates/blob/master/js/common/URQueryParameters.js) for a list of query parameters. The query parameters that are most useful for testing are `showAnswers`, `randomEnabled=false` and `animationSpeed=100`. 

See also the "Terminology" section of [implementation-notes.md](https://github.com/phetsims/unit-rates/blob/master/doc/implementation-notes.md). This will be useful for creating and discussing issues, so that we're all speaking the same language. 

Please mention this issue in any related issues that you create.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to assign and prioritize.

**Comment by ariel-phet** [comment]
@phet-steele definitely top priority...we ideally want to publish before Thursday, so good to get the testing rolling.

**Comment by phet-steele** [comment]
Currently on hold due to the above issues. Chances are we will need to begin an rc.2, but we will see once those issues are addressed.

**Comment by pixelzoom** [comment]
This RC test is aborted due to phetsims/scenery#609.
