### ISSUE TITLE
Prepare booth for NCTM

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#810]
- [ ] Print general flyers (800?)
- [ ] 2x iPads with app
- [x] Potentially new stickers?
- [x] Booth bag ready
- [x] Print app flyers (200?)
- [ ] Macbook Air conference video (@ariel-phet, is this video sufficient or does @phet-steele need to remake? https://github.com/phetsims/phet-info/blob/master/conferences/NCTM_2016.mp4)
- [x] Send NCTM email
- [x] KP business cards

**Comment by oliver-phet** [comment]
Remind people:
- Chromebook filtering (and iPad): sort by device
- Remind people to register for an account (new sim email notifications)

**Comment by ariel-phet** [comment]
All going well, closing
