### ISSUE TITLE
RC test: Unit Rates 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#811]
1.0.0-rc.1 was aborted due to an accessibility bug in scenery (https://github.com/phetsims/unit-rates/issues/196).  Here's the next RC.

Link to sim:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-rc.2/unit-rates_en.html

Link to iframe:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-rc.2/unit-rates_en-iframe.html

Testing Matrix:
https://docs.google.com/spreadsheets/d/1nsZJqZvbLbPE0ZzsF2DQRSN-EwoeiQii3_W_unDO-f8/edit#gid=691260756

In addition to the test matrix, please perform these specific tests on 1 or 2 platforms:

- [x] ?stringTest=double (double all strings)
- [x]  ?stringTest=long (excessively long strings)
- [x]  ?stringTest=X (short strings)
- [x]  ?stringTest=rtl (right-to-left text direction)
- [x]  ?stringTest=xss (test for security issues, passes if it does NOT redirect to another page)
- [x]  full screen test
- [x] screenshot test

See [URQueryParameters.js](https://github.com/phetsims/unit-rates/blob/master/js/common/URQueryParameters.js) for a list of query parameters. The query parameters that are most useful for testing are `showAnswers`, `randomEnabled=false` and `animationSpeed=100`. 

See also the "Terminology" section of [implementation-notes.md](https://github.com/phetsims/unit-rates/blob/master/doc/implementation-notes.md). This will be useful for creating and discussing issues, so that we're all speaking the same language. 

Please mention this issue in any related issues that you create.

**Comment by pixelzoom** [comment]
Self-assigning so I don't have to search for this issue to check status.

**Comment by phet-steele** [comment]
![greenlight](https://cloud.githubusercontent.com/assets/5863899/24669332/3869fe54-1927-11e7-855b-275f84c15a53.png)

**Comment by pixelzoom** [comment]
Thanks @phet-steele. I'll proceed with publication of 1.0.0.
