### ISSUE TITLE
Dev test: Graphing Slope-Intercept 1.0.0-dev.6

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#812]
Dev version:
http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.6/graphing-slope-intercept_en.html 

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.6/graphing-slope-intercept_en-iframe.html

This sim consists of 2 screens from Graphing Lines:
• Slope-Intercept: identical to Graphing Lines, no changes.
• Line Game: quacks like Graphing Lines, but has only 4 levels, and the challenges involve only slope-intercept equations. 

Game challenges, and the rewards for a perfect score in each level, are specified in:
https://docs.google.com/document/d/1ztSRN1YE1BIGI1rsCBnZXzZQYvelSFySp4sDHPh2OJs/edit#

Sim-specific query parameters are in [GLQueryParameters.js](https://github.com/phetsims/graphing-lines/blob/master/js/common/GLQueryParameters.js).  You'll find `?showAnswers&shuffle=false` to be useful for comparing the Game challenges to the design specification. With those query parameters, you'll see a brief description of the challenge in the upper-left of the corner of the screen, numbered to  correspond with the design specification. For example:

![screenshot_323](https://cloud.githubusercontent.com/assets/3046552/24673022/0cf00806-1934-11e7-8a54-81edaa2c3509.png)

Terminology is defined in [implementation-notes.md](https://github.com/phetsims/graphing-lines/blob/master/doc/implementation-notes.md).

Most of my testing during development has been on Chrome, Safari and Mobile Safari. So please check other platforms (especially Edge).

Please mention this issue in any GitHub issues that you create.

**Comment by pixelzoom** [comment]
Assigned to @ariel-phet to assign and prioritize.

Mentioning @amanda-phet so she knows that this issue is tracking dev testing.

**Comment by pixelzoom** [comment]
@phet-steele Please standby... I just realized that 1.0.0-dev.5 was built awhile ago, and may (or may not) have the common-code problems that were identified during RC testing of unit-rates.  So while there haven't been any graphing-slope-intercept changes since 1.0.0-dev.5, I'm going to build you a new dev version with fresh common code.

**Comment by pixelzoom** [comment]
@phet-steele I published a new dev version (1.0.0-dev.6) and updated the URLs in the instructions above, as well as the title of the issue.

graphing-slope-intercept 1.0.0-dev.6 was built using the shas that were used to publish unit-rates 1.0.0, with the following changes:
• added `vegas` and `vibe` from master, since unit-rates didn't use those repos
• used `brand` master to pick up About dialog copyright fix in https://github.com/phetsims/brand/issues/31

**Comment by pixelzoom** [comment]
@phet-steele  You may proceed with dev testing.

**Comment by phet-steele** [comment]
@pixelzoom, done. I personally tested on macOS 10.12.4 browsers and iOS latest. @EthanWJohnson  tested on Win 10 browsers.

**Comment by pixelzoom** [comment]
Great, thanks.  All related issues have been addressed, so we will proceed to RC testing.
