### ISSUE TITLE
Maintenance release RC tests

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#818]
The following RCs are available for for https://github.com/phetsims/phet-android-app/issues/16, https://github.com/phetsims/phetcommon/issues/37 and https://github.com/phetsims/vibe/issues/30. I'll comment when they are fully deployed.

The following complete list should be tested for:

- Basic interaction (no major introduced bugs, standard ~30sec or so)
- When given the `?phet-android-app` query parameter they should include `phet-android-app` as the `loadType` in the immediate.gif Yotta message.
![network](https://cloud.githubusercontent.com/assets/480878/25049382/d272e5e0-20fe-11e7-85f7-57e8e5c47c63.PNG)
I believe @phet-steele should be familiar with checking the network tab of dev tools for this.
- Additionally, when that query parameter is passed, there should NOT be a "Check for Updates" item in the PhET menu, and it won't have update information in the About dialog.
- Any runs should include pingver=3 (NOT 2) in the Yotta message, and the brand query parameter in it should be 

- [x] [acid-base-solutions](http://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.10-rc.2/acid-base-solutions_en.html)
- [x] [area-builder](http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.5-rc.2/area-builder_en.html)
- [x] [arithmetic](http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.9-rc.2/arithmetic_en.html)
- [x] [atomic-interactions](http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.3-rc.2/atomic-interactions_en.html)
- [x] [balancing-act](http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.9-rc.2/balancing-act_en.html)
- [x] [balancing-chemical-equations](http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.9-rc.3/balancing-chemical-equations_en.html)
- [x] [balloons-and-static-electricity](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.4/balloons-and-static-electricity_en.html)
- [x] [beers-law-lab](http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.3-rc.2/beers-law-lab_en.html)
- [x] [bending-light](http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.6-rc.2/bending-light_en.html)
- [x] [build-an-atom](http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.5-rc.2/build-an-atom_en.html)
- [x] [charges-and-fields](http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.3-rc.2/charges-and-fields_en.html)
- [x] [color-vision](http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.9-rc.2/color-vision_en.html)
- [x] [concentration](http://www.colorado.edu/physics/phet/dev/html/concentration/1.3.5-rc.2/concentration_en.html)
- [x] [energy-skate-park-basics](http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.5-rc.1/energy-skate-park-basics_en.html)
- [x] [faradays-law](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.9-rc.1/faradays-law_en.html)
- [x] [forces-and-motion-basics](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.4-rc.1/forces-and-motion-basics_en.html)
- [x] [fraction-matcher](http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.7-rc.1/fraction-matcher_en.html)
- [x] [friction](http://www.colorado.edu/physics/phet/dev/html/friction/1.3.3-rc.1/friction_en.html)
- [x] [function-builder](http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.3-rc.1/function-builder_en.html)
- [x] [graphing-lines](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.10-rc.1/graphing-lines_en.html)
- [x] [gravity-and-orbits](http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.1.2-rc.1/gravity-and-orbits_en.html)
- [x] [gravity-force-lab](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.2-rc.1/gravity-force-lab_en.html)
- [x] [hookes-law](http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.9-rc.1/hookes-law_en.html)
- [x] [isotopes-and-atomic-mass](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.8-rc.1/isotopes-and-atomic-mass_en.html)
- [x] [john-travoltage](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.6-rc.1/john-travoltage_en.html)
- [x] [least-squares-regression](http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.6-rc.1/least-squares-regression_en.html)
- [x] [make-a-ten](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.3-rc.1/make-a-ten_en.html)
- [x] [molarity](http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.10-rc.1/molarity_en.html)
- [x] [molecule-shapes](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.10-rc.1/molecule-shapes_en.html)
- [x] [molecule-shapes-basics](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.8-rc.1/molecule-shapes-basics_en.html)
- [x] [molecules-and-light](http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.15-rc.1/molecules-and-light_en.html)
- [x] [neuron](http://www.colorado.edu/physics/phet/dev/html/neuron/1.1.3-rc.1/neuron_en.html)
- [x] [ohms-law](http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.7-rc.1/ohms-law_en.html)
- [x] [ph-scale](http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.10-rc.1/ph-scale_en.html)
- [x] [ph-scale-basics](http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.10-rc.1/ph-scale-basics_en.html)
- [x] [plinko-probability](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.3-rc.1/plinko-probability_en.html)
- [x] [reactants-products-and-leftovers](http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.9-rc.1/reactants-products-and-leftovers_en.html)
- [x] [resistance-in-a-wire](http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.8-rc.1/resistance-in-a-wire_en.html)
- [x] [rutherford-scattering](http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.6-rc.1/rutherford-scattering_en.html)
- [x] [states-of-matter](http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.2-rc.1/states-of-matter_en.html)
- [x] [states-of-matter-basics](http://www.colorado.edu/physics/phet/dev/html/states-of-matter-basics/1.0.2-rc.1/states-of-matter-basics_en.html)
- [x] [trig-tour](http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.8-rc.1/trig-tour_en.html)
- [x] [under-pressure](http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.4-rc.1/under-pressure_en.html)
- [x] [unit-rates](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.3-rc.1/unit-rates_en.html)
- [x] [wave-on-a-string](http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.8-rc.1/wave-on-a-string_en.html)

The following subset of sims have the Vibe fix, and should be tested to ensure they have proper sound on iOS (in addition, spot-checking one to ensure sound is good elsewhere):

- [x] [area-builder](http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.5-rc.2/area-builder_en.html)
- [x] [arithmetic](http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.9-rc.2/arithmetic_en.html)
- [x] [balancing-act](http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.9-rc.2/balancing-act_en.html)
- [x] [balancing-chemical-equations](http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.9-rc.3/balancing-chemical-equations_en.html)
- [x] [build-an-atom](http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.5-rc.2/build-an-atom_en.html)
- [x] [faradays-law](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.9-rc.1/faradays-law_en.html)
- [x] [forces-and-motion-basics](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.4-rc.1/forces-and-motion-basics_en.html)
- [x] [fraction-matcher](http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.7-rc.1/fraction-matcher_en.html)
- [x] [graphing-lines](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.10-rc.1/graphing-lines_en.html)
- [x] [john-travoltage](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.6-rc.1/john-travoltage_en.html)
- [x] [make-a-ten](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.3-rc.1/make-a-ten_en.html)
- [x] [ohms-law](http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.7-rc.1/ohms-law_en.html)
- [x] [plinko-probability](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.3-rc.1/plinko-probability_en.html)
- [x] [reactants-products-and-leftovers](http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.9-rc.1/reactants-products-and-leftovers_en.html)

Also BASE includes fixes for phetsims/special-ops#68, and is a continuation of https://github.com/phetsims/tasks/issues/795:

- [x] [balloons-and-static-electricity](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-rc.4/balloons-and-static-electricity_en.html)

**Comment by jonathanolson** [comment]
RCs are ready for testing.

**Comment by ariel-phet** [comment]
@phet-steele these tests would be good to perform sooner than later (preferably before May 1) as we would like these releases published well before publishing the android app.

**Comment by phet-steele** [comment]
Also @ariel-phet, https://github.com/phetsims/vibe/issues/30 is pretty serious so I'll more than likely get to these tests immediately.

**Comment by ariel-phet** [comment]
@phet-steele sounds good

**Comment by phet-steele** [comment]
@jonathanolson, balancing-chemical-equations shows no change with `phet-android-app`.

**Comment by jonathanolson** [comment]
Fixed balancing-chemical-equations, new RC linked in main list.

**Comment by phet-steele** [comment]
Fixed, thanks

**Comment by phet-steele** [comment]
@jonathanolson Done! Everything went swimmingly. All runs included the brand, had pingver=3, and hid the appropriate items in the PhET menu with the query param.

**Comment by jonathanolson** [comment]
Ok, will be pushing out production releases.

**Comment by jonathanolson** [comment]
Deployed production versions:

- [acid-base-solutions](http://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.10/acid-base-solutions_en.html)
- [area-builder](http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.5/area-builder_en.html)
- [arithmetic](http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.9/arithmetic_en.html)
- [atomic-interactions](http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.3/atomic-interactions_en.html)
- [balancing-act](http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.9/balancing-act_en.html)
- [balancing-chemical-equations](http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.9/balancing-chemical-equations_en.html)
- [balloons-and-static-electricity](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0/balloons-and-static-electricity_en.html)
- [beers-law-lab](http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.3/beers-law-lab_en.html)
- [bending-light](http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.6/bending-light_en.html)
- [build-an-atom](http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.5/build-an-atom_en.html)
- [charges-and-fields](http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.3/charges-and-fields_en.html)
- [color-vision](http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.9/color-vision_en.html)
- [concentration](http://www.colorado.edu/physics/phet/dev/html/concentration/1.3.5/concentration_en.html)
- [energy-skate-park-basics](http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.5/energy-skate-park-basics_en.html)
- [faradays-law](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.9/faradays-law_en.html)
- [forces-and-motion-basics](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.4/forces-and-motion-basics_en.html)
- [fraction-matcher](http://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.7/fraction-matcher_en.html)
- [friction](http://www.colorado.edu/physics/phet/dev/html/friction/1.3.3/friction_en.html)
- [function-builder](http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.3/function-builder_en.html)
- [graphing-lines](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.10/graphing-lines_en.html)
- [gravity-and-orbits](http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.1.2/gravity-and-orbits_en.html)
- [gravity-force-lab](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.2/gravity-force-lab_en.html)
- [hookes-law](http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.9/hookes-law_en.html)
- [isotopes-and-atomic-mass](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.8/isotopes-and-atomic-mass_en.html)
- [john-travoltage](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.6/john-travoltage_en.html)
- [least-squares-regression](http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.6/least-squares-regression_en.html)
- [make-a-ten](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.3/make-a-ten_en.html)
- [molarity](http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.10/molarity_en.html)
- [molecule-shapes](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.10/molecule-shapes_en.html)
- [molecule-shapes-basics](http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.8/molecule-shapes-basics_en.html)
- [molecules-and-light](http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.15/molecules-and-light_en.html)
- [neuron](http://www.colorado.edu/physics/phet/dev/html/neuron/1.1.3/neuron_en.html)
- [ohms-law](http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.7/ohms-law_en.html)
- [ph-scale](http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.10/ph-scale_en.html)
- [ph-scale-basics](http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.10/ph-scale-basics_en.html)
- [plinko-probability](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.3/plinko-probability_en.html)
- [reactants-products-and-leftovers](http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.9/reactants-products-and-leftovers_en.html)
- [resistance-in-a-wire](http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.8/resistance-in-a-wire_en.html)
- [rutherford-scattering](http://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.6/rutherford-scattering_en.html)
- [states-of-matter](http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.2/states-of-matter_en.html)
- [states-of-matter-basics](http://www.colorado.edu/physics/phet/dev/html/states-of-matter-basics/1.0.2/states-of-matter-basics_en.html)
- [trig-tour](http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.8/trig-tour_en.html)
- [under-pressure](http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.4/under-pressure_en.html)
- [unit-rates](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.3/unit-rates_en.html)
- [wave-on-a-string](http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.8/wave-on-a-string_en.html)
