### ISSUE TITLE
QA Task: Android App

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#820]
@phet-steele - Can you do a QA test for the current state of the phet app?

The app is available here:
~~https://drive.google.com/open?id=0BwA8lLKUclCPSU5XaXFXMEppb28~~
(You'll need to enable apps from outside sources before dowwnloading)

The features implemented include:
- Searching and Filtering
- Selecting/Unselecting/resetting favorites
- Updating sims
    - They are installed from an old archive which will be updated at publication time
    - They should attempt to update whenever the collection screen is viewed.  The sims that change will be available the next time the collection view loads.

Things to test include correctness of the above features and correctness of layout.  There shouldn't be any strings, titles, images etc. cut off on screens larger than ~3.7".

**Comment by mattpen** [comment]
@phet-steele - Talkback is now enabled in the app and should be tested as well.  Things should be fairly similar to the ios app with VoiceOver.

The new version (0.2) is available here: https://drive.google.com/a/colorado.edu/file/d/0BwA8lLKUclCPMDFnbVhfTnVkVm8/view?usp=sharing

**Comment by mattpen** [comment]
@phet-steele - Keyboard navigation is not working in the app as well.

The latest version (0.3) is available here: https://drive.google.com/a/colorado.edu/file/d/0BwA8lLKUclCPTE1aRElEX3RxYUk/view?usp=sharing

**Comment by mattpen** [comment]
@phet-steele - The latest version is available here: https://play.google.com/apps/testing/edu.colorado.phet.android

**Comment by mattpen** [comment]
@phet-steele @ariel-phet - 

The latest beta will now be available here:
https://play.google.com/apps/testing/edu.colorado.phet.android_app

**Comment by phet-steele** [comment]
@mattpen, when you are ready for more testing (which could even be now!), please make an issue in the QA repo.
