### ISSUE TITLE
Creating Qualtrics Teacher Survey

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#822]
In collaboration with Georgia Tech, we have developed a survey to be given to teachers using PhET sims. This survey needs to be created in Qualtrix. This survey has about 40 questions and a moderate amount of logic needed (e.g., multiple branching questions). If there is a way to give @kainip from GT access to CU's Qualtrix, she may be able to create this independently, otherwise she can help the PhET team member understand the intended logic structure. 
Ideally, a first draft would be complete by April 24th.

**Comment by ariel-phet** [comment]
@oliver-phet - you are the qualtrix expert, any thoughts here?

**Comment by oliver-phet** [comment]
We can add the GT collaborator as a CU affiliate which will give them access to CU Qualtrics. 
Can you email me @kainip's contact info?

**Comment by emily-phet** [comment]
Done. Just sent @oliver-phet an email connecting him with @kainip.

**Comment by oliver-phet** [comment]
@emily-phet it sounds like @kainip was able to log in to Qualtrics. Closing for now.
