### ISSUE TITLE
Dev test: Function Builder: Basics 1.0.0-dev.3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#823]
Dev test:
http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en.html

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.3/function-builder-basics_en-iframe.html

"Function Builder: Basics" consists of 2 screens:
• Patterns: identical to Function Builder, no changes
• Mystery: similar to Function Builder, but deals with images instead of numbers

If you need a Terminology refreshers, review the Terminology section of Function Builder's [implementation-notes.md](https://github.com/phetsims/function-builder/blob/master/doc/implementation-notes.md).

Sim-specific query parameters are documented in [FBQueryParameters.js](https://github.com/phetsims/function-builder/blob/master/js/common/FBQueryParameters.js).

The challenges for the "Mystery" screen are specified in [Function Builder: Basics - Mystery challenges](https://docs.google.com/spreadsheets/d/1_ndx3YmLA2H_w0iFouS6rur3EmDebyjPIf_OTmKy13M/edit#gid=0).  With `?showAnswers&playAll` the challenges will be presented in the same order that they appear in the specification.

I have tested primarily on Chrome, Safari and Mobile Safari. So please spot check on other platforms.

Please mention this issue in any GitHub issues that you create.

**Comment by pixelzoom** [comment]
@ariel-phet please prioritize and assign.

**Comment by phet-steele** [comment]
@pixelzoom @ariel-phet this testing is done.

**Comment by pixelzoom** [comment]
Thanks @phet-steele. I'll have an RC test task for you shortly.

**Comment by pixelzoom** [comment]
RC test task created. Closing.
