### ISSUE TITLE
Dev test: Graphing Lines 1.2.0-dev.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#825]
Previous dev test (1.2.0-dev.1) is https://github.com/phetsims/tasks/issues/816.  See that issue for pointers to query parameters, terminology, etc.

Dev test:
http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.2.0-dev.2/graphing-lines_en.html

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.2.0-dev.2/graphing-lines_en-iframe.html

GitHub issues to regression tests:
- [x] https://github.com/phetsims/graphing-lines/issues/75
- [x] https://github.com/phetsims/graphing-lines/issues/76
- [x] https://github.com/phetsims/graphing-slope-intercept/issues/16

In addition to the specific issues above, the fix for https://github.com/phetsims/graphing-lines/issues/78 (memory leak) touched a lot of code.  It's not necessary to re-verify the memory test.  But please give the entire sim a close look on at least 1 platform to make sure there was no collateral damage.

Please mention this issue in any GitHub issues that you create.

Assigned to @phet-steele, please work out prioritization with @ariel-phet.

**Comment by phet-steele** [comment]
@pixelzoom this is completed. Sim is very solid at this point.

**Comment by pixelzoom** [comment]
Thanks @phet-steele and team.

**Comment by pixelzoom** [comment]
Since this dev test went well (no issues), I was planning to use the 1.2.0-dev.2 shas for 1.2.0-rc.1.  But then I discovered that @jessegreenberg published 1.2.0-dev.3, and I have no idea if it addresses anything relevant to this sim.  So RC testing is blocked until I can find out what's up with 1.2.0-dev.3.

**Comment by pixelzoom** [comment]
Graphing Lines 1.2.0-dev.3 was used to test joist#140 (a11y heartbeat fix), not relevant to production sims yet.  So I can proceed with the shas from 1.2.0-dev.2.

**Comment by pixelzoom** [comment]
RC test task #843 created.  Closing.
