### ISSUE TITLE
Use event.canStartPress

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#826]
In https://github.com/phetsims/scenery-phet/issues/214#issuecomment-296918337 @jonathanolson said: 

Also worth noting:

```js
// Ignore non-left-mouse-button, see #64
if ( event.pointer.isMouse && event.domEvent.button !== 0 ) {
  return;
}
```
should probably be converted into
```js
// Don't try to start drags with a right mouse button or an attached pointer.
if ( !event.canStartPress() ) { return; }
```

**Comment by samreid** [comment]
I see 7 occurrences of this pattern across charges-and-fields, circuit-construction-kit, expression-exchange and projectile-motion.  @ariel-phet can you recommend a developer and priority level?

**Comment by ariel-phet** [comment]
@veillette do you mind taking care of this in charges and fields? And if easy the other sims listed?

**Comment by jonathanolson** [comment]
I had noticed this pattern in expression-exchange and tagged it with a REVIEW item.

**Comment by veillette** [comment]
all the instances of
``` event.pointer.isMouse && event.domEvent.button !== 0 ```

have been replaced

**Comment by veillette** [comment]
There are additional expressions which perform the same function:

```
 // Ignore non-left mouse buttons
          if ( event.pointer.isMouse && event.domEvent && event.domEvent.button !== 0 ) {
            return;
          }
```

These can be found in make-a-ten, and molecule-shapes.

@jonathanolson: should I go forward and replace them as well?

**Comment by jonathanolson** [comment]
I'll look into those.

**Comment by veillette** [comment]
As an update, there are three examples of the conditional expression
```
          if ( event.pointer.isMouse && event.domEvent && event.domEvent.button !== 0 ) 
```

one In moleculeShapeScreenView,js one is ExplorePanel.js and One in PaperNumberNode.js

Unassigning myself from this issue.

**Comment by samreid** [comment]
I know it's been a while, but this still seems good to investigate when there's time.

**Comment by jonathanolson** [comment]
Fixed and tested.
