### ISSUE TITLE
Dev test: Proportion Playground 1.0.0-dev.25

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#827]
General dev version testing desired for the latest version. Moved back to non-WebGL handling for the necklace/balloons, did major refactoring for the billiards table, and updated the rate for the number pickers (so those are good places to test more)

Dev test:
http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.25/proportion-playground_en.html

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.25/proportion-playground_en-iframe.html

Please mention this issue in any GitHub issues that you create.

Assigned to @phet-steele, please work out prioritization with @ariel-phet.

**Comment by ariel-phet** [comment]
@phet-steele this sim is definitely "tippy-top" priority

**Comment by phet-steele** [comment]
@ariel-phet @jonathanolson sim is done testing. Nothing big found (except performance).

**Comment by jonathanolson** [comment]
@phet-steele, I've published http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.26/proportion-playground_en.html (presumably as a sanity-check) version for reproducing crashing. It includes no changes since dev.25, but has updated common code.

**Comment by ariel-phet** [comment]
@phet-steele please see if this version is free from crashing

**Comment by phet-steele** [comment]
> @phet-steele please see if this version is free from crashing

It is not, here is an attempt to have other people try to reproduce: phetsims/proportion-playground/issues/74. Closing this dev test.
