### ISSUE TITLE
Dev Test: Gene Expression Essentials 1.0.0-dev.10

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#829]
@ariel-phet 

After current level of optimizations this simulation is still a bit choppy on IPad 2. 

It works very smoothly in Chrome Book and IPad Air and above. 

In discussion with @jbphet the target audience for this simulation is not going to be many on people on IPad2. 

Link for latest dev version
http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.10/ 

 Let us know what you think about performance on IPad2. We have a few more optimizations which we can do but are not straight forward.

**Comment by ariel-phet** [comment]
@aadish I took a look and after discussing with @jbphet it appears the rendering of mRNA is the bottleneck and would be good to improve. Closing, and creating a separate issue in the sim repo.
