### ISSUE TITLE
Website QA: Team Page translatability

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#832]
@phet-steele - I've made the "Our Team" page translatable and it required a significant retooling of the entire Team Member process.  Could you please schedule a QA test for the Team Page?  The proposed changes are currently deployed to https://ox-dev.colorado.edu/en/about/team

The processes that were affected include:
- [x] Creating a new Team Member
- [x] Deleting a Team Member
- [x] Editing an existing Team Member
- [ ] Translating the Team Page
- [ ] Previewing a translation of the Team Page

Everything should be translatable except for the names of people and companies.

**Comment by phet-steele** [comment]
Moved to phetsims/QA/issues/3
