### ISSUE TITLE
Artwork for Circuit Construction Kit

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#833]
@clmccutchan we'll need some artwork for the Grab Bag items for [Circuit Construction Kit: DC](http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.12/circuit-construction-kit-dc_en.html?dev). These items should be similarly scaled to the other components, like the batteries and resistors (~100px when the sim resolution is 1024x768). In [Java](https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc), these items were mostly photorealistic, but we'll want these items in line with our HTML5 style. 

- [x] Paper clip
- [x] Pink eraser with this perspective (no branding)
![image](https://cloud.githubusercontent.com/assets/8419308/25716828/bd459ac2-30bd-11e7-9edd-f3864db9e964.png)
- [x] Pencil, sharpened on both ends
- [x] Hand -- In Java, we used an image of the hand of God from Michelangelo's Creation of Adam. I think it would be nice to keep the hand posed similarly, though it certainly doesn't need to be so detailed. I think the style you used for the statue of David would work here.
![image](https://cloud.githubusercontent.com/assets/8419308/25716970/3f5bb8e8-30be-11e7-903b-964a847aef1a.png)
- [x] Dollar bill -- We'd like to go with a fictional currency, though it can still be green like American paper money. The simulation will also be using a fictional coin, but we'll be reusing artwork from Expression Exchange. Here's the coin, for comparison:
![image](https://cloud.githubusercontent.com/assets/8419308/25716251/a99c436a-30bb-11e7-8edd-cbb0041b9694.png)
- [x] Dog based on Emmy -- see https://github.com/phetsims/tasks/issues/833#issuecomment-305246639.

Please let me know if it would be helpful to schedule a Zoom chat!

**Comment by arouinfar** [comment]
@clmccutchan how are things coming along? It would be helpful if we could get the artwork to the developer soon. Do you have an estimate of when you'll have the artwork ready?

**Comment by clmccutchan** [comment]
@arouinfar This is on my list for today! The symmetrical cards took considerably longer than I would have guessed. I should have drafts of everything by next Tuesday. Will that work for you?

**Comment by clmccutchan** [comment]
@arouinfar, here are drafts of four of the five assets. I'm working on the dollar bill next. I know we had a discussion about sizing of the objects, but I can't seem to find anything in my notes. Do you recall the specifications you were looking for? 

![833_circuitconstruction_eraser](https://cloud.githubusercontent.com/assets/25354670/26633527/f1dca0b4-45d0-11e7-8ab6-d838c796a0f5.png)
![833_circuitconstruction_hand](https://cloud.githubusercontent.com/assets/25354670/26633529/f1ecb684-45d0-11e7-8bc2-399098de4142.png)
![833_circuitconstruction_paperclip](https://cloud.githubusercontent.com/assets/25354670/26633528/f1e21d3c-45d0-11e7-9c0f-f570619871ee.png)
![833_circuitconstruction_pencil](https://cloud.githubusercontent.com/assets/25354670/26633530/f1ff30b6-45d0-11e7-8675-eb585a75603b.png)

**Comment by arouinfar** [comment]
@clmccutchan these look great!! Most of these items will be ~100px wide on an iPad, but scaling the vector art shouldn't be a problem. Can you put these assets in your Google Drive folder (or email it to me) as a CS6 .ai file?

**Comment by arouinfar** [comment]
I'll also need to add the dog to your list, as well. I tracked down the .ai asset, and it turns out it's just the dog's head -- we'll need a full body.

**Comment by clmccutchan** [comment]
@arouinfar Yep, I'll get the file into my Google drive. Once I've got the dollar bill and dog in, I'll let you know and update the file. Note that the paperclip is made of a stroke with a gradient. If you scale it in Illustrator, you will also need to change the stroke width.

**Comment by arouinfar** [comment]
Thanks @clmccutchan! I was able to track down the dog artwork yesterday, and it looks like we just have a head, so I'll need to add the dog to your list. Not sure if it will be helpful, but I'll email you the asset for the dog head -- it's based on Ariel's dog. 

We'd still like to base the artwork on Ariel's dog. Here's a reference photo:
![image](https://cloud.githubusercontent.com/assets/8419308/26643082/530ebdce-45ed-11e7-9036-f5c3a684b78c.png)


The pose above is good, but the perspective is a bit too top-down. This angle would be preferable, but this exact positioning of the limbs is not important.
![image](https://cloud.githubusercontent.com/assets/8419308/26643122/77faf7ce-45ed-11e7-8ef4-4f9e9a1cc027.png)

Please let me know if you'd like to have a follow up chat.

**Comment by clmccutchan** [comment]
@arouinfar Oops, I forgot to convert the .ai file to CS6. I've got a dentist appointment in about 20 mins. I'll try to get the correct version for you before, but if not, then by 2 pm today

**Comment by arouinfar** [comment]
No worries @clmccutchan! By the end of the day will be fine. :)

**Comment by clmccutchan** [comment]
@arouinfar I'm pretty sure I can find a good side angle of the pose Ariel's dog is in and then I'll just use Ariel's dog's coloring.

**Comment by arouinfar** [comment]
Sounds perfect @clmccutchan!

**Comment by clmccutchan** [comment]
@arouinfar New cs6 version in Google drive!

**Comment by clmccutchan** [comment]
@arouinfar I'm looking at the assets and, while none of them are taller than 100 px, most are considerably longer than 100 px. Do you want me to scale these down for you? I can make the dog and money no wider than 100 px.

**Comment by arouinfar** [comment]
@clmccutchan no need to adjust anything. I'm more worried about the aspect ratio than the physical width. I ended up shortening the pencil a bit so that it's not too narrow at 100 px long.

**Comment by ariel-phet** [comment]
@clmccutchan if there is a specific angle/pose you want of Emmy (my dog) just let me know. I will be happy to take some pics.

**Comment by clmccutchan** [comment]
@ariel-phet Thanks, I'm all set! I just found some dog poses on the internet that I'll use to position the dog and then and Emmy's coloring.

**Comment by clmccutchan** [comment]
@arouinfar I've attached drafts of the dog and dollar. What do you think?

![833_circuitconstruction_cs6_dog](https://cloud.githubusercontent.com/assets/25354670/26694185/d5e09eb2-46c3-11e7-9e5a-ee4d335a5953.png)
![833_circuitconstruction_cs6_dollar](https://cloud.githubusercontent.com/assets/25354670/26694184/d5d995ea-46c3-11e7-8dd0-eb4207fbff39.png)

**Comment by arouinfar** [comment]
@clmccutchan I really like the direction of the dollar bill. I'd like to see the circle vertically centered in the bill, and it would also be good to replace the serif PhET with our logo (sans plane). I'll send you an .ai file with the PhET logo.

Can you also add a collar to the dog? @ariel-phet was there any other feedback you had?

**Comment by ariel-phet** [comment]
No, that all sounds good

**Comment by clmccutchan** [comment]
@arouinfar Here are new drafts of the dog and the dollar. I could potentially darken the PhET logo on the dollar bill so that it stands out a bit better.

![833_circuitconstruction_cs6_dog](https://cloud.githubusercontent.com/assets/25354670/26792708/8bee4148-49d8-11e7-8faf-c39e0efa522a.png)
![833_circuitconstruction_cs6_dollar](https://cloud.githubusercontent.com/assets/25354670/26792707/8be81476-49d8-11e7-894d-cb830d93b319.png)

**Comment by arouinfar** [comment]
Looks good @clmccutchan! I accidentally sent you the wrong logo file (iO shouldn't be included), but that's something I can easily adjust on my end. Please go ahead and drop these in your Drive folder.

**Comment by clmccutchan** [comment]
@arouinfar The .ai file is in my Google drive now.

**Comment by arouinfar** [comment]
Thanks @clmccutchan!

**Comment by samreid** [comment]
@arouinfar please let me know when the dog and dollar are ready.

**Comment by arouinfar** [comment]
@samreid I've emailed you the last of the assets. Discussion can continue in https://github.com/phetsims/circuit-construction-kit-common/issues/264 (or new issues, if needed).  Thanks again @clmccutchan!
