### ISSUE TITLE
Artwork for Coulomb's Law

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#834]
@clmccutchan we're working on a new sim called Coulomb's Law. It will be somewhat similar to [Gravity Force Lab](https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html), as they're both inverse square laws. In Gravity Force Lab, there are figures that pull against the masses so that they don't accelerate towards one another.
![image](https://cloud.githubusercontent.com/assets/8419308/25718449/561755d8-30c3-11e7-9d0a-a2759de91677.png)

In Coulomb's Law, we'll be dealing with attractive and repulsive forces, so we'll need artwork for figures that are able to push and pull against the charges. Somewhat recently, we updated the pushers in [Forces and Motion: Basics](https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html) (pushers are in screens 2-4). We would like to create pullers in the same style to use in Coulomb's Law. I will email you the .ai file for the pushers.

I think it may be helpful if we could schedule a short Zoom chat sometime next week. We can coordinate via email to set up a time.

**Comment by ariel-phet** [comment]
@clmccutchan any movement on this issue? The sim is moving along nicely and it would be good to get the artwork inserted in the next couple of weeks.

**Comment by clmccutchan** [comment]
@ariel-phet This is next up on my list. I'm hoping to have it complete by mid-next week.

**Comment by clmccutchan** [comment]
@arouinfar I've got a draft of the puller. The pullers are stacked on top of each other on a single artboard. I'll send you the .ai file via email.

**Comment by arouinfar** [comment]
Sounds good @clmccutchan!

**Comment by arouinfar** [comment]
Looks great @clmccutchan!! Self-assigning to export the images and deliver the assets to @jessegreenberg.

**Comment by ariel-phet** [comment]
@arouinfar do we also have the "pullers made of atoms"...and the "hair sticking up pullers"? Just checking since I don't see any mention of those in the issue.

**Comment by mbarlow12** [comment]
@arouinfar have you sent @jessegreenberg the images? Or do you have any updates on their status?

**Comment by arouinfar** [comment]
@mbarlow12 I've been working on them this afternoon, so I should have things ready for you and @jessegreenberg soon.

**Comment by arouinfar** [comment]
Artwork has been delivered to @mbarlow12 and @jessegreenberg. Closing.
