### ISSUE TITLE
Change your unfuddle password

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#835]
There was an unfuddle security breach and they are recommending all users change their password. You should be prompted to change upon sign in.
https://unfuddle.com/blog/2017/05/important-notice/

Please check your name when your password has been updated:

- [x] Amanda McGarry 
- [x] Amy Hanson 
- [x] Amy Rouinfar 
- [x] Arnab Purkayastha 
- [x] Emily Moore 
- [x] Kathryn Dessau 
- [x] Michael Kauzmann 
- [ ] Sam McKagan 
- [x] martin veillette 

Edit - Mike and trish have been removed

**Comment by oliver-phet** [comment]
It doesn't appear Dubson or Trish are on github?
@dubson

**Comment by pixelzoom** [comment]
I set permissions to "None" for the remaining people who have not changed their passwords: Arnab Purkayastha,  Michael Dubson, Sam McKagan, Trish Loeblein.   When one of them attempts to login, they will be required to change their password.  Then they'll find out they can't access anything.

**Comment by oliver-phet** [comment]
Sam McKagan was deleted. Closing.
