### ISSUE TITLE
RC Test: Resistance In A Wire 1.3.0-rc.1 and 1.3.0-phetiorc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#836]
Phet link:
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-rc.1/resistance-in-a-wire_en.html

PhET-iO link to wrappers index (password protected and hidden in the parent version dir):
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.1/wrappers/index

These two versions were just created from master shas. The sim was newly instrumented for PhET-iO and went through major code refactoring and review in the process (thanks @samreid @veillette for all the help), so it will be useful to publish a phet version while we are at it. 

Please reference this issue in any related issues that are created.

There are no sim-specific query parameters.

Assigning to @ariel-phet for priority and delegation.

**Comment by phet-steele** [comment]
@zepumph @samreid am I wrong in saying this should be a dev test?

**Comment by samreid** [comment]
Normally we start with a dev test, but I thought it would be prudent to create branches in case we move forward to production with this.  Will it change your process much/at all?

**Comment by zepumph** [comment]
We need to maintenance these shas into these releases

https://github.com/phetsims/scenery-phet/commit/f210433ebe9880152f420a51c036fd5e95f783c9
https://github.com/phetsims/scenery-phet/commit/727d5bd7ac8d93a1c6e8b78b27c9fb6a8a4e783d

**Comment by phet-steele** [comment]
Moved to phetsims/QA/issues/4
