### ISSUE TITLE
RC test: Proportion Playground 1.0.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#839]
@amanda-phet, [Proportion Playground] 1.0.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.1/proportion-playground_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.1/proportion-playground_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1dJzClegHHu4zB-cR5A4odlOBx-0ygy2CXtpm-UezJ0c/edit#gid=2)**

**Please verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/proportion-playground/issues and reference this issue.  

 
**(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?scene={{scene}}` - Starts with a different scene active by default

Sim-specific terminology:
• Scenes are "necklace", "paint", "billiards" and "apple"

**Comment by phet-steele** [comment]
@jonathanolson rc.1 finished. Ready for rc.2 when you are.

**Comment by jonathanolson** [comment]
Thanks, rc.2 in https://github.com/phetsims/tasks/issues/845. Closing.
