### ISSUE TITLE
Spot check: John Travoltage 1.3.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#841]
@phet-steele found an IE11 specifiic problem with rc.2, caused by one of the fixed for rc.1. Fix is in place, 1.3.0-rc.3 is ready for spot checking.

[Link to sim](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-rc.3/john-travoltage_en.html)

[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-rc.3/john-travoltage_en-iframe.html)

Could you please verify that the following issues have been fixed?

 - [x] phetsims/john-travoltage#249
 - [x] phetsims/john-travoltage#252

**Comment by ariel-phet** [comment]
@phet-steele - looks like you have checked these off, but obviously still a top priority until complete

**Comment by jessegreenberg** [comment]
It's live!
