### ISSUE TITLE
RC test: Proportion Playground 1.0.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#845]
@amanda-phet, [Proportion Playground] 1.0.0-rc.2 is ready for RC testing. Only spot checks needed.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.2/proportion-playground_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.2/proportion-playground_en-iframe.html)**

**Please verify**

- [x] The "Show Both" and any billiards-related icons look fine (normalized the billiards icon size there), see https://github.com/phetsims/proportion-playground/issues/98
- [x] Things related to the paint scene and visibility (fixed the delay at https://github.com/phetsims/proportion-playground/issues/100).

**Open (deferred) issues**

- https://github.com/phetsims/proportion-playground/issues/101

If any new issues are found, please note them in https://github.com/phetsims/proportion-playground/issues and reference this issue.  

 
**(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?scene={{scene}}` - Starts with a different scene active by default

Sim-specific terminology:
• Scenes are "necklace", "paint", "billiards" and "apple"

**Comment by phet-steele** [comment]
@jonathanolson @amanda-phet @ariel-phet this rc test was downgraded to a spot check, no full matrix was needed.

**Comment by EthanWJohnson** [comment]
Have found no issues here--paint scene, with show both or otherwise.

**Comment by phet-steele** [comment]
@jonathanolson, the ball is in your court with phetsims/proportion-playground/issues/73.
