### ISSUE TITLE
Test Build an Atom 1.2.6-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#851]
For https://github.com/phetsims/build-an-atom/issues/162 @jessegreenberg and I prepared an RC that has the following changes:
1. The sim broadcasts a start message for legends of learning
2. The sim responds to legends of learning pause/resume messages
3. This includes @jbphet's changes to the timer for the game screen so it will also pause and resume.

It was published here:
http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.6-rc.2/build-an-atom_en.html

This is a maintenance release, and hence is using safe SHAs and only has the minor changes as described above.  Full testing will not be required.  However, this sim will be republished on our website as a new production version, so we would like to be confident that these changes haven't disrupted anything.  The changes (1) and (2) above are buried under a query parameter, so I guess mainly we should sanity check things in the new build and make sure the game timer still behaves as expected.

This will be our first test of the Legends of Learning platform.  To test, launch:
harness.legendsoflearning.com

Then put this as "game URL" (note the legends of learning query parameter):
http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.6-rc.2/build-an-atom_en.html?legendsOfLearning

Check that "init" "pause" and "resume" all work properly.  This harness test should be done on all of legends of Learning supported platforms, which are indicated here:

https://www.legendsoflearning.com/teachers/faq/
> Legends of Learning supports Chromebooks, iPad Air 2, and iPad Air Pro. Laptop/desktop computers will also work. Android tablets and smartphones are not officially supported.

If this checks out, we will publish this sim to the Legends of Learning store.  Then if all is well, we can use this same strategy for rolling out maintenance releases for all of the other science HTML5 sims.

From https://github.com/phetsims/special-ops/issues/70#issuecomment-305570609 @kathy-phet said: 
> @kathy-phet says would be good to be tested by mid-June.

Reassigned to @ariel-phet for prioritization, scheduling and reassignment, and to add any other labels as necessary.

**Comment by samreid** [comment]
This has been top priority for 7 days.  Can I get a status check?  Should @jonathanolson and I wait for full testing results before addressing https://github.com/phetsims/scenery/issues/619 ?

**Comment by phet-steele** [comment]
> Can I get a status check?

@samreid this has been tested pretty heavily on chromebook and iPad Air 2. Enough testing has been done on desktop where we are probably okay, but it hasn't been enough for the team to "sign off" if you know what I mean.

**Comment by samreid** [comment]
Sounds good, please keep me posted.

**Comment by phet-steele** [comment]
@samreid, sanity checked. Timer behaves nominally.

**Comment by samreid** [comment]
Thanks, we'll proceed with fixing the identified problem in https://github.com/phetsims/build-an-atom/issues/162
