### ISSUE TITLE
RC test: Graphing Slope-Intercept 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#852]
RC version:
http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-rc.2/graphing-slope-intercept_en.html

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-rc.2/graphing-slope-intercept_en-iframe.html

Text matrix:
https://docs.google.com/spreadsheets/d/1Tocnn1DCtML3rrYDJj4pTgQ96tE0caTQR4fqYeA0vuU/edit#gid=315434409

In addition to the test matrix, please perform these specific tests on 1 or 2 platforms:

- [x] ?stringTest=double (double all strings)
- [x] ?stringTest=long (excessively long strings)
- [x] ?stringTest=X (short strings)
- [x] ?stringTest=rtl (right-to-left text direction)
- [x] ?stringTest=xss (test for security issues, passes if it does NOT redirect to another page)
- [x] full screen test
- [x] screenshot test

Issues to regression test from previous RC task https://github.com/phetsims/tasks/issues/815#issuecomment-296767592:

- [x] #17 pick up the fix for web audio
- [x] #18 layout of level-selection buttons

Other issues were verified during testing of Graphing Lines 1.2.0, and this RC version uses the same shas as that release.

Other useful info:

• Game challenges, and the rewards for a perfect score in each level, are specified in:
https://docs.google.com/document/d/1ztSRN1YE1BIGI1rsCBnZXzZQYvelSFySp4sDHPh2OJs/edit#

• Sim-specific query parameters are in [GLQueryParameters.js](https://github.com/phetsims/graphing-lines/blob/master/js/common/GLQueryParameters.js).  These have been simplified a bit since 1.0.0-dev.1, so review them again.

• Terminology is defined in [implementation-notes.md](https://github.com/phetsims/graphing-lines/blob/master/doc/implementation-notes.md).

Please mention this issue in any GitHub issues that you create.

**Comment by pixelzoom** [comment]
Note to self: This RC was created using the same shas as Graphing Lines 1.2.0.    Here's the process:

```
% cd graphing-lines
% git checkout 1.2
% grunt checkout-shas
% cd ../graphing-slope-intercept
% git checkout 1.0
% grunt
% grunt deploy-rc
```

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/27143274-13572f50-50eb-11e7-93db-315c5e23525a.png)

**Comment by pixelzoom** [comment]
Thank you @phet-steele and QA team.  No issues found, so we will proceed to publication.
