### ISSUE TITLE
RC Test: Plinko Probability 1.1.0-rc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#854]
**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.0-rc.1/plinko-probability_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.0-rc.1/plinko-probability_en-iframe.html)**

**[Link to Test Matrix](https://docs.google.com/spreadsheets/d/1Z1HvuZpJIaHYHikb6X5klkvDdgYjCHiY5jtW2OA1jjo/edit#gid=815015682)**

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/plinko-probability/issues and reference this issue.  

 
**(Other potentially useful items)**  

@veillette  please fill in additional tests needed. I didn't take point on this work, so I am unaware of specifics with this sim. 

This rc is mainly in correlation with phetsims/plinko-probability#99, and the new design of pegs when there are less than 5 of them.

@ariel-phet please assign and prioritize.

**Comment by ariel-phet** [comment]
Marking as high priority since the sim might be used in a study soon

**Comment by zepumph** [comment]
Ideally this, with https://github.com/phetsims/tasks/issues/855,  could be done by the end of next week for a study on Tuesday the 20th. @ariel-phet please comment if this is a deadline that we want to try to adhere to, I can relay this back to Ian either way.

**Comment by veillette** [comment]
The main additional concern that should be targeted in this RC candidate is the performance on the iPad2.
Since the Pegs and the Balls must look visually good at row 1 rather than five, the images of the peg and ball is much larger.
I expect that it may be more costly to render the balls and the pegs.

Performance wise, we are aiming to be on par with the current published simulation.

**Comment by phet-steele** [comment]
@zepumph @jonathanolson let's pick up the changes in phetsims/scenery-phet/issues/312

**Comment by phet-steele** [comment]
@zepumph testing done with one issue mentioned above. Performance on iPad 2 between this version and the production version was identical.

**Comment by zepumph** [comment]
@ariel-phet could you please assign someone to publish this phet version to the website. Feel free to keep it on me and I can give it a whirl. I had no part in the changes made, nor have I ever published a phet brand sim to the website. I wanted to give the opportunity for someone else to take over if that should happen.
