### ISSUE TITLE
RC Test: Plinko Probability 1.1.0-phetiorc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#855]
This is a test for https://github.com/phetsims/phet-io/issues/1140 to get Plinko Probability record and playback ready for Ian and a study he is conducting.

Here is the RC link:
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.0-phetiorc.1/wrappers/index/

Note: most of the phet-io features are not functional, only the record and mirro- input wrappers should be tested. We will also need to add the phetioValidateTandems=false parameter, because we haven't passed any tandems into the sim, it is not instrumented. The index page allows you to toggle tandem validation in the bottom left of the page.

This rc is using the same shas as Plinko 1.1.0-rc.1 in #854, and a phet brand test should be done as part of this release (but perhaps testing can be combined somehow). 

Ariel please assign and prioritize.

**Comment by zepumph** [comment]
I reached out to Ian recently asking him to try to specify specific devices and or browsers that he will be using for the study, and he has not responded yet, if he does with useful info to help narrow the focus of this RC Test, I will pass it on to this issue.

**Comment by ariel-phet** [comment]
@phet-steele it probably makes sense to work on #854 first, and not begin this test until you are reasonable confident the the production release has no major issues. Also would be good to wait for a narrower list of platforms for the iO test.

**Comment by zepumph** [comment]
I just heard back from Ian. We are looking to try to get him the phetio version before Tuesday the 20th, so there is a bit more time than we thought, but I think the end of next week delivery would be a good goal. 

Ian said that he is unsure of browsers, but the computer bank is all PCs.

**Comment by phet-steele** [comment]
Record and Mirror-Input wrappers performed great on macOS 10.12.5 Chrome.

**Comment by phet-steele** [comment]
Record and Mirror-Input wrappers performed great on Win 10 Chrome, FF, and IE 11 as well.

> EDIT2: Ian: "The PCs are running Windows XP. They have Explorer, Firefox, and Chrome."

We do not, and probably never will, perform testing on Win XP. We do not have a device with it loaded, I believe. So @zepumph, maybe we just cross our fingers that it works? 

> most of the phet-io features are not functional, only the record and mirror- input wrappers should be tested

Recording and mirror inputs were the only two tests run on the above platforms. @zepumph is this reasonable?

**Comment by zepumph** [comment]
@phet-steele I hate to do this to you, but it seems only right that we would also look at the plain ole simulation with tandem validation disabled. Could you spend a bit more time on this as well?
http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.0-phetiorc.1/plinko-probability_en-phetio.html?phetioStandalone&phetioValidateTandems=false

**Comment by phet-steele** [comment]
> I hate to do this to you, but it seems only right that we would also look at the plain ole simulation with tandem validation disabled

No worries, finished! (Win 10 Chrome, FF, and IE 11)

**Comment by zepumph** [comment]
Thanks! Waiting on https://github.com/phetsims/tasks/issues/854 to proceed.

**Comment by zepumph** [comment]
All was good for both versions. I will continue in https://github.com/phetsims/phet-io/issues/1140 with a cherry pick and a phet-io publish.
