### ISSUE TITLE
Add Legends of Learning to the QA checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#856]
At yesterday's meeting it was suggested to add "Testing the Legends of Learning" features to the QA checklist.  The basic instructions for how to test with the Legends of Learning harness are identified in #851.  We should rigorously test the first several sims while this is a new technology, then we can re-evaluate after we have some more experience.  Any sim built with June 2017 Joist or later will have this feature built-in.

@ariel-phet and/or @phet-steele can you please direct me to the best place to document this?   Should it be in a test matrix template or somewhere else?

**Comment by ariel-phet** [comment]
@samreid I would think https://github.com/phetsims/phet-info/blob/master/issue-info/sample_rc_test_task.md would be a good place. 

What say you @phet-steele?

**Comment by ariel-phet** [comment]
And @phet-steele please take the appropriate action and close this issue, no need to reassign to me.

**Comment by phet-steele** [comment]
Yes, the rc template is a good place to put it. I've went ahead and done this.

> And @phet-steele please take the appropriate action and close this issue, no need to reassign to me.

How about I assign to you, then close?
