### ISSUE TITLE
RC Test: Balloons And Static Electricity 1.3.0-phetiorc.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#857]
Here is the link:
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-phetiorc.2/wrappers/index/

I'm new at the the iterative RC process, but I think we just need to spot check some issues from the first rc (https://github.com/phetsims/tasks/issues/848):
- [x] https://github.com/phetsims/phet-io/issues/1143
- [x] https://github.com/phetsims/phet-io/issues/1141

Feel free to close if they are fixed.

@ariel-paul please assign and prioritize. Ideally @jbphet would be able to use the published version on Tuesday.

**Comment by phet-steele** [comment]
@zepumph @jbphet verified above issues on macOS 10.12.5 Chrome and Win 10 FF.

**Comment by zepumph** [comment]
I will publish this today for @jbphet to use tomorrow.
