### ISSUE TITLE
RC Test: John Travoltage 1.4.0-phetiorc.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#858]
Here is the link:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.4.0-phetiorc.2/wrappers/index/

I'm new at the the iterative RC process, but I think we just need to spot check some issues from the first rc (https://github.com/phetsims/tasks/issues/846):
- [x] https://github.com/phetsims/phet-io/issues/1143
- [x] https://github.com/phetsims/john-travoltage/issues/254
- [x] https://github.com/phetsims/phet-io/issues/1141
- [x]  https://github.com/phetsims/john-travoltage/issues/255

Feel free to close if they are fixed.

@ariel-paul please assign and prioritize. Ideally @jbphet would be able to use the published version on Tuesday.

**Comment by phet-steele** [comment]
@zepumph @jbphet verified above issues on macOS 10.12.5 Chrome and Win 10 FF. Although, looks like will need some more fixing.

**Comment by zepumph** [comment]
Yeah it will, it will need a one word change to get it back to where it was before, pretty safe. I will publish from there. Thanks @phet-steele for the hard work! Closing.
