### ISSUE TITLE
RC Test: Build An Atom 1.5.0-phetiorc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#859]
Here is the link:
http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.5.0-phetiorc.1/wrappers/index/

This is actually the third rc, but because of https://github.com/phetsims/build-an-atom/issues/163 we moved from 1.4 to 1.5.
I'm new at the the iterative RC process, but I think we just need to spot check some issues from the last rc (https://github.com/phetsims/tasks/issues/850):

- [x] https://github.com/phetsims/build-an-atom/issues/163 
- [x] https://github.com/phetsims/phet-io/issues/1143
- [x] https://github.com/phetsims/phet-io/issues/1141
- [x] https://github.com/phetsims/build-an-atom/issues/160
- [x] https://github.com/phetsims/build-an-atom/issues/164

Feel free to close if they are fixed.

@ariel-paul please assign and prioritize. Ideally @jbphet would be able to use the published version on Tuesday.

**Comment by phet-steele** [comment]
@zepumph @jbphet verified above issues on macOS 10.12.5 Chrome and Win 10 FF.

**Comment by zepumph** [comment]
Thanks for all you do. I will publish from here. Closing.
