### ISSUE TITLE
dev test: Expression Exchange 1.1.0-dev.3

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#860]
Expression Exchange is getting close to being ready for an RC, but a lot of code was touched during the recent code review, so a round of dev testing would be wise.  Please test it fairly thoroughly for basic functionality on at least one platform, test basic functionality on several platforms, and look at performance on our worst case performance platform (which I believe is iPad 2).

Link: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-dev.3/expression-exchange_en.html

In addition, this would likely be a good time to validate that the following issues are resolved (please close the issue if found to be resolved):

- [x] https://github.com/phetsims/expression-exchange/issues/31
- [x] https://github.com/phetsims/expression-exchange/issues/64
- [x] https://github.com/phetsims/expression-exchange/issues/67
- [x] https://github.com/phetsims/expression-exchange/issues/71
- [x] https://github.com/phetsims/expression-exchange/issues/79
- [x] https://github.com/phetsims/expression-exchange/issues/80
- [x] https://github.com/phetsims/expression-exchange/issues/85
- [x] https://github.com/phetsims/expression-exchange/issues/103

Assigning to @ariel-phet to add any additional thoughts and to prioritize.

- [x] Mac Safari
- [x] Windows Chrome
- [x] iPad 2

**Comment by phet-steele** [comment]
This is done. 1.1.0-dev.4 is out and being used to verify the above issues.
