### ISSUE TITLE
RC Spot Check: Balloons and Static Electricity 1.2.4-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#861]
@ariel-phet @phet-steele after a fix for https://github.com/phetsims/balloons-and-static-electricity/issues/273, balloons-and-static-electricity 1.2.4-rc.1 is ready for a spot check.  Changes in that issue were not invasive, a full test is not necessary.

[**Link to sim**](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.4-rc.1/balloons-and-static-electricity_en.html)

[**Link to iframe**](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.4-rc.1/balloons-and-static-electricity_en-iframe.html)

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them. If not, they should be updated.
- [x] https://github.com/phetsims/balloons-and-static-electricity/issues/273

If any new issues are found, please note them in https://github.com/phetsims/balloons-and-static-electricity/issues and reference this issue.

@ariel-phet could you please prioritize and assign this issue?

**Comment by ariel-phet** [comment]
@phet-steele I imagine this will be a fairly quick test, but currently lots in line before it higher priority

**Comment by jessegreenberg** [comment]
@phet-steele mentioned that this change could require a new screenshot. This comment is just a reminder so we don't forget.

**Comment by phet-steele** [comment]
@jessegreenberg, checked Win 10 Edge, macOS 10.12.5 Chrome, and iOS 10.3.2 Safari. Good to go.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, excellent, will deploy today.

**Comment by jessegreenberg** [comment]
@phet-steele took an updated screenshot (thanks!!).  Going through redeploy steps now.

**Comment by jessegreenberg** [comment]
Deployed, and I can see the new screenshot on the site.  Closing.
