### ISSUE TITLE
animated GIFs created with Camtasia can't be viewed in Safari desktop

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#862]
The GIF added to https://github.com/phetsims/scenery/issues/619#issuecomment-308221723 causes desktop Safari 10.1.1 (11603.2.5) to error on Mac OS X 10.11.6 when I open that issue. According to @phet-steele, I am "literally the only person with this problem". 

This is not the first time that I've experienced this problem, and it requires me to open issues like this with a different browser, which is very inconvenient.

According to @phet-steele, this GIF (and others that I've had a problem with) were created using Camtasia.

**Comment by pixelzoom** [comment]
@samreid said:
> I'm using Safari Version 10.1.1 (12603.2.4) on MacOS Sierra 10.12.5 and the page is loading OK. Is the problem loading any GIFs on Safari? Or just certain GIFs?

**Comment by pixelzoom** [comment]
>  Is the problem loading any GIFs on Safari? Or just certain GIFs?

It appears to be a problem only with the GIFs that @phet-steele creates with Camtasia.  Preview and Photoshop CS6 also have problems with these GIFs.  If I download the GIF from the above comment, here's the info about the file:

```
% file 27100474-802c2b90-503b-11e7-812c-cb991718bb2e.gif 
27100474-802c2b90-503b-11e7-812c-cb991718bb2e.gif: GIF image data, version 87a, 1747 x 829
```

**Comment by pixelzoom** [comment]
Preview error when attempting to open the animated GIF that appears in https://github.com/phetsims/scenery/issues/619#issuecomment-308221723:

![screenshot_280](https://user-images.githubusercontent.com/3046552/27146866-0409a1c4-50f8-11e7-928a-6466d55dd226.png)

Photoshop CS6 experiences the "beachball of death" and must be force quit.

**Comment by pixelzoom** [comment]
I tried these recommendations:

**Comment by pixelzoom** [comment]
I tried these recommendations: https://support.apple.com/en-us/HT203353

All extensions off, unnecessary plug-ins and add-ons deleted ... still crashing.

**Comment by pixelzoom** [comment]
Here's what I see each time I try to load phetsims/scenery#619 in Safari:

![screenshot_281](https://user-images.githubusercontent.com/3046552/27147077-bf9756a2-50f8-11e7-9828-5a1854d60f75.jpg)

**Comment by pixelzoom** [comment]
I viewed animated GIFs from a few test websites using Safari and Preview, no problems.  The ones that I downloaded reported `version 89a`, while Camtasia is creating `87a`.  Not sure if that's relevant.

**Comment by pixelzoom** [comment]
@phet-steele is use Camtasia 2.10.5 (91864) on macOS 10.12.5.

**Comment by pixelzoom** [comment]
No plans to work on this, hopefully the problem will go away with a new version of Camtasia, Safari or macOs.  Unassigning for now.

**Comment by pixelzoom** [comment]
The animated GIF in  phetsims/scenery#619 (comment)  still crashed my Safari.
But the animated GIF in https://github.com/phetsims/molecule-polarity/issues/56 does not.
????

**Comment by ariel-phet** [comment]
We seem to no longer be facing this issue in github issues. Closing
