### ISSUE TITLE
How about a "tasks:spot-check" label?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#863]
@ariel-phet @phet-steele and other QA folks, would this label be helpful in prioritizing issues and organizing tasks that may not take very long?

My thought is that this would be most often used for RC tests >= 2 that just have issues that need to be confirmed as fixed. For an issue that that is inherently fast and easy.

There is probably a better name out there. Assigning to people to see if people want/would use it.

**Comment by zepumph** [comment]
maybe `type:spot-check` makes more sense.

**Comment by ariel-phet** [comment]
@zepumph `type:` is usually reserved for bugs in our labeling scheme so far

Perhaps we need a new part of the scheme, something the can precede something like `spot-check` or such

We have 'tasks:QA' but maybe it is time to switch this up and have various 'QA:' labels. Such as 'QA:spot-check' 'QA:dev-test' 'QA:rc-test' or such

**Comment by zepumph** [comment]
I like that idea, then the need for tasks:QA would not be necessary.

**Comment by ariel-phet** [comment]
@phet-steele what say you about at QA specific repo?

**Comment by ariel-phet** [comment]
@phet-steele I have decided to move ahead with this suggestion. It is on the developer meeting agenda (doc) now
