### ISSUE TITLE
ISTE 2017 booth video

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#866]
@ariel-phet please review the video at https://github.com/phetsims/phet-info/blob/master/conferences/ISTEProjectionVideo_06-15-2016.mp4 and suggest any wanted additions.

**Comment by ariel-phet** [comment]
@phet-steele lets remove graphing lines, but add the following sims:

States of Matter
Function Builder
Make a Ten

**Comment by phet-steele** [comment]
Video approved and uploaded here: https://github.com/phetsims/phet-info/blob/master/conferences/ISTE_2017.mp4

Leaving open for myself to put this on some devices.

**Comment by phet-steele** [comment]
Video loaded onto Curie.
