### ISSUE TITLE
RC Test: Forces and Motion Basics 2.3.0-phetiorc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#869]
@samreid @jessegreenberg  so they know this is in the queue.

This RC is from the same shas as https://github.com/phetsims/tasks/issues/868, so it should be done after testing the phet features. Here is the link to index.

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.1/wrappers/index/

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues/227 and reference this issue.  

Parent issue for the design changes and implementation: https://github.com/phetsims/forces-and-motion-basics/issues/220

Here is the list of all the changes that have been added 

>- All changes are in the "Net Force" screen
>- NetForceScreenView includes two new ```CartStopperNodes``` placed at a location which will stop movement of the cart.
>- The cart can move about twice as far along the screen since the stoppers are placed farther than the previous version allowed the cart to move.
>- The pullers stand up when the game is over
>- The speedometer was added to the center of the cart, showing speed of the moving cart
>- A "Speed" checkbox was added to the control panel, which toggles visibility of a speedometer

**Comment by ariel-phet** [comment]
marking medium after #868

**Comment by phet-steele** [comment]
Moved to phetsims/QA/issues/6
