### ISSUE TITLE
QA repo setup and task migration

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#871]
@phet-steele now that a QA specific repo exists can we do the following?

- [x] migrate open QA issues to the QA repo
- [x] migrate appropriate checklists to the QA repo (example RC test task and such)
- [x] create some QA specific labels (`QA:spot-check` for instance) , and others ones that you feel might be appropriate (I think there should also be something in the realm of `QA:upcoming` or `QA:expected` or `QA:scheduling`) or such
- [x] remove the `tasks:QA` label once everything is migrated

**Comment by phet-steele** [comment]
> create some QA specific labels

So far I have:

`QA:a11y`
`QA:ios-app`
`QA:android-app`
`QA:website`
`QA:batch-maintenance-release`
`QA:spot-check`
`QA:phet-io`
`QA:dev-test`
`QA:rc-test`

@ariel-phet, not really sure what the purpose is of `QA:expected` and such. Why not just make the QA issue when it's ready?

> remove the tasks:QA label once everything is migrated

Won't this delete the label from all issues in this repo? We'd still want to preserve past QA task issues.

**Comment by phet-steele** [comment]
> not really sure what the purpose is of QA:expected and such

@ariel-phet said (in person) that it would be a good idea to create a QA outlook so deadlines/priorities could be planned, without conflict, by all members of the team. Not sure that github is the best place for this. A calendar might be better.

> remove the tasks:QA label once everything is migrated

Not going to do this.

**Comment by ariel-phet** [comment]
closing, we are fully migrated and working nicely
