### ISSUE TITLE
Primer Stats

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#872]
@oliver-phet it would be good for us to look at some primer stats, perhaps current, and quarterly for the last year. 

Since we are investing quite a bit of resources into primers, it would be helpful to understand usage
- how large is usage?
- is it growing?
- rate of growth?
- are there certain kinds of sims/primers getting more attention?

I think that would help us prioritize which primers to work on, and the level of priority for primers in general

**Comment by ariel-phet** [comment]
Obviously, not something that needs attention until after ISTE

**Comment by arouinfar** [comment]
@ariel-phet @oliver-phet do we have any stats for Teacher Tips? It may be worth comparing Teacher Tip downloads to Primer stats, as well.

**Comment by oliver-phet** [comment]
I can get the analytics through vimeo for primer views. @mattpen how would I get Google analytics for a URL like this? https://phet.colorado.edu/services/download-servlet?filename=%2Fteachers-guide%2Fbuild-an-atom-html-guide.pdf

**Comment by mattpen** [comment]
@oliver-phet - I don't believe we are tracking hits to static files (non-HTML pages) in Google Analytics.  We could set something up for the future, using an approach [like this](http://www.ybo-interactive.com/blog/2008/05/29/track-non-html-files-with-google-analytics/), but for know the only way we can find these numbers is by analyzing the access logs for the website.

I can write a script to scrape the logs for counts on the primers.  How far back in time are we interested in tracking? (Gathering data prior to August 2016 will require a bit more work)

**Comment by oliver-phet** [comment]
To discuss at dev meeting.

**Comment by mattpen** [comment]
I will write a script to get historic data for the past year (since phet-server went live).  I'll open a separate issue in the website repo to track download clicks in GA moving forward.

**Comment by mattpen** [comment]
The GA tracking will be implemented as part of phetsims/website#621

**Comment by mattpen** [comment]
@ariel-phet According to the apache logs (with bot access filtered out), here are the statistics for teacher-guide access:

- how large is usage?
    - Over 16k total requests for teachers guides in the past year.
    - Average of 112 requests per guide for the past year, varies between 1 and 3500 requests
- is it growing?
    - These are the total requests per month.  
![image](https://user-images.githubusercontent.com/11747676/27926829-ff13330a-6246-11e7-908d-ed9dd8f0020e.png)

- rate of growth?
    - The chart above indicates growth through the end of the school year, but there were several problems with apache log retention through December.
    - I'd say it's really an indication of an average of over 2000 requests per month that stays static while school is in session.  It would be difficult to compare against previous years, but I can look into it if needed.
- are there certain kinds of sims/primers getting more attention?
    - Yes, here are the sims/primers with over 100 requests total.  There are 115 primers that have received less than 100 requests in the past year.
![image](https://user-images.githubusercontent.com/11747676/27927081-d4e307b2-6247-11e7-95ad-551e7562e19d.png)

Here is a copy of the teachers-guide data with the pivot chart:
[teachers-guides.xlsx](https://github.com/phetsims/tasks/files/1128900/teachers-guides.xlsx)

**Comment by mattpen** [comment]
@ariel-phet - Does the above data answer the questions?  Do you need anything else?

**Comment by oliver-phet** [comment]
I think that's all we need on your end @mattpen, thanks. I might use your data to compare it with primer views.

**Comment by oliver-phet** [comment]
I compared the primer plays and teacher guide downloads (for those sims that had data for both primer and guide). It looks like, on average, the primers are getting more 'plays' than guides are 'downloaded' (roughly 25% more plays than downloads) over the same 13-month period .

It is difficult to parse out the growth of primer plays and guide downloads since use is cyclical and new primers contribute to increased plays. I looked at the most recent lull in primer uploads (8/2016-3/2017) to see the statistics of a static library of primer videos:

![image](https://user-images.githubusercontent.com/5090275/28137117-5bd04396-6709-11e7-85f5-36446da5ca94.png)

Seems to be growing at a slow pace (roughly 30 plays per month), but this is very limited data.

**Comment by oliver-phet** [comment]
I don't know of anything else that needs done on this issue? @ariel-phet

**Comment by ariel-phet** [comment]
@oliver-phet I don't think anything else needs to be done with this issue. I think it answers the main question of what is the value of primers relative to the teacher guides. It seems comparing the two, the primers are certainly getting used at a rate that gives them comparable values to the guides. 

I will point @arouinfar and @amanda-phet at this issue so they are aware of the stats.
