### ISSUE TITLE
New screenshot for Plinko

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#876]
We need a new screenshot for Plinko now that the minimum number of rows is 1. All settings should be identical.

**Comment by phet-steele** [comment]
Looking at [responsible-dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md), @pixelzoom would you mind doing a release of plinko-probability with this new screenshot? The screenshot is both on master and 1.1, but I'm sure a quick maintenance release off 1.1 would be fine (with no testing).

**Comment by pixelzoom** [comment]
For future changes like this, the issue should live in plinks-probability.

**Comment by pixelzoom** [comment]
Moving this issue to https://github.com/phetsims/plinko-probability/issues/102.
