### ISSUE TITLE
Create a spot account for @mbarlow12

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#877]
It would be great if @mbarlow12 could deploy dev versions.  This issue will track progress for setting up an account on spot.

We sent OIT a request to do this on 7/19/17.

**Comment by jessegreenberg** [comment]
Spot account was created, OIT help number was forwarded to @mbarlow12 and he will contact to set up a password.

**Comment by mbarlow12** [comment]
I've received my updated PW from OIT. @jessegreenberg should we go over the deployment process sometime next week?

**Comment by jessegreenberg** [comment]
@mbarlow12 sounds great.  Since account has been set up, closing this issue and we can test it out on Friday.
