### ISSUE TITLE
Does this repo need a license?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#878]
From https://github.com/phetsims/tasks/issues/875

**Comment by samreid** [comment]
Scheduled for developer meeting to decide on license.

**Comment by pixelzoom** [comment]
Licensing is outside of my area.

**Comment by ariel-phet** [comment]
@samreid we store no code here, so a license does not exactly seem particularly meaninful.

However, the repo is public, I would treat it like "common code" repos if I had to give it a license.

**Comment by samreid** [comment]
@ariel-phet recommends MIT, I'll go for it.

**Comment by samreid** [comment]
Done, closing.
