### ISSUE TITLE
Atomic Pushers/Pullers for Coulomb's Law

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#879]
The Coulomb's Law sim will have an Atomic Scale screen, and if possible, we'd like to have a version of the pushers and pullers that appear to be made of atoms. While atomic pushers/pullers will be a bit whimsical, the goal here is to cue to the users that the sim is now at a very different scale.

@clmccutchan could you mock up what **one** of the figures would look like if they were to appear as though they were made of atoms? Modifying one of the pullers you created for https://github.com/phetsims/tasks/issues/834 be fine. We'd like to get a sense of what atomic pushers/pullers could look like before asking you to create sixty-some odd variants.

**Comment by clmccutchan** [comment]
@arouinfar I'll be back from vacation tomorrow morning and can mock this up then. Will that be ok?

**Comment by clmccutchan** [comment]
@arouinfar Here's a quick and incomplete draft of an atomic puller. Sorry I didn't get more of it done before you leave for vacation! I was trying to model it after a molecular building kit students would use.
![pullers_atomic_879](https://user-images.githubusercontent.com/25354670/29143290-cf8b9600-7d11-11e7-9922-3c2d2f46e605.png)

**Comment by arouinfar** [comment]
I really like the style @clmccutchan!! 

I think it would be good for @ariel-phet to also review before you go any further.

**Comment by ariel-phet** [comment]
Super cool @clmccutchan - Very "ball and stick" model. 

@arouinfar - We might want to use different colors (since blue and red in the sim are associated with positive and negative charges in the sim), but color is an easy change. But overall this seems like a good direction, and will be straightforward to make the versions in different states of pulling and pushing.

**Comment by clmccutchan** [comment]
Thanks, @ariel-phet!

@arouinfar I'll plan on finishing the draft of atomic human by Friday at the latest. It's probably wise to determine the colors of the atoms before I complete the whole series of illustrations for the pusher and puller.

**Comment by arouinfar** [comment]
@clmccutchan let's go with cyan for the head/hips, and yellow for the elbows/knees. The figure will be on a black background, so I think it would be a good idea to add a thin white stroke around the circles. Here's a rough mockup (please ignore the missing upper arm)
![image](https://user-images.githubusercontent.com/8419308/29334959-611b5804-81c6-11e7-89ca-5254783197ea.png)

We'll also want to make sure that the vertical distance between the feet and hands matches the artwork that's already in place. I'll email an updated .ai file to @clmccutchan.
![image](https://user-images.githubusercontent.com/8419308/29335028-8e9dea08-81c6-11e7-822e-02479c3a43a0.png)

**Comment by clmccutchan** [comment]
@arouinfar How does this look?
![pullers_atomic_879_081817](https://user-images.githubusercontent.com/25354670/29476264-72d503c2-8420-11e7-8923-9549d17f913f.png)

**Comment by arouinfar** [comment]
Looks pretty good @clmccutchan! A few suggestions...
* Use the blue (#6ACEF5) and yellow (#FEE105) from the PhET logo. (Your draft looked close to our logo colors, which think would look really nice here!)
* The arms/hands should be more overlapped, like the original pushers/pullers.

**Comment by clmccutchan** [comment]
will do, @arouinfar! I had pulled that other hand up just so it was more visible but will match the body positions in the updated .ai file you sent me.

**Comment by arouinfar** [comment]
Sounds great! Thanks @clmccutchan.

**Comment by arouinfar** [comment]
@clmccutchan just realized I didn't directly answer your question. Please go ahead and create the set of atomic pushers/pullers. We'll also need one figure that stands upright (see below) for when the force is zero.

![puller_1](https://user-images.githubusercontent.com/8419308/29633804-bf5a86c6-8804-11e7-9451-187afe5b2849.png)

**Comment by clmccutchan** [comment]
@arouinfar I'll have the pullers for you today and the pushers tomorrow!

**Comment by clmccutchan** [comment]
@arouinfar Here's a png of the standing atomic person and the last frame of the puller. I'll send you the .ai file for the puller via email.
![pullers_atomic_082817](https://user-images.githubusercontent.com/25354670/29833909-46de6ef6-8caa-11e7-9750-c2d4535fb4eb.png)
![pullers_atomic_stand_082817](https://user-images.githubusercontent.com/25354670/29833910-46f62afa-8caa-11e7-9ac0-6016e8d7a1d4.png)

**Comment by clmccutchan** [comment]
@arouinfar Here's the last frame of the pusher. I'll send you the .ai file via email.

![pushers_atomic_879-01](https://user-images.githubusercontent.com/25354670/29928774-f32bbce0-8e26-11e7-8733-b0d0a6c0aa9c.png)

**Comment by arouinfar** [comment]
@clmccutchan looking good so far! The pullers are all ready to go. Self-assigning to review/export the pullers.

**Comment by arouinfar** [comment]
The final assets have been delivered to devs, closing.
