### ISSUE TITLE
Research video editing software and port primer bumpers

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#882]
This task has two parts: 

1. Research video editing software to be used for creating video primers. Create a table with columns for software name, cost, licensing, platform(s), and any other relevant information. 

ideal features: 
- free or inexpensive (multiple licenses) 
- cross platform 
- easy to use 
- pretty basic features in terms of transitions, adding text, adding images
- white noise removal? 

platforms we know we want included in the table: Camtasia 2 (we currently have a license but it's an old version), Camtasia 3, iMovie, Final Cut. 

2. Once we select the platform we'd like to use for primers, create new bumpers in that program that have the separate video, music, audio, screenshot, and sim title components. 

(Not sure exactly how to explain this.. but we don't want an exported video file for bumpers because every sim needs to customize the screenshot, sim name, and recorder info. We also may need to edit bumpers down the road if we want to change the music, or the screenshot at the end when the website changes.)

**Comment by amanda-phet** [comment]
@arnabp can you confirm that you'll be able to work on this this week? I'd like part (1) to be done by Friday if possible.

**Comment by arnabp** [comment]
Yes, I can do this. I'll start working on it today.

Although from memory of past research into video editing software, none are as reliable as Final Cut or Premiere Pro. But I'll see what I can find!

**Comment by oliver-phet** [comment]
I just got an email from TechSmith and they are going to provide 5 licenses of the latest version of Camtasia (Mac or Win).

**Comment by arnabp** [comment]
- iMovie (**Free**): Fast, has most of the features we would require, might take some research to do some of the higher level functions (frame by frame editing, white noise removal, etc). Mac only.

- Camtasia (**Licenses Available**): Already in use, works with legacy projects. Not very optimized, can be slow to edit with and struggles to do higher level functions.

- Filmora (**$60 per license, not including school discount**): Clean and easy to user interface. Can handle some of the more difficult editing requirements without being over complicated.

- Final Cut Pro (**$300 per license**): Fastest editing software, extremely optimized. Can handle almost anything necessary. Mac only.

- Adobe Premiere Pro (**$15 per month per user**): Most powerful editing software available. Not as fast as Final Cut.

**Comment by oliver-phet** [comment]
Thanks, @arnabp. We may just stick with Camtasia for the time being since we have some new licenses.

**Comment by oliver-phet** [comment]
Also, I don't see a reason we couldn't use several editors... as long as we have the assets available for each format. For example, we could have the "bumpers" in Camtasia, Final Cut, Premiere, etc. There are several labs around campus that have Final Cut and Premiere installed for us to use.

**Comment by amanda-phet** [comment]
For primers, we need to stick with one video software. They change often enough that I wouldn't want to go around to all the formats and update them all. I agree with @oliver-phet that since we have licenses we should just continue to use it for the time being. However we don't have to use camtasia for *everything*, just looking for something stable and easy to use for primers. 

@arnabp thank you for looking into this and giving us some pros and cons about the different softwares.
