### ISSUE TITLE
Record Least-Squares Regression primer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#884]
Script shared with @CWilson4960. 

@CWilson4960 when you have a draft ready to review feel free to add it to the drive folder and ping me to let me know it's ready to review.

**Comment by CWilson4960** [comment]
@amanda-phet I just finished up a rough draft and it is uploaded. Let me know if there's any trouble looking at it.

**Comment by CWilson4960** [comment]
Rough draft 2 is uploaded.

**Comment by amanda-phet** [comment]
Ready to produce! Handing off to @CWilson4960 and @arnabp .

**Comment by CWilson4960** [comment]
@arnabp , [here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYcS12a28xWUQ4NkE) is the link, version 3 with my name on it is the one ready for editing.

**Comment by arnabp** [comment]
Edited and exported. Final video placed in the same folder. @amanda-phet please review and make sure everything looks okay.

**Comment by amanda-phet** [comment]
Awesome. 

One small change, the text on the first frame should say "Recorded by Clara Wilson with Amanda McGarry". That is our convention when someone wrote or assisted with script writing, and someone else recorded. 

Can you make that change, re-export, and replace the file in the folder? Once it is exported, let's have @CWilson4960 go through the steps to upload the file to Vimeo with the special PhET settings.

**Comment by arnabp** [comment]
Fixed, new version is uploaded.

**Comment by CWilson4960** [comment]
@amanda-phet The Least-Squares Regression primer is uploaded to the PhET website. Captions to follow this week

**Comment by CWilson4960** [comment]
@amanda-phet The captions are live. Should I close the issue?

**Comment by amanda-phet** [comment]
Just a few changes and then it will be ready:

(1) the script toward the end is supposed to say “correlation coefficient” not “correlational coefficient”, and even though you accidentally said correlational, the captioning should say the correct word, which is correlation.

(2) There are a couple places where the sentence is cut off at an odd time. At 0:32 I’d move “more” to the next chunk with “advanced students..” At 1:10 I’d move “line” to the next chunk with “modeling their data”, and “expanding” to the next chunk with “best-fit line”. This might be subjective though.. I'm not sure what the conventions are for captions, but it seems natural to me to not end a caption with a verb, and generally keep some phrases together. 

(3) The intro and outro need captions as well. I know there are some done in other sim primers, such as Arithmetic. Is it possible to re-use those?

**Comment by CWilson4960** [comment]
@amanda-phet I will see if I can reuse them. I will fix these tonight. Thanks

**Comment by amanda-phet** [comment]
Final video with all captions is up! This can be closed.
