### ISSUE TITLE
Record Molecules and Light Primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#885]
Reviewed the script on Drive with @CWilson4960.

@CWilson4960 once you have a draft ready for review, please upload it to the Drive folder, and I'll take a look. If you have any questions about the primer, I'd be happy to chat with you.

**Comment by CWilson4960** [comment]
@arouinfar. The draft file is uploaded to the drive folder. Thanks!

**Comment by CWilson4960** [comment]
@arouinfar The second draft file is uploaded to the drive folder. [Here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYZkRIWUh4SlRNbHM?ths=true) is the folder. Thanks!

**Comment by arouinfar** [comment]
v2 is ready for production @CWilson4960 @arnabp!

**Comment by CWilson4960** [comment]
@arnabp The cmproj file is [Here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYZkRIWUh4SlRNbHM) for the MOL primer.

**Comment by arnabp** [comment]
Exported final video. I'll upload my camtasia file when I figure out how to get cross-platform working. Final video placed in the same folder.

**Comment by CWilson4960** [comment]
@arouinfar Molecules and Light is uploaded to the PhET website. Captioning to follow this week.

**Comment by arouinfar** [comment]
Excellent! Thanks @CWilson4960 @arnabp. Once captioning is completed, you can close this issue.

**Comment by arouinfar** [comment]
On second thought, I should probably take a look at the captions once they're live. So reassign to me, and I'll let you know if anything needs tweaking.

**Comment by CWilson4960** [comment]
@amanda-phet listened to it and found some errors that I had missed. We are planning on taking it down and re-recording it. Its got some bad white noise which comes and goes, and some weird buzzing. Does that sound good @arouinfar ?

**Comment by CWilson4960** [comment]
v4 is uploaded to the [drive](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYZkRIWUh4SlRNbHM)

**Comment by CWilson4960** [comment]
Molecules and Light is captioned and uploaded to the PhET website. Should I go ahead and close the issue?

**Comment by arouinfar** [comment]
@CWilson4960 next time, please reassign the issue to me once the primer is uploaded and captioned. That way I'll do a final review of the live primer to make sure the captions look good, and then close the issue. 

Everything in MAL looked good, by the way. :)
