### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/tasks#886]
Test device:
MacBook Air (13-inch, Early 2015)

Operating System:
macOS Sierra 10.12.4

Browser:
Safari 10.1

Problem description:
There is no cake.

Steps to reproduce:
1. Open the sim.
2. There is no cake.

Screenshots:
![screen shot 2017-08-23 at 12 53 19 pm](https://user-images.githubusercontent.com/31285590/29633024-16868380-8802-11e7-9153-e1c1d71d282b.png)
There should be cake in this area.

For phetsims/QA/issues/43

Troubleshooting information (do not edit):
Name: ‪Atomic Interactions‬
URL: https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_en.html
Version: 1.0.3 2017-08-23 04:09:04 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
Language: en-US
Window: 1264x736
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.24.45)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"atomic-interactions":{"sha":"7b15018f","branch":"HEAD"},"axon":{"sha":"b4404f00","branch":"HEAD"},"babel":{"sha":"523383c4","branch":"master"},"brand":{"sha":"853b3b17","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"23b13772","branch":"HEAD"},"joist":{"sha":"e1fc3b06","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"nitroglycerin":{"sha":"ad3cb990","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"7bad0484","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"3a5aa6e8","branch":"HEAD"},"scenery-phet":{"sha":"9d87b624","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"states-of-matter":{"sha":"8ff9bed9","branch":"HEAD"},"sun":{"sha":"10af95af","branch":"HEAD"},"tandem":{"sha":"4a8edbc9","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@lmulhall-phet thanks for pointing this out....here you go:

![cake](https://user-images.githubusercontent.com/5863899/29633223-cb6996ac-8802-11e7-9e24-81e641864cf7.jpg)

@lmulhall-phet is this to your liking?

**Comment by lmulhall-phet** [comment]
Yes, this is to my liking.
