### ISSUE TITLE
Convert teacher tips files 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#887]
- [x] Play around with these two pages documents. See if you can find an easy way to "transfer" the styles from the function-builder-basics-guide-helvetica.pages doc to the function-builder-guide.pages doc. 
[teacher tips.zip](https://github.com/phetsims/tasks/files/1257777/teacher.tips.zip)

- [x] Go through each sim folder (PhET files > PhET Sim Design > Sim Name HTML5 folder) and download the current tips file. These might be .pages, .docx, or .pptx. Hopefully an editable one exists for each sim... if not, you might only have a .pdf to work with.

- [x] Make a google spreadsheet with all HTML5 sims listed to keep track of your progress. Start with columns for "downloaded (and file type?)", "updated" and a column for "uploaded". 

Wait before doing any actual updating, as we are still refining the exact style of the documents. The main component that is still not finalized is the header at the top.

**Comment by CWilson4960** [comment]
@amanda-phet The Acid Base Solutions Teacher Tips has been uploaded to the Updated drive folder.

**Comment by CWilson4960** [comment]
Area builder has as well.

**Comment by CWilson4960** [comment]
@amanda-phet The first batch of 21 teacher tips (not including Atomic Interactions, Forces and Motion: Basics, and Friction) is uploaded to the drive for you to review. 
https://drive.google.com/drive/u/1/folders/0B3l-M0dd38HNVWl1ZC1lR2hzdjg

**Comment by CWilson4960** [comment]
@amanda-phet The second batch of 22 tips is uploaded for review https://drive.google.com/drive/u/1/folders/0B3l-M0dd38HNVWl1ZC1lR2hzdjg

**Comment by CWilson4960** [comment]
All of the teacher tips have been redeployed. Closing.
