### ISSUE TITLE
Balloons for Balloons and Static Electricity

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#888]
In https://github.com/phetsims/balloons-and-static-electricity/issues/72, it was discovered that we don't have an .ai asset for the balloons in [Balloons and Static Electricity](https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html). 

@clmccutchan can you recreate these balloons (as closely as possible) in Illustrator? The string is drawn in code, so we'd just need the balloon itself.

![screen shot 2017-08-28 at 2 12 50 pm](https://user-images.githubusercontent.com/8419308/29791671-04159b1c-8bfb-11e7-9803-1515998e2e26.png)

The artwork for #879 is higher priority, so this can be done after the pusher/pullers are wrapped up.

**Comment by ariel-phet** [comment]
@arouinfar can you get @clmccutchan the current artwork for the balloons? (probably .png files) so we can match dimensions and such? My guess is it will be easiest if these are just "drop in" replacements

**Comment by arouinfar** [comment]
@clmccutchan here are the .png files currently being used in the sim. The images have some transparency so that the sweater is visible beneath them. Unfortunately, I don't know the precise opacity %, but please try to match as closely as possible.

[balloon-green.png](https://user-images.githubusercontent.com/8419308/29794566-b19679fa-8c05-11e7-95d6-cf25fb328c32.png)
[balloon-yellow.png](https://user-images.githubusercontent.com/8419308/29794567-b1a551d2-8c05-11e7-9938-425e7e4aec12.png)

**Comment by clmccutchan** [comment]
@arouinfar Here's a first draft of the balloons. I made them the same size as the reference pngs. I set the opacity at about 80%.
![balloons_green](https://user-images.githubusercontent.com/25354670/30234761-ab077916-94bd-11e7-9637-6282a7314d4f.png)
![balloons_yellow](https://user-images.githubusercontent.com/25354670/30234762-ab2b1d12-94bd-11e7-919a-c1c11fc449ff.png)

**Comment by arouinfar** [comment]
Those look spot-on @clmccutchan! Can you send me the .ai file?

**Comment by clmccutchan** [comment]
@arouinfar I just emailed you the .ai file.

**Comment by arouinfar** [comment]
Everything looks good @clmccutchan! The assets have been delivered to @jessegreenberg. Closing.
