### ISSUE TITLE
LOL sim preparation

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#890]
@kathy-phet said she'll request a designer to send metadata to LOL for 

Build an Atom
Projectile Motion
Pendulum Lab (when published) 

And I'm going to work on preparing these sims for LOL release:
Force and Motion: Basics
Energy Skate Park: Basics

**Comment by samreid** [comment]
Forces and Motion: Basics is being tracked in https://github.com/phetsims/forces-and-motion-basics/issues/235

**Comment by samreid** [comment]
Energy Skate Park: Basics is being tracked in https://github.com/phetsims/QA/issues/41

**Comment by phet-steele** [comment]
> @kathy-phet said she'll request a designer to send metadata to LOL for
> 
> Build an Atom
> Projectile Motion
> Pendulum Lab (when published)

Reopening for @kathy-phet to do this. It is evident this is still on her plate since https://github.com/phetsims/QA/issues/46#issuecomment-328160857 was still assigned to her to complete.

**Comment by arouinfar** [comment]
These sims were delivered to LoL in 2017, closing.
