### ISSUE TITLE
Record Function Builder primer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#891]
Script is written and ready to be reviewed by @CWilson4960 

Files located in this folder: 
https://drive.google.com/drive/folders/0B6CMwxdP0NGYMUpxOTVlbXE2ZFE

**Comment by CWilson4960** [comment]
@amanda-phet The first draft (script draft) of the Function Builder primer is uploaded, [here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYMUpxOTVlbXE2ZFE)

**Comment by CWilson4960** [comment]
@amanda-phet The second draft is uploaded for review, [here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYMUpxOTVlbXE2ZFE)

**Comment by amanda-phet** [comment]
Looks great! Feedback is detailed in slack.

**Comment by CWilson4960** [comment]
@amanda-phet The third draft is uploaded for review [here](https://drive.google.com/drive/u/1/folders/0B6CMwxdP0NGYMUpxOTVlbXE2ZFE)

**Comment by CWilson4960** [comment]
The Function Builder Primer is live with captions (or will be once it uploads) [here](https://phet.colorado.edu/en/simulation/function-builder)

**Comment by amanda-phet** [comment]
All looks good.
