### ISSUE TITLE
File Upload to Google Drive/mailing of hard drive

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#893]
I need someone to move the files from the hard drive sitting on my desk, and put them on Google drive (wherever the raw footage for videos go). This footage is from interviews with me, Esha, and Jesse from two years ago, which have been used for the NSF Video Showcase videos.

Once that's complete, the hard drive needs to be returned to Shawna. Email me and I'll send the address.

No particular urgency for this, but it would be good to get the hard drive back to Shawna soon-ish.

**Comment by ariel-phet** [comment]
@oliver-phet seems like something @arnabp could take care of pretty easily. Let me know if that won't work.

**Comment by oliver-phet** [comment]
@arnabp let's put this in the root of phet-storage.

**Comment by arnabp** [comment]
PhET Accessibility folder is now in the root of phet-storage.
