### ISSUE TITLE
Artwork for Equality Explorer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#894]
https://github.com/phetsims/equality-explorer/issues/6

@clmccutchan is creating a tiny dog, cat, and turtle for the fourth scene.

**Comment by clmccutchan** [comment]
@amanda-phet How do these look? I'm not entirely satisfied with the dog, but it's so tiny I'm not sure my dissatisfaction matters that much.

![basics-artwork-without-shadow_cat](https://user-images.githubusercontent.com/25354670/31282065-af8df7c8-aa6e-11e7-8bcd-59484f5c395d.png)
![basics-artwork-without-shadow_dog](https://user-images.githubusercontent.com/25354670/31282066-afaf0454-aa6e-11e7-84e7-60916e5e5d65.png)
![basics-artwork-without-shadow_turtle](https://user-images.githubusercontent.com/25354670/31282067-afb3d114-aa6e-11e7-8adc-80466b83b45a.png)

**Comment by amanda-phet** [comment]
In context: 
![screen shot 2017-10-06 at 10 14 29 am](https://user-images.githubusercontent.com/7852916/31287653-2e10f202-aa7f-11e7-8911-3973ec1732bf.png)

I think they really work! I agree, the dog could use something but I'm not sure what.. can you make it more of a "golden retriever" color? And maybe make the head a little rounder? not sure if that would actually be an improvement or not. 

For the cat, is it possible to show a little more definition in the body, perhaps using a dark gray somewhere? If not, all black is fine, it totally works.

**Comment by pixelzoom** [comment]
To my eye, the arc of the cat's tail conflicts with the '0's in equations - I would lose the long tail.  I also don't think the cat needs more detail.  Less detail is better for these icons, since they need to be rendered so small.

**Comment by clmccutchan** [comment]
@amanda-phet @pixelzoom I tweaked the horrible first draft of the dog and changed the cat's tail and adding just a bit of highlighting to the cat. What do you think now?

![basics-_cat](https://user-images.githubusercontent.com/25354670/31627237-c87b6dee-b269-11e7-95d4-c2c7e5028703.png)
![basics-_dog](https://user-images.githubusercontent.com/25354670/31627238-c8d66c80-b269-11e7-8392-59d898ae4ef3.png)

**Comment by amanda-phet** [comment]
I really like these! The white on the cat is nice so at a small size it is even more distinguishable from the other objects. And the dog looks great with the golden color. I'm really happy with these so unless @pixelzoom is concerned I'd like to try integrating them.

**Comment by pixelzoom** [comment]
@amanda-phet Proceed with integrating into .ai files. Let's see how they look in context.

**Comment by amanda-phet** [comment]
@clmccutchan One more request for the cat. I really like everything about it but @kathy-phet had a good suggestion to remove some of the detail in the white fur. Perhaps just a triangle patch for the chest and just a circle at the tail? Basically removing some of the furriness.

**Comment by clmccutchan** [comment]
@amanda-phet I've updated the .ai file and am emailing it to you.

**Comment by pixelzoom** [comment]
Did we reflect the dog and cat? (rotate horizontally)

**Comment by amanda-phet** [comment]
@pixelzoom yes I reflected them and am going to commit the updated .ai files now

**Comment by ariel-phet** [comment]
I am pretty sure all artwork has been made. Closing

**Comment by pixelzoom** [comment]
There may be artwork required from the screen icons.  But we'll deal with that in https://github.com/phetsims/equality-explorer/issues/14.
