### ISSUE TITLE
Sim runs and standards

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#901]
For the following list of eight sims, can someone list out:
- the specific middle school and/or high school NGSS standards addressed, and
- total sim runs for the last year.

Balancing Act
Balloons and Static Electricity
Energy Skate Park: Basics
Forces and Motion: Basics
Friction
Gravity Force Lab: Basics
John Travoltage
Plinko Probability

The standards can be found in the various standards documents uploaded alongside the teacher activities.

Updated to add deadline: I need this by end of day Monday.

**Comment by arouinfar** [comment]
@emily-phet I could not find relevant NGSS standards for Balancing Act and Plinko Probability, so I've provided Common Core math standards instead. @ariel-phet said he would provide the sim run stats, so unassigning myself.


**Balancing Act**
[CCSS.MATH.CONTENT.K.MD.A.2](http://www.corestandards.org/Math/Content/K/MD/A/2/)
[CCSS.MATH.CONTENT.4.OA.A.2](http://www.corestandards.org/Math/Content/4/OA/A/2/)
[CCSS.MATH.CONTENT.4.OA.A.3](http://www.corestandards.org/Math/Content/4/OA/A/3/)
[CCSS.MATH.CONTENT.6.EE.C.9](http://www.corestandards.org/Math/Content/6/EE/C/9/)
[CCSS.MATH.CONTENT.6.SP.B.5](http://www.corestandards.org/Math/Content/6/SP/B/5/)
[CCSS.MATH.CONTENT.7.RP.A.2](http://www.corestandards.org/Math/Content/7/RP/#CCSS.Math.Content.7.RP.A.2)
[CCSS.MATH.CONTENT.8.EE.B.5](http://www.corestandards.org/Math/Content/8/EE/B/5/)
[CCSS.MATH.CONTENT.8.F.A.3](http://www.corestandards.org/Math/Content/8/F/A/3/)
[CCSS.MATH.CONTENT.8.F.B.4](http://www.corestandards.org/Math/Content/8/F/B/4/)
[CCSS.MATH.CONTENT.8.F.B.5](http://www.corestandards.org/Math/Content/8/F/B/5/)
[CCSS.MATH.CONTENT.8.SP.A.1](http://www.corestandards.org/Math/Content/8/SP/A/1/)
[CCSS.MATH.CONTENT.8.SP.A.3](http://www.corestandards.org/Math/Content/8/SP/A/3/)
[CCSS.MATH.CONTENT.8.SP.A.4](http://www.corestandards.org/Math/Content/8/SP/A/4/)

**Balloons and Static Electricity**
[MS-PS2-3](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=150)
[HS-PS2-4](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=98)

**Energy Skate Park: Basics**
[MS-PS3-1](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=158)
[MS-PS3-2](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=160)
[MS-PS3-5](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=166)
[HS-PS3-1](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=105)
[HS-PS3-2](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=106)

**Forces and Motion: Basics**
[MS-PS2-2](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=149)
[HS-PS2-1](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=95)

**Friction**
[MS-ESS2-1](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=223)
[MS-ESS2-2](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=224)
[HS-ESS2-5](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=188)

**Gravity Force Lab: Basics**
[MS-PS2-4](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=151)
[MS-PS2-5](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=152)
[HS-PS2-4](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=98)

**John Travoltage**
[MS-PS2-5](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=152)
[HS-PS2-4](http://ngss.nsta.org/DisplayStandard.aspx?view=pe&id=98)

**Plinko Probability**
[CCSS.MATH.CONTENT.6.SP.A.2](http://www.corestandards.org/Math/Content/6/SP/A/2/)
[CCSS.MATH.CONTENT.6.SP.A.3](http://www.corestandards.org/Math/Content/6/SP/A/3/)
[CCSS.MATH.CONTENT.6.SP.B.4](http://www.corestandards.org/Math/Content/6/SP/B/4/)
[CCSS.MATH.CONTENT.6.SP.B.5](http://www.corestandards.org/Math/Content/6/SP/#CCSS.Math.Content.6.SP.B.5)
[CCSS.Math.MATH.CONTENT.7.SP.C.5](http://www.corestandards.org/Math/Content/7/SP/C/5/)
[CCSS.MATH.CONTENT.7.SP.C.6](http://www.corestandards.org/Math/Content/7/SP/C/5/)
[CCSS.MATH.CONTENT.HSS.ID.A.1](http://www.corestandards.org/Math/Content/HSS/ID/A/1/)
[CCSS.MATH.CONTENT.HSS.IC.A.2](http://www.corestandards.org/Math/Content/HSS/IC/A/2/)

**Comment by ariel-phet** [comment]
| Simulation  | Runs Oct 2016 - Oct 2017|
| :---------- | :------------- |  
| Balancing Act | 1,250,845 |
| Balloons and Static Electrcity | 1,147,656  |
| Energy Skate Park: Basics | 3,401,149 |
| Forces and Motion: Basics | 3,598,726 |
| Friction  | 230,249  | 
| Gravity Force Lab  | 936,715 | 
| John Travoltage  | 786,632  | 
| Plinko Probability  | 239,710  |

**Comment by emily-phet** [comment]
Thanks! This is perfect!
