### ISSUE TITLE
Craft email to Colorado teachers for "personal stories"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#903]
CU strategic relations would be interested to see if we can gather some leads on personal stories that might relate to PhET/CU especially in regards to areas outside of Boulder (rural CO and western slope).

They like the "end user" to be the focus and compelling personal stories.

We should look over the types of stories they have used:
https://www.colorado.edu/hometowns/

The main goal is to improve likability and perception of the university.

The idea would be to create an email to our Colorado teachers and see if we can find leads on these kinds of stories. Probably after thanksgiving would be a good time to craft the email

**Comment by amanda-phet** [comment]
or even during Thanksgiving when many teachers have a week off... right after Thanksgiving teachers will be pretty swamped with getting back in to things.

**Comment by ariel-phet** [comment]
@amanda-phet it is true...although with my travel I might not be able to help craft the email much!

**Comment by ariel-phet** [comment]
Not sure if this is going to happen or not. Closing and will make a separate issue if it comes up.
