### ISSUE TITLE
Urgent: Artwork needed for grant proposal (today!)

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#904]
I need some image of ESP:B for a grant proposal. The images will need to be very similar to those created in https://github.com/phetsims/tasks/issues/880 for BAA, but using ESP:B. Here's the images ones I need:
- Color Contrast (note, instructions on how to do this are in https://github.com/phetsims/tasks/issues/880)
- Zoom/Enlarge w/ Text-to-speech Highlight (zoomed in on bar chart, with one kinetic label highlighted in pink - see https://github.com/phetsims/tasks/issues/880)
- Sim options (same options as in https://github.com/phetsims/tasks/issues/880, just with ESPB in the background)

They do not the any bubble callouts - just the sim images. The sim should look close to this one.

<img width="302" alt="screen shot 2017-11-13 at 7 26 46 am" src="https://user-images.githubusercontent.com/5109055/32730358-0d72d10e-c844-11e7-9ce2-995056d08ba3.png">

**Comment by ariel-phet** [comment]
@arouinfar it looks like you did something similar in the past. Could you handle this today?

**Comment by arouinfar** [comment]
@emily-phet I have a question about the color contrast screenshot. In #880 you said:
> For the color contrast screenshot of the sim, I just take a screenshot, open in Preview, and adjust the color under Tools>Adjust Color...

Which parameters should I adjust? Contrast? Saturation?  How far up should I bump them? I don't know what the a11y invert color mode looks like, so I'm not sure what I'm trying to replicate.

Original:
<img width="500" alt="espb" src="https://user-images.githubusercontent.com/8419308/32740166-49b47a30-c85f-11e7-934f-764069c001b1.png">

Contrast ~50%:
<img width="500" alt="espb-high-contrast" src="https://user-images.githubusercontent.com/8419308/32740168-49c32a08-c85f-11e7-8317-66a02f2e9dde.png">

Max Contrast:
<img width="500" alt="espb-max-contrast" src="https://user-images.githubusercontent.com/8419308/32740231-8241c330-c85f-11e7-9ab3-3a2edd013777.png">

**Comment by arouinfar** [comment]
@emily-phet here are the other two screenshots. Please let me know if anything needs tweaking! 

Zoom/Enlarge with text-to-speech highlight:
![espb-zoom](https://user-images.githubusercontent.com/8419308/32741735-7ece15dc-c864-11e7-8fb8-153f42c49504.png)

Options:
![espb-options](https://user-images.githubusercontent.com/8419308/32741773-99967f58-c864-11e7-94c1-391c6733c313.png)

**Comment by emily-phet** [comment]
Thanks @arouinfar! A couple things:
- for the Zoom version, can edit the graph so that it's more compact (and can be "zoomed in" on further? For example, can you move, or even remove, the trash can, and lower the word "Energy" so that the actual graph can be much larger? Can you also highlight the word "Kinetic" by using a pink-ish background behind the whole word, rather than an outline? I think that's what we settled on for highlighting text in the BAA version.
- For the Options version, can you make the options dialog almost the size of the entire screen (or at least, a lot bigger than it is now)?

**Comment by arouinfar** [comment]
@emily-phet here are the updated screenshots. Can you also take a look at https://github.com/phetsims/tasks/issues/904#issuecomment-343999733? 

![espb-zoom-2](https://user-images.githubusercontent.com/8419308/32749258-0ba7ed0e-c87c-11e7-9c62-2dd63706a2e5.png)
![espb-options-2](https://user-images.githubusercontent.com/8419308/32749257-0b913442-c87c-11e7-9dbc-77c953d3f3a4.png)

**Comment by emily-phet** [comment]
Thanks! I have everything I need.
