### ISSUE TITLE
Move Vimeo teacher primers to YouTube.

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#906]
@ariel-phet brought it up that we are going to proceed with moving our Vimeo primers to YouTube to gain "easy" (our hands off) translation.

**Comment by oliver-phet** [comment]
Some updates from today:

- Youtube appears to NOT support downloading. If we proceed, we may need to host videos on both Youtube (for translated subtitles) _and_ Vimeo (for download).

- Investigation of the Youtube API will be done by @mattpen.

**Comment by mattpen** [comment]
Changes to the website and the Metadata API will be tracked here: https://github.com/phetsims/website/issues/660

**Comment by oliver-phet** [comment]
Duplicate of https://github.com/phetsims/website/issues/660. Closing.
