### ISSUE TITLE
Toolbox is one word

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#909]
While working on CapacitorLabBasics, I noticed that we sometimes use `toolbox` and sometimes use `toolBox`.  This disparity can potentially lead to incorrect variable, type or tandem names.  I checked the internet to see which is correct and it seems that "toolbox" gets 23,100,000 hits whereas "tool box" gets 16,700,000 hits.  Most of the dictionaries vote for "toolbox", so perhaps we should standardize on that.  Can a lint rule help us here?

**Comment by samreid** [comment]
Note we should be consistent about "toolbox" vs "tool box" in comments, but it seems more important to be consistent about "toolbox" vs "toolBox" in code.

**Comment by samreid** [comment]
As for our own code, we have around 600 occurrences of `oolbox` and around 60 occurrences of `oolBox`

**Comment by samreid** [comment]
I changed tool box => toolbox in several files (code only, not comments yet), and ran a full fuzz test and didn't see any issues.  I'll commit, but there's a chance that the case-renamings will cause problems on mac or win.  I'll check with someone after commit.

**Comment by samreid** [comment]
I messaged the developer channel on slack:

> chipper 2.0 has a new lint rule to prevent using the word toolBox (with uppercase B), see https://github.com/phetsims/tasks/issues/909 for details.

**Comment by samreid** [comment]
Should we add lint rules to prohibit "tool box" in comments?

**Comment by samreid** [comment]
I manually changed tool box => toolbox in comments and docs.  No lint rule yet, and technically we may not need one since all APIs are derived from code/strings.  Closing for now.

**Comment by samreid** [comment]
Before closing, I should make sure someone with Windows can pull the filename casing changes without a hassle.  @jessegreenberg can you please pull-all and see if you have any problems, say with `BiomoleculeToolboxNode.js` which had a case-only renaming?

**Comment by jessegreenberg** [comment]
I was able to pull this with Windows, all looks good here. Closing.
