### ISSUE TITLE
Checkbox is one word

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#910]
Similar to #909 it seems we should make checkbox be one word and avoid "checkBox" or "check box".

Having a uniform custom will make it easier to avoid casing mismatch bugs, and will help us keep a consistent API for sim development and for PhET-iO clients.

**Comment by samreid** [comment]
Google votes 9,020,000 votes for "check box" and 25,300,000 votes for "checkbox".

**Comment by samreid** [comment]
Our codebase has 1176 occurrences of `heckBox` and 603 occurrences of `heckbox` and 137 occurrences of `heck box`.  So it seems we have been inclined to separate that into two words.  I'll search further for ground truth.

**Comment by samreid** [comment]
Even wikipedia uses both forms in the 2nd paragraph:

![image](https://user-images.githubusercontent.com/679486/34850723-53790596-f6e4-11e7-88d9-0a634aab5fc2.png)

though checkbox appears 27 times on that page and "check box" appears 4 times.

**Comment by samreid** [comment]
On MDN https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement "checkbox" appears 7 times and "check box" appears 0 times.

Likewise the spec refers to checkbox (17 times) and never "check box".  Note these are for the HTML element not the scenery component, but it seems we should follow the same logic.  

I'm inclined to go with "checkbox".  I'll add lint rules and look at updating these.

**Comment by samreid** [comment]
I noticed that @pixelzoom used "Check box" and CheckBox in sun--it would be good to get him to sign off before we start making changes.  @pixelzoom can you please review this issue and comment?

**Comment by pixelzoom** [comment]
I'm fine with whichever you choose. Is this and #909 primarily motivated by consistency of phetioIDs?

**Comment by pixelzoom** [comment]
Btw... I've used "check box" mainly for consistency with the UI toolkits I've used in the past.  E.g. JCheckBox (Java Swing), QCheckBox (Qt), CheckBox (X/Motif), ...

**Comment by samreid** [comment]
This issue was discovered while working on making `phetioID`s consistent, but I would consider it nearly as important to have a consistent API for our sim development (to avoid case-related `undefined` bugs).

It seems odd because Java has `java.awt.Checkbox` but `javax.swing.JCheckBox`.  Why did they make this change?

Iterating through top hits in google search for "checkbox API":
* Android has `android.widget.CheckBox`
* Angular (also from Google) uses `Angular Material checkbox`
* Ionic uses "checkbox" https://ionicframework.com/docs/api/components/checkbox/Checkbox/
* Drupal uses Checkbox
* .NET uses CheckBox
* Facebook uses Checkbox

I'm still leaning toward the one-word solution.  I'll add a lint rule and start converting usages.

**Comment by samreid** [comment]
After adding this lint rule, lint-everything reports:

> ✖ 1353 problems (1353 errors, 0 warnings)

This may take some time unless we can take error-free shortcuts.

**Comment by samreid** [comment]
I changed checkbox to one word in the preceding commits.  Aqua is passing and lint (with new rule) is passing.  I also tested an instance proxies wrapper + launch and it worked OK.  Leaving open until we find out if Windows handles case changes OK.

**Comment by jessegreenberg** [comment]
I was able to pull changes on my Windows machine, thanks @samreid. Closing this isssue.
