### ISSUE TITLE
Resubmit all Spanish HTML5 sim translations

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#911]
Task from https://github.com/phetsims/chipper/issues/563#issuecomment-358757182

@DianaTavares Can you please resubmit your translations (for all HTML5 sims)? This will cause a sim rebuild using a new build process.

**Comment by oliver-phet** [comment]
@DianaTavares please comment in this issue once all sims have been resubmitted. Thank you!

**Comment by DianaTavares** [comment]
It's ready! The Spanish and MX translations

**Comment by oliver-phet** [comment]
Thanks @DianaTavares, closing for now!
