### ISSUE TITLE
Flyers for MIT Event - need by EOD 1/26

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#912]
Just a heads up - I need two flyers created (or adapted from prior flyers) to send to MIT folks for their booth. 

Both flyers would be focused on providing information about accessibilty work. 
- One would be for a researcher or more technical audience (research questions and technical infrastructure). 
- The other would be for a practitioner audience (what features we're developing, what's available right now, and what's coming soon)

I can provide more details tomorrow.

**Comment by ariel-phet** [comment]
@emily-phet do you have a previous flyer to work off? Do you have the content figured out?

**Comment by ariel-phet** [comment]
@oliver-phet said he could help out with this

**Comment by emily-phet** [comment]
@oliver-phet we updated some flyers for accessibility for the Nov 8th event at NSF. I can find no files on this (on Google drive, in my email, in a previous Github issue). Crazy. Maybe we discussed on slack but search history won't let us go back that far? 

@phet-steele printed them and shipped them to NSF, so he might remember something. 

My hope is to adapt these.

**Comment by oliver-phet** [comment]
@emily-phet is this the flyer you'd like to work off? https://drive.google.com/open?id=0B6CMwxdP0NGYLUwtSWRKek9pZTA

**Comment by emily-phet** [comment]
@oliver-phet - there is a version of this flyer that has images of individual sims listing out the individual accessibilty features (like the front of the general phet flyer). I can't find it - I think Slack has eaten it and I can't remember who worked on (maybe @arouinfar?). If this file could be found, it would be helpful, but if not that's ok.

Turns out, they need the files for the flyers asap if they're going to print them themselves. So here's what I need by noon today:

- [ ] The latest and greatest PhET general flyer (the two-page one that has sim screenshots listing ways to use the sims on the front, and a screenshot of the webpage with callout bubbles on the back)

- [ ] Attached powerpoint needs higher resolution images of john travoltage - for some reason they're really blurry from my computer.
[a11y-example.pptx](https://github.com/phetsims/tasks/files/1664405/a11y-example.pptx)

**Comment by oliver-phet** [comment]
@emily-phet I'll upload the general flyer and powerpoint to this folder: https://drive.google.com/open?id=1o3r9Fznt_mJAST7wQkzfRtQxMsrXfdfK

@arouinfar can you try to track down the accessibility flyer? We've both looked through drive, but haven't had luck yet.

**Comment by oliver-phet** [comment]
@emily-phet the John Travoltage screenshot looks very crisp on my Mac. I turned off picture compression and re-saved the .pptx -- can you try opening to see if it is resolved? The image is very blurry if I try to export as a .pdf, however. 
I can try exporting on a Windows machine this morning, too.

**Comment by arouinfar** [comment]
@emily-phet @oliver-phet I tracked down the accessibility flyer in the FETC folder:
https://drive.google.com/drive/folders/0B6CMwxdP0NGYNUlYNG9RNWc5Z2M

**Comment by oliver-phet** [comment]
@emily-phet I had to recreate the .ppt in .ai and I exported it as a .pdf
The latest general flyer is also uploaded.

We're still looking for the accessibility flyer you are describing.

Here's the folder: https://drive.google.com/open?id=1o3r9Fznt_mJAST7wQkzfRtQxMsrXfdfK

**Comment by arouinfar** [comment]
@oliver-phet pointed out that I linked to the same flyer as in https://github.com/phetsims/tasks/issues/912#issuecomment-360206815. 

@emily-phet could you be thinking of the work I did for ESPB in #904 or BAA in #880?

**Comment by emily-phet** [comment]
@oliver-phet @arouinfar Looking at this now. From the comments I think I have everything I need. I'll just double check. I'll close this in a moment if all is good.
