### ISSUE TITLE
Small edit to Camtasia (For Mac) or MP4 files - need by EOD Feb. 1

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#913]
Using Camtasia, I created two video files describing how to make accessible pdf files and word files. Since then, Word for Mac has changed, and I need these videos to remove any mention of Word for Mac removed.

I tried to do this myself, but cannot get Camtasia2 (on Mac) to remain open for more than 15 seconds or so. This could be an issue with my computer - it's old and quirky - or it could be that Camtasia2 is too out of date. PhET does not have licenses for Camtasia3, and my trial has run out, so I haven't tried it. 

For each of the two items below - 
Please try to open the *.cmproj files using Camtasia (on a Mac). If you can get it to stay open, please remove the section mentioned below, and re-export the file as an MP4 file of moderate quality (for streaming). 
If that doesn't work, please edit the MP4 file some other way to remove the section listed below. 
Try to have the resulting video feel as seamless as possible, but there will likely be some artifact of removing sections and that's ok.

Files are on Google Drive in PhET Accessibility/Inclusive Design.../Week 2

- Week2 - Video 3 (Week2-Video4.mp4 and Week2-video4.cmproj)
Remove 5:41-5:42 - where I say "not Word for Mac"

- Week 2 - Video 4 (Week2-Video4.mp4 and Week2-video4.cmproj)
Remove 4:13-4:44 - the section where I talk about not being able to generate tagged pdf files from Word for Mac

**Comment by ariel-phet** [comment]
Sounds like @arnabp can handle this task.

**Comment by arnabp** [comment]
Can I get write permission for the necessary folders so I can add the new versions?

**Comment by emily-phet** [comment]
@arnabp I didn't realize it didn't already have write privileges. Sorry about that. Should be fixed now. Let me know if it's not.

**Comment by arnabp** [comment]
All good now! I've uploaded Week2-Video4-v2.mp4 and Week2-Video3-v3.mp4 to their respective folders and updated both cmproj files. I did this on Camtasia 2 so it doesn't seem to be a compatibility issue.

**Comment by emily-phet** [comment]
These look really great! Very smooth transitions! Thanks very much @arnabp
