### ISSUE TITLE
Draft of PDOM Content for Rutherford Scattering (e.g., labels)

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#914]
@ariel-phet Please draft label, help, and static description content for this sim's PDOM.

I have created an outline for you to complete in this [a11y design doc](https://docs.google.com/document/d/1PxMAm5qjbYn_F8Buo_CH5cZ-Xb6D4ARjrAt3NAc5Kms/edit?usp=sharing). The section to be completed has the heading "Headings, Labels, and Help Text". Text in blue is for you to consider and edit. Red are notes from me, and black is content that I anticipate does not need to be changed.

In case it is helpful, here is the sim with keyboard navigation and the a11y view: 

- Sim:
https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.3/phet/rutherford-scattering_en_phet.html?accessibility
- a11y view: 
https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.3/phet/rutherford-scattering_a11y_view.html

If you have a chance to try drafting the content prior to tomorrow's 10am meeting, that would be ideal. We won't be able to focus on Plinko Probability as anticipated, so this would be a good sim to swap in for discussion.

**Comment by ariel-phet** [comment]
moved to https://github.com/phetsims/rutherford-scattering/issues/138 since this issue belongs in the sim repo not in tasks
