### ISSUE TITLE
Updated Artwork for Publication - need by end of day March 1st

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#920]
From a prior issue Dave worked on a diagram of the PDOM for a publication. That publication was accepted, though we need to update the PDOM figure prior to publication. 

@terracoda is working on a mockup of the needed changes, and will upload those tomorrow. 

Can someone be assigned to this - who can have a quick meeting with @terracoda Wednesday to iterate on some of the changes?

**Comment by ariel-phet** [comment]
@DianaTavares I think you can handle these changes, they should be pretty simple.

**Comment by DianaTavares** [comment]
It's a pleasure to work with @terracoda again :D 
I am free any time Wednesday for the meeting

**Comment by terracoda** [comment]
@DianaTavares, agreed. This one should be easier than the last one. 

This is the figure that we need to update.
![screen shot 2018-02-27 at 19 49 31](https://user-images.githubusercontent.com/1902116/36760950-6363a0f0-1bf7-11e8-8b05-6f2ffc1dd34c.png)

Instead of showing two uncharged balloons, we want it to represent a single negatively charged balloon against the wall.

The upper Tree Diagram should contain boxes with:
                Play Area
             /                  \
Yellow Balloon        Wall
/    /   |  \                 /  /   \  \
charges (not sure how many)

Then little screen shot of charged yellow balloon against the wall.
<img width="314" alt="screen shot 2018-02-27 at 19 58 59" src="https://user-images.githubusercontent.com/1902116/36761240-bb20d24e-1bf8-11e8-9b1e-57b7a282d6c5.png">

Then the HTML box will show the following code snippet:
```html
<h2>Play Area</h2>

<h3>Yellow Balloon</h3>
<p>At wall. Has negative net charge, several more negative charges than positive charges. Look for grab button to play.</p>
<button>Grab Yellow Balloon</button

<h3>Wall</h3>
<p>At right edge of Play Area. Has zero net charge, many pairs of positive and negative charges. Negative charges in wall move away from Yellow Balloo a lot.</p>
```

**Comment by DianaTavares** [comment]
What size should the image be?

**Comment by terracoda** [comment]
@DianaTavares, the balloon in the little screenshot could contain fewer negative charges, if need be. And if so, the HTML content would need to change to, like this:
<img width="297" alt="screen shot 2018-02-27 at 22 31 56" src="https://user-images.githubusercontent.com/1902116/36765980-5fc62384-1c0e-11e8-97df-60eebdb38b43.png">
HTML
``` html
<h2>Play Area</h2>
<h3>Yellow Balloon</h3>
<p>At wall. Has negative net charge, a few more negative charges than positive charges. Look for grab button to play.</p>
<button>Grab Yellow Balloon</button>
<h3>Wall</h3>
<p>At right edge of Play Area. Has zero net charge, many pairs of positive and negative charges. Negative charges in wall move away from Yellow Balloon a little bit.</p>
```

**Comment by terracoda** [comment]
@DianaTavares, I can meet sometime after 20 am mountain time.

**Comment by terracoda** [comment]
Great question. No wider than the column. we have some flexibility in height. I'll have to check the column. It might be the same width as the last one. I need to double check.

**Comment by terracoda** [comment]
@DianaTavares, the template says that the text columns are 8.45 cm (3.33") with a .83 cm
(.33") gutter. 

So, the image should be no more than 3 inches wide, maybe no more than 3.33 inches. Does that make sense?

**Comment by terracoda** [comment]
You should have access to the original image file. Dave Underwoord made it. I do not have access to it.

**Comment by emily-phet** [comment]
The file should probably be located in the artwork folder on google drive - everyone should have access. If it’s not there, please email Dave directly to track them down. 
If you’re not able to get access quickly, it’ll probably easier to just start from scratch. The lowers portion of the figure will be re-done anyway, so it’s only the upper boxes that would be duplicate work.

**Comment by DianaTavares** [comment]
I already start the work and I have the boxes, then I don't need the file. Thanks for the size picture, no more that 3",I have it.

**Comment by DianaTavares** [comment]
it's ready

![balloonwall](https://user-images.githubusercontent.com/26031501/36810925-68484250-1c89-11e8-8c06-ba9269a39fdd.jpg)

**Comment by terracoda** [comment]
@DianaTavares thanks for your work on this. All files are uploaded to google drive. I am closing this issue.
