### ISSUE TITLE
Is canvasBounds required?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#922]
In https://github.com/phetsims/tasks/issues/663#issuecomment-370853957 I noted 5 occurrences of:

```js
assert && assert( options && options.hasOwnProperty( 'canvasBounds' ), 'No canvasBounds specified.' );
```

It seems these were mainly introduced by Schmitz.  Are they necessary?  Is canvasBounds optional or required?  What happens if it is not passed in?   Should there be an assertion in CanvasNode?  I suspect @jonathanolson will be able to answer these questions most efficiently.

**Comment by jonathanolson** [comment]
The CanvasNode doesn't care about canvasBounds until it needs to be rendered. (it's required for it to be displayed, but not required for its construction).

**Comment by samreid** [comment]
It seems we should remove the assertion.

**Comment by samreid** [comment]
@jonathanolson just to clarify, should we remove the 5 assertions mentioned in the issue description?

**Comment by jonathanolson** [comment]
> @jonathanolson just to clarify, should we remove the 5 assertions mentioned in the issue description?

Sounds fine in general, but if they always need `canvasBounds` up-front (and will never change), an assertion at the start sounds fine.

**Comment by samreid** [comment]
@jonathanolson said it's OK to keep these assertions where we know the `canvasBounds` is not set elsewhere.
