### ISSUE TITLE
CoSN conference materials

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#924]
@oliver-phet here is what I am thinking I should have for the CoSN conference pod

- [x] some app fliers definitely (200?)
- [x] some general fliers (maybe?)
- [x] PhET general business cards (2 packs maybe)
- [x] Business card holder/display
- [x] iPad Air with app loaded
- [ ] Perhaps some stickers

Any thoughts? probably easiest for me to grab this stuff Thursday, but Friday would be fine too.

**Comment by oliver-phet** [comment]
@ariel-phet Everything checked above has been left in @phet-steele's office. He'll get the iPad ready.

**Comment by ariel-phet** [comment]
Got what I needed. Closing.
