### ISSUE TITLE
Should we be consistent about using “chart” vs “graph” in our user interface text?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#927]
From Slack:

Should we be consistent about using “chart” vs “graph” in our user interface text? I see:
Masses and Springs “Energy Graph”
Acid base Solutions “Graph”
Energy Skate Park: “Bar Graph”
Hookes Law: “Bar Graph”
Pendulum Lab: “Energy Graph”
Neuron: “Potential Chart”
Energy Skate Park: “Pie Chart”
And Wave Interference has “Graph” in the mock-up

Steele Dalton [10:56 AM]
https://english.stackexchange.com/questions/43027/whats-the-difference-between-a-graph-a-chart-and-a-plot/272682

Chris Malley [11:03 AM]
If the subject-matter experts aren’t concerned about (and haven’t noticed) the inconsistency, then perhaps we shouldn’t spend time on it.  Or pose the question to them to see if they think it’s important.
You can call it chart or graph in the code, and I’ll know what you’re referring to.

So my recommendation is to create a general issue, assign it to Ariel, and let subject-matter experts decide whether they want to go though sims and standardize (user-visible text). (edited)

**Comment by samreid** [comment]
@amanda-phet said:

> These aren’t my sims, but I would say (1) it’s important to title your graph, so the Acid Base Solutions title is a little lackluster, and (2) Pie charts are not usually called pie graphs, so chart is appropriate. Neuron should probably be renamed Potential Graph.
> 
> ESP and Hooke’s law could also use more specific titles, actually

**Comment by pixelzoom** [comment]
If there are any sim-specific changes to be made, please create sim-specific issues.

**Comment by ariel-phet** [comment]
Seems like a good topic to bring up when @kathy-phet is available since she will have more historical context. I will plan on bringing up in design meeting sometime in April, but definitely not a pressing issue.

**Comment by emily-phet** [comment]
My 2 cents - just seems like we should be consistent for similar looking representations (e.g., pie chart looking representations are all called 'pie charts', and things that look like an x and y-axis grid-like things are called 'graphs'). If there are discipline-specific reasons for calling a representation something different, that's fine though (like - the grid/square representation in Area Model sims I believe are called 'area models', and not anything with the word 'grid' in it).

**Comment by ariel-phet** [comment]
We agree with @emily-phet suggestion for internal consistency, but right now within sim usage all the above make sense. Closing
