### ISSUE TITLE
Proliferation of Properties named `activeProperty`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#929]
From https://github.com/phetsims/joist/issues/479, I'm not sure that this is even an issue.

I wonder if having so many different usages for the term activeProperty is troublesome. I think of it as a code smell, as it makes for many false positives when searching for it across the project, but I am curious about how other devs feel about this. Currently I count 6 `activeProperty = new` declarations throughout the codebase.

To me, going forward, we could go with any of the following solutions:
(a) business as normal, use that name all you want
(b) decide not to make new Properties called `activeProperty`
(c) retroactively fix the 4 or 5 (because screen.activeProperty is currently being renamed) other usages that overload `Sim.activeProperty`.

Even if we decide to go all out and fix usages, this doesn't feel like a high priority to me. Marking for dev meeting to discuss (probably briefly).

**Comment by pixelzoom** [comment]
I see no problem with naming something `activeProperty`.  As with any other Property or property, the name is disambiguated by the context.  E.g. `Sim.activeProperty` tells me that the Sim is active; `Screen.activeProperty` tells me that the Screen is active.  If there are some `activeProperty` names that are unclear, that's a different problem.

**Comment by pixelzoom** [comment]
As an analogy...  I see 29 occurrences of `visibleProperty = new`, 35 occurrences of `enabledProperty = new`.   Why would `activeProperty` be treated differently?

**Comment by zepumph** [comment]
It wouldn't be treated differently in my book, I just didn't notice the other names. If we don't think that it is beneficial to rename these then I'm fine with that. I have found that it makes it hard to find all usages without getting false positives, but no matter it isn't a large problem by any means.

**Comment by jessegreenberg** [comment]
I agree with https://github.com/phetsims/tasks/issues/929#issuecomment-380605895. Actually, I think it could be more confusing for Sim and Screen to both have an axon Property that indicates whether or not they are "active", but have them named different things.

**Comment by samreid** [comment]
@zepumph maybe instead we should make a change to the studio so that if it detects a name clash, then it will get include the preceding part of the PhET-iO ID (before the last dot) to disambiguate.

**Comment by zepumph** [comment]
I think we have heard a consensus, and I have also been convinced (3 to 0). Closing. We will leave these named the same.
