### ISSUE TITLE
Decide on scope for constants

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#931]
From CalculationNode.js for Area Model review https://github.com/phetsims/area-model-common/issues/99

```js
    // REVIEW: I typically move these out to // constants and uppercase them.
    // REVIEW*: Since they are locally used (not across the file), it seems nicer to have next to the one spot in code
    // REVIEW*: that uses it. Maybe good to discuss at a dev meeting?
    // REVIEW: Yes, I'd like to know what the group consensus is, because it will change how I proceed in my sims.
    var arrowSize = 18;
    var arrowTouchDilation = 8;
    var previousShape = new Shape().moveTo( 0, 0 )
      .lineTo( arrowSize, 0 )
      .lineTo( arrowSize / 2, -arrowSize * 0.8 )
      .close();
```

**Comment by zepumph** [comment]
If CalculationNode.js was 2000 lines of code, I may agree with @jonathanolson, but since it is barely 200, I think I agree that uppercase and in the `// constants` section is a bit cleaner for an outside coder to come across.

**Comment by pixelzoom** [comment]
There's nothing preventing you from using uppercase for constants in local scope.  Uppercase is not reserved for the `// constants` section.

**Comment by jonathanolson** [comment]
> There's nothing preventing you from using uppercase for constants in local scope. Uppercase is not reserved for the // constants section.

Agreed. When we do es6+, this would be nice:
```js
const arrowSize = 18;
const arrowTouchDilation = 8;
const previousShape = new Shape().moveTo( 0, 0 )
  .lineTo( arrowSize, 0 )
  .lineTo( arrowSize / 2, -arrowSize * 0.8 )
  .close();
```

and things like this I believe are harder to read:
```js
var ARROW_SIZE = 18;
var ARROW_TOUCH_DILATION = 8;
var PREVIOUS_SHAPE = new Shape().moveTo( 0, 0 )
  .lineTo( ARROW_SIZE, 0 )
  .lineTo( ARROW_SIZE / 2, -ARROW_SIZE * 0.8 )
  .close();
```

furthermore, say we do the above usage, but then run into a case where we want the arrow size to be some that is NOT a constant (say, depends on options). Then we need to take the chain of everything that "was" a constant and rename it so it doesn't look like a constant?

[Google's style guide](https://google.github.io/styleguide/jsguide.html#naming-constant-names) likes module-local or exported constants upper-case (but I don't see any mention of it applying to local constants), and [Airbnb's guide](https://github.com/airbnb/javascript#naming--uppercase) says only exported constants should be upper-case.

So I generally would prefer we stick with not upper-casing local constants, but that we do upper-case module-local (e.g. declared in the `// constants` section) constants, or constants statically declared on a type.

**Comment by samreid** [comment]
Module level constants are for things used throughout a file, or things that may need to be tweaked in that file.  OK to have local variables that are used in localized spots.
