### ISSUE TITLE
Create a reverse polyfill to facilitate cross-platform compatibility

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#932]
From slack:

> Hey guys I have a crazy idea.  Anything we want to blacklist since we know it is unsupported on some platform (I’m looking at you IE11), we do a “blacklist polyfill”, where we make it fail on every platform.  Like `BlacklistPolyfill(){Array.prototype.find = function(){throw new Error('…')};}`
> 
> Jonathan Olson [4:50 PM]
> Presumably only if assertions are enabled?
> 
> Sam Reid [4:50 PM]
> good point!
> 
> Jonathan Olson [4:50 PM]
> It’s also likely to break jQuery/lodash
> 
> Sam Reid [4:50 PM]
> why?  Maybe we could `delete Array.prototype.find`?
> 
> Jonathan Olson [4:51 PM]
> Depends on their potential feature detection.
> Just saying, any third party library we are using (now or in the future) could break with those changes, so it’s a tradeoff
> 
> Sam Reid [4:51 PM]
> true

A lint rule would be nice but cannot cover all bases because it doesn't know the runtime types.

This issue is to decide if we want to investigate something along these lines.

**Comment by samreid** [comment]
From slack:

Chris Malley [1:01 PM]
Why is the reverse polyfill needed if we have a lint rule?


Sam Reid [1:02 PM]
Some cases cannot use lint rule, such as the first example in #932
Generally, it is OK to call someArgument.find(…), but we have to know the runtime type of someArgument to know if it is illegal.
Lint does not know runtime types.

Chris Malley [1:04 PM]
reverse polyfill just sounds like it may create more problems than it solves.

Sam Reid [1:05 PM]
maybe!

John Blanco [1:10 PM]
+1 for having a lint rule and avoiding reverse polyfill if possible.

**Comment by zepumph** [comment]
I am unsure that we need to devote time to the reverse polyfill. How often does this bite us?

**Comment by samreid** [comment]
Maybe we should focus on lint rules, including special cases so that _.find() is OK but somethingElse.find() is not OK?

> I am unsure that we need to devote time to the reverse polyfill. How often does this bite us?

Initial development of the polyfill would be quick to make--the main time cost will be handling corner cases--say if one browser throws an error when we change Array prototype or such.

> How often does this bite us?

I'm guessing maybe 30% of RC versions have a problem like this, on the other hand, it is not too difficult to solve when it comes up. (But we rely on manual QA testing for finding the problems).

**Comment by jonathanolson** [comment]
I wouldn't mind if there was a custom query parameter that added the "polyfill" (if it's workable and doesn't cause problems with ANY of the libraries we use). That could be used with CT.

However I've said before we should have various different platforms/browsers testing for CT, so all of these cases are things that should be caught almost immediately by seeing CT go red (right?)

**Comment by samreid** [comment]
@ariel-phet suggested working on this since it may be quick.  Investigating usages of Array.prototype.find, I used this regular expression: `[a-zA-Z0-9]\.find\(` and it revealed code in fractions-common/js/building/view/ShapeGroupNode.js that would fail on IE.  Also, there are several places in perennial that are using Array.prototype.find acceptably, because we control those environments.  For those cases, do we want to use `// eslint-disable-line`?  I also noticed that babel may have a way to polyfill Array.prototype.find anyways? See https://stackoverflow.com/questions/32401513/array-find-doesnt-work-with-babel and https://github.com/babel/babel/issues/892.  @jonathanolson are we using those polyfills with our babel?

**Comment by jonathanolson** [comment]
> and it revealed code in fractions-common/js/building/view/ShapeGroupNode.js that would fail on IE

That's an ObservableArray, which implements find(), so that should work, right?

> @jonathanolson are we using those polyfills with our babel?

Nope, we aren't including the babel-polyfill.

**Comment by samreid** [comment]
> That's an ObservableArray, which implements find(), so that should work, right?

My apologies, you are right.  Based on the considerations mentioned above, a static lint-based check for this seems like it won't work, unless we have a lot of `// eslint-disable` directives scattered around.  Not sure if it is worth the effort.  If we are conscientious about testing on IE, we will catch the problems there and can patch with similar SHAs (without a lot of effort).  Or should we add code review steps anyways, just in case?

**Comment by jonathanolson** [comment]
I'm not sure what's best, but I have no objections to adding a code review step that lists the most common "offenders". Either way.

**Comment by samreid** [comment]
I added to the code review, please review.  OK to close if it seems good to you.

**Comment by jonathanolson** [comment]
Looks good, thanks!
