### ISSUE TITLE
Replace legacy sim footage with HTML5 footage

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#933]
The Brief Intro to PhET and What is PhET videos have a lot of footage of sims that have been ported, so @CWilson4960 is replacing that footage with newer sim footage. We don't have editable video files so we can't make any other changes at this time, but this is still a huge improvement. 

1. @CWilson4960 will finish up final edits (just one left) 
2. We need to upload the videos to our youtube channel 
3. We need @mattpen to replace the video links on our website with the new ones that will be created in step 2 above.

**Comment by CWilson4960** [comment]
Both "A Brief Introduction to PhET" and "What is PhET?" have been updated and uploaded to youtube.
What is PhET? : https://youtu.be/OjZ6qvi21Qo
Brief Intro: https://youtu.be/H9rdIl3rPgI
@mattpen they are ready to be uploaded to the website. 
Thanks!

**Comment by mattpen** [comment]
@CWilson4960 @amanda-phet - These videos are now up at https://ox-dev.colorado.edu/en/about and https://ox-dev.colorado.edu/en/teaching-resources/tipsForUsingPhet.  Can you please take a quick look and let me know if these are ok to deploy?

**Comment by amanda-phet** [comment]
Both look good. Thanks @mattpen !

**Comment by mattpen** [comment]
OK, I'll deploy these tonight.

**Comment by amanda-phet** [comment]
Sorry, one more thing. 

On the sidebar of this page https://ox-dev.colorado.edu/en/about there is a link for the What is PhET video at the top. That link opens the old version of the video. I didn't realize that link would need a separate update. Can you please replace that one too?

**Comment by mattpen** [comment]
OK, I thought I replaced all instances, I'll take another look.

**Comment by mattpen** [comment]
I fixed the remaining link and deployed to production. Closing.
