### ISSUE TITLE
Filter options

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#934]
In https://github.com/phetsims/tasks/issues/930 we decided we would no longer like to pass all of the options through to parent options--rather we would like to omit the subtype-specific options before passing the options through to the parent.  This will take slightly more CPU and memory, but hopefully in the noise (unless many objects being created using this pattern per frame).

To explore this strategy in TimerNode, I factored out different kids of options like this:

```js
    var timerNodeOptionDefaults = {
      iconColor: '#333',
      buttonBaseColor: '#DFE0E1',
      unitsChoices: [], // {string[]} The possible string values for units
      units: null // {string|null} The currently selected value for units
    };
    var supertypeOptionDefaults = {
      touchAreaDilation: 10,
      cursor: 'pointer'
    };
    options = _.extend( {}, supertypeOptionDefaults, timerNodeOptionDefaults, options );
// ...
    // Omit TimerNode specific options before passing along to parent
    this.mutate( _.omit( options, _.keys( timerNodeOptionDefaults ) ) );
```

I realized if we are filtering options, we will have many lines of code that read like:
```js
    this.mutate( _.omit( options, _.keys( timerNodeOptionDefaults ) ) );
```

Which is kind of difficult to read (though we would get used to it), and kind of error-prone (not trivial).  I wonder if we could benefit from a library method in phetcore, or possibly a Node method for convenience, which will do the `omit` for us.
```js
this.mutateOmit(options,timerNodeOptionDefaults);
```

@jonathanolson and @pixelzoom can we settle this in the issue, or should we schedule discussion at dev-meeting?

**Comment by samreid** [comment]
If we go for something more general in phet-core (usable outside of Node.js), one option would be something like:

```js
this.mutate( omitKeys( options, timerNodeOptionDefaults ) );
```

**Comment by zepumph** [comment]
the above method wouldn't support passing options up via `.call( options )`, which to me feels more dangerous that just overlapping with the `Node` options. `.call` will pass up through all ancestors on its way to `Node`

**Comment by samreid** [comment]
Sam Reid [5:07 PM]
Thanks, good point.  The `omitKeys` strategy I proposed in the issue may work for `call(this,options)`.


Chris Malley [5:07 PM]
I almost never use `mutate`.

Sam Reid [5:07 PM]
On the other hand, there are 258 occurrences of `this.mutate( options );` across our repos, so it may warrant special handling.

Chris Malley [5:08 PM]
The only reason to use `mutate` is if there are circumstances that make it difficult/impossible to use the supertype constructor.
Not saying it shouldn’t be used, but it shouldn’t be one’s default strategy.

**Comment by samreid** [comment]
If we implement filtering thoroughly, we will be able to check for incorrect options.  For instance, at the end of an inheritance hierarchy, we do one last filter.  Anything left in options is a typo and we can throw an assertion error.

**Comment by pixelzoom** [comment]
I suspect that we're going to create some problems when we omit options in existing code.  For example, consider something like `font` which might be used by both the subtype and supertype - a dubious approach, but I guarantee it's out there somewhere.  When the subtype filters out `font`, the subtype is going to be left using its default `font`.  And that will result in different look/behavior, depending on the option.  And I can't think of any way to detect this.

**Comment by samreid** [comment]
Note that this issue is very similar to https://github.com/phetsims/area-model-common/issues/139 which describes nesting as a way to specify where options are supposed to go.

**Comment by jonathanolson** [comment]
Also potentially relevant, but filtering everywhere will reduce performance (since now we're creating lots of extra objects everywhere to get GC'ed).

**Comment by jbphet** [comment]
@pixelzoom said:

> I almost never use mutate.

and

> The only reason to use mutate is if there are circumstances that make it difficult/impossible to use the supertype constructor.

I use it quite a bit in cases where I create a Scenery node and need methods like `addChild()`, but then want to pass through attributes such as `left`, 'top`, etc.  The supertype constructor is called early, then child nodes are added, then `mutate` is called.  This was a pattern that was suggested way back in the PhET HTML5 stone ages, and I think we will continue to need to support it.

**Comment by pixelzoom** [comment]
@jbphet I used that same pattern in the early days, but switched to calling the supertype constructor as late as possible, passing in children.  I'd like to see a specific example where you need to use mutate.

**Comment by pixelzoom** [comment]
And for the record... I'm not saying that you shouldn't use `mutate`, though I prefer not to unless I need to.  What I'm saying is that filtering of options (the issue we're discussing here) should not rely on having to use `mutate`, as was proposed in some of the comments above.

**Comment by pixelzoom** [comment]
And to clarify... I'm not saying that you shouldn't use mutate. If that's your style, go for it.  I personally think it's overused, and I don't see the point in initializing something twice (which is what happens with mutate) unless you need to, so I only use it if I have to -- which I find to be very rarely.  What I'm saying related to this issue is that filtering of options should not rely on having to use mutate, as was proposed in some of the comments above.

**Comment by samreid** [comment]
So are the outstanding questions for this issue:

(a) coming up with a pattern that works for both `Super.call(this)` and `mutate`?
(b) deciding how to address options that are needed by both the subtype and parent type (from @pixelzoom in https://github.com/phetsims/tasks/issues/934#issuecomment-385857016 ) ?

**Comment by Denz1994** [comment]
> This will take slightly more CPU and memory, but hopefully in the noise (unless many objects being created using this pattern per frame).

`_.omit` is documented as being " considerably slower than `_.pick`. " Instead of omitting options we don't want to pass could we `_.pick` options we do want?

**Comment by pixelzoom** [comment]
> Instead of omitting options we don't want to pass could we `_.pick` options we do want?

@Denz1994 Nice find, and that's a good thought.  Using `_.omit` only requires that a type know about its own options.  Using `_.pick` would require types to know the options of subtypes and subcomponents.  We could probably find a way to limit breakage of encapsulation, but it wouldn't be as clean/straightforward as omitting.

**Comment by jonathanolson** [comment]
> Using _.pick would require types to know the options of subtypes and subcomponents. We could probably find a way to limit breakage of encapsulation, but it wouldn't be as clean/straightforward as omitting.

We could just expose this like is done for Node and its subtypes in scenery (`Node._mutatorKeys`, `Path._mutatorKeys`, note that it's not public right now), but that style might be a lot of boilerplate if we do that for every component.

**Comment by jonathanolson** [comment]
Also, if we use `_.pick`, we lose the benefit of assertions failing if you typo something.

Another note is I would consider an option that **only uses `_.omit` when assertions are enabled** so we don't hurt performance by creating new objects if we don't have to for assertions.

**Comment by pixelzoom** [comment]
> We could just expose this like is done for Node and its subtypes ... but that style might be a lot of boilerplate if we do that for every component.

Having to maintain a separate list of keys (like `Node._mutatorKeys`) seems like a hassle, and an opportunity for the list to get out of sync from the default options hash.

**Comment by jonathanolson** [comment]
Also I'd like to discuss the question of whether the level of boilerplate/performance-loss/discussion is worth the benefits (mainly, in my understanding, catching typos of property names earlier). Are there other major benefits that I'm not factoring in here?

**Comment by Denz1994** [comment]
It seems like there hasn't been problems with not filtering passed options. At this point, we should be aware of how we are naming options. It would not be worth the dev time to implement a general solution for filtering options. @zepumph will update the PhET_software_design_pattern.md to include a warning for how we name options.
