### ISSUE TITLE
Artwork for Wave Interference

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#939]
@clmccutchan, as discussed, we need artwork for various wave sources for the Wave Interference simulation. The [Java version](https://phet.colorado.edu/en/simulation/wave-interference) of the sim will give you a better idea of what things will look like in action, but the [HTML5 prototype](https://bayes.colorado.edu/dev/html/wave-interference/1.0.0-dev.12/phet/wave-interference_all_phet.html?dev) will provide a better sense of the layout/scaling. The red border in HTML5 represents the iPad aspect ratio, so all artwork would need to fit within that boundary.

**Water Source**

* Appropriate perspective to drip water onto the surface (we already have artwork for the drip)
* Could be like a dropper or faucet
* Enough detail to convey its actions, but not photorealistic
* Room for on/off button 

**Speaker**

* Separate artwork for cone/body and membrane
* Needs cutouts or some way to view the membrane within
* Membrane displacement maps to amplitude, so need a set of 21 images (10 sets of max/min + one image for zero point)
* Enough room on base for on/off button

We had also discussed the possibility of alternative sources for plane waves, but there are design decisions we need to make as a team first. For now, don't worry about those. 

If you would like to have a follow-up chat or have any questions, please let me know @clmccutchan!

**Comment by clmccutchan** [comment]
@arouinfar For the water source, how about a garden hose? The shape would match that of the light source, and the button could be the same as for the light source.

**Comment by arouinfar** [comment]
I really like the idea of the garden hose @clmccutchan! I also just realized that I forgot to send you the laser asset file, which might be helpful. You can find it here:
https://drive.google.com/open?id=1ZrFzcqdGY1ZD1LGhxaZZtAPEswf5zngQ

**Comment by clmccutchan** [comment]
@arouinfar Here's a draft of the water source and speaker at max and min. I can easily edit the speaker between the max and min settings to create a set of images for the animation.

![wave interference_hose](https://user-images.githubusercontent.com/25354670/42126476-95795ff8-7c46-11e8-9ead-330f4c50a3cd.png)
![wave interference_speaker max](https://user-images.githubusercontent.com/25354670/42126477-9594d7c4-7c46-11e8-8379-1640d088ec39.png)
![wave interference_speaker min](https://user-images.githubusercontent.com/25354670/42126478-95ad5952-7c46-11e8-80d3-8ae9964a2ae0.png)

**Comment by arouinfar** [comment]
@clmccutchan these are looking really nice!  A few thoughts...

### Garden Hose
* I still really like the idea of using a hose as the water source.
* Can you mock up a version with a longer nozzle?
![image](https://user-images.githubusercontent.com/8419308/42188885-0b249614-7e13-11e8-85af-25dcbc8c0ba4.png)


### Speaker
* Speaker skeleton is looks awesome!
* Can you tweak the min/max so that they are a bit more extreme? I think we'll want the membrane animation to be a bit exaggerated so that students can make the connection between the speaker membrane and the wave itself.
* After adjusting the min/max, I'd like to see the a few steps of the membrane animation. 

### Plane Wave Source
The team decided that we'd like to try out a generic, black-box plane wave source. It could be a block or cylinder that looks like it grabs the edge of the wave viewing window. Here's a rough sketch.
![image](https://user-images.githubusercontent.com/8419308/42189052-c57e3f6a-7e13-11e8-8d1c-5a34ebddf18a.png)  ![image](https://user-images.githubusercontent.com/8419308/42189064-ce4aa5de-7e13-11e8-982f-c7d72500067f.png)

@clmccutchan please let know if you have any questions, or would like to have a follow-up chat!

**Comment by arouinfar** [comment]
@clmccutchan these are all looking great! I think the first/last speaker will work great for the max amplitude case.  

Can you upload the .ai file (CS6) to your Drive folder? I'd like to add them to the mockups for design team feedback.

In the meantime, can you prioritize the fan/propeller blades for #938?

**Comment by clmccutchan** [comment]
@arouinfar I've placed the .ai file in my artwork folder and formatted for CS6. Is that the right version for you?

I'm working on those blades today!

**Comment by arouinfar** [comment]
Thanks @clmccutchan!  The CS6 file works for me. Can you also include the original garden hose?

**Comment by clmccutchan** [comment]
@arouinfar Do you mean the reference photo with the longer nozzle or the first hose I sent you? I modified my original into the long nozzle version. I can easily redo my original in about 15 minutes if you'd like to have both versions.

**Comment by arouinfar** [comment]
@clmccutchan I was referring to the first hose you drew:
![image](https://user-images.githubusercontent.com/8419308/42466658-c06539a8-836c-11e8-8eec-e734cc3a808a.png)

I can modify the other hose to look somewhat similar. If the team prefers that look, I'll follow up with you recreate the original, but don't worry about it for now. Sorry about that! I should have clarified that I was looking for options to show the design team.

**Comment by clmccutchan** [comment]
@arouinfar I've got the .png of the original hose if that does you any good.

**Comment by arouinfar** [comment]
That would definitely be helpful @clmccutchan! Can you drop it in your folder?

**Comment by clmccutchan** [comment]
@arouinfar It's in there now! It's only screen resolution not high resolution but that should be good enough to debate over.

**Comment by arouinfar** [comment]
Got it, thanks @clmccutchan! It'll definitely work for debate. :)

**Comment by clmccutchan** [comment]
@arouinfar Here's a quick draft of the reworked hose. It's a bit boring right now, but what do you think of the shape and bronze color?  

I've got all of the speakers done and can pass that on to you if you'd like.

![wave interference_spout 2](https://user-images.githubusercontent.com/25354670/46896300-9bf85100-ce39-11e8-8d2e-eb22a922b450.png)

**Comment by arouinfar** [comment]
Thanks @clmccutchan! I'll review the hose with the design team and get back to you early next week. In the meantime, can you send me the .ai file (CS6) for the speaker?

**Comment by arouinfar** [comment]
The artwork has been committed in `wave-interference` so there's nothing else left to do here. Thanks @clmccutchan!
