### ISSUE TITLE
Should we use a Web App Manifest JSON?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#941]
This May be a nice improvement to how mobile devices can use our content. The jury is still out on exactly how best to implement this, but already in some places I see:
```
  <link rel="apple-touch-icon" href="../assets/img/apple-touch-icon.png">
```

perhaps this would just be adding onto this/improving on it.

I see potential here to add manifests for sim html files, for when people add a sim link directly to their homepage. And perhaps also (to a much lesser extent) for the phet-io website content too.

Further reading:
MDN: https://developer.mozilla.org/en-US/docs/Web/Manifest
Chrome: https://developers.google.com/web/fundamentals/web-app-manifest/
CanIUse: https://caniuse.com/#feat=web-app-manifest

**Comment by samreid** [comment]
We should probably even expand the scope and delegate a developer too look into Progressive Web Apps (of which Web App Manifest JSON is one facet) more generally, to see if there are other strategies we should leverage (included but not limited to manifest).

**Comment by jonathanolson** [comment]
Also might be worth checking whether we can stuff that information inline with a data URL.

**Comment by ariel-phet** [comment]
We are not going to investigate this idea at the moment, if we start to get some requests from users we will revisit.
