### ISSUE TITLE
QA: check a11y functions in the iOS app TableView

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#945]
The new table view for browsing some in the iOS app (iPhones only) needs to be checked to make sure it is accessible.  The primary things to check will be compatibility with voice over and focus highlighting.

Currently there is no dev version available. Assigning to myself until there is one published.

**Comment by ariel-phet** [comment]
Just noting when there is a dev version, to put the issue in the QA repo, but seems appropriate to have this one in tasks as a reminder.

**Comment by mattpen** [comment]
I moved this to https://github.com/phetsims/QA/issues/171, closing.
