### ISSUE TITLE
Improve information in our "Good Media Tweets" doc

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#948]
@kathy-phet requested that we improve the information in the [Good Media Tweets](https://docs.google.com/document/d/1E3Kk5FBd-8rnyHHZKFrpWhbI5cuK0_A-x793pB0i_zs/edit) google doc

She said:  

> Can you have an undergrad go through and put a header on each to describe what is know about these tweets: "Year, location, grade, sim, brief description"

My plan is to have Kelly W. work on this task when she starts, since it would be a good intro to understanding our social media presence and some of the "PhET love" out there.

**Comment by kellywurtz** [comment]
Completed spreadsheet w/ all tweets and tweet info: https://docs.google.com/spreadsheets/d/1yttVrJKGl0txW93JOihr4m_FRRSipjcw9rtdgU4OX64/edit?usp=sharing

**Comment by ariel-phet** [comment]
This spreadsheet is working nicely. Closing
