### ISSUE TITLE
Need artist for icons and slide designs for presentation

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#949]
I'm creating a presentation that needs to look very polished, including overall consistent professional PhET theme, and design of some icons. I'm outlining and laying out content now, and already know of some icons and slide designs needed. 

- Content will be created/refined now until Sept 20. 
- Final polishing can occur between Sept. 21-Sept. 25 (mid-day). 

I would like to partner with someone on icon and slide design soon.

**Comment by ariel-phet** [comment]
@emily-phet I think you might have seen some of @megan-phet work on the design-sims channel. She is working with our QA team, but seems to have some great graphic artist chops. I suggest you two connect on slack to discuss the project.

**Comment by emily-phet** [comment]
@ariel-phet Will do, thanks!

**Comment by emily-phet** [comment]
- [ ] Slide 1 and Slide 5: Keep text as is on each slide. Make look of each consistent. Make sure background cropped image is even on slide, and center box with text is centered. Right now the alignment is all wonky!

- [ ] Slide 7: Please see image of a sketch I created for an idea of what I have in mind. Please use the same icons aready in the slide (need grey version of laptop icon). These are just screenshots from fontawesome (links in the presentation notes under the slide). 

- [ ] Slide 8: I think it's fine as-is, please just check if the overall design appears consistent with Slide 7. I will frequently present these two slides together.

- [ ] Slide 10: (if you have time) I would like for this slide to be a pretty network map of PhET's partners. There's a great open-source program called gephi for creating network maps. If you could use this, or something else, to make a network map that shows clusters of partners, with clusters labeled in large font and partners labeled in smaller (but still legible at a distance) font, that would be wonderful. And it would probably be fun figuring out how to create one of these! They're quite trend now. :)

Overall design thoughts - I really like slide 1. I'd like the main colors to be white, black, or dark grey, with orange as an accent color (when needed). 

Please let me know if you have any questions.

**Comment by emily-phet** [comment]
Worked with Megan on some slides, and will work with Kelly to wrap up.
