### ISSUE TITLE
Are all eslintrc files needed?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#950]
I see 8 `.eslintrc` files in the project, but I didn't know if we still needed them because of recent work in supporting es6 for all repos.
![image](https://user-images.githubusercontent.com/6856943/44239610-b8904980-a166-11e8-8f01-4ae609358c12.png)

@jonathanolson are these all needed? Or just the one in chipper.

**Comment by jonathanolson** [comment]
All but the main one should be unneeded. I removed and tested `grunt lint-everything` and it's working nicely.
