### ISSUE TITLE
artwork for Fractions Intro

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#955]
@clmccutchan we are porting the java version of Fractions Intro to HTML5 and wanted to make a change to the cake artwork. Then we found out we only have .png files for every variation of cake, and they were all drawn using sketchup. So... it would be great if you could create these in illustrator instead so that we can also request a few tweaks. 

(1) Re-draw each asset using illustrator, saved in one file, with each piece of cake on its own artboard.
(2) Draw new pieces of cake for each fraction with the cake "resting" on the curved portion. Sixths are unique because one of the pieces is already in this orientation (cake_6_5), so you won't need to create it for sixths. But for the others, the artwork we already have doesn't include a piece in this orientation. Here is an example of what we need for fifths: 
![image](https://user-images.githubusercontent.com/7852916/45526514-a2d96880-b794-11e8-960e-34a89eaa106d.png)

Depending on your availability, I think it would be fine to start with (2) since we technically have all the artwork for (1) available (it is just not in an editable form). 

Here is the HTML5 version so you can see them in context: https://phet.colorado.edu/en/simulation/fractions-intro (incomplete, but shows the cake pieces in the first screen) 
Here is the original sim in case the HTML5 version gives you any problems (since it is in progress): https://phet.colorado.edu/en/simulation/fractions-intro

**Comment by amanda-phet** [comment]
Whoops! Here is the original artwork! 

[Cakes.zip](https://github.com/phetsims/tasks/files/2381700/Cakes.zip)

**Comment by clmccutchan** [comment]
@amanda-phet So sorry for the delay on this! I've dropped you an email about meeting to discuss. Also, the top link takes me to the original sim. Could you check that for me?

**Comment by amanda-phet** [comment]
After a discussion with @clmccutchan she is going to first redraw the whole cake (1/1) and make sure we agree on that look first before drawing the pieces. She proposed making it look a little more realistic with the decoration (maybe pink frosting instead of green, that sort of thing). Once we have agreed on the look she will draw the remaining pieces.

**Comment by clmccutchan** [comment]
@amanda-phet I've attached a new draft of the cake with more decorative frosting. I need to tweak the perspective on some of the frosting, but I think you'll be able to see what I'm thinking about for a more realistic cake than the original. 

I didn't add any shading on the actual cake, which I think will be appropriate since the frosting has some shading.

![fractions_cakes_draft100818-01](https://user-images.githubusercontent.com/25354670/46631773-a5b24980-cb05-11e8-97fc-7336838e1f68.png)

**Comment by amanda-phet** [comment]
I like this direction! It does look more realistic than the green stripe, and I agree the pink could be toned down a bit- perhaps more of a pastel pink. 

Can you elaborate on why there is no shading, or why that might be appropriate? I personally liked the shading.

**Comment by clmccutchan** [comment]
@amanda-phet I was just trying to get a quick draft with the frosting. But, because the frosting has some shading, I think the cake should also. I've toned down the pink and added shading to the cake. Let me know what you think of this draft.

![fractions_cakes_draft100918-01](https://user-images.githubusercontent.com/25354670/46684575-773d7880-cbb0-11e8-84b5-94b7603d61ce.png)

**Comment by amanda-phet** [comment]
@clmccutchan this is very pretty and a big improvement over the current cake pieces. However, I talked with @jonathanolson this morning about how he is currently using the images in the code, and I'm starting to think this is going to be problematic to re-draw all of the cake pieces. It could end up being very expensive to use new artwork if it isn't exactly the same in every way as the current artwork 😦 

So, can you instead just (2) and *not* do (1)? The cake pieces for (2) will be static in the sim, so they will not affect the code that is already implemented.

**Comment by clmccutchan** [comment]
@amanda-phet You betcha! I knew redrawing the cake would certainly take a lot more time than leaving  it as is. But I hadn't considered the issues with coding. I'll work on (2) for the pieces of cake sitting in the bucket next week.

**Comment by clmccutchan** [comment]
@amanda-phet Finally!! Let me know how these look and what needs to be fixed.

![fractions_cakes_whole](https://user-images.githubusercontent.com/25354670/49954610-1424d680-febe-11e8-9a24-55513beca12e.png) 
![fractions_cakes_eighth](https://user-images.githubusercontent.com/25354670/49954604-12f3a980-febe-11e8-8df9-5f6985e087db.png)
![fractions_cakes_fifth](https://user-images.githubusercontent.com/25354670/49954605-12f3a980-febe-11e8-90c5-49b1969bae22.png)
![fractions_cakes_fourth](https://user-images.githubusercontent.com/25354670/49954606-138c4000-febe-11e8-923e-18d90cf2234b.png)
![fractions_cakes_half](https://user-images.githubusercontent.com/25354670/49954607-138c4000-febe-11e8-92ca-050e7893fb56.png)
![fractions_cakes_seventh](https://user-images.githubusercontent.com/25354670/49954608-1424d680-febe-11e8-8e98-8731686185ab.png)
![fractions_cakes_third](https://user-images.githubusercontent.com/25354670/49954609-1424d680-febe-11e8-9e02-8f759084b497.png)

**Comment by amanda-phet** [comment]
These look great! I said we didn't need the 1/6 piece, but since yours all look really sharp and maybe slightly different from 1/6, can you make that piece too?

**Comment by clmccutchan** [comment]
@amanda-phet You bet!

**Comment by clmccutchan** [comment]
@amanda-phet Here's 1/6.

![fractions_cakes_sixth](https://user-images.githubusercontent.com/25354670/50021760-50783580-ff97-11e8-9a63-fe3b0df2bcd8.png)

**Comment by amanda-phet** [comment]
This sim has been published so this can be closed.
