### ISSUE TITLE
Two short videos clips for presentation

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#956]
I need two short video clips made for the presentation I'm giving Sept. 26.

- [ ] John Travoltage. Shooting for 30 seconds total. Use keyboard nav throughout. Includes:
- rubbing foot shown (no discharge event) - no audio at all
- rubbing foot shown, (no discharge event) - clear concise auditory descriptions provided (Note - No Voiceover readout visually on screen, make sure electron count is heard. Probably need to move slowly). Also: - minimal to no 'extra' non-sim specific description heard (can manipulate audio to get this if needed). Goal is to help someone who is not familiar with screen readers understand the value of description, hearing all the extra info screen readers provide not needed here.
- Rubbing foot shown, descriptions and sound heard, discharge event happens - description and sound heard
If this setup is proving too difficult, consider something that clearly indicates 1) experience with no auditory information, 2) experience with description only, description clear and helpful - minimal to no 'extra' description heard (can manipulate audio to get this if needed, e.g., selectively mute screen reader in post-processing ), and 3) experience with full audio (description and enhanced sound). 

- [ ] 15-20 second video of Friction with the latest sound (no description). Use mouse (no need to show mouse cursor in video, though)
- Move the book slowly
- Then quickly (get particles to fly off)
- Then release and let system cool down. 
- Hit reset all at end.

Ideally would have these done by Friday. Friction should be very quick, JT may prove more difficult.

**Comment by ariel-phet** [comment]
@emily-phet do you want any "effects" likes text or any overlay or intro/outro or such? @kellywurtz who I am assigning this to is quite skilled with video stuff.

@kellywurtz please make this your top priority, and feel free to have QA show you how to access the various features.

**Comment by emily-phet** [comment]
All done!
