### ISSUE TITLE
Mockup of a Physics calendar submission on a11y work

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#959]
The physics department is asking for submissions for the 2019 calendar. @kathy-phet suggested we put together one representing the a11y work. Here's an idea I had:

One idea would be an artistic image that conveys the description layers added into Balloons and Static Electricity, with an inset or overlay of an image of a student using the a11y features [like this one](https://donatenow.networkforgood.org/accessiblephetsims). 
Maybe something layered that has 1) a semi-transparent background image showing some sketches, the a11y view, etc., 2) a large screenshot of BASE, and 3) a small-ish inset image of the student using the sim. 

I'd like someone to mock this up, so we can pass it along to those in the department collecting possibilities for the calendar.

**Comment by amanda-phet** [comment]
Would it make sense to include the work that Megan has done to illustrate an inclusive classroom? She and Mariah have spent a lot of time on those graphics and I have been wondering when they will be used.

**Comment by ariel-phet** [comment]
@amanda-phet I use those scenes Mariah created (and will be using the ones Megan created) a fair bit on social media.

@emily-phet can you make a powerpoint slide or just a hand sketch of what you are describing, I am not quite sure I follow. This could literally be just rectangular boxes with "screenshot here" etc, very low fidelity. I am also not sure what you mean by things like "a semi-transparent background images showing some sketches"...what are sketches in this context?

I think we need a bit more info on your vision of the image before handing it off to an artist.

**Comment by emily-phet** [comment]
For layer 1, I was hoping to have something that conveys some of the different types of work involved. It doesn't have to be readily understandable to the viewer, but something visually interesting that sets the backdrop for the outcomes shown in layer 2 and 3 (i.e., the completed accessible simulation, and the happy learner). 

This could be screenshots of the a11y view, text Taliesin generates listing description scenarios (with her pseudocode style), some representations of sound could be used (even though there's none in this sim specifically), etc. Just some of the visual artifacts (or artifacts that can be visual) that get created along the way, somewhat randomly distributed about, with a slight transparent feel, so it's clear that this is the 'background'.

**Comment by emily-phet** [comment]
Some screenshots of example artifacts:
From [BASE: Two-balloon experiments.](https://docs.google.com/document/d/1LrOWT4RZiS4emrumW479POK--zWveWiylZMd7unNyi0/edit?usp=sharing)
<img width="779" alt="screen shot 2018-10-22 at 12 01 30 pm" src="https://user-images.githubusercontent.com/5109055/47306555-61897380-d5f2-11e8-95cd-4d41df3cefd4.png">

From [BASE: Grid Descriptions Simplified and Revised](https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit?usp=sharing)
<img width="535" alt="screen shot 2018-10-22 at 12 04 34 pm" src="https://user-images.githubusercontent.com/5109055/47306694-cba21880-d5f2-11e8-8999-d61301d629eb.png">

[A11y view of old-ish version of sim](https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.24/phet/balloons-and-static-electricity_a11y_view.html):
<img width="1079" alt="screen shot 2018-10-22 at 12 07 30 pm" src="https://user-images.githubusercontent.com/5109055/47306851-2e93af80-d5f3-11e8-998b-84fa866e2648.png">

**Comment by ariel-phet** [comment]
@megan-phet will try to do a rough draft tonight.

**Comment by DianaTavares** [comment]
Hi @emily-phet, this is what I understand with the descriptions. Let me know what you think: 

![screen shot 2018-10-23 at 1 09 40 pm](https://user-images.githubusercontent.com/26031501/47384639-112f1600-d6c5-11e8-9aae-f7c4d6dae6bc.png)

**Comment by emily-phet** [comment]
@DianaTavares Looks nice! A few suggestions:

- Could you add a border to the image of the student, and bump the picture up and to the left a little, so that it doesn't go to the edge of the image. Maybe enough left so that it covers the 'reset balloon' button in the sim, and just high enough it doesn't overlap with a speech bubble in the sim. 
- Could you replace the text in the speech bubbles with the same text, but a more pleasant font? 
- Could you replace the sim name in the sim screenshot with bolder text, so it doesn't look so faded?
- Could you shift the upper right keyboard icon down to be somewhere lower along the left side of the sim screenshot (rather than in the corner)?

Do you have a few minutes in the morning for final tweaks and checking how the exported files look with me?

**Comment by emily-phet** [comment]
@kathy-phet 
Proposed caption:
Dr. Moore is the Director of Research and Accessibility for the PhET Interactive Simulations project. Dr. Moore is a leader in inclusive education technology, and directs a team of physicists, linguists, musicians, education researchers, software developers, teachers, and students in the research and development of multimodal simulations. Through the careful design and evaluation of auditory descriptions, sound effects and sonification, and diverse input capabilities, many PhET simulations now offer new ways for students to communicate with, and learn from, the simulations. By providing the opportunity to access PhET simulations through visual, auditory, and diverse input layers, learning experiences with these multimodal simulations are now fully accessible to learners with sensory or mobility impairments. 
This month’s calendar image honors the work of Taliesin Smith (Inclusive Designer) and Jesse Greenberg (Lead Accessibility Developer) whose tremendous ingenuity and tenacity resulted in the first complex PhET simulation with auditory description, Balloons and Static Electricity. The artwork shows just a few of the many design artifacts used to create, organize, and study the descriptions for this simulation. The photo shows one of the many learners, representing a diversity of needs, whose feedback and insights contributed significantly to our understanding of effective description for simulations.

**Comment by emily-phet** [comment]
@DianaTavares 

Looks great! A few last tweaks:

- Let's replace the 'description icon' with the blue lines, with the one having yellow/orange lines. Then remove the current 'description icon' with yellow/orange lines from behind the photo.
- Move the keyboard icon up slightly
- You might just remove the radio buttons box entirely, and just draw in a balloon cord that would then be missing. It doesn't have to be exactly the sim, just clearly identifiable as the sim.
- There are multiple typos in the description text in the speech bubbles. Can you take a look through and double check that the text matches exactly that from the original figure.

Thanks! 

-

**Comment by DianaTavares** [comment]
![screen shot 2018-10-24 at 11 51 05 am](https://user-images.githubusercontent.com/26031501/47450706-2c605b00-d783-11e8-9152-84b39266534e.png)

**Comment by emily-phet** [comment]
@DianaTavares 
Perfect!! I love it. :)

**Comment by DianaTavares** [comment]
:D perfect, I am glad that you like it! I love it too!

Here is the PDF that have the size that @ariel-phet give me (because the images that I use in this issue are screenshot. Let me know if you need that I save the file in other extension and where to save it in PhET google Drive if its needed. 
 
[2018calendarRoughDraft.pdf](https://github.com/phetsims/tasks/files/2512012/2018calendarRoughDraft.pdf)

**Comment by DianaTavares** [comment]
yes, working in that!

**Comment by DianaTavares** [comment]
this is a 9 X 11.5 in document with .25 in border (then the image is 8.5 X 11). I just move a little bit some pictures.
![calendarphet2018-01](https://user-images.githubusercontent.com/26031501/47465371-eff42580-d7a9-11e8-922b-52eca4e6719f.png)
[calendarPhET2018.pdf](https://github.com/phetsims/tasks/files/2512559/calendarPhET2018.pdf)

**Comment by emily-phet** [comment]
Wonderful. I believe this all done. I'll reopen if we get some requests from the folks putting together the calendar.

**Comment by emily-phet** [comment]
@DianaTavares 
Update suggested by folks making the calendar:

> This is totally fine as a graphic, but the result will likely be some white space on one side or another, trimming isn’t always 100% on point, which is why we’re using the bleed, and carrying the graphic to .25” outside of the normal print area...My inclination is to just stretch the back and keep the front two images and logo exactly where they are.

Does this seem doable? So having the grey background, and the images in the background, go to the edges, leaving the logo/sim screenshot/photograph where they are.

**Comment by DianaTavares** [comment]
Yes, then it's something like this: 
A 9 X 11.5 document without white margin: pictures and logo in the same position that the last time:
[calendarPhET2018.pdf](https://github.com/phetsims/tasks/files/2516138/calendarPhET2018.pdf)
 
![calendarphet2018v2-01](https://user-images.githubusercontent.com/26031501/47519823-b4119c80-d84b-11e8-87ba-fd10df282f5d.png)

**Comment by emily-phet** [comment]
Sent. Thanks @DianaTavares
