### ISSUE TITLE
Downloads and views for Activities authored by Tim Herzog

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#960]
Can someone aggregate statistics on the views and downloads to activities authored by Tim Herzog? I'd like to share these numbers with him, and acknowledgment his long-time collaboration with us.

**Comment by arouinfar** [comment]
I don't know how to access statistics for activities, but here's a link to Tim Herzog's activities to make it a bit easier for whoever is assigned this issue:
https://phet.colorado.edu/en/teaching-resources/browse-activities?sims=all&types=all&subjects=all&levels=all&locales=all&query=Herzog

Interestingly, one of Tim's activities has been modified by another teacher for MS/HS, and another has been translated into Swedish.

**Comment by ariel-phet** [comment]
@emily-phet how important/priority is this? I will discuss with Matt, but I don't think we currently have this ability as I think stats are only currently being kept for sims. My guess is it will take either some new scripts going forward, and I am not sure if we can parse logs or not for this historical data. Will check with Matt?

**Comment by mattpen** [comment]
Here are the total page views from Google Analytics.  This relies on sampling and is not super accurate, but should give a good rough estimate.  To calculate the downloads, I'd need to spend a couple of hours parsing the apache logs.  Should we be tracking these numbers going forward?


|                         title                          |       date | authors                                                       | views |
| ------------------------------------------------------:| ----------:| -------------------------------------------------------------:| -----:|
| Molecule Shapes - Guided-Inquiry Activity              | 2014-11-02 | Timothy Herzog, Emily Moore                                   | 41723 |
| Build an Atom - Guided-Inquiry Activity                | 2014-11-05 | Timothy Herzog, Emily Moore                                   | 54117 |
| Isotopes and Atomic Mass - Guided Inquiry Activity     | 2014-11-05 | Timothy Herzog                                                | 31175 |
| Balancing Chemical Equations - Guided Inquiry Activity | 2014-11-05 | Timothy Herzog, Yuen-ying Carpenter                           | 68312 |
| Molecule Polarity - Guided Inquiry Activity            | 2014-11-05 | Timothy Herzog, Emily Moore                                   | 15422 |

**Comment by emily-phet** [comment]
Hmm, I didn't realize this was such a challenge. I believe I've seen download counts for activities before, and assumed we had some relatively straightforward way of determining this. The views from Google Analytics are probably sufficient. I'm going to close this issue, and will re-open in the (unlikely) case more data is needed. Thanks!
