### ISSUE TITLE
Poster Layout Help for ASSETS demonstration poster

### ISSUE THREAD

**Issue by terracoda** [phetsims/tasks#961]
Help needed to set-up illustrator file that I can tweak content and add and adjust images

Google document containing sketch and text is here:
https://docs.google.com/document/d/11i-V1xENMVCKhvpXiQCEZ9tqOfqlIEVwROcoZNdoKp8/edit?ts=5bc4c4ec#

What would be great to have illustrator poster file set in a portrait layout 
- no wider than 33 inches (with bleed)
- using the new black/pink theme
  - thick black header (White text) 
  - large dark pink section headings for the sections as indicated sketch and text the google document
  - at least one bulleted list that  can copy
  - two speech bubbles with alert text provided in google doc

Is this possible for end of day Tuesday, so add the figures that I will gather up tomorrow.

**Comment by terracoda** [comment]
@arouinfar or @DianaTavares would one of you be able to help me with this issue? I know it is very short notice.

**Comment by emily-phet** [comment]
@ariel-phet - any chance someone might be able to help @terracoda out with this one?

**Comment by DianaTavares** [comment]
This is the first draft. I fallowed the structure in the picture in the document in google drive and I put all the text of the file (The table in the Demo/auditory Display is only an example). The size in this moment is 33X48 in, body font size 32 pt and 40 pt for the header. 

Bullet lists are super tricky in illustrator (I did the Visual Demo and Methods as example). I am going to ask @arouinfar if it's an easier way. I am going to finish with that edition tomorrow. 

If @terracoda prefers,  you can put the pictures and logos in google drive and  I will put them in the document in the same size and resolution. 

As you can see in the draft, the size of the sections are not the same for to have all of them in a perfect grid as the picture in the google drive shows. Let me know what do you want I modify. 

The gray rectangles  are just a guide, I will delete them later. 

![screen shot 2018-10-15 at 7 43 55 pm](https://user-images.githubusercontent.com/26031501/46987752-ca349580-d0b2-11e8-9d0c-84351a45a008.png)

**Comment by terracoda** [comment]
@DianaTavares, thank you are amazing! I now see very clearly where I need to shorten text (everywhere)! 

I'd like the poster to be a very visual attention grabber - with the Demo section big and inviting. I will visualize PDOM text, so it will be an image. 

On the final version, I'd really like to have the four main PhET A11y icons (Sound, Static Descritpions, Dynamic Descriptions, Alternative Input) somewhere, maybe nice and beside the big Demonstration heading. 

These icons are on the ISTE poster and flyer in PhET Conferences, Workshops../2018 Conferences/2018.06 ISTE folder, but I'm not sure where the originals are. 

I'll shorten text and make/gather images.

**Comment by terracoda** [comment]
Found the accessibility icons. They are here:
https://drive.google.com/drive/folders/0B44Uycdx6JGdb2NkbmhlSGtMSUk

For easy access, I'll copy the png's into my Assets Poster folder.

**Comment by terracoda** [comment]
@DianaTavares, thanks again fro your quick layout. It's helping me focus.

I uploaded several images:
- a head shot of me (and my son, but it was the only good one I could find)
- 2 screen shots
  - the JT PDOM
  - JT arm positions (may not use)
- a11y icons for sonification, description, full description, and keyboard
- STILL NEED to FIND a Georgia Tech logo and maybe sound lab logo if they have one?

**Text:**
I've started, and plan to drastically shorten text in the Research section.
If you get to layout before me, just chop off the middle column in research section, and I can add text that fits.
I will drastically shorten Summary to make room for Refs, Acknowledgements & Contact Info

**Visual Design Feedback:**
- would like the black background for the header to bleed off the page if possible.
- would like the title to be on one line if possible (maybe make PhET logo smaller)
- would like References and Acknowledgements in separate boxes

**Comment by arouinfar** [comment]
> Bullet lists are super tricky in illustrator (I did the Visual Demo and Methods as example). I am going to ask @arouinfar if it's an easier way.

@DianaTavares I don't think there is a particularly great way to make bulleted lists in Illustrator. You'll need to insert the bullet symbol into the text box or draw your own circle next to the text. I prefer drawing the circle separately, as that gives me more control over the size and placement. The size of your bullets in the mockup looks good, but I would add a few more spaces between the bullet and the words.

> STILL NEED to FIND a Georgia Tech logo and maybe sound lab logo if they have one?

Not so sure about the Sound Lab, but you can find Georgia Tech's brand standards and logos here:
http://www.comm.gatech.edu/brand/visual

**Comment by DianaTavares** [comment]
Thanks @arouinfar and @terracoda! I am working in the editions suggested. @terracoda, can you send me the link of the folder with the images? 

I will wait till the text is shorten to work about the bullet lists with @arouinfar recommendations.

> Visual Design Feedback:
> 
> would like the black background for the header to bleed off the page if possible.
> would like the title to be on one line if possible (maybe make PhET logo smaller)
> would like References and Acknowledgements in separate boxes

I already did this feedback.  Working in the Auditory Display - Sound Table!

**Comment by terracoda** [comment]
@DianaTavares, I uploaded new logos for Georgia Tech and Sonification Lab.

**Comment by terracoda** [comment]
Apologies, I just updated the list instead of posting a new comment. I should have made a checklist.

**Comment by terracoda** [comment]
All the files are  in here:
https://drive.google.com/drive/folders/1IafXB_kq_OTzAhDBWeF5VDKHCiTqAjdF

**Comment by DianaTavares** [comment]
I add the pictures (I just need to know where to put them). The quality of the logos looks a little bad when it's small, but looks good in the 100% zoom. I don't finish the table yet because I only put two rows and it's not going to fit, the table in the document has 4 rows more, then probably @terracoda want to delete some text in the table as well. 

Let me know your comments and when the new text it's ready! I have class today at 4:45, but before that I can work in the poster and send you the .ai file. 

![screen shot 2018-10-16 at 12 00 59 pm](https://user-images.githubusercontent.com/26031501/47037064-2c38dd80-d13b-11e8-96b1-9f0095ea823f.png)

**Comment by terracoda** [comment]
New version just uploaded to google docs.
Everything above the Evaluation section is done (except I need to add new small screen shots)

I am now shortening the text in the google doc for the bottom sections. I do not know how to 3 important things:
- Underline my name in the list of authors
- Add bullets where I currently have dashes
- Turn off auto hyphenation. I'd like to see if everything fits without any hyphenated text

**Comment by DianaTavares** [comment]
The poster it's looking beautiful!! this is the way to get that 3 things:

> Underline my name in the list of authors

Select the text that you want to underline, click in "Character" in the top of illustrator and click in the underline icon:

![screen shot 2018-10-17 at 10 06 26 am](https://user-images.githubusercontent.com/26031501/47101052-4388d100-d1f6-11e8-9d7a-9a3e84f3c97f.png)

> Add bullets where I currently have dashes

Find the little circle symbols clicking first in "Type" in the top of illustrator and then in Glyphs. This is going to open a window, look there for the bullet symbol. 

![screen shot 2018-10-17 at 10 31 33 am](https://user-images.githubusercontent.com/26031501/47101872-72a04200-d1f8-11e8-9984-49ecab498fe5.png)

In your text, put the cursor in the position where you want the bullet and give double click in the icon of bullet in the Glyphs window.

**Comment by terracoda** [comment]
Thanks so much for your help @DianaTavares. Here's a small screenshot of the final version.
<img width="397" alt="screen shot 2018-10-18 at 3 28 39 am" src="https://user-images.githubusercontent.com/1902116/47125904-26034800-d286-11e8-8049-2fbdcc2eb50c.png">
