### ISSUE TITLE
Artwork for Energy Skate Park

### ISSUE THREAD

**Issue by arouinfar** [phetsims/tasks#962]
@jessegreenberg will be working on adding skater options to ESP (https://github.com/phetsims/energy-skate-park/issues/32), so we should get started on updating the skater artwork.

Here are the options in Java:
<img src="https://user-images.githubusercontent.com/8419308/47448163-8f9abf00-d77c-11e8-85ef-9439a169fdc2.png" width=250>

Some modern skater options could include:
* PhET girl
* @ariel-phet's dog Emmy (reference photo would be much appreciated!)
* Skater in a wheelchair (inclusive, but we would need to ignore the rotation of the wheels)

Any thoughts @ariel-phet? 

This seems like a good task for @megan-phet.

**Comment by ariel-phet** [comment]
Here is a reference photo for Emmy (I can certainly take one if having a specific post would be helpful, just let me know what you would want @megan-phet) 

@arouinfar lets start with the basic options, and we can talk with @emily-phet if there is an inclusive option we want to try. 

![hans yard](https://user-images.githubusercontent.com/4051174/48040577-be2e7780-e136-11e8-9b97-2c2e4b2f18d0.jpg)

**Comment by emily-phet** [comment]
@ariel-phet @arouinfar How about a skater with a prosthetic leg, an homage to Jon Comer?

**Comment by arouinfar** [comment]
Thanks @ariel-phet @emily-phet! I'll set up a meeting with @megan-phet to get started on this.

**Comment by arouinfar** [comment]
Thanks @megan-phet! I'll show these to to the team in our next design meeting.

**Comment by emily-phet** [comment]
Nice! As a note for any future iterations on the the third skater above - modern prosthetic limbs look more bionic. If you'd like me to point you to some images of real ones, let me know.

**Comment by arouinfar** [comment]
@emily-phet can you send us some reference images?

**Comment by emily-phet** [comment]
google image search for "prosthetic leg skateboarder" and you'll find a ton.

**Comment by emily-phet** [comment]
as i believe @ariel-phet mentioned, there's also the wheelchair athlete that could be represented. image search "wheelchair athlete skateboarder" and you'll find a lot.

**Comment by arouinfar** [comment]
@emily-phet we don't have any artwork of a wheelchair athlete with the appropriate perspective. While I love the inclusivity, I'm worried that the large wheels will create expectations of moment of inertia/rotational energy that ESP is not designed to address.


Looking at "prosthetic leg skateboarder", none of these look particularly bionic to me, though I do see some room for improvement over the current design. If there is something in particular you're looking for @emily-phet, please let us know!
![image](https://user-images.githubusercontent.com/8419308/48367656-95ded580-e66e-11e8-9f08-b0e6c9e56ddf.png)
![image](https://user-images.githubusercontent.com/8419308/48367671-a727e200-e66e-11e8-9d88-626e72c342fb.png)
![image](https://user-images.githubusercontent.com/8419308/48367684-aee78680-e66e-11e8-82a2-da51f586c6f0.png)
![image](https://user-images.githubusercontent.com/8419308/48367625-8790b980-e66e-11e8-8859-0ed672ec8e06.png)

I did find some examples of 3D printed covers for prosthetic legs that look pretty cool.
![image](https://user-images.githubusercontent.com/8419308/48367834-2c12fb80-e66f-11e8-93f3-8a0c12172e42.png)
![image](https://user-images.githubusercontent.com/8419308/48367846-346b3680-e66f-11e8-9765-8760b4dfa1ed.png)

**Comment by emily-phet** [comment]
@arouinfar I don't have a preference re wheelchair or not. For the prosthetic legs, I think it just needs to 1) be clearly a prosthetic leg, and 2) look "cool". Maybe something like the second pic above?

**Comment by megan-phet** [comment]
<img width="396" alt="screen shot 2018-11-20 at 5 48 56 pm" src="https://user-images.githubusercontent.com/40698031/48811827-ba7d2200-ecec-11e8-913b-afb479ebaee1.png">
<img width="373" alt="screen shot 2018-11-20 at 5 49 14 pm" src="https://user-images.githubusercontent.com/40698031/48811829-bcdf7c00-ecec-11e8-8372-e9cddcaf5e10.png">

**Comment by arouinfar** [comment]
Looks awesome @megan-phet! I think the 2nd option has a very cool prosthetic, but I think we'll have to wait and see how well it scales since the skater's size changes with mass.

![image](https://user-images.githubusercontent.com/8419308/49117623-91b1db00-f25e-11e8-8d2a-7bd1248a3324.png) ![image](https://user-images.githubusercontent.com/8419308/49117648-a42c1480-f25e-11e8-9ebc-103f644d3dc1.png)

I like @emily-phet's suggestion for more stylish shoes. Can you add a bit of detail to the shoes @megan-phet? Maybe they can look more like classic Converse, since that's a simple silhouette.

**Comment by arouinfar** [comment]
As discussed with @megan-phet, we'd like two additional skaters which look more like high school students -- one male and one female.

The latest .ai file can be found in the sim design folder:
https://drive.google.com/drive/folders/0B6CMwxdP0NGYQXEyZVk0U3I1Q3M

This should take priority over #1019.
