### ISSUE TITLE
All a11y listeners should use scenery.Event instead of DOMEvent

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#970]
From https://github.com/phetsims/scenery/issues/888, now that many listeners are passing a scenery Event as the arg to listeners I think it would make things easier to read if all a11y functions did this moving forward, especially in common code. For instance, in KeyboardDragListener instead of passing the optional `start`  function a DOMEvent, it would be more unified if it received a scenery.Event. So all a11y callbacks and listeners listeners get the keycode through event.domEvent.keyCode.

@mbarlow12 @zepumph OK if I proceed with this or do you have concerns?

**Comment by zepumph** [comment]
No concerns. This is great. This implementation seems like it will cover discussion in https://github.com/phetsims/scenery-phet/issues/408#issuecomment-444571306. Should we close that one to be done here?

**Comment by jessegreenberg** [comment]
Thanks @zepumph, sounds good.

**Comment by jessegreenberg** [comment]
Running through local tests now, Ill commit if all looks OK. I tried to find all cases of this by searching for usages of `click:` `focus:` `blur:` `change:` `input:` `keydown:` `keyup:` `event.preventDefault` and `keyCode ` and `event.which`. Hopefully this caught everything.

**Comment by jessegreenberg** [comment]
Local aqua is passing, scenery unit tests are passing.

**Comment by jessegreenberg** [comment]
Closing, but Ill keep an eye on CT. @mbarlow12 if you would like to discuss this further, please feel free to reopen.
