### ISSUE TITLE
Remove `for of` loop from sim code

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#972]
It looks like babel transpiles this into using `Symbol` and expects a polyfill. We don't do polyfill that right now. On top of that @jonathanolson says that `forEach` loops are faster even with the closure. As a result we should convert usages to that, and when necessary use the traditional `for (let i=0; i<length; i++)`.

I see 75 usages of `for \( let \b[A-z]*\b of`, though many can stick around because they aren't in sim code. Assigning to responsible devs of these repos.

- [x] friction
- [x] wave interference
- [x] fractions-common
- [x] gravity force lab
- [x] Enumeration

**Comment by samreid** [comment]
See also https://github.com/phetsims/wave-interference/issues/223

**Comment by samreid** [comment]
Pushed new lint rule that prevents `for...of`.  This will prevent it from leaking into our sims, and will help encourage us to use consistent style across sims + tools.

**Comment by jonathanolson** [comment]
> I suspect some team members may prefer to use for...of in tools without having to specify // eslint-disable-line no-restricted-syntax, but it would seem unfortunate to divide our linting rules.

Definitely don't want to have to provide an eslint disable for most of my for-loops in Node.js code.

How about we deliberately have separate Node.js and browser rules? For example, you never want to reference a global `window` in Node.js since it doesn't exist. But presumably we don't want to have an eslint line disable comment for every usage of `window`, etc. (or would you feel otherwise?)

**Comment by jessegreenberg** [comment]
Possibility to extend eslintrc files? https://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config

**Comment by pixelzoom** [comment]
12/13/18 dev meeting:  @zepumph will investigate splitting into sever (Node) vs browser lint rules.

**Comment by zepumph** [comment]
High priority so this doesn't fall off my list.

**Comment by zepumph** [comment]
Looking into https://github.com/eslint/eslint/issues/6460 it doesn't look like we can support this with one eslint file, but perhaps we can still handle this within chipper. 

Before we supported es6 linting in all repos (and sim code), we had eslintrc files all over the place specifying that it was es6. Rather than trying to do a solution like that, I wonder if we can just have two lists in lint, where we apply the main .eslintrc to all sim repos, and then add a new eslintrc file that "extends" the original with the appropriate node specific rules, like allowing `for of` loops. See https://eslint.org/docs/user-guide/configuring#extending-configuration-files

I'm not sure if this is how we want to go about this forever, but I'm going to try to create a list in perennial/data/node that supports node linting, and everything else will be linted normally.

**Comment by zepumph** [comment]
I tried the following and thought it would work, but I can't see to get it to:

`chipper/js/grunt/.eslintrc`:
```
{
  // Use all of the default rules from eslint, unless overriden below.
  "extends": "../../eslint/node_eslintrc.js"
}
```

`chipper/eslint/node_eslint.js`:
```

module.exports = {
   extends: './.eslintrc',
   rules: {
    'no-var': 'error',
    'no-restricted-syntax': [ 'off', 'ForOfStatement' ],
    'no-console': 2
  }
};
```

But I can't get this to work. If it did, the next step would be to add the basic eslintrc to every dir we wanted to be linted with node. 

Next I'm going to try having two instances of CLIEngine in lint.js because you can specify different environments for each instance of that.

**Comment by zepumph** [comment]
After discussing with @samreid, we made some good progress!

the dead end I found in https://github.com/phetsims/tasks/issues/972#issuecomment-447176812 had to do with the fact that we were using `configFile` option in eslint.CLIEngine in lint.js, and that has precedent over any other eslintrc files in directories. So we weren't able to override our "defaults" by adding an eslintrc file in, say, `chipper/js/grunt`.

We determined that the following path may be an option to look at: Look at removing the configFile option, and having each package.json file specify the path to `chipper/eslint/.eslintrc`. In small tests this appears to have worked. 

During this process we also (locally) looked at upgrading to eslint 5.10 (we are still in 3), and it looks like a few new rules came along for free. Maybe that's something we want to do.

**Comment by samreid** [comment]
> baseConfig - Can optionally be set to a config object that has the same schema as .eslintrc.\*`. This will used as a default config, and will be merged with any configuration defined in .eslintrc.\* files, with the .eslintrc.* files having precedence.

https://eslint.org/docs/developer-guide/nodejs-api#cliengine

> Michael Kauzmann [8:33 PM]
ahhh so maybe we can just load the base config as a string, and then have the files override it.

> Sam Reid [8:34 PM]
on second thought, I don’t know how that would plug in to IntelliJ

**Comment by zepumph** [comment]
Alright, with the immense help of @samreid, I was able to get to a commit point. This piece of writing is a bit of a hunk (sorry), but I would like devs to understand it as best they can so we can discuss next steps at developer meeting.

Here is how lint now works in the project now:

Well maybe it would be best to explain how it used to work. Before we just had one file. It was simple enough to use that one config file as the absolute truth, providing it to the eslint plugin in webstorm, and to the grunt task. For the purpose of clarity below. Let's call this main/single eslint file the "base eslint config file." 

Since we wanted to support two different possible lint rules, we had to rethink this single file approach. Now in next to the base file, there is a supplementary config file meant only for node code, this is called `chipper/eslint/node_eslintrc.js`. This extends the base config, overriding the rules we want, and adding others (though currently we haven't added anything). In addition, we now support sub directories opting into node (see `chipper/js/grunt`). As part of this, we have now moved to `eslintrc`-like files throughout the tree structure of the project. The way it works is that each `package.json` now has a pointer the either the base eslint file (most repos, including sims, do this), or, if it is a node repo, to the supplementary node config.

To support node in a subdir, you just create an `.eslintrc` in that dir, see `chipper/js/grunt`. This simple file just points to the node config file (which then in turn extends the base config).

One downside to this approach, is that currently, the grunt lint task fails on a repo if it doesn't find any js to lint in the repo. As a result I created `perennial/data/not-lintable` as a blacklist for the grunt lint process. The plugin will fail in those repos if looking at js files.

A few other modifications that were made to support this endeavor:
* There is now a `perennial/data/node` list that points to all
* Converted the base `.eslintrc` to a `.eslintrc.js` module which is in javascript (@samreid was happy about that).
* Updated the docs on how to setup the IDEA eslint plugin (all devs using jetbrains should see https://github.com/phetsims/phet-info/commit/59e6f102867edcbf3d50891953eb961af3442660#diff-c6bef019481d20c834578acdcbe8839d)

note to myself:
<details>
<summary>script used to modify all package.json files</summary>

const fs = require( 'fs' );
const getDataFile = require( '../chipper/js/grunt/getDataFile' );

const activeRepos = getDataFile( 'active-repos' );
let nodeRepos = getDataFile( 'node' );

// don't keep subpaths
nodeRepos = nodeRepos.filter( repo => {
  return repo.split( '/' ).length === 1;
} );


activeRepos.forEach( repo => {
  try {
    const path = `../${repo}/package.json`;
    const packageString = fs.readFileSync( path );

    const packageJSON = JSON.parse( packageString );


    let extendsPath = '../chipper/eslint/.eslintrc.js';
    if ( nodeRepos.indexOf( repo ) >= 0 ) {
      extendsPath = '../chipper/eslint/node_eslintrc.js';
    }
    packageJSON.eslintConfig = {};
    packageJSON.eslintConfig.extends = extendsPath;

    fs.writeFileSync( path, JSON.stringify( packageJSON, null, 2 ) );
  }
  catch( e ) {
    if ( e.message.indexOf( 'no such file or directory' ) >= 0 ) {
      console.log( `no packagejson for ${repo}` );
    }
    else {
      throw e;
    }
  }
} );


</details>


## Next Steps:
- [ ] Look into having `grunt update` or another task modify the `eslintConfig` section of package.json.
- [ ] @samreid was very interested in pursuing custom lint rules, for example. We could create a third config file that extends the base config for es6-only sims. That could have rules like `no-var`, but still would not allow `for of` loops.
- [ ] There is a potential concern about how package.json can have two different values, depending on if the repo is in `perennial/data/node`. Is that the best way to go? We could also say that all package.json entries look the same (extending the base config), and then node repos can add an `.eslintrc` file to the root, therefore overwriting the package.json config.
- [ ] Automate the maintenance of `node` and `not-lintable` files? Perhaps with flags in package.json files? 
- [ ] Perhaps we can just get rid of `data/not-lintable`, and instead put a dummy js file in each repo, or some other solution. @samreid and I thought that there must be some setting we could flip to make it not error out (or to catch the error and move on?).

**Comment by zepumph** [comment]
In the above commit, we added a "sub" `.eslintrc.js` file to specify a global that we are only allowing in a single wrapper. This could become a convention for how we allow sub directories to add on addition lint rules. I hope to discuss further about how we likely will only want to do with sparingly (mit Geschmack). No matter this seemed useful enough to us to commit to master before discussing.

**Comment by zepumph** [comment]
We discussed this at the dev meeting today. People were excited about having three rc files that could be extended: 
 * a base one for most things, including es5 sims
 * a node one
 * a sim specific es6 one for sims entirely in es6

We also wanted to take some time to go through globals currently defined in the main `.eslintrc.js` file and see if (a) some should be removed, and (b) if any only have one usage, and as such should be specified in a sub directory's config, similar to what was done for `Split` in `phet-io-wrappers/studio/`

The meeting coupled with the above list of next steps from https://github.com/phetsims/tasks/issues/972#issuecomment-447521519 has formulated the following checklist:
I think these are in order of what I will work on

- [ ] Create a sim specific eslint file to be extended.
- [ ] Create a README in chipper/eslint/ to describe what the three files are for, and how/when to use them.
- [ ] add `no-var` rule to `node_eslint.rc`
- [ ] convert all `.eslintrc` files to `.eslintrc.js` files. Using javascript provides a better format. So convention is: Use package.json for an entire repo, then use `.eslintrc.js` to specify overrides to one of the three rules if needed in sub directories.
- [ ] Delete `perennial/data/node` because we are not going to invest in an automated system to develop consistent config creation. It will be manual.
- [ ] Automate `not-lintable` list with a flag in `package.json` files 
- [ ] Go through globals in base config and see what can be removed, and/or factored out to sub configs.

**Comment by zepumph** [comment]
I'm not going to add `no-var` to the node rules right now, because there are 700+ usages in the repos we are linting with node rules ( mostly in aqua). I will tackle that soon though.

**Comment by zepumph** [comment]
- [ ] There are over 100 usages of `/* eslint-env node */`, but we can now specify that in the node eslint file and remove those usages when they are in node repos.

**Comment by zepumph** [comment]
> Automate not-lintable list with a flag in package.json files

I could not do this without adding package.json files to basically all of the repos, which I didn't want to do, nor did I think it was better long term. I renamed to a better name ('no-lint'). For now I think we should move on.

**Comment by zepumph** [comment]
Now the only places where we put `eslint-env node` is to override a default config that is for sim, not for node repos.

**Comment by zepumph** [comment]
Everything here has been done or has separate issues addressing it. @samreid please review.

**Comment by zepumph** [comment]
One thing I should still do:
- [ ] convert the "JSON-like" stuff in .eslintrc.js to our code conventions of javascript. For example get rid of double quotes.

**Comment by samreid** [comment]
I would even consider getting rid of quotes from keys that don't need them at all.  For example:

```js
module.exports = {
  // Use all of the default rules from eslint, unless overridden below.
  extends: 'eslint:recommended',

  // specify that this file is the root of the eslintrc tree, so eslint won't search past this file looking for a file
  // in a parent dir
  root: true,
  // The new rules, overrides, etc.
  rules: {

    // Permit console.log statements (we have a lot of them)
    // TODO: Find a way to make sure no console.log statements make it to production.  Can use the no-console rule
    // but we want to be able to use console.log during development.
    'no-console': 0,

    // specify whether backticks, double or single quotes should be used (fixable)
    quotes: [
      2,
      'single'
    ],
```

etc.

**Comment by pixelzoom** [comment]
FYI, adding this to all package.json files:

```js
  "eslintConfig": {
    "extends": "../chipper/eslint/.eslintrc.js"
  }
```

... has made it impossible to cherry pick and run `grunt lint` without checking out all dependencies for a release branch.

For example, this fails:

```
% cd balancing-chemical-equations
% git checkout 1.2
// cherry picked file(s) here
% grunt lint
Fatal error: Perennial task failed:
Error: No ESLint configuration found.
...
```

I need to get shas for all dependencies in order lint sim-specific changes.  E.g., this works:

```
% cd balancing-chemical-equations
% git checkout 1.2
% grunt checkout-shas
// cherry picked file(s) here
% grunt lint
```

Mighty inconvenient, but I guess we'll have to live with it.

**Comment by pixelzoom** [comment]
I see 128 occurrences of this in project-wide package.json files: 

```js
  "eslintConfig": {
    "extends": "../chipper/eslint/.eslintrc.js"
  }
```

Why is this needed in every sim's package.json file? For the same reason that we don't repeat "phetLibs", "preloads", etc. in every package.json, why is this default not specified in chipper/build.json?

**Comment by samreid** [comment]
This convention is required by ESLint, see https://eslint.org/docs/user-guide/configuring

**Comment by zepumph** [comment]
This is not for build, this is for our linting in requirejs mode. Each repo needs eslint configuration specified. Rather than just having a single file for all linting, the structure of the file system specifies the eslint config desired for that directory.

**Comment by zepumph** [comment]
I believe everything has been done for this issue. Further work in linked issues above. 

>Mighty inconvenient, but I guess we'll have to live with it.

@pixelzoom as for the error you pointed out, I have two thoughts.

* The chipper lint config doesn't change all the time, but if we added a lint rule that the old rc of BCE failed, then it would be reasonable to think that you would have to checkout old chipper in order to get lint to pass. To me finding a bug because some shas are on a branch and others aren't comes with the territory, though I do admit that lint wasn't failing for those cases, and not is.
2. I think I have a potential solution, though it isn't ideal. The error is because we have moved to a tree structure in eslint configs, so if the linter looks at parent directories until it finds an eslint config file, for most repos, that is in the package.json. What you can do is add `.eslintrc.js` to the directory that contains all of the phet repos, so the parent to chipper and sims and whatnot, and have its contents look like:
```js
module.exports = {
  extends: './chipper/eslint/.eslintrc.js',
};
```

Then the linter will fall back to this if no config is found in a given repo. I tested this by adding the file to my repo parent dir, and then checking out BCE 1.2. `grunt lint` is successful (though note it fails lint because of added lint rules in the past few weeks).

@pixelzoom let me know if this is something you are interested in pursuing as a workaround. Otherwise feel free to close.

**Comment by pixelzoom** [comment]
Thanks for investigating options.

I'll live with having to checkout-shas in order to cherry pick.

Closing.
