### ISSUE TITLE
add `no-var` to node lint rules

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#976]
From https://github.com/phetsims/tasks/issues/972. This code doesn't need to support ie11, and for the most part it already uses no-var anyways. We should make sure that it uses let/const correctly and consistently.

**Comment by zepumph** [comment]
I added the no-var rule to node config above, and I converted quite a few files to accomplish this. It would be good to get a review on this. For the most part it seems like it was in files that are not sim files, so it felt safe to me. Please review.

**Comment by samreid** [comment]
This rule is working as desired:

![image](https://user-images.githubusercontent.com/679486/52283695-310ae280-2920-11e9-874e-7e79da9b4dfc.png)

I reviewed the rule specification in node_eslintrc.js and sim_es6_eslintrc.js and they seem good.
