### ISSUE TITLE
estimate to port Fourier

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#978]
@ariel-phet requested a ballpark estimate to port _Fourier: Making Waves_ from Java to HTML5.  Assume that the basic layout will be the same, and only minor UI changes will be required.   Assume that we don't a 3rd-party library for charts.

My previous overview from https://github.com/phetsims/tasks/issues/354:

> **fourier**
> - lines of code: 19286
> - Unfuddle issues: 18
> - graphics: phetgraphics
> - model: Listener
> - sims: 
>   - Fourier: Making Waves (3 screens)

Deadline is Wednesday, January 23.  Earlier is better.

**Comment by pixelzoom** [comment]
Fourier is also dependent on a PhET-specific package called "charts".  It does not use JFreeChart.

**Comment by pixelzoom** [comment]
Fourier has 18 Unfuddle tickets that need to be triaged.   The only issue that is relevant to the HTML5 version is [#2152 revisit game levels](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2152?cycle=true).

**Comment by pixelzoom** [comment]
Fourier is a 3-screen sim, written by me. Implementation started in May 2005, and 1.00 was published in August 2005. The most recent version (3.06) was published in July 2011. 

The Java implementation has about twice as many lines of code as Graphing Lines (19286 vs 9866), another 3-screen sim that I wrote in Java and ported to HTML5.  Fourier has sophisticated charting needs, and PhET currently lacks an HTML5 charts package. Fourier makes extensive use of Java's `javax.sound` library, and that will need to be rewritten to use PhET's sound system. 

So I estimate that a _direct port_ of Fourier to HTML5 will take **~400 hours**, about twice as long as the Graphing Lines port (199 hours). 

Charts and sound will be the 2 biggest challenges.

**Comment by ariel-phet** [comment]
@kathy-phet here is the information for estimates of porting Fourier that we discussed. Use at your discretion to produce an estimate for the STROBE folks.

**Comment by pixelzoom** [comment]
Kathy contacted me via Slack to confirm my estimate.

Kathy Perkins  3:58 PM
Hi Chris, Natural selection was 436 hours (non PhET-iO). Your original estimate for Fourier was about 400 hours. Do these feel about the same to you now?

Chris Malley  5:19 PM
Yes. I'm optimistic that 400 hours is on the upper end. That's a bit higher than my hours for previous 3-screen sims. But Fourier has these features that will increase the cost: (1) heavy use of charts, and it's unclear whether I'll be contributing to griddle or creating sim-specific charts (I suspect some of both), (2) a game screen, which has historically been a more expensive kind of screen, and (3) integration with the new sound framework, which I haven't worked with yet.

And even though this sim is not being instrumented for PhET-iO and a11y, those aspects are impossible to ignore. They are now part of everyday PhET programming and thus contribute to increased cost.

**Comment by arouinfar** [comment]
Fourier: Making Waves was published in Oct 2021. This estimate is no longer relevant, closing.
