### ISSUE TITLE
3rd-party chart libraries

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#979]
According to @ariel-phet, some upcoming sims will need charts (Fourier, Moving Man,...)  PhET has griddle, but undertaking a full-featured chart library may not be in PhET's best interests.  So investigate 3rd-party chart libraries that meet PhET's feature and licensing needs. 

JFreeChart has been ported to JSFreeChart, see https://github.com/jfree/jsfreechart

**Comment by pixelzoom** [comment]
@ariel-phet Even if PhET finds a chart library that meets feature and licensing needs, there's no way that it will match PhET's a11y and PhET-iO requirements.  And you definitely don't want to be adding a11y and PhET-iO instrumentation to 3rd-party code. So if PhET is planning sims that have significant chart needs, then you should anticipate a significant cost to create a general chart package. 

And unfortunately, the above likely applies to 3rd-party libraries or frameworks for any need. This is another big cost of a11y and PhET-iO that I had not previously considered.

**Comment by ariel-phet** [comment]
Discussed with @kathy-phet briefly and she agreed that given our desires for both a11y and iO we will need to "roll our own" charting library. Likely as we begin to design Moving Man we will simultaneously be considering requirements for a charting library and plan to work on this library as a supporting project potentially with several developers.
