### ISSUE TITLE
Shoud "Box" suffix be lowercase everywhere?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#981]
In https://github.com/phetsims/tasks/issues/910 we decided to change CheckBox to Checkbox for consistency. We have other *Box classes, should they be renamed too? Also related to https://github.com/phetsims/sun/issues/440

ComboBox
ComboBoxDisplay
ComboBoxItem
ComboBoxItemNode
LayoutBox
AccordionBox
AlignBox

And many others in sim code. @samreid what do you think?

**Comment by jessegreenberg** [comment]
Also in https://github.com/phetsims/tasks/issues/909 ToolBox was renamed to Toolbox.

**Comment by samreid** [comment]
Wikipedia lists "Checkbox" as one word but "Combo box" as two words.  Likewise it seems like "Accordion Box" is two words, "Layout Box" is two words and "Align Box" is two words.

**Comment by samreid** [comment]
"List Box" is also listed as 2 words.

**Comment by jessegreenberg** [comment]
Got it, thanks. I was comparing against attributes in the [ARIA spec](https://www.w3.org/TR/wai-aria-1.1/), but all attributes are lowercase so that shouldn't have been used. At that link I see two cases of "List Box" in documentation.
