### ISSUE TITLE
Make sure ResetAllButton size and pointer area is OK in each sim

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#985]
In https://github.com/phetsims/scenery-phet/issues/458#issuecomment-456872033 we decided to change the default ResetAllButton radius and pointer area.  We will need to do the following additional steps:

(a) simulations that were using the default size will now have a smaller ResetAllButton, with a larger pointer area.  We will need to look through and make sure this doesn't cause any layout issue.

(b) we should iterate through simulations using a non-default layout size and see if we want to match the reset all button size to the new defaults.

Sims that use a copy of 768x504 (and hence are at the default specified by ScreenView)

- [x] acid-base-solutions
- [x] arithmetic
- [x] balancing-act
- [x] balancing-chemical-equations
- [x] balloons-and-static-electricity
- [x] color-vision
- [x] curve-fitting
- [x] example-sim
- [x] fractions-common
- [ ] friction
- [x] john-travoltage
- [x] molecules-and-light
- [ ] wave-on-a-string

Simulations that specify a different `layoutBounds: `

- [ ] area-builder 768, 464
- [ ] beers-law-lab 1100, 700
- [ ] bending-light 834, 504
- [ ] blackbody-spectrum 1024, 618 
- [ ] build-a-molecule 1100, 679
- [ ] build-an-atom 768, 464
- [ ] charges-and-fields 1024, 618
- [ ] coulombs-law 768, 464
- [x] energy-forms-and-changes 1024, 618
- [ ] energy-skate-park 834, 504
- [ ] expression-exchange 1024, 618
- [ ] faradays-law 834, 504
- [ ] forces-and-motion-basics 981, 604
- [ ] function-builder 1024, 618
- [ ] graphing-lines 1100, 700
- [ ] graphing-quadratics 1160, 700 
- [ ] gravity-force-lab-basics 768, 464
- [ ] gravity-force-lab 768, 464
- [ ] hookes-law 1024, 618
- [ ] isotopes-and-atomic-mass 768, 464
- [ ] least-squares-regression 1024, 618
- [ ] make-a-ten 1024, 618
- [ ] molarity 1100, 700
- [ ] molecule-polarity 1100, 700
- [ ] molecule-shapes 1024, 618
- [ ] neuron 834, 504
- [ ] ph-scale 1100, 700
- [ ] plinko-probability 1024, 618 
- [ ] proportion-playground 1024, 618
- [ ] reactants-products-and-leftovers 835, 504
- [ ] states-of-matter 834, 504
- [ ] sugar-and-salt-solutions 1024, 618

edit by AP: removed simulations that have no active work/relevance (ie optics lab, joist, chains)

**Comment by samreid** [comment]
Sorry for the wild goose chase, after our discussion earlier I realized what we really need to check are simulations that use the default ResetAllButton radius (not the list of simulations with non-default screen bounds).  Maybe I can print out a list of that with the help of aqua.  I'll take a look.

**Comment by samreid** [comment]
This list should be more helpful. I ran all the simulations through aqua and printed out the simulation name if it created a ResetAllButton with the default radius.  Hence they are the only ones that could have changed in https://github.com/phetsims/scenery-phet/issues/458#issuecomment-456872033

- [ ] acid-base-solutions
- [ ] area-model-algebra
- [ ] area-model-decimals
- [ ] area-model-introduction
- [ ] area-model-multiplication
- [ ] arithmetic
- [ ] balancing-chemical-equations
- [ ] balloons-and-static-electricity
- [ ] beers-law-lab
- [ ] blackbody-spectrum
- [ ] build-a-fraction
- [ ] calculus-grapher
- [ ] charges-and-fields
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-dc
- [ ] circuit-construction-kit-dc-virtual-lab
- [ ] concentration
- [ ] curve-fitting
- [ ] energy-skate-park
- [ ] energy-skate-park-basics
- [ ] equality-explorer
- [ ] equality-explorer-basics
- [ ] equality-explorer-two-variables
- [ ] estimation
- [ ] example-sim
- [ ] faradays-law
- [ ] fluid-pressure-and-flow
- [ ] fraction-matcher
- [ ] fractions-equality
- [ ] fractions-intro
- [ ] fractions-mixed-numbers
- [ ] function-builder
- [ ] function-builder-basics
- [ ] gas-properties
- [ ] gene-expression-essentials
- [ ] graphing-lines
- [ ] graphing-quadratics
- [ ] graphing-slope-intercept
- [ ] gravity-and-orbits
- [ ] gravity-force-lab
- [ ] gravity-force-lab-basics
- [ ] hookes-law
- [ ] isotopes-and-atomic-mass
- [ ] least-squares-regression
- [ ] make-a-ten
- [ ] masses-and-springs
- [ ] masses-and-springs-basics
- [ ] models-of-the-hydrogen-atom
- [ ] molarity
- [ ] molecule-polarity
- [ ] molecule-shapes
- [ ] molecule-shapes-basics
- [ ] neuron
- [ ] optics-lab
- [ ] pendulum-lab
- [ ] ph-scale
- [ ] ph-scale-basics
- [ ] plinko-probability
- [ ] projectile-motion
- [ ] proportion-playground
- [ ] reactants-products-and-leftovers
- [ ] rutherford-scattering
- [ ] scenery-phet
- [ ] simula-rasa
- [ ] unit-rates
- [ ] wave-interference
- [ ] wave-on-a-string

**Comment by samreid** [comment]
Discussion with @ariel-phet on Slack:

Ariel Paul [9:09 PM]
Also for https://github.com/phetsims/tasks/issues/985 I am finding several sims where the dilation is larger than agreed upon
Is is possible just to make every sim use the default?

Sam Reid [9:10 PM]
for the dilation, or for the radius?

Ariel Paul [9:10 PM]
Dilation definitely, radius maybe
I know that the "actual" radius will depend on layout bounds
But I think you could just force everything in code to be the default size...it will look bigger in some older sims, but that will be fine
The dilation of the touch area is what I am seeing not be consistent

Sam Reid [9:11 PM]
Can you show me an extreme case simulation so I can take a closer look?

Ariel Paul [9:12 PM]
Area Model Algebra
or BlackBody Spectrum
Looks like dilation is being overridden, and the point of this issue was mainly to get all these consistent. Making it a bit easier for touch, but minimizing ability to swipe accidently
So defaults that did not have a dilation are getting it
But defaults that had too much dilation are not getting shrunk

Sam Reid [9:34 PM]
Wow, I see what you mean about that blackbody spectrum pointer area dilation.
I’m running a program to print out all of the non-default ResetAllButton dilations.

Ariel Paul [9:35 PM]
Can we just force them all to be the 10 percent or so we decided on?
There is no reason for them to be larger, those need to be overridden

Sam Reid [9:35 PM]
We could either (a) remove it as an option and hard-code it to our new favorite value of 5.2 or (b) iterate through the offenders and remove the overrides

Ariel Paul [9:35 PM]
Or removed
I am fine (I think) with removing it as an option
it should always be place with some visual padding around it by design
and a small dilation generally makes sense for touch

Sam Reid [9:37 PM]
I think if we remove it as an option, we should at least run it past the dev team.  Someone may know of an important reason to keep it as an option, even if we override it rarely.

Ariel Paul [9:37 PM]
I am fine with a, or b
Is "b" much work?

Sam Reid [9:38 PM]
Not too much work, my code that detects offenders is already 20% done.
It discovered that Capacitor Lab Basics specifies “Non-default touchAreaDilation of 20” woot!

Ariel Paul [9:38 PM]
yeah, this was found in another issue I think

**Comment by samreid** [comment]
I've identified all of the ResetAllButton touchAreaDilation overrides and removed them.  Will commit shortly.

**Comment by samreid** [comment]
I commented on slack:

> For https://github.com/phetsims/tasks/issues/985 @ariel and I have standardized the pointerAreaDilation for the Reset All Button.  I also added a comment to the ResetAllButton that the touch area dilation has been fine tuned and should not be overriden lightly.  Commits for several repos incoming.

**Comment by samreid** [comment]
@ariel-phet I committed removal of the overrides for ResetAllButton touchAreaDilation.  What's next?

**Comment by ariel-phet** [comment]
AP self note:

unchecked in list above will need some sim specific issues (minor tweaks)

Build a fraction Reset button moves between screens, not a problem but would be a nice polish in future

**Comment by ariel-phet** [comment]
Issues made in relevant sims. Closing
