### ISSUE TITLE
Record stable SHAs for next RCs or Publications

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#986]
From yesterday's developer meeting notes:

JG: There are some changes in the wings that are potentially destabilizing to master.  Does anyone need to publish soon (and who therefore needs stable SHAs on master)?
CM: Graphing Lines 1.3.0, Graphing Slope-Intercept 1.1.0 (> Feb 4)
JO: Molecule Shapes Basics - requested in early March, would like to get done in Feb
DB&AP: Masses and Springs Basics - go to RC!
None of these are phet-io (they are mostly to get EPUB support)
None of these have keyboard nav support
AP: Capacitor Lab Basics we’re going to wait (it currently has no priority on it).

@jessegreenberg and myself reported that we are postponing some common repo work until this is complete, so we don't disturb upcoming releases too much.  I've created this issue so that we can track when things are ready.  I added assignments based on the comments.  Please unassign yourself after you have SHAs and close the issue if you are the last one.

Also, if this isn't expected to be completed in the next couple of business days, I wonder if it would be acceptable for a developer to copy/paste SHAs for each of the aforementioned sims here, then when the responsible developer is ready, they can use those shas, and @jessegreenberg and mine (and other developers) can continue work in master.

**Comment by pixelzoom** [comment]
RCs for my sims were published yesterday afternoon during dev meeting. So I'm all set.

**Comment by jonathanolson** [comment]
I branched earlier today, I'm all set.

**Comment by Denz1994** [comment]
Branch created for MASB, so I'm set. I'll reassign @samreid.

**Comment by samreid** [comment]
Thanks @jonathanolson @Denz1994 @pixelzoom, closing.
