### ISSUE TITLE
Spreadsheet Help - Need by Feb. 22nd (Friday) 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#989]
I'm working on a grant proposal, and would like someone to complete a spreadsheet of a collaborators list of co-authors. This person has a lot of co-authors!

Please take the attached spreadsheet, [Mackay_Collaborators.xlsx](https://github.com/phetsims/tasks/files/2884463/Mackay_Collaborators.xlsx) start at line 67, and list all the co-authors and their affiliations from this [webpage](https://ex-situ.lri.fr/people/mackay/) (**years 2015 to current only**). 
Note: You can open the papers and find their affiliations. Each co-author needs to be listed only once.

**Comment by ariel-phet** [comment]
@kellywurtz said should would be able to work on this task.

**Comment by emily-phet** [comment]
@ariel-phet Thanks! I think @phet-steele may have already started on this. He asked me a question on Slack earlier today.

**Comment by emily-phet** [comment]
@kellywurtz Let me know if you have any questions!

**Comment by kellywurtz** [comment]
[Mackay_Collaborators.xlsx](https://github.com/phetsims/tasks/files/2886619/Mackay_Collaborators.xlsx)

Let me know if this looks alright! I also took down the email addresses from those who had them on their paper.

**Comment by emily-phet** [comment]
Thanks @kellywurtz - meant to tell you sooner, but this was perfect! Special thanks from me, and from Wendy!
