### ISSUE TITLE
Reference formatting - need by 10am MT Feb. 28

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#991]
Need to have this list of 43 references in APA format by 10am MT Feb. 28th.
[ReferencesCited.docx](https://github.com/phetsims/tasks/files/2911807/ReferencesCited.docx)

Here are other reference lists with a lot of overlap, APA formatted.
[References.docx](https://github.com/phetsims/tasks/files/2911813/References.docx)

I need someone to copy/paste the APA formatted version of each reference into the original doc, transforming it into a more beautiful APA formatted version of the list. 

For a subset of references not in my APA formatted list, you can use google scholar to generate an APA listing for each - like this: 
Open google scholar, search for the reference title (or other identifying info), verify google scholar found the right match, click on the quotation marks ( "" ) under the google scholar match and voila - there should be the reference in APA formatting, most of the time this is pretty accurate.

**Comment by ariel-phet** [comment]
@phet-steele is on the :briefcase:

**Comment by phet-steele** [comment]
This was finished and delivered last night.
