### ISSUE TITLE
Testing for Map

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#992]
From https://github.com/phetsims/phet-info/issues/93, we would like to create a simple usage of Map and request QA to test it on all of our supported platforms.  MDN indicates it is supported, but @jbphet indicated trouble in https://github.com/phetsims/expression-exchange/issues/102.  But maybe things have changed since then.

**Comment by jessegreenberg** [comment]
I have need for Map in the above issue, I am happy to create a simple test.

**Comment by jessegreenberg** [comment]
Link to expected compatibility from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility

**Comment by jessegreenberg** [comment]
I checked in tests for Map that are driven by QUnit. Tests were mostly derived from examples or descriptions at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map. @samreid is this ready for QA to test on supported platforms?

**Comment by samreid** [comment]
I spot checked coverage in the QUnit test against https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map and it seemed pretty good.  I also ran tests on my mac/chrome and iphone/safari and all tests are passing.  I bet @jonathanolson would appreciate taking a quick look if he isn't too busy at the moment.  Otherwise I think you are good to proceed, thanks!

**Comment by jessegreenberg** [comment]
Thanks @samreid. @jonathanolson do you have time to review tests at https://github.com/phetsims/phet-core/commit/afe2dd935aeff5c072fcdd4ee973fd4f574e9317 to see if this includes all features we would want from Map before asking QA to run on supported platforms?

**Comment by jonathanolson** [comment]
It looks like enough features for QA testing to me.

**Comment by jessegreenberg** [comment]
Awesome, thanks! Ill make an issue in QA.

**Comment by jessegreenberg** [comment]
Testing results can be found in https://github.com/phetsims/QA/issues/355. Of the platforms we support the only one to have issues with the tests was IE11. Results all match the table in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility.

Everything works with Map except that in IE11:
- You cannot create a new map from an iterable
- You therefore cannot create a clone of a Map with `cloneMap = new Map( originalMap )`
- `entries()`, `keys()`, `values()` functions aren't supported.
- `0` and `-0` are treated as different keys
- `set()` returns `undefined` instead of the Map object.

**Comment by jessegreenberg** [comment]
Adding developer meeting label to decide how to proceed and whether we can use Map.

The list of IE11 issues is too long to use Map as-is. We could create our own `Map` class that uses native Map but  fixes these issues or errors loudly everywhere.

**Comment by samreid** [comment]
I'm fine to use the IE subset of Map.  I'm also fine with using the "use objects as maps" pattern which I will describe for clarity:

```js
// Map
var model = new Model();
var view = new View();
var modelToViewMap = new Map();
modelToViewMap.set(model,view);

// use objects as maps
var model = new Model();
var view = new View();
model.view = view;
```

In the latter example, `class Model`'s constructor would have `this.view=null` with documentation about how it can be assigned.  I know this is not what we learned in GOF class, but it is clear and idiomatic to JS, and seems suitable for simulation code, though not for common code.

**Comment by jessegreenberg** [comment]
We discussed during developer meeting 7/25/19. We are going to proceed with using Map in PhET code. With the list in https://github.com/phetsims/tasks/issues/992#issuecomment-507384524, we are going to add a point in the code review checklist that if you are using Map, be sure that everything works in IE11.

**Comment by jessegreenberg** [comment]
I added the item to the CRC - closing.
