### ISSUE TITLE
Add babel and phetmarks to list of repos required to build

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#993]
A google group member pointed out that we need babel and phetmarks need to be pulled.

**Comment by samreid** [comment]
@pixelzoom can you please jot down the places that need to be updated?

**Comment by pixelzoom** [comment]
Need to:

(1) Run `grunt published-README` for all published sims.

(2) Fix [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit) to indicate the new dependencies.

(3) Notify the user in https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/9QouIghG2wg that the problem has been addressed.

**Comment by jbphet** [comment]
I've made the requests changes and updates.  @pixelzoom and @samreid - feel free to check my work and/or close at your discretion.

**Comment by pixelzoom** [comment]
Looks good.   

This is not the first time that this has happened, and probably won't be the last.  Instead of having to update the `git clone` commands in the "Getting Started" sections of [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit), perhaps we should run `grunt published-README` in example-sim. Then have the "Getting Started" sections of PhET Development Overview refer to `examples-sim/README.md` for the `git clone` commands.  @jbphet thoughts?

**Comment by samreid** [comment]
Sounds like a step in the right direction to me.  How will we remember to run `grunt published-README` in example-sim when dependencies change?

**Comment by jbphet** [comment]
I agree that this sounds like a step in the right direction.  One question first: Do all sims have the same dependencies and thus need the same list of `git clone` commands?  I had made the (possibly naive) assumption that the list in the Development Overview doc was all inclusive, but the list in each individual sim's readme file had the actual dependencies of the sim, and could be a subset.  So, for instance, if there was no usage of `twixt` in the sim, it wouldn't be on the "clone list".  

To test this theory, I just looked at the dependencies for `charges-and-fields`, and it doesn't include `twixt`, `vegas`, or `vibe` whereas `expression-exchange` includes all of those.  My guess would be that `example-sim` would be missing some too (as of right now, it doesn't have a published readme file).  So maybe what we should do is point to the readme file to the sim in which the user is interested.

**Comment by pixelzoom** [comment]
> Do all sims have the same dependencies and thus need the same list of git clone commands? 

No, all sims do not have the same dependencies.   The core dependencies are in `chippper/build.json`.  Additional dependencies are described in the "phetLibs" field of `package.json`.  

The list of `git clone` commands in README.md is generated for that sims, and is ground truth. 

> I had made the (possibly naive) assumption that the list in the Development Overview doc was all inclusive,

The description that doc is for example-sim, and should therefore should match example-sim's dependencies.  Which is exactly what is shown in example-sim/README.md.

**Comment by jbphet** [comment]
> The description in the Development Overview doc is for example-sim, and should therefore match example-sim's dependencies. Which is exactly what is shown in example-sim/README.md.

Got it, thanks for the clarification.

I just looked at the main example-sim GitHub page at https://github.com/phetsims/example-sim and the README at https://github.com/phetsims/example-sim/blob/master/README.md, and it is the unpublished version, which does not list dependencies.  If we want to use this approach, we should update to the published readme.  Will that work okay for an unpublished sim (I think it grabs screenshot icons, and I'm not sure if they're around), and are y'all okay with updating it even though it technically isn't a published sim?

**Comment by phet-steele** [comment]
Whatever all has changed, and whatever will continue to change, don't let me/yourself forget to also change the .md for the Development Overview doc in phetsims/phet-info/issues/94. FYI, that issue has been pretty much done for awhile, but I still wanted to make sure links worked and I had one TODO to add an image. It's probably totally maybe perhaps ready for use.

**Comment by samreid** [comment]
> are y'all okay with updating it even though it technically isn't a published sim?

I believe @pixelzoom suggested this in https://github.com/phetsims/tasks/issues/993#issuecomment-475900890.  I'm OK with the idea and not aware of any problems it could cause.  It also crossed my mind that we could use an actual published simple simulation (like faradays-law) in place of example-sim, but that has disadvantages too.

**Comment by pixelzoom** [comment]
>  It also crossed my mind that we could use an actual published simple simulation (like faradays-law) in place of example-sim, but that has disadvantages too.

I don't think we want anything more complicated that example-sim.  The purpose of the example is to provide a good starting place for understanding how a PhET sim is architected (especially the use of MVC). And even example-sim has proven to be a bit complicated, and probably requires more scaffolding/documentation.

**Comment by pixelzoom** [comment]
`grunt published-README` isn't appropriate for example-sim.  It doesn't have a page on the PhET site, it doesn't have screenshots, etc.  This is taking more time than anticipated, so I think we should just leave this as is, with the `git clone` commands duplicated in the Development Overview doc.  @jbphet @samreid feel free to close if you agree.

**Comment by samreid** [comment]
I agree let's keep using example-sim and not mark it as a published sim. Also a reminder for @jbphet to check on links as requested in https://github.com/phetsims/tasks/issues/993#issuecomment-477316471 before closing.

**Comment by jbphet** [comment]
@pixelzoom and @samreid - sounds like a plan, we'll leave it as is for now.

@phet-steele - I just took a look at the list of `git clone` commands in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md, and it appears that `babel` and `phetmarks` have already been added as dependencies.  Assigning to you to double check that all is copacetic with this and, if so, please close this issue.

**Comment by phet-steele** [comment]
> Assigning to you to double check that all is copacetic with this and, if so, please close this issue.

The changes were simple and minimal. Miniple? Thanks @jbphet.
