### ISSUE TITLE
Graphic Design work for Chart - Needed by April 25th

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#995]
We have a data set we would like to include in a manuscript as a chart. We need some help designing the chart. Here's some info from Brianna - who is leading the manuscript.

> I had a hard time finding something that I really liked (on google) -- but here's one [image below]that might get at it. Mostly, I want it to be a row/person/sim, and for there to be 2 colors + a white/gray scale to represent the breaks. I'd be fine without color if there were three easily differentiable black and white patterns.  

>The data is included in the excel.

![image](https://user-images.githubusercontent.com/5109055/55832858-17cb1180-5adc-11e9-8146-2e03f4f30e12.png)
[Data in this spreadsheet: for figure.xlsx](https://github.com/phetsims/tasks/files/3060870/for.figure.xlsx)

This will likely take a few iterations, and needs to be finalized by April 25th.

**Comment by ariel-phet** [comment]
@emily-phet unfortunately, I don't think have anyone to recommend at the moment for this work. Dave Underwood has officially retired, and unfortunately Kelly is swamped until the NSF video showcase is complete. This might fall within @clmccutchan wheelhouse, but not sure she does infographic type work.

**Comment by emily-phet** [comment]
@cimccutchan Thanks! @amanda-phet drafted up something really quick a few days ago, and it looks pretty close already. I'm checking in with her about whether or not she feels she'd have the time to complete and finalize the draft. I'll reach out to you if it seems like she wouldn't be able to continue.

**Comment by amanda-phet** [comment]
@emily-phet and Brianna, here are two ideas. These are missing time stamps, colors have not been verified for color-blindness and for b&w printing, and these are certainly far from pixel-polished. However I wanted to share progress as far as organizing the information goes. 

Option 1, separates data by whether the sim was used first or second (my preference). This makes it easier to compare overall how sims were used when it was the first time vs. the second time. 
![image](https://user-images.githubusercontent.com/7852916/56162668-cf9f6980-5f89-11e9-9bd7-42c032838dd2.png)


Option 2, separates data by sim. This makes it easier to compare how a specific sim was used when it was someone's first time vs. second time. 
![image](https://user-images.githubusercontent.com/7852916/56162684-d75f0e00-5f89-11e9-8219-67003060678c.png)

Another thought could be to put the data into 4 quadrants, so you can compare vertically or horizontally. (This was quickly done while posting, but there would be labels on the y-axis.) 

Option 1b, 
![image](https://user-images.githubusercontent.com/7852916/56163359-5acd2f00-5f8b-11e9-9c5e-c15c51f072b0.png)


Option 2b, 
![image](https://user-images.githubusercontent.com/7852916/56163278-278aa000-5f8b-11e9-967c-e441b685bb16.png)

Let me know your thoughts! Once you have a preferred layout, we can finalize the appearance.

**Comment by briannatomlinson** [comment]
I think that I like 1b or 2b better, in general -- seeing it more split up makes comparisons across a bit easier? 

I don't know that I have a huge preference between them, but maybe 1b would be a bit better? So far, the paper is structured so that we talk about first time sim use then differences across their second-time sim use, and any patterns/changes between when that's OL vs. RIAW.

I'm hoping for some input from @emily-phet or even Bruce

**Comment by amanda-phet** [comment]
I prefer option 1 myself. Having all data sets stacked makes comparisons easier than looking across, and will make it easier to indicate time stamps. The color coding can orient you if you are wanting to compare sims, and having the first on top helps orient first uses vs second uses.

**Comment by briannatomlinson** [comment]
So everyone can see the whole conversation, here's the note/comment from Bruce (my advisor):
"I like 1b the best. I think that the time dimension (first used, second used) is easiest for people to grok, and so it's a good way to lay out the quadrants (left/right). 2b makes you do some mental gymnastics to think about what was used first, what was used second, etc. Another possible layout would be to start with 1b, keep the color=simulation mapping, and then vertical, sort the participants 1-8; that is, align the participants' first and second experience, so P1 blue (ohm's Law) is followed on the same line by P1 orange (RIAW). That would show the subject-by subject data...though I'm not sure if it supports the story as well."

I get what you mean about option 1, and it would make the labels for the time scale a little easier to read (since it would generally be a bit larger)

I'll talk with @emily-phet in our meeting today & update you with our final choice!

**Comment by amanda-phet** [comment]
Quickly, here is what it could look like keeping each row consistent with one participant. Let's call this 1c. 
![image](https://user-images.githubusercontent.com/7852916/56228456-1dbd7700-6035-11e9-8d0b-a743d2a977b4.png)


Sorting by 1-8 could get messy, but I'm happy to mock that up as well.

**Comment by briannatomlinson** [comment]
Yeah, I think sorting 1-8 totally would be way too much, to be honest

**Comment by briannatomlinson** [comment]
Ok! So we had lots of discussion about these images. It seems that: option 1 with all 4 lined up might be easiest to read. Can we use this one moving forward?

Thanks for all of your work on these! It's made us have some interesting discussions about the paper/what we're trying to convey/

Would it be possible to:
- try option 1 with a faint gray vertical grid system that runs through across all of the blocks (except for the labels?) to make it a bit easier to scaffold comparisons
- see it with time stamps
- add the black line (end of session) + white block to the legend
- compare a version with and without labels like "P1A" (e.g., for "P1's Ohm's Law" row) and "P1B" (e.g., for "P1's RIAW" row) <-- I'm not sure how well this will work out, but was hoping to see

Happy to talk if any of these don't make sense

**Comment by amanda-phet** [comment]
Option 1, in four variants. All have the P1A, etc. labels, but those can be reverted. 

A. With grid lines. It's pretty busy, so I'm also including an option with no hatches for the description navigation. 

![image](https://user-images.githubusercontent.com/7852916/56302593-59207a00-60f7-11e9-94e1-2ff8c9bfec03.png)

![image](https://user-images.githubusercontent.com/7852916/56302615-62a9e200-60f7-11e9-9a2a-433580176183.png)

B. has grid lines only at the minutes
![image](https://user-images.githubusercontent.com/7852916/56302636-6e95a400-60f7-11e9-8ec3-e722ee78d86a.png)

C. has no grid lines
![image](https://user-images.githubusercontent.com/7852916/56302654-76554880-60f7-11e9-9966-513a4082e6c6.png)

**Comment by briannatomlinson** [comment]
Thanks for all of these!!

I think I would prefer B (with the minute grid lines) but without the other labels on the participant IDs (I think keeping them at a more simple "P1" would be best)

@emily-phet -- what do you think??

**Comment by emily-phet** [comment]
I like (B) as well, also without the additional labels on the participant IDs (so P1, P2, etc. and not P1A, P2A).

**Comment by ariel-phet** [comment]
Deadline has passed, closing
