### ISSUE TITLE
Modify scenes to be wider

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#997]
Related to the scenes created in #951 

We'd like to use the scenes found here (https://drive.google.com/drive/u/0/folders/1ZwO6UgHtgKmT7KXjiZAWK2aq4K-TQVUs) like the skatepark, classroom, etc. as background images for a new website header design. 

Here is an example of how we will use them: 
![image](https://user-images.githubusercontent.com/7852916/55910901-c0d94100-5b9c-11e9-8605-5b25784707f4.png)

However, they need to be significantly wider to be usable! When I used the image in this mockup, I had to zoom so far in that you can't even see that this is at a skate park. 

If it's easier to instead create new images, that's another option... so we could use a simple solid colored background with a few elements from these scenes or even elements from sims, but we should talk first about our needs and the look we are going for.

**Comment by megan-phet** [comment]
<img width="682" alt="Screen Shot 2019-06-05 at 12 42 49 PM" src="https://user-images.githubusercontent.com/40698031/58981401-8e5c5680-878f-11e9-9e4e-a9c9e2fb378c.png">

**Comment by megan-phet** [comment]
<img width="1046" alt="Screen Shot 2019-06-05 at 12 49 30 PM" src="https://user-images.githubusercontent.com/40698031/58981850-6de0cc00-8790-11e9-89b5-ae2e43d4a0dc.png">

**Comment by amanda-phet** [comment]
Thanks @megan-phet , we have re-thought the direction of these banners and will be making new artwork instead of trying to re-use some of the older stuff.
