### ISSUE TITLE
replace Array.includes with _.includes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#998]
Over in https://github.com/phetsims/scenery-phet/issues/493, @samreid determined that `Array.includes` is undefined on IE11, and fixed a problem in NumberControl by replacing `Array.includes` with `_.includes`.    I was assigned to review, and discovered many more usages of `Array.includes` in PhET code, including core classes like Screen, Enumeration, ComboBox,... 

How were these passing QA?

Should they be replaced?

@ariel-phet FYI.

**Comment by pixelzoom** [comment]
Should we have a lint rule that prevents us from using `Array.includes`?  Does eslint already have such a rule?

In the commits above, I fixed the cases that I felt confident touching.  Here are some remaining cases that need to be examined.  We can probably skip some of these if they don't involve a browser.   @jbphet the ones in tambo and rosetta probably need to be addressed.

- [ ] tambo/soundManager.js
```js
317 _.values( SoundLevelEnum ).includes( options.sonificationLevel ),
543 _.values( SoundLevelEnum ).includes( sonificationLevel ),
```

- [ ] rosetta/translate-sim.js
266 const tags = openTags.filter( tag => closedTags.includes( tag ) );

- [ ] installer-builder/BuildManager.js
117 const validateAllLocales= locales.includes('*');

- [ ] Multiple occurrences in chipper.

- [ ] Multiple occurrences in perennial.

**Comment by pixelzoom** [comment]
I asked why these weren't being caught in QA.  In https://github.com/phetsims/scenery-phet/issues/493#issuecomment-487799669, @samreid said:

> For example, Screen.js usage of `Array.includes` is only in an assertion.

So does that mean that no one is testing on IE with assertions enabled? Why?

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to prioritize and assign.  Looks like the "must do" ones are for @jbphet, in tambo and rosetta.

**Comment by ariel-phet** [comment]
@KatieWoe isn't there something about IE where we had to give up running with assertions enabled?

**Comment by samreid** [comment]
We had similar discussion about `Array.prototype.find` in https://github.com/phetsims/tasks/issues/932.  In that issue, we decided to add a code review item under the "IE11" section rather than adding a lint rule or erroring "polyfill".

**Comment by KatieWoe** [comment]
There is a problem with running assertions in IE.  It looks something like this in the console when you try to run the debug version.
![fails](https://user-images.githubusercontent.com/41024075/56969577-aa326400-6b22-11e9-9c46-7bf3e0a2ad31.png)

**Comment by jbphet** [comment]
This isn't a problem for the rosetta code, since the portion identified only runs on the server.  I've left this as is because I think it reads better, but I can change it if we decide to add a lint rule.

I've changed the usages in `soundManager` to use the underscore version.  The reason it was never a problem in IE is that the `includes` calls were only used in assert statements, which are stripped out at build time, and we only test built versions of sims on IE.  So, in reality, it would never have been a problem assuming nothing major changes about the build process, but I changed the code anyway.

**Comment by KatieWoe** [comment]
Further notes.  When testing rcs we generally only run the debug version through fuzz on chrome on one platform.  RC's that aren't the debug version do not have assertions in them.

**Comment by ariel-phet** [comment]
@pixelzoom see @jbphet comment above, is this something we should bring to dev meeting, I am a little unclear if further action is needed.

**Comment by pixelzoom** [comment]
Sounds like all work is done, no further action needed.
