### ISSUE TITLE
Data-driven social media sim posts

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#999]
It would be beneficial to get a student worker to go through our Yotta stats and identify if there are times of the year for peak usage of sims. Some sims we know are fairly steady use during the school year (such as CCK), However, others historically have more "seasonal" usage.

As the season for popular sims are approaching we could advertise these sims more on social media. I do this process a bit anecdotally know -- so for instance if I notice a couple of teachers organically posting about a particular sim, I will make a post around that sim. However, we could be much more strategic about this practice.

**Comment by ariel-phet** [comment]
@KatieWoe this would be a fairly helpful background task for QA (or yourself)

Basically it would be useful to analyze our stats for several various trends. Perhaps starting with a spread sheet that notes peak usage times for something like our 30 most popular HTML5 sims

We could also interrogate statistics for other trends in the future, like understanding if there are certain international usage trends, or if certain subject areas seem to be more popular in certain locales (like perhaps in Spanish, physics is by far our most popular subject area and we should be pushing our chemistry sims more in that locale or some such).

@oliver-phet maybe you have some other thoughts about useful data for stats that could help drive marketing efforts?

**Comment by KatieWoe** [comment]
This spreadsheet was made with data from 2017, 2018, and 2019: https://docs.google.com/spreadsheets/d/1NzSOldWr2ewmj-YmY38rfyDF6Tjd-sx_yyRhpNrizMI/edit?usp=sharing
The cells have the number of the two months that saw the most traffic that year for that sim. The cell is red if the data is incomplete and grey if there is no data. The sims are marked green if there is complete for all three years. They are marked yellow if there are two complete years of data. They are marked orange if there is one complete year of data. They are marked red if they came out in 2019. Will be working next on organizing sims by months most used.

**Comment by KatieWoe** [comment]
The second sheet is finished. It is organized by month and contains sims that are listed on the first page with that month if it included a year's worth of data. If the sim is Green, that month was in the top 2 used for 3 years. If it is yellow, the month was in the top 2 used for 2 years. If it is orange, the month was in the top 2 used for 1 year.

**Comment by KatieWoe** [comment]
New page ranking sim usage in each month of 2019..
